### ISSUE TITLE
Single player campaign - No connection route from first biome to second biome for seed EigAFNfV

### ISSUE THREAD

**Issue by feru7** [Regalis11/Barotrauma#10047]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The first biome has no traversable route connecting it to the second biome for the campaign seed EigAFNfV. The outpost where the sub is docked on the screenshot had the officer unlocking access to the second biome.

Only mods used were custom modified submarines.

![map](https://user-images.githubusercontent.com/96304666/194903072-d194d362-3218-433a-8d0f-6adb5aea88fe.jpg)

### Reproduction steps

Start a campaign with the seed: EigAFNfV

Or try the attached save file where the bug occured.

[Save.zip](https://github.com/Regalis11/Barotrauma/files/9747225/Save.zip)

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This seemed to be a rare edge case in the map generation:
![image](https://user-images.githubusercontent.com/14351070/195025634-1b53fad4-0507-4ccc-babc-38e031d32f2f.png)

Basically what happened here was that all the connections to Apep (the 1st location in the next biome) happened to lead back to the previous biome. The way the map generator creates those gates between biomes was to remove all the connections between biomes, except that specific locked one, and in this case it made Apep a dead-end. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7dc0f3a992d1496a658e9b4850f733c10bd0c00c
