### ISSUE TITLE
Reactor gauges bands do not revert to automatic control values

### ISSUE THREAD

**Issue by kgiergiel** [Regalis11/Barotrauma#10070]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Expanded (optimal area) gauges, after being turned on by going to manual control of a reactor, seem to stay on after going back to automatic control.

### Reproduction steps

1/ Enter reactor UI
2/ Disable Automatic Control 
3/ Enable Automatic Control

![Screenshot from 2022-10-13 08-51-34](https://user-images.githubusercontent.com/115675388/195476185-cdb8d0ab-6e2d-4550-bfd5-d7ffa8c9fa87.png)
![Screenshot from 2022-10-13 08-51-38](https://user-images.githubusercontent.com/115675388/195476199-949f4a26-f1ea-4692-8326-39050c0130c4.png)
![Screenshot from 2022-10-13 08-51-40](https://user-images.githubusercontent.com/115675388/195476203-f247cc77-ca59-4c7d-8ef9-2b9fc71bc573.png)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment]
Both seem to be rather static, but I don't think toggling auto control has anything to do with it. Tbh I'm not sure if they work as intended or not. Could @Regalis11 you check them out?

**Comment by Regalis11** [comment]
> Both seem to be rather static, but I don't think toggling auto control has anything to do with it

The size of the optimal sectors depends on the electrical skill of the character operating the reactor. 

Even though making the size of the sectors persist after turning autocontrol on probably wasn't an intentional design choice (it's been so long I'm not sure), I don't think it's necessarily a bad thing: it just means the it works slightly more efficiently if the last person who operated it was an engineer, which in my opinion makes sense both in-world (maybe the engineer knows the best which knobs to turn for optimal autocontrol performance) and gameplay-wise.
