### ISSUE TITLE
Wrecked captain's IDs have the wrong access.

### ISSUE THREAD

**Issue by datorangebottle** [Regalis11/Barotrauma#10078]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Possibly related to [this issue](https://github.com/Regalis11/Barotrauma/issues/9156) , but i'm experiencing it in vanilla solo and multiplayer campaigns.

![image](https://user-images.githubusercontent.com/46474741/195770084-c298fa9e-0661-4038-b8b1-68a5fdcb7c77.png)
1. Start a campaign.
2. Find a wreck or do a wreck mission.
3. Dive in and grab a captain's ID from a corpse.
4. Try to open the armory door and become unable to.
Save file attached if it's relevant. I had a mission to loot the wreck and it was full of mudraptors. There were also multiple instances of the ship's logs, but only one of them counted the mission as completed.
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/9782812/Save.0.zip)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by PokkeTigrex** [comment]
I think this has been an issue for every locked secure container that wasn't a pirate one. **Wreck1** is actually a much better example, where the guaranteed id card in the broken vent no longer works on the secure cabinet it was supposed to open. Even bandit outposts where at least one of the ID cards work in the armory refuses to work anymore. 
My guess is that all the container tags and id clearance might have been messed up when that was updated, since one of the subs I had to update, I had to rename id tags for containers as they no longer gave access to anyone.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/40bb442569d407080318a507a5a584b36a63abd9

**Comment by itchyOwl** [comment]
The corpse spawn points don't need the tags anymore since Regalis11/Barotrauma-development@5dbab8d and   Regalis11/Barotrauma-development@04520ed, because the tags are defined in the corpse prefabs, and it seems to work still:

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/287c15a3-d913-41ee-bf86-f4230f20b581)

So I doubt  the fix works. Looking into what's up with it.

**Comment by itchyOwl** [comment]
Found out an issue in the code, where corpses spawned from a spawn point without a job definition sometimes had a wrong job, resulting in their idcard (and other items) being selected from a wrong set. Fixed in Regalis11/Barotrauma-development@7516997 (bugfixes).

Also fixed one door in Kastrull_wrecked not being accessible with any id card found in the wreck: Regalis11/Barotrauma-development@3cc5bc5 (dev).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
