### ISSUE TITLE
cosine component go bruh

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10145]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Cosine component has the funny float moment when input is 90 or 270

### Reproduction steps

![image](https://user-images.githubusercontent.com/5103517/197411371-9b82c3e4-2f1d-4b54-9369-2066f2dce404.png)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
Is this a bug? Is there anything that can not take values in exponential format? Engines, arithmetic, function components all work correctly.

**Comment by jcx1991911** [comment]
> Cosine component
It should output 0 while input 90 and 270

**Comment by jcx1991911** [comment]
> Is this a bug? Is there anything that can not take values in exponential format? Engines, arithmetic, function components all work correctly.

Cosine component should output 0 while input 90 and 270

**Comment by mygamingaccount** [comment]
Is there anything in the game that does not interpret 4.4E-8 at 0?

**Comment by mygamingaccount** [comment]
Is there anything in the game that does not interpret -4.4E-8 as 0?

**Comment by Regalis11** [comment]
> Cosine component should output 0 while input 90 and 270

-4.4E-8 is for all intents and purposes 0. This is a limitation of floating point numbers which have a limited accuracy, and working around it would not be trivial - and in my opinion not necessary either, since the inaccuracies are so minuscule I can't think of any kind of a circuit where it'd matter (unless you're maybe comparing the value against the string "0", but that's not something you should be doing anyway).
