### ISSUE TITLE
[Dev Version] Monster Spook

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1015]
So Developers, I've changed my mind, the textures are awesome, now this game is spooky as hell.

But wouldn't a little bit more spook be welcome?

This is why  I introduce, spook sound 2.0!

Whenever you see a huge ass monster on the sonar, wouldn't you panic? So I introduce, when seeing a monster on the sonar for the first time (one spook sound per first seeing of each monster or one spook sound if there a couple at once) a spook sound is played! This is not limited to the sonar however, as if you haven't checked the sonar and never triggered the spook sound for the monster, you can trigger it in other ways! By checking the guns and seeing it up close, by seeing one through the window, seeing one through a broken dent, a spook sound will be played!

What would be the spook sound you may ask?

Well the spook sound is already in your very own assets!

Introducing containment breach spook sound.

https://www.youtube.com/watch?v=I2M53xvV0gM

Also some sound effects for the player character screaming as a spook sound occurs would be nice.

Thanks in advance, AbominationBanisher

**Comment by AbominationBanisher** [comment]
Bump, I'm still strongly advocating for this idea. Let's get some traction on this going, I personally think this idea would be great in application!

**Comment by deadmomo69** [comment]
Personally, I don't think this is a good idea because for me- the atmosphere can make it the scariest, it feels like a cheap jumpscare to play a sound upon sight of a creature.
I think the sub creaking, or hearing some distant sound while in the sub is better, because it makes you think: "Is the sub being attacked, or is the hull just creaking?", or "Is that a monster coming, or just some random sound?" Sudden noises break the atmosphere and ambience.

**Comment by NilanthAnimosus** [comment]
Personally I don't think we should have random sound ques of a creature appearing or coming into view, or if you do have that, ONLY for the captain.

but this ruins another thing: A perpetual sense of horror to not knowing what a thing is, I've seen submarine crews empty multiple boxes of coilgun ammo into a moving chunk of ice, without a sound que a captain (or whole team) will probably just shrug it off, while also using it to get on guns instead of being caught unaware.

The fun of this game is disaster, the unknown factor lends to the spook factor to begin with, getting spook noises is like the equivilant of comedy laugh tracks, its not going to make the game any spookier, and simply gives a mechanic to make the game easier by distinguishing a sonar target as a fish or part of the level.

I am completely against this, the sub creaking is a better idea, if there are ques for this, it has to be the ones you hear without fish nearby too. but then a creature attacking the hull makes those sounds of hull creaking (Just their not very powerful to dent/damage the hull IE. crawlers and mudraptors).

Still, their all not preferable to me. nothing should play to the sight of a creature, if you want to keep players on edge you may as well just play (without fish nearby) random hull creaking as if the hull was attacked, and maybe give some dialogue to AI's about the subs random creaking and how it could be some loose rock / chunk of ice the sub hit : P
