### ISSUE TITLE
Automatick Re-Docking to station

### ISSUE THREAD

**Issue by SalzLordJoe** [Regalis11/Barotrauma#10175]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If i try to start a mission in Campaign mode, sometimes the Ship will Dock with the Station again making us fail the mission(s).
This started happening a few times, but has now progressed to be every time.

We are currently using the Dugong.
We tried a lot of fooling around in the wire system to get the auto dock removed wich didnt work.

At the moment we turn the Reactor off and flood our ship by using batteries connected to pumps.

Is there a better/ not manual way not to fail at most of the missions?

With kind regards
SalzLordJoe

### Reproduction steps

1. Start Multiplayer Campaign with the Dugong
2. Start Missions
3. Start the Reactor
4. Redock with the Station automatically

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

There should be no autodocking logic in Dugong, so I'm not quite sure what could be causing this. I wonder if it's possible someone tampered with the wiring of the docking port? If you could send us the save file you're using, we could also take a shot at diagnosing the issue there directly. Note that you need to .zip the save file to attach it here, since GitHub doesn't support the .save file extension.

**Comment by Regalis11** [comment]
No known steps to repro, closing
