### ISSUE TITLE
Water speed through docking port is extremely low

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10190]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Low speed of water's flow through docking port if the water rises up.
If the shuttle is docked from above , the water is barely seeping through the docking port into a shuttles or submarines.
In normal situstion the water level rises correctly.

Test chamber: [_Test_DockingPort-UpWater.zip](https://github.com/Regalis11/Barotrauma/files/9896183/_Test_DockingPort-UpWater.zip)

### Reproduction steps

Flooding Up:

https://user-images.githubusercontent.com/93348499/198886910-d2365923-edfd-4560-a274-95aa47364330.mp4

Flooding Down (for comparison) - everything works:

https://user-images.githubusercontent.com/93348499/198887028-02aa8a61-abb2-45bf-a155-cc998808b18b.mp4

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This happens due to the water having to flow through 3 gaps to get to the hull on the left, but just through one to get to the one on the right. Assuming the gaps are the same size (which I don't think we can know looking at it from a 2D perspective - the opening through the hatch could be more narrow on the z-axis), I agree this is somewhat unrealistic. But considering it doesn't really cause any issues in practice (the water level does eventually even out as it should), I don't think we'll be addressing this.

**Comment by MaaiG** [comment]
I’m just saying IMHO, in the second video, the water does exactly the same thing, but it’s flowing down and there’s no problem.
It seems to me that the difference is only in the direction of the water flow. The gaps are the same and all other conditions are identical. Sub file was attached ...I just don’t understand the difference between the upper and lower docking ports...

**Comment by Regalis11** [comment]
Yeah, the water flow logic works a little differently when the water is flowing up, as the pressure is basically pushing the water up and there's a difference in how the pressure equalizes through multiple gaps vs one gap.
