### ISSUE TITLE
Tutorial outpost can spawn in place of an abandoned outpost

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#10215]
Occured on feature/bugfixes.

![Screenshot_1.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/677d03cd-431c-47a0-b75c-fb924b750438)

Save file:
[https://app.zenhub.com/files/175046454/6c4566c1-e4ab-4a55-be9f-02bcedf294a6/download](https://app.zenhub.com/files/175046454/6c4566c1-e4ab-4a55-be9f-02bcedf294a6/download)

**Comment by itchyOwl** [comment]
Seems to happen always(?). I deleted the tutorial outposts, then started a new game and triggered an outpost that was loaded properly (or so I first thought). When I discarded the local changes, it seems to override the previously properly loaded outpost with a tutorial outpost. Deleting the tutorial outposts again "fixes" the issue, also on the save file linked above. However, it still doesn't load the proper abandoned outpost with the modules, instead I now always seem to get Outpost2.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a485222f6fa4e737d89fe5186185bebe044deb5a (prevent tutorial outposts from being used as the fallback if generating the outpost fails) https://github.com/Regalis11/Barotrauma-development/commit/2c01fc0926c46ff15b6a979896b634e231d1fec1 (fixed outpost generation failing)
