### ISSUE TITLE
[dev] Playing guitar causes dicsonnect.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#1021]
- [+ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing guitar in multiplayer as a client for about 15 seconds causes a "steam authentication failure" and the game returns to main menu.
**Steps To Reproduce**
Play the guitar for about fifteen seconds, while being a client on someone else's server.

**Version**
Current steam version, played on windows 7.

**Additional information**
It was kinda funny though, a guitar of death.

**Comment by Regalis11** [comment]
Unfortunately I wasn't able to reproduce this. I have a feeling it could be an issue unrelated to the guitar (i.e. you just happened to get disconnected while you were playing the guitar). Or does it happen consistently?

**Comment by NilanthAnimosus** [comment]
I've never seen it while hosting, and seen many use guitars. I don't strictly think its the guitar as much as any other number of factors.

I have however seen AFK kicks occur while players are repairing damaged components or doing something-ish while standing still however. but then that would have been noticed by a popup.

I've seen no evidence yet as a server host a guitar could cause any issues, I did have a sound related crash however as the server host one game, and went over that with juan to find it was a peculiar issue with .Clone() on arrays. but also don't feel that is likely to be it due to how extremely infrequently that occurs to crash clients or servers.

**Comment by Waagher** [comment]
Since it hasn't happened to me or, to my knowlege, to anyone else again, it can be reasonably assumed to be a one-time incident.
