### ISSUE TITLE
Curved magazine looks weird when inserted into a smg

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10310]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Curved magazine looks weird when inserted into a smg or deadeye.
Considering their structure are similar to Kriss Vector in reality, the smg magazine's texture should be changed to a straight one like a mod below.
![KrissVector](https://user-images.githubusercontent.com/99462070/201239298-0d35f0ee-6553-4d1c-913b-16f1991dca23.png)

### Reproduction steps

1. equip a smg or deadeye
2. load a magazine

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I probably don't know enough about firearms to see the issue myself. Why do you feel it looks weird? If the mag well is straight like in you pic, I can see how a curved magazine would look strange, but in the case of the SMG and Deadeye Carbine, you can't see the shape of the mag well.

**Comment by BiffW** [comment]
![smg mag well](https://user-images.githubusercontent.com/99462070/201305088-8a665379-b584-450c-8b50-cd2cdd8d7f96.png)
The part in red circle clearly marks the shape of mag well, which is similar to that of Kriss Vector.

**Comment by MaaiG** [comment]
> The part in red circle clearly marks the shape of mag well

I agree with that.

But...
From the point of view of the gunsmith, this submachine gun makes no sense. It is made of two parts of different types of weapons!
In general, it appears that this type of weapon is [**bullpup**](https://en.wikipedia.org/wiki/Bullpup).
![Image 001_14-45](https://user-images.githubusercontent.com/93348499/201336559-954d67f7-1213-4a45-854e-48920af30c6f.png)
His large butt proves it - otherwise his size makes no sense.
However, there are a number of errors. If the curved magazine should be inserted into the butt - the shutter frame must be in the butt.
![Image 001_15-03](https://user-images.githubusercontent.com/93348499/201336994-c9a1d699-8bdd-45a2-bb5f-3a1523067ce3.png)
However, the front end of the weapon tells us that these are [**Vector-type**](https://en.wikipedia.org/wiki/KRISS_Vector) weapons with pistol-type ammunition. That weapons has a straight magazine!
![Image 001_15-03](https://user-images.githubusercontent.com/93348499/201337674-c8434b00-2d4f-4aa9-9077-ac3da257d638.png)

**Comment by IiroEnges** [comment]
Pushed into wip-additions branch

**Comment by Regalis11** [comment]
Cherry-picked the commit to [talent-fixes-4](https://github.com/Regalis11/Barotrauma-development/commit/0effc0f) (doesn't relate to the factions or endgame, so it shouldn't be in wip).

**Comment by Regalis11** [comment]
The magazine sprite seemed to be offset from the collider and the rotation was a bit off, fixed in https://github.com/Regalis11/Barotrauma-development/commit/9ea30a6a3b9481c7654cf275c317509f2aca0f57

**Comment by BiffW** [comment]
Still need some adjustments for Machine Pistol and Dead Eye.
![{V33DU3Q1{6IJU7MQQW)L_A](https://user-images.githubusercontent.com/99462070/204069241-4f2fc046-0372-4b35-8cae-7bcefa62c3e7.png)
![%XNY5X`F$N48JDO}9TG`CGQ](https://user-images.githubusercontent.com/99462070/204069245-33958697-d563-4ada-bf43-54fac2eb1435.png)

**Comment by Rokvach** [comment]
Moving to Team1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5302d0c9681777776c24a042adf876cf1d89d34

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
