### ISSUE TITLE
You can place more than 2 portable pumps on some custom subs

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10341]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The talent says the maximum amount of pumps is 2, but you can place as many pumps as you want manually on some subs, case in point:
![image](https://user-images.githubusercontent.com/73229309/201453881-cc023b8f-3daf-48f0-83b7-64e3a8902790.png)

I've tested on other subs and there I couldnt place more than 2. 
No idea what causes this, here's the "sub" in question:

[A Testbox.zip](https://github.com/Regalis11/Barotrauma/files/9993952/A.Testbox.zip)

### Version

Faction/endgame test branch

**Comment by Regalis11** [comment]
It seems the issue was that we used the "attach target" (the structure or level wall the item is attached to) to determine which submarine it's in, so if there was no background wall or other item behind it, the per-submarine limit got ignored. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad70038925755f8fa1a7f573affccad576ea420c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
