### ISSUE TITLE
[Dev Version] Robots are still morons....

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1034]
The captain can't steer, the ship only moves when I myself manually steer as an engineer, the security officer cowered in the ballast as a manta that broke into our ship ravaged the crew, and the mechanic got stuck on a ladder and couldn't fix a tiny fucking breach. Had to micromanage each of them, and even then I still died.

**Comment by itchyOwl** [comment]
These issues are known. The AI will be reworked at some point, don't worry ;)

**Comment by etet2** [comment]
i think there should be more priority put into ai rework, right now singleplayer is not very playable, this will have a big impact of first impressions of the game for new players

**Comment by thegrb93** [comment]
I imagine it's a dominantly multiplayer game so I don't think it needs high priority.

**Comment by etet2** [comment]
it is dominantly mutliplayer becuase ther eis nothing to do in singleplayer. in dev there is actually some things you can do and singeplayer would be the obvious place to go for new players

**Comment by BillCombs** [comment]
Also, i feel like if the first thing new players did was trying to play multiplayer with random players, they would likely be put off from playing the game after the possible chaos they could experience. There are some good servers with good players, but, if you are new, you don't know which ones are the good ones.
 And i doubt that it would be easy and fun to be trying to finish the campaign with random players. At least the bots are not trying to blow up the reactor and kill the whole crew. Playing alone gives you more control, lets you do everything at your own pace. In multiplayer, if you try to go slowly and carefully, or decide to stop and collect some random items from the ocean, the dead players usually just vote to end the round so they won't have to wait for you to finish it.

 You could get some friends to play it, but it's pretty hard to get them all to play at same time, because of   
possible events in their life. Some may have to work at the time when other are free; some may just stop liking the game and decide not to play anymore; etc.
 The bots are always there for you. You can join or leave at any time without any consequences.

**Comment by itchyOwl** [comment]
Single player will be playable too. Not just there yet, so much to do. AI is high priority.
