### ISSUE TITLE
[Dev version] Lockers should have more compact versions of their sprites

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1036]
The new sprites of the lockers seem a bit too big and bulky. They look nice, but the size of the sprites forces you to give them more space to keep them from clipping through each other and looking bad. That makes it harder to make small shuttles or compact storage rooms.
![-2019-feb-4-006](https://user-images.githubusercontent.com/38168249/52192958-47ad2d00-287f-11e9-82aa-b50e47985cac.jpg)
![-2019-feb-4-008](https://user-images.githubusercontent.com/38168249/52192961-48de5a00-287f-11e9-8599-9517ee1f193d.jpg)

The older sprites, even though more simple looking, were a lot more fitting for rooms without much space and could be placed together without problems, giving a lot more options for storage making.
![-2019-feb-4-012](https://user-images.githubusercontent.com/38168249/52192983-6ca1a000-287f-11e9-945e-1bf938820f38.jpg)
![-2019-feb-4-010](https://user-images.githubusercontent.com/38168249/52192984-6dd2cd00-287f-11e9-81ad-288d1a6443a6.jpg)

There should be compact versions of the lockers' sprites.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
