### ISSUE TITLE
[UNSTABLE] Substantial Deusizine dosage can kill the Defense Bot

### ISSUE THREAD

**Issue by Kaktar-1** [Regalis11/Barotrauma#10383]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The inflammation (burn damage) Deusizine causes will deplete the Defense Bot's health as though it is poisoned. The chances of someone using Deusizine on a Defense Bot is absurdly low so perhaps this can be overlooked.

Also, the squishy/fleshy injection sound when hitting the drone with a syringe can be misleading. Perhaps a shattering sound should be in place when hitting a metal target? There are now technically three targets in the game that deflect syringe darts.

Deusizine can also kill the Fractal Guardian but don't ask how much it takes.

### Reproduction steps

1: Inject Defense Bot with Deusizine
2: Continue injecting a substantial amount of Deusizine into the Defense Bot

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Kaktar-1** [comment]
I just realized that damaging/debuff darts don't work on the Fractal Guardian which is strange. Most healing/buff darts seem to work. 
Guess the alien robot/cyborg doesn't deflect syringe darts, just rejects them. Again, this is a very minor issue but I though it was worth pointing out these things.

**Comment by Regalis11** [comment]
Thank you for the report!

To me this seems like something that we don't need to necessarily change: the defense bot is intentionally vulnerable to burn damage, and even though it would make some sense to disable it in this case, I think it's such a rare edge case there's no need to complicate things further to address it. And I don't think it's necessarily even unrealistic: the burn damage doesn't represent "inflammation" but actual burns (perhaps the drug is caustic or something), and to me it seems plausible that if it burns organic tissue, it could also burn some plastic/rubber parts of the robot.

**Comment by itchyOwl** [comment]
> the defense bot is intentionally vulnerable to burn damage

This is incorrect. Defensebot and Fractal guardians are intentionally resistant to burn damage, because they are artificial creatures. However, they are are vulnerable to _explosion damage_, which often comes from the same sources. They should also be invulnerable to poisons. Deusizine causes burns, to which Defensebot is partially resistant. We could fix this by adding a conditional for whether the target is a machine or not. I added a wrapper property so that this works in Regalis11/Barotrauma-development@08d5d58 (even if we don't use it, a modder might).
