### ISSUE TITLE
Dragging bodies

### ISSUE THREAD

**Issue by G234i** [Regalis11/Barotrauma#104]
Currently there are a few problems that apear when draging a dead/unconcious player.

1. Draging them up ladders is impossible.
2. Opening doors/operating machines while draging a person drops the body

Issue No2 can be negated by assigning an additional key for interacting with ragdolled bodies other than the default "E".

**Comment by Crystalwarrior** [comment]
Additional key sounds like a terrible idea imo, there should ideally be only a single interaction button.

#1 Dragging bodies up ladders being impossible seems to be intentional, however I have an idea to make it possible (drag by 1 hand? Piggyback?)

Issue #2 could be fixed by either prioritizing interaction over dropping, or making the player specifically interact with the body itself to drop it.

**Comment by Crystalwarrior** [comment]
#101 boom baby. Both issues fixed.

**Comment by G234i** [comment]
> Additional key sounds like a terrible idea imo, there should ideally be only a single interaction button.

Well I come form playing some simulaton games like the Arma franchise KSP and many others and I am accustomed to having to use a different key on my keyboard for different actions.
That beeing said having an open inventory/use key (aka E) and another for interacting with ragdolls/crates (maybe Q???) would be quite usefull as now the only way to open a container is to hold it (not the most intuitive thing but it works, I guess)

**Comment by Regalis11** [comment]
Fixed in dde320b
