### ISSUE TITLE
Adding more than 3 specialization trees breaks the UI

### ISSUE THREAD

**Issue by Milord-ThatOneModder** [Regalis11/Barotrauma#10415]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When you try mod in more then 3 talents (now its 6) this happens with ui.
Please ignore the the empty spaces, its error on my part.

### Reproduction steps

1. Add more than 3 talent specialization tree in talents.xml, either with overriding with content other packages or adding to vanilla content package
2. Load a game in submarine editor
3. try to scroll max to the left and to the right

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Images that represent the issue
https://ibb.co/yQMc2X8
https://ibb.co/nwCykbP
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad8c0409a0c16c16311a9c152c2aff6320a2932c

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b

Having more than three trees appears to place a scrollbar a little too high (At least on a resolution of 1600x900) but otherwise does add the extra trees correctly:
![image](https://user-images.githubusercontent.com/29177976/204488723-5416cf70-6ccc-48a3-8bb3-d9f6efae2f89.png)

![image](https://user-images.githubusercontent.com/29177976/204488808-8e3db4fe-96ef-48df-b674-555ddcdc5d68.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/83c4c9da7df7a1dabf195721393f8fa572f6fa15. Note that this should be tested in the talent-fixes-5 branch (or in release after we've merged it), because there's been changes to the UI in that branch to address https://github.com/Regalis11/Barotrauma/issues/10553

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/f9ace46c636157ec9d37bcde5084063bbd176e1f, no issues found, closing.
