### ISSUE TITLE
Unidentified Genetic material cannot be looked for using an item scanner

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10460]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using an item scanner, you cannot search, or look for, unidentified genetic material, making it hard to find genetic material sitting somewhere in the sub.
![image](https://user-images.githubusercontent.com/104232152/202920650-b33c267a-5ea0-4d02-827c-93c88d4b60b0.png)

### Reproduction steps

1.Spawn in unidentified genetic material
2.Try and look for it using an item finder
3.Find that it can neither be searched for, nor selected in the item finder menu

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Caused by a similar problem as https://github.com/Regalis11/Barotrauma/issues/10474: the different kinds of unidentified genetic materials are all individual prefabs (i.e. there's dozens of seemingly-identical "unidentified genetic material" prefabs), so searching for them would not quite work with the way the item finder has been implemented. Similar to #10474, I'd consider this such a low-priority problem that I don't think it's worth the trouble to fix. One could even argue this is a feature - there's several items that are hidden from menus and unplaceable in the submarine editor, unidentified genetic materials are one of these items.
