### ISSUE TITLE
[Factions] Wrecked turret sprites are broken

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10472]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Simply put, the sprites for wrecked turrets are completely broken, having them a tad misshapen, basically just shows up as here: 
![image](https://user-images.githubusercontent.com/104232152/202923334-d2e29172-7ff3-4b6f-9107-cb392a2b2356.png)

![image](https://user-images.githubusercontent.com/105495756/202921238-8cdf1800-b73d-466f-937f-3953280b19d1.png)

![image](https://user-images.githubusercontent.com/105495756/202924079-4aea9aac-409a-43af-bcdc-f4219b7c2a89.png)

### Reproduction steps

1.Place wrecked turrets in the sub editor
2.Stare at them intently

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2f02591cf27b8d49d3e3f3c8a9bece4d90ddaa6c

**Comment by Wheatley1001** [comment]
![image](https://user-images.githubusercontent.com/105495756/204051767-2e1dda3f-08a3-4cd9-aa1d-da05c5378fb6.png)
Railgun sprite is still borked

**Comment by Rokvach** [comment]
Moving to Team1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d888f63eb60cac947df890d77b71b9ba3eb6feed

**Comment by Rehexr** [comment]
Not adressed in the issue, but wanted to note that for some reason railguns are also tiny now when placed in the editor, thought it might make sense to note this aswell, incase its not part of the fix 
![image](https://user-images.githubusercontent.com/104232152/204390559-06f20c92-8613-4b46-8119-efe967dd22de.png)

**Comment by JeroonBosch** [comment]
Not sure if the following are really problems but:
- Railgun and Railgun (Wrecked) don't look all that same atm. The wrecked version has some vent, also it's a bit higher in the sprite. If you replace a Railgun with the wrecked version to create a wrecked version of a sub, it might not look good because of these minor differences. Same goes for Coilgun wrecked version
![image](https://user-images.githubusercontent.com/8641689/212663537-a0ae73da-a703-4576-a43c-3ca94e2525f8.png)
- Most turrets do not have a wrecked version: Chaingun, Pulse Laser, Double Coilgun, Chain Cannon all do not have. 

This one should still be fixed though (although very minor issue):
Kastrull_Wrecked has a Railgun that's slightly floating/detached:
![image](https://user-images.githubusercontent.com/8641689/212664284-979766cf-eb39-406d-98dd-a923a4c60755.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d155c64acf8afe7b4b309c8f3a3697b6c679db42

**Comment by JeroonBosch** [comment]
Tested again after the changes, no issues found - closing
