### ISSUE TITLE
Combined genetic material shows up separately on the item finder

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10474]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Combining gene material causes it to still show up seperately on the item finder, pretty basic minor issue
![image](https://user-images.githubusercontent.com/104232152/202924717-19993851-72cb-436c-92a3-3f4bed716fcb.png)

### Reproduction steps

1.Combine some genes
2.Look for genes on the item finder
3.Have them show up seperately

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Partially addressed in https://github.com/Regalis11/Barotrauma-development/commit/83f691636d113079e927bf5d85a2f3655c27bd4c: now only the "primary" genetic material is listed here (the one mentioned first in the name). Fully fixing this would be tricky due to the way the item finder works: it lists item prefabs as search options, and there are no prefabs for combined genes (they're technically just one type of genetic material inside another one). And I'd consider this such a minor issue that it's not worth to overhaul the whole item finder logic to address this.

**Comment by Rehexr** [comment]
Works as is adressed, this is at least a good compromise to deal with it, closing it then.

**Comment by Regalis11** [comment]
Reopening, the fix seems to have caused another issue https://github.com/Regalis11/Barotrauma/issues/10697

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/32420b0e4ea9565560a9e78a3e300d4a7542a51f

**Comment by ekqvist** [comment]
Tested that combined genetic materials are displayed as a single one (using the name of the first one like noted above). Seems to be working correctly, closing.
