### ISSUE TITLE
Graduation Ceremony grants 6 talent points 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10484]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There is no mention of this in the talent description, yet during one of our testing sessions one of the assistants was granted 6 talent points upon taking the talent.

Talent description as of 100.5.0.0 for reference.

![image](https://user-images.githubusercontent.com/105495756/202929021-5582c64b-eb25-4f61-9f83-f53fbe303432.png)

### Reproduction steps

1. Be assistant
2. Get Graduation Ceremony
3. Get free talent points

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm not sure if this is actually bug. I would assume these points are for unlocking that extra specialization tree.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a1577f87c53ede09d28bd5b2f5fb5241043da131

The old "All-Seeing Eye" talent where I copy pasted most of the behavior from required you to increment talent points because it granted all the talents in the tree but since Graduation Ceremony unlocks you talents outside of the talent trees you don't need to allocate extra talent points for them and was giving you double, removed it now

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
