### ISSUE TITLE
Controlling detachable shuttles remotely

### ISSUE THREAD

**Issue by Geevies** [Regalis11/Barotrauma#105]
Could birth the creation of scout shuttles that are operated using a new remote control terminal. Cameras can be used to guide the pilot, etc.

**Comment by NilanthAnimosus** [comment]
I suggest instead of cameras the usage of a Sonar device.
- Additionally allow the signal of a sonar to be used across multiple devices (Such as a relay or two towards 5 or more sonar monitors and navigation terminals
-Allow the sonar device the ability to work across linked submarines via Wifi
-Have the devices perhaps have a checkbox (Default true) for an internal sonar, thus enabling old submarine compatibility while allowing it to be overridden by an external sonar source.

This allows every status monitor and sonar to change the location of the center of its sonar / movement controls essentially, allowing remote shuttle control and different centers of submarine alongside possible game play opportunities (Such as cutting the sonars feed while retaining submarine control).

if one still wants cameras, allow cameras to be adding to the navigation terminal and allow cameras to be wifi compatible (If they are not already) - but display only one camera at a time requiring a switch of which wire signal to use (GUI of navigation terminal or in-world wiring).

**Comment by Regalis11** [comment]
Implemented in the dev branch
