### ISSUE TITLE
Dedicated server visibility is changed to private when player joins / Dedicated servers Server Settings doesn't include visibility setting

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#10523]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

-

### Reproduction steps

1. Make sure IsPublic is set to True on server settings
2. Launch dedicated server
3. Join server and notice on the lobby server banner that the visibility is set to private and you have no way of setting it public

### Bug prevalence

Happens every time I play

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The issue was actually that the server was expecting the XML attribute to be "public", when it's now "IsPublic". So it would actually start up as a private server when using public="true". Fixed in https://github.com/Regalis11/Barotrauma-development/tree/feature/bugfixes

The latter part, changing the setting on the fly, is not supported for dedicated servers as mentioned in the PR https://github.com/Regalis11/Barotrauma-development/pull/3702

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
