### ISSUE TITLE
Collection of depth charge issues

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10524]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Theres a couple of issues ive noticed since the depth charge changes, which i wanted to list here.
Firstly, as much as it pains me to report, the fact that decoy depth charges cannot be damaged just seems off, or an issue in general. Well it wouldn't be, if not for the second issue here.

Decoy depth charges never use the explosives put inside them, neither on contact with a character, nor with any surface, making loading them with explosives useless in their current state. 

And at last, less of a direct issue, more of an oversight, nuclear depth charges, and i guess also depth charges in general, have too little health, with me at points being able to explode one with a single harpoon shot. While this wouldnt usually be an issue, i do have concerns with the degree of trolling people will use this for (as they always do), and obviously also the possibility that going by this indirectly may not account for their karma. 

I hope me posting these all as one issue isnt a problem, just thought itd be more convinient to have them in a thread of sorts. 

### Reproduction steps

For the first issue
1.Try dropping a decoy depth charge, and shoot it

For the second
1.Drop a decoy depth charge with a load inside at any place of your choosing (using the subs depth charge loader) 
2.Watch it not explode

And for the third
1.Really, just reference the amount of health it has against how quickly you could shoot it to explode

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem to be specific to the faction branch.

**Comment by Rehexr** [comment]
Ah, thought depth charges were only changed since the factions branch

**Comment by itchyOwl** [comment]
Thanks for the feedback, I'll look into it!

**Comment by itchyOwl** [comment]
Tested using the latest unstable release branch (0.20.8.0). Addressed some of the the issues in #3783, but can't repro/agree with all of them.

> the fact that decoy depth charges cannot be damaged

Doesn't seem to be the case: had no issues with damaging any of the depth charges. Tested both projectiles (harpoon and coilgun) and hit scan (revolver). Note that they are damageable only after launching, not inside the sub. This was done to prevent accidents and to limit abuses.

> Decoy depth charges never use the explosives put inside them, neither on contact with a character, nor with any surface, making loading them with explosives useless in their current state.

They did, but only when the decoy was destroyed. Changed this so that they will self-detonate when the timer runs out. It's intentional that the decoys don't explode on collision, because otherwise they wouldn't be very effective in luring the enemies away from the sub.

> And at last, less of a direct issue, more of an oversight, nuclear depth charges, and i guess also depth charges in general, have too little health, with me at points being able to explode one with a single harpoon shot.

They had 100 health, which takes three harpoon hits (each 40 damage on items), which is actually much more than intended. I reduced the health from 100 to 10, so that they will explode from one hit. I don't see the issue here: the depth charges are only destructible when they have been launched. If they can't be one-shot, there's no point in making them shootable in the first place. They are difficult to hit (had to disable the detonation in OnImpact to test it), and ffs they are explosives, so they _should_ explode when shot at.

**Comment by itchyOwl** [comment]
Actually there seems to be something wrong with the projectile collisions _before_ the depth charge hits something. Looking into it.

**Comment by Rehexr** [comment]
Thanks for the response, considering depth charges should only be damagable outside the sub, it might be important to mention that, well, regular depth charges can still be damaged without launching them, inside the sub, ha

**Comment by itchyOwl** [comment]
> regular depth charges can still be damaged without launching them, inside the sub
Not intentional. Need to test this.

**Comment by Rehexr** [comment]
Depth charges being damageable within subs isnt fixed, might wanna check that out

**Comment by Rehexr** [comment]
I hope this being closed means that the latest issue has been adressed aswell?
