### ISSUE TITLE
Gap between submarine and shuttle

### ISSUE THREAD

**Issue by WILHELM-WICK** [Regalis11/Barotrauma#10541]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So I made a sub with two shuttles one can undock and dock with no problem (no gaps between the two docking ports) but the other... When the sub spawns there is no gap but when you detach the said shuttle (is in fact a kind of torpedo controlled by a second nav terminal in the sub) and dock it again a gap appears. Also the hulls of the torpedo show up on the nav terminal but I can't "interact" with them (no additional data when my mouse is over it).

The one in the front doesn't work
[](url)
![image](https://user-images.githubusercontent.com/107401709/203971667-f29f5edc-5336-44f0-864f-c4c7e5bca473.png)

When the sub spawns
![image](https://user-images.githubusercontent.com/107401709/203972767-273a638f-db95-46b5-96c6-25989ecd0277.png)
![image](https://user-images.githubusercontent.com/107401709/203973207-7fb8306f-8684-4197-a803-861e1924ac5c.png)

When you detach and dock the torpedo back
![image](https://user-images.githubusercontent.com/107401709/203972927-4eed2afd-5f36-42fc-82c5-3af87aff1589.png)

![image](https://user-images.githubusercontent.com/107401709/203973287-28bc7181-73dc-4784-8eb7-127b93e46f94.png)

Link for sub: https://steamcommunity.com/sharedfiles/filedetails/?id=2893060611

(don't pay attention to the yellow arrow in the back)

### Reproduction steps

1. spawn sub
2. detach torpedo by using nav terminal (the one with 2 Ws on it)
3. attach it back
4. see the gap

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by WILHELM-WICK** [comment]
btw i know people had approximately the same issue but i didn't understand the fix :(

**Comment by Regalis11** [comment]
´Thank you for the report!

Finally got around to testing this. Fixed the bug that prevented the hulls from being highlighted now (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/5a0fbbc55fbde95fd30257bea56bf3c9bf69171a).

The gap seems to happen because of the unusual way the docking ports have been set up: the torpedo has a tiny, invisible docking port, while the sub has a normal one. Having two ports of different sizes dock with each other wasn't really something we had considered, and what happens here is that the distance between the ports depends on which port initiates the docking. At the start of the round, the torpedo docks to the sub, causing it to get placed close to the sub. But during the round, the main sub initiates the docking, which causes it to be placed further apart. I recommend setting the scale of the ports to the same value to fix the issue.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843, no issues found, closing.
