### ISSUE TITLE
[Port Forwarding Bug] 

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1055]
I port forward to the port shown on the barotrauma website, set it to my ipv4 ip, and add udp with the rest being default settings. People still get the remote host message when trying to join.

Steps to reproduce: > be me

Windows 10, latest barotrauma not the closed beta, latest bte

**Comment by Regalis11** [comment]
Could you post a screenshot of your port forwarding settings? This could be an issue with incorrectly configured ports or possibly some kind of a firewall problem.

**Comment by AbominationBanisher** [comment]
Sure thing. 
![image](https://user-images.githubusercontent.com/41457828/52224121-a6df6180-28c0-11e9-9740-876c025f5d04.png)

**Comment by NilanthAnimosus** [comment]
Although I noticed you created this issue previously, have you tried going through what I wrote on this issue before?

https://github.com/Regalis11/Barotrauma/issues/518

I link back to this more because it will also help to show what your local IP is from command prompt using IPconfig

though the rest of it may help to give some ideas, the above image looks ok to me and you clearly got it to work before oddly.

Finally, as a note (Though you don't state it, i'm just being thorough) you cannot connect to yourself using the external (From server browser) IP, you need someone external to test the servers connection while you yourself connect via 127.0.0.1. connecting yourself wont prove its forwarded too.

**Comment by AbominationBanisher** [comment]
Port forwarding worked before, now it stopped.

**Comment by Regalis11** [comment]
That can be caused by a multitude of reasons, and without further info it's unfortunately very hard to help you. Have you verified that your local IP address is still 192.168.0.21? (Instructions in #518) If you select the server in the server list, does the IP match your external IP?

**Comment by AbominationBanisher** [comment]
I have verified my local ip, did everything in the link you posted. The ip does indeed match my external ip.

**Comment by Regalis11** [comment]
Unfortunately there's not much we can do to help based on this info. If it used to work before it seems to imply that something in your network changed - perhaps your IP, some router setting, firewall or antivirus.
