### ISSUE TITLE
[Factions] Gaps missing in Winterhalter wreck in the end level

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10579]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the Winterhalter wreck of the final level, gaps are missing which makes swimming between them impossible

![image](https://user-images.githubusercontent.com/73229309/204112528-e31c162c-cc0a-429b-b938-d5d41b0b2268.png)

### Version

Faction/endgame test branch

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch

**Comment by ubertpendragon** [comment]
More specifically horizontal gaps, you can't see them in debugdraw unless water is flowing (I didn't test them all)
The other wrecks seemed fine

![image](https://user-images.githubusercontent.com/73229309/204162445-c5933a04-e576-4cba-96d2-02a4694a1f6a.png)

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d

Very minor hull issue where it doesn't quite touch the outer wall inside the submarine (Otherwise, the gaps appear to be fine):

![image](https://user-images.githubusercontent.com/29177976/208071666-2b92eda1-db9e-4812-8d82-497df3835a28.png)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@dd3414b (wip-fixes).

**Comment by JeroonBosch** [comment]
![image](https://user-images.githubusercontent.com/8641689/211554548-f41a5629-fac9-4968-b5ae-d341f4bcf9f2.png)
hard to say if this gap is between the hulls, could be a minor issue? No other issues found

**Comment by JeroonBosch** [comment]
No further issues
