### ISSUE TITLE
Item marked as stolen in an Abandoned Outpost 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10597]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I started up the campaign in an abandoned outpost module. For context, we had just come through two or three natural formations before this (we're in the final biome). Upon checking my inventory, I noticed one of my Plastiseals had been marked as stolen - something which should be impossible. 

Furthermore, once we had rescued the hostages within the abandoned outpost (all of bandits were in a single room) one of them started yelling at me to return a stolen item. I did not interact with any stolen items. I climbed down the ladder in front of them when this prompt triggered.

![image](https://user-images.githubusercontent.com/105495756/204136885-d811d34e-bd15-4ba2-ab48-2cd41a8145c0.png)
![image](https://user-images.githubusercontent.com/105495756/204136895-2747498e-f089-4535-8345-3b978b4019aa.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch

**Comment by Regalis11** [comment]
I'm not entirely sure what caused this, but my theory is that the name of the outpost the items were stolen from (assuming they were stolen?) happened to be the same as the name of this level. Previously, the name was used as the seed for the level, and the seed was used to determine which outpost the item was stolen from.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b5e47ed1222a0150c37f3a044bf4dcd7940f6ce0

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d, no issues found, closing.
