### ISSUE TITLE
[Factions] Unlocktalents all command gives talents weirdly

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10607]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you enter the following command:

unlocktalents all (NAME OF CHARACTER)

You will unlock every talent in the game. That part works fine. What doesn't work is that you'll get a huge wave of talents and then they start to slow down. The best way I can describe it is like spinning a giant wheel; it slows down over time until it reaches a painfully slow crawl. 

I'm not sure why this is done instead of giving you all the talents immediately as this is clearly done in the first few seconds after typing the command. It doesn't make sense for the last 20 or so talent notifications to be drip fed. 

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It actually gives all the talents immediately, it's just that the text popups aren't all shown at once. This is an intentional feature, as otherwise it would be hard to read all of the messages when multiple ones appear at the same time (although, with the unlocktalents command there's such a huge amount of messages that they scroll past too fast to read, but that should never happen in normal gameplay).
