### ISSUE TITLE
[Factions] Outpost Clinic healing shows inconsistent afflictions 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10649]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The outpost clinic suffers from an issue relating to affliction representation and healing. Some afflictions show up but cannot be healed, whilst other afflictions can be healed but don't show up. 

Images below for reference.

![image](https://user-images.githubusercontent.com/105495756/205412966-ae875b99-8cbe-4af0-85b2-9fba10923500.png)
_Figure 1. Jade Harley suffers from both Opiate Addiction and Opiate Withdrawal, yet only one can be healed. Blunt Force Trauma also shows up to be healed yet is not shown on Jade's character._

![image](https://user-images.githubusercontent.com/105495756/205413001-59cfbf1f-04e1-45de-94dc-4c2fa81f3218.png)
_Figure 2. Bananaman suffers from two afflictions, but you can only see one associated with his character._

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Should be fixed with the changes in https://github.com/Regalis11/Barotrauma-development/pull/3796/commits/e221ab30e4874df243c0b698f2b3f2a7b4c65d3c https://github.com/Regalis11/Barotrauma-development/pull/3796/commits/7ef2532c7e49b2802d158812ae08d37f0653ab7a and https://github.com/Regalis11/Barotrauma-development/pull/3796/commits/6ec8a5f1bf2661194478abd73a34dd6704e0e953

**Comment by Regalis11** [comment]
Tested, working correctly. Closing
