### ISSUE TITLE
Status Monitor merges outpost hulls with submarine hulls and extends beyond the monitor

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10655]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon checking the navigation terminal, I noticed the status monitor was showing the outpost hulls. These hulls were also extending beyond the boundaries of the status monitor, going as far as to leave the screen at the highest point.

![image](https://user-images.githubusercontent.com/105495756/205414867-d5db6a34-7e58-47ca-9cf4-070ac942005c.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I unfortunately couldn't find a way to reproduce this.

**Comment by Regalis11** [comment]
Found a way to reproduce this now: it seems this (only?) occurs when the status monitor is out of power. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/add1e27d347d11e67d06265c50e58d0dc2c315c1

Can by reproduced e.g. as follows:
1. Start a new campaign
2. Switch to the editor and set the status monitor's power consumption to 100000
3. Switch back to the game and have a look at the status monitor

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/0b2d49ccd119c0e932389f71cf6fa7ab6d7680f0.
