### ISSUE TITLE
Helm skill and bypassing it via maintaining position 

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1067]
From playing the game i've noticed that the helm skill affects how quickly the velocity vector for the sub goes to its intended location while on manual steering. This is a great way to implement the captains role in a way that actually matters, However if you use the selector for where you want to maintain position you have the effects of an instant adjustment of the velocity vector no matter the helm skill ultimately rending the implementation of captains helm skill moot.

**Comment by BillCombs** [comment]
It seems that using autopilot does not affect leveling up the helm skill. If you are planning to make it depend on the skill, then you should also make it give you experience for using it.

**Comment by NilanthAnimosus** [comment]
to be honest flipping a button for a computer to drive the submarine should not level the helm skill, and it does need sorting out by preventing this being used to bypass it.

Conversely though - this REALLY hurts if you are a none-helm based job who has a respawn shuttle to drive (which is nearly all the jobs in honesty) or if everyone is dead who can drive a sub making it an awfully painful slow experience to drive the sub without making use of it.

I've heard some stating submarines feel extremely slow to drive compared to legacy, and this makes it worse as much as I would like to see a good implementation.

**Comment by BillCombs** [comment]
I doubt the computer would be able to immediately read your mind and know where you want to go just from a press of a button. Perhaps the character at least needs to know how coordinates(or whatever navigation system is used in submarines) work.

Perhaps the autopilot should consume more power as a cost for easy control. Though that might make it pretty hard for shuttles without a reactor and with small power capacity. To be honest, i don't really know what would be the best solution for this problem.

**Comment by NilanthAnimosus** [comment]
that's my main point, I don't know the solution with the current implementation, and I have yet to think of a good way about this.

Perhaps helm should really modify the potential output of the engine and drainage rates / sink/rise rates of the ballasts, so the sub is easier to handle without artificially saying where you are/are not aiming for.

as amusingly punishing the vanilla respawn shuttles are where you either drive into a wall you can't slow down to or run out of power either way because they don't hold a charge to go anywhere. it would be nice to give helm skill a benefit without severely impacting other jobs alongside not having ways to bypass it.

If you were able to suddenly take the autopilot issue out, and somehow fixed and corrected this problem of being able to bypass the helm skill - is it really that good for gameplay when a captain is dead to try to pilot a sub at the moment? there are already players thinking submarines drive pretty slowly.

I could see maybe having a time delay before the target location changes (IE. high helm skill it only takes 0 seconds to 0.25 seconds) but for a low helm skill it can take a full second to take effect, stalling out and keeping its last heading while its changing and making further changes only resets the duration of said stalling out.

but when you have low helm skill and this isn't an issue, the captain being dead may as well be a game end, or a very, very long wait. autopilot is not too great in terms of speed and low helm is extremely punishing. your typically about as likely to run out of fuel than actually win that way.

**Comment by Regalis11** [comment]
https://github.com/Regalis11/Barotrauma-development/tree/feature/autopilot-improvements (private repo) remedies this somewhat. The autopilot now gets to the position more slowly when the terminal is used by a character with a low helm skill. Not sure if that's still enough, needs some more testing and balancing

**Comment by Rokvach** [comment]
Tested, didn't see anything wrong with this. Closing.
