### ISSUE TITLE
Taken items and killed characters respawn after saving and quitting in SP

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#10689]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Taken items and killed characters respawn after saving and quitting in singleplayer campaign.

### Reproduction steps

1. Start a singleplayer campaign
2. Take an item from the outpost
3. Save and quit
4. Reload the game
5. Find the same item still there and another copy in your inventory

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@c943491

**Comment by Regalis11** [comment]
It seems all of the NPCs get randomized when you quit and reload, regardless if you killed them or not. So essentially, killing them has no effect because you'll always get a random set of NPCs anyway. Not sure what's causing this - synced random being used in a non-deterministic way in `GameSession.InitializeLevel` maybe? A trivial way to fix that would be to set the seed before calling `Level.SpawnNPCs`, but I think it'd be better to figure out what's causing it to get out of sync despite the seed being set in `Level.Generate` (which happens before spawning the NPCs).
