### ISSUE TITLE
Live sub editing by players

### ISSUE THREAD

**Issue by JJRcop** [Regalis11/Barotrauma#107]
This idea would require a lot of work, but I want to be able to, as a normal player in-game, use materials to build walls, paneling, air vents, et cetera, to in the end be able to completely deconstruct an existing sub into materials, or build a new one from scratch.

This idea would require that every structure be constructable or deconstructable, air vents would need piping to connect to oxygen generators, vs 'linking' as they are now, naming a sub would have to be tied to some sort of object in the sub rather than the whole sub itself, et cetera.

Maybe this is completely out of scope for the game, however, it would be neat to see a sub evolve over the course of a campaign, or in non-campaign Combat mode, one team moves a gun somewhere else that the other team doesn't expect, surprising them.

Don't underestimate the amount of work required for this to happen, it is likely a lot, with all the refactors and rewrites and stuff.

**Comment by JJRcop** [comment]
A few more things I can think of: Spawning would need to be tied to beds, you would have to be able to edit the access of buttons, depth charges and railguns would need connecting tubes to their ammo store, waypoints would need to be regenerated occasionally, along with being more robust and accurate (at least the ones surrounding the sub), a new "cargo bin" would need to be added.

**Comment by G234i** [comment]
@JJRcop this really sounds like a lot of new stuff that will comepletely changa the game but yes having submarines "evolve" sure would be nice, but perhaps this can be done by assigning price to the different building "blocks" and then (in campaign mode) players might have the ability to enter edit mode at the end of missions. 

Assigning monetary value to everything will probably render the current resource system useless but it's a pretty straightforward solution.

**Comment by Crystalwarrior** [comment]
The way the game is built right now I actually like that the subs are all pre-made.
Don't get me wrong, this sounds like an incredible idea, however the only thing it would fit is Campaign mode, not to mention how much tweaking and bugs you have to endure if you're planning to make a sub from scratch. It's a gargantuan effort on the player side.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
