### ISSUE TITLE
ship gun sprite bleeding in editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10785]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

top and left of ship guns have some bleeding

![image](https://user-images.githubusercontent.com/5103517/208959017-0e610fbb-c1e4-4c0f-9ea3-002c84fd4c08.png)

![image](https://user-images.githubusercontent.com/5103517/208958848-34330c28-8350-447c-8633-862f60839991.png)
![image](https://user-images.githubusercontent.com/5103517/208958929-bf520e2f-7ed7-417d-914b-d222c6de0e6f.png)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
@IiroEnges the barrel is no longer centered properly 
![image](https://user-images.githubusercontent.com/14351070/210241430-efc537b9-5999-4087-b5d5-e28fbb72b5d5.png)

**Comment by JeroonBosch** [comment]
![image](https://user-images.githubusercontent.com/8641689/211556386-665957cf-c7ff-4bff-9d21-235e3672b6c2.png)
Centering on the coilgun is a little bit off? Might be nitpicking here

**Comment by Regalis11** [comment]
I ended up reverting the earlier commits, because changing the turrets' dimensions is a bit tricky (we'd need to rescale them in existing subs and make sure they're still correctly positioned). Implemented another fix by just moving the sprites a bit in the atlas: https://github.com/Regalis11/Barotrauma-development/commit/c6e44763a506edb6bfa14069701fa12f8f4cdbf7

**Comment by JeroonBosch** [comment]
No issues found, tested for:
No more sprite bleeding. 
Coilgun is properly centered.
Checked all subs, the guns are all correctly placed still.
