### ISSUE TITLE
Colorblind Troubles

### ISSUE THREAD

**Issue by Zeuskiron** [Regalis11/Barotrauma#10788]
Maybe you could change the color set for the spikes on the navigation terminal and monitors like that for people with colorblind for a notorious one orr make an option in the settings to activate some notorious colours for the people that have problems with them, with the artifacts or metals. Specially the spikes i'm colorblind and is not the first time neither the last one that i have to make a reverse trayect going through the abbyss  passing it and surrounding the map because i barely can see them as captain.

I have more than 600 hours of gameplay and 600 hours of game editor.

**Comment by cshingle** [comment]
I am color blind as well. As far as I am aware wrecks, beacon stations and other stuff on sonar are all the same color, it is more the shape that is the giveaway.
I do not understand the other stuff that you're talking about.

**Comment by Regalis11** [comment]
Yep, they are intentionally the same color: it's not supposed to be immediately obvious what you're looking at on the sonar.

**Comment by Wheatley1002** [comment]
This doesn't address the initial concern of the report. The OP was explicitly mentioning Spikes, as in Ice Spires. They are shaded green so users can explicitly identify them as destructible relative to the rest of the environment. Indestructible environments/destructible structures are blue, destructible environments are green, and sonar distortion is red. Whilst yes, you are not supposed to identify structures such as wrecks, ruins, and beacon stations by colour, the game heavily implies that you're supposed to identify Ice Spires/Ice Burgs through colour.

**Comment by Zeuskiron** [comment]
Thanks god that @Wheatley1002  understood me, but is closed anyway. That was the real problem the Ice Spires that i wrongly  though  they were named Spikes.

**Comment by Regalis11** [comment]
@Wheatley1002 thank you for pointing out on Discord that there'd been comments on this ticket - I don't get notifications of comments on closed tickets.

While it is intentional that the ice spires (and other destructible walls) are very similar-looking to normal walls, they definitely shouldn't look identical, so I think we do need to adjust the colors.

@Zeuskiron @cshingle (or anyone else who has had difficulty telling them apart), could you give any feedback on how this looks? 

https://github.com/Regalis11/Barotrauma/assets/14351070/218979bd-81d1-426d-b288-983eef110f52

I made the color change from yellowish to green now, is it any easier to distinguish it from the normal walls?

**Comment by Regalis11** [comment]
Implemented the colors above now. I gave them a test with https://pilestone.com/pages/color-blindness-simulator-1, and if the results given by that page are at all accurate, the destructible walls should now be much easier to see.
