### ISSUE TITLE
[Dev Version] Round start loading stuck in a loop

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1079]
After the loading screen, the mission dialogue pops up, then the loading screen appears again, and repeats until I get disconnected.

My only guess is my game loaded so much faster than the server that things broke. (SSD and very good cpu/gpu)

**Comment by NilanthAnimosus** [comment]
This sounds like it could be caused by #1056 which an update has yet to go out for this issue or other networking issues for most servers.

Technically, it can do more than two loads on the server-side, and the client only loads once per time the server tells it to. odds are the server has started the same round multiple times and done multiple loads.

**Comment by thegrb93** [comment]
Yeah, I think that may be the same issue.
