### ISSUE TITLE
 The server option DestructibleOutposts="False" does not seem to be working for abandon stations

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#10829]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Abandon outposts are still destructible when I have the server setting DestructibleOutposts="False". I am hosting via dedicated server.
This didn't used to the the case on version 0.19.
I use this setting because it eliminates common cheese tactic of flooding the station to kill NPCs when using high difficulty mods. I prefer making my crew die horribly.

I have not tested this without mods, but I expect the same result since the mod I am using adjusts the NPC equipment, health and missions via XML.
Here is a link to the mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2824698537

### Reproduction steps

1. Create a server with DestructibleOutposts="False"
2. Start a campaign
3. Get to an Outpost Assassination mission
4. Use small arms or grenades to damage the station (which should not be possible due to the server setting)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
> This didn't used to the the case on version 0.19.

This doesn't seem to be the case. I gave 0.19.9.0 a test, and they seem to be destructible regardless of the setting. Looking at the commit history, they should've been destructible ever since they were added in the Embrace the Abyss update:
![image](https://user-images.githubusercontent.com/14351070/210530101-76aefbfc-81a9-4078-8d86-dfe4b5664819.png)

If you want to disable this behavior, it can be done by setting `alwaysdestructible` to `false` in the abandoned outpost config (Content/Map/Outposts/OutpostGenerationParameters.xml).
