### ISSUE TITLE
Cannot properly use hatches/doors - Looks like desync with my own multiplayer server

### ISSUE THREAD

**Issue by capncereal** [Regalis11/Barotrauma#10832]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When i open any hatch or door, it appears to open. i walk through, but get sucked back and stuck. it's as if the command to open the door is not received by the server. my client shows it open. other people in my server said that the door was not visibly opening for them.

the only way I can go through any hatch that requires interaction to open is if bots or other players open it for me. 

this started happening in my multiplayer campaign about 15 hours into the save after numerous sessions of play. It is persistent now. no restarts of the lobby or client or my computer help.

im running an intel i7 10700k, RTX 3080ti, and have symmetrical gigabit fiber internet that tested over 930 Mbps up and down this morning. issue is still happening after the most recent speed test. 

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no messages or crash. just can't play because i can't go through doors on my own.
```

**Comment by cshingle** [comment]
The issue could be on the server side. Do you have any info about the server?
Is the host hosting via the game client, or a dedicated server? What kind of ping are you getting with the server, etc.

**Comment by whyyallsobroke** [comment]
Hello. I had the same problem, I copied your question and pasted it into the steam forum. User answer helped me. 
https://steamcommunity.com/app/602960/discussions/1/3735205432017579933/#c3735205432018630505
"I don't have a fix to offer you I'm afraid. But if that is the only problem I may suggest a motion detector wired to the door. You would at least still be able to play the game. I'd suggest the github but it appears you've already been there.

One small thing I would check is to verify your id card is actually your id card. But I doubt that is the problem." 

I just changed the ID and everything is fixed)

**Comment by Regalis11** [comment]
Thank you for the report!

I suspected this might've something to do with the ID cards as well (some kind of desync of the ID card tags?), and @whyyallsobroke comment seems to suggest that might be the problem here.

This seems very difficult to diagnose unless we figure out a way to reproduce this. Do you still happen to have the save file, and the character data file saved in the same folder available? If you could post those here, it might help us get to the bottom of this. Until we manage to fix this, it could also be possible to work around the issue by purchasing a new ID card for the character.

Thanks and sorry for the inconvenience!
