### ISSUE TITLE
Piezo Crystals can soft-lock a submarine by increasing load too much

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10856]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Piezo Crystals increases Load by 500 per junction box on the submarine in a 3000 radius

Some submarines, like the Orca2, have enough JBs and a low enough reactor max output that a single Piezo crystal can put the entire grid below the minimum voltage threshold. This makes it impossible to restart the sub without blowing up the Crystal(s) which maybe lodged directly next to your ship.

As a side note it's somewhat counterintuitive than a massive electrical current going through the sub _undervolts_ it.

Change the `extraload="500"` to `extrapower="500"` ?
Overvolting might also cause the same issue in reverse, otherwise the problem lies in reactors having a max output

![image](https://user-images.githubusercontent.com/73229309/210270414-572d0197-8411-4b59-8076-239a25b97000.png)
![image](https://user-images.githubusercontent.com/73229309/210270523-03eb06fb-92cd-4f1e-847c-27652198174a.png)
![image](https://user-images.githubusercontent.com/73229309/210270549-cab9353a-f0a4-4477-82e6-4913b2ae7838.png)
![image](https://user-images.githubusercontent.com/73229309/210270594-3a85ad91-ade7-4cd3-8432-772d68a6b52e.png)

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by cshingle** [comment]
I had this happen during a campaign, but we just unwired/disabled everything but the pumps and got out that way. I could see a less experienced crew having issues.
I like the affects of the Piezo Crystals because it is something different. Maybe the load affect could be 10 seconds on then 10 seconds off to give a sub some time to escape.

**Comment by mygamingaccount** [comment]
Get your sub unstuck by sending out an assistant with a plasma cutter

**Comment by cshingle** [comment]
> Get your sub unstuck by sending out an assistant with a plasma cutter

I like the way you think!

**Comment by Regalis11** [comment]
> > Get your sub unstuck by sending out an assistant with a plasma cutter
> 
> I like the way you think!

Me too! I'd say this "soft-locking" is intentional. If you happen to end up right next to a crystal, you need to destroy it to get back moving. There are plenty of ways to do that: turrets (if they have line of sight to the crystal), detonators and explosives, drones, that assistant with a plasma cutter, firing at it with a handheld weapon from afar...
