### ISSUE TITLE
Bot ignore follow order and swim to bottom right when outside of the submarine

### ISSUE THREAD

**Issue by hko2006** [Regalis11/Barotrauma#10866]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bot sec officer follows my mechanic when outside of the submarine.

### Reproduction steps

Video

https://user-images.githubusercontent.com/5365456/210467315-e3d8004a-b214-4ab7-92e9-9dbf3ee045a5.mp4

They are at the cursor

![image](https://user-images.githubusercontent.com/5365456/210467866-e5febf36-f1a4-4a56-b585-437d6bde38fa.png)

Save

[Save 1.zip](https://github.com/Regalis11/Barotrauma/files/10340852/Save.1.zip)

No order and return ship dont work too.

This is the third time this happen, all three times with this Day sec officer.

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Here's some debug info about what's probably happening there. I'll look into it. Probably only affects caves.

![image](https://user-images.githubusercontent.com/5370738/219327091-4ea7239e-643c-477b-8ec2-6d5dc0907ad0.png)


![image](https://user-images.githubusercontent.com/5370738/219326491-c7d51e4f-bb28-4060-ae4f-c5d72a181098.png)

**Comment by itchyOwl** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3987

**Comment by itchyOwl** [comment]
Seems that this issue was only partially fixed:

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/4acc96b0-51d5-432d-a820-a48bd63f388d)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/77955c27-a952-4a84-abfa-2533ea198a33)

**Comment by itchyOwl** [comment]
I'll push a fix on this tomorrow, but writing the repro steps here now.

Steps to repro the last issue:
1. Make a bot to follow you outside of the sub so that there is a direct line of sight between you and the bot
2. Teleport the sub so that there's no direct line of sight from the bot to the sub
3. Order the bot to return back to the sub
4. Order the bot to follow you again
5. Observe the bot continuing to use pathing even though it should just steer towards you (when there's nothing blocking the way)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/bc2d0f7f-7cf6-49fe-9194-85d5ce181c87)

After the fix, the bot should steer towards the player when it can see the target. If the line of sight is blocked, the bot will try to use pathing to get around the obstacles.


![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/463dad8b-0751-45d0-a8a0-4bdac0d8502a)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
