### ISSUE TITLE
Missions no longer appear in old campaign

### ISSUE THREAD

**Issue by wjamesbonner** [Regalis11/Barotrauma#10886]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Like discussed in issue #9869 (https://github.com/Regalis11/Barotrauma/issues/9869) I have a long-running campaign and suddenly no longer received missions from any NPC's in the populated bases. No ellipses appear over their heads or dialogue is available. In issue 9869 you were able to fix the linked multiplayer files to adjust the difficulty curve. Would it be possible to take a look at our groups campaign to see if it can be fixed? If not, no worries; we will re-start using one of our new ships.

Here is a link to our campaign files: https://github.com/Regalis11/Barotrauma/files/10201159/Multiplayer.zip

### Reproduction steps

1. Start the long-running campaign file.
2. Dock at a populated base in the great sea (Kenneth Linea in our case).
3. No missions or ellipses indicating missions. No flags at connected bases indicating missions.

I just patched to 0.20.16.1 tonight and tested again to confirm we are still having the same problem.

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! 

It does seem that this was the same issue as https://github.com/Regalis11/Barotrauma/issues/9869. I made the game automatically clamp the difficulty of the locations to the difficulty range of the biome now to prevent this from happening again (commit in our private repo: https://github.com/Regalis11/Barotrauma-development/commit/9225441aea6b30191b6449b42d93532483ae089f).

Here's a modified save file with the difficulty curve adjusted. Note that there are still no events in the current location, because it seems all the events from that location have been exhausted for now (meaning there will be no further events unless you travel out from the location and return back to it later).
[HellBread.zip](https://github.com/Regalis11/Barotrauma/files/10372062/HellBread.zip)

**Comment by wjamesbonner** [comment]
Awesome, thank you! I will test and update/close this evening!

**Comment by wjamesbonner** [comment]
Hello, We just tested, and it is all working; receiving missions once we went to the next station over. Thank you!
