### ISSUE TITLE
Add a put on suits command

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1089]
Shit hits the fan pretty quickly a lot of the time in barotrauma. As it currently stands AI do not seem to be competent enough to know that if they're in a flooded room that they need oxygen and a pressure free environment. Please add a command to tell them to put on suits in the same region as the Wait, Follow, and extinguish fires commands.

**Comment by thegrb93** [comment]
Probably related to #1034

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
