### ISSUE TITLE
Medical Doctor Ai Prioritizes Hulls Over Medical

### ISSUE THREAD

**Issue by GreatBlueMoon** [Regalis11/Barotrauma#10911]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

even after assigning them to focus rescueing/healing crewmates and whether or not they are set to do so they'l always prioritize hulls if theres a heavy leak even if you got others focusing said job (in my case 2 mechanics focusing leaks) and i dont mind other crewmates focusing hull repairs in a heavy emergency, or when people prioritize defending themselves as it does fit and doesnt end in a huge amount of pain where your the only one handling medical.

the tasks assigned to a crewmate should prioritize their emergency decision i think

### Reproduction steps

3rd biome
6+ crewmates
assign doctor to medical
assign mechanic/other classes to leaks
have heavy water pressure come in via lategame swarms

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
NA
```

**Comment by itchyOwl** [comment]
I suspect what happens here is that the potential targets are fixing leaks, so they get ignored. It seems ignoring targets that fix leaks was intentional, but it might have been a bad decision. Changed that in Regalis11/Barotrauma-development@5f83ea8. Other targets that are intentionally ignored are those that are fighting or fleeing/finding safety, because grabbing those targets might be dangerous/lethal.

Couldn't repro any other issues: the medics prioritize fixing leaks very little, and in any case, as an autonomous objective, fixing leaks shouldn't ever be prioritized over orders, unless the bot doesn't find anything to do with the order and thus idles.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
