### ISSUE TITLE
Feature suggestion: Revival with items via XML definitions

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1094]
**Description**
The idea is simple, allow certain command types (Specifically revive in this case) to be triggered via XML's like status effects. This way items like defibrillators can be added to the game via modding, for after a character has died - and be used to resuscitate a corpse.

**Additional information**
It would be a bonus if there was a way included for this to determine how long a character had been dead for, and for conditionals to target such, along with checking if all the limbs are intact / severed count.

Double bonus if conditionals can check if afflictions exist and in certain weights of the affliction (so certain conditions cannot be revived for instance).

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
