### ISSUE TITLE
Replace Structure WallSections with Hull edge sections

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#1096]
Having repairs be applied to the sections of structures sometimes makes it difficult to fix leaks because of sections that are difficult to reach. By making gaps appear relative to the edges of the hull objects instead, repairs would generally be easier.

**Comment by NilanthAnimosus** [comment]
I think it would help immensely if walls were not blocking other walls and hit through them partially.

Given most repair issues are due to hitting a different wall as most designs are stacking them.

**Comment by Regalis11** [comment]
I'm not sure if this is the easiest/best way to solve the problem. In some subs there may be walls that aren't next to a hull (for example some of the sloped walls in Typhon and multi-layered walls in some subs). I think I'd rather try making the repairtool raycasts fix all walls within range instead of just picking the closest one.
