### ISSUE TITLE
Something wierd is happening with junction boxes

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10978]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some odd reason in 100.14.0.0 the junction box sprites have changed, and since  had odd behaviours with pre-placed junction boxes, including on vanilla subs. For example, first of all, they flicker red for no reason really in the editor.

https://user-images.githubusercontent.com/104232152/213450294-f63c60ef-1b6c-4e8b-b19f-fcc6b8273d77.mp4

Secondly, for some reason the sprites on existing subs has not only changed, but is scaled differently, as you can see here. 
![image](https://user-images.githubusercontent.com/104232152/213450504-5a36bdf2-4832-4b1a-b749-07bb3a48bbb9.png)
The newly placed one is on the left, the one on the right is directly dragged from the Barsuk, notice the fact that its got a different shape and is overly dark, somewhat annoyingly, this issue persists on outposts and all vanilla subs.

### Reproduction steps

1.Look at junction boxes on any pre-placed places in the editor (aka any vanilla sub/outpost)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This happened as a result of the fix to https://github.com/Regalis11/Barotrauma/issues/10900.

The issue in Barsuk seems to happen because both of the light components (the green and red one) are set to be initially on. The scale doesn't seem to be different either, the box on the right is just a couple of pixels lower than the top one. Since this doesn't really cause any problems aside from that flickering, I think the ticket can be closed.
