### ISSUE TITLE
Quickdraw does not apply bonus damage 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10985]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Related to #10711

Quickdraw does not apply bonus damage 
There is an ordering issue; the affliction seems to be removed faster than the 
`<AbilityConditionHasAffliction afflictionidentifier="quickdrawing" minimumpercentage="1.0"/>` 
condition is checked, thus not applying the damage

Adding a small delay before removing quickdrawing seems to solve the issue; delay needs to be short enough to not affect the second bullet.

```xml
            <StatusEffect type="OnAbility" target="This" delay="0.1" stackable="false" disabledeltatime="true">
              <ReduceAffliction identifier="quickdrawing" strength="8"/>
            </StatusEffect>
```

Lightning wizard uses the same system but doesnt have this problem

### Version

0.20.16.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57e2da0a16547ca3b5cd227e77347eb2574d9e1f. The reason why the issue applied to Quickdraw but not Lightning Wizard was that Quickdraw reduced the affliction when the weapon is used and checked the affliction when the attack hits, and the former always runs before the latter. Lightning Wizard uses OnAttacked and OnAttackedResult instead.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
