### ISSUE TITLE
[DEV] Can't press the radio chat button again once you've already pressed it to cancel it

### ISSUE THREAD

**Issue by DataCrusade** [Regalis11/Barotrauma#1106]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
See the title.

**Steps To Reproduce**
Press the radio chat button - press it again and it doesnt cancel the message like it would with the regular chat. 

**Version**
Latest public version as of 2/9/2019.

**Comment by BillCombs** [comment]
It's intentional. See #1044
You will have to get used to pressing the normal chat button after pressing the radio button.

**Comment by NilanthAnimosus** [comment]
I still think maybe the chat cancel key should be its own bind, and to allow the same keys to be bound to multiple functions (IE. tab as radio and cancel, or changing it to escape yet keeping escape as the menu function).

By default for UK keyboards, it ends up being ' for OemTilde for some reason, instead of ~, effecting the chat by default.
