### ISSUE TITLE
AI crewmates incorrectly remove battery cells from exosuits

### ISSUE THREAD

**Issue by AtobaAzul** [Regalis11/Barotrauma#11099]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

AI Crewmates with the "Recharge battery cells" order remove the currently in-use powercells from exosuits, leaving them powerless.

### Reproduction steps

1. Power an exosuit
2. Order an AI crewmate to recharge battery cells

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@7eabe25. The load items objective automatically ignores all items that are inside preferred containers, but exosuit wasn't defined as such for the battery cells. An alternate fix for this would be to add the "donttakeitems" tag on exosuit, but that would make the bots unable to take the items from the suit if they needed them. Not a huge thing, but decided to add exosuits in the preferred containers of the battery cell instead.
