### ISSUE TITLE
Crippling limbs

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#111]
Have things possibly cripple and disable limbs like arms and legs.

Crippled leg results in slower speed, no running and a limping animation. Both legs forces you into a crawl.

Crippled arm denies use of two handed items and disables the respective arm slot usage. Comes with a respective animation. Both arms crippled is bad news because you can only pick stuff up into your inventory but not use anything.

Crippled limbs heal in a minute or more if you're at full health, or with a special chemical or medic exclusive item tied to their medical skill. Low medical should potentially hurt the player if they try to use it.

**Comment by G234i** [comment]
Add a serverside option to disable this as (depending on implementation) this will not be the most player-friendly feature because it can leave crippled players helpless until a medic comes by and "fixes" them which is a rare occurrence in open for all multiplayer servers. Not to mention that doctors prefer to inject every person with the husk parasite xD

**Comment by Crystalwarrior** [comment]
Oh definitely. I firmly believe that half of the core game features should be customizable to a huge degree straight from the .xml or host settings menu.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
