### ISSUE TITLE
No pressure warning before imploding (dying/exploding from barotrauma)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11163]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I went to a flooded part of a station in a diving mask. I imploded without overpressure.
Then another crew member went ther and also imploeded without pressure.
Then I went there again, which you can see in the video.
We're using quite a few mods, including Neurotrauma.
https://youtu.be/poonXXOGlIY

### Reproduction steps

1. Go to a flooded station without pressure warnings

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem to occur in the vanilla game
![image](https://user-images.githubusercontent.com/14351070/216920934-ef8f55b1-a2c6-4d73-8cc4-d1964ad3938e.png)

**Comment by Ek-Videogames** [comment]
Question: does the status effect only appear at 100% pressure?

I've noticed multiple times that it's possible to explode from pressure far before reaching what would generally be considered "pressurized" state in the hull - be it a bug or intentional. So it looks like a long exposure to medium-high pressure which is sufficient to cause death without actually triggering the status effect.

**Comment by Regalis11** [comment]
@Ek-Videogames 

I'm not entirely sure what you mean by status effect: there are no status effects involved in the pressure death. The icon should be visible when you're under pressure, and after a certain time, you should be given the insta-killing "barotrauma" affliction.

**Comment by Regalis11** [comment]
After taking a closer look at the code, I think I found the issue (even though I was still unable to repro this): it seems the pressure for showing the icon was slightly higher than the threshold at which the character starts dying. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d9fac79a2507dbe36372f01fd9e15966eb6ab6a

**Comment by Rokvach** [comment]
As there is no repro steps I just tried dying to barotrauma in different situations and didn't spot any issues with it. Seems to be working correctly, closing.
