### ISSUE TITLE
[Factions] Mysterious status monitor in colony

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11205]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A status monitor appeared in the admin module with a quest icon. It's not powered and doesn't seem to do anything

![image](https://user-images.githubusercontent.com/73229309/218222568-fa344eb7-2000-4a83-8477-3eb45bdec0dd.png)

![image](https://user-images.githubusercontent.com/73229309/218222516-53bfa14e-2929-4031-986d-3daa6298aa41.png)

The save file in question. I cheated in solo campaign for testing purposes
[Save 8.zip](https://github.com/Regalis11/Barotrauma/files/10712008/Save.8.zip)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It seems the status monitor wasn't the issue here: there's some fliers on that same spot in separatist outposts, but events didn't consider whether the item is hidden or not, so an event happened to trigger on those invisible fliers. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b8b19e5859d4945164c1c7a40ee88ba04cddc083 + made that status monitor only show up in separatist outposts https://github.com/Regalis11/Barotrauma-development/commit/f2a96c158ad2eb1a7eb8123eb690816c527a9198

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
