### ISSUE TITLE
Brakes- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1124]
This feature request implements into the game fourth behavior option for auto pilot: "Stop". It will cause submarine to reduce it's speed on both horizontal and vertical movement to 0 by pointing into selected areas on the sonar to accomplish it. Unlike "Maintain Position" "Stop" does not tell submarine to point at the same position all the time, it's task is not to have submarine be in the same place all the time but to prevent it from changing position regardless of current location.

Advanced:
If "Stop" A.I. detects a wall it may decide to take some speed in order to dodge it before collision occurs. Occurs only, when sonar is active or submarine generates enough power to lit the area on the map. It's a complex thing and perhaps should be considered a optional objective in this thread.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
