### ISSUE TITLE
Mutated raptorbane splatting can be heard very very far 

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#11252]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The sound of mutated raptorbane fruit popping can be heard at any point of the ship, perhaps even outside (?). The volume does not fall off with distance.

### Reproduction steps

1. Plant raptorbane in the stern of the ship
2. Be somewhere near the bow, far away from the planter
3. Noises of raptorbane spontaneously  exloding can be heard

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment]
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/c4b20982-c1d8-47b7-84e4-0a74ca9dd35e)

Need to test this. If it's this sound, the definition doesn't seem off to me. Also the other bad fruits have the same effect.

**Comment by mygamingaccount** [comment]
It sounds out of place

https://user-images.githubusercontent.com/68995233/220168851-ad5829ee-699f-416b-bd0a-d3c97d1992b0.mp4

Normally you can't hear small things. Flares, or welding tools, etc. are inaudible.
Things you hear at such a distance are explosions or gunshots.

**Comment by itchyOwl** [comment]
Cannot confirm that the sound could be heard from "very very far". The range is 1000 pixels (or 10 meters) and there is a falloff, though it is a bit steep, like on all the sounds. Also muffling by doors, walls, or diving suits seems to work (though in the video it doesn't seem to work). The sound effect is a bit out of place imo (because it's using the limb damage effect), but not so much that we should seek for a new effect.

So, all in all, there doesn't seem to be anything bugged here. But reduced the range and the sound volume 25% in Regalis11/Barotrauma-development@8b04140.

**Comment by Jasontti** [comment]
Tested and works.

Closing ticket.


https://github.com/Regalis11/Barotrauma/assets/8488224/dca869de-ec91-461c-b87d-93fa3f4b1fc7
