### ISSUE TITLE
Add Option in Submarine Editor to Make Spawn Points of Characters Depend On Their Karma- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1128]
What I mean is that with this request accepted in submarine editor player can set how low the karma has to be for the player to forcefully spawn in a selected place. 

There even is a optional setting allowing characters spawning at spawn point like that to spawn with no inventory.

Also if there is a specified job for a spawn point like that player needs to be that specific job to spawn there.

### Usage:

A spawn point like that can be put inside a prison cell. All players below certain karma level will forcefully spawn there. Disabling starting inventory will prevent them from escaping.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
