### ISSUE TITLE
[1.0] 3x 8x oxygen tank stacks spawn at colony modules in supply cabinets 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11333]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue was apparently "supposed to be fixed" (according to the discord chat) so I apologise if a ticket already exists; I couldn't find it.

In several of the colony modules, supplies cabinets will spawn 3x 8x oxygen tank stacks, totalling 24 oxygen tanks in a single storage space. The reason for this is not obvious and makes stealing them incredibly profitable, especially for harder campaigns. Whilst I don't know which modules specifically have this, I can confirm that several modules have this issue and it has happened since the first test campaign I hosted back in 100.0.0.0. 

![image](https://user-images.githubusercontent.com/105495756/221040645-d10c46c7-3d78-4f5d-b102-116883104135.png)

### Bug prevalence

Happens regularly

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b6a7b67bff149113749623dad1bac874fa82b3fa. I went through every colony module, using a debugger to see if any tanks are created when loading the module, and the only module with pre-placed tanks I could find was MedicalModule_02_Colony.sub (the one in the picture).

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
