### ISSUE TITLE
The inability to finish the game due to the generation of the world.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1133]
**Description**
SEED: WBWHhgU9
Submarine: https://drive.google.com/file/d/1QDFhAMMbqjUucGU0m0Hz8w4evIRr_Bja/view?usp=sharing
![20190213005531_1](https://user-images.githubusercontent.com/33912761/52670936-e7775480-2f2a-11e9-9010-5f491872ed41.jpg)
Red - ice;
Green - outpost.
*I then wanted to get the achievement of "The lone sailor". This generation does not interfere with multiplayer, but in a single game to finish the game impossible.*
And Yes, I didn't get the achievement. :c

**UPD**
All multiplayer achievements are impossible to obtain. As if they can only be obtained in a single game. It's confusing.

**Version**
Steam.

**Comment by rico6822** [comment]
I think it was implemented by developers to make achievements obtainable only in single player since in multiplayer player doesn't need to use credits to purchase crew, crew resurrects entirely upon leaving the mission and players are in fact smarter than bots.

By the way:
It's an old bug. Several people reported before levels which generate the way they prevent submarines from passing by.

**Comment by Regalis11** [comment]
It should be possible to unlock achievement in the multiplayer as well, but only if the server doesn't have cheat commands (= things such as godmode, fixwalls, killmonsters, spawnitem...) enabled. It could be bugged though, I'll do some testing and see if it's actually working as intended.

**Comment by Regalis11** [comment]
Could you please send the save file if you still have it? I wasn't able to find those locations on the map, so I'm guessing they appear later during the campaign.

And another thing to note, docking the submarine to the outpost is not required to finish the level. You can exit as long as the submarine is close to the end of the level and a member of your crew is inside the outpost.

**Comment by NilanthAnimosus** [comment]
For the record, when hosting my server from visual studio and without visual studio, I recall many earning achievements fine (Both before and after switching over to VS) so I am not so sure it's bugged.

I think I also saw clients get informed if cheats were activated too when playing on a server other than my own during the test.

I believe the visual studio (In debug mode) hosted version appears to allow cheats without using the command, though I've never used commands really other than one time going for debugdraw due to spotting a bug.
