### ISSUE TITLE
[1.0] Creatures ignore abyssal restrictions

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11344]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A Giant Spineling chased our sub deep into the abyss and refused to retreat as it is coded to do so (since `avoidabyss='True'`). Creatures will naturally leave the abyss the moment they enter if they are coded to avoid the abyss. This is why the Giant Spineling's behaviour was not only concerning, but widely confusing as it should not be able to do this. 

Another instance of this is the Latcher. Over the last few months, I have received several anecdotal reports into the Latcher being able to leave the abyss whilst hunting a player sub. This happened to me personally, as a Latcher has chased my sub as far as the level's end docking hatch before it pulled the sub back into the abyss. Looking at the xml code did not immediately present any issues (aside from `StayInAbyss` and `AvoidAbyss` being CamelCase in the Latcher's xml file, but completely devoid of capital letters in the Endworm's xml file which was used as a control variable. I doubt the issue is due to that, however).

The two different instances mentioned above make me believe this issue isn't due to level generation, but something to do with creature aggression overriding other coded parameters such as staying within the abyss and avoiding it. I believe this as both recorded instances occurred when a hostile creature was pursuing a submarine into a restricted area.

![image](https://user-images.githubusercontent.com/105495756/221051426-4a067c05-6ad7-479e-a94e-896b627b6a6b.png)
_Figure 1. Body of dead Giant Spineling in the abyss._

![image](https://user-images.githubusercontent.com/105495756/221051462-b918da6d-36c8-4c02-9478-9d4c7cad2a61.png)
_Figure 2. Freecam + Debugdraw image demonstrating submarine's relative position in the map, proving that the Giant Spineling did indeed enter abyssal territory._

![image](https://user-images.githubusercontent.com/105495756/221051570-a9768b26-9369-43a7-9575-5a358300cfd9.png)
_Figure 3. Level seed._

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.0.3.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Intentional when the creatures are chasing a target. Otherwise they should stay "where they belong to". Is it an issue?

**Comment by duarm** [comment]
Not once you know about it, but I've always considered the "run away strategy" to or from the abyss since I knew about the monster's biology, once I got to implement it as the captain, I was upset it didn't work.

**Comment by Wheatley1002** [comment]
Surely if the behaviour is intentional, it invalidates the Doomworm's gimmick? Especially since abyssal creatures can technically remain outside the abyss if it constantly chases the target (which they tend to do due to their high sight and hearing stats). Whilst I understand the Doomworm is a placeholder which may or may not be getting axed, I also noticed that the xml file was edited quite heavily in the 1.0 build.

**Comment by Regalis11** [comment]
> Surely if the behaviour is intentional, it invalidates the Doomworm's gimmick?

I don't think it does: there's a difference between the monster hanging out above the abyss and the monster following you up from the abyss if you happen to run into it down there. But yeah, Doomworm is a placeholder (that has now been replaced with something else at the end of the campaign) and we shouldn't be doing any design decisions to accommodate for it.

**Comment by Wheatley1001** [comment]
The two parameters "avoidabyss" and "stayinabyss" are what made me believe that creatures set to stay in the abyss would stay in the abyss. If this is a case of misunderstanding game mechanics, I'll add the information to the wiki to state that abyssal creatures _can_ leave the abyss if chasing a target to prevent future confusion.
I know this is anecdotal, but the reports about the Latcher leaving the abyss and none of the other abyssal creatures leaving might be something to look into. Up until the time of the report, I had only seen the Latcher leave the abyss and heard other people report the Latcher being able to leave the abyss. Normally swarm creatures will turn and abandon their target if it enters the abyss, and the same goes for abyssal creatures if the target leaves (though again, this is purely anecdotal and taken from a gameplay perspective rather than how the mechanics actually work).

![image](https://user-images.githubusercontent.com/105495756/226180721-d10a3309-11af-496e-a401-c5d9cf28e84f.png)
_Taken from the Endworm's xml file_

**Comment by itchyOwl** [comment]
Note that the abyss monsters won't target anything above the abyss, unless they first target something in the abyss. I'm still not convinved that this is an issue.

**Comment by duarm** [comment]
After playing some more, this issue shed light on a what I think it's balance issue. I just slightly fell into the abyss, which was enough to lure an endworm, I dodged her 10 times but it ended up hitting us near the outpust we planned on docking, after 10 minutes of intense fleeing, it was kinda of unfair since we played so well and ended up still losing because of sheer attrition with the monster we had no chance of killing. There needs to be another way of escaping these monsters, being a more inteligent de-aggro method or abyss restriction, dunno.

**Comment by itchyOwl** [comment]
Sorry for a late response.

> There needs to be another way of escaping these monsters, being it a more inteligent de-aggro method or abyss restriction, dunno.

There is. By keeping silent, because the abyss monsters primarily navigate with sound. Try to turn off your sonar and engine. Lay still until the monster loses interest. Then repair your sub. And start moving _quietly_ and _slowly_ outside (up) from the abyss. Don't use the sonar, or only use it for brief moments. Prefer directional ping. Don't go too fast (makes noise). Depth decoys help. And realize that it doesn't always succeed, because the abyss monsters move fast. So if they happen to be nearby, you can't go unnoticed without turning the engine off. So if you notice their precense (orange waves on the sonar), try to turn off the engine for a while and just let the sub float/sink for a while, then try again.

Escaping the Latcher is slightly more straightforward: shoot it so that it escapes, then burst away full speed, then turn off the sonar and continue moving slowly. Can also work with Charybdis, if you manage to hit the head with a railgun, but can be tricky...
