### ISSUE TITLE
Sonar Flora obscured by wall detail

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11359]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sonar flora can be almost completely obscured by wall details. Not exactly a game breaking bug, but something that should probably be corrected at some point. 

Example Images:

![image](https://user-images.githubusercontent.com/92034548/221333644-acd4120d-3b67-4b09-b02d-5ff1251900d7.png)

![image](https://user-images.githubusercontent.com/92034548/221333655-e8b35fcd-1950-45b3-99a8-9bb0e1226efd.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Internal note: looks like this is not trivial to fix as I would've expected, because the sonar flora uses deformable sprites which cannot be sorted normally with normal sprites. Might be wort considering to just make them larger and more offset from the wall to make sure they're visible even if there's something in front of them.

**Comment by Regalis11** [comment]
Looks like there was a simple fix to this after all: the level objects are sorted into 3 batches (front, mid, back), and moving them to front took care of the issue. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dcf706a88f340c290e144b0dbbbdd7e8f0c299ff

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
