### ISSUE TITLE
Disappearing Level Objects

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#11390]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

**What Happened:**
While I was playing Frith's Biomes, a mod that makes levels more immersive, I entered a cave and noticed that some level objects were disappearing while I swam around.

**What I Expected to Happen:**
The level objects in my field of view should've always been visible.

**Video of the issue:**
https://user-images.githubusercontent.com/67431770/221738763-02140c16-32c8-44d1-a646-2357f3f2e4fd.mp4

### Reproduction steps

1. Enable [Frith's Biomes](https://steamcommunity.com/sharedfiles/filedetails/?id=2020332046).
2. Load into any level with a cave.
3. Enter the cave and swim around for a bit.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed to some extent in https://github.com/Regalis11/Barotrauma-development/commit/243af0eeea32b6e2d6051bd2d13302b927054dc2

> Improvements to LevelObject culling:
> - Ignore LevelObjects that have nothing to draw (e.g. water currents) when determining which objects to draw.
> - Prefer rendering objects in the foreground if some objects need to be culled due to the maximum number of visible objects being reached.
> - Prefer rendering objects at the center of the view.

This does not entirely fix the issue of the objects appearing and disappearing, but it makes it less noticeable. I would say that we shouldn't even make the game try to render the amount of level objects that can be on the screen at the same time in this mod, because it's almost guaranteed to cause performance issues. The amount of objects is unreasonable: there can be 10,000 objects in a single cave (more than the entire level in the vanilla game), with an enormous amount of overdraw (tons and tons of objects on rendering on top of each other). I think the amount of objects in the mod could be drastically reduced without any noticeable effect on the visuals.

**Comment by Rokvach** [comment]
Tested this with the Frith's biomes, there was one area of a cave where the background rock texture was vanishing when I moved my camera around but doesn't seem as drastic as on the provided video, so this seems to be an improvement but as Regalis mentioned above it doesn't fully fix the issue and we shouldn't try to fully fix it. Closing.
