### ISSUE TITLE
[1.0] Cultist Hood overlaps with Exosuit

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11404]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you wear the Cultist Robes, the hood floats on the Exosuit.

![image](https://user-images.githubusercontent.com/105495756/222260412-3be75ee2-5cad-43ad-b179-4765d990562d.png)

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67088c5f7093b002b96537460f1d03138b780b61. Note for testing: check that this doesn't cause any problems with other wearables, e.g. https://github.com/Regalis11/Barotrauma/issues/10456, https://github.com/Regalis11/Barotrauma/issues/10308, https://github.com/Regalis11/Barotrauma/issues/11058

**Comment by Rokvach** [comment]
Apparently not an issue, so working correctly. Closing.
