### ISSUE TITLE
[1.0] Coalition Submarines are less equipped than Separatists

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11423]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Separatist submarines (pirates) are pre-filled with equipment, Coalition (vanilla) submarines are not and only rely on autofill tags

Compare Dugong vs DugongPirate

For the future, merge all hostile submarines from all factions into one "interception" submarine, and impelement faction item groups just like outpost to make a faction variation (clown/husk too) of each submarine?
![image](https://user-images.githubusercontent.com/73229309/222321109-5d9eadff-92ca-414d-9d72-2f63732dd212.png)

### Version

1.0

**Comment by itchyOwl** [comment]
This is an oversight: they should be similarly equipped. Currently coalition vessels are equipped like the player subs without the starting items, which is not intentional, which is because they actually are the same submarines. I think the best solution would be to **a)** reuse the pirate subs for all enemy subs with faction-specific layers, like I think was proposed by the author, or **b)** define and maintain separate submarines for all the enemy subs. Shouldn't use the submarines meant for player use. If the option **a)** isn't too much work, it would be preferable, not least because it's easier to maintain.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/3990. Tested & merged
