### ISSUE TITLE
Mining mission: cave minerals spawned on the wrong side of the cave

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11434]
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/1c01e2f3-97c6-4a99-a090-355c1dd6387e)[Save file](https://app.zenhub.com/files/93301055/ca5999f9-2089-499d-841a-e5a5c905f29b/download)

**Comment by kocyk5125** [comment]
![image](https://user-images.githubusercontent.com/61655430/225450112-93285929-834e-4069-a9be-ecebfac3f9d4.png)
Bug still prevalent in 1.0 release, encountered at 1st biome.
![image](https://user-images.githubusercontent.com/61655430/225450220-d44bb142-60d9-49d2-b80e-5f7bc614deaa.png)

**Comment by itchyOwl** [comment]
Yeah, it's not yet fixed.

**Comment by Regalis11** [comment]
It seems the issue here was how we marked edges as being "next to a cave". We marked all of the edges of the cells lining the cave like this (red lines indicate edges that are "next to a cave"):

![image](https://user-images.githubusercontent.com/14351070/232034586-67dbcad7-b9fc-4076-af74-1bbda614f4b9.png)

See how there's an edge that's outside the cave at the bottom-right corner. I changed the logic so it only marks the edges that are actually lining the cave:

![image](https://user-images.githubusercontent.com/14351070/232034813-6b278de4-6f20-4245-9cbf-8e03026b2371.png)
