### ISSUE TITLE
Make Captain Having More Vitality- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1143]
Why is the captain having vitality modifier set to -20? I think he should have the same as his officers.

Can we make vitality modifiers randomized so crew members would be more different? Characters would be less clone-like.

**Comment by BillCombs** [comment]
I think making it random wouldn't be fun in multiplayer where pvp situations can easily happen. Having more or less vitality than your opponent just because you got the lucky/unlucky number wouldn't feel fair.

Perhaps it could be a thing in the singleplayer campaign. You could see how healthy a crew member is when hiring them, and, if you had extra money, you could hire tougher ones.

**Comment by rico6822** [comment]
> I think making it random wouldn't be fun in multiplayer where pvp situations can easily happen. Having more or less vitality than your opponent just because you got the lucky/unlucky number wouldn't feel fair.
> 
> Perhaps it could be a thing in the singleplayer campaign. You could see how healthy a crew member is when hiring them, and, if you had extra money, you could hire tougher ones.

I know:
In multiplayer host decides if it is random or not.

**Comment by Regalis11** [comment]
The intention was to make the captain a sort of "glass cannon". All of the classes are strong in some aspects and bad in others, and since the captain is a very powerful class (both in the sense of having authority over the crew, and also in the sense of having a powerful weapon and a high weapon skill), I think giving them a little less health is a good way to keep things more balanced.

I'm not sure if the randomized vitality would work that well in practice. If there's lots of variation, it makes the classes less balanced and adds an (in my opinion) unnecessary luck factor into the game. If the variation is small, it will be barely noticeable - I would argue that even the current 10-20% variation between the classes doesn't make any significant difference most of the time.

In the single player campaign however I think it could be a good idea. Especially if it's tied to character progression.

**Comment by rico6822** [comment]
> The intention was to make the captain a sort of "glass cannon". All of the classes are strong in some aspects and bad in others, and since the captain is a very powerful class (both in the sense of having authority over the crew, and also in the sense of having a powerful weapon and a high weapon skill), I think giving them a little less health is a good way to keep things more balanced.
> 
> I'm not sure if the randomized vitality would work that well in practice. If there's lots of variation, it makes the classes less balanced and adds an (in my opinion) unnecessary luck factor into the game. If the variation is small, it will be barely noticeable - I would argue that even the current 10-20% variation between the classes doesn't make any significant difference most of the time.
> 
> In the single player campaign however I think it could be a good idea. Especially if it's tied to character progression.

Sounds good.
