### ISSUE TITLE
Shadowcasting enabled on submarine lights is ignored on outposts

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [Regalis11/Barotrauma#11463]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Exterior lights on a submarine that are set to cast shadows don't cast shadows on outposts, making their light brighten up the entire outpost.

Light is set to cast shadows:
![image](https://user-images.githubusercontent.com/74098498/223055116-f4b0e6e5-db0e-45b6-912c-e843537cbb14.png)

Video that shows it doesn't cast shadows on outposts:
https://youtu.be/nZW8WzyrQJA

### Reproduction steps

1. Create a submarine on Faction branch
2. Set exterior lights to shadow casting
3. Visit an outpost in campaign

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3d14b4b846182797301a69f51e5f2e53822b084

**Comment by Regalis11** [comment]
Looks like this was actually a wider issue than I though: it doesn't just apply to the lights in the sub, but all lights - e.g. a flashlight inside the outpost would also shine through walls. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b7d0013c56e791e2f4b7d93a1b54f0d7e81b4e03
