### ISSUE TITLE
When Using ANY Medical Items on Crewmembers for Healing, Karma is Decreased

### ISSUE THREAD

**Issue by BDToneMain** [Regalis11/Barotrauma#11506]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When Using ANY Medical Items on Crewmembers for Healing, Karma is Decreased

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

What kind of medical items specifically? I gave a test to a bunch of medical items, and could not spot anything out of the ordinary. Opiates do seem to cause a minuscule karma hit (-0.001 karma) on default settings due to the oxygen loss affliction it causes as a side-effect, but it's so small it makes no difference in practice. And if you're actually treating some injury, not just injecting morphine on a healthy character, the karma boost from the healing makes the decrease even more irrelevant.

**Comment by BDToneMain** [comment]
Primarily blood related items like saline and blood bags. Horribly overdosing someone on ABX to combat husk was fine, but combating blood loss with any kind of blood item (not alien blood) caused a massive dump in karma.

**Comment by Regalis11** [comment]
Ah, thank you for the clarification! I was able to repro the issue with blood packs now. It seems it also requires that using the medical item makes the patient's health go up - treating a full-health character seems to have no effect. 

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea94b902653a31b8fd17deacf6c2baf1c381c323

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
