### ISSUE TITLE
Give Characters Skill Level Limits- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1156]
### Entire Concept:
Amount for every character, which determines maximum skills is randomly generated.

Example on Captain:
Helm <65;80>
Weapons <40;50>
Mechanical <30;40>
Electrical <30;40>
Medical <20;30>

If starting skill level gets randomly generated above maximum level possible or is equal to it maximum level gets equal to current value and than gets randomly increased from 0 to 5.

**Comment by Regalis11** [comment]
You mean a maximum skill level in the sense that the level can't increase above the limit even if the character gains exp? Tbh I don't see why that would be necessary.

**Comment by rico6822** [comment]
> You mean a maximum skill level in the sense that the level can't increase above the limit even if the character gains exp? Tbh I don't see why that would be necessary.

That's what I mean. Different people are skilled in different things. It comes genetically.

**Comment by Regalis11** [comment]
Honestly I don't quite see the need for this. I get your point about different people being skilled in different things, but it could be argued that all of the crew members would be able to learn to use the machines, items and such with enough training regardless of their genetic predisposition.

I also don't feel becoming "overpowered" is a major concern. If you somehow manage to keep a character alive for dozens of rounds and get all of their skills to a high level, why shouldn't you be rewarded for that? I think it'd be cool if near the end of the campaign you had a super-experienced character or few who can potentially manage most of the tasks on board the sub by themselves - and then most likely having them die at some point anyway, making the death much more significant.

**Comment by NilanthAnimosus** [comment]
Actually despite the fact I would never have given it any thought, I think it should be possible for all characters to get every skill, but perhaps with a learning penalty for things far outside ones field. Most people generally do not learn to do everything.

I don't know if the experience required to raise a skill scales to the level your about to gain (IE. 35 costs more than 34) or the specifics of these mechanics, but I've found it very hard / almost never occuring for a high-skilled engineer to gain any electrical skill at all (Or if there is even any bonus to it), conversely I found it capable to get the necessary skills to be a mechanic for most engineers in a single run.

in a long campaign, it likely wouldn't take much to get multi-skilled characters as-is. and I feel maybe a doctor should learn far slower than a mechanic for electrical, but a security could learn medical faster (If there is/was a way to) than say, a mechanic. sort of like a per-skill experience rate based on the likeliness for them to easily learn it.

I also feel all skills should be able to hit 100 through some means, even if the training is provided out-of-game IE. at the campaign menus like purchasing some kind of training course, these are things I wouldn't mind seeing.

I also think if a character had hit milestones in certain skills, they could be penalized a little for earning more in other skills, there is likely only so much someone would know or learn reasonably, otherwise why should they only exist on your crew, and not have purchasable outlier crew members for a more extortionate credit cost?
