### ISSUE TITLE
[dev] directional sonar shouldn't stop listening to sounds from other directions, enabling it right now essentially just blinds you

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1157]

**Comment by Regalis11** [comment]
I don't think I understand what you mean: it does stop listening to sounds from other directions, only showing ones that are coming from within the sector you're pinging towards.

**Comment by etet2** [comment]
typo, meant to say shouldn't

**Comment by Lynkzz** [comment]
Agreed. I'm not sure what the point of it is right now since it's a tiny cone as well. Like etet2 said, it currently just blinds you.

It'd be nice if you could change the size of the cone and the thinner you make it the deeper and more accurate the "view" you get (so you could perhaps use it when next to a ruin to get a more accurate "map" of them). Right now it's just too thin to be useful and there doesn't seem to be any upside compared to the 360 degree sonar.

**Comment by etet2** [comment]
the one upside is that you can scan stuff without alerting monsters(they are attracted to sound and sonar is the loudest object in the game), but at the momment you can just use passive and you dont allert monsters and get to see all around you

**Comment by Lynkzz** [comment]
The directional sonar doesn't make noise? I thought it did considering how it makes an audible 'ping' sound and it's listed under active sonar. You mean it only alerts mobs inside the cone that's being scanned? If so, that's pretty unintuitive considering that's not how sound works in real life.

**Comment by etet2** [comment]
well that's actually how real sonar works.

**Comment by AbominationBanisher** [comment]
i don't think that real sonars can ping in a specific direction, correct me if I'm wrong

**Comment by Regalis11** [comment]
I think this isn't necessary anymore now that the passive sonar has been nerfed - it doesn't show your surroundings as clearly and has a lower range, making the directional sonar much more useful.
