### ISSUE TITLE
[dev] xml option for wearables to hide hair, usefull for hats on people with long hair

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1161]

**Comment by itchyOwl** [comment]
So, are you asking that wearables could hide other wearables? Currently items can hide all other items and limbs. Wearables defined in the character config xml (hair and stuff) can disallow other werables defined by the "disallow"="partialspritename" attribute. But no, currently it's not possible for a hat (item) to hide a hair.

In principle we could just hide all hair behind a hat. But would that work if the character had a long hair? I think we'd need to introduce another attribute for the hair to mark that it needs to be hidden if the character has a hat. But then again it depends on the hat: not all hats should hide all hair that is marked as hidable. So we'd need to evaluate both. Yes it's possible, but I'm not sure about it. Maybe some day ;)

In the mean while, you could make the hair small enough to fit behind and the hats large enough to cover the hair.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
