### ISSUE TITLE
Searchlights not working

### ISSUE THREAD

**Issue by LardalsHuldra** [Regalis11/Barotrauma#11629]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After purchasing a new sub (humpback) and selecting a mission, the searchlights on the sub does not work. It is difficult to find targets without the light. For some reason, when I am not using the periscopes and hovering the mouse somewhere outside the sub, the searchlights start working. But when I hover the mouse on the inside of the sub, the searchlights stop working again. They never work while using the sub's weapons anymore. I could not get them to work when tinkering with the wires either. 

Thank you for your time. 

### Reproduction steps

1. Start a single player game.
2. Purchase a new sub (humpback)
3. Select a mission
4. Observe the searchlights on the sub's weapons not working

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This sounds like it might be caused by the "active light limit" which can be adjusted in the graphics settings. I'm fairly sure increasing it or setting it to unlimited should fix the issue.

Regardless, I don't think the turret lights should get hidden this easily (if ever) no matter what the limit is set to. I decided to change the logic a bit and heavily prioritize turret lights over everything else. https://github.com/Regalis11/Barotrauma-development/commit/9178382bc5e8436b38dd304b27b507bc1a0b76b9

**Comment by LardalsHuldra** [comment]
Hello,
That seemed to fix the problem, thanks!

Kind regards,
Eirik

tor. 23. mar. 2023 kl. 01:06 skrev Joonas Rikkonen ***@***.***
