### ISSUE TITLE
Azimuth is overtiered

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#11675]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Being the only sub in its tier without any heavy hardpoints and only coming with 3 diving suits, while being more expensive than something like the Humpback or Orca 2, Azimuth feels overtiered as tier 2 and would probably fit better as a tier 1.

![kuva](https://user-images.githubusercontent.com/86321358/227982407-bc0d1022-738b-4ac7-9c8a-b41bbe7512d2.png)

### Reproduction steps

Compare Azimuth to other tier 2 subs

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Koku0** [comment]
I agree with the Azimuth's lacklustre design. In my opinion, it should stay at Tier 2 and be buffed instead of being put into Tier 1. For what it's worth, I'd replace one coilgun with a double coilgun, add a couple of extra diving suits, and add a Navigation Terminal-controlled discharge coil upon the dorsal hull near the docking hatch.

This is my uneducated sub designer opinion, but I think that these buffs would make it comparable with the Orca2, especially since it surpasses its Tier 2 scout rival in speed and maneouvrability.

**Comment by JeroonBosch** [comment]
Agreed the Azimuth is currently underwhelming. It is the submarine with the best engine force relative to it's size (read: it's fast) which probably shouldn't be underestimated, but it could have a few more plus points.

**Comment by Jallu** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4147
