### ISSUE TITLE
Nonexist Captain in wreck, Issue ID card, locked Secure Steel Cabinet 

### ISSUE THREAD

**Issue by PlayeRocket** [Regalis11/Barotrauma#11708]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I found the wreck but the captain wasn't there and the medic's and security officer's ID didn't open the Secure Steel Cabinet and some of the doors.

![image](https://user-images.githubusercontent.com/63512746/229313321-f3905669-5cdb-40a0-b3e0-4b90a83e77e0.png)

### Reproduction steps

1. Entering a campaign 
2. find the wreck
3. Perhaps not find a captain or Secure Steel Cabinet

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by dakkhuza** [comment]
Happens because the secure cabinet requires id card tags with either `wreck_security` or `wreck_captain` to open but none of the spawn points for security or captain corpses have these tags on them, meaning it's impossible to ever open this in normal gameplay. Maybe at some point these tags were auto-asigned?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3b768b29e70a40f08ab593e817ddb2f91d2f25b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
