### ISSUE TITLE
Glowstick can not be "light on" in inventory by double mouse click anymore.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11755]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In previous versions of the game, the glowstick could be lit by mouse double-clicking, without taking it out of the inventory. 
It was logical and perfect. The real glowstick needs just to be bend to make it glow. No need to throw it.
Now the glovstick can only be ignited by throwing it.
Please return it the same as before.

### Reproduction steps

Take glowstick and double-click on it. Nothing happens.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
You can light them simply by left-clicking while holding one. Being able to light them by clicking on the inventory icon [was a bug that we fixed in v1.0](https://github.com/Regalis11/Barotrauma/issues/11065), because it made it impossible to move them between slots, equip, or unequip them without lighting them up.
