### ISSUE TITLE
Linux Closed Testing: Autocomplete only works once

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1177]
On Linux, autocomplete (by pressing Tab) works for the first command. Once as the first command has been entered, pressing tab at any point -- regardless of what the first letters are -- autocompletes to the old autocomplete solution. This essentially renders autocomplete useless, which is strange because it works on Windows and the old Linux build (0.8.2.3)

Eg: (where '->' is pressing tab)
enablech -> enablecheats (this is correct)
spawnit -> enablecheats (this should be spawnitem)
godmo -> enablecheats (this should be godmode)

incorrect autocomplete seems to vary based on what the first autcompleted command was. Commands themselves still work.

**Comment by CommanderMark** [comment]
Was looking into this along with #1175 and found that...

[This delegate](https://github.com/Regalis11/Barotrauma/blob/e487504c796bb2dd2aa623d84f16e16c4fb60c91/Barotrauma/BarotraumaClient/Source/DebugConsole.cs#L76) never triggers...

...because [this line](https://github.com/Regalis11/Barotrauma/blob/e487504c796bb2dd2aa623d84f16e16c4fb60c91/Barotrauma/BarotraumaClient/Source/GUI/GUITextBox.cs#L723) never triggers...

...because [this line](https://github.com/Regalis11/Barotrauma/blob/e487504c796bb2dd2aa623d84f16e16c4fb60c91/Barotrauma/BarotraumaClient/Source/EventInput/KeyboardDispatcher.cs#L35) never triggers...

...because [this delegate](https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaClient/Source/EventInput/EventInput.cs#L112) never fires since [the only code calling it](https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaClient/Source/EventInput/EventInput.cs#L200) is wrapped in a `WINDOWS` preprocessor.

So this giant chain relies on some Windows-only features it seems. It probably needs to be changed for other OSes.
