### ISSUE TITLE
how do medicines work?

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#11780]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

sry for poor english

so, i did some testing

I experimentally calculated the approximate probability of success when using medications

| your medical skill | items required medical skill | probability of success |
| ------------------- | ------------------------------ | ------------------------ |
| 5 | 25 | 75% |
| 5 | 50 | 59% |
| 5 | 75 | 29% |
| 5 | 100 | 3% |
||||
| 49 (red) | 100 | 44% |
| 50 (yellow) | 100 | 51% |
| 90 | 100 | 91% |
||||
| 0 | 25 | 75% |
| 25 | 50 | 78% |

i can't see the pattern here
can someone please explain how medical skill works, here or on wiki or elsewhere

also i've noticed your skill become red if it's below 1/2 of required, this seems to have no effect

### Reproduction steps

i've made a [mod ](https://steamcommunity.com/sharedfiles/filedetails/?id=2959456088) for this test, so that  i don't die from aging while performing the test

it overrides medical items: Opium, Morphine, Fentanyl and Deusizine
their required skills now: 25 50 75 100
they all do total 10 organ damage on success and 90 on failure in 0.5 sec
also stack size increased to 63 (max)

1. use mod
2. go to sub editor, load any sub
3. bindkey m "setskill medical 5" (you need this because you will gain skill in process)
bindkey j heal
4. spawnitem Opium inventory 100
5. open your health gui
6. spam dclick on item -> j -> m
7. count the number of successful attempts, divide by item count (100)
8. i did at least 200 attempts for table row

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by G3jzer** [comment]
Medical items use the Success Rate formula you can find on the [Skills](https://barotraumagame.com/wiki/Skills) page on the wiki.

100 - (Required Skill - Character Skill)

For example let's take an item with 25 skill requirement used by a character with 5 skill:
100 - (25 - 5) = 100 - 20 = 80
You have an 80% chance to succeed and get the full positive effects.

Now a character with 25 skill:
100 - (25 - 25) = 100 - 0 = 100
You have a 100% chance to succeed and get the full positive effects.

Exceeding the requirement provides no benefit other than guaranteed success.

If you have further or other questions i recommend asking in the baro-questions-and-answers text channel on the official discord instead of doing it through a bug report on github.

**Comment by SomeRandomNoobKekeke** [comment]
ok
