### ISSUE TITLE
大型鋼櫃 標籤 (can't contain uranium and lead in a large steel cabinet)

### ISSUE THREAD

**Issue by baby9210490** [Regalis11/Barotrauma#11787]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

Barotrauma  中的大型鋼櫃 標籤無法在部分材料上生效，導致櫃子無法放入特定物品，比如:

uranium 鈾
lead 鉛

### Reproduction steps

[保存 9.zip](https://github.com/Regalis11/Barotrauma/files/11185825/9.zip)

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Unfortunately no-one in the team speaks Chinese, but if Google Translate got this right, it sounds like the issue is that uranium and lead can't be contained in large steel cabinets. 

I gave the provided save a test, but unfortunately could not reproduce the issue. The save includes a large number of mods though (which I didn't install for testing this), so could be one of the mods is causing the issue?

![image](https://user-images.githubusercontent.com/14351070/231105931-5a374149-70c6-4207-91db-8186066ff325.png)

**Comment by Regalis11** [comment]
Insufficient information to address the issue.
