### ISSUE TITLE
A Few Changes to Carrier- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1182]
* Carrier should show up only on "Salvaging a Derelict" mission. I don't believe coalition is so unprofessional to crush several cargo vessels with chemicals like that. Coalition would notice for sure strange object like that moving anyway, so they could task someone to investigate it.

* Description of "Salvaging a Derelict" changes upon completing it once. I believe xml files should feature a possibility of predicting that upon completing the mission coalition won't believe for second time a vessel "magically" decided to give the lost cargo for it's own.

* Carrier should have it's own loot.

* "Salvaging a Derelict" should occur less often. Like I said before Coalition is not so unprofessional to crush so many shuttles.

**Comment by Regalis11** [comment]
I think you've slightly misinterpreted the "story" of the derelict mission. Which is of course understandable, because the few pieces of texts don't reveal much about what's going on.

The idea behind the mission was something like this:
1. Someone was transporting cargo from an outpost to another. There's no implication that it was a Coalition vessel, it could've been some average joe who hauls cargo with his old shuttle every now and then to make a bit of extra cash.
2. Some kind of alien organism or thing took over the shuttle. 
3. The nearby outposts noticed the shuttle had gone missing. Someone might have gone looking for it (or not), but in the end it was not found. Perhaps because the organism didn't want to be found yet, or because the shuttle was somewhere in the abyss, too deep to be reached.
4. The shuttle reappeared and turned on an emergency signal, maybe to attract other vessels on purpose.
5. Your crew agreed to go and investigate the signal and found out they had to "kill" the shuttle.
6. After the mission you tell about this to the researchers, and they "are eager to know all the details of the encounter, but seem hesitant to answer any questions". Implying that they know something about what happened to the shuttle, but are reluctant to tell you.
7. Average joes, private shipping companies, etc keep transporting cargo, and every once in a while the same thing happens again.

As said, the mission descriptions and such aren't really enough to piece out the whole story or even to get a clear idea of what the world is like. But this will change as we start expanding the campaign and adding more NPC dialogue (not just between the crew but also between the NPCs in outposts).

**Comment by rico6822** [comment]
> I think you've slightly misinterpreted the "story" of the derelict mission. Which is of course understandable, because the few pieces of texts don't reveal much about what's going on.
> 
> The idea behind the mission was something like this:
> 
> 1. Someone was transporting cargo from an outpost to another. There's no implication that it was a Coalition vessel, it could've been some average joe who hauls cargo with his old shuttle every now and then to make a bit of extra cash.
> 2. Some kind of alien organism or thing took over the shuttle.
> 3. The nearby outposts noticed the shuttle had gone missing. Someone might have gone looking for it (or not), but in the end it was not found. Perhaps because the organism didn't want to be found yet, or because the shuttle was somewhere in the abyss, too deep to be reached.
> 4. The shuttle reappeared and turned on an emergency signal, maybe to attract other vessels on purpose.
> 5. Your crew agreed to go and investigate the signal and found out they had to "kill" the shuttle.
> 6. After the mission you tell about this to the researchers, and they "are eager to know all the details of the encounter, but seem hesitant to answer any questions". Implying that they know something about what happened to the shuttle, but are reluctant to tell you.
> 7. Average joes, private shipping companies, etc keep transporting cargo, and every once in a while the same thing happens again.
> 
> As said, the mission descriptions and such aren't really enough to piece out the whole story or even to get a clear idea of what the world is like. But this will change as we start expanding the campaign and adding more NPC dialogue (not just between the crew but also between the NPCs in outposts).

I didn't tought coalition is already aware of that shuttles like it keep reappearing. I though they simply lack dialogue for this incident to reappear. They also always state they send a shuttle like it 2 months ago. They always say it.

**Comment by Regalis11** [comment]
Yeah, I agree that there should be (and will be!) more variation in the mission descriptions. But expanding the current mission description system is not worth the effort at this point imo, since it will go through major changes anyway when we start implementing the physical outpost (in which you'll talk to NPCs to receive missions).

**Comment by rico6822** [comment]
> Yeah, I agree that there should be (and will be!) more variation in the mission descriptions. But expanding the current mission description system is not worth the effort at this point imo, since it will go through major changes anyway when we start implementing the physical outpost (in which you'll talk to NPCs to receive missions).

That's great.
