### ISSUE TITLE
add a non-binary gender option or remove gender options

### ISSUE THREAD

**Issue by DexterirtyAmbush** [Regalis11/Barotrauma#1184]

**Comment by rico6822** [comment]
Really?

**Comment by rico6822** [comment]
*casually hides in the comment section*

**Comment by rico6822** [comment]
What am I supposed to think about it?

**Comment by rico6822** [comment]
What am I supposed to think about it? Is this comment really a joke?

From what I see on your profile you only made 2 contributions in your entire github history just today, so I suppose you are not here to help us since you may be just a troll who made a quick account to have some fun. The owner of this repository doesn't consider issue tracker a good place for memes.

**Comment by rico6822** [comment]
What am I supposed to think about it? Is this comment really a joke? Yes, it is a joke!

From what I see on your profile you only made 2 contributions in your entire github history just today, so I suppose you are not here to help us since you may be just a troll who made a quick account to have some fun. The owner of this repository doesn't consider issue tracker a good place for memes.

**Comment by Regalis11** [comment]
@rico6822 I think that's a bit derogatory. It could be a joke, or it could be a serious request: I'm sure there are a lot of non-binary people who prefer to play as non-binary characters.

That being said, I'm not sure if we should have a non-binary option in Barotrauma. I know it isn't evident in the game yet, but the idea is that the Coalition is an oppressive, totalitarian regime. In a game that takes place in an extremely harsh environment in which people struggle for survival (not just on an individual level, but as a species), and where a totalitarian military state is pulling the ropes, I wouldn't be surprised if non-binary and LGBT+ people were discriminated or downright persecuted. Europa is not a pleasant or tolerant place to live in, and personally I would find it a bit odd if it had a non-negligible non-binary population.

**Comment by rico6822** [comment]
> @rico6822 I think that's a bit derogatory. It could be a joke, or it could be a serious request: I'm sure there are a lot of non-binary people who prefer to play as non-binary characters.
> 
> That being said, I'm not sure if we should have a non-binary option in Barotrauma. I know it isn't evident in the game yet, but the idea is that the Coalition is an oppressive, totalitarian regime. In a game that takes place in an extremely harsh environment in which people struggle for survival (not just on an individual level, but as a species), and where a totalitarian military state is pulling the ropes, I wouldn't be surprised if non-binary and LGBT+ people were discriminated or downright persecuted. Europa is not a pleasant or tolerant place to live in, and personally I would find it a bit odd if it had a non-negligible non-binary population.

If players don't like their real life genders they can simply play as opposite.

**Comment by Regalis11** [comment]
@rico6822 That's not what non-binary means. The point was that some people may want to choose something else than "male" or "female".

**Comment by rico6822** [comment]
> @rico6822 That's not what non-binary means. The point was that some people may want to choose something else than "male" or "female".

If they are going to be persecuted due to in-game regime will they have worse roles just because of it?

**Comment by rico6822** [comment]
> @rico6822 That's not what non-binary means. The point was that some people may want to choose to play as something else than "male" or "female".

Ultimately I choose to stay neutral. LGBT and non-binary stuff in my country are being officially seen by most people as simply disgusting because most Poles doesn't consider it a natural thing for people to love someone of the same gender or even change personal gender, exceptionally because in Poland changing gender does not always go as planned. Unfortunate surgeries may result in having the voice being unchanged or female's beard being manly.

The only reason I consider this thread as a joke is that it's author requested to alternatively remove completely gender options if non-binary variant cannot be applied which is radical for real.

Do not consider me sexist for I am not one I have only described how most Poles see stuff like it. My personal opinion is being limited to sentencing that completely removing gender options as an alternate solution would go too far.
