### ISSUE TITLE
Welding Tool issues and optimization

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11884]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The welding tool is pretty old and has some strange quirks

~~1. Redundant StatusEffect?
I'm not sure why there's -3 and +3 condition over 2 statuseffects, I've tried deleting it and it didnt change anything, whether it's cutting ice spires, thalamus, guardian pods or other items taking damage by welding tool.~~

2. Oxygenite condition after exploding isnt 0
Since oxygenite health has been increased, the SE only removes -100 condition instead of setting it to 0. It does "explode" but without entirely exploding. Use `Condition="0" setvalue="true"`?
![image](https://user-images.githubusercontent.com/73229309/233684977-58f268d1-cdb6-4782-8fe0-6aa94719942f.png)

3. Using different statuseffects for Incendium / condition not updated
Oxygenite and other items were updated to have more condition than their basic counterpart, which avoids using multiple statuseffects for each type of fuel used #10000 . This change will also affect other items that use incendium: Flamer, Steamer, Cutter (see 2.) and maybe diving suits 
![image](https://user-images.githubusercontent.com/73229309/233687871-d8ed7d97-24f1-4fb0-aaa3-1d992db7c370.png)

4. Welding speed barely affected by skill
Welding a door with 0 skill took 40 seconds, 20 seconds with 1000 skill (capped at 100?). 
This is pretty slow and doesnt get much faster

5. Welding doesn't increase door health

6. "Fleshsmoke" particle barely visible
The welding tool is particle-heavy and Fleshsmoke (when hitting characters) particle is almost entirely covered by other particles due to its angle. `anglemin="265" anglemax="275"` makes the smoke perpendicular to the beam and more noticeable

6. Ancient `Upgrade` dating back to the stone age of barotrauma

### Version

v1.0.9.0

**Comment by Regalis11** [comment]
Thank you for the report!

As far as I can see, some of these don't need to be changed though:
>1. Redundant StatusEffect?

The effect isn't redundant; the 1st one welds door shut, and the 2nd one damages items that can be damaged by welding tools.

>4. Welding speed barely affected by skill

In my opinion say doubling the welding speed is a significant enough difference. I also think 20-40 seconds to weld a door shut is a reasonable amount of time, it certainly shouldn't be faster than that.

>5. Welding doesn't increase door health

It shouldn't; doors a repaired with wrenches.

>7. Ancient Upgrade dating back to the stone age of barotrauma

I don't see any reason to remove these, since they don't do anything in up-to-date saves.

**Comment by ubertpendragon** [comment]
> 
> > 1. Redundant StatusEffect?
> 
> The effect isn't redundant; the 1st one welds door shut, and the 2nd one damages items that can be damaged by welding tools.
 
As said above I thought long and hard and tested items that are damaged by welding tools; didn't notice a difference after removing the -condition, it still damaged them all the same 🤔 


> > 4. Welding speed barely affected by skill
> 
> In my opinion say doubling the welding speed is a significant enough difference. I also think 20-40 seconds to weld a door shut is a reasonable amount of time, it certainly shouldn't be faster than that.
> 
> > 5. Welding doesn't increase door health
> 
> It shouldn't; doors a repaired with wrenches.

I meant increasing the health of a welded door vs unwelded, so you could weld a door to make it sturdier (airlock, docking hatch...). Faster welding could also be used in combat if Mudraptors invade your sub, at 20/40 seconds it's a really long time for any practical use (even on traitor servers where welding could be a strategy)

**Comment by Regalis11** [comment]
Addressed 2. and 6. in https://github.com/Regalis11/Barotrauma-development/commit/b44ac82518c13acd24b87a1cfc500eee07167eb7. The rest aren't bugs.

**Comment by itchyOwl** [comment]
> I meant increasing the health of a welded door vs unwelded, so you could weld a door to make it sturdier (airlock, docking hatch...).

This is addressed in a separate branch, Barotrauma-development#4204, which makes the welded doors have "extra health" that needs to be undone before the door can be broken.

I don't think it ever has worked like that, but back in "the stone age" when the doors were repairable with welding tools, it worked in practice a bit like that. Not quite though, because welded doors would still take normal damage from the other sources of damage, which in practice was monsters (and submarine weaponry). Now that also explosions, small arms, and any tools can be used to damage the doors, the issue was more prominent.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
