### ISSUE TITLE
Husks made from players always attack each other

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#119]
Sure, it's pretty creepy when they keep chomping each other up, but as creatures this doesn't make sense. Why would they attack their own kind if all that results in is constant health-stealing?

**Comment by NilanthAnimosus** [comment]
This actually nets them a higher net-return usually than they lose in previous version - though I don't think Player husks attack AI Husks anymore - but this issue is really at fault to the way fish vs fish is handled in the AI. it doesn't matter to their type or a team but this can equally be resolved by giving husks the same combat strength (At least for now unless a better system is implemented) in the XMLs as I understand it.
