### ISSUE TITLE
Add to Server's Host Panel Option to Change "Braindead" Timer- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1191]
What I'm talking about is that by default it takes 30 second before player's in-game character dies in multiplayer due to disconnection. I believe hosts should have a option to change it for a maximum amount of infinite. If it had to be set to infinite it would be slightly harder for players to suicide in order to respawn in a shuttle or to instantly turn self into fully active husk after being huskified. Somebody AFK for short time after disconnecting may still play as his own character if he gets lucky.

Most importantly detaining hostile players makes sense since they won't respawn anymore.

I know it can already be edited in server's settings file by notepad++ but not every host knows it.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
