### ISSUE TITLE
StatusEffect in Afflictions don't apply properly in MP

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [Regalis11/Barotrauma#11982]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm working on a pass out affliction for Hungry Europans, which is applied by a stun affliction override.
Basically if the player is stunned, but is not at least 99% paralized, apply the passout affliction over time. Once 100% pass out is reached, the screen is black to prevent players from seeing what's happening. Once the stun gets below 0.5% the pass out affliction uses a status effect configured in it to reduce its own strength to remove the black overlay. 

All of this works perfectly fine in sub-editor and singleplayer campaigns, but in multiplayer the pass out affliction is not properly reduced and the screen starts to flicker as it is trying to remove the affliction, but isn't actually removing it. You can test that by setting the he-passout affliction to different strengths to see it'll always flicker with the corresponding intensity of your value. Basically "giveaffliction he-passout 50" will result in a flicker of your screen turning 50% darker in a specific pattern. The pattern speeds up depending on other mods loaded so you might see a different/slower flickering pattern when testing yourself.
Here's a video of the affliction working fine in SP while bugging out in MP:
https://youtu.be/zSu5d9m3SGE

And here's a mod folder prepared for you to drop into LocalMods and test it yourself:
[Affliction StatusEffect Issue.zip](https://github.com/Regalis11/Barotrauma/files/11445623/Affliction.StatusEffect.Issue.zip)

### Reproduction steps

1. Create an affliction with an effect that sets strenghtchange="0" and with a StatusEffect included that will reduce the strength of the affliction with multiple conditionals configured.
2. Give the affliction an overlay and make it apply linear.
3. Test in both SP and MP. MP will most likely flicker your affliction overlay until you reload the save file while it works fine in SP.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.1

### Which operating system did you encounter this bug on?

Windows

**Comment by giists** [comment]
Repro steps confirmed.

**Comment by Regalis11** [comment]
Sorry for taking so long to look into this!

It seems the issue here is the `<Conditional IsLocalPlayer="true" />` check. The affliction is only removed if the character is a local player, which it isn't in multiplayer (where the server has authority on the players' afflictions). So I would say this is working correctly.

I'm not entirely sure what the purpose of that check is, but could the property IsPlayer be used instead?

**Comment by UnhappyWithMyUsername** [comment]
Oh interesting. I'll mess around with that and see if it works. I wasn't aware of IsPlayer being a thing. I used IsLocalPlayer to force effects to only display or be audible for the person affected by the affliction as I previously had trouble with my cannibalism affliction in Hungry Europans broadcasting the heart beat sound effects to everyone near the afflicted person if I didn't put the IsLocalPlayer as a condition, when it was supposed to only be audible for the cannibal as audio feedback for getting a craving.

**Comment by Regalis11** [comment]
> I used IsLocalPlayer to force effects to only display or be audible for the person affected by the affliction

For these kinds of effects that others don't need to see, IsLocalPlayer is the way to go. But in cases where the effect needs to behave the same for all clients, it shouldn't be used: and I think this is one of those cases, every client should remove the passout affliction when it elapses. To me it doesn't seem necessary to have that check anyway, because the effect has no sounds or other effects that the other clients shouldn't be able to hear/see.

**Comment by UnhappyWithMyUsername** [comment]
Fair point. Thank you very much!
