### ISSUE TITLE
Incorrect reactor output at any turbine setting

### ISSUE THREAD

**Issue by FunAndEngaging** [Regalis11/Barotrauma#12000]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since the update, the output of all nuclear reactors is too low at any turbine setting. The difference is 1% of the maximum output.
This only seems to affect manually controlled reactors or reactors controlled by external wires.
The bug has a detrimental effect on certain reactor controllers, as real and expected output will never match.

Expected: A stock Barsuk with sufficient temperature produces 4200kW at 100% turbine setting and 420kW at 10% turbine setting
Observed: A stock produces 4157kW and 378kW on these settings
![output](https://github.com/Regalis11/Barotrauma/assets/77514133/a98af6c3-e2ea-4cd2-b91a-4a1db49ca27e)

### Reproduction steps

1. Open any submarine in the editor
2. disconnect all wires from the reactor
3. Insert sufficient fuel rods to achieve maximum reactor output (2x uranium) and deactivate automatic control
4. Manually set the turbine output to 100% and the fission rate to a level that maintains sufficient temperature
5. Observe the output not matching the configured maximum output of 4200kW

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! It seems this is how the reactors have worked since the power rework in v0.19.7.0. Seems to be a side-effect of the "load balancing" logic that tries to make different power sources connected to the same grid share the load between each other in a sensible way. Considering the 1% difference doesn't really make much difference in practice, and how complex the balancing logic is, I don't think we will be addressing this.
