### ISSUE TITLE
Allow modders to modify gender

### ISSUE THREAD

**Issue by LavCorps** [Regalis11/Barotrauma#1201]
This is my own personal response re: #1184 but I figured it might be better to make a separate issue for this request

I want to open this up by saying that I respect the lore choices for Barotrauma, but I'd like to see the option for modders to modify gender, maybe as something related to parameters in the creature editor, giving freedom of choice to both the base game and mods.

**Comment by Regalis11** [comment]
We currently don't have plans to expand the gender options in the base game (not just for the lore reasons I mentioned in that other issue, but also due to the fact that it'd be quite a large art task to make the sprites for the additional genders, which I don't think is worth the effort at this point when there's a ton of more critical tasks to get out of the way first). Adding code support for it would be pretty easy though, and would allow modders to add their own genders, so I think I can take a look at this after we've got some of the more high-priority issues out of the way!

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
