### ISSUE TITLE
"unlimited power" not giving battery and capacitor capacity. 

### ISSUE THREAD

**Issue by G-M-twostay** [Regalis11/Barotrauma#12056]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The engineer's talent unlimited power should give batteries and super capacitors 10% bonus capacity, but this didn't happen in game.

### Reproduction steps

1. Start a single player game.
2. Play the engineer and enable cheats.
3. use the giveexpereince command to give the engineer lots of experience.
4. choose the unlimited power talent.
5. check the batteries and supercapactiors for their capacity.
6. select a mission and leave.
7. check again for the capacity.

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

It seems the issue here was the buff was applied to batteries and supercapacitors in the sub/outpost the player is inside. It got reapplied every 60 seconds though, so once you started the round and waited, it should've gotten applied eventually.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a0291c1f24fb8477796a8ec86919886b7e5d0bf (commit in our private repo)

**Comment by Jasontti** [comment]
Tested, works in single- and multiplayer.
Closing ticket.
