### ISSUE TITLE
Can not select some of hairs when there are more than 40 kinds of hair style

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12067]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While developing new content for [EA-HI]Animated Barotrauma, I noticed that when there are more than 40 kinds of hair style, I can not select some of them by dragging the hair selection scroll. It's like some of the hair style are skipped.

### Reproduction steps

1. create a mod that adds more than 40 kinds of hair style
2. go to character customization menu of singleplayer campaign
3. try selecting hair no.41

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
There are 41 kinds of hair in total when using the mod. I can not select hair no.38 and no.41. When I move the slider a bit, the hair changes from no.37 to no.39. And when selecting the last 2 hair options, they all show hair no.40.

**Comment by BiffW** [comment]
The hair styles are successfully added to the game. NPCs can spawn with them randomly. The issue only affacts player selection. Ideally, is it possible to allow players to choose hairstyle like choosing head type?

**Comment by Regalis11** [comment]
Thank you, got it to happen now! It seems that this happened due to a rounding error: the scroll bar value (a float) was cast to an int, and if there was a specific number of hairs, some scroll bar values could end up being something like 40.9999, which would get cast to 40 instead of properly rounding it to 41. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4c1e3647b9076c83a44a869733cd0766ee58417

**Comment by DrinkFromTheCup** [comment]
> It seems that this happened due to a rounding error:

@Regalis11 , sorry for direct mentioning, but one quick clarification might save us all quite a time.

Do, by any chance, the fix fixes other sliders too?
For some reason I can't set VOIP volume to exactly 100% - it's either 99 or 101. SOME other sliders are affected too.

**Comment by Regalis11** [comment]
@DrinkFromTheCup it doesn't affect any other sliders. What kind of resolution are you playing on? I tried changing the VOIP volume and was able to set it to 100%, but I suspect it could behave differently on different resolutions.

**Comment by DrinkFromTheCup** [comment]
@Regalis11 , 1920*1080, borderless fullscreen. Ubuntu 23.04, if it's important.
Quick-checked audio settings sliders.
Voice Chat Volume is either 99% or 101% for me.
Other sliders are OK since these either use increments of 5-10-20-whatever - or, with mouse sensivity low enough, allow selecting exact values. Notably, was unable to set global sound volume to 53% until lowered mouse sensivity to minimal (+ moved the mouse diagonally).
Probably not much of a trouble on its own.
