### ISSUE TITLE
Visibility On Waypoints Are Still Visible After Being Disabled Sub Editor

### ISSUE THREAD

**Issue by brand175** [Regalis11/Barotrauma#12088]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

AI waypoints still show after being regenerated when the waypoint box is unchecked

### Reproduction steps

1. Make a ship in the sub editor
2. Generate AI waypoints (Visibility enabled)
3. Disable waypoint visibility and regenerate the AI waypoints
4. Ship will now show waypoints even when the box shows it's unchecked

![Screenshot 2023-05-27 125742](https://github.com/Regalis11/Barotrauma/assets/20964160/b3c4ced2-73fa-44ce-84b7-c1bcee8592fc)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Regenerating waypoints toggles waypoint visibility on (same with all other types of entities, e.g. if you place a hull, hulls become visible), but the problem was the checkbox stayed disabled. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/74f733ff0b8aa06b9a2d4272cf5786977e938b30

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
