### ISSUE TITLE
Creatures spawn within player's sight in a destroyed wreck

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12144]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I tried to destroy every destructible structure of a wreck with nuclear shells and thought it could be safer for later exploration. However, creatures sometimes spawn within my sight in wrecks like they came out of nowhere.

### Reproduction steps

1. Destroy every destructible structure of a wreck from a distance using nuclear shells
2. Dive and explore the wreck

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thanks for the report. It's an oversight: It's intentional that the monsters sometimes spawn when they are fairly close by, because those spawn events are designed to be encounters. And if the monsters spawn too early, it's impossible for the player to see the combat between the creatures. But I haven't taken into account that you might destroy the walls before triggering the events. Need to figure out something to prevent that from happening.

**Comment by giists** [comment]
Sometimes if your line of sight is blocked into an area that you know is empty (like going around a small piece of wall) enemies spawn into that area. It can be pretty jarring sometimes. There should probably be some kind of distance check so that the enemies don't spawn right next to around a wall.

**Comment by giists** [comment]
No issues, closing.
