### ISSUE TITLE
[PR/FEATURE REQUEST] Grenades Tweaks

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12154]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

First and foremost, I wanted to do it as PR similliar to [Jade's Changes](https://github.com/Regalis11/Barotrauma/pull/10288) but I had skill issue on doing it, so instead I will post it here.

Anyways, here's what changes include:
- new sounds
- new pin pulling mechanic (press E) and cooking of grenades
- new effects on for EMP and STUN grenades
- tweaked damage values
![Grenade Tweaks](https://github.com/Regalis11/Barotrauma/assets/42521948/4675044e-cafa-487e-8fca-362767f56eba)

XML file fully documented by original author (M12) with all changes highlighted
scuffed video demo:
https://youtu.be/4Uk3-7W8lIM

### Reproduction steps

1. download [Better_Grenades.zip](https://github.com/Regalis11/Barotrauma/files/11739412/Better_Grenades.zip)
2. put it in your local mods
3. activate it like any other mod
4. load on any submarine/level of choice
5. spawn grenades of choice
6. pick em in your hands and press E
7. throw

Once again sorry for posting it here!

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report, but I'm afraid we cannot integrate something you've submitted in behalf of someone else into the game, since we don't know whether the author approves of them being added. We also don't know where these sound files are from or whether we have the rights to use them (assuming they weren't made by you or M12).

If you want your changes to be included, please submit a pull request, which as stated in the EULA serves as a sort of statement you've made the changes yourself and/or have rights to use everything in the PR, and are giving us the rights to use them.

**Comment by PanmanS** [comment]
Dont worry M12 approves me uploading since he himself doesnt know nor have github account and that's why he asked me to do PR myself 

grenade sounds mixed from stalker anomaly mod that uses royalty free sound library (which i can provide you if needed)

**Comment by Regalis11** [comment]
Regardless, we need this to be submitted as a PR instead of a bug report to adhere with the EULA. We also need to know exactly where the sounds are from and what kind of license they are under (royalty free doesn't always mean they're free to use "no strings attached" - we might need to for example give credit to the creators of the sounds, or make a note about what kind of license they're under in the game's credits). Please provide this information in the PR if possible, because it's better to have that information publicly visible there instead of a private Discord conversation on the off chance we run into some kind of legal/licensing issues.

**Comment by PanmanS** [comment]
we took sounds from anomaly mod from stalker and remixed em cause they were perfect match...

Anyways, maybe there are any "ping-ish" sounds in barotrauma itself? (like grenade pin ping)
