### ISSUE TITLE
NPCs cannot be killed when Killable Outpost NPCs is disabled

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12156]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Disabling Killable Outpost NPCs in the multiplayer anti-griefing menu leads to the predicted behaviour of npcs being unkillable. This is a problem, however, in events where npcs must be killed to progress. A notable example is during the Tormsdale report mission, where the station manager needs to be killed or incapacitated to access his safe. This is completely impossible if the setting is on, since he cannot be knocked down for long enough to grab his card.

NPCs whose death are important for events should be exempt from this server setting. I don't know how many events it does affect, but Tormsdale Report was the one that brought it to my attention.

### Reproduction steps

1. start a multiplayer lobby with the Killable Outpost NPCs setting disabled
2. get the Tormsdale Report mission and head up to the outpost manager
3. find that you cannot kill or incapacitate him, and so the mission is impossible to complete

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/65904f188e7df70ec8eb3a7e38daadbfebed1bcf. I couldn't think any other missions affected by this aside from the Tormsdale Report one. The assassination missions (assassinating the Coalition spy for the husk cult, assassinating Subra) came to mind at first, but they don't seem to be affected, because the NPCs are spawned by the mission itself, and aren't "normal" outpost NPCs affected by the setting.

**Comment by Jasontti** [comment]
Tested.
Could not kill Tomsdale report station manager, they had same super healing properties as other NPCs.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/56e1daccdf93a1042bfc1a2ca054c7947dd436f3

**Comment by Jasontti** [comment]
Tested.
No further issues found.
Closing ticket.
