### ISSUE TITLE
Allow other clients to see via icons if a player is spectating and their top job preferences/current job

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1220]
**Description**
The idea is simple, Add job specific icons and syncing for the top player preferences to other clients as part of the lobby GUI, along with replacing them with an icon for spectating instead of the preferences.

A place holder could be used just reusing some of the order images, such as the steering command for captain 

The space available on the lobby screen's clients list is quite limited, but having detail added to it would be beneficial to things like multiplayer campaign or general rounds while indicating what their current job (If in game and have spawned) or top job preferences / spectating status is if they have not yet spawned / won't spawn.

I feel such information may allow players to better plan what roles they would prefer to take in a given match at a glance, instead of 5 engineers and 1 mechanic, a player seeing this may switch over for a second mechanic, or pick a medical/security role instead.

**Comment by NilanthAnimosus** [comment]
I tried to implement some code in the meantime to allow players during campaigns / regular play to be individually told (and updated) on a cooldown timer and if the top preference changed - what the top preference was of their crew (Including already taken jobs and campaign character data that is in use by a client).

I found it didn't work as I intended it to - then additionally found clients only appear to send updates in client packet "RESPONSE_STARTGAME". this is only sent when the client receives QUERY_STARTGAME from the server or clicks spectate and not as they change anything periodically.

So effectively, I found it was actually impossible (as of currently) to update players on the job selections of other players! I know it would be silly to send multiple character updates everytime someone just changes a head - but it would be nice if they synced their latest state periodically and is sort of required for the above feature request to visibly work otherwise it will always show an incorrect job if you did retrieve that data from the server.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
