### ISSUE TITLE
Bots might drown in ballast, if they don't wear any diving gear

### ISSUE THREAD

**Issue by DrParanoik** [Regalis11/Barotrauma#12220]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since last patch I noticed as bot suffocate in ballast. After few experiments in editor I conclude next: bots take masks only when water level greater than 60%. This is really bad situation, because bots have big chances just to die in ballast even in vanilla subs (Remora and Camel for example).
I don't saw this situation before last patch.

### Reproduction steps

1. Start round (better to use editor to damage pumps).
2. Look as bots try to suffocate in ballasts when water level lower than 61% (if they failed and stunned while repair a pump, they easily can dying there)
P.S. As a solution, I ask that the bots wear a mask in case of any work in the wet room.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Seems to be an oversight: the bots should indeed be equipped with a mask when doing repairs in the for the pump in the ballast, because it's likely that they will need it. However, this is not something that has changed recently.

**Comment by itchyOwl** [comment]
Here's the case ![image](https://github.com/Regalis11/Barotrauma/assets/5370738/2b0df7f9-d82f-4cd7-bc39-7307fdd06ad6). Seems to be a bit bugged too.

**Comment by itchyOwl** [comment]
Steps to repro:
1. Open Camel in the subeditor
2. Edit the pump on the right to have 0 condition
3. Go in the test mode
4. Order a bot to repair the pump
5. Observe the bot suffering from oxygen loss and requesting medical aid (though not dying, unless stunned by a failed repair attempt).
6. Regalis11/Barotrauma-development@cb4447d fixes the issue so that the bot will escape before suffocating, but won't be able to complete the task.
7. Regalis11/Barortrauma-development@269d339 should fix the issue by making the bot to equip a mask before trying to repair the pump.

Note that these changes may have wider implications and should be thorougly tested for any unintentional side effects: test that bots can still operate normally in flooded or partially flooded hulls. And please report if the behavior has changed (apart from what's described above).

**Comment by itchyOwl** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4326.

**Comment by Jasontti** [comment]
Tested.
Bots correctly put on mask or suit when working in flooded areas.
Closing ticket.
