### ISSUE TITLE
Allow Players to Download Any Server's Host Submarine They Want- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1229]
If players would have the ability to do so and sharing submarine folders on the server would be enabled players would be able to download any submarine they want from server's host without having to wait for the round featuring them.

**Comment by BlueTheKing** [comment]
Since it's downloading it directly from the server it could slow it down, and either way if they want a sub soon enough they will be able to just go on the workshop and download it.

But it could still can be an optional thing for the server host to pick.

**Comment by rico6822** [comment]
> Since it's downloading it directly from the server it could slow it down, and either way if they want a sub soon enough they will be able to just go on the workshop and download it.
> 
> But it could still can be an optional thing for the server host to pick.

Yes, you are right.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
