### ISSUE TITLE
Hulls water volume glitches up and down

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12335]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Observing weird behavior with water in hulls:
Water compresses 5.000% (water volume 139776/133120)
![image](https://github.com/Regalis11/Barotrauma/assets/68995233/14a15cb2-133b-4604-8c0a-5f50fc84da75)

Oscillations occur when above hull is near empty but not quite.

https://github.com/Regalis11/Barotrauma/assets/68995233/8e21c285-2a88-4c1a-b916-71e7530fe8b5

### Reproduction steps

Observe water as it moves between hulls.
Something is not quite right but I can't put my finger on it!

### Bug prevalence

Just once

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
This is a side effect of how the water propagation logic works. Water in the game is slightly compressible: water basically pushes "too much" water into the hull below, and that extra water tries to find a way to get out, making it possible for it to flow e.g. from one side of a U-shaped hull configuration to the other side and for the water level to equalize.

There is some oscillation involved, but it's generally not noticeable unless you use debugdraw (because the rendered water surface is "smoothed" to hide the oscillations).
