### ISSUE TITLE
Expand Editing Options of Description Boxes- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1235]
I think descriptions of servers can be expanded further by adding following features to them which would potentially make some server hosts not having a need to give links to discord chats for server guides:

- [ ] Pressing description box results in a larger box popping-out for editing. By default only server's host can edit it. Others can only enlarge it to see it more clearly.

- [ ] Text editing based on steam's url code.

- [ ] Pressing enter starts writing text from the new line.

- [x] Marking text by holding mouse, dragging and releasing trigger.

- [x] Marked text can be copied by holding "CTRL" and "C" key at once.

- [x] Text pasting feature. Keys "CTRL" and "V" need to be pressed at the same time to paste a text at selected spot.

- [x] No need to backspace to return to a specific place in the text.

- [ ] Players don't see how text constantly changes on their eyes and "Save Changes" must be pressed if they have to finally see it.

I was wandering if the same thing could be done in submarine editor for editing descriptions of submarines.

If you decide to implement active links feature to exterior websites it would be safer if the player was asked by the game if he wants to do this.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
