### ISSUE TITLE
Some explosives are ultra stable, others are not

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12354]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Fire causes IC-4, (volatile) Compound N, nitroglycerin to detonate. Fuel tanks and O2 tanks explode as well.
It is particularly interesting how C-4 and UEX appear to be invulnerable to any type of damage.

_Is this expected?_

### Reproduction steps

Spawn explosives:
UEX, C4, IC-4, Compound N, Volatile compound N, nitroglycerin.

Hand grenades:
Fragmentation, stun, EMP, Incendium, Oxygenite shard.

Observe their reaction to fire, and damage from other explosives.

### Version

Unstable (v1.1.3.0)

### -

ps: let me know if this is not the right place to ask _is this intended_ type of questions!

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
_Incendium shard_ sounds like it should somehow start fires.

**Comment by Regalis11** [comment]
This is intentional: C-4 is very stable in real life too, and doesn't explode even if set on fire. UEX is intended to be some kind of a "simpler form" of C-4 (since it's used as a recipe in C-4), so it's intentionally very stable as well.

> ps: let me know if this is not the right place to ask is this intended type of questions!

It's fine to ask, if it is unintentional or a bug we can then easily pick the ticket up without having to create one. :)
