### ISSUE TITLE
Cursor flickering when aiming

### ISSUE THREAD

**Issue by takinxane** [Regalis11/Barotrauma#12370]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I've downloaded a few mods, and there's only one that changes how something works (neurotruama), I noticed that sometimes my mouse flickers when aiming a gun.

### Reproduction steps

[bug.zip](https://github.com/Regalis11/Barotrauma/files/12073993/bug.zip)
here's the modlist i'm using, you should be able to see it when hosting with server side lua

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by CodeLamp168** [comment]
Does this affect turrets as well?
 I do remember having issues with **"Brighter Lights"** once before when using turrets. 
 Try removing that and test it again.
 
Also it might be irrelevant but the Hydroponics Patch Mod you have requires another mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=2137671136

**Comment by takinxane** [comment]
Hello, i've just checked and it does affect the turrets, also i turned off the "Brighter lights" and added the required mod for hydroponics patch, and it's still flickering.

https://github.com/Regalis11/Barotrauma/assets/139818057/8f827186-b0af-4217-b8a6-0572ccfe1f0a

**Comment by CodeLamp168** [comment]
> Hello, i've just checked and it does affect the turrets, also i turned off the "Brighter lights" and added the required mod for hydroponics patch, and it's still flickering.
> flickering.mp4

Just to make sure. That echo effect from the mp4 is caused by the video program you used or is the game making that sound?

**Possible Solution**
Try the Performance Fix Mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=2701251094&searchtext=Performance
I personally don't know my way around configuring it, but it has helped in removing some issues similar to yours.

It could also be the LUA (with xpath patch), try using the original one and testing it out to see.
If the error still persists, I'd recommend a clean reinstall of your mods.

**Comment by takinxane** [comment]
The effect is from my microphone recording software, it started echoing every sound on my system, trying to fix it now

**Comment by Regalis11** [comment]
Thank you for the report!

Since this doesn't seem to happen in the vanilla game, you might want to get in touch with the creators of the mod(s) that are causing this instead.
