### ISSUE TITLE
Sometimes, permanent leak can remain after full repairing the Reactor room in BeaconStation1

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12381]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During natural playthroughs, the Reactor room in BeaconStation1 can sometimes have a permanent leak in the top right of the room that no amount of repairing can fix. Closing the Reactor room door will cause it to flood again, and it generally causes the beacon to take far, far longer to drain. 

Opening the map in the sub editor doesn't give clear indication on why this occurs, but a picture has been added.

**Notes:**
- Issue cannot be reproduced in the submarine editor, even by destroying all the walls.
- The crew quarters has indestructible walls. While they do appear to be fully repaired, it is unclear if they are still secretly damaged and causing a leak.
- Attempting to repair all the walls in this spot from the outside will not resolve the issue.

https://github.com/Regalis11/Barotrauma/assets/5988156/574c99fa-5448-4334-b170-bc97dc654dd5

![spot](https://github.com/Regalis11/Barotrauma/assets/5988156/bd170bf2-7d97-45a1-8824-d69b6f0f00f2)

### Reproduction steps

1. Start a new campaign
2. Progress naturally until reaching a Beacon Station side mission with BeaconStation1 as the Beacon
3. Repair all the walls
4. Drain the water with the pumps
5. Observe for any lingering leak above the Reactor

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### -

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. I suspect this requires that some specific part of the wall is leaking initially in the beacon station. A save file where this occurs consistently, or even a screenshot with debugdraw enabled that shows where exactly the leak is might help us diagnose this.

https://github.com/Regalis11/Barotrauma/assets/14351070/db1dc71d-4b50-4987-8436-fe630896468b

**Comment by WJohn** [comment]
I have found the same damaged wall piece and noticed something: The wall does not actually look damaged, despite being about 95% destroyed. Repairing shows a full health bar to players, but the Damage number goes down invisibly to them.

https://github.com/Regalis11/Barotrauma/assets/5988156/bccc1f48-5d82-4de0-8f2a-2b97fdc584c2

A save has been attached as well, but damage on beacon stations is randomized, so it is only useful as a relatively quick natural playthrough savefile to repeatedly try it out on.

[BeaconStation1_Save.zip](https://github.com/Regalis11/Barotrauma/files/12114701/BeaconStation1_Save.zip)

**Comment by AdamH-Daedalic** [comment]
v1.0.21.0

Tried this on multiple attempts, both natural and also with the provided save data and I did not encounter any unexpected leaky wall segments. Each instance of BeaconStation1 did not have any unexpected leaks or walls that appeared fine but were damaged, resulting in normal, expected behaviour when water was pumped out.

**Comment by NilanthAnimosus** [comment]
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/cd25531824ed25a6c9c237ce3357e07a2cb41542

Successfully reproduced on a server in mission mode using barsuk with the seed o7syhTog

Modified the code to essentially damage all walls instead of a few random wall segments in Level.cs (Line 4354 onwards):

```
//poke holes in the walls
foreach (Structure structure in Structure.WallList.Where(s => s.Submarine == BeaconStation))
    {
        //int sectionIndex = Rand.Range(0, structure.SectionCount - 1, Rand.RandSync.Unsynced);
        //structure.AddDamage(sectionIndex, Rand.Range(structure.MaxHealth * 0.2f, structure.MaxHealth, Rand.RandSync.Unsynced));

        for (int i = 0; i < structure.SectionCount - 1; i++)
        {
            structure.AddDamage(i, Rand.Range(structure.MaxHealth * 0.4f, structure.MaxHealth, Rand.RandSync.Unsynced));
        }
    }
```

its very difficult to weld, and shows no damaged health bars even if you hit it - but does eventually fix with enough effort. Not too sure why its very difficult to weld this point however. May be easier if the damage is set to just always be full though. Also curious why explosions in submarine editor don't seem to have the same effect as the code causes in a mission on multiplayer?

![image](https://github.com/Regalis11/Barotrauma/assets/29177976/64a266ec-af7a-422b-9e57-e3ac93f9c4ba)

**Comment by Regalis11** [comment]
I'm afraid I still couldn't repro this. :/ Tested with the same code modifications, and I had no problems repairing the leak:

https://github.com/Regalis11/Barotrauma/assets/14351070/6ecc95b1-a526-42d0-bc2c-2ab311b0ce01

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4514/commits/2a8d56365a30146f9bfe7e8a141b7bfd501a8c57

Tried in sub editor and naturally in campaign
Destroyed it completely and fixed

No issues found
Closing ticket
