### ISSUE TITLE
Implement Missing Controls Instructions Into "Readme" File- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1239]
This text file lacks "H" key responsible for healing HUD as well as "R" key responsible for attacking with husk's parasite.

I think this file is also missing other important information like ChikoEduardo being one of the programmers for the game and FakeFish being a cooperating game development studio.

**Comment by Regalis11** [comment]
Thanks for the reminder, the readme file needs quite a lot of updating (not just the controls, but the credits, copyright notices, etc). 

>ChikoEduardo being one of the programmers for the game
What do you mean by this though? I know he's done amazing work on his own mod, but I don't think he's contributed any code to the main game (and as far as I know, Barotrauma Extended doesn't include any source code changes either).

**Comment by rico6822** [comment]
> What do you mean by this though? I know he's done amazing work on his own mod, but I don't think he's contributed any code to the main game (and as far as I know, Barotrauma Extended doesn't include any source code changes either).

I mean he created a motion detector which you pasted into the game.

**Comment by Regalis11** [comment]
Ah, you're right (although it was added by Crystalwarrior in a0d3131, not by me). Gotta add both of them to the credits. :+1:

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
