### ISSUE TITLE
AI can't repair hull in the two corners on Typhon 1

### ISSUE THREAD

**Issue by Venus-Flytrap** [Regalis11/Barotrauma#12417]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

AI can't repair hull in the two corners on Typhon 1

### Reproduction steps

damage hull in marked places on screenshoot 
![typhon](https://github.com/Regalis11/Barotrauma/assets/140067399/22103e9d-5d7c-4238-ac0c-758e8abd3a89)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@1f52da0.

Steps to repro: Cut a leaking hole right next to a door/hatch. Not specific to Typhon, though didn't test on the other subs.

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/c47764b4-e113-43c3-a719-1060d315fbc3)

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/e4689132-8f92-491f-8d8f-6c2010afb389)

**Comment by Jasontti** [comment]
Tested.
Destroyed couple subs and bots fixed them up. No issues found.
Closing ticket.
