### ISSUE TITLE
Make opiate addiction more harmful

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1244]
So let's talk opiate addiction for a second here.'

So I ordered two crates full of cargo full of morphine to get the "getting clean" achievement (just to see how it is).

So I got myself addicted right, almost overdosed and died but I was thankfully saved by my decision to ingest only five instead of six, and that was that (on that topic I think the amount to get addicted should be three, there's only like two tablets of morphine on the ship anyways, what's up with that).

After that I got addicted and in addition the "opiate addiction" tab above my healthbar, right. So here I was, my screen a teeny bit wonky from ingesting too many opiates right. After about two minutes the wonky screen went away as well as my addiction. And in addition I got the achievement too which was what I wanted.

My problem is that the opiate addiction was not only underwhelming, but pretty unrealistic. I expected some more severe effects, something that would actually make me as a player scramble for more morphine, someone that would make me want to injest all of that addiction removing medicine in the world.

But nope, I just sat it off and that was that. 

I suggest you guys make the opiate addiction a lot more severe, as well as punishing addicts for not ingesting more opiates to satisfy themselves and rewarding them for scrambling for more opiates, just like in real life. This would make me happy.

Leave all responses and comments, as well as opinions in the comments below!

**Comment by Regalis11** [comment]
Opiate addiction by itself is not harmful, but it gives you a gradually worsening "opiate withdrawal" affliction that can be fatal. 5 shots of morphine only gives you a mild addiction that goes away by itself before causing any withdrawal symptoms.

I think we could maybe make the opiates cause addiction a little more easily, but we can't go too far with it. Treating an injured character often requires at least a couple of shots of morphine/fentanyl, and we don't want characters to become addicted every time they're treated with opiates, but only when you use them very frequently or in very high doses.

**Comment by AbominationBanisher** [comment]
But I have noticed one thing, on the "Orca" for example, I've found only two vials on morphine in the medical cabinet, making addiction hardly possible unless you order it in the masses in the campaign store, or spend all your time fabricating it. So I think another solution would be to add more morphine to the default subs, just some food for thought.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
