### ISSUE TITLE
Allow selecting the face attachments of a character

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1246]
![profile](https://user-images.githubusercontent.com/41457828/54066925-99afec80-4249-11e9-93aa-580d5788f677.PNG)

Do you see this beautiful character model made by the graphics designers? Do you see their good taste and plentiful art work? Yes it's great, marvel at it, right?

Sure, la de da, it is great and all. But I want to make a minor issue clear here. So as you developers know, each base character for each gender has variants. For instance, my favourite character as seen in the screenshot has a weird looking beard variant, a bald variant, goatee variant, a beautiful greatly designed scar variant, and the like. What I don't like is having to scroll for five minutes to get the exact variant I want, as each time I scroll through the base character models the character variant is assigned by random chance, meaning through the first scroll through he'll have a beard, second scroll through he'll be bald, this and that. This usually takes me five minutes to get pic related profile. I suggest on each base character, when you go on them, new arrows on top and below the profile will appear. These arrows you can scroll through to pick your favourite variant for that base character.

Pretty simple idea, would love to see it implemented.

**Comment by itchyOwl** [comment]
We've been discussing about it. It's certainly possible to do when the lobby view is redesigned and reimplemented.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
