### ISSUE TITLE
Harpoon guns (And other ranged weaponry) no longer log hits from players

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#125]
This is really easy to fix though I don't have a branch to make a pull request from on this right now (I'll set something up for submitting bug fixes at some point).

In Rangedweapon.cs's Use (Which fires the projectile) it calls the projectile's use function.
Before doing this it sets the User of the projectile however this should also be included in the Use send (as character will be equal to null, and then the user is set from character on use, setting the user to null)

Simple fix is in Barotrauma Shared -> Items -> Components -> Holdable -> RangedWeapon -> line 114
Projectile.Use(deltaTime); -> Projectile.Use(deltaTime, character);

**Comment by Regalis11** [comment]
Could not reproduce this, the hits seem to be logged the way they're supposed to because the user is set on line 115 right after calling the Use function. Projectile.Use(deltaTime, character) would prevent most projectiles from working at all, because their CharacterUsable property is false, meaning that they can only be used via another item, not directly by a character.

**Comment by NilanthAnimosus** [comment]
This was tested using 0.7.0.1 Code (Not the latest commit code).

Issue has been fixed in the commit "Added Karma, harming players reduces it" with the second user set although not specifically stated, I try to find issues that have been fixed but this commit seems to have slipped by me.

Closing the issue as its resolved (I'll try to include specific commit or version tags for future reports when I find any issues).
