### ISSUE TITLE
Allow Fractual Guardians To Deal Hull Damage- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1250]
Fractual guardian are already creatures with intellect limited to just blindly attack any human intruder inside ruins. It would be interesting if they were able to deal damage to their own hull of ruins in order to pierce walls and break doors in order to get to you.

Player would have limited amount of time to locate and complete a puzzle before fractual guardians locked inside their small cell would break the hatch and start an assault. Also they would deal hull damage to submarine if they had for some reason leave their territory.

About the puzzle stuff it takes extremely long for fractual guardians to break hatches and doors. They would try that if the player was still searching for puzzle. It also expands tactical options of the player to exploit ruins and makes fractual guardians more serious.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
