### ISSUE TITLE
Door condition goes up from 0 while being repaired, even when broken

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12513]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The purpose of the condition check is to track what is broken. If the condition goes up from 0 before the door is fixed sufficiently to operate as a door, then this signal will not serve its purpose.

### Reproduction steps

`quickstart humpback`
Wire the `condition_out` of the hatch next to gunnery to one of the text displays
Plasma cut the hatch
Repair it

Value should stay at 0 until there is actually a hatch (at 50)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
> Value should stay at 0 until there is actually a hatch (at 50)

Imo it shouldn't. That'd mean there's no way to keep track of the progress of the repair until you reach the point where the door becomes functional again. I also don't think we should be introducing this kind of an inconsistency in the condition system.

Currently, 0% condition means the door is "as broken as it can be", 50% is a "good enough condition to function as a door" and 100% is perfect condition. I don't see the problem with that - if you want to check for the 2nd option specifically, check that the condition is above 50% instead of 0%.

**Comment by mygamingaccount** [comment]
Progress of repair is not tracked, that information is of no value. Broken doors engaging safety systems on the o the hand has value.
Value checking is already awkward. Makes you choose between a false positive report and a false negative.
Checking for greater than is a less dense solution, requiring an extra component. People use regex instead.
