### ISSUE TITLE
CPR stabilization only works briefly during the mouth to mouth

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12519]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

CPR stabilization only works during the very discreet "mouth to mouth" animation that lasts 2 seconds.
Chest compressions do *nothing*, the oxygen level still goes down even with enough medical skill to push stabilization above 100%

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/a4fd1dcd-8638-4ab6-813b-87d889b98f0a)

https://github.com/Regalis11/Barotrauma/blob/60b0e2ae3ed5163c823e8d59bc87a26dac4ab8c4/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs#L1435

**Nobody noticed because CPR's "revive" component is excessively powerful. At 50+ medical skill when stabilization should kick in, revive change is at 25%+ and instantly cures low oxygen** https://github.com/Regalis11/Barotrauma/issues/12468

### Reproduction steps

1. Use these parameters in Afflictions.xml

Revive chance set to 0
60 medical skill should give you the biggest amount of stabilization (300%)

```xml

  <CPRSettings
    revivechanceperskill="0.0"
    revivechanceexponent="2"
    revivechancemin="0.0"
    revivechancemax="0.0"
    stabilizationperskill="0.05"
    stabilizationmin="1.1"
    stabilizationmax="3"
    damageskillthreshold="50"
    damageskillmultiplier="0.02"
    insufficientskillaffliction="internaldamage">    
  </CPRSettings>
  
```

2. giveaffliction oxygenlow 150

3. Equip Health Scanner HUD and start doing chest compressions

4. Change your medical skill to the desired amount. 

5. Notice that O2 only goes up during the 2 seconds of mouth to mouth

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d47bf7eb9b4527d36d23ad9141a03eee7adf1f97

**Comment by Ek-Videogames** [comment]
> Chest compressions do _nothing_, the oxygen level still goes down even with enough medical skill to push stabilization above 100%

CPR always was weird and inconsistent, alot of people talk about it I guess you just didn't notice.
Its always surprising seeing such a inarguable cold-take from Uber of all people.

> **Nobody noticed because CPR's "revive" component is excessively powerful. At 50+ medical skill when stabilization should kick in, revive change is at 25%+ and instantly cures low oxygen** #12468

"Russian roulette heal-button" essentially making CPR into a race between "Will I roll the dice and instantly revive them before the internal organ damage CPR causes kills them" - a common tragedy is a character's passive oxygen loss from being unconscious combined with the fact that CPR damages them even more will kill them, even with high medical skill if you're just 'unlucky' and don't get the magical instant-rez in the first 10 or so seconds.

> CPR stabilization only works during the very discreet "mouth to mouth" animation that lasts 2 seconds. 

Yea I did notice that cool little detail (albeit completely impractical) in the mechanics when I was developing the 'CPR improvement mod.'

- I'm eager to see what changes this next build brings, 
since CPR has barely been touched at all since early retail release.

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4412/commits/cc8174ac37026eea7f46edf089db105ef2127572

Technically works and no issues with changes.
CPR can keep character alive more consistently now, until actual medical issue is resolved.

Commented more on the animation issues in PR https://github.com/Regalis11/Barotrauma-development/pull/4412

Closing ticket.
