### ISSUE TITLE
[SPOILER] Hole To Portal Needs To Be Bigger

### ISSUE THREAD

**Issue by Slykirby116** [Regalis11/Barotrauma#12565]
The hole that leads to the portal for the end of the game needs to be larger to support larger subs of greater size for those wanting none blocky looking subs (no offense to those who made those subs though). Having a larger and wider hole for ships of greater size will allow larger groups of people to enjoy the game as well. I already know the game auto fits the terrain of levels for the ship your using. but it seems it was not turned on for the end mission.

**Comment by Regalis11** [comment]
Thank you for the report!

We've added a warning about the submarine being too large for the end levels now https://github.com/Regalis11/Barotrauma/issues/11025. Supporting a larger submarine would be somewhat complicated, because there are several passages in all 3 of the "end ruins" the submarine needs to fit through. So we pretty much had to choose a maximum size and build the entrance in a way that larger subs can't get through and get stuck in the later levels. While it does restrict the maximum size of the sub, we feel that the current limits are very generous (about 80x32m, which is significantly larger than Berilia, the largest vanilla sub), and that it's an acceptable downside that you may have to switch to a smaller sub if you're playing on something extremely large.
