### ISSUE TITLE
[Feature request] Item transfer machinery

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#1259]
Two linked containers that transfer the items you put inside from one to the other, like the old-timey pneumatic tubes or a dumbwaiter. One-way transfer machines could be used to quickly get mined ore or alien artifacts inside the sub, without getting to the airlock. A two-way transfer machinery could be used for exchanging items inside the sub between diffrent rooms.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
