### ISSUE TITLE
Network blood splatters and keep them there until someone cleans it

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#126]
As an extension to this, perhaps implement "bloody hands" when you cause blunt trauma with a melee weapon? Taking a swim, using soap or using sinks (if we even bother implementing them) would clean you up, including the damage overlays.

And even more ideas: make Assistants spawn point a "custodial's closet" and encourage sub makers to cram janitor's supplies, etc. in it! It would have soap to wipe up blood and other janitorial supplies, making them the real scrubs they're supposed to be :^)

**Comment by G234i** [comment]
This may also requere another job preference aka janitor to be added (since the game is inspired from Space station 13)

**Comment by Crystalwarrior** [comment]
It's better to keep less jobs, though.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
