### ISSUE TITLE
[Feature Request] Better doors and hatches

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [Regalis11/Barotrauma#1260]
Dear Barotrauma dev team
Can you add: hangar doors, armored doors\hatches. 
And make doors destroy under pressure 
Thanks for your attention
VelonacepsCalyxEggs

**Comment by NilanthAnimosus** [comment]
A change I used to make with nilmod was to make explosions damage doors the same way explosions deal damage via EMP, making the explosion deal a % of its structure damage to doors as well as walls.

Though that would just effect explosions themselves, I feel that change could be a vanilla feature, plus adding into the submarine pressure crush mechanic to also target the doors perhaps beyond a certain depth.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
