### ISSUE TITLE
Horizontally placed duct blocks do not cast shadows when closed

### ISSUE THREAD

**Issue by Arctodites** [Regalis11/Barotrauma#12617]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Under certain configurations, duct blocks placed horizontally -- i.e., with a gap oriented left-to-right -- do not properly obstruct line of sight even when closed.  Usually this happens when: A.) a duct block is placed between a vertical inside wall and a horizontal inside wall, or B.) when the duct block is placed between a door and any inside wall (whether vertical or horizontal).  It does NOT typically happen when the duct is placed between two sections of vertical inside wall (see examples circled in red/green in the uploaded images, below).

![Duct Block LOS Example 01](https://github.com/Regalis11/Barotrauma/assets/110938168/86ba0419-3676-45ec-8531-88954494ef8c)

![Duct Block LOS Example 02](https://github.com/Regalis11/Barotrauma/assets/110938168/e4548ab6-5ebd-43d4-9aff-0e065f359b78)

### Reproduction steps

1.) Open the sub editor
2.) Create a test sub
3.) Place a duct block between any two sections of large inside wall (or a section of inside wall and a door), such that the gap of the duct block auto-orients to a horizontal (left-right) orientation.
4.) Make sure that Line of Sight is set to 'opaque' in the game settings menu.
5.) Perform a test-run either in the sub editor or in a singleplayer game
6.) Toggle debugdrawlos on

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

Unstable v1.1.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/A
```

**Comment by Regalis11** [comment]
Thank you for the report! This is a known issue with the algorithm that "merges" the shadow-casting areas of walls, doors, duct blocks and such (visualized by the green lines on the debug view). It tries to stretch them so there's no gaps between them, but there are limits to how far the lines can be stretched. In this case, the shadow caster of the duct block would have to be stretched significantly outside the duct block to reach the shadow caster of the wall above.

It's possible to work around the issue by placing an extra wall piece above the duct like this:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/82e4db0a-fc3a-4bcd-936b-4bbfa671a593)

Regardless, we should find a way to address this because the current behavior is far from intuitive or user-friendly.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78216358ed57fdf32605c96eba3092025dff4d31 (commit in our private repo)

**Comment by Arctodites** [comment]
Thanks for all your efforts as a dev.  It's very much appreciated, and doesn't go unnoticed.  A top-notch game by a top-notch team.

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll still keep it open until we've tested the fix internally and verified it's working as intendend. :)
