### ISSUE TITLE
Restore BarotraumaClient/Content/Effects?

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#1269]
I've noticed that the .fx files are gone now that the assets are no longer on the repo. I find this rather inconvenient since it forces modders to write new shaders from scratch and figure out their signatures from the source code. Ultimately I see no reason to treat the shaders as if they were assets rather than source code.

**Comment by NilanthAnimosus** [comment]
I actually wanted to attempt a few custom shaders and drawing effects when barotrauma was released onto steam for moddings sake, though in all honesty have little to no idea how to create shaders myself enough to create a "Similar enough" shader to the vanilla.

I would like to see the .fx available in some form myself, since those files are not really part of the content folder that ships with the game normally.

**Comment by Regalis11** [comment]
I moved the shaders to a separate folder now, will be merged to the public repo later this week.

**Comment by Regalis11** [comment]
Fix'd
