### ISSUE TITLE
Alterations to the Character.CharacterInfo.IsHuman function

### ISSUE THREAD

**Issue by lowrck** [Regalis11/Barotrauma#12702]
is there any chance alterations can be made to the IsHuman tag to check for a flag in a creature type so that i can make a custom human variant species that is detected by the game as human and put in the crew list? i created a custom class that uses a custom species type but the game doesnt allow it to show in the crew list and doesnt allow setting RewardDistribution or allow requesting money. and it makes it very difficult to kick, ban, give permissions to or otherwise deal with players of the class.

**Comment by Regalis11** [comment]
Thank you for getting in touch!

The issue tracker is intended for bug reports, while this is more of a feature request or a modding support request. [We have an existing ticket in our private repository](https://github.com/Regalis11/Barotrauma-development/issues/3175) about improving the support of custom human characters, but unfortunately it's a bit more involved than just making the IsHuman property editable - that's not actually what determines whether the character is added to the crew or any of the other "human-specific" functions you mentioned.

Since this isn't really a bug report, I'll close the ticket, but that doesn't mean we won't be addressing this at some point! :) Can't give you an ETA unfortunately though.
