### ISSUE TITLE
Getting permanent error: "Disconnecting client vladac100. Syncing the client with the server took too long."

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12720]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My friend (vladac100) regularly (every evening) plays on my server using the Internet of his cell phone (3G, 4G).
In each campaign, about halfway through, he has difficulty connecting. In the server log I see the message:
"Disconnecting client vladac100. Syncing the client with the server took too long."
At the beginning of a campaign and in a single mission he does not have connection problems.
Why it may be? Does it happen if the save size exceed a certain amount?
Is it possible to increase server timeout? How can I do it?

Also can you explain what kind of error regularly appears in the server log:
"Error when writing character spawn data for "Джо": status data caused the length of the message to exceed 255 bytes (194 + 64)"
Where "Джо" is one of my bots
This error appears for every of my bots.
Is it important error?

### Reproduction steps

Play in multiplayer on a dedicated server using poor internet connection, sell phone 3G as example.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

> "Disconnecting client vladac100. Syncing the client with the server took too long."
> At the beginning of a campaign and in a single mission he does not have connection problems.
> Why it may be? Does it happen if the save size exceed a certain amount?

This happens because the server needs to inform the client of what has happened during the round (which items and monsters have spawned, what the current state of the items and the sub are). It doesn't have to do with the save file, it's basically about "what has happened after the latest save was loaded". I suspect it might be the 3G phone connection just might not be fast or reliable enough to get Baro to work smoothly. :/

>Is it possible to increase server timeout? How can I do it?

I'm afraid it's currently not possible - the server determines the timeout automatically depending on the amount of data the client needs to receive. I added an property called "MinimumMidRoundSyncTimeout" to the server settings now though, so it should be adjustable when we get these changes to the public version ([commit in our private repo](https://github.com/Regalis11/Barotrauma-development/commit/0cfc70f807d36f7026d8b9b4313aa7b335034cbe)).

> Also can you explain what kind of error regularly appears in the server log:
> "Error when writing character spawn data for "Джо": status data caused the length of the message to exceed 255 bytes (194 + 64)"

This means a character had a large amount of status data (e.g. lots of different afflictions), and writing it took an unexpected amount of space. This can sometimes happen if you're for example using mods that add a lot of new afflictions. It shouldn't break anything though, although it does make the server use more bandwidth.

**Comment by pavel4win** [comment]
Please can you describe minimal through maximal values for the "MinimumMidRoundSyncTimeout" setting?

**Comment by Regalis11** [comment]
There are no minimum or maximum values, it can be freely set to anything. The value is in second: you could for example try a value of 60 to set the timeout to one minute, or even higher if that's not enough.

Although, unfortunately you will still need to wait for the fix to go out: I'm afraid it didn't make it to the latest Treacherous Tides update, because we didn't get it through our review/testing pipeline in time. :/

**Comment by pavel4win** [comment]
oh, 
I'm willing to wait, thank you.
you are doing a great job.

**Comment by pavel4win** [comment]
Please inform me, when MinimumMidRoundSyncTimeout has been included in the release.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

Played couple rounds in MP
Tested with different values in MinimumMidRoundSyncTimeout 10-50
And simulatedlatency 0-3000

Could not get VM to properly throttle bandwidth for client

No issues found
Closing ticket
