### ISSUE TITLE
[Dev Version] Connection Issues

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1281]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The fucking bug is this. Each time I join the fucking server, I fucking disconnect at the start of the fucking round, which makes me sit out the rest of the fucking round. This is fucking annoying as how you would fucking know, when in game the connection is fine, I could even steer the fucking shuttle properly, I can even fucking communicate well through the dead chat that I'm fucking forced into because I have to automatically fucking die each fucking time I get fucking disconnected. Maybe have the fucking server wait a few more fucking seconds before giving up and fucking kicking me from the fucking game? Fix this fucking shit. 

**Steps To Reproduce**
Play some fucking multiplayer, my dude. Just fucking play it, preferably have the fucking ping be 160.

**Version**
The fucking steam tester's version, what do you think?

**Additional information**
I thought you made the game fucking wait and learned from the fucking bugs everyone fucking encountered in legacy. I fucking guess not. Oh and by the way, some goes for fucking spectating. I cannot fucking spectate without being disconnected, this shouldn't be a fucking problem.

**Comment by Regalis11** [comment]
I'm sorry for the trouble your having, we have some networking-related fixes coming up in the next patch that could be related to this issue. What kind of error messages do you get when the game fucking disconnects?

**Comment by AbominationBanisher** [comment]
It just says "trying to connect to (insert ip address)", then disconnects, mmmmmm.

I think I've found out the solution though. When clicking repeatedly (like a retard) during and before the round start, it doesn't disconnect. An odd and random solution but for now, it seems to work.

**Comment by Regalis11** [comment]
That seems like it could be caused by the automatic AFK kicking logic. We just fixed a bug in it a few days ago that could potentially be causing this, so hopefully the next patch will take care of the issue. Again, sorry for the inconvenience, I know it's really frustrating to get disconnected for no reason and wait until you get to play again.

**Comment by NilanthAnimosus** [comment]
That is a lot of swearing for a copy of the game you got *for free* in a period where *new bugs are expected due to large scale changes associated with an alpha* occurring. I've never read anything that I felt so offensive to read for those that actually try hard to avoid such issues from cropping up and try to fix them as soon as possible, given the entire point of this alpha test is to spot and correct these issues for release while giving constructive feedback for the game.

When the next steam update lands I'll be keeping an eye out for this still being an issue with any unusual looking disconnections, perhaps also to add any timeout messages to the authentication logic to see if anyone times out on connecting if there are any missing there.

This does actually sound familiar though - almost like the server double start. as players would be booted about the exact same manner so just in case I might code in a check for this too as the double load would boot out often some but not all players (Typically most, but it did not boot them all at times).

I don't think many played the last released steam version in multiplayer much due to item syncing issues (Specifically with the dropping of worn/equipped items being lost, such as diving suits or guitars) and less actively playing at once. I remember I used to counter-act syncing issues in legacy with nilmod by periodically adding in a few items of the entire item list's new positions and your new logic is actually very similar to my old logic in that regard (just giving more active objects more updates which is better).

Keep up the good work regalis, looking forward to the next version, the last wasn't really tested so much and we know you can only test so much and need some real gameplay testing to spot most issues.

**Comment by Regalis11** [comment]
All disconnects initiated by the server have a customized message, but in v0.8.9.5 some of them do not work correctly because the localization changes caused specific disconnect messages to be sent in a format the clients couldn't recognize (causing them to show the generic "connection lost, reconnecting" popup). 

I think the more tailored disconnect reasons are a really good idea, I think I'll add that and some additional debug logging to the console to help diagnose these issues.

**Comment by AbominationBanisher** [comment]
> That is a lot of unnecessary swearing for a copy of the game you got _for free_ in a period where _new bugs are expected due to large scale changes associated with an alpha_ occurring. I've never read anything that I felt so offensive to read for those that actually try hard to avoid such issues from cropping up and try to fix them as soon as possible, given the entire point of this alpha test is to spot and correct these issues for release while giving constructive feedback for the game as it develops to make it more fun, though the aggravation is pretty fair I'd probably be pissed too.
> 
> When the next steam update lands I'll be keeping an eye out for this still being an issue with any unusual looking disconnections, perhaps also to add any timeout messages to the authentication logic to see if anyone times out on connecting if there are any missing there.
> 
> This does actually sound familiar though - almost like the server double start. as players would be booted about the exact same manner so just in case I might code in a check for this too as the double load would boot out often some but not all players (Typically most, but it did not boot them all at times). I'm pretty sure they did load the identical and correct seed and such from the double start as it never loaded extra entities, in any other order or changed the seed due to netlobby code so it was never a case of syncing problems - so it is more like having a prolonged load, which may also have been a mass disconnect due to AFK kicking logic.
> 
> I don't think many played the last released steam version in multiplayer much due to item syncing issues causing deaths (Specifically with the dropping of worn/equipped items being lost, such as diving suits or guitars) and less actively playing at once. I remember I used to counter-act syncing issues in legacy with nilmod by periodically adding in a few items of the entire item list's new positions and your new logic is actually very similar to my old logic in that regard (just giving more active objects more updates which is better).
> 
> Keep up the good work Regalis, looking forward to the next version, the last wasn't really tested so much and we know you can only test so much and need some real gameplay testing to spot most issues.
> 
> Do AFK-kick based disconnects have customized messages? If not I think it should so this could be spotted much easier if it persists, perhaps even for the test or overall future have more tailored disconnect reasons to their more specific cause. (IE. if a syncing error - also state the why, such as event no longer exists, event requested is too old, entity did not exist or what stage of authentication it booted at and such).

Not defending myself, but this was after me trying and failing to participate in a game four times in a row. Whoops.

**Comment by NilanthAnimosus** [comment]
I don't know where to stick this so im sticking it in here:

had another desync kick on my server and noticed the server console gave me interesting information

this is not the beta branch, it is still 0.8.9.6 closed steam alpha (none beta) - windows:

![image](https://user-images.githubusercontent.com/29177976/54783082-5fb2f300-4c18-11e9-88b8-1c44dfa27316.png)
