### ISSUE TITLE
Overvoltage of EDCs is not working

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12828]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Looks like there are no ways to overload the Electrical Discharge Coil.
I found the code that means it's allowed to overload the EDC and it will deal damage by (strength * voltage) points.
https://github.com/Regalis11/Barotrauma/blob/12e43d95efcb6cf4823863002eac8cceed7a7d50/Barotrauma/BarotraumaShared/SharedSource/Items/Components/ElectricalDischarger.cs#L229
I tried two ways but neither worked
First way: pull power from the grid.
Second way: pull power from the power container.

### Reproduction steps

1. Test with the sub: 
[Training Ground unstable.zip](https://github.com/Regalis11/Barotrauma/files/12930318/Training.Ground.unstable.zip)
2. There's a button on the left that is used to trigger an EDC that is pulling power from the super capacitor. It should deal burn damage to the engineer (wearing a -20% burn suit) by 14%, but in fact it's only 7%.
3. Another EDC on the opposite side should pull power from the grid, but in fact it isn't and can't be triggered.

![image](https://github.com/Regalis11/Barotrauma/assets/73634685/cd169f26-eddc-40ee-9edc-9ffba72844d8)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

It seems this is a consequence of the changes done to address https://github.com/Regalis11/Barotrauma/issues/10347. It's currently not possible to overvolt the EDC, because 1. supercapacitors can't provide overvoltage, the EDC just pulls as much power as it needs from the capacitor 2. electrical grids can't provide enough power to trigger the EDC.

I don't think it hurts to keep this logic in though, because it can still be used by other items that use the ElectricalDischarger component.
