### ISSUE TITLE
Can someone (allow to) add music to https://barotraumagame.com/wiki/Music?

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#12833]
Can someone (allow to) add music to `https://barotraumagame.com/wiki/Music`?

`Stub Notes: Need to ask for a spam filter exemption and the devs' permission to upload music. Notes on when newer tracks play (spoilers?)`

**Comment by Regalis11** [comment]
I think you're going to have to ask our publisher Daedalic: info@daedalic.com

My gut feeling is that this would be difficult to do due to all the legal questions related to the copyrights and licensing terms of the soundtrack. I don't really see why they should be included in the wiki anyway: the wiki should be information about the game, not a place to share content from the game.

**Comment by Ek-Videogames** [comment]
So moving to the "official" wiki site has hamstrung it, because it's not actually affiliated with the game's developers&community?

**Comment by Regalis11** [comment]
Quite the opposite, the official wiki site is owned by us developers and to a large extent run by the community (unlike the old wiki). 

It's just that copyright and music licensing matters are complicated, especially in cases like this where there's multiple parties involved (us devs, the composers/artists behind the music, the publisher), and since Daedalic owns the publishing rights to the game, including the soundtrack, it's better to ask them.

**Comment by SoNickRND** [comment]
@Regalis11 I don't have the wiki account, so, maybe the music page should be removed?
