### ISSUE TITLE
[Dev Version] Auto closing doors

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1283]
This is currently my biggest pet peeve in the alpha version. It is doors closing automatically behind you. 

I get why you guys might have wanted autoclosing, as to minimize flooding caused by small leaks and such, but this is simply not the right solution.

When trying to go there and back when the sub is flooded, especially in a compact sub like "Orca", and especially using a water scooter, it gets tedious opening the doors over and over again.

Especially when combined with bad pings around the area of 140, this basically turns the doors into people crushers, as you cannot run into an open door without it closing automatically in your face. It's just tedious.

That's about it. Auto closing needs to be removed.

**Comment by AbominationBanisher** [comment]
> auto closing doors are a feature of the submarine and not the door itself, the doors don't automatically close on their own, you can edit the submarines or remove the wiring of such. its really down to the submarine designer.
> 
> The AI also loves closing doors behind it as a side note and tries its best to do so.

Aaaah, I realize, thanks.

It's not the game, it's the crappy default sub, lmao.

**Comment by JJRcop** [comment]
We just rewired all the doors directly to the buttons one time when we got sick of it, not that big of a deal. Nilanth is right about it being a feature of the sub.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
