### ISSUE TITLE
Traitor update question

### ISSUE THREAD

**Issue by furia155** [Regalis11/Barotrauma#12846]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While playing after the new traitor update, i got a mission to poison the VIP. After successful poisoning, the guards of the VIP started attacking me which outed me as a traitor. Was it how it was meant to make me eliminate guards first or was it unintended?

### Reproduction steps

It is pretty self explanatory, got a traitor mission during the VIP transport and poisoned him with provided morbusine after which the guards attacked me. 

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional, the guards always defend the VIP regardless if the attacker is a traitor or not. You need to use some creativity to pull this off without getting caught - for example, you could incapacitate the VIP somehow so they can't call the guards for help, do the poisoning outside the radio range of the guards, kill the guards too or discreetly lock them away somewhere...
