### ISSUE TITLE
OnSpawn won't play its sounds when it spawns first time

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12995]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Look into the following xml code:
```xml
  <Item name="" identifier="otfx_hellfiregrenadesafetypin" noninteractable="true" hiddeningame="true" hideinmenus="true">
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="0,0,2,2" depth="0.55" origin="0.5,0.5" />
    <ItemComponent>
      <StatusEffect type="OnSpawn" target="This">
        <Sound file="%ModDir%\OTFX\Items\Weapons\grenade_pinpull1.ogg" range="500" selectionmode="Random" />
        <Sound file="%ModDir%\OTFX\Items\Weapons\grenade_pinpull2.ogg" range="500" />
        <ParticleEmitter particle="otfx_hellfiregrenadesafetypin" particleamount="1" copyentityangle="true" anglemin="70" anglemax="100" velocitymin="100" velocitymax="200" />
        <Remove />
      </StatusEffect>
    </ItemComponent>
  </Item>
```
when you spawn 'otfx_hellfiregrenadesafetypin' first time, it won't play any sounds. If you spawn it again, except the first time, the sounds will play.

### Reproduction steps

1. Start game with [OTFX.zip](https://github.com/Regalis11/Barotrauma/files/13309204/OTFX.zip) mod enabled
2. spawnitem "otfx_hellfiregrenadesafetypin" within 5 meters of you
3. You hear nothing
4. spawn again
5. You will hear something

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This seems to happen because the effect attempts to play the sound immediately after the object has spawned, when the sound is still being loaded. Items spawned afterwards are able to reuse the sound loaded for the previous items, so this only applies to the one you spawn first.

I addressed this in https://github.com/Regalis11/Barotrauma-development/commit/88220703325aba99a284df9d609b7086585224e8 by making the effect wait for the sound to be loaded, but for now, it should be possible to work around this by adding a very brief delay to the effect (0.1 s most likely be enough).

**Comment by zhu-rengong** [comment]
> but for now, it should be possible to work around this by adding a very brief delay to the effect (0.1 s most likely be enough).

Thanks!
