### ISSUE TITLE
Allow drugs to be used in smaller doses for the same total effect + add stabilizing drugs + Implement Projectile for more medical types

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1299]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
in a game like campaign where resources matter, items like bandages get immediately used usually, but often do almost nothing for the actual wounds like bleeding effects, as if only targeting a single bleed even though they are all seemingly low strength.

It would be nice for a lot of drugs to be able to space the medicines out more, such as 2 uses of bandages / 3-4 uses of plastiseal, 4-6 uses of antibiotic glue, 3-4 uses of morphine, 2-4 uses of saline, 3-4 uses of blood bags and such. while having an equivalent change in effect for the change of uses.

lethal drugs should keep their current usage counts.

Inventory is tight and most classes don't have a container to store gear, 

Perhaps even have usage based off medical skill, where doctors require less of it than none doctors (This is already the case with antibiotic glue, but at best it is only 2 uses).

IE. for 4 uses of morphine, have 1/2 the previous effect.

There are currently a lot of medicals which feel almost utterly wasteful to use, where even 30% internal damage feels like a waste to heal.

In legacy, we had 2-4 use drugs, and although this meant a log of injections when you needed it  fast, people usually die slower and have ways to avoid deaths.

perhaps in addition, new medicines that maintain the stability of a patient (IE. chloromodryde which I cannot spell from legacy or Inaprovaline), which are specially coded to effectively set a minimum (or far harder to pass) vitality modifier on the unconscious, IE. if below 50% negative vitality, make the vitality modifier worth 30-50% more and/or keep it scaled. perhaps even simply have it as a multiplier on the strength/weight of certain affliction types almost like an affliction armour status effect (Though they should still deny exiting an unconscious state).

never enough to wake them up but enough to halt, prevent or slow down death during treatment of critical cases.

Additionally, many types of medicals that would make sense placed into a syringe gun cannot be used as ammunition, most if not all harmful toxins cannot, and a good number of indifferent or positive ones, only a select few appears to be usable inside of a syringe gun.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
