### ISSUE TITLE
Lights sometimes go through walls

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#13005]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Lights can go through walls in some situations. This happens because of the way the results of the raycasts are handled in `LightSource.RayCastTask`: we do 2 slightly offset raycasts to hit the segment and whatever is behind it, but it's also possible that one of the raycast actually hits something in front of the segment, causing us to add a vertex that should be obstructed into the light volume. 

Example pic: when we're raycasting towards point 1, the raycast hits point 2, adding both of those as vertices to the light volume, even though the 1st one is obstructed by the door.
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/a0c6a180-05db-4a78-8bce-880780abaec2)

### Reproduction steps

One easy place to repro this is the command room in Dugong, as shown in the pic above. Take a flashlight, aim left into the engine room, and walk to the right - in specific spots, you should see the light going through the door of the engine room.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by BlackMoons** [comment]
Ever considered adopting GPU based shadows? It should be possible to render a 1 pixel wide 'strip' depth buffer that represents what the light sees in a 360 degree view, like how 3d lighting works (May take 4 render passes to make a cube map style to avoid distortion?). Would take some clever math in the GPU shader but I believe this game has GPU time to spare in the pixel shader department. Then you'd just render the light mask by looking up the shadow texture depth of what each pixel is along that axis to the light.

Objects that cast shadows would be rendered as lines (any camera facing edges) to set their depth info in the buffer. Imagine the 2d world as just a 1 pixel wide 3d world and apply the same shadow algos as used for point lights. (And maybe give us directional lights too)

**Comment by Regalis11** [comment]
> Ever considered adopting GPU based shadows?

We have, but it's seemed like switching to one would be quite a time-consuming task which we don't really have the resources for. I also have some doubts about whether that kind of an approach would even give much performance benefit: generating that "depth buffer" seems like something that would most likely be much heavier than generating the geometry of the light volume based on the shadow-casting convex hulls around the light.

There was one attempt at implementing something similar to this here https://github.com/Regalis11/Barotrauma/pull/8570, and the performance was a huge problem even though in that case there was only a single "light source".

**Comment by BlackMoons** [comment]
that is a very cool approach but its nothing like basic 3d shadow rendering.

The great thing about basic 3d shadow rendering is that your not rendering anything complex at all. your not even needing to switch textures unless your doing alpha cutouts ie tree leafs and such. (maybe something for doors with windows?), your basically just rendering untextured geometry to a depth buffer. 

#8570 tried to implement penumbra and physically correct shadows. I am just saying improved the speed of the existing shadows, way less steps and GPU overhead. 

Picture rendering all the geometry of shadow casters, as line objects (Or camera aligned quads?). you render the 4 edges of each shadow casting enabled object. Can be one big vertex buffer, drawn in one draw call with 4 lines (quads?) per object, maybe 8 per door since they have a hole in windowed doors. Very small vertex buffer, 100~10000 vertices is literally nothing to a GPU as long as its one draw call/vertex buffer upload with no state changes required like texture. 

The GPU can easily do this, outputting to a 1x1024 texture is the simplest task in the world to modern gpus (other then the cost of switching to a new render target, that is expensive). Then you just use the depth written to calculate shadows when drawing the light texture.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
