### ISSUE TITLE
Add an option for multiplayer AI to limit their dialogue on servers (Or single too).

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1300]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In multiplayer, some players have expressed annoyance at the AI having conversations as if its single player, while some other players like it.

I suggest adding an option (Even if only a command that saves or a server setting in the XMLs) for the multiplayer AI to have them either have random conversations (A sort of full mode), or only to spotted threats/order received/danger and such (a limited/partial mode) and a silence state (Where they are either saying nothing anymore, or confirm an order and that is it).

I think just adding an option for their dialogue to be on/off is very sufficient, but whatever seems appropriate. some players/hosts just do not seem to want to hear the AI converse with each other when used to fill or add to a servers population.

there are some points in the code (Such as barotrauma server -> game session ->  crewmanager -> CreateRandomConversation(); and tweaking that to be based on a server setting if it should add random conversations or not.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
