### ISSUE TITLE
Crash on startup if internet is On

### ISSUE THREAD

**Issue by zaap38** [Regalis11/Barotrauma#13173]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hi,

Barotrauma was working correctly until the last update. Since then, if my WiFi is on, Barotrauma won't start (crash after the first loading). However, if I turn off the WiFi, I can play the game, but then it is impossible to connect to multiplayer.

What I tried so far:
Check files (multiple times)
Uninstall/Reinstall
Restart computer

Nothing is working.

I'm playing on Windows 10 with a NVIDIA 3060.
I precise, this is only affected by my actual WiFi, not turning offline mod on steam.
I have no mod installed.
Network drivers are up to date.

### Reproduction steps

1. Get the new update
2. Have your WiFi (supposingly any internet connection) turned on.
3. Crash after the first game loading, after a 2s freeze then game closing.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by zaap38** [comment]
Someone else is having the same issue (see official Discord).

**Comment by mygamingaccount** [comment]
You have a crash log?

**Comment by zaap38** [comment]
> You have a crash log?

Unfortunatly it does not generate any.

**Comment by Regalis11** [comment]
Thank you for the report! This seems similar to, or perhaps even the same issue as https://github.com/Regalis11/Barotrauma/issues/11523, which we unfortunately still haven't been able to properly diagnose and fix.

As mentioned in that other ticket, it's possible to prevent the game from fetching any data from our master server (which we're suspecting could be behind these issues) by adding `RemoteMainMenuContentUrl=""` to the config file config_player.xml inside the game folder. Could you please give that a test and see if it resolves the problem? That'd be a valuable clue for diagnosing the problem. Thank you and sorry for the inconvenience!

**Comment by zaap38** [comment]
> Thank you for the report! This seems similar to, or perhaps even the same issue as #11523, which we unfortunately still haven't been able to properly diagnose and fix.
> 
> As mentioned in that other ticket, it's possible to prevent the game from fetching any data from our master server (which we're suspecting could be behind these issues) by adding `RemoteMainMenuContentUrl=""` to the config file config_player.xml inside the game folder. Could you please give that a test and see if it resolves the problem? That'd be a valuable clue for diagnosing the problem. Thank you and sorry for the inconvenience!

Hi, I already tried this when discussing on discord, where the same potential issue has been raised. It indeed works, but then multiplayer is unnaccessible.

**Comment by Daniel-Chin** [comment]
I can confirm that this issue is related to VPN. If I exit in UAE the game freezes and crashes. If I exit in Egypt it works fine. This is confusing because`remotemainmenucontenturl="https://www.barotraumagame.com/gamedata/"` uses https verification. Does the main menu read data from other hosts depending on DNS?

**Comment by Regalis11** [comment]
> Hi, I already tried this when discussing on discord, where the same potential issue has been raised. It indeed works, but then multiplayer is unnaccessible.

To clarify, does multiplayer become inaccessible when you only edit the value of RemoteMainMenuContentUrl? That should not be possible, because that setting only controls where the game tries to fetch the main menu changelog from.

I think @NilanthAnimosus suggested a couple of other solutions to you on Discord: deleting GameAnalytics.dll and disconnecting from Steam. I assume one of those fixed the issue - any idea which one it was? Did it start working when you deleted GameAnalytics.dll or did you need to disconnect from Steam too?

@Daniel-Chin 

The main menu data shouldn't read data from other hosts. Did you try whether emptying the url does anything? If not, could please you try deleting GameAnalytics.dll from the game folder and see if that helps (that would also be another valuable clue for diagnosing the issue)?

Thanks and sorry for the trouble! :/

**Comment by Daniel-Chin** [comment]
I did "verify integrity of game files" with Steam, and performed the following tests. Unless stated otherwise,  
- `remotemainmenucontenturl="https://www.barotraumagame.com/gamedata/"`.  
- "GameAnalytics.NetStandard.dll" is present.  
- VPN is off, and my IP is in the UAE.  

> Did you try whether emptying the url does anything? If not, could please you try deleting GameAnalytics.dll from the game folder and see if that helps (that would also be another valuable clue for diagnosing the issue)?

- `remotemainmenucontenturl=""`. Game freezes and crashes. The moment the game freezes, process RAM drops from 1GB to ~40MB. The game freezes for 3 seconds before exiting.  
- "GameAnalytics.NetStandard.dll" is absent. Game freezes and crashes.  
- `remotemainmenucontenturl=""` AND "GameAnalytics.NetStandard.dll" is absent. Game freezes and crashes.  

> The main menu data shouldn't read data from other hosts. I also got a VPN a gave an UAE IP a test, but unfortunately couldn't reproduce the issue: the game seems to launch and run with no issues. :/

- VPN to Egypt. Game OK.  
- VPN to Egypt AND `remotemainmenucontenturl=""`. Game OK.  
- VPN to UK. Game OK.  
- VPN to US. Game OK.  
- VPN off. Game OK (!?!?)  
- Verify integrity of game files. Steam reports to have re-acquired 2 files.  
- Another test. Game freezes and crashes.  
- VPN to Egypt. Game OK.  
- VPN off. Game OK!  
- Verify integrity of game files. Steam reports to have re-acquired 2 files.  
- VPN off. Game freezes and crashes.  
- VPN off. Game freezes and crashes.  
- Turn the VPN on and then off. Game freezes and crashes.  
- Verify integrity of game files. Steam reports no file is corrupted.  

The above tests are reported as a time sequence.  

Conclusion: launching the game once with VPN on changes some game files which fixed the issue, but the fresh game doesn't work in my environment. I'm diffing the files after I submit this reply. 

> Thanks and sorry for the trouble! :/

Hey, thanks for the game!

**Comment by zaap38** [comment]
> > Hi, I already tried this when discussing on discord, where the same potential issue has been raised. It indeed works, but then multiplayer is unnaccessible.
> 
> To clarify, does multiplayer become inaccessible when you only edit the value of RemoteMainMenuContentUrl? That should not be possible, because that setting only controls where the game tries to fetch the main menu changelog from.
> 
> I think @NilanthAnimosus suggested a couple of other solutions to you on Discord: deleting GameAnalytics.dll and disconnecting from Steam. I assume one of those fixed the issue - any idea which one it was? Did it start working when you deleted GameAnalytics.dll or did you need to disconnect from Steam too?
> 
> @Daniel-Chin
> 
> The main menu data shouldn't read data from other hosts. I also got a VPN a gave an UAE IP a test, but unfortunately couldn't reproduce the issue: the game seems to launch and run with no issues. :/
> 
> Did you try whether emptying the url does anything? If not, could please you try deleting GameAnalytics.dll from the game folder and see if that helps (that would also be another valuable clue for diagnosing the issue)?
> 
> Thanks and sorry for the trouble! :/

Hey, I confirm to you that simply removing "https://www.barotraumagame.com/gamedata/" was enough to make it work, but then the "Host Server" option was unclickable.

I did not removed GameAnalytics.dll.

So far the best fix I found is to downgrade to the previous version, since I'm only playing with a specific group of friends who also dowgraded.

**Comment by Regalis11** [comment]
Thank you for the followup! I think I was actually able to reproduce and fix this now: enabling TOR on top of the VPN seemed to do the trick. It seems the issue was that a particular method that logs an error message in the debug console caused a stack overflow (which causes the game to immediately crash without being able to write a crash report). One of the places where that method was being used was logging an error if the GameAnalytics consent server returns an error code, which seems to happen when trying to access it from certain kinds of IP addresses.

Thank you so much for the help with diagnosing this, we'll try to push out a hotfix for this asap (hopefully even later today)!
