### ISSUE TITLE
Implement deterioration and repair for vents

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1322]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Vents are moving mechanical components, personally I think they should be powered in some way and add to the subs power drain (and thus stable load) normally, but ignoring this they still are moving mechanical components and as such perhaps deserve to be repairable ones and have worse airflow the more they degrade.

they should have some of the slowest degrading if they do, and I cannot think of any submarines where the air fans are completely  unreachable to make this an infeasible concept to implement.

They could look interesting in the environment with some badly maintained decay sprites on top and/or reduce their animation speed from decay.

finally, when broken. it could be they still transmit some air with an operational oxygen generator, but only 10% of the normal airflow at most due to the mechanism to make it flow breaking.

**Comment by thegrb93** [comment]
I don't think vents are mechanical.. The O2 gen pumps the air. Would interesting if they could be broken or clogged though for traitoring purposes.

**Comment by NilanthAnimosus** [comment]
they have a moving fan when you actually look at it, as for broken/clogged for traitor purposes I believe that breaking an item intentionally as a feature should be a potential mechanic of its own.

**Comment by AbominationBanisher** [comment]
Yeah, had to fix my bathroom vent last week, It's realistic. It also works. Repairing vents is a good game idea.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
