### ISSUE TITLE
[Vanilla] Failed to find a target item for the mission "gotoend2".ltem tag:logbook2

### ISSUE THREAD

**Issue by EricDasha** [Regalis11/Barotrauma#13236]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

At the end of the game I couldn't continue the mission, click f3 and I found this error report
![Snipaste_2023-12-27_21-24-06](https://github.com/Regalis11/Barotrauma/assets/146364373/fa945c07-2353-4099-bc42-03c9e81b2373)
I'm not sure if it's because of the mods, so here's my list of mods
![Snipaste_2023-12-27_21-25-54](https://github.com/Regalis11/Barotrauma/assets/146364373/9b9e8376-6fc5-4089-810c-8e08f21ed992)
“搬炮弹”is a practical mod that doesn't require Lua For Barotrauma so I was the first to rule it out
But I couldn't even reinstall the game to get this quest item, so I felt it was a game problem
I didn't know if you needed my game archive, so I uploaded it
[保存.zip](https://github.com/Regalis11/Barotrauma/files/13778907/default.zip)
Excuse me for not finding the error log. Where is it

### Reproduction steps

At the end of the game I couldn't continue the mission, click f3 and I found this error report
![Snipaste_2023-12-27_21-24-06](https://github.com/Regalis11/Barotrauma/assets/146364373/fa945c07-2353-4099-bc42-03c9e81b2373)
I'm not sure if it's because of the mods, so here's my list of mods
![Snipaste_2023-12-27_21-25-54](https://github.com/Regalis11/Barotrauma/assets/146364373/9b9e8376-6fc5-4089-810c-8e08f21ed992)
“搬炮弹”is a practical mod that doesn't require Lua For Barotrauma so I was the first to rule it out
But I couldn't even reinstall the game to get this quest item, so I felt it was a game problem
I didn't know if you needed my game archive, so I uploaded it
[保存.zip](https://github.com/Regalis11/Barotrauma/files/13778907/default.zip)
Excuse me for not finding the error log. Where is it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This seems like the same issue as https://github.com/Regalis11/Barotrauma/issues/12575. That one occurred if you'd finished the campaign once and then returned to the end of the map again - the logbook you'd taken from the level on the first playthrough would still be gone from the level. The issue was fixed in The Treacherous Tides update (v1.1.14.0), but if you'd completed the campaign for the first time in an earlier version, it would still occur even in the latest version. Could that be what happened in your case?

**Comment by EricDasha** [comment]
Yes, I completed a campaign in the past version and reached the end of the campaign the second time, so what should I do to recover, because the game has been played for a long time and I don't want to open a new save

**Comment by Regalis11** [comment]
There's unfortunately no easy way to work around the issue - I think the save file needs to be edited to "undo" the items being taken away from the level (by removing them from the "takenitems" element of the location). If you send us the save file here, I can take a shot at editing it. Note that you need to .zip the file first to attach it here, because GitHub doesn't allow attaching files with the .save file extension. Thank you and sorry for the inconvenience, I can imagine how frustrating it must be for a very long-time save to get broken like this. :/

**Comment by EricDasha** [comment]
Thanks, this is my game save, it would be great if you could fix it
[保存.zip](https://github.com/Regalis11/Barotrauma/files/13809433/default.zip)

**Comment by Regalis11** [comment]
There you go:
[保存.zip](https://github.com/Regalis11/Barotrauma/files/13809531/default.zip)

**Comment by EricDasha** [comment]
thank you！
