### ISSUE TITLE
Allow horizontal resizing of text display components

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1324]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It would be nice if these components could support resizing the length to fit more or less characters at once. seeing one word at a time when there is space in the room for a text display of 4-5 words really does make me wish this was a thing.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
