### ISSUE TITLE
Lights aren't working unless I look away from them 

### ISSUE THREAD

**Issue by Facehurt1** [Regalis11/Barotrauma#13272]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://clips.twitch.tv/TameSincereWrenchHoneyBadger-wEOnc7pW579wAZpK

Here is an example of the bug 

Here is the item assembly

https://steamcommunity.com/sharedfiles/filedetails/?id=2545207873&searchtext=server

### Reproduction steps

1. load the assembly into a sub
2. hook it up to reactor
3. watch as the lights go out as you look at it :(

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Facehurt1** [comment]
nvm not fixed the exact same thing happened when I tried to fix it by building it from scratch

**Comment by SomeRandomNoobKekeke** [comment]
probably because light limit is reached
you zoom out - more lights fit on screen - more than light limit - some of them disabling
try increasing visible light limit in settings

**Comment by Regalis11** [comment]
Thank you for the report!

It does seem like this is caused by the light limit. When there's a very large number of lights visible, the game hides some of them for performance reasons (preferring to hide small / unimportant lights further away from the character). It seems this assembly includes a pretty huge number of lights (more the total number of lights in vanilla subs), so it seems to easily make the number of visible lights go over the limit.

Could you try increasing the "visible light limit" in the game settings and see if it helps? Sorry for the inconvenience!

**Comment by Facehurt1** [comment]
YEP, now everything works, thanks!
