### ISSUE TITLE
add some kind of artifact transport container to prevent their effects in-sub.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1328]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
it would be nice if we had some kind of container that blocked out and prevented the artifacts effects. one that had say, 1-3 slots. or an Achilles heel like requiring a battery cell or other item to prevent the effects from going off.

having the air drained out is often hilarious, yet having to transport an incendium artifact to a safer spot (Ballast) or to your deconstructor (which is suicide and rather explosive given what fire can do to say, oxygen/welding tanks and such) I feel realistically there would have been a more sane way to transport these items, even if it was an alien container!.

Imagine if the fulgurium-based artifact was basically an indoors-only activating electrical discharge coil? I'm sure one would love to have their artifact container then.

The alternative to not having some method to transport it, has always been wasting tons of time and fuel to flood a submarine to carry a thermal. though even this can still hurt you if I recall. the only safe ways are to build external deconstructers and/or artifact containment rooms which is just less preferable if you ask me and could be done even if the artifact transport container existed.

This essentially is needed to make crafting with them useful and not a 15-20 minute chore intentionally flooding a sub with auto-closing doors and auto-opening ballast tanks that drain.

if the container did not last forever, this I would not mind, you usually just want to get it from A to B fast, hence why I Wouldn't mind a consumable way to do it - or perhaps have it break and release the effects of whats contained yet always allow it to deconstruct for its full material worth to simply replace/repair it so to say while still keeping it a threat.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
