### ISSUE TITLE
Add an XML tag for skillgain - implement it into medical items and weapon Attack tags

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1344]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
concept is simple, implement skillgains for medical item usage (Self/Other) that can be configured per-item, without taking guesses based on damage dealt/affliction gained or removed and such.
 
Would be nice to have it exist - even better if it is eventually implemented, perhaps with conditionals or a built-in check for a living receiving character in the use / attack methods and/or minimum affliction strength for it to count.

this would allow medics to gain skill beyond fabrication and CPR while allowing weapons to be earned through railgun hits or weapon strikes instead of crafting.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
