### ISSUE TITLE
Improve campaign save handling when playing as a client host

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1347]
Currently the server treats the client who's hosting the server the same as any other client when it comes to campaign saves. I.e. the servers sends the save files to the client, and the client decompresses and loads them as usual. I haven't done much debugging on this yet, but I would assume that reading/writing to the same file as the server can cause a ton of bugs: save files becoming corrupted, exceptions if the other application is locking the file, the client overwriting an up-to-date campaign file with a previous one...

**Comment by Regalis11** [comment]
Should be fixed in c2e8263

**Comment by NilanthAnimosus** [comment]
I have some questions regarding these fixes - specifically to 1 case of it and what the behaviour would be since I am not fully understanding how ownerkey is handled.

If someone uses the dedicated server in their steam directory separately, but plays from their steam directory (so they setup a server that does not require them connected to exist - but still connects via 127.0.0.1 without using the host server function in the menus) - what is the behaviour of this?

I assume ownerkey would be equal to 0, despite it being 127.0.0.1 they would skip the fixed code if ownerkey is 0 as that treats them as a none-owner just the same as if 127.0.0.1 was not the address.

I believe this would cause the above bug that is fixed to appear in that use-case.

**Comment by Regalis11** [comment]
You're right, if you start the dedicated server and the client executable separately, the client wont be the owner of the server. However, I think these changes should still work: the server and the clients still decompress the files into separate temp folders, and if they happen to attempt loading a file that's locked by the other application, the "wait and retry" logic should be able to work around that.

There is still the issue that the separate server instance will transfer save files to the client even if the client could access them directly. I'm actually not 100% if it can cause problems or not; after the changes in 86c4b6a the client should be able to "receive" them successfully, but it might be possible that there are edge cases where the client receives an outdated save and overwrites the most recent one before the server has initiated a new transfer. So we might still need some extra safeguards to make sure that doesn't happen.
