### ISSUE TITLE
Feature Request: Reset Steering Vector Button

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1348]
It would be extremely helpful if there was a button to reset the manual steering vector to (0,0) at all times (even when not manually steering). This would help keep the ship still in a hurry. I also ask that it be available even when not manually steering so that you can center the vector before switching back from "maintain position" in autopilot mode, preventing unecessary movement.

**Comment by NilanthAnimosus** [comment]
essentially, something to tell the sub to slow down and cease moving, but not move back or set a specific position but just try to maintain its position whatever it may be?

this would be nice if that is the suggestion, as maintain goes above/below the target point and keeps utilizing 100%/-100%, using power and generally is active a lot while sometimes I just want to try to stop the sub moving IE sinking, and not have the sub simply return and slam into something on the way (IE, sink past a cliff after a moloch knows you off, repair the sub and drive right back into said rock).

Instead of maintaining a position - to maintain a full stop of sorts while counting added/removed water to maintain a velocity of 0km/h sink/rise/forward/back forces?

I wouldn't mind such a function of the nav terminal.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
