### ISSUE TITLE
[Feature Request] Don't clear chat text field when clicking in the navigation terminal

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1354]
As it is right now, if I am steering the ship, maybe typing a message telling someone where a leak is, and I need to make a slight adjustment to our course, when I click on the navigation terminal's monitor, the chat text field is deselected and I have to completely retype my message all for the sake of a slight adjustment.
This is really inconvenient as this wiped message I was typing could be anything ranging from a leak location to a endworm approaching the ship.
It would be nice if clicks within the navigation terminal didn't wipe the chat text field clean.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
