### ISSUE TITLE
Add "Move to that room" and "Fix items in that room" bot orders

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1360]
Some parts of the sub are not as important as other. Just ordering a bot to fix items makes them start wandering around the whole submarine, looking for things to fix, sometimes giving too much attention to unimportant parts of the sub and neglecting vital systems.
It would be great if you could tell a bot to stay in a room with important parts and keep it in good condition.

It also would become easier for you to make them go and fix a certain place that has been broken. Right now you have to either do it manually, or at least move them to that room and then order them to do their job(or just tell them to start fixing things and hope they will stumble upon the important parts, but that could take too long).

---

An order that makes crewmembers go to a certain room would save a lot of time. Making the captain go to the control room, making the doctor go to the medical storage, making the security go to the armory, etc.
Right now you have move them manually, which delays your work on other important tasks, and is taking a lot of time in the long terms. Since the equipment on the sub is deteriorating, and staying in one place for too long makes you have to deal with more creatures attacking you, it's important to use your time as effectively as possible.
If you could just tell a bot to go to a certain room, you would be able to use the extra time to deal with the more important tasks, such as steering the sub or loading railgun shells during a battle.

---

Overall this would make controlling a submarine full of bots a bit less of a manual and tedious task.

---
Perhaps the way you make the order could work similarly to the railgun orders. You would get ui with the rooms of the sub and click on the room you need. If the room is inaccessible, the bots should respond accordingly.
![-2019-mar-26-006](https://user-images.githubusercontent.com/38168249/54984505-8f2f7a00-4fe1-11e9-946e-c173b3b08395.jpg)

**Comment by itchyOwl** [comment]
Good idea! We've been thinking about some kind of priority list for the bots. Possibly based on the class. Introducing more options that the user can choose is on the todo list. In my opinion the hull map could be used more. Some commands like "operate item" should probably be "operate and maintain", where it relates to your suggestion. Have to design, test, and implement ;)

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
