### ISSUE TITLE
[Steam Version] Grabbing non-stunned crew members

### ISSUE THREAD

**Issue by armadillosloth** [Regalis11/Barotrauma#1368]
As a security officer it’s always annoying to have to track down and stun someone to be able to handcuff them. I propose a space station 13 style grab, where you can instantly grab someone to drag them somewhere, but have to spend some time to take anything off them or cuff them. If this was to be implemented, it would add a lot of depth to the game. A possible use of this would be to plant evidence on a person while they aren’t paying attention, or cuffing someone without having to waste the charges of your baton.

**Comment by NilanthAnimosus** [comment]
You can do this amusingly (though irritatingly) with the medical system and if you catch them, can stun then.

Of course, I wouldn't mind security / high weapons skill characters to be capable of a tackle/grab maneuver at distance, they would in theory be capable of this.

You can demand a person to ragdoll and then cuff them, and if they resist well their resisting - a stun baton comes into play. Not so sure about being always able to cuff players, I feel that will not be as good as it sounds. A player capable of cuffing you without stun means you cant resist if he reaches you, even though hes armed to deal with said 'Resistance'.

I am totally in favor of a new tactic (to offensively and quite clearly tackle a character down) - but not in favor of being always able to grab without demanding them to get down.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
