### ISSUE TITLE
[Feature Request to resolve Issue] E should not disengage ladder while hovering over interactive item

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1369]
As it stands right now, while you're climbing a ladder and press E under any given circumstance, you immediately get off the ladder.

It would be nice if E didn't dismount you from the ladder if your mouse is hovering over an interactive item such as a button or a container. The way it is currently usually leads me to fall off a ladder while trying to get something from a container or press something in a hurry. Essentially, this renders things un-interactable while on a ladder.

For example, if you are trying to get a fuel rod in the typhon in a rush, the fuel cabinet is up a floor. It's really a huge time waste to climb all the way up the ladder, press e to dismount above the platform, then press e to open the container, so naturally while i'm still on the ladder and can reach the fuel cabinet, to save time, I just press E on the ladder. This causes me to fall back down out of reach distance to the fuel cabinet, and is a huge inconvenience and time sink.

**Comment by NilanthAnimosus** [comment]
I do think it'd be very difficult to say, grab an item out of a locker when your halfway between decks on a ladder.

I also think it would get annoying if you have a large concentration of objects near a ladder, and was trying E to get off - to find you were unable to (Does A/D detach us? Don't recall I've actually been using E myself, I figure it would though).

I do however feel some fixable items are hard or strange to reach, that actually are close to the ladder (One of the vanilla submarines had a design like this I think? Or it was a custom one). the AI is also prone to climbing up ladders, starting a repair without reaching the next hull/room and then falling down upon starting, to repeat the process a good 3-5 times until fixed.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
