### ISSUE TITLE
Identity system

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#137]
Extending on the ID card slot idea (https://github.com/Regalis11/Barotrauma/issues/135), people should be able to wear someone else's ID card to steal their identity if they are wearing a mask or suit to cover their face.

This would change their floating name to that of who they're impersonating, or completely blank if they're not wearing any ID card. Speaking would still use their real name, however.

Later on when actual account system is implemented (forum accounts used for in-game?) players should be able to change their "RP names" on a per-server basis or maybe have servers optionally generate random names for people to play with.

This can be countered by attentive players who remember the victim having a different face/gender (if wearing an oxy mask) OR by asking the player to speak or take off their mask/diving suit to confirm no shenanigans are in place.

Overall, this enhances the game's element of paranoia and spooky traitor shenanigans as allowing them to impersonate other people gives them more leeway in stealthing around and not getting caught, which means getting away with assassinations in more creative ways.

However, a thing to watch out for is the griefer potential as well. Hosts should definitely have a "whois" command which reveals the identity of the target, or identities of everyone if target isn't specified. Server logs should also log when someone equips or removes an ID card from the slot.

**Comment by NilanthAnimosus** [comment]
I like whats in the above, but throwing in parts of what I suggested in another issue related to this.

Pulling some thoughts I had for the above from #64 : 

"Instead of writing a new issue for the same feature request, it would be nice if the ID Card was in the format style and expanded upon where:

The name of the original owner and the Name of the job is on the ID Cards name.

Have the name of the character overridden by the ID Card if they are wearing items that cover the face (A tag perhaps in the XMLs for facial coverage?) such as Unknown (ID Name).

Later one could add a headset-like voice changer to mask the voice in the text chat which works with this concept, I think this would better expand on improving the ID Card itself. This is sort of how SS13 handles things and would work here too for in-game impersonation purposes."

**Comment by Crystalwarrior** [comment]
https://github.com/Regalis11/Barotrauma/pull/160 mostly implements this
