### ISSUE TITLE
Electrical discharge coils are ineffective

### ISSUE THREAD

**Issue by Weebyxanide** [Regalis11/Barotrauma#1377]
A few stock submarines rely upon electrical discharge coils to cover their baffles. However, these coils are almost completely useless for most purposes; 8 stun, 10 burn. Killing even a crawler this way requires enormous amounts of power and the minor stun damage it deals is hardly worth draining the supercapacitors. This is even worse against armoured targets; testing this on a diving suited human resulted in 4 burn damage to one arm and nothing else.

I"m reasonably sure that their stats at present are just a placeholder, but I felt it wouldn't hurt to mention this. The Teslas are just too weak to have any impact on combat, even if they're meant as a diversion device rather than a weapon, and their power consumption means they may well be *worse* than nothing.

**Comment by Regalis11** [comment]
Actually the reason why we added the coils was to have a way to get monsters off the hull by stunning them. We used to have lots of problems dealing with crawlers attaching themselves to the hull, often in spots where they couldn't be reached by any of the turrets. I'm not sure how much of a problem it currently is after all of the monster AI changes.

But I do agree that the coils need some kind of an overhaul: it's not clear at all what their purpose is, they're only useful in very niche cases, and there's so little feedback when you use them that it's hard to even see what pressing the discharge button does.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
