### ISSUE TITLE
Thoughts about the crew roster

### ISSUE THREAD

**Issue by Weebyxanide** [Regalis11/Barotrauma#1378]
The crew list in-game at present gives a great deal more situational awareness, and I can see why it's here, but it has some problems from a design standpoint. As it is now, it provides 100% accurate data on who's alive, which makes a traitor's job somewhat difficult (disguises are effectively pointless if you know Pavel just died and see him walking around), and it removes the tension of losing contact with a dive team. Or losing contact with the ship while in the ruins.

Also, they disappear from the player list in the tab menu on death, which prevents votekicking them. That's a bit of an annoyance.

I can think of three potential solutions to this. None of these are perfect by any means, of course:
* Require someone to find the body before removing them from the list, and add a "report body" button. This incentivises hiding the evidence.
* Carriable biometric sensors that immediately report a flatline. These devices should be expensive, with false positives and negatives, and not all that reliable in one way or another to keep them from eclipsing the Mk.I Eyeball. Possibly they could require a machine of some sort to work, so a wily traitor could still work around these.
* One could simply not remove someone from the list under any circumstances. Imperfect solution and a regression in functionality to legacy, but it won't immediately out a traitor who's otherwise done everything right.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
