### ISSUE TITLE
[Feature Request] Sonar Beacon has sonar label of player holding it

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1379]
It would be nice if the sonar label in the sonar interface, instead of saying "Sonar Beacon" said the player name if a player had it in their inventory, so that someone viewing a sonar monitor could keep track of who was holding what beacon.

**Comment by deadmomo69** [comment]
Even better: Allow people to name the sonar beacons aswell, so if you leave the beacon somewhere in a point of interest, you can come back there if something happens.

**Comment by NilanthAnimosus** [comment]
A GUI to name and select settings of the beacon would be nice.

IE. emit half the range for half or a third the aggression radius for the device, ability to turn it on and off and such.

It could be expanded to have a maximum radius and/or a transmission power to effect its max range or AI Target (Yea, beacons have an AI target and make fish target you).

Not only does it have an AI Target, it has an insane AI Target that might as well be map-range and they will shread you for it:
```xml
  <LightComponent LightColor="0.0,1.0,0.0,1.0" range="50" powerconsumption="10" blinkfrequency="2" IsOn="true">
    <AiTarget soundrange="20000" sonarlabel="Sonar Beacon" />
    <StatusEffect type="OnActive" target="Contained" Condition="-0.5" />
  </LightComponent>
```

I feel 20000 range is insanely excessive personally, for what is thought to be a tool to aid by tracking position of divers, and a -0.5 condition rate is a pretty fast decline of its power level leaving it almost no operational time at all for that purpose too while attracting fish insanely. Its better off dropped in the ocean somewhere if i'm honest. That or having one version for divers and after as intense decoy device.

a 500-2000 range is still pretty dangerous, 3000 even, 20000 is huge.

This is why I think variable label range and variable strength of the signal would be nice somehow, or at least granting us the power to turn off such a suicidal device without taking its battery out (It has buttons on it even)

**Comment by Regalis11** [comment]
@NilanthAnimosus The reason why the range is so large because the AITarget is what the sonar is detecting - if it was something like 500, it would mean you have to be basically standing next to the transducer or the nav terminal for it to pick up the signal.

But in any case, I do agree that we need to add some controls to the beacons (a label, a way to turn it off and maybe a range control).

**Comment by NilanthAnimosus** [comment]
That makes more sense in an unfortunate sort of way given a submarine doesn't exactly have a 20000 range target for its sonar, but you can see the submarine from anywhere too, which obviously uses different behavior.

I think the AI Target should be separate (or use a different name and a second target) so the fish have a different range to it at least, submarines and outposts emit a large-range traceable signal, but the sonar beacon is the one that gets the huge target.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
