### ISSUE TITLE
[Crazy Feature Request] Killed crew in PVP missions respawn as weak monsters for winning team's return trip

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1380]
This is a bit of a crazy idea, but what if the losing team in PvP rounds (renegade or coalition) respawned as monsters (weak ones) as one last act beyond the grave to try and screw over the victorious team during their return trip?
Monsters are already more or less controllable (some small modifications would have to be made to make them more... playable?) but as long as people are respawning as something relatively weak, it would at least give the losing team something to do instead of wait for the winning crew to get back to home base.

Just a thought.

**Comment by AbominationBanisher** [comment]
I don't see this happening, sorry. 

I vehemently dislike this idea, because as you can see now, controlling monsters right now is a nightmare. They're super slow, you never know where the sub is (the map is fucking hugeeeeeeee), and you'll die in three gunshots from the railgun (especially as a weak monster).

**Comment by hubismal** [comment]
> controlling monsters is a nightmare
monster controlling as it exists now is only an issue because the camera doesn't zoom properly
> slow
the powerful ones are slow, crawlers and husks and so on are pretty fast in water.
> you never know where the sub is
this could easily be changed so that monsters see the sub indicator (that's normally present in spectator mode) if the sub is making noise.
> you'll die in three gunshots from the railgun
the idea is that you hypothetically respawn multiple times as monsters, maybe in waves, not just once.
> tedious boring unfun experience
the idea is that it's more fun than waiting for the already-victorious crew to make it all the way back to base, which is usually 3-8 minutes of literally nothing but watching them. This is a better-than-nothing alternative that at least provides interactivity.

The idea has some potential hiccups but none of them are ones you mentioned.
making monsters controllable and actually playable is a pretty big task (balancing, abilities, etc), but Regalis said at some point that he wants the game to have a monster controlling mode eventually anyway; This is more of an idea for the team than it is a fully fleshed and thought out feature request.

**Comment by AbominationBanisher** [comment]
> > controlling monsters is a nightmare
> 
> monster controlling as it exists now is only an issue because the camera doesn't zoom properly
> 
> > slow
> 
> the powerful ones are slow, crawlers and husks and so on are pretty fast in water.
> 
> > you never know where the sub is
> 
> this could easily be changed so that monsters see the sub indicator (that's normally present in spectator mode) if the sub is making noise.
> 
> > you'll die in three gunshots from the railgun
> 
> the idea is that you hypothetically respawn multiple times as monsters, maybe in waves, not just once.
> 
> > tedious boring unfun experience
> 
> the idea is that it's more fun than waiting for the already-victorious crew to make it all the way back to base, which is usually 3-8 minutes of literally nothing but watching them. This is a better-than-nothing alternative that at least provides interactivity.
> 
> The idea has some potential hiccups but none of them are ones you mentioned.
> making monsters controllable and actually playable is a pretty big task (balancing, abilities, etc), but Regalis said at some point that he wants the game to have a monster controlling mode eventually anyway; This is more of an idea for the team than it is a fully fleshed and thought out feature request.

You're overestimating the speed of the weaker monsters and underestimating the size of the map. Ever tried using the water scooter to navigate the entire map?

**Comment by NilanthAnimosus** [comment]
because monster control is fleshed out does not make the initial suggestion a bad idea but instead sheds light to where creatures can be expanded upon somehow. such as giving them their own GUI specific to monsters and fleshing them out for player usage.

However, I am one for fish vs fish, as well as submarine vs fish gameplay, I do not think it would be great for the losing team to have to deal with very smart player fish eternally after having beaten them...players are more likely to get aggrivated if anything.

Instead, dead players could become a fish, but in a small almost separate area of the map that either cannot or is extremely unlikely to reach the main submarine, then pit it out for fun against other dead players in that round, as more a passtime than a lets go mess up the winning crew device.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
