### ISSUE TITLE
[Tester's Version] [Feature Request] Leg Shackles

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1386]
So this is purely an item for the security guards. It slows down the person donning such shackles so that not only can they not run, but their regular walking speed is a third of what it used to be. And they also won't be able to climb stairs and the such, as well as ladders. We have always found that one traitor that kept on running away from the brig no matter how many times he got stunned, right?

**Comment by NilanthAnimosus** [comment]
If this is wanted as an item, i'd say implement it into the already existing cuffs. given how wearable's work (Hands slot, over body slot etc) it would have to end up taking up a different slot - such as outer body clothing to be separate (No diving suits, no armour etc). or be prisoner clothing with the cuffs on legs already attached.

so it makes sense to combine it into the handcuffs, which already are for humanoids with hands - It would be presumed they had legs too. sort of like upgraded handcuffs. a modder can create such things mind you.

I always figured prisoner clothing (not the cuffs) should get a speed malice. anyways I think 1/3rd walk speed without run is too excessive. I suggest making it more like they can still run, but all speed is at 40% to 50%, there is no reason why they cant sort of half-hop-joggingly run in cuffs and chains, but their no longer doing laps around the security this way.

I would also think this should have its own animations, because the legs would be restricted from this, for this to look correct in any particular way. one could just give a speed reduction to those wearing handcuffs though.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
