### ISSUE TITLE
[Feature request] Allow moving the directional sonar cone by mouse

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#1387]
It would be great to be able to control the directional sonar by holding, say, the right mouse button over the sonar screen and dragging it, while controlling the sub with left button as usual. I feel that at the moment directional sonar is a bit annoying to use: it feels unintuitive to control a tool, which is supposed to rotate 360 degrees with a simple left-to-right slider, that is also limited to one full circle, often forcing you to scroll all the way back to the desired cone position, where it would be more reasonable to move it a few degrees further to the front. I think this addition would dispense with the artificial difficulties of using this tool, while maintaining the intended suspense of having limited vision.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
