### ISSUE TITLE
[Feature Request] Sub editor: Indicators for how bad your submarine might lag for the average player

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1392]
It would be nice if the green numbers in the sub editor (indicating the amount of items/hulls in the ship) turned different colors to indicate the stress a sub might put on a player's computer. This would be nice just because in legacy there were a lot of people who made _ridiculously_ heavy subs that would lag the game to death for anyone who didn't have a NASA computer.
How I see this working:

If the amount of items were enough to noticably lag a computer with the specs of the REQUIRED SPECS section of the Steam page, the numbers should all turn yellow. (I assume this could be measured through a certain cpu/memory usage, not just a fixed value of items/hulls as the optimization of this game could get better/worse)

If the amount of items were enough to noticably lag a computer with the specs of the RECCOMENDED SPECS section of the Steam page, the numbers should all turn yellow, and a warning when saving your sub should appear notifying the player that their sub is very laggy.

Just an idea, but I think it would really, really help the submarine scene overall and make the game more accessible for (from what i've seen) the specs of the average baro player.

**Comment by Regalis11** [comment]
They do actually turn yellow/red, although atm it's only based on the number of entities. I think we could make it a little more accurate by giving some the items some kind of "performance cost estimations", although I don't think there's a way to calculate an exact estimation: not only is it extremely difficult to, for example, estimate the cost of some complex circuit in advance, the performance can vary on different hardware even if it technically matches the required specs.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
