### ISSUE TITLE
[Feature Request] Mark workshop items as such and disallow publishing to prevent plaigarism

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1395]
The title isn't exactly accurate, because i'm trying to keep it short. It's not a bar all editing system, here, take a read:

A few really nice polishes to the workshop system would be to store workshop items in a different location from the basic Submarines folder, and mark them ingame with a green name or something to indicate they're from the workshop, not your own, so that your subs with the same name wouldn't overlap with the workshop version.

This might sound complicated, but when you publish a sub to the workshop, you're unable to download it because an identically named one exists in the same folder. It is very convenient to be able to download the sub from the shop for various reasons such as verifying everything is working right, or just having an older workshop version while you maybe work on a newer version of the sub with the same subfile name.

Additionally, you shouldn't be able to overwrite workshop subs (you can make copies though if you Save As something else) and you shouldn't be able to just upload a workshop sub marked as downloaded from workshop. These changes would help combat people downloading subs and publishing them to workshop without alteration. We don't want 500 iron gears on the workshop.

The workshop marker could also apply to other custom items such as Missions or Mods or Characters. Just a general plaigarism preventer to prevent what happened with the crikentide of subs lying around the workshop from happening again.

**Comment by hubismal** [comment]
I also know that workshop isn't a high priority feature; This is just for the future, presumably around the time actual content package deletion becomes a thing.

**Comment by hubismal** [comment]
To add on to this, I think this is necessary if downloading missing content packages on the spot from the server list is ever going to be a thing.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
