### ISSUE TITLE
[Mac] [Bug] Game still doesn't launch from Steam, probably due to launch script error or mono missing

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1411]
Probably a good one to fix before the Mac testers arrive: The mac version of the game doesn't run when double clicking play from steam. I think it has something to do with the script using mono64 or something (I got an error when trying to run it on mac). This was tested yesterday so unless there was a patch for mac in that short amount of time this should be relevant.
This might have to do with what's installed on the base machine (I don't think mono is manually installed on my Mac), but either way a new user won't be able to run it.

**Comment by hubismal** [comment]
I should also mention my mac is like a 2012-13(?) Mac (I don't buy all the latest apple products anymore). It runs every single other steam game fine, but it would be helpful if the two other Mac Gamers remaining on this section of the solar system verified the non-functionality

**Comment by CommanderMark** [comment]
> but it would be helpful if the two other Mac Gamers remaining on this section of the solar system verified the non-functionality
You rang?

So yeah the game doesn't launch directly inside of Steam on macOS. Navigating over to the game's files and running the launch script manually does seem to work though.

**Comment by Regalis11** [comment]
Thanks for the notice! I think launch settings were wrong on Steamwork's side, could you try if it works now?
![asefrew](https://user-images.githubusercontent.com/14351070/55757815-ae0c2280-5a5d-11e9-8479-31f75c190e58.png)

**Comment by hubismal** [comment]
>could you try if it works now?

Was I supposed to recieve some kind of update? Nothing is different for me.
Trying to run it outside of steam prints:

>Support/Steam/steamapps/common/Barotrauma/barotrauma_launch.command: line 3: mono64: command not found

then logout... etc etc, [Process completed]

**Comment by CommanderMark** [comment]
It still doesn't work for me, but in addition to that my build is still on v0.8.9.6. Is the Mac repo up to date?

**Comment by hubismal** [comment]
My build is still way behind too, it's on 0.8.9.7. I just think virtually nobody has been pushing updated Mac builds for steam.

CommanderMark is able to run his because he has mono64 installed. I don't. 
I don't think many players are going to come in with mono64 automatically installed (especially the casual spectrum of Mac players), so if there's a way to automatically install mono, that should probably be configured (assuming it's straightforward).

I'm also going to uninstall mono on linux and see if the game still runs.

**Comment by Regalis11** [comment]
Yeah, unfortunately at the moment you need to install mono yourself when playing the game on Mac or Linux. Steam automatically installs the dependencies required on Windows, but for some reason they don't support this on Mac/Linux (nor install scripts), so we're going to have to go with an alternative solution. Possibly these: [package_DesktopGL_OSX.md](https://github.com/mrhelmut/MonoGame/blob/eb22a324860c353391f7ae7688bee08940e2b3a6/Documentation/package_DesktopGL_OSX.md) and [package_DesktopGL_Linux.md](https://github.com/mrhelmut/MonoGame/blob/eb22a324860c353391f7ae7688bee08940e2b3a6/Documentation/package_DesktopGL_Linux.md).

And sorry, no, we haven't always been keeping the Mac version up-to-date on Steam because there haven't been any active Mac players (before you tried it now, the last time someone played the Mac version was in february).
