### ISSUE TITLE
Crash to Desktop Upon Launch

### ISSUE THREAD

**Issue by Just-Jamess** [Regalis11/Barotrauma#1424]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

Essentially, I downloaded and enabled Barotrauma Extended from the workshop to test out the items it adds. After this, I disabled it to return to working on a new submarine of mine. I relaunched the game just in case and was met by a crash to desktop before I load in. Yes, I verified my cache, and I checked to see if BTE was in my workshop files- It wasn't.

**Steps To Reproduce**
Download a mod that adds assets (BTE I suppose), enable the mod, and then disable and relaunch.

**Version**
Windows 10. All I can say is the latest version of 4/17/2019. I would get a proper version, but y'know. I can't launch the game.

**Comment by hubismal** [comment]
Did you get a crashlog? I think I might've seen this issue myself.

**Comment by Just-Jamess** [comment]
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/3092534/crashreport.6.log)
@hubismal

**Comment by Regalis11** [comment]
The issue seems to be that disabling BTE doesn't automatically enable the vanilla content package, causing you to have no content packages selected, which leads to all sorts of error (and in this case the game crashes due to missing text files).

Will be fixed for the next patch, but for the time being you should be able to fix it by removing "config_player.xml" inside the game folder, or if you want to keep your existing settings, you can add "<contentpackage path="Data/ContentPackages/Vanilla 0.9.xml" />" to the file manually.

**Comment by Regalis11** [comment]
Fixed in ea54fa2

**Comment by PicolasCage** [comment]
reinstall the game to be able to access it again
