### ISSUE TITLE
[Feature Request] Documentation for ships: Papers, Clipboards, Etc

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1425]
One issue with creating custom subs is that many ships lack the ability to describe a feature in depth outside of the workshop descriptions or in game sub descriptions. Essentially, subs lack a way to add "comments" the way you would in programming to explain how things work. 
I think Barotrauma Extended had a very good idea when it came to having pieces of paper in game with information on them, like your roles, objectives, etc. 
I think a "document" item would be extremely helpful, especially one that allowed you to edit the contents of the document in the editor, maybe with the option to restrict it ingame. Even something as simple as plaintext documents would be helpful, but if you really wanted to help worldbuilding you could implement minor markup features too.
Traitors could also get special renegade documents containing essential information or intel. The possibilities of documents to be utilized in missions have only been partially showcased in BTE.
I feel like customization is a key strength of Barotrauma and that having documents would really help this.
Clipboards, Bulletin Boards etc would not be terribly difficult and an added bonus as well. Maybe some way to view documents directly from a bulletin board?

**Comment by BillCombs** [comment]
Perhaps there could also be some that can be edited mid game? Like notes that can be secretly shared between players, or documents used to log lost crewmembers, equipment, or to memorize events that happened during the campaign. Could be pretty good for roleplay.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
