### ISSUE TITLE
Use Steam Cloud to sync config_player.xml.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#1427]

**Comment by hubismal** [comment]
why would you want to sync your config file over cloud? Wouldn't the multiple computers you use all have different graphics settings based on their respective hardware?
I'm for syncing the player between computers though.

**Comment by CommanderMark** [comment]
In that case maybe the control scheme should be moved to a separate file that'll be synced.

**Comment by ZealanL** [comment]
I don't see much of a benefit to doing this. If re-installing barotrauma and having to reconfigure is difficult, just save a copy of the config somewhere else.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
