### ISSUE TITLE
[Feature Request] [Steamworks] Use Steam Achievement Progress Bars, counts, etc

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1428]
I assume facepunch.steamworks supports this because I think gmod utilizes a few of these, but it would be nice if we got those little progres bars and counters underneath achievements that indicated how much of the achievement you had completed. For example, that f*cking Naval Architecht (spend 24 hours in the sub editor achievement and the bane of my life) could really use a float bar indicating how many hours have been spent out of 24 in the sub editor.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
