### ISSUE TITLE
Tethers for subs

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#143]
Make tethers a thing so divers can examine the sub's status without being potentially left behind.

Rope component code already exists in code so I believe this shouldn't be too hard to implement.

Tethers themselves might be a thing you press use on to latch on to, They would require a diving suit to be worn to be usable. When you drop the diving suit or press E on the tether point you'll cut the rope and it could be used by someone else.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
