### ISSUE TITLE
[BUG] Errors and issues when using commands in Submarine Editor

### ISSUE THREAD

**Issue by ZealanL** [Regalis11/Barotrauma#1431]
When in character mode in the submarine editor, you can use commands to varying degrees of success. Using the `spawnitem` command will throw an error in the console, instead of spawning an item in your inventory. You are also able to spawn actual monsters and characters using the `spawn` command, which while not game-breaking does actually spawn a living monster. All commands can be executed, which can often mess up what you are doing or produce an unexpected result. I suggest that only a limited number of commands or no commands at all are allowed use in the submarine editor.

_For reproduction, enter the submarine editor, enter character mode, and try out some of these commands._

**Comment by hubismal** [comment]
The more direct equivelant of this is just going straight to game using `gamescreen`. While I'm not sure this qualifies as an actual report since mode-jumping through the console isn't technically a supported feature, a lot of things in game after jumping from the sub editor are just really f*cky: characters float off the ground when walking around, item errors exist (as mentioned above), shooting holes in the hull crashes the game, the water shader is frozen for some reason, etc.
I didn't report this because I used console commands to achieve these.

**Comment by Regalis11** [comment]
The spawnitem command can now be used (fixed in da3e325). Aside from that, I wouldn't consider this a bug: you can do a lot of stuff with the console commands that should never be possible otherwise, and if you do something unusual like spawning monsters inside the editor, there's a chance it may mess things up.
