### ISSUE TITLE
[Feature Request] Wiring option to shut off/toggle air vents

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1432]
This request is just what the feature sounds like. It would be nice if we could wire a "toggle" node on vents to either close them or shut them. this could provide more air to other vents or intentionally suffocate fires/hostiles.
Some kind of integration with sonar monitors would be nice too but that's a little ambitious. We do have oxygen monitors at the moment though, and they don't serve much purpose other than to all turn red at once.

**Comment by ZealanL** [comment]
Agreed. Having `toggle` and `state_out` would be quite useful, especially for the large amount of fires I experience in game. At the moment, vents lack any real functional value and are just a visual indicator that "oxygen spawns here".

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
