### ISSUE TITLE
[Feature Request] Tutorial should teach Sec Officers how to police characters (handcuff, take stuff)

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1437]
Suggested by redkite in the discord.
The tutorial should probably teach a player how to stun a player, remove their weapons when unconcious, and handcuff them. handcuffing is one of the features that really confused me in the early days of playing the new steam build, especially since I normally use the hotkeys to equip things instead of the little green buttons above the inventory slots.
Maybe an engineer or something could be trying to attack you with a wrench (or whatever the weakest weapon is) and you have to stun him with a baton, take the wrench, and cuff him.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
