### ISSUE TITLE
[Feature Request] [Sub editor] Filter items shown in sub editor viewport

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1439]
It would be nice if we could specify to view only or highlight all the items entered in some kind of search field. For example, entering "wificomponent" would highlight all the wifi components on the screen.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
