### ISSUE TITLE
[Bug?] [Feature Request?] Deleting an item in a sub editor should delete connected wires as well

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1440]
Almost self explanatory, but considering there is no way to re-wire a leftover wire segment, it would be much more convenient than having to dewire the wire manually so you don't get left over with an undeletable floating wire.

**Comment by hubismal** [comment]
To clarify, I understand wires tend to be automatically deleted once as the second thing they are connected to is deleted. But under some conditions they seem to stay around even after the second item is deleted, and as long as there's no way to reconnect that wire to something there's no point to them sticking around anyway.

**Comment by BillCombs** [comment]
When reworking complex systems, wire leftovers often help me remember where the connection is supposed to go. It would suck to have to memorize each connection before deleting items.

Perhaps the game should ask you if you want to delete leftovers. Or there could be a checkmark option, so the wires would get deleted automatically without asking, or would leave the floating wires, if you need that.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
