### ISSUE TITLE
[Feature Request] [Code] Be able to very obviously break out of handcuffs over time, guards have to check on them

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1448]
Suggested by TheLaughingDead in the discord. 
This is a two birds with one stone suggestion, in that it both makes handcuffs not a stand-around-for-the-rest-of-the-game ordeal, and also gives security officers a real job other than make up excuses to arrest people (also makes arresting people an actual undertaking rather than cuffing and forgetting about them).
Players should be able to somehow wear down the cheap, coalition manufactured handcuffs over 3-4 minutes with a timer attatched, maybe by aiming (right click) and using (left click) while handcuffs are on, making it very obvious they are breaking out to any bystander. If they are interrupted during this period, the timer will reset and they will have to "use" the handcuffs for the whole 3-4 minutes all over again. Any handcuffed people will have to be regularly checked on by the guards, who can force-interrupt them by grabbing them with G (maybe some kind of special security officer perk/skill?). Not only does being able to break out make handcuffed prisoners not just something you can forget about, the forcing of guards to actually interact with the prisoners means that they may be able to escape if doors around them aren't closely monitored. The same gameplay changes apply to evildoers/disguisers who may be trying to keep a kidnapped cuffed: They will have to regularly check on the kidnapped to make sure they aren't escaping somehow and ruining their plan.
All in all, this will make the game more fun for security guards, the handcuffed, and evildoers, and shouldn't be terribly hard to implement (I think). Everyone on discord liked TheLaughingDead's idea.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
