### ISSUE TITLE
[0.8.10.0] A few server errors.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1452]
**Description**
Recently decided to start a server and play with friends, but there were a few problems.
1. Players could not connect to the game because of the "seed error". Play was with seed "NEVOL4SV".
2. Once the submarine appeared inside the Outpost.
3. You could not change the job type through the console. There was a sandbox.
4. When given a task "Salvage", then in the console there were many errors with regards to the ruins.

**Logs**
1. [ЗБТ Русский паблик._2019-05-04_1657.txt](https://github.com/Regalis11/Barotrauma/files/3147746/_2019-05-04_1657.txt)
2. [ЗБТ Русский паблик._2019-05-04_1630.txt](https://github.com/Regalis11/Barotrauma/files/3147743/_2019-05-04_1630.txt)

**Version**
Windows 10x64. 0.8.10.0.

**Comment by Regalis11** [comment]
1. The server log seems to imply that the other players are playing a non-Steam build (I'm guessing from IGG-games?). The seed error can happen more frequently when the players are using different builds (see #848). And the build on IGG is actually a debug build which differs from the version that's available on Steam, so these kind of errors are to be expected if your friends are indeed using a non-Steam version.

2. This has been fixed in the dev branch, will be fixed in the next patch!

3. Could you give some more details on this? Which command were you trying to use?

4. Do you by any chance remember what the errors said? Something along the lines of "could not find a suitable position of interest"?

**Comment by Nevol2110** [comment]
1. Identical version of the game. When trying to start a round on "BT Public", a similar error appears.
P.S. Now server why something not works, and those, with whom I played, sleep. Later I will attach a screenshot.
3. mission Salvage 
4. ![image](https://user-images.githubusercontent.com/33912761/57263967-127cca80-707a-11e9-8301-3dec8f34385d.png)

**Comment by Nevol2110** [comment]
1. ![Uploading image.png…]()
I also noticed that the submarines from the workshop can't be downloaded by others. Is this about the unlicensed version?

**Comment by Regalis11** [comment]
This is most likely due to the "unlicensed version", especially if it's a custom build. What exactly is this version, did you build it yourself or get it from somewhere outside Steam?

**Comment by Rokvach** [comment]
This shouldn't be an issue anymore, closing.
