### ISSUE TITLE
[Steam Version] Game window offset to the bottom-right

### ISSUE THREAD

**Issue by Splaxiom** [Regalis11/Barotrauma#1483]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When launched through Steam, the window is offset to the right and down, making the game unplayable as part of the window is now offscreen

**Steps To Reproduce**
Can't reproduce it, seems to be random
For some reference, it happened twice in 10 launches

**Version**
This happened under Steam version 0.9.0.1 (development opt-in beta), which should be the latest version

**Additional information**
Native resolution is 1366x768, the game screen is offset 275x104 pixels to the bottom right. This happened in borderless windowed mode, could not test if changing display mode would fix it (mostly because the *apply* button was located off-screen)
Using Windows 10, here's a screenshot of the bug:
![offset](https://user-images.githubusercontent.com/47252286/57988870-74362f00-7a93-11e9-805d-af1849a19ba3.png)

**Comment by hubismal** [comment]
This is because the resolution is incorrectly set to be larger than the screen; Somehow you got a config file with an incorrect predetermined resolution. The game is supposed to automatically fix this, apparently, but for now if you go into config_player.xml you should be able to change the resolution manually.

**Comment by Rokvach** [comment]
This is fixed with the new SDL2 window implementation and there hasn't been any new complaints about the issue. Closing.
