### ISSUE TITLE
Crawler issue

### ISSUE THREAD

**Issue by fabevil** [Regalis11/Barotrauma#1484]
I have another bug report on the line here, this might be a little harder to patch out though. This is based off of an experience that happened a few weeks ago. I was playing With the bots (lonely I know) when I see a Crawler Head pop up from one of my Submarine hulls. I decide to Damage it with a welder and it straight up teleported inside the Sub making me jump. I have unfortunately no video evidence or screenshots.

**Comment by Regalis11** [comment]
Do you remember which sub it was? There was a problem with the external walls in Venture that has been since fixed, could be related

**Comment by fabevil** [comment]
Oh, I think it was the Venture, is it that sub with the recommended crew of 7-12 and with the shuttle? If so, yes

**Comment by fabevil** [comment]
Wait. It's not the Venture, It was Remora!

**Comment by ZealanL** [comment]
Certain monsters that are very horizontal, especially crawlers, can poke through things and even get stuck. This is because when they turn around their character is flipped, which often causes parts to become stuck that weren't before. I'm guessing this could be fixed quite easily with some collision logic, but I'm not sure.
