### ISSUE TITLE
[Feature Request] [Design] [Major Overhaul] Simple Submarine-tagging Upgrade system

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1487]
This is most likely a duplicate issue because it's not a new idea, but I can't find anything related to this.
A way to implement a much-discussed upgrade system might be to create a fully decked out sub, but mark certain items in the sub with the tags "upgrade1" or "upgrade2". These items won't be available when starting a campaign, but upon purchasing the "first upgrade" or whatever at the shop for (X) amount of money (specifiable in the editor), the items tagged "upgrade1" will be made available, effectively creating an upgrade system.
Of course this doesn't mean this is exactly how it would work. If you wanted to implement branches or forced permanent upgrade branch choices between something like having a railgun or a coilgun, i'm sure you could find a text-tagging solution for that, too.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
