### ISSUE TITLE
[Docking to station]

### ISSUE THREAD

**Issue by PicolasCage** [Regalis11/Barotrauma#1488]
One of the biggest issues I have with docking is that it's simply too hard. It's like having 5/20 vision and trying to pull a thread through the eye of a needle, simply frustrating. Last game, I was trying to dock for a good fifteen minutes. I just don't see this tediousness as a key or core part of the game which creates any sort of fun. So I just that the dock button is a bit more automated, and when you press dock in a 10m radius from the ship, the docking button simply auto adjusts the position of the submarine to the right place and docks itself.

**Comment by rico6822** [comment]
Try autopilot next time.

**Comment by rico6822** [comment]
Try autopilot next time at the end of the mission.

**Comment by PicolasCage** [comment]
> Try autopilot next time at the end of the mission.

I DID try it. Autopilot gets stuck on the side of the outpost.

**Comment by thegrb93** [comment]
I don't have any problems with it. Try more practice.

**Comment by rico6822** [comment]
> I don't have any problems with it. Try more practice.

I advice Picolas to use zooming in.

**Comment by rico6822** [comment]
> > Try autopilot next time at the end of the mission.
> 
> I DID try it. Autopilot gets stuck on the side of the outpost.

Ok, use zoom in.

**Comment by Regalis11** [comment]
I think you might be misunderstanding some part of the docking system, it's not really that difficult when you use "maintain position" and slightly nudge the position to get the docking ports to align. I've watched streamers and first-time players manage to do it on the first try in less than 30 seconds.

But in any case, players not being able to figure it out means we've done something wrong. In v0.9.0.0 the docking system has been overhauled to hopefully communicate it more clearly to the players what the easiest way to dock is by automatically enabling "maintain position" and allowing the position to be nudged with special buttons.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
