### ISSUE TITLE
Reimplement Small Monitor Back Into Barotrauma- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1493]
If you don't remember what small monitor was it was an unused feature in Barotrauma just like heat absorber that could still be added by using submarine editor or console commands into the game.

Purchasing cameras in campaign mode is mostly useless since periscopes are already being occupied by railguns. I would like small monitors to only have `position_out` output giving player the ability to create custom surveillance system.

Potential bug I predict:
Wiring small monitors to railguns would still allow the player to rotate railguns but firing from them would be impossible this way.

Edit:
We could make small monitor have multiple cameras wired to it and every time player pressed left mouse button the camera is changed. It may be a little difficult to do so. I personally think this should be considered a optional objective (I mean multiple cams to 1 monitor).

**Comment by rico6822** [comment]
I would use a thing like it to install a camera in the airlock showing me up if thermal artifact haven't went out of control.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
