### ISSUE TITLE
Clown Ensemble - Squeak on Damage

### ISSUE THREAD

**Issue by ughaz** [Regalis11/Barotrauma#1498]
Alright, basically upon taking damage (Or certain types of damage, at least) while having the Clown Ensemble equipped (Just the clothing, not necessarily the mask or anything else) some sort of squeak or honk would play alongside damage sound files

Like honestly just imagine a clown being torn apart and you hear the sounds of bone gnashing and feeble honks

Hilarious if you ask me

**Comment by rico6822** [comment]
Potential ear rape.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
