### ISSUE TITLE
Lots of desyncs

### ISSUE THREAD

**Issue by v5844** [Regalis11/Barotrauma#1522]
**Description**
I sometimes have 1/3 of the players get kicked because of desync at round start. It also happens randomly mid-game. When I was playing on my server with a friend, both of us got desynced and our game crashed. Here's the log:
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/3262453/crashreport.log)

**Steps To Reproduce**
No clue

**Version**
Linux, 0.9.0.4, Mono 5.18

**Additional Information**
I never had problems like this on legacy.

**Comment by v5844** [comment]
The one with starting rounds might be somewhat related to #1518 I posted earlier. Desyncs happen when it didn't display the round end screen

**Comment by ZealanL** [comment]
Yeah, desyncs happen extremely frequently on my server and on others, often regardless of the server's performance. I'd suggest a sort of check-and-balance system where non-received entity events are somehow ignored or sent at a later time.

I personally experienced this a lot on legacy too, but it seems more prevalent on the Steam release.

~~Valve~~ Undertow please fix.

**Comment by Regalis11** [comment]
It seems that the wire issue that caused the crash was fixed in v0.9.2.0.

As for the desync, there have been several bugfixes to the networking issues in previous patches (and more to come in the next patch that's going to be out very soon), so there's a chance the issues you were facing have already been resolved. Since this report is about desync issues in general, it may be covered by the existing (or closed) reports, so I think it might make sense to close this and make separate issues for specific networking errors when they occur.

I also made a new issue report with some more information and details about one of the most common networking errors, which may be related to this: #1815
