### ISSUE TITLE
Server messages cannot display shashes ("/" or "\")

### ISSUE THREAD

**Issue by ZealanL** [Regalis11/Barotrauma#1524]
**Description**
Messages sent by the server in chat are unable to contain slashes. If they are present, they will be removed.

**Steps To Reproduce**
Use the `say` command from the server's console and add a slash to the message. It will not appear in-game or even in the console log.

**Version**
I tested this on Windows and Linux, but I doubt it is an OS problem.

**Comment by ZealanL** [comment]
Bump I guess? I would love to know why this is so I can fix it for my server.

**Comment by Regalis11** [comment]
This happens because the server uses TextManager.GetServerMessage to translate the text if it's something that can be translated. Slashes are used to separate text tags in the server messages, which causes them to be stripped from the message. I think we should just use the message as-is if it can't be translated.

**Comment by ZealanL** [comment]
I found that if you only use backslashes and use "\\\a" for every slash it will come out as a single slash. For now, I'll just modify the GetServerMessage function with a boolean parameter for text tags enabled.

**Comment by EdusFF** [comment]
Fixed and allowed the use of ' / ' in server messages. If the ' \ ' character is desired, use the ' \\ ' method

**Comment by Rokvach** [comment]
Tested, '/' is working correctly on server messages now. Closing.
