### ISSUE TITLE
Allow to break dead monsters into parts

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#1527]
Because the bodies hide items and characters behind them, hindering the gameplay.

So the suggestion is to be able to dispose the bodies by doing damage on them.

The parts should disappear/fade away in a few seconds after doing the damage. Could even do it so that you can destroy only a part of the body?

**Comment by CurePindal** [comment]
Oh yes, please!

**Comment by Nevol2110** [comment]
Can we add a limit on dead bodies? The time of their life? The possibility of destruction? It would be nice to see this in the game. You can also add enable or disable this feature on servers.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/e8c8ae4646d102d46f910469ed9553b865c0d91f

**Comment by Rokvach** [comment]
Tested, seems to have some issues cutting up humans and human sized creatures, noticed that diving knifes works better on cutting them up, might just be because plasma cutter doesn't have much of a indicator when it hits. 

Also noticed that when crouched plasma cutter doesn't tend to hit the creature/human, same can happen with the diving knifes on human sized targets, so need to walk around a bit to find the correct spot. 

@Regalis11

**Comment by Regalis11** [comment]
b91ba8e should remedy the hitting issue

**Comment by itchyOwl** [comment]
Works ok as far as I see it (after the fix that is). Also see 96f094b (private dev). Please check that I didn't break anything.
