### ISSUE TITLE
AI bots do not use ladder properly.

### ISSUE THREAD

**Issue by Lordawesome001** [Regalis11/Barotrauma#1531]
They just dont let go.

**Comment by OverwatchVoice** [comment]
To explain what Lordawsome meant, **This only happens when in the middle of the ladder, with two possible exits on each side.**

**Comment by Lordawesome001** [comment]
Its dismounting it in general. I have experimented  and they do it alot less with shorter ladders but still sometimes never get off doesn't matter where their at on the ladder itself.

**Comment by itchyOwl** [comment]
Might be because of this: #1589, but it's possible that this is a separate issue.

**Comment by exuvo** [comment]
Example where bots refuse to go left or top right. They just hang above the platform for the respective level. I have tried moving up the waypoint so that bots hang completely above the platform but they remain stuck.
![Barotrauma_2019-06-14_19-31-54](https://user-images.githubusercontent.com/2049338/59527311-857c2b00-8edb-11e9-9a7b-9dd82be7292c.png)

**Comment by Lordawesome001** [comment]
I was messing with waypoint for hours and this is what i came up with. Ai still gets stuck 40% of the time but less often than always. But always on starting level.
![ladder](https://user-images.githubusercontent.com/51491232/59537073-24445f80-8ebb-11e9-83ac-cc5075cb16bd.png)

**Comment by Rokvach** [comment]
There's been plenty of improvements regarding this so closing this one.
