### ISSUE TITLE
Job preferences not applied properly when there are a low amount of people

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1549]
Operating System:
Windows

Hardware:
windows 10, 32GB RAM, Nvidia GTX 1050

Message Body:
We cannot use our set own job preferences as 3 people, and we can only be captain and engineer and mechanic. My first preference was captain, my first friend's security and my other friend's mechanic. When we start the game, we are only a captain, a mechanic and an engineer. It feels like the job preferences don't work.

**Comment by EdusFF** [comment]
Not sure if a bug or by design, if the former then this needs to be fixed.

**Comment by Nevol2110** [comment]
If there are only three players, then regardless of your choice (if You are not the host) will be the captain, engineer and mechanic, as they are mandatory.

```xml
  <Job identifier="engineer"      
       minnumber="1" minkarma="0.5" initialcount="1"
```
Minnumber is responsible for this.

**Comment by hubismal** [comment]
This is almost certainly by design. The game is virtually unplayable without at least a captain, mechanic, and engineer.

**Comment by EdusFF** [comment]
Saw a stream where everyone managed to spawn as an assistant so there's something not exactly right with the logic

**Comment by Regalis11** [comment]
@EdusFF That's intentional as well, players are always allowed to pick Assistant (allowalways="true").

But in any case, this has been fixed for the next patch (not visible in this repo because the jobs.xml is in the Content folder which is excluded from here). Captains, mechanics and engineers are not as crucial anymore now that all characters can do any task regardless of their skills, so I think there's no reason to enforce having all of them in the crew.
