### ISSUE TITLE
Add a way to create character templates that can be reused

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1556]
Let us design a character by selecting skin color, body type, and facial features, then save them as a template. Then when starting a new game, we can choose a template for each of the default starter crew members to override their vanilla appearance and name. I feel that having a customized crew/character gives the player a stronger connection with their crew/character. After all, they did make them. This would also be cool for multiplayer and RP. It would make a multiplayer crew feel like an actual crew of people. And if you want to play a grizzled captain, or arrogant assistant, you can make one. (I like the crew banter by the way. Fills the silent moments.)

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
