### ISSUE TITLE
Balance: Toolbox slots overdone?!

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1592]
**Description**
Gamebalance, not a bug

With 12 slots the toolbox is insanely useful and with that somewhat overdone in relation to the default 10 tooolbelt slots a player has.
Wouldnt ~6 slots already be more than enough?

**Comment by CurePindal** [comment]
On top you can also stuff toolboxes into toolboxes, producing kinda unlimted inventory sizes.

Expected: Toolboxes dont fit into other tooboxes.

**Comment by BillCombs** [comment]
I could see it being helpful to engineers when making any complex electronic systems.
 An example of those systems would probably be something like an upgrade from a normal door to autodoor with a motion detector. To make the upgrade, you need 2 AND components, 1 NOT component, 1 delay component, 1 motion detector and 9 wires. That's 14 slots.
 With the toolbox you could make most average sized ones without walking back and forth to the lockers with components and wires.

 Even if not considering those situations(an average engineer would probably never bother to try making any complex system), i don't see the extra slots as too big of a problem, especially when there is so much new loot that you can get in the ruins or outside the submarine. Alien trinkets, weapons, monster loot, ores. Having a toolbox turns going back and forth outside or to the ruins into a single looting operation, making it take a lot less time, which is quite nice for players, who have to wait in the submarine, while others are having fun exploring alien ruins.

Also, the new health system makes you need to carry a lot more than just a couple of yellow syringes to be safe. Otherwise you will die if you are too far away from a doctor or med bay.

The bad side of having too many slots is the kind of players who like to take all of the items for themselves. Having so many slots would only encourage that behaviour, since even if you took a ton of items, you would not be getting punished with a complete lack of empty inventory space. Though i doubt that you could completely stop them by lowering the amount of slots by 6. It seems to be something that the players themselves will have to deal with.

**Comment by Regalis11** [comment]
I agree with BillCombs, closing
