### ISSUE TITLE
Deconstructor doesnt show deconstructed items

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1593]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deconstructing ores doesnt give any resource output in multiplayer. (no resources icons shown)
Noticed this a couple of times already.
Couldnt find a way to properly reproduce the issue yet.

**Steps To Reproduce**
- Deconstruct any kind of resouces in the constructor
- The output slots flash as if the resources got added, but no icon is shown. The output slots stay empty. (no other player intervened in the process, no other player was around)

Probably a synconisation issue!? The servers had 10+ players online and had some lag issues.

**Version**
0.9.0.4 - official and other public (probably dedicated) servers

**Comment by Regalis11** [comment]
Haven't seen this occur or gotten any reports about this since the fabricator syncing improvements in v0.9.1.0, so I'm assuming this is fixed.

**Comment by MarxSoul55** [comment]
I am experiencing this issue on v0.12.0.3, as described by @CurePindal. For reference, I'm playing singleplayer with a custom submarine. When I try to put in, for example, empty uranium/thorium fuel rods, I see the output slot flash, but no icons are shown i.e. the output slots remain empty. It's as if the inputs have simply disappeared without any trace.

**Comment by MarxSoul55** [comment]
UPDATE: I think I understand the issue. I looked at the custom submarine itself in the editor, and I noticed that there was a green line extending from it to a "secure steel cabinet". I'm fairly new to Barotrauma, so I wasn't initially sure what that green line meant, so I decided to experiment by putting something into the deconstructor and then checking the cabinet. As it turns out, the output actually went there! I'm not sure why the designer of the custom submarine I was using made that choice, but I'm nevertheless very happy that I can keep using it, since it's such a lovely sub.
