### ISSUE TITLE
AND component forgets DELAY component's output

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1601]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When attaching a Delay component to an And component, and the Delay component has a delay greater than around 6 or so seconds, the And component will switch it's output off, and then back on.

**Steps To Reproduce**
Attach Delay component and Constant signal to an And component, and use lights to monitor the output state of all component. The And component will switch off seemingly at random.

**Version**
Windows 10. Barotrauma 0.9.0.4

**Additional information**
I've included an Item Assembly of the circuit I was testing.
[NFG Delayed Open Door.zip](https://github.com/Regalis11/Barotrauma/files/3278514/NFG.Delayed.Open.Door.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d98301579fa8795f2c869b33e7d2d20c300dd43c (private repo). The issue was that the delay components only stored the signals received within the last 500 ticks, and ignored any additional ones it received. That meant the component would not work correctly if the delay was more than 8.3s (500 ticks / 60 ticks per second).

**Comment by Rokvach** [comment]
This doesn't appear to be fixed, here's a comment from one of our community tester.

"I followed the repo steps in the bug report and found the same issue to be present. I attached a memory component to an AND component, then to a Delay block and the same AND component, then the AND component to a light. On a 10 second delay, the light will "flicker" every 10 seconds. That is to say, it briefly turns off and then back on again, putting it through it's "light up" animation.
This does not happen if the Delay Component is set to a 1-second delay or a 6-second delay. This leads me to suspect that the original issue of the Delay Component not holding onto data for more than 500 ticks / ~8.3 seconds is somehow in effect."
- Malidictus

@Regalis11

**Comment by Regalis11** [comment]
I think https://github.com/Regalis11/Barotrauma-development/commit/876655e997f1c813aa09ea96849b5abc57b8d7ba should fix this. The issue was that the delay component left a 1-frame "gap" between the queued signals, causing it to output nothing every 10 seconds, which would toggle the AND component's state every 10 seconds.

**Comment by Regalis11** [comment]
Fixed in v0.9.4.0
