### ISSUE TITLE
Kicked from server: Missing oxygen tank

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1603]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing campaign on a dedicated server. 
Suddenly a couple of players (3-4 from 10 total) get killed and disconnected. 
In chat: "XXX has been kicked from server. Reason: Missing item Sauerstoff-tank (event ID 757, entity ID 1010) (Sauerstoff-tank is german for oxygen-tank or -bottle)
When they tried to reconnect they got instakicked again with the same message in the chat.
Players could rejoin once the mission was over and it stopped.

**Steps To Reproduce**
Sorry, no idea replicate 

**Version**
9.0.4. dedicated server, german setting, windows 10

**Comment by fluidsc** [comment]
I do not want to double-post or tripe, or quadruple, or whatever... I know there are other posts about this out there, but this issue is still happening to our group playing as well. I also know another group that plays this game, and it died like this on stream for them numerous times. This really needs to be resolved, as I can find the same issue discussed as far back as October 2018 without really looking.

It looks pretty bad for you guys starting out to have this game die on a stream with 1500 viewers like that :(

**Comment by SaulApostle** [comment]
Missing entity EntitySpawner
Come on, this is an important bug,making certain locations inaccessible

**Comment by Regalis11** [comment]
I made a new issue report with some more information and details about these errors, lets try to compile information about the problem there from now on: #1815
