### ISSUE TITLE
Missing equipment and stuff in my character's and other's inventory

### ISSUE THREAD

**Issue by 63ss** [Regalis11/Barotrauma#1618]
- [V] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i spawn at a ship, i do not have any items, except the toolkit and a crowbar, i don't even have an ID-card or clothes, only visual but other players have the same problem, but they really don't. I can run, open doors with the "access denied" message showing up, but i can't really take any items - within 1 or 2 seconds it's drops out of my inventory. Other players see that i'm dropping my things at the begining. 

**Steps To Reproduce**
Join the server, spawn in, that's all.

**Version**
0.9.0.4, steam.

**Additional information**
When i'm hosting the server - my friends do have the exactly same problem, but i don't.
![1](https://user-images.githubusercontent.com/43208571/59375804-97cd5c00-8d57-11e9-9793-ea748fc80973.png)
![2](https://user-images.githubusercontent.com/43208571/59375806-9865f280-8d57-11e9-8374-63e531b7b6cb.png)

**Comment by Regalis11** [comment]
Do you have any mods installed? There is an issue in v0.9.0.4 that causes the game to use modded character files even when the mod is not enabled, and in this case I think it might be that it's using character files from Barotrauma Extended that cause the number and order of the inventory slots to change, preventing the inventory from working correctly in multiplayer.

The issue should be fixed in commit 122be77, which hasn't been released as a patch yet, but for now you might be able to fix it by deactivating BTE (or any other mods that modify the human config file) from the Steam workshop menu. Sorry for the trouble. :/

**Comment by 63ss** [comment]
Firstly, thanks for the answer. Secondly, yes, i do. I have BTE installed, i tried to reinstall the game, but it doesn't help me. But! I found the problem and the solution. 

BTE isn't deleting from the game folder even if game was deleted in Steam. I deleted all folders from the main folder, redownloaded the game and now it's all right.
