### ISSUE TITLE
Everyone drops clothing and I cant put any on

### ISSUE THREAD

**Issue by TheGoodDoctor194** [Regalis11/Barotrauma#1621]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I join a server and a new round starts, I hear the sound of everyone's inventory dropping onto the floor, then when I spawn in everyone has no clothing, and I see everyone clothing on the floor. I then try to put clothing onto myself then it drops immediately. 

**Steps To Reproduce**
I don't know, man I even reinstalled my game.

**Version**
Steam Release, Vanilla 0.9

**Additional information**
Can't upload a video so here is a private youtube link:
https://www.youtube.com/watch?v=34bYoBBmxNE&feature=youtu.be

**Comment by Regalis11** [comment]
Do you have any mods installed? There is an issue in v0.9.0.4 that causes the game to use modded character files even when the mod is not enabled, and in this case I think it might be that it's using character files from Barotrauma Extended that cause the number and order of the inventory slots to change, preventing the inventory from working correctly in multiplayer.

The issue should be fixed in commit 122be77, which hasn't been released as a patch yet, but for now you might be able to fix it by deactivating BTE (or any other mods that modify the human config file) from the Steam workshop menu. Sorry for the trouble. :/
