### ISSUE TITLE
Launching multiple instances of the game from the same folder(mainly for mod and server testing) can cause game to have two content packcages selected at the same time and a lot of weird bugs

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1629]
changin content pack while two games are running adds another contentpack into .xml instead of editting the content pack part

**Comment by Regalis11** [comment]
Unfortunately I wasn't able to reproduce this. Selecting any combination of content packages and applying the settings causes the settings file to be updated correctly. Being able to select multiple content packages at the same time is intentional, the only exception are core packages (that define the executable and config files the game won't work without), of which there can only be one selected at a time. Could you please give more detailed steps on how this happened?

**Comment by etet2** [comment]
i've messed around and i'm not actually sure how i a managed to do it the first time, might have been a one off thing. closing this
