### ISSUE TITLE
Cannot get "Kill a Moloch" acheivement

### ISSUE THREAD

**Issue by gustavlasko** [Regalis11/Barotrauma#1633]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have killed 3 Molochs and not gotten the acheivement

**Steps To Reproduce**
1) Start single player campaign mode
2) Select Dugong as sub
3) Tool around for a bit
4) Find Moloch (or have one find you)
5) Shoot with coilgun until dead
6) Underachieve :(

**Version**
Barotrauma 0.9.0.4
Windows 10 Home 1908

**Comment by Regalis11** [comment]
I think I finally figured out what might be causing this. This seems to happen in the case of the larger boss variant of the molochs (the one that's used as a target in monster missions, not the ones that spawn naturally in levels), because their species name is "molochboss" instead of "moloch". Should be fixed now in the private repo (https://github.com/Regalis11/Barotrauma-development/commit/1f4176a68900e52825b84051bbedf6c8ad3375a6)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
