### ISSUE TITLE
Lock all wiring button / disable option

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1687]
It would be nice if there was some sort of block on rewiring on anything as an option in editor / in game. Going through an entire ship and disabling such is a pain and sometimes you only wish such for a hosted public campaign but wish it able to be wired when playing with trusted people without having to make 2 copies of a ship.

**Comment by thegrb93** [comment]
Good way to make a ship 200x more boring.

**Comment by littlewolf120** [comment]
This isn't a conversation, it's a request for such feature for people who would like such, you don't need to use it if you don't like such. You'd probably be a banned guy on my servers.

**Comment by hubismal** [comment]
> This isn't a conversation, it's a request for such feature for people who would like such, you don't need to use it if you don't like such.

A comment option exists so that people can present counterpoints like what thegrb93 technically just did. This isn't just an issue ticket place, people have the right to disagree with your request, present a solution to issues, etc.

>It would be nice if there was some sort of block on rewiring on anything as an option in editor / in game. 

I feel like a much better solution to the dewiring problem would be having wiring be a repair-like system that takes a while to do and has a high chance of electrocution without the required skill. Wiring still occasionally works for doing things like rerouting power to parts of the ship that need it badly, or attempting to jam enemy signals in sub vs sub, or dewiring detonators. I just think it's way too easy at the moment to quickly dewire the terminal and DC.
