### ISSUE TITLE
FR: Show battery level, improve drug affects

### ISSUE THREAD

**Issue by d3x0r** [Regalis11/Barotrauma#1705]
I see you're very busy with lots of little issues, but congrats on having thousands closed and only few open.

Drug Effect/Affects
People are going around willy nilly giving me morphine and phentonyl for just a sliver of burn damage (from the occasional 2 second overheat on reactor)... It would be interesting if drugs affected what you saw in gauges.  The reactor, for instance, could show that it's running too cool, and needs to be heated (or vice versa), or that the power level is higher/lower than what it really is.... ON the captain side/sonar -nav, if affected, could slowly turn the display (but only while watching, so the changes are just gradual, and you don't really notice a radical change)...

but; my more practical feature request
it would be nice to know  __Edit: at the reactor panel__, what the level of the batteries are in the ship (and maybe separately gun batteries from ship batteries).  I'd assume that the batteries really cover most of the lull/overvoltage the reactor generates from lots of maneuvers. While in the reactor control panel.

I'd also slightly nerf the AI reactor control, reaction time; basically you can put in 1 rod, and basically never overheat the reactor (given that there is a load on it), so a lot of people are convinced that the 'best' thing to do, is put 1 nuclear (not even thorium) rod in, and leave it on auto....
I Personally love the reactor-control-slider-mini-game :)  would be a little better if I could see some indication of what navigation is doing; like WHY suddenly there's a load of 11K on the reactor...

Some ships are just way underpowered, such that the turbine is capped out, and just can't give any more (the typhoon can pull 6.5 aldmost 7K power, but its turbine can only give 5k (maybe 5.2-5.5k) 
There's a little room that you could overdrive the turbine, by running the reactor extra hot, but it doesn't give you very much...

(I am a developer, and might decide to tinker with this some; I did like C#; just personally moved on and away from it (can see my github profile)).

**Comment by SaulApostle** [comment]
In the current version, you can see the battery's power, percentage or value.

**Comment by d3x0r** [comment]
Perhaps by 'current' you mean 'next?' is there a experimental branch I failed to find?

![image](https://user-images.githubusercontent.com/1909610/60095209-eb01c000-9702-11e9-8255-6cc46b81bbf0.png)

Or maybe I'm just blind?

**Comment by SaulApostle** [comment]
We're talking about batteries. Why do you look at nuclear power plants?

**Comment by d3x0r** [comment]
Because I apparently missed the context of 'while in the reactor control panel'.

**Comment by SaulApostle** [comment]
How does the reactor know how much electricity is in the battery?

**Comment by d3x0r** [comment]
Probably more wires from the batteries that provide statuses out to reactor

**Comment by hubismal** [comment]
>People are going around willy nilly giving me morphine and phentonyl for just a sliver of burn damage (from the occasional 2 second overheat on reactor)... It would be interesting if drugs affected what you saw in gauges. The reactor, for instance, could show that it's running too cool, and needs to be heated (or vice versa), or that the power level is higher/lower than what it really is.... ON the captain side/sonar -nav, if affected, could slowly turn the display (but only while watching, so the changes are just gradual, and you don't really notice a radical change)...

Painkillers already give you addiction/withdrawl through abuse. It would be pretty harsh to give people actively game-screwing psychosis just because a medic injected them a few too many times. Withdrawl seems like a more balanced and fair approach, especially since heavy withdrawl can kill you.
You did mention some interface-screw, which is something I do think the default psychosis could really use, just to be more convincing than something like water that's on fire.

>it would be nice to know Edit: at the reactor panel, what the level of the batteries are in the ship (and maybe separately gun batteries from ship batteries). I'd assume that the batteries really cover most of the lull/overvoltage the reactor generates from lots of maneuvers. While in the reactor control panel.

Your feature requests relating to showing the distribution of the grid load seem like things that could be fixed by just including an interface showing power pull through a basic wiring system with indicators for whether the batteries are on; Basically, it could be fixed through custom wiring. This especially applies to batteries, as there could literally just a be a charge display on the wall. It wouldn't be in the hud but you could see it on the corners of your screen. (I'm actually working on a feature request related to this)

There's an already existing feature that lets you link two items to have their GUI show side by side. It seems like your issue could be fixed if these feature was expanded on to let things like batteries and reactors be linked to show their GUI (or parts of their gui) next to eachother.

>I'd also slightly nerf the AI reactor control, reaction time; basically you can put in 1 rod, and basically never overheat the reactor (given that there is a load on it), so a lot of people are convinced that the 'best' thing to do, is put 1 nuclear (not even thorium) rod in, and leave it on auto....

The reason auto can't do everything is so the reactor intentionally handicaps the power grid by not allowing people to use it recklessly. It's also super slow so that if someone needs to get the reactor back online, it's better to do it manually. Having the autotemp be too good would make the game too easy.

>Some ships are just way underpowered, such that the turbine is capped out, and just can't give any more (the typhoon can pull 6.5 aldmost 7K power, but its turbine can only give 5k (maybe 5.2-5.5k)
There's a little room that you could overdrive the turbine, by running the reactor extra hot, but it doesn't give you very much...

Putting in multiple fuel rods should up the reactor max output should you really need it. If it absolutely cannot go any higher, that is (hopefully) the intentions of the designer, and your best approach is disabling taxing power drains from the ship.

Sidenote: Feature requests generally aren't allowed in the github. Go on the forums and post your FR there. Maybe they will be allowed again later, but right now only devs are allowed to make feature requests. This is because there are still a lot of critical issues and feature requests are flooding the issues page.

**Comment by d3x0r** [comment]
> Painkillers already give you addiction/withdrawl through abuse. 

well... during a quick match there isn't much time for withdrawal; but maybe.. I do remember someone saying they wanted more...


> Your feature requests relating to showing the distribution of the grid load seem like things that could be fixed by just including an interface ....

There's a few readout panels I've seen too... 

> There's an already existing feature that lets you link two items to have their GUI show side by side. It seems like your issue could be fixed if these feature was expanded on to let things like batteries and reactors be linked to show their GUI (or parts of their gui) next to eachother.
> 

Hmm interesting.

> The reason auto can't do everything is so the reactor intentionally handicaps the power grid by not allowing people to use it recklessly. It's also super slow so that if someone needs to get the reactor back online, it's better to do it manually. Having the autotemp be too good would make the game too easy.
> 

I was saying, it's already too good :)  Though if you just do something like put a few rods in, or a thorium/fulgiam(whatever) rod in, the AI drives the reaction rate really high before the power, so it's pretty much doomed to fail startup with more than a couple rods.   (I did do some digging, to see the algorithm of the core/reaction/fuel consumption), I was kinda hoping there would be like an exponent to multiple rods... such that `( H =  sum(rods) ^ (1 + (nRods-1)/10) ) `  ~ My original scribble was like ( rod1 * rod2 * rod3 * rod4  ) ~  such that more rods added more heat than a single rod of any type... hadn't really thought about what that would be; but right now, it's just the sum of all fuel, which doesn't give any fuel savings for having more than one... one might argue 'well it's not a breeder reactor', but still, neutrons from other near sources can enable other fission to happen that wouldn't have previously....  

> Putting in multiple fuel rods should up the reactor max output should you really need it. If it absolutely cannot go any higher, that is (hopefully) the intentions of the designer, and your best approach is disabling taxing power drains from the ship.
> 
Yes, was noting that in the ship designer.  and I suppose by the point I really was sort of rambling without much intent.

> Sidenote: Feature requests generally aren't allowed in the github. Go on the forums and post your FR there. Maybe they will be allowed again later, but right now only devs are allowed to make feature requests. This is because there are still a lot of critical issues and feature requests are flooding the issues page. Don't be surprised if Regalis closes this issue without comment.

Right; gotit; sorry.

**Comment by d3x0r** [comment]
The editor doesn't have settings for how much the reactor can be overpowered (on turbine); so it's just character skill that allows it... but I think it's only like +10% .

Also reactor doesn't have control points for fusion rate and turbine output control (at least not that I understand)  there's tempurature out, meltdown warning, and shutdown...
If I wanted to wire wifi controls to it or other ai logic circuits...
