### ISSUE TITLE
Multiplayer campaign missing entity Some things

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1725]
![PCTH9Y7428V(P6%0)N~6@CW](https://user-images.githubusercontent.com/11502419/60383040-834eca80-9a9e-11e9-9eb7-1b9ea88cdfdf.jpg)
The problem remains serious.
Errors usually occur when a level starts cruising.Someone was kicked out of the server,And the cruise was terminated and the others returned to the outpost.However, the level is still inaccessible and the same error message will appear.This campaign is usually abandoned.Because there are more and more places that can't be visited.This bug prevents the game from going on properly. It's the main bug in the current version. Please fix it first.Many people I know mostly play this game in COOP, especially in the multiplayer campaign mode.
9.0.7

**Comment by Regalis11** [comment]
Found another issue that was still causing these errors:

The problem was that NetEntityEventManager would write the _current_ ID of the entity in the message, even though the client did not necessarily know about the ID being changed yet.

For example, if the game created an event for an alien pump with the id 123, then loaded the player's character who happened to have a headset with the ID 123, the pump would get assigned a new ID and EntitySpawner would create an event that lets the client know about the ID change. But when the server wrote the event for the pump, it used the new ID, which the client would not know about because the EntitySpawner event had not been received yet.

The bug has been fixed for the next patch, although it is still possible there are additional issues that can cause these errors.

**Comment by Rokvach** [comment]
The issue has been improved for the next update, will close this as its better to open up a new issue if it still occurs.
