### ISSUE TITLE
Campaign Mode mission: "submarine recovery"

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#173]
In the event that someone manages to escape the submarine via shuttle and the round ends, next round the crew will have to recover that broken-down sub.

If nobody is alive on the main sub or everyone voted it to end, even if a single person has escaped a "submarine recovery" mission will be initiated.

On the campaign map it would place a special icon somewhere along the path, and you'll start at whatever outpost you reached via the shuttle. You cannot do any mission besides this, however, since all you get is a respawn shuttle to pilot.

Not only would this make use of a respawn shuttle in Campaign mode, but it would also add "escape" mechanics for the missions. Perhaps in modes besides Campaign, escaping should be possible, however this would only benefit traitors who have completed their objectives and decided to escape via the nibbler or something.

If the submarine fell into the abyss, no "submarine recovery" mission is initiated and it's either an instant game-over or you'll have to buy a submarine with 5-10k credits or w/e.

If submarine recovery mission is failed, it's game over, man.

All of this can also be implemented into single-player campaign.

**Comment by Crystalwarrior** [comment]
Related issues:
https://github.com/Regalis11/Barotrauma/issues/76
https://github.com/Regalis11/Barotrauma/issues/77

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
