### ISSUE TITLE
VSync causes bugs in multiplayer campaign

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1737]
[1684](https://github.com/Regalis11/Barotrauma/issues/1684)
One of the reasons for this problem,VSync ON causes no monsters in multiplayer campaign,It may also cause incoherent firing of the turret.I've been testing this for hours and I've finally found out what the problem is

@Regalis11 Many questions I didn't get answers from you, especially the closed posts, including the Steam forum.I'm not sure you saw them.The bugs caused by those bugs maybe I should write a separate post.

**Comment by thegrb93** [comment]
I use v-sync and have had no problems.

**Comment by SaulApostle** [comment]
> I use v-sync and have had no problems.

I finally had a way to avoid the bug that had plagued me for so long.

**Comment by Regalis11** [comment]
I don't think VSync is causing the problem - we've been testing the game with VSync on and most players tend to have it on as well. And since the server is responsible for spawning the monsters, I don't see how the client's graphic settings could have an effect.

>Many questions I didn't get answers from you, especially the closed posts, including the Steam forum.I'm not sure you saw them.The bugs caused by those bugs maybe I should write a separate post.
We do read everything that's posted in the issue tracker, if you haven't gotten an answer it generally means we haven't had time to look into that issue yet or haven't been able to find a solution to it yet. 

As for the video you posted in #1684, I don't see anything out of the ordinary in that. You're playing low-difficulty levels and only encountering a handful of small monsters in most of them, which seems normal to me.

**Comment by SaulApostle** [comment]
> We do read everything that's posted in the issue tracker, if you haven't gotten an answer it generally means we haven't had time to look into that issue yet or haven't been able to find a solution to it yet.

OK then, I've written what I said before as a new bug.
