### ISSUE TITLE
"Dry-dock" as suggested by John Brown

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#174]
As suggested by John Brown, have it so submarines could have a special type of hull in which another shuttle could be located. This way, the dry-dock would open its gigantic hatches, let in whatever shuttle that is trying to dock, close the hatches and then drain the water.

This might be challenging to implement due to the various physics interactions happening at the time of docking, but it sounds like a really neat idea and almost a must for things like physical outposts.

**Comment by T-rexsuper1** [comment]
Great idea, whos the autor...Wait a second, its me!

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
