### ISSUE TITLE
Thermal Scanner HUD

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#175]
This could be under other names, its a nice idea cooked up in discord between a few users.

In short:
Add a new item, Much like the Medical Scanner HUD.

This one plays an entirely new role, more towards the securities new gadget.

Essentially it picks up Heat sources. I know the game does not have a heat system but this would be simple to actually implement.

This tool does the following overlay when equipped:

- Tint the screen to a slightly darker colour (A darker green or darker blue) to simulate its a heat sensor.

- Allow this tool to display where you cannot see (It draws over the shadows if possible) such as characters and objects behind walls for the glow effect only.

- Display 'heat' as a Green/Orange/Red tint with distance and alpha

- Give it a limited range, the further away an object the less alpha and colour it has.

- Water level of a hull or the ambient temperature of the ocean makes the scanner worthless in the sea and in flooded hulls (Not drawing inside them and turning it into a blue static if in range perhaps of water) - If the character wearing it is submerged completely nullify the device.

- Possibly enable it to record heat from specific component types (Oxygen generator, reactor, junctions) based on activity / load - Highest value of all valid components checked results in the strength.

- Naturally display where fires are and perhaps the damage radius of volcanic vents

- Show creatures limbs as a copy of the sprite colored to the heat, creatures may have warmblooded tag so numerous creatures can in fact not be displayed by this device at all

Note for balance reasons, this is to have a high falloff in alpha with range, make things "Hard to make out".

Why have this as a thing? It will allow security to pinpoint where characters may be to a degree without knowing whom they are, if there is a danger beyond a door perhaps, if there are lukewarm corpses stashed in the broom closest.

If its balanced right this could be a fairly nifty tool giving spawning security (Or as an item for submarine makers) a new way to find hiding suspects or those in suspicious places (Such as inside the security spawn as a mechanic).

**Comment by Crystalwarrior** [comment]
Personally I feel this will cripple the traitor's ability to murder as it basically means that as soon as he tries killing anybody security will see it no matter what they do.

**Comment by NilanthAnimosus** [comment]
Thats why the range is very limited. its not meant to be insanely useful - but could help determine a few things. Picture it having a max range of half your view distance or less, and even then is hard to actually make out. heat sensors aren't so amazing through walls anyways in reality.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
