### ISSUE TITLE
Reactor output changes cause issues with batteries on Automatic Setting.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1758]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Due to reactors changing their output based on battery output, batteries fail to charge unless reactor output is manually raised. Compared to 0.9.0.7 in which the reactor simply output the load plus the battery charge rate, and it seemed that batteries only output when reactor output was less than current grid load.

The best example is this picture comparing the Typhon's reactor load in 0.9.0.7 (Left) to 0.9.1.0 (Right)

Reactor Load (0.9.0.7 Left) (0.9.1.0 Right)
![0 9 0 7 Left 0 9 1 0 Right Reactor](https://user-images.githubusercontent.com/16188887/61479692-fa6ad680-a959-11e9-9c45-15bfe47e094d.png)

Battery Charge (0.9.0.7 Left) (0.9.1.0 Right)
![0 9 0 7 Left 0 9 1 0 Right Battery](https://user-images.githubusercontent.com/16188887/61479746-140c1e00-a95a-11e9-803e-0459b60b3b06.png)

An example of how the load behaves when manually raising the reactor output with batteries attached to the grid, is show in this Gfycat Link
https://gfycat.com/aridacidicdevilfish

As far as adding this to fix the Humpback overloading, I believe the issue is caused by the simple operation of batteries charging, and then filling up and dropping all the charge load immediately. Not to mention Batteries directly tied to relays, as seen in the default Humpback, do not properly balance load between batteries. This leads to all batteries on the humpback draining as if they are the only singular battery powering the submarine, instead of a bank of four. Though that is probably another issue in and of itself. Battery and Relay issues already posted in this issue. https://github.com/Regalis11/Barotrauma/issues/1445

**Steps To Reproduce**
I believe the description should contain all relevant information. Though if you compare a 0.9.0.7 build Typhon to a 0.9.1.0 build typhon, you will see the difference.

**Version**
Barotrauma 0.9.1.0 Windows 10

**Additional information**
No additional information I can think of currently.

**Comment by FamiliarBreakfast** [comment]
Honestly, the "fix" for the humpbacks overloading issue has caused more problems than it fixed. You can't use backup batteries to spool up the reactor, batteries can't just be directly wired in to act as capacitors, now this.

What the humpback needed was a simple circuit that detected if the batteries were on and the power overloading, then to shut the power off. This would be easy to do if we had a power detector to output the amount of power on the connected circuit. With that, it would be fixed with only two AND gates and a delay component. 

![Diagram](https://user-images.githubusercontent.com/48958412/64719633-a7fbf100-d496-11e9-9ad0-63bc69e1ad98.png)

You can see it in action here: (replace .zip with .sub)
[Sub.zip](https://github.com/Regalis11/Barotrauma/files/3601928/Berilia.Improved.zip)

The "ARSE" system uses a similar circuit to automatically shut off the reactor when it overheats for too long (off by default). With a power meter, this could easily be modified and much better contraptions could be made.

Personally, I would add an output to the junction box that outputs its current power level. Shouldn't be that hard since it already displays it and uses it to run code to explode.

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
