### ISSUE TITLE
Идея(и) с гидрокостюмами. / The idea(s) with the wetsuits.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#177]
Сделать так,
1. ... чтобы гарпун, пули и прочие удары имели хоть какой-то шанс на нанесение урона.

2. ... чтобы нельзя было вколоть что-либо в игрока, который находится в нём.

3. ... чтобы появлялись повреждения на них. При этом если появилась в гидрокостюме "пробоина" во время нахождения в воде, то:
          1)  замедлить игроку движение.
          2) уменьшить "срок работы" кислородных баков и кристаллов.
          3) постепенно набирать давление внутри гидрокостюма.
                    Идею предложил не я, а он: steamcommunity.com/id/CrowRaZeR/
To do so,
1. ... to harpoon, bullets and other attacks had at least some chance of dealing damage.

2. ... so you can't stick anything in the player that is in him.

3. ... to have damage on them. Moreover, if appeared in a wetsuit "the hole" while in the water, then:
1) slow down the player movement.
2) to reduce "period of work" oxygen tanks and crystals.
3) gradually build up the pressure inside of the wetsuit.
                     The idea came from not me, but him: steamcommunity.com/id/CrowRaZeR/

**Comment by Crystalwarrior** [comment]
7.0.1 version has bugged diving suits having way more protection than they should. This will be fixed in later update.

Not being able to inject anyone inside a diving suit, ehhh... I dunno, sounds like a huge pain in the ass especially if you're out on a salvaging mission. If you can't inject or be injected with corrigodone, how are you even going to survive?

Having diving suit condition doesn't really sound fun, either. Keep in mind that there's a LOT of spare diving suits, which means having to do any sort of upkeep on them in addition to that would just warrant the players to dump the broken ones and purchase newer suits just so they don't bother.
All diving suit condition would do is limit their use, and the oxygen tanks already fulfill the same purpose.  

Oxy tanks last incredibly short so people don't keep on diving forever without burning through a lot of tanks or getting oxygenite shards ASAP. If you also had to worry about the diving suit breaking or rupturing it'd just make salvage missions HELL and make them even less used outside of that.
