### ISSUE TITLE
Microsoft antvirus quarantining Barotrauma.exe after a crash

### ISSUE THREAD

**Issue by Shoe-Pi** [Regalis11/Barotrauma#1789]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I launched the game through Steam and hopped into a server hosted by a friend to try out some of the patch features.  The game crashed suddenly (I can't think what the cause may have been, I think I was repairing a junction box) with [this error log](https://github.com/Regalis11/Barotrauma/files/3542737/crashreport.log).

If I try to launch the game Steam gives me this error:

"An error occurred while updating Barotrauma (missing file privileges):
E:\Steam\steamapps\downloading\602960\Barotrauma.exe"

After verifying the game files Steam reports 2 files which need to be downloaded.  When these files download Microsoft Security Essentials opens a popup in the bottom right of my monitor saying that "detected threats are being quarantined".  The History tab of MSE states that it is flagging "Behaviour:Win32/DefenceEvasion.LR!ml":

![MSE](https://user-images.githubusercontent.com/20929510/63719633-40fafd00-c845-11e9-9990-73fcea20accc.jpg)

**Steps To Reproduce**
I'm not sure how to trigger the original crash, but after that launching the game gives the missing file privileges error, and validating the game files through the Steam interface triggers the MSE quarantining warning.

**Version**
v0.9.2.1

**Comment by Regalis11** [comment]
MSE doesn't seem to flag the current build as malicious anymore, so the false positive may have been reported enough times or the file reanalyzed. 

But in any case, antiviruses produce false positives every now and then, and I don't think there's a foolproof way we can prevent that. Especially since Barotrauma needs to be able to do "potentially suspicious" things such as communicating with remote servers, downloading and installing files and deleting files. I think we can close this as it's not technically a bug, and there's not much we can do about this other than reporting the false positives to the av vendors when they happen.
