### ISSUE TITLE
Crashes when welding holes

### ISSUE THREAD

**Issue by kloskon** [Regalis11/Barotrauma#1793]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
tutorial first mission

**Version**
0.9.2.1

**Additional information**
crashes when welding holes

**Comment by Regalis11** [comment]
Are you playing in Russian? If so, this is caused by an incorrect text tag in one of the tutorial texts. We've fixed this for the next patch that's coming out very soon, but for now it's possible to work around the issue by opening Content/Texts/RussianVanilla.xml inside the game folder, and replacing the line
`<mechanic.draintext>Когда подлодка затоплена, лишнюю воду можно откачать при помощи насосов. Обычно насосы получают сигнал от датчиков воды или навигационных терминалов, но некоторые можно использовать и вручную. Чтобы включить насос, используйте {1} и переведите выключатель в положение «Вкл.»</mechanic.draintext>`
with
`<mechanic.draintext>Когда подлодка затоплена, лишнюю воду можно откачать при помощи насосов. Обычно насосы получают сигнал от датчиков воды или навигационных терминалов, но некоторые можно использовать и вручную. Чтобы включить насос, используйте {0} и переведите выключатель в положение «Вкл.»</mechanic.draintext>`

**Comment by Rokvach** [comment]
Working correctly. Closing.
