### ISSUE TITLE
Coilgun shoots through hull

### ISSUE THREAD

**Issue by BradleyRasic** [Regalis11/Barotrauma#1796]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If two ships in the combat game mode meet with one ship on top of the other, the bottom guns of the top ship can swivel through the hull and shoot inside the other ship, essentially bypassing the hull -- Using standard ammo

**Steps To Reproduce**
Position one ship on top of the other, and aim/fire the coilgun from the top ship into the bottom ship

**Version**
V 0.9.2.1

**Additional information**
Unknown if it occurs with the railgun aswell

**Comment by Krzeszny** [comment]
I have an idea how to solve it. **Hardpoint should have HP.** When shot X timex or when something rams into them, they break and need to be welded like hull. Until they're welded, they can't shoot.

**Note:** at least one of these options must be added:
a) when a hardpoint is wedged against a hull, it can't be repaired 
and/or b) you can't repair enemy hardpoints (to be able to repair hulls)

**Comment by Krzeszny** [comment]
@Regalis11 I have an idea how to solve it and it's somewhat important in pirate battlles, so that pirates don't shoot with coilguns bypassing hull. 
- **Hardpoint with HP.** When damaged for X damage or when something rams into them even at minimal speed, they break and need to be welded like hull.
- AI won't try to and players can't repair them if they're too close to enemy hull - this solves the original issue
- You can't repair enemy hardpoints - this allows you to repair your own hulls if they're wedged against hardpoints
- Until they're welded:
- - Gun traverse is locked
- - They can't shoot

**Comment by Regalis11** [comment]
The fix is not yet included in any public build I'm afraid.

**Comment by Jasontti** [comment]
Tested with coilgun and railgun.
No issues found, closing ticket.
