### ISSUE TITLE
Crashed when going into server browser.

### ISSUE THREAD

**Issue by PgLemon** [Regalis11/Barotrauma#1809]
I have searched the issue tracker to check if the issue has already been reported.

Description
When I click on the Server Browser button the game just crashes. Happened 15 times in the last two days.

Steps To Reproduce
Well, you can try just clicking server browser but honestly its a hit or miss thing.

Version
v0.9.2.2 Mac.

**Comment by Regalis11** [comment]
Unfortunately I wasn't able to reproduce this issue. Could you please send the crash report if you have one? It should be saved in the game's root folder with the name "crashreport.log".

**Comment by FamiliarBreakfast** [comment]
https://pastebin.com/Gs0xVFrW
I got about twenty different crash logs from this. I can send more if needed.
Neofetch:
https://pastebin.com/eR9VdJm2

Sometimes it fixes itself.

**Comment by mlooney** [comment]
I too experience this issue +1

**Comment by Rokvach** [comment]
The previous patch added a fix for this issue and we haven't had any further reports of it happening, seems that the issue has indeed been fixed, so closing this.

**Comment by FamiliarBreakfast** [comment]
This issue seems to have reappeared, though unlike the previous times, the only crash report is a mono crash report. no crashreport.log
I have no idea if this report is even relevant, but it's the only thing that appeared. Reinstalling and verifying have not worked. Just like before, it sometimes goes away, which makes me think it's related to mono, still.

[mono_crash.3b53af77b.0.json](https://github.com/Regalis11/Barotrauma/files/3906277/mono_crash.3b53af77b.0.json.txt)
