### ISSUE TITLE
Dock/Port Damage integration, docked shuttle sheering force effects (IE. Can tear off shuttles in crashes)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#181]
Currently docks and ports have a "Fix requirement" though I know of no method to actually *Break* them in any particular way (And this requirement is high in skill or multi-job required as-is).

As well as this a shuttle can be used to effect the ballast weight and the speed of the submarine its docked to (IE, you may use a shuttles engines when the main submarines engines have been destroyed to move the main submarine).

The idea is simple, give Docks and Ports a "Max force" or "Max Sheer force" value.

Then use this value as a measure of undocking a submarine and destroying the port with a significant enough impact against the docked shuttle (But not if a main submarine - only when the submarine impacted is the docked sub).

Additionally (If possible) allow smaller values to act as a "buildup" to if beyond a certain percentage of the maximum sheer force a dock can take - eventually tearing off a docked shuttle, destroying the dock and freeing the shuttle (Such as achieving 80%+ of the max sheer).

Whenever a docked shuttle is "Torn off" - Perhaps add damage to both submarines near the dock location (such as an invisible structure explosion) damaging both the shuttle and main submarine for being torn off forcibly.

This will allow additional mechanics (Such as no permission to undock a shuttle - one could forcibly undock the shuttle although likely suicidal to do so).

**Comment by Crystalwarrior** [comment]
Perhaps make it very loud and obvious when someone is trying to undock the shuttle by sheer force with looping pitch-shifting creaking sounds? That way people will know something fishy is going on.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
