### ISSUE TITLE
[Suggestion] Infinite Oxygen when Docked to an Friendly Outpost

### ISSUE THREAD

**Issue by MystLeissa** [Regalis11/Barotrauma#1810]
I would like to see Outposts have the capability to resupply our submarines oxygen vents. There are a couple of ways you could go about doing this but the overall objective is to prevent "Death by timeout" when docked to a friendly outpost. Methods by which you could do this are as follows:

A. Link Oxygen Generator to Docking Port to Pass Oxygen Between Ships and Give Outposts a "infinite" supply of air.

B. Give the Outposts the Ability to Transfer Exactly 1kW of Power to the submarine via the existing docking port recharge mechanism.

Of the options I like A the best - as it solves the problem while not introducing any unwanted scenerios such as rouge battery charging etc. On the other hand, Option B is likely easier to implement straight away seeing as half the system already exists in the docking port.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
