### ISSUE TITLE
Vanilla 0.9 Content Package: SecureMetalContainer Doesn't Lock Because of Singular Identifier Tag

### ISSUE THREAD

**Issue by MystLeissa** [Regalis11/Barotrauma#1814]
- [ No - Pretty sure a 1 character fix isn't reported] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"RequiredItem identifier='idcard'" SETS the identifier not checks it.

Steps to Fix:
Change "RequiredItem identifier='idcard'" to " RequiredItem identifiers='idcard' " Under "itemContainer" for SecureMetalCrate in Containers.xml

**Version**
Which version of the game did the bug happen in. You can see the version number at the bottom left corner of the main menu, and in a file called "Version.txt" inside the game folder.
Also, please include the operating system you're using (Windows/Linux/Mac).

Vanilla 0.9 Content Package Windows NT (Well actually Windows 10 but for some reason randomly my operating system reads WinNT :shrugs:)

**Additional information**

This is a content package fix and I fixed it in closed alpha with a simple override of the item. Fixing it in Vanilla is a 1 character change to the content package. Also Due to Formatting I have changed Less than and greater than symbols in the this report to double quotes and reformatted singular quotes for double quotes.

**Comment by Regalis11** [comment]
The file does seem to say "identifiers", and actually it does not even matter, both "identifier" and "identifiers" are valid. Are you sure you're using an unmodified version of the game?

But in any case, I'm glad you pointed this out, because there seems to be another bug in restricting access to inventories. It's possible to interact with the inventories of items that are forced to stay open when equipped (such as crates), I'll look into fixing that now.
