### ISSUE TITLE
Players with a variant of illegal symbols/emoticons can still join servers

### ISSUE THREAD

**Issue by databasetd** [Regalis11/Barotrauma#1819]
- [* ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Despite certain symbols/emoji not being listed on the "allowed symbols list", it still permits a handful of symbols to pass through. This is mainly around emoji symbols. I noticed it after someone joined in with a swastika emoticon on a game server.

Symbols:
|
卐
Or generally any other emoji on https://fsymbols.com, while it may not appear it still passes through. One thing I saw is when attempting to change my name with this, it denied it for illegal symbols, however joining remained unaffected.

**Steps To Reproduce**
1. Join the game with a certain illegal/emoji symbol (as mentioned as to what I've found above)

**Version**
0.9.3.2

**Additional information**
On certain symbols as well, it is known to increase the font size of the chat UI.
![image](https://user-images.githubusercontent.com/28366123/65377364-e6549580-dc78-11e9-9417-2db88f3650e1.png)
![image](https://user-images.githubusercontent.com/28366123/65377393-3c293d80-dc79-11e9-8025-67c82241d3c8.png)

**Comment by Regalis11** [comment]
卐 seems to actually be the symbol for the Chinese word "swastika" (which causes the font to change because Chinese symbols cannot be rendered with the default font). I think we can disallow this specific symbol, but if you want to make sure none of the players use any Chinese/Japanese/Korean symbols in their name, you could change the range of allowed symbols in the serversettings.xml file (removing all the character ranges above 1279)
