### ISSUE TITLE
Mousewheel dimension layer scrollability

### ISSUE THREAD

**Issue by Akronos** [Regalis11/Barotrauma#1846]
For example: A Divesuit a welder a crate a ladder and a button are  placed at the same place.
Problem: to pick a particular item it s  a Little bit difficult to pick it.
Solution? ; mousewheel up changes the layer of the itemselection in the one direction. (any dropped item gets an individual layer or number) mousewheel down in the other.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
