### ISSUE TITLE
Clipboard item for player-created documentation in mods

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1850]
Subs really need some kind of hands on documentation, the millions of obscure two word labels next to buttons really don't do it.

It seems like a straightforward solution to let users make their own simple text documents with minor XML formatting that can be accessed as items.

**Comment by hubismal** [comment]
Since this is copy pasted from what I wrote in the discord, I should probably add that users cannot, in this hypothetical situation, edit the documents because that would probably just lead to chaos, misinformation, and a bunch of stuff we already have enough of in baro as is.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
