### ISSUE TITLE
[0.9.5.1] [Feautre Request? Issue?] Lobby prompts to download every selected sub on serverlist

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1901]
When a server host clicks on a server, sometimes just to see its preview, it prompts clients to download every time a new sub is selected. Usually, server hosts are just clicking through the subs to see which one they want, but clients are flooded with download prompts. It would be better if there was a "confirm" button where you clicked a sub and selected confirm in order to send the file to the users.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
