### ISSUE TITLE
Password config field disappears after a server is shut down

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#1907]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The password field in serversettings.xml disappears if the server is shut down, so after each shutdown a new password would have to be added to the config.
This only really affects dedicated servers, as client-hosted servers can add a password when creating it so it doesn't really matter.

**Steps To Reproduce**
1. Manually add the password field to serversettings.xml
2. Run the server
3. Exit
4. Password disappears

**Version**
* 0.9.5.1
* Windows 7

**Additional information**
It must be a proper shutdown with the exit command, if it crashes it doesn't save the values and also doesn't remove the password field.

**Comment by Regalis11** [comment]
I believe this may have been intentional (@juanjp600?). Storing passwords in plaintext is generally not a good idea, although in this case I'm not sure if we necessarily need to put security over ease-of-use; if someone has access to read the config files on your server, having them get to your password-protected Barotrauma server is probably not the thing you should be most concerned about.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/238c853e8f414ace9b1c6013f9e158c53ea1e00f (private repo). Servers keep a plaintext version of the password in memory now, which allows them to store it in a readable form; might consider adding the option to store the hash instead.

**Comment by Regalis11** [comment]
Moved to Review/QA

**Comment by Rokvach** [comment]
Tested, works correctly. Moving to Done.
