### ISSUE TITLE
[Feature Request] People with the stunned affliction go blind

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1913]
I posted this on the discord and people overwhelmingly thought this was a good idea. It shouldn't be too hard to implement either. 
People with the stunned/unconcious affliction should go blind. This would make it more realistic and give players more fair-ish opportunities to sabotage people (it would be possible to run into a room and quickly knock someone out before they see who you are). The sabotaged would also wonder where they were dragged to when they wake up, somewhat realistically. They would wake up with handcuffs on in a room without a radio, adding to the mystery(?).
They could also be made deaf I guess. But there's sort of a cool habit ingame right now where people taunt the stunned in whisper chat, so making them go deaf while stunned would sort of ruin that.

**Comment by FamiliarBreakfast** [comment]
I quite like this idea. I would also add that the when going into stunned from a blunt force (which doesn't actually happen, but should. Like a charged hit with a crowbar, or 2-3 uncharged should) it should be instant blackout, whereas chloral hydrate should be a slow fade in as the sedative takes effect. Furthermore, stunning from electricity (stun baton, taser, etc.) should just lock the players movement and make them stumble for the first hit, rather than immediate blackout. When waking up out of unconsciousness, you could have a nice fade where your character slowly gets up off the floor.

Two things I think should be in both the existing system and a new system is struggling, basically you click/press a button as much as you can to try and struggle your way to consciousness, and blurred vision after blunt trauma.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
