### ISSUE TITLE
[Future Feature Request] Dynamic UI Degradation + Improved Repair System

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#1925]
I was browsing the new dev blog on [UI](https://barotraumagame.com/gameplay-features/future-user-interface-improvements/) and I noticed at the bottom, there's a lot of competing styles that are fundamentally different. Specifically, they can be separated into two groups: new and damaged.
So I thought, "What if instead of having just one, the sub designer could choose a certain theme to fit with their sub?" And then I had another idea: What if the UI started out clean, but over time it degraded as components either got damaged, flooded, burned, and repaired. 

Basically, they start out fresh (unless the sub designer specifies otherwise), and as environmental conditions changed, they get worse. For example, if they get partially flooded with sea water, then they get lightly rusted. If they get completely submerged in sea water, they get very rusted (and rust could build overtime). Or if the get damaged, the interface gets burnt, destroyed, etc, to match the existing sprites. Fire leaves charring and melting, but flooding washes char away. Repairing it adds metal plates, etc. And if the device stops working, the physical UI components could get a damaged look, like dials shattering and buttons falling off.

This could also go well with an advanced repair system where it isn't just, "Oh, it broke again, throw a wrench at it," and instead different parts could break that you have a little minigame to repair. Those parts could then break on the UI so you know what to fix. You could then add more use to the engineer, who's really only good at doing it faster than others, but not anymore since the update changed the thresholds. The engineer could either have hints, or see things other people can't.

Sidenote: It'd be nice if the reactor was at risk of shutting off or having a meltdown when damaged, since currently, unless it's at zero, I don't _think_ it does anything.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
