### ISSUE TITLE
Enable deleting with backspace in the sub editor

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1928]
https://steamcommunity.com/app/602960/discussions/2/1740008902398839194/

> The delete key doesn't delete the structures already placed in the submarine editor. I'm using Apple's Magic Keyboard (which most of us desktop Mac users use) which doesn't have the Insert+Home+PgUp...section and the delete key in the backspace position which is sending out the backspace signal (tested and confirmed at keyboardtester.com). I tested the game in Mac OS and Windows 10 (using boot camp), and it's the same thing in both cases.
> 
> Apple's Magic Keyboard
> https://www.apple.com/shop/product/MLA22LL/A/magic-keyboard-us-english?fnode=56

**Comment by Rokvach** [comment]
I replied to this idea somewhere previously but I think changing the keybinds for a single type of keyboard is a bit too much of a stretch, I think the deletion process of selected items in the sub editor would need to be simplified on the UI level. So if someone does have a custom keyboard like this one they would still have the easy access of deletion.

Because if we just change it from Delete to Backspace there is bound to happen issues of players accidentally deleting items they didn't mean to if they forget to select a text field before pressing backspace for example. 

We could also make it possible to bind that key, but that would mean we would need a separate controls settings for the sub editor outside of our current controls settings so there isn't any confusion.

**Comment by Regalis11** [comment]
I don't think we should change it from delete to backspace in any case, I was thinking of supporting both. Accidentally deleting items when trying to erase text is a good point though, although I'm not sure how likely that is actually to happen. I'm having a hard time imagining a situation in which you forget to select a text field before pressing backspace.

**Comment by CommanderMark** [comment]
Generally it seems like most pieces of software that support both macOS and Windows just change the behaviour per-OS, where on Windows deletion of non-text assets is done using delete and on macOS it's done using backspace.

**Comment by muhhy** [comment]
You may not be aware, but there are a whole lot of keyboards out there besides Apple's Magic Keyboard without independent delete keys, especially on laptops, so please be aware that it's not a "Mac thing".  I just pointed out Magic Keyboard because there's a whole lot of people using it since it's the cheaper option when you buy a Mac.

In fact, I own 6 keyboards which only 2 of them have independent delete keys.  Try a google image search for "compact keyboard layout" and you'll find that a lot of the keyboard doesn't have it.

There usually are some non-standard key modifiers that will change some other key to act as delete, but most of us have to go digging for the manual to find that since we don't use those keys in our everyday lives.

**Comment by CommanderMark** [comment]
So pretty much just making it impossible to delete on an 84-key keyboard. Just to clarify (since I've never actually used the sub editor myself) is there no way of deleting structures using only the mouse?

In the event that you can't a workaround for the moment is to press fn + backspace which functions the same as delete, but there should really be a way of removing structures without a hotkey.

**Comment by Regalis11** [comment]
Added a context menu that can be used to delete entities (https://github.com/Regalis11/Barotrauma-development/commit/d72abd3, private repo). Might be enough to solve this issue without having to risk accidental deletions when trying to remove text from textboxes?

**Comment by Rokvach** [comment]
I think the context menu would need to be always present when right clicking, currently it only seems to work when right clicking placed items, but what if you copy that item, there is no way for you to paste it other than using shortcuts

**Comment by Regalis11** [comment]
Should be fixed in the ux-improvements branch now (along with a couple of other improvements)

**Comment by Rokvach** [comment]
- [ ] When pasting an item using the context menu, it places the item to the current position of the cursor rather than the position the context menu was opened from.

**Comment by Regalis11** [comment]
Fixed in b6d9c6d

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
