### ISSUE TITLE
[Feature Request] Movement-based Oxygen Loss

### ISSUE THREAD

**Issue by ZealanL** [Regalis11/Barotrauma#1929]
It's kind of silly how you go unconscious from not having oxygen for more than 25 seconds, even when standing still.

I think that your oxygen depletion rate should be increased depending on whether you are moving or not. Maybe your character can hold their breath 50 seconds if you are standing still, but if you run and swim around your oxygen depletes more quickly and only lasts about 20 seconds. This would make running around looking for oxygen a big risk, and give players an intuitive and realistic method of staying alive if they find the submarine flooded or the oxygen running out.

You could simply do something along the lines of this pseudocode.
```
if (character.MovementInput == NotMoving) {
    someClient.Character.Oxygen -= oxygenLossRate;
} else {
    someClient.Character.Oxygen -= oxygenLossRate * 2;
}
```

**Comment by itchyOwl** [comment]
Agree. Needs some design input.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
