### ISSUE TITLE
[Feature Request] Multiple traitors

### ISSUE THREAD

**Issue by Athenades** [Regalis11/Barotrauma#1940]
What drew me into this game originally was the prospect of traitor mode, although it's seemingly somewhat different now than back then.

Would be cool to have multiple traitors w/code words, just because it seems fun to have to try to find allies at the expense that someone might find out.

Furthermore, a long run traitor mode for Campaign might also be nice.

**Comment by DerEchteSpatz** [comment]
+1

To be honest, I do not understand why they completely removed the option to have more than one traitor, in the beginning.

Why not make it ONE traitor as standard, but let a server option present where the admin could change that, if he feels the need for it?

**Comment by Regalis11** [comment]
This is actually supported by the traitor system, we unfortunately just haven't had the time to design and implement any multi-traitor missions yet. :/ In the previous system it was easy to have multiple traitors because the objective was always the same and it didn't require any changes to the objective text, but now that we have much more complex multi-stage missions, multiple traitors need to be taken into account in many of the objectives and texts.

Btw, it is fairly easy to mod these in (and you won't have to worry about localizing the texts to a dozen languages! :D). We already have one placeholder 2-traitor mission in place (but currently disabled), see line 211 in TraitorMissions.xml. 

I unfortunately can't give you an ETA on when we'll actually include multi-traitor missions in the vanilla game, but they are on our todo list.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1720](https://github.com/Regalis11/Barotrauma-development/issues/1720) via [**ZenHub**](https://www.zenhub.com/)
