### ISSUE TITLE
Mountable speakers for ship-intern communication.

### ISSUE THREAD

**Issue by DerEchteSpatz** [Regalis11/Barotrauma#1945]
When our ship is full to the brim, the radio channel often gets spammed with unnecessary chitter...
We tried to throw them in the brick. We tried to beat them up by the security. We even airlocked some of them out of the ship to make a clear statement...

But it simply does not work. Disciplined communication behaviour is rare in these days...

So, our captain ordered the regular crew to take of their headsets off and only take them on, when we have an emergency. Since then, we have problems communicating with our chief of engineering, since he often takes off his headset, too, when he gives minor orders to his engies, in order to keep the radio channel free...

We would propose a ship-intern-communication system to be a good solution for problems like that. It would include speakers (which would transfer the used VOIP signal of the selected channel) into the sourrounding area, just as if the bystanders would use a headset for said channel. And 
additionally some (mountable) communication buttons which would work like a stationary headset, transfering the local VOIP of the bystanding crewmember(s) into the speakers channel.

In that way, 90% of the crew could use only local VOIP (to preserve radio discipline), but the captain could make sure, that his orders are always heard by everyone, everywhere.
If the crew would need to make immediate answers to his message, the single crewman (mostly it would be a chief of some kind) could answer with the system as well.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.

As for this particular issue, we're implementing local VOIP and the option to change the channel on the headset, which should remedy the issue to some extent. :) If that's not enough, we may consider adding support for transmitting VOIP through items.
