### ISSUE TITLE
Coprocess Load has failed

### ISSUE THREAD

**Issue by Rob-exe** [Regalis11/Barotrauma#1952]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes on load up.

**Version**
V0.9.5.4

**Additional information**
The files:
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/3995887/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/3995888/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/3995889/crashreport.4.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/3995890/crashreport.log)

**Comment by Hydroculus** [comment]
I have the same thing, how to fix it?
When i open the game it crash instantly and shows this note

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4007011/crashreport.2.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4007012/crashreport.log)

**Comment by Hydroculus** [comment]
Close steam app, it works for me when i did it.

**Comment by Regalis11** [comment]
It seems that the game for some reason fails to autoupdate some of the mods you have installed. We need to look into this more closely to figure out why it happens, but for now you might be able to work around the problem by doing one of the following:

- Disable mod autoupdates by openig config_player.xml inside the game folder, and change the line `autoupdateworkshopitems="true"` to `autoupdateworkshopitems="false"`.
- Disable the mods you have installed. Since you can't open the settings menu, you'll have to do this by editing config_player.xml manually: remove all the contentpackage definitions like `<contentpackage path="Mods/Somemod/....." />`, except the vanilla content package ("Data/ContentPackages/Vanilla 0.9.xml").
- Launch the game directly from the game folder when Steam is not open. This will prevent the Steam autoupdates from running, and should allow you to go to the settings and disable the mods.

**Comment by Regalis11** [comment]
Just noticed that the crash report is from an older version of the game. There were some fixes related to workshop items in the latest update, so you might want to update your game and see if that fixes the issue. I'm closing this for now, but if the problem persists or reappears, please drop a comment here and I'll reopen the issue!
