### ISSUE TITLE
Autopilot is abit wonky.. Sub keeps moving when set to maintain position...

### ISSUE THREAD

**Issue by diebaeterz** [Regalis11/Barotrauma#1955]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Parked my sub near the alien ruins. Set it to autopilot. Sub doesnt stay in one place, keeps struggling to maintain position. Moving up and down and doesnt seems to stop.

**Steps To Reproduce**
Load any map. 
Load Humpback sub.
Manual steer sub at high speed.
Then turn on autopilot with maintain position.
Watch the sub, shake it down.

**Version**
9.5.0 - Windows 10 x64
0.9 Vanilla

**Additional information**
Didnt find any thread about this.

**Comment by hubismal** [comment]
if you used the airlock on your sub (I assume you did because you parked outside an alien ruins), its inevitably going to have to adjust when you go out of the airlock since you're letting water into the sub. it's also possibly you could just have an extremely big/sensitive ballast. I (and nobody else I know) have never had an actual issue with the autopilot maintaining position, so i assume one of these is the case.

> Manual steer sub at high speed.
Then turn on autopilot with maintain position.

What's the expectation here? for it to stop on a dime?
0.9.6.0 also makes autopilot improvements. this isn't really related to your issue per se but you might want generally to report things here for the latest version of the game, not older versions where issues might be fixed.

**Comment by Ek-Videogames** [comment]
(PID settings for AI maintain position just need updating to the new physics parameters to prevent oscillation issues. Maintain position undercorrects for how slow submarines are now causing the sub to constantly ping up and down on it's target position. Very annoying on artifact missions, and likely causes ballast pumps to waste energy constantly having to make huge corrections after the sub flies past its intended target position)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3dc31ab80bd8d0e729358c3db5e0c9bdc571a65 (private repo). This seems to have been caused as a side-effect of the autopilot changes in v0.9.5.0: the autopilot didn't try to prevent overshooting waypoints as heavily, which caused it to perform better when navigating a path, but not so well when trying to maintain position.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
