### ISSUE TITLE
[Feature request] Visualization of external installations on the sonar

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1970]
It's kind of difficult to approximate the timing for ejecting decoys / depth charges when you don't know where they're going to be ejected unless you haven't checked it out beforehand.

I'd like to see devices mount on the exterior of the submarine (discharge coils, railguns, ejection tubes, etc.) to be visible on the sonar of the helm, similar to how the docking port is shown,possibly represented by a small icon, or something similar to that.

**Comment by hubismal** [comment]
adding to this, the exact shell would also be nice. i don't see a real gameplay reason why you wouldn't want the player to know exactly where things are on the shell of their ship. it would also help with docking.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
