### ISSUE TITLE
Removal of the Throwable Component

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#198]
An idea conjured up between myself and Crystalwarrior - Essentially:

Add a new key for throwing an item, essentially allowing one to throw anything from their welder to an oxygen tank or a simple drug.

Remove the Throwable component, have it so anything that could be held can be thrown - Perhaps add a tag to the Holdable class for Throwable in XMLs (Default to false)

Add a new condition for status effects like OnContained / OnUse except for OnThrown. This way grenades can have their timed behaviours and such - And have their separate use. this could allow items not meant to be throw-able have their own status effects for being thrown.

This way one could have a primary use, a secondary use (The Aim), use inside other items and a thrown use all entirely separate from each other.

If one wants to not require the aim use for throwing, It could be a held action (Such as requiring at least 0.5-2.5 seconds of holding down the throw key to actually throw an item, varying the range once the minimum time is met).

Throwing distance and speed could simply go off a weight/mass item attribute related to how easy an item can be thrown based in the XML per-item

**Comment by Crystalwarrior** [comment]
I'm thinking the throw key is basically second aim tho

**Comment by NilanthAnimosus** [comment]
well if you have Aim on an item that doesn't actually use it for aiming exactly, as it is technically a secondary use as well - it might not be so great, and this key could apply to almost anything that could be held.

So none throwable and none-aimable items that are meant to have a second use could wind up impaired if you began to add throw-like aiming to them by default if they could be thrown when using that second action.

Hence why the throw key is more of a "Second Aim". just considering how that'd be in implementation is all.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
