### ISSUE TITLE
Forced Ragdoll and Health Screen issues

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1986]
I've noticed these two bugs while doing some tests with some new afflictions. I checked if these happen in vanilla and they do, so here's both of them.

Forced ragdoll will make characters show up as "stunned" and allow them to fake being stunned even against a piece of hardware that should detect such trickery. Don't know how the hardcode for it is set up but after some tests with custom afflictions, a value of 0.5 will keep characters stunned without them showing as such in the scanner, while using 1.0 will show the stunned condition in the piece of hardware.

The other issue is in the health screen. When an affliction appears/dissapears (I think) from a character, the targeted limb "resets" and targets the torso or another limb. This is more noticeable in mods with a number of afflictions running at the same time, even afflictions set to not show up in the scanner and/or the health screen.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
