### ISSUE TITLE
Mechanic Tutorial progression flag not triggered during deconstruction.

### ISSUE THREAD

**Issue by mfoutch** [Regalis11/Barotrauma#1988]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When doing the Mechanic tutorial, the door doesn't unlock if you deconstruct multiple air tanks at the same time.

**Steps To Reproduce**
Play the Mechanic tutorial normally until you get to the point where the game wants you to build a fire extinguisher.

If you deconstruct 3 air tanks at the same time, the door won't unlock and you won't be able to progress. Even if you make the fire extinguisher.

**Version**
 v0.9.6.0

**Additional information**
I didn't try this with recycling 2 at the same time.

You could also easily fix this by adding one more air tank to recycle. That way if the player recycles 3 the first time (like I did) there's still one remaining to trigger the flag to get the next objective.

**Comment by Regalis11** [comment]
I think the issue was not actually that you deconstructed all the three tanks at the same time, it was that the game expected you to pick up an oxygen tank and some sodium from the cabinet before proceeding to the next step, and did this by checking if you have _both a tank (or aluminium) and sodium in your inventory simultaneously_. If you moved the tanks and the sodium away from the cabinet separately, it would get stuck at that step, and if you used the materials at that point to craft extinguishers, there was no way to proceed.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3eb0ced75694e556311366d7cc97c4b98dd34ab3.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
