### ISSUE TITLE
[Bug] [AI Bots in Singleplayer] Bots will object to themselves trying to do things

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2004]
If you control a bot when they are trying to do something (like navigate at the helm), attempting to switch to manual and steer on your own will have them yell at you and switch it back to auto.

**Comment by itchyOwl** [comment]
Which version were you on?

From your text I understand that when you take control of a bot that is currently doing something the bot would not allow you to control the character you are controlling (which is he/she). I don't understand how that could be possible.

However, if you mean that the bot doesn't allow another character to take control of the device they are currently operating, this could happen. If the bot is _ordered_ to do something, it's intentional that the bot doesn't allow others to operate the same device. However, when they act on their own (following the autonomous objectives) the bots should always give room for the player.

There were issues where the bots wouldn't allow the player to take control of the reactor or steering when they were following autonomous objectives (i.e. acting on their own). But these issues should be fixed in 0.9.7 (current unstable).

**Comment by itchyOwl** [comment]
I don't think this happens anymore. Let's close the ticket.
