### ISSUE TITLE
[Modding] [Feature Request] Give locations ability to change name

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2005]
It would be much appreciated if there was a way for locations to change the name when they change location types to appropriately reflect the change. This could be a parameter or something in locationTypes.xml.

**Comment by Regalis11** [comment]
This is already possible to some extent: the format of the name can change, for example "The Hives of Belus Linea" -> "Belus Linea" -> "Belus Linea Outpost" -> "The City of Belus Linea". I personally don't see it worth the effort to implement the option to change the "base name", especially since we wouldn't use it in the vanilla game.
