### ISSUE TITLE
Broken devices still send the last signal they were sending when they were working.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#2035]
This happens with the reactor, relays, junction boxes... etc. They get stuck with the signal until repaired. Don't know if it's intended or not but I feel like it's a bug.

**Comment by Regalis11** [comment]
The reactor does keep sending the "temperature_out" signal even if it's broken, but shouldn't be sending anything else. I tested this on the public v0.9.6.0 version and the Unstable version, but unfortunately couldn't reproduce the problem; the signals stop going out as soon as the devices break (excluding "temperature_out", which sends out "0" as intended). Could it be that the issue is somewhere else in the circuit you're using? For example, if you're using Text Displays to show the outputs, the last received output will stay on the display until you set it to something else with the "set_text" input.

**Comment by ChikoEduardo** [comment]
I currently have no internet at home to send a file but another example would be to send a signal thru a junction box that set_states a light on, and then break the jb. You'll see the light will still be on, even if the signal is no longer true.

**Comment by Regalis11** [comment]
That's actually intended behavior. When the junction box is broken, it won't send any kind of signal through, and the light won't receive a signal that would turn it off.

**Comment by ChikoEduardo** [comment]
Oh. I thought it was a bug. if the signal is set to an alarm instead, how do I make it so the alarm stops sounding on its own if the component relaying the signal is broken?

I noticed this while I was working on automatic alarm systems but I guess I better use relays that don't break instead, lol.

**Comment by Regalis11** [comment]
You need some kind of a circuit that stops the alarm if it hasn't received a signal from the relay in a while. You could for example add an AND component between the relay and the alarm, with the output of the relay connected to both inputs of the AND component, or an oscillator that sends a shutdown signal to the alarm every x seconds.
