### ISSUE TITLE
[0.9.702] Issuing orders is tedious

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2094]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It takes forever to issue orders to your crew especially in singleplayer when you start having a large amount of them. There's too much mousing over to verify the orders, and having to right click to give different crew a command, since left clicking may end up giving a occupied crew a new order. This should be reverse where right click should be the quick order issue, not left. The crew selection web is pure random for the first 5 as well, making you have to dig further for the rest of the crew by expanding. There's no priority given to people with higher skill level for those orders, nor priority to those with no orders. Also there's no name under the crew web, making you have to mouse over to double check each one.

**Version**
0.9.702

**Additional Information**
![](https://user-images.githubusercontent.com/5086682/73505505-a88f1880-43a0-11ea-92f8-8ff2d51d3281.PNG)
This takes me a good 4 minutes to issue, and I have to redo it every single round.

**Comment by NilanthAnimosus** [comment]
I feel this could get tedius navigating through menus. I made a few tweaks for fun to the UI quickly on my own end.

I increased the size of the crew image and slightly increased the distance from the center, while decreasing the distance the expanded icons appear at, so its all easier to see, closer together, and less need of expanding it.

![](https://media.discordapp.net/attachments/552424003546120192/672638168205361163/unknown.png?width=803&height=640)

**Comment by ekqvist** [comment]
With the current behavior, "idle" crew members **should** always be prioritized over those with active orders, both in quick assignment and in manual assignment. The crew assignment nodes **should** take into account the appropriate jobs for the task, such as engineer for operating the reactor. But I agree that the relevant skill should also be accounted for, as should the current orders and their importance.

Thank you for your feedback. It's a work in progress, and we're definitely looking to improve the command interface further.

**Comment by NilanthAnimosus** [comment]
I like where the UI is going and I hope this is taken more as a suggestion, but I do like speed when using a UI and I feel that currently its taken a bit of a hit with orders compared to a list format.

I understand its a work in progress, and the UI is unfinished, so i'm going to throw in some thoughts I stated on the discord. I did use other methods like holding down the key to assign an order (took me around ~4 seconds for a reactor job auto assign) alongside the mouse

I feel to the older UI, it takes me perhaps longer to issue a series of orders to separate crew members.

so mind keeps thinking what may make the process quicker
such as category hotkeys (IE. you hit your order button, in my case "T", then you can hit another key such as 1 for the first clockwise option, perhaps noted on the icon itself) - all optional things, but view this as hitting T -> 1 1 to assign a fix leaks, T -> 1 2 for a fix objects, etc. which if your a long term player becomes actually a very quick painless means to do certain orders almost by code.

The benefit is I can do this 3-4 times in a few seconds, ordering a wave of AI to get down on fixing a catastrophe.

Interestingly, if anyone was insane enough, 9-10 characters does basically mean a 1-0 button press. though that isn't really making it faster or easier use and feels senseless to me perhaps, its an interesting enough thought.

visual information to which character already has a job when manually selecting, its not obvious in any sense I could think of short of manually comparing what heads look like for assigned jobs. Perhaps include an active job icon near the portrait.

job or skill level based order sorting of the crew on the interface so in a clockwise fashion you see it by relevant job or skill first even if currently assigned, After all - I want my medics who may be on page 2 fixing damaged systems to be my immediate options in a crisis on commanding them to rescue.

I also feel both right mouse and left mouse should be able to navigate, which I've tried several times as I Actually almost always want to pick a character myself but need to use the button that is auto assign to navigate, to the point I nearly wish it was reversed.

Finally, oddly enough, I instinctively keep trying to close it by clicking away from the nodes. instead of escape or using the same key. not sure if that's just me.

right now, it feels like a random mix. where you don't see names/differences/skills/capability, just a job colour, nested in several menus each you have to click or drag to and wait while holding a key.
with a small amount of options per menu, requiring expands that throws icons somewhat far apart.

personally, I used the following to compact it (as honestly, I prefer less space and more compactness as I'll be navigating by mouse for this aspect, and the assignment logic for holding it down is basically unaffected, as you auto assign and not manually select a character when going clickless):

assignmentNodeMaxCount to 9 (9 to 10 options for first menu, depending if expand button is visible), if sorted, its way more than enough.
a node distance of 250 multiplied by UI scale.
node size / center node size around 100.
Slightly reduced the return node distance so it couldn't clip at all. (I used 0.55 in my screenshot, to be honest, mine isnt really the best value for size or position)
I slightly nudged the other node sizes up a few pixels.

Reduced the multiplier on GetPointsOnCircumference from a *2 to around a  * 1.55, to reduce the empty space.

**Comment by ekqvist** [comment]
Thanks for the suggestions! You definitely have a lot of good ideas in your comment. We have been monitoring the feedback on GitHub and Discord closely, and we're definitely actively considering our options for improving the command interface (among others) to make it feel more useful and fluid, instead of tedious.

Thanks, the feedback and suggestions are extremely valuable to us. I cannot comment on whether or not each specific thing gets implemented, but I can say that we have already internally discussed hotkeys, displaying information better, and improving assingment logic, at least.

**Comment by ezjamsen** [comment]
And on my behalf, thanks also - this is pretty much the model of feedback we would hope to get: constructive, well written, well thought out, and given in good spirit. Awesome stuff.

**Comment by NilanthAnimosus** [comment]
One more thing - I had a captain on steering and did another steering order with some AI free, which simply assigned a mechanic to steer the same terminal. I feel for certain objectives that you only have one person for (specifically almost just steering) - you actually want to change the existing persons order. conversely, if you have a submarine with multiple navigation terminals - how would this order cope? Some have backup bridges is all.

Perhaps the command related orders could be different, as I didn't notice until the bots were complaining at each other, If the orders are filled up though I imagine it would use a captain first. but perhaps it should change whomever has a similar order first. (IE. if it was mechanic, re-use that same mechanic when maintaining from navigating).

**Comment by Kaillera** [comment]
Maybe we can also add to the character saves with lastorder="leak" or lastorder="gun:1" so that each crew remembers what they did last round?

**Comment by NilanthAnimosus** [comment]
That should probably be a separate issue. I keep thinking to write it yet hadn't got around to making a fleshed out suggestion in my head for handling saving of objectives.

Saving of the objectives though could at least be implemented into single player.

partially and progressively implementing it per objective in the future with all unimplemented saving simply set to "Idle/None" - adding essentially the framework for later more complex implementation.

**Comment by ezjamsen** [comment]
I find that I often want to swap a crewmember between a pair of jobs quite regularly, especially when I have a small crew trying to do a lot of stuff (mechanic doing double duty and operating guns when not repairing equipment, for example), so remembering last task at least might be a handy shortcut.

**Comment by Rokvach** [comment]
No issues, closing.
