### ISSUE TITLE
Steamworks integration

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#21]
**Matchmaking**
= Listing available servers and connecting players to them using Valve's servers. The old master server could still be preserved as a legacy option for a potential non-Steam (GOG?) release and as a way to allow players to host their own "master servers".

**Achievements**
Self explanatory

**VAC?**
Investigate whether Valve's Anti-Cheat has any features that could be of use in the game.

**Comment by etet2** [comment]
workshop pls

**Comment by AlyMar1994** [comment]
There's an easy solution to the matchmaking problem. GoG's Galaxy system allows for cross-platform play, and can integrate into Steamworks as well so Legacy (GoG) branches can play with Steam branches when updated, and so on.

STAR WARS: Battlefront II Classic is already doing this, and works well but is a tad buggy (only because Disney doesn't truly care).

https://www.gog.com/galaxy

**Comment by Regalis11** [comment]
WIP achievement list: https://docs.google.com/spreadsheets/d/1f2s_SRTAEVnXsLnhqC7oUaTDsj26LJ3wFCxkVGcDKU4/edit?usp=sharing

**Comment by CryIz** [comment]
Can you add the similarity of "sv_cheats 1"? To make it so that when you enter any console commands achievements impossible to obtain. Yes, you can make an immortal submarine, but what is the chance that the path will be endworm?
As for the servers, I do not know how to implement it. The host can use console commands not only in its own .

**Comment by Regalis11** [comment]
I think the best way to do that might be to mark certain console commands as "cheats", allowing the host/admins/moderators to use the rest of the console commands without disabling achievements.
