### ISSUE TITLE
Wifi channel interference with Respawn Shuttle and/or Renegade submarines.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2100]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If Respawn Shuttle is the same as a existing shuttle or a shuttle that uses the same Wifi channels to operate, it causes interference with each other in some ways when they're in range. This also applies to Renegade submarines that has Wifi components.

I think the best solution for this is to have the game change all of the wifi component channels for Respawn Shuttles and Renegade Submarines so that it's different than the original.

**Version**
~0.9.702

**Additional information**
This has caused a interesting mishap where my regular shuttle has a very large wifi range. When I used the periscope, I found the respawn shuttle (which was selected to be the same shuttle as the one on the sub) hiding in the ceiling of the game. This also messed up the respawn shuttle, making it stay in the ceiling when players are spawned in, and thus they are stuck up there eternally.

**Comment by Regalis11** [comment]
Instead of modifying the actual channels, I think we should solve this the same way we solved the issue with wifi components communicating between the coalition/renegade subs in the Combat missions; they simply ignore the components in the other sub, but the channels are kept untouched.

If we did modify the channels, it would cause issues in more complicated circuits. For instance, if some sub had some circuit that modifies the wifi channels somehow (e.g. push a button, and the channel is set to 123 which controls the top railgun, push another button and it's set to 124 which controls the bottom coilgun), we would not only have to modify the wifi components, but all the components can that affect which channel the components operate on. And that would very easily get _extremely_ complicated; for example, there could be a regex component that reacts to a signal starting with "12" sent by the buttons in the earlier example and does something based on that signal...

**Comment by NilanthAnimosus** [comment]
this is where I wonder "how does that solution impact drone shuttles that are linked to a submarine" - I assume it would exclude outposts and respawn shuttles, but we do need cross-channel communication for linked submarines such as shuttles from a mainsub - I assume that theoretical fix would leave this unaffected ?

Drones, as well as submarines made of multiple smaller shuttles, are in fact designs that are used currently.

**Comment by Regalis11** [comment]
You're right: I think we should only prevent cross-communication between respawn shuttles and other submarines. If we applied it to shuttles in general it would break drones and multi-part submarines.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/70b3bbb6962420eef15706aca776e2a4e67927d5

**Comment by Kaillera** [comment]
Not fixed in 0.9.703.

Rokvach was using the same respawn shuttle as the shuttle that exist in my submarine, and we were able to interfere with eachother.

**Comment by NilanthAnimosus** [comment]
I saw it set the team to friendlyNPC - is this the same team as the mainsub in a campaign and mission though?

**Comment by Regalis11** [comment]
Looks like there was an oversight in the code: wifi components with the team ID "none" (= anything in the main sub in non-combat missions) were able to communicate with any wifi component and vice versa. Should be fixed now in https://github.com/Regalis11/Barotrauma-development/commit/5b9a2435939d5bd1b5b9873f84982f80ee2e7540.

@NilanthAnimosus No, FriendlyNPC is the team ID used for outposts and NPCs spawning in the outposts.

**Comment by NilanthAnimosus** [comment]
ok, Thanks for clarification : >

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
