### ISSUE TITLE
Unstable - game crashes 

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#2112]
- [**+**] I have searched the issue tracker to check if the issue has already been reported.
**Description**
Game crashes on launch immediately.

**Steps To Reproduce**
Launch the game.

**Version**
v0.9.702 (unstable), Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
**Additional information**
Previous DEV and master branches didnt have that problem.
Crash log
[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/4143750/crashreport.13.log)

**Comment by NilanthAnimosus** [comment]
One of your mods you are loaded has a modified Style.xml (or is it styles.xml ?) - it contains the tag "override" twice.

Saw this identical crash with BTE and the fix was to remove/replace that file, you may have to let the mod author know.

Sadly I do not know which mod is causing this issue specifically from the list.

**Comment by Stallfighter** [comment]
Yep, that was the translation fix, I turned it off on stable and problem is gone, ill note its author about possible future problems. Strange thing is that my game was on English for a long time now (for editor mostly).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d52577c99de1c5456d09ad6272e24c9bf38ddb5. Now this type of invalid style configuration displays an error in the console instead of crashing the game.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
