### ISSUE TITLE
[Feature Request] Stop despawning people in respawn shuttles

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2126]
it's pretty funny when the respawn shuttle despawns and then you have to explain to them in spectator chat that their character just stopped existing, but it's kind of unfair to the people who are still in the shuttle. maybe just dump them out in the ocean? that being said it's pretty funny when they're just about to get out the door in their diving suit and then the sub despawns with them.

**Comment by NilanthAnimosus** [comment]
I say keep it in. but it should be made more clear what will happen, when it will happen, timers, etc.

This simply sounds like an issue of it being unclear enough. simply dumping their bodies into the ocean will just kill anyone unsuited pointlessly and add never found or interacted with corpses often nowhere near a submarine.. its not like most players dumped into the ocean will know where the sub is, most don't even check the terminal. assuming they had suits, they will likely drown on top.

no really - why should we have bodies in the ocean full of potentially updating items, ragdoll physics, etc where nobody would ever see on the mainsub or next respawn? this seems senseless on so many levels and a waste of server resources. suddenly not existing isnt strange, as the respawn shuttle itself does that, and if you don't do this it very rarely ever navigates back successfully / always runs out of power, etc.

But I do dislike how even I am explaining the often missed or ignored single message to get off the shuttle, followed by confused players with closing doors and a shuttle autopiloting, to then simply be "deleted" isn't exactly the most understood concept for many I've played with in public servers, it could use something to aid why it does this, which is why in the past I asked for a timer on all stages to begin with to hopefully lessen the confusion.

though the whole auto closing doors, auto undock etc just messes with players as I cant even swim through a door on average in 0.5 seconds.

**Comment by Regalis11** [comment]
We're redesigning the respawning logic altogether, closing this

**Comment by grifball** [comment]
Just noticed this thread, I made a patch for this, but it currently has a lot of testing changes: https://github.com/Regalis11/Barotrauma/issues/3089

Curios to see how the rework turn out. I've been thinking about the respawn sub and it seems tough to balance.
