### ISSUE TITLE
[Feature Request] Summary Tooltips on Entity Mouseover in Console

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2128]
There is nothing more fun in Barotrauma then cycling through "Mudraptor 1" "Mudraptor 2" "Mudraptor 3" in the console. It would be nice, if on mouseover while the console was open (and the right permissions), entities displayed a tooltip with relevant debug info. Something like:
```
Mudraptor 3 (species: mudraptor)
Vitality: 40/80
Afflictions: bloodloss 10 gunshotwound 30 laceration 40
AIenabled: False
AIState: Null
ControllingClient: hubismal
Alignment: Team1
Inventory: revolver
```
would be nice. basically just a tooltip hooked up to every get method an entity has.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
