### ISSUE TITLE
[0.9.703] Crash EnemyAIController.UpdateAttack has returned

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2139]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[servercrashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4154868/servercrashreport.3.log)

**Version**
0.9.703
Windows

**Additional information**
Bots were shooting at something, and then it crashed.

**Comment by NilanthAnimosus** [comment]
same issue as #2019 and #2054 - Just a new line number, perhaps the same reason of crash but later in the codeblock.

**Comment by itchyOwl** [comment]
So either the Character, the SelectedAiTarget, or the SelectedAiTarget.Entity is null. The last two are checked at the beginning of the method. Character is readonly and always set in the constructor (AIController.cs:123). So I don't see how any of those three could be null.

**Comment by itchyOwl** [comment]
Unless we create the controller with a null character in the first place...

**Comment by Regalis11** [comment]
SelectedAiTarget.Entity is checked at the beginning of the method, but the value of SelectedAiTarget can change after that (line 646). There's a null check in place there too though, so I don't really see how the Entity could be null. I may be missing something here though: could the setter of the SelectedAiTarget property, or the virtual method call inside it, cause this as a side effect?

**Comment by Kaillera** [comment]
One thing I forgot to mention was I was hosting this in multiplayer server.

**Comment by itchyOwl** [comment]
You are in the right tracks there: the target can change if the original state resets.

I think this is what happens:
1) A neutral creature is attacked and turns from neutral to aggressive because it has "AttackWhenProvoked" true
2) It changes target to an item held by the target
3) Target changes and the original state is thus restored -> the selected target is null.

So there needs to be extra checks after setting the target. However, in this case we don't want to reset the original state, so I need to think over it.

**Comment by itchyOwl** [comment]
I guess I'll rewrite the logic so that this can't happen. It's confusing if the target can change in a callback.

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@50292f2.

**Comment by Rokvach** [comment]
No reported sightings since 703, seems to be working correctly. Closing.
