### ISSUE TITLE
Show wires in the entity selection dropdown in the submarine editor

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#216]
Сделать так, чтобы при наведении на провода в "Wire mode" показывало все, с которыми можно манипулировать. При наведении на окно с названиями выделять этот провод. Это будет очень удобно. Во всяком случае для меня.
To make it so that when you hover over the wire in "Wire mode" showed everyone that you can manipulate. When you hover over the window with the names to mark this wire. It will be very convenient. At least for me.
![default](https://user-images.githubusercontent.com/33912761/34434356-a36e48de-ec96-11e7-8755-429fa9274f2a.png)

**Comment by T-rexsuper1** [comment]
Cool!

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
