### ISSUE TITLE
Bots - Power Up Reactor order and Engineers hates 2+ Uranium Fuel Rods

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2164]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever Engineer Bots or those that were given Power Up Reactor order, they don't put in extra uranium fuel rod when you're struggling at 80% output. Conversely, if you had a second rod in the reactor, they pull it out (This leads to another problem described in #2165).

**Version**
0.9.703

**Additional information**
To improve on this, Bots should automatically throw in another rod when you're about to hit that 80% on uranium fuel rod. I feel like they shouldn't try to take out any rods not depleted afterward. Currently swapping into thorium as fast as possible and never making uranium ones ever again is a thing.

**Comment by Regalis11** [comment]
I think this was an intentional design choice. Operating the reactor with more than one fuel rod should not be necessary except in special circumstances (e.g. something pulling abnormal amounts of power from the grid), and it tends to be more dangerous than using one rod, so generally in those situations you'd need a human player to take the wheel or someone to fix whatever is causing the abnormal power drain).

@ezjamsen @danielasteljoki any thoughts on this?

**Comment by ezjamsen** [comment]
Let's avoid letting the bots load extra rods into the reactor. That's something I barely trust humans to do right...

Not a bug. Let's review the situation later on however when we have a bit more breathing room to iterate existing features as needed.

**Comment by Jazun** [comment]
I'm a few years late but could this not be a configurable option or something?
