### ISSUE TITLE
Fulgurium Battery Cell is just a regular Battery Cell outside of Stun Baton

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2168]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fulgurium Battery Cell is just a regular Battery Cell outside of Stun Baton. Perhaps higher life span or stronger electronic effects?

Handheld Sonar: Rapid pings?
Sonar Beacon: Further receiving range for Navigation Terminals and Handheld Sonars?
Underwater Scooter: Increased Speed?
Onboard/Shuttle Battery: Slower battery drain the more you put into them, or increased capacity?
Flashlight: Wider and Brighter ray? (I would put it on my head more if so)
Headset: Further transmission and receiving range.

**Version**
~0.9.703

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Regalis11** [comment]
Because the statuseffects are now tied to the vanilla item identifiers instead of the "mobilebattery" tag, it's impossible for modders to add custom batteries that would deplete inside the items. I think we should add an extra status effect to all of them to make sure they still work with other batteries, something like

`      <StatusEffect type="OnUse" target="Contained" Condition="-0.25">
        <Requireditem identifier="mobilebattery" excludedidentifiers="batterycell,fulguriumbatterycell" type="Contained"/>
      </StatusEffect>`

**Comment by danielasteljoki** [comment]
Sure. Did that for now. We might also consider using tags like 'basicbatterycell', 'advancedbatterycell' etc. but as long as we only have two kinds, there's probably no point.

**Comment by Rokvach** [comment]
No issues again, closing.
