### ISSUE TITLE
Bots - Does not know how to travel between submarine and docked shuttle/station.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2174]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm not sure if there's a way to install waypoints correctly to prevent this, but bots doesn't seem to know how to travel between docked shuttle/stations (There's no link first of all). In Multiplayer, there are rare occasions where they climb out into the station, and doesn't know how to come back to the sub.

**Version**
~0.9.703

**Comment by NilanthAnimosus** [comment]
given bots respawn that is a curious yet actual problem, but also since bots have no reason to enter a station in of itself not a strict issue in a regular campaign.

is worth looking into as AI does happen to respawn in mission mode on servers though. perhaps an active docking can link the necessary waypoints for the AI to follow. sort of like how they keep track of doors even to a degree.

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/6277af4b6cfc624c5ed354e9437467d0cf1ba41b (commited in bugfixes and merged to dev as well). The waypoints at the hatches would not get linked to the hulls created between the outpost and the sub, causing the bots to think they need a diving suit to get through the hatch.

**Comment by Rokvach** [comment]
When a player enters the hull piece between the sub and outpost bots will report in chat "Can't get there" but they do still follow the player without any issues. @Regalis11 

Tested in multiplayer campaign using Berilia. 

Steps:
1. Ask 5 or so bots to follow
2. Walk from the submarine to the outpost and notice that as soon as your character enters the hull placed between the two the bots will spam the chat with "Can't get there"

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/88af42aa8520a228c5fde0e8ed43ef3fff2a20c5

**Comment by Rokvach** [comment]
No issues, closing.
