### ISSUE TITLE
Item location desync, Especially non-ruin holded artifacts

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2177]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Occasionally you'll find artifacts outside of ruins in the levels. They can spawn in the air, or on slopes of the map generation. When you try to pick them up, it will fall out of your inventory until you pick it up where it originally spawn at. This is also true when it happens on items on the sub when you're changing battery/oxygen tank etc.

Also commonly in 0.9.6 multiplayer, items would drop out of a player's inventory by a whole floor. The player would see it be on the floor in the same room where it was dropped, but it usually desync to the the floor of the floor below.

**Version**
0.9.6

**Comment by Regalis11** [comment]
Did some changes to remedy this in https://github.com/Regalis11/Barotrauma-development/commit/018e056390985dd607f466c29f4b8325b04390a3: if the client fails to pick up the item, the server forces it's position to be updated. Won't fix the underlying issue of the items ending up in incorrect positions, but now the item's position should get corrected as soon as the client fails to pick it up.

**Comment by Kaillera** [comment]
Wouldn't that make artifacts that spawn in the middle of the water or on slopes impossible to get now? Usually we try to carry the false item back to it's original location because it drops off/rolls off from somewhere.

**Comment by Regalis11** [comment]
It shouldn't, because the bodies of the artifacts should be kinematic (immovable) until someone successfully pics them up.

That was actually the underlying issue; the artifact event would make the physics body kinematic to prevent it from falling down, but since the event logic now only runs server-side, it would stay dynamic client-side and end up in a different position than at the server's end. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/af7f5a1de4c0f8e0e9cd70f7ef4db95e8d96d708

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by thegrb93** [comment]
I'm getting reports of this occurring again for artifacts in 0.9.9.1
