### ISSUE TITLE
[0.9.703] Shuttle spawns outside the map, above starting station and unable to move

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2178]
**Description**
When I died, I spawned in a shuttle that was above starting location. I was in total dark, as seen on picture, and the shuttle can't move.
![bug5 shuttle1](https://user-images.githubusercontent.com/59519434/73966806-07abda80-4917-11ea-9fd9-a6cc3656165c.png)

**Steps To Reproduce**
Start a mission with shuttles enabled.
Die.
Wait for respawn.
Get spawned outside the map

**Version**
0.9.703

**Additional information**
Map seed: 0IaBY52U
Server: Nil's
Sub: Orca
Shuttle: Hemulen

**Comment by thecannons** [comment]
This bug is still happening as of latest vanilla build with no mods. 6/16/2024

Reproduce:
2 players
Park main ship outside of outpost (very first mission).

30 seconds respawn
3 min shuttle interval

1 person dies, other stays in main ship
Shuttle spawn normal, go to main sho near outpost, exit ship and die. Shuttle goes and despawns nearest outpost.

Respawn outside of map (shuttle is forever stuck here).
