### ISSUE TITLE
Running water sound when opening Humpback's bottom right ballast door for use

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2187]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Although the name for this issue is inaccurate, it should help lead to fix the issue.

When you open the bottom right ballast tank's door for the Humpback, the room plays the water leakage sound when there's no leak. I assume it's the sound that plays when water travels through another hull that doesn't have a pump in it.

**Version**
0.9.703

**Comment by Kaillera** [comment]
To be more precise, it's when water crosses hull, even if it's ballast water. Can be annoying when players make submarines with non rectangular shape for one ballast room.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/72864043ae81aede149c897f08ca831a5bd07dba. The water flow sounds aren't played when water is flowing between linked hulls (i.e. inside rooms that consist of multiple hulls). Doesn't affect Humpback's ballast though, because it consists of two rooms separated by a door, and I think in that case the flow sounds should play when water is moving between the rooms.

**Comment by Rokvach** [comment]
No issues, closing.
