### ISSUE TITLE
[0.9.704] SupplyCabinet is pretty underfilled

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2209]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Supply cabinets using SupplyCabinet spawner are pretty underfilled. They usually only contain 0~3 items.

**Version**
0.9.704

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
