### ISSUE TITLE
Вылетает игра при запуске реактора. / Game crashes when starting up the reactor.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#222]
Сегодня ночью тестировал свою субмарину и всё было в порядке. Сейчас же я снова решил проверить её работоспособность и дальше её доделывать, но тут появилась проблема. Как только реактор достигает температуры в 1300-1700 градусов игра просто выдаёт ошибку. В журнале сервера нет ничего об этом, журнал ошибок вообще не создаётся. Мне не хочется терять столько времени в пустую. Есть предположения, что это происходит при включении ламп.
to test it further to finish it but there is a problem. Once the reactor reaches the temperature of 1300-1700 degrees, the game just gives an error. In the server log there is nothing about this error log is not created at all. I don't want to waste all that time for nothing. There are suggestions that this occurs when switching on the lamps.
Субмарина / Submarine: 
https://drive.google.com/open?id=1B3sRcr_dWPFudXf-gi0Cpl2LqkLEjb6q
![image](https://user-images.githubusercontent.com/33912761/34461378-fb0cffce-ee38-11e7-95c7-5aec2f3f12e9.png)

**Comment by Regalis11** [comment]
Looking into this, seems like it's an stack overflow exception caused by an infinite signal loop between junction boxes. Nice work on the sub btw!

**Comment by Regalis11** [comment]
Fixing this turned out to be more complicated than I thought. I managed to fix the stack overflows by using the delayed signal approach where the signal carries on during the next frame if it takes more than 10 steps between items, but it completely killed the performance due to the complexity of the signal connections in this sub.

So I think I'll need to do a bigger overhaul on the junction box logic. The PowerTransfer components should probably maintain a list of all the connections/itemcomponents that the signals eventually get sent to and simply relay the signals directly to them instead of stepping through all the wires and junction boxes in between. This could also be used to optimize the power logic, no need to keep recursively checking the layout of the grid every frame if the PowerTransfers maintain a list that only gets updated when needed.

**Comment by CryIz** [comment]
То есть нужно дождаться обновления, чтобы субмарина начала покорять пещеры спутника?
That is, you need to wait for updates to the submarine began to conquer the cave of the satellite?

**Comment by Regalis11** [comment]
I'm afraid this won't be fixed until the next update, but in the meantime you could might be able to work around it by reducing the amount of signal-carrying wires between the junction boxes. I think the way the steering signals were passed to the pumps and engines was causing this error, so you could try passing those signals using less complex wire connections (e.g. directly from the nav terminal to the pumps and engines with max 1 junction box in between).

**Comment by CryIz** [comment]
Понятно, спасибо. Просто я хочу добиться полной реалистичности на этой субмарине. Всё равно спасибо.
Okay, thank you. I just want to achieve complete realism on this submarine. Thanks anyway.
