### ISSUE TITLE
Include icon for tooltip or container icon for contained items

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2222]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the new tooltips are nice, but it'd be nice to see the icon of either the first contained as a smaller icon over the large container icon - as to know what it might contain at a glance, or to have the item icon in the tooltip for each item.

Not suggesting add all the contained items to the container's own item icon, just one.

I just feel on the HUD these would be nice, if not minor improvements visually.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
