### ISSUE TITLE
[Feature Request] Functional piping and deeper pump customisation

### ISSUE THREAD

**Issue by box-admiral** [Regalis11/Barotrauma#2242]
We have pipes in the game, but they are purely aesthetic. Small pumps remove water rather slowly for a large room, and if multiple are used they start to overtake aesthetic design unless scaled down, which could be seen as illegitimate by sub designers. Large pumps are impractical to place in every room and have the same issues with scaling.

A system similar to the current hull-and-gap for moving water could be used for pipes, where a separate layer of hulls and gaps would move water into the ballasts or other water handling rooms for removal. A block similar to the duct block could be used as a pipe interface, dropping water into or taking water out of rooms as required between the submarine and the pipe hull planes. As balancing measures, the pipes would have a deterioration and condition component similar to most other installations in game and could be repaired with welding torches or broken with plasma cutters. To add risk to letting pipes deteriorate, water or even even enemies from small hammerhead spawn to husks or crawlers at minimum condition could appear, though hopefully with an auditory warning.

Edit because I forgot the second part of the title like an idiot, and some other things

- The ability to change pumping rate independent of power consumption
- If not already implemented, option to toggle power consumption of pump constant while on or proportional to set speed
- The option to disable or enable pumps from removing water from the sub, so in-room pumps could be used to assist the piping drainage system or remain as they currently are

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
