### ISSUE TITLE
[Campaign Rework] [Idea] [Design] Give smaller subs more path options in campaign

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2272]
You guys are reworking campaign soon, so here's a summary of an interesting idea I thought of to shake up campaign. I say "should" a lot in this FR like i'm the one making the demands, but as you know it's just a request.

Smaller subs are pretty weak on their own, with less tools, less storage, and less utility overall. Hypothetically, they can fit through smaller cracks in the ice and slip through icebergs slightly easier, but that's about it. Large subs far outweigh smaller subs in almost every aspect except in that they're harder to manage, and that feels more like a playercount problem than an actual gameplay feature.
Logically though, in Europa it would make sense that some small subs would be able to take more obscure shortcuts to locations through smaller holes in the ice that are less accomodating to large ships like the typhon.
Paths between destination nodes in the campaign map should have "sizes" that vary.
The game should have paths blocked off if your ship exceeds a certain size in dimensions, citing the cave from one outpost to another as too narrow. This would give small subs much more freedom to compensate for their lack of mass/ability. If you are frustrated with your inability to get somewhere without taking a masssive detour, **you could always buy/rent a new, smaller sub** if you're really dying to go somewhere. There should obviously always be at least one "huge" sized path so that some absolutely massive sub someone builds has room. **It would also be cool if map generation accounted for this, and scaled the cave path "radius" based on the previously mentioned map path size**. This would give smaller ships the ability to take the claustrohopbic shortcuts, but also have the ability to pick the more spacious detours if they wanted more room for juking monsters and so on.
As always, it's possible there's something I didn't think of, so if there's some critical flaw feel free to comment on it.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.

As for this particular issue, we'll be reworking the level generation as a part of the campaign update, and branching paths of varying sizes are on our todo list. :)
