### ISSUE TITLE
[Feature Request] Multi-item settings

### ISSUE THREAD

**Issue by box-admiral** [Regalis11/Barotrauma#2275]
Somewhat often the situation arises that multiple components requires a change in settings that are identical, such as multiple signal check components each with different output devices. Changing many components like this can be time consuming without something like a mouse-movement-capable macro which thankfully I have, but others may not.

While the setentityproperties command does exist, it does not work for settings such as signals because they are not entity properties. So two potential solutions could be if multiple items are selected, if a change is applied in the top right panel it is applied to any selected items that can accept that change such as signal check targets or true/false outpus, or a copy-paste feature that could be similar to the one found in Factorio. This is not a hugely important feature, but one that could save some time in submarine construction.

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/d1fcf6146a8d4df318a4311ed56320d437f4033f

The editing panel now applies property changes to all items in the selection if they share the same component. ex. selecting a search light and a light component and adjusting the light color will change them both because they both have the LightComponent which holds the light color property, or changing sprite color of walls since they are both structures.

<sub>Referencing issue https://github.com/Regalis11/Barotrauma-development/issues/224 "Sub editor multiselection editing"</sub>

**Comment by Rokvach** [comment]
No issues, closing.
