### ISSUE TITLE
Feedback on new Ruin Traps [Ongoing]

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2279]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Artifact Room Configuration:
![](https://cdn.discordapp.com/attachments/668819422919524352/677187337481879582/Capture.PNG)

Difficulty: 2/10
The new configuration is a simple red light green light game. The difficulty is further reduced by the easily accessible alien generator that anyone can yank out the power cell from.

Trap Room
![](https://cdn.discordapp.com/attachments/668819422919524352/677190883191291907/Capture.PNG)

Difficulty: 9/10 (or 0/10)
This room is a bit more fair than the previous version prior to 0.9.707, but the problem is that there is no possible way for players to weave through the two selected sensors (Trust me, I tried 20 times) unless they have some sort of TAS-like reflex to reposition their character's body to fit through. That aside, players aren't as likely to die as last time as I can just dive head first at full speed with scooter and suffer shocks until 25~50% of my HP bar remaining. The sensors will give the player a break when they hit a certain stun point.

That said, anyone with a plasma cutter will still do it the old way and just cut around the whole thing.

![](https://cdn.discordapp.com/attachments/668819422919524352/677195967048581145/Capture.PNG)

Difficulty: 0/10 (Even without a plasma cutter)
Nothing to say here, the gap is obvious.

![](https://cdn.discordapp.com/attachments/668819422919524352/677196510303354881/Capture.PNG)

Difficulty: 1/10
Stay low and you won't be shocked. Even if you did accidently triggered it, you'll probably be pushed to safety or your stun will get you out of it. I like the extremely short hallway to the artifact room, as it prevents cheesing.

![Capture](https://user-images.githubusercontent.com/5086682/74448011-3b6f8e80-4e48-11ea-9f60-eb587e6981dd.PNG)

Difficulty: 11/10
No way to get through this normally. Cheesing is required.

**Version**
0.9.707

**Additional information**
I'll post more when I see them.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
