### ISSUE TITLE
Additional submarine preview info

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#228]
The submarine selection menus should show a preview image of the submarines and some additional information about the submarine.

**Image**
The sub editor should automatically create a picture of the submarine during saving, but there could also be an option to edit it manually so people can put their MyAwesomeSubFleet logos and whatnot in the pic.

**Size**
The dimensions of the sub.

**Recommended crew size**
While this can already be included in the submarine description, asking for it during saving would encourage/force sub creators to include it.

**Required content package**
Useful for subs that require a non-vanilla content package and identifying outdated subs that were made using some older vanilla pack.

**Recommended crew experience**
Would give the players a rough idea about the complexity of the sub. Maybe a three-step rating along the lines of:

Beginner: Plenty of pre-placed items to minimize the need for fabricating more (more than enough ammo, medical stuff, tools, etc), automatized systems that make breaches and such easier to handle (auto-closing doors, water-activated pumps, reactor shutdown circuits, automated airlocks)...

Intermediate: The current vanilla subs would probably be in this category. Enough pre-placed supplies to get started (but not necessarily enough to take down a moloch) and being familiar with the gameplay mechanics and the usage of the vanilla devices/machines should be enough to maintain the sub.

Experienced: Subs with more exotic features or things that require more manual management than usual: multiple power grids, subs with such a high power consumption that the crew has to pay more attention to power management, more complex steering systems (e.g. having to select which ballasts/engines to use)...

**Comment by CryIz** [comment]
I just wanted to offer this. Even the outline to do :).

**Comment by NilanthAnimosus** [comment]
I like this, even to the point if there was a way to add even further additional information to it that could be skipped if the game did not contain such information, such as new fields that wouldn't cause issues if an unmodified game did not have the data to read from the save.

Though that's probably asking a bit much, I am very much interested by the above idea though. if this is going to be added - there should be better control over what a server uses based on the above information (Right now you cant even deny players from voting shuttles despite there is a shuttle flag through any option and hiding them from the lobby list likely causes issues).

If the above is being implemented I hope the values such as recommended crew size / crew experience / size and such can be preset values instead of free text - Although this sounds odd it would allow in the future for sorting / code based on it to adapt the saved features for sub sorting / denying sub voting and such based on server population and server preferences.
