### ISSUE TITLE
Transformation into Duffel Bag should probably not happen outside of the Sub?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2292]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I died in a ruin and another player came to bring me back. Before they even got my body out of the ruin, I became a Duffel Bag. This prevented him from continue using a scooter to return back to the sub.

Also since Duffel Bag doesn't appear on Sonar, it would be hard to find out where someone died outside when relying on sonar pings.

**Version**
0.9.708

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
