### ISSUE TITLE
[0.9.708] Bots with only melee weapons always retaliate when attacked

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2297]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So when a bot that has a melee weapon only is attacked, they will flee and use that melee weapon to retaliate against the player if they come close. If you put a gun in their inventory, they will always flee even if they have a melee weapon.

**Steps To Reproduce**
Attack a bot without gun
Attack a bot with gun

**Version**
~0.9.708

**Comment by Regalis11** [comment]
I think this may not be a bug, as far as I remember there's some kind of logic in place to prevent the bots from retaliating with unnecessary force when you inflict small amounts of damage on them.

Just tested this a bit and that seems to be the case: when I hit a bot who has a revolver with a wrench, they won't shoot me, but if I stab or shoot them, they will.

**Comment by Kaillera** [comment]
Well you can wrench them to death and they'll just flee even if they have a wrench and revolver on them too.

**Comment by itchyOwl** [comment]
It's intentional that the bot doesn't attack you if you do dmg less than 10% of the current health. So if you are on low health, using a something like a crowbar could also cause retaliation.

But I think I'll have to check it out.

**Comment by itchyOwl** [comment]
Actually the bots attacking the player when they only had melee weapon was a bug.

It's intentional that they don't attack the player, unless taking more damage than 10% of the current health. The reason here is that we don't want the bots to attack the players so easily. What we are actually planning to do, is to introduce a reputation system which guides the bots to decide whether or not the other crewmembers are acting weird/sneaky/hostile and react upon that based on what class they are. So security officers should basically try to arrest you first. It's been designed already, but not implemented yet.

So, at the moment its actually intentional that the bots basically let you almost beat them to death with wrench or crowbar.

**Comment by Kaillera** [comment]
Cool, so it was the other way around

**Comment by Rokvach** [comment]
No issues, closing.
