### ISSUE TITLE
Unstable Multiplayer - Rejoining game midround (before killdisconnect) prevents that person's character from receiving EXP for the remainder of the round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2298]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you rejoin a server before your character is killed due to disconnect time, your character is unable to receive any EXP.

**Steps To Reproduce**
Craft stuff
Verify you get Level Ups
Leave Server
Rejoin Server
Craft more stuff
You will not get EXP (You can check Save_CharacterData.xml too, not a single increase if you leave the server first thing instead and end the round)

**Version**
~0.9.708

**Additional Informations**
In this case I was playing Multiplayer Campaign and crafting Medical items. Most likely players that were kicked from excessive desync at the start suffers the same problem.

**Comment by 3e849f2e5c** [comment]
Should be fixed in [6741256](https://github.com/Regalis11/Barotrauma-development/commit/67412562836425cf822c46acf8eb2fe1240f32a2)

From my understanding this was caused because the client's CharacterInfo was created in NetLobbyScreen where their character is null but the server never set CharacterInfo.Character once "reattaching" the client to the character when reconnecting, preventing CharacterInfo.IncreaseSkillLevel from knowing who to give XP to.

**Comment by Rokvach** [comment]
No issues, closing.
