### ISSUE TITLE
(Suggestion) Traitor mission - husk cult slight change

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2308]
**Description**
As it is now, mission ends instantly with enough players infected. I argue it would be more fun for both players and traitor if the mission finished when enough players turned into husks. In current version, player can mass infect people very quickly and sometimes it even leads to confusion as to why the round ended so abruptly. Requiring players turning into husk would make the traitor think about getting rid of the antidotes and ABX, which often would not be on sub in large enough quantity so players would experience proper progressive crew epidemic, with one of the survivors being the traitor in some cases. In some cases people would see the infecting and traitor would have to infect and run away, maybe even from the sub in order to survive.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
