### ISSUE TITLE
[Unstable] [Feature Request(???)] Disable duffelization in settings?

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#2309]
Is it currently possible? I can't find it in serversettings.xml.

**Comment by Regalis11** [comment]
This is currently not possible, and I'm not quite sure if we should even allow it. The main purpose of the "duffelbagging" was to make it possible to delete dead bodies during a round while making sure their items don't get lost. This was mainly for performance reasons: during long rounds, there can be a ton of bodies inside the submarine, which tends to cause performance issues. If we allowed disabling the duffel bags, it'd either mean
1. A higher risk of losing the items the despawning character was carrying
2. That we'd have to come up with an alternative solution for making sure the items don't get lost
3. Disabling despawning altogether and accepting that some players will most likely have performance problems on servers that have disabled it.

I personally don't find any of those options very good. But we could consider ways to make it work. Can you elaborate a bit on why do you want to disable the bagging, is it causing some kind of issues, do you maybe prefer the realism of not having bodies magically disappear...?

**Comment by FamiliarBreakfast** [comment]
Honestly? I just like having tons of dead bodies littering the sub. I understand performance issues are a problem, and I get that this is an easy solution, but I feel it ruins a lot of the game atmosphere. Plus, I always enjoyed the fun of setting up an elaborate framing job, but now that's sorta impossible.

As well, actual dead corpses could have a place in the future. I've always thought the medical system could use improvement, especially psychosis, and one way I think that could be improved is with dead bodies making your character go insane (slowly).
I won't go into detail with my ideas right now, but you can read more about them [here](https://steamcommunity.com/app/602960/discussions/2/1751268425426970169/) and [here](https://steamcommunity.com/app/602960/discussions/2/2952595757894673242/) (I'm the last response).

Finally, I think a way to improve performance could be to 'freeze' corpses when they aren't being moved, basically lock their current pose and convert them to a single intangible object until someone grabs them again.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
