### ISSUE TITLE
Unstable - Berilia - Strange shadows and sprite depths on guns and fins

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2317]
**Description**
Berilia guns have strange black spots at them and sometimes go behind fin sprites. Fin sprites them selves have strange shadows on them, as can be seen on the picture.

**Steps To Reproduce**
-Play Berilia
-Check all the guns

**Version**
Unstable 
**Additional information**
This gun's barell can go behind the fin, which confused me when I was fighting off raptros from engine.
![image](https://user-images.githubusercontent.com/59519434/74613725-0b0e4580-5111-11ea-9a33-810e08f37947.png)

**Comment by danielasteljoki** [comment]
Fixed in 0c5b0a7

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Regalis11** [comment]
There's still a couple of spots where the lighting looks off. I think this is something we should fix on the code side, because the lighting behaves differently in the sub editor than it does in-game.
![berilia](https://user-images.githubusercontent.com/14351070/79242565-2aa9bc00-7e7d-11ea-9e95-5e142ca6ae9b.png)

**Comment by Rokvach** [comment]
This isn't a issue anymore
