### ISSUE TITLE
[Bug] [Unstable] [Mapgen] "Height" mapgen parameter cuts off small tunnels

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2339]
![2020-02-21-080323_298x219_scrot](https://user-images.githubusercontent.com/47284081/75040646-a6404b80-5480-11ea-8894-fe6543489b34.png)
It would appear that the height parameter cuts off tunnels that branch off of the main path. Very inconvenient if you don't want holes in your walls.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.

**Comment by hubismal** [comment]
not entirely sure how this constitues as a feature rq but i understand the issue tracker is pretty cluttered.
