### ISSUE TITLE
Navigation Terminal and Status Terminal doesn't draw what my sub looks like.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2345]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My sub is designed to look like the letter H, but the navigation and status terminal draws it as a box.
![Capture](https://user-images.githubusercontent.com/5086682/75085400-cc083780-54f6-11ea-8dc6-a31d4430b948.PNG)

**Comment by hubismal** [comment]
seconding this. it would be nice if the visual representation looked like an outline of the sub physicsbody.

**Comment by Regalis11** [comment]
This is actually a little more difficult to implement than it may seem, calculating the outline of a concave shape consisting of multiple polygons is not trivial. Since you can already see the shape of the sub based on the hulls, I personally I don't think this is worth implementing at least for the time being.
