### ISSUE TITLE
[Bug... Reporting?] [0.9.7.0] Ingame bug options broken.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2346]
The "Technical Help" button is just dead. It doesn't do anything period, even ask if you want to open a link in your browser.
The Report Bug button leads you to the github template instead of the new handy-dandy bug report firebot forum you guys made for the unstable branch.

**Comment by Regalis11** [comment]
The "Technical Help" button should open a Steam overlay; were you logged in to Steam when testing this?

The report bug button leading to the github template is actually intentional. There's 2 reasons we did this: to make it more clear which reports are coming from the Unstable version, and to prevent a flood of duplicate and low quality tickets which would probably happen if every single player in the public version had quick and easy access to the firebot form.
