### ISSUE TITLE
[0.9.7] Driving off the path in Cold Cavern is Risk Free

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2349]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you find a opening somewhere in Cold Cavern biome and drive out to avoid the long up and down path, aliens do not spawn off the path making it risk free to the next station.

**Version**
0.9.7

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.

This particular issue will be addressed - once we add some more life to the Abyss the path below the level might become even more dangerous than the main path. :)
