### ISSUE TITLE
[Feature Request] No dropped letter during chat box communication inside submarine and docked shuttles

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2358]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of the quirk in big submarine builds are that players are not able to read each other from the opposite ends of the submarine in the chat box, but microphone players can be heard perfectly at maximum distance of the headset.

I propose that players inside the submarine and shuttles docked to the main submarine should not drop any letters for them.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
