### ISSUE TITLE
Stairs collider not changing with object scale

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2359]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Changing size of objects like stairs and shells don't have their collision box adjusted to their size

**Steps To Reproduce**
Changing scale of stairs won't work in-game, scaling down front parts will make difficult to select on sub editor after a certain point.

**Version**
It has been like this since release. I've used sub editor on Linux too and it had same issue, im using Windows now.

**Comment by Kaillera** [comment]
#2354 I guess is related to this too

**Comment by SenhorPatolino** [comment]
#2354 Yep, it is same, sorry didnt find while looking for similar problems

**Comment by FLundin** [comment]
Don't forget labels. I'm sorry if I am overbearing but I really like to see this fixed.

**Comment by FLundin** [comment]
Would this be able to be fixed for the next update? I kinda lost my momentum since the stair scale bug was encountered and haven't played baro for a while. I would like to finish my sub but as i cant walk around in the sub to test it out... i kinda lost motivation. It kinda bothered me that the bug was miss labeld to be the same as another bug and that bug got fixed instead of this one...
Main reason why I bought the game was for the sub editor, its what I do when i cant find good public servers (and that 90% of the time) so.. yeah.. :/

**Comment by FLundin** [comment]
Here are a few teasers.
https://steamuserimages-a.akamaihd.net/ugc/1005937231172315224/FAE42664E539167A7C690143344450DF68CE430B/
https://steamuserimages-a.akamaihd.net/ugc/1005937231172318371/96D02B916B5216B0D481EF68FE0FA7AD6166E05D/
 https://steamuserimages-a.akamaihd.net/ugc/1005937231172316801/CC44357116D3B33CEB2A36C1709252A2F47F0D58/

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/597d2a6bed864acca9b3a3ac4c44b1c66d31d48a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by FLundin** [comment]
<3
