### ISSUE TITLE
[Modding] [Feature Request] [Issue] Allow Light Sprites to wrap

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2370]
Very specific feature request but I wouldn't assume it would be that hard to do(?).

Right now you can sort of make a resizable light by doing this with an item:
```
<Item
  name="Light Strip"
  identifier="lightstrip"
  tags=""
  resizevertical="true">
	<sprite texture="Content/Items/Electricity/lamp.png" sourcerect="0,48,48,16" depth="0.68" premultiplyalpha="false" origin="0.5,0.5" />
	<LightComponent lightcolor="1.0,1.0,1.0,1.0" range="0" IsOn="true" castlights="false" resizevertical="true">
      <LightTexture texture="Content/Lights/pointlight_bounce.png" origin="0.5,0.5" resizevertical="true"/>
      <sprite texture="Content/Items/Electricity/lamp.png" sourcerect="0,48,48,16" alpha="1.0" resizevertical="true"/>
    </LightComponent>
</Item>
```
...basically give both the lightcomponent and the item itself resizable properties. The sprite for the lightcomponent (not the lightsprite, the "bright" sprite for the light source) doesn't actually scale though, which kind of screws up my item here. 
![2020-02-26-212621_323x210_scrot](https://user-images.githubusercontent.com/47284081/75409696-14509c80-58df-11ea-9de2-e15683912079.png)

It would be nice if lightcomponents had wrapping sprites to make fully scalable "light up" items.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
