### ISSUE TITLE
[0.9.7.1] Ruins seems to not contain artifacts in the holder more than 50% of the times

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2379]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For some reasons it seems like more than 50% of the ruins I go into (legitimately) doesn't hold an artifact in the holder.

**Version**
0.9.7.1

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
