### ISSUE TITLE
Weird desync and complete disconnection.

### ISSUE THREAD

**Issue by Applejakerie** [Regalis11/Barotrauma#239]
A group of us are playing constantly lately - it's a great game. I've been hosting locally and we've been having an issue where at random (20-60 minutes in usually) everyone is desynced and then disconnected from me as the host. They also can't get back in until I rehost. I saw a similar issue at #219, just wondering if there's a workaround, or if I'm doing something wrong and this shouldn't be happening? Just let me know if there's anything I can provide that would be useful.

Looking forward to future updates, especially for c77c598 and 567b440. 👍

**Comment by CryIz** [comment]
Есть модификация для сервера позволяющая ограничить к-во существ. Сам ею пользуюсь и де-синк уже давным-давно не видел. Если нет мода, то отключи кравлеров, мантисов, Хасков.

There is a modification for the server allows you to limit the number of creatures. Myself use it and de-sink has long since not seen. If not fashion, then disconnect crawlers, mantis, Husk.

**Comment by Applejakerie** [comment]
https://undertowgames.com/forum/viewtopic.php?f=20&t=7451

I've tried using this mod but it's not gone great, If I have to I will try removing some of the smaller creatures but it's always fun when one gets inside. 😄 What number of creatures do you limit it to yourself? From what I've seen this desync issue is not based on bandwidth limits, I have more than enough myself to host and plenty are in the same situation.

Unfortunately with this mod, I have to run two instances of the game, I'm not sure if that's suitable. I haven't got a spare computer to be acting as host and I haven't found any dedicated Baro servers aside for usual VPS with no pre-configs.

**Comment by CryIz** [comment]
Я использую ограничение в 4 существа (хотя их всё равно больше, но de-sync нет). Хост делаю через свой ноутбук и также играю на нём.
I use a limit of 4 creatures (although they still do, but no desync). The host is doing through your laptop and also play it.

**Comment by Applejakerie** [comment]
Thanks, I will try a little more than 4, would like to see a few smaller creatures still as they're good fun when they're latched onto the ship. Thanks again for the replies.

> Спасибо, я попробую немного больше, чем 4, хотелось бы видеть еще несколько небольших существ, так как они весело проводят время, когда они защелкиваются на корабле. Еще раз спасибо за ответы.

**Comment by Applejakerie** [comment]
To limit creature spawns, which is it I'm changing? These?

>     CreatureLimitRespawns="False"
>     CreatureMaxRespawns="1"

**Comment by CryIz** [comment]
Да, это. Где "CreatureLimitRespawns" нужно выставить "True", а где "1" - к-во существ. У меня стоит 4.
Yes, it is. Where "CreatureLimitRespawns" you need to set "True", where "1" is the number of creatures. I have 4.

**Comment by NilanthAnimosus** [comment]
As a note (And the creator of that modification) I have updated it and you no longer need to do any limitation on the creature respawning (Though this would have had no effect and should have been to turn off the respawning entirely, it did have the ffect of potentially reducing the root cause).

The disconnections being referred to here should have been fixed from commit b36d3fc70ee80f9ece36e9310d6c6441d3678ac0 but since there could be other causes give my updated server modification a try which now properly contains that fix (I made a mistake which did not fix it correctly).

**Comment by Regalis11** [comment]
Assuming this was caused by monster respawning and considering it fixed. There's a bunch more bugs that are causing desync disconnects but we should have separate issues for those.
