### ISSUE TITLE
Lighting/Visibility through shell walls

### ISSUE THREAD

**Issue by mikeydbrad** [Regalis11/Barotrauma#2393]
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I previously made my ship starting somewhere right after Barotrauma was added to Steam, and have been updating it as new updates come in. The most recent update (Silky Smooth update) has resulted in the following visibility/LOS glitches happen in certain areas of my ship: (the slim bits of light up area that are outside the ship and should not be visible)
https://i.imgur.com/NaSAHoB.png
https://i.imgur.com/JUjCvv8.png
https://i.imgur.com/J96BKZs.jpg

**Steps To Reproduce**
Currently unknown - might just be an issue with an old version of the ship updating to a new update.

**Version**
Windows, Silky Smooth Update

**Additional information**
I tried working on this problem on the Barotrauma discord with user @Halfdeadkiller. My id is @mikey bimley (Message history starts here: https://discordapp.com/channels/103209684680323072/427654262453960724/684943352776491034)

- Replacing the walls with Inside Walls fixes the problem perfectly.
- Trying to make the ship a sub-assembly and then reimporting it to a new ship does not solve the problem
- Removing parts of my ship except the areas next to the glitch result in the issue dissapearing

[Bimmer 99000.zip](https://github.com/Regalis11/Barotrauma/files/4291097/Bimmer.99000.zip)

**Comment by mikey** [comment]
Wrong @mikey @mikeydbrad

**Comment by mikeydbrad** [comment]
Important thing to mention that Halfdeadkiller on discord discovered: https://i.imgur.com/Lw7vej1.png

**Comment by mikeydbrad** [comment]
I was able to reproduce at least one part of the glitch - the Shell A Cap 0 Deg piece not working properly.

https://i.imgur.com/K1SqaV5.png

**Comment by NilanthAnimosus** [comment]
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/cd25531824ed25a6c9c237ce3357e07a2cb41542

Unable to find any issues with the new LOS mechanics similar to the above, Tried both the submarine and recreating the testing environment in the image as well without issues. Since there doesn't seem to be any issues and the code has changed enough that this is likely to be fixed now closing unless new issues related to this are found.
