### ISSUE TITLE
Lights and Lamps does not experiences short circuitry flicker on Relay Components

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2414]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Lights and Lamps do not experience short circuitry flicker on Relay Components

**Version**
~0.9.7.1

**Comment by Regalis11** [comment]
I suspect that this happens when the power is dropping in the main grid, but there's still enough power to keep the light(s) connected to the relay on. 

I tried reproducing this with 3 different setups (connecting a lamp to a battery through a relay, to the reactor through a relay, and to the power grid in Humpback), and couldn't spot any issues; in all cases the light starts flickering as soon as the power going through the relay is less than 50% of the load.

**Comment by Kaillera** [comment]
Relay components seems to get their power faster than junction boxes. If you have all the lights and lamps hook up to a junction box, you'll see the flicker when the output drops, but relays doesn't make them flicker during near power outage as much as junctions.

**Comment by Regalis11** [comment]
The relays only account for the load of the items after the relay, so this seems to be working as intended.
