### ISSUE TITLE
Character-specific orientation lock

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#2418]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unsure how this happened, but when I played campaign, one of the characters had their orientation locked, and couldn't turn around. Bots could navigate around just fine, only I couldn't, but only on this specific character. Switching to other characters worked fine. Video below.
https://www.youtube.com/watch?v=EbMCw1ibFTY&feature=youtu.be

**Version**
Win 10, Barotrauma version 0.9.7.1

**Comment by ekqvist** [comment]
Were you using the command interface before this happened? There is a known issue where you can get character stuck facing a certain direction by opening the command interface and switching to another character while the interface is open. Basically, the **controlled** character's orientation is locked when you open the interface, and the orientation is unlocked for the **controlled** character when you close the interface.

I believe there might be another cause for a similar bug as well, but so far there are no known steps to reproduce it in other ways. If it was caused what I described above, the workaround should be to open and close the command interface while controlling the stuck character. I have fixed the issue with Regalis11/Barotrauma-development@6453ea5 (private repo) and it _should_ be included in the  next patch.

If it was caused by something else, any steps to reproduce the issue would be helpful.

**Comment by OverwatchVoice** [comment]
This was most likely the case. I was trying to use the command menu before.
