### ISSUE TITLE
BUG REPORT: Extreme lag while perfmorming a dock

### ISSUE THREAD

**Issue by georgearredondo** [Regalis11/Barotrauma#2428]
Hello:

I created a sub, but it has a problem. The problem is that when i try to dock it, the lag increase to extreme levels to every players in the sub. We try everything to solve the problem but there is no use. 
So i want to report it as a bug (the sub is attached to this message)
[The Freaker 2.6.zip](https://github.com/Regalis11/Barotrauma/files/4325979/The.Freaker.2.6.zip)

**Comment by Kaillera** [comment]
i think this and #2356 are the same.

**Comment by Regalis11** [comment]
This seems to be caused by the huge number of very long-range shadow-casting lights in the submarine. As mentioned in the warning message that pops up when saving the sub, you should disable shadow-casting on lights that don't absolutely need to cast shadows, and reduce the ranges of the lights wherever possible.
