### ISSUE TITLE
Can't hold a flashlight with hand unless head slot already has an item

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2441]
- [x] I have searched the issue tracker to check if the issue has already been reported.

No matter what, I can't figure out how to hold a flashlight with my hand; it always goes into my mouth unless I have something on my face already. Even clicking that tiny 'equip' bar causes it to go to my mouth.

**Comment by 3e849f2e5c** [comment]
Fixed in [acfdc61](https://github.com/Regalis11/Barotrauma-development/commit/acfdc61b9fcfa3ea142932a7a63ebbb13037c6cc)

Items now prioritize the hand slot first before trying to put them into the equipment slots, tried a handful of items and it doesn't seem to have broken the behavior of other items.

**Comment by Rokvach** [comment]
No issues, closing.
