### ISSUE TITLE
Campaign Buy Menu Idea - Manifest of Submarine Inventory + Additional Features

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#245]
Essentially, either like the submarine preview or as an addition to the buy menu itself - Give the lobby screen information on the items a submarine has left in its inventory from its last game session.

I imagine there could be a number of ways to do this, either to add a bracket near the item names to state the stock of the item on the submarine, or to add a separate tab to show a short, comprehensive list of the stock (Perhaps even items that cannot be purchased in the menu).

If a separate menu is used, perhaps the average condition of such items too, and/or offer to "Refill" (Replace) those items.

This could also include an overview of the submarines power storage, and to refill them at a cost, Bonus if they could be given separate tags to allow for different groups of power items for recharging from such a menu (Such as a default group, then a custom main / backup group a sub designer specified).

This way players can identify what they are lacking, what may be a good idea to buy, and potentially allow for battery powered submarines to recharge while not making it free. Anything bought (Refills and such) could simply be applied on game start once the save is loaded, so it is more of a count or toggle to refill which could be proportionate to the cost of the item. (IE. 50% of a steel bar would take 50% of it's cost to replenish).

If it's not a separate menu, it could be in smaller GUI additions be integrated into the existing buy menu, or at least to have the manifest itself included for a rough idea.

**Comment by Applejakerie** [comment]
And lower the stock costs/raise the mission rewards. There's no balance. 👌

**Comment by NilanthAnimosus** [comment]
I consider the balance a separate issue but is still worth considering, while this is more new mechanics and quality of life.

The costs/mission rewards are more of an issue due to the game being excessively lossy in resources with the lack of character persistence / fuel usage rates and I believe that's a separate issue, and mods can still rebalance the game.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
