### ISSUE TITLE
Allow different char file selections for modders + Multiple loadouts for jobs and jobless Creatures.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#246]
I know its not exactly a feature for standard Barotrauma (Or at least I don't see Barotrauma having additional racial selection/char files and I quite like how it is currently), but I think modders in general being able to define which character file to use for a spawned player (And their charhusk counterpart) may be interesting.

I think tying it to the job at first may be a simple / better idea if this would actually be added. This way modders could add playable husk-like characters, different stats like playing the morbidly obese human (Just a joke) or a robot-like / cyborg with more fixed joints.

Additionally (If the previous is not considered good/wanted that's fine) adding the ability of multiple "loadouts" where one is selected at random (Or even by a choice) for the same job may be interesting. Additionally having the ability for a character file itself to have "loadouts" where the job start items override it (If its playable like a human) otherwise to give the character a random loadout such as a husk spawning with a clean diving suit set or a damaged set / one with and without a helmet and such.

Essentially granting other humanoids that are not playable a potential random inventory. this could also be given to other creatures as a form of harvesting supplies from them by granting inventory access to none-humanoids once their dead only, while granting inventory access to specific humanoids while alive like husks and humans.

I think this should allow for additional sources of resources and methods for modders, potentially new mechanics for the games future (Such as butchering), but for now grants more variability and realistic behaviour for the same characters.

I do not think however a none-humanoid should be "Grabbed" or if they are grabbed, to assign a specific points on the limbs and movement speed for dragging the creature (Though their sort of too large).

As a note - I understand the game has an entity limitation that is worth mentioning and not all characters should be filled with inventories of various items. Either to spawn creatures that do not wear items loadout/inventory only once checked (And just the once) as well as not changing the current assets of the game to add more items where unneeded makes sense - but this is more of a concept/idea for modders and future mechanics.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
