### ISSUE TITLE
[0.9.801] Bots - Doesn't Idle patrol when nothing to do

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2469]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots in 0.9.801 when have nothing to do during certain orders like fix leaks/repair items/fight hostile:

-Doesn't Patrol
-Doesn't take off Suit/Diving Mask after accomplishing task. Kept on until new task.
-Stuck walking/running in one direction until new task.

**Version**
0.9.801

**Comment by Rokvach** [comment]
Reported as still happening on the 0.9.9.0 Unstable build, not 100% sure if this made it to the build

**Comment by Regalis11** [comment]
This was fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ee8dbc, but looks like the changes got lost somewhere along the way in the merges (https://github.com/Regalis11/Barotrauma-development/commit/f9758eb seems to be the culprit). The changes have now been readded in dev, so this should be fixed for the next unstable build.

**Comment by Rokvach** [comment]
Didn't notice any issues with the AI this time around when playing, closing.
