### ISSUE TITLE
[0.9.8.0] Lack of small enemies at the two/three rings closest to The Center

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2472]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was hovering around the big egg in the center today, and found the 2 or 3 rings closest to the center has little to none small enemies like mudraptors and crawlers. To be honest I found those add more intensity than hammerheads and threshers which are all over in these rings.

**Version**
~0.9.801

**Comment by Ant1V1RU5** [comment]
The very first time me and my friends were going to the center, we were afraid about what we could possibly fight.

The big ennemies add certainly a lot of stress on new players, but when you know how to fight them they become less threatful.

We know that the center is the most dangerous place to be and to fight. But my crew and I see the fight differently. Moloch and bigger threath are like boss battles, but with an free open arena, and the lack of smaller "mobs" make it easier for us to take down our target, or even worse just past them.

What Kaillera is speaking about is interesting, because if we have to make hard choices during this "boss battle" this you will make it more engaging to play, more intense.

I know my words are weird, english is not my main language, but i will give an example to make it easier :

Lets say we are fight a Hammerhead Matriarch with two or three regular Hammerhead. BUT there is a big swarm of mudraptor breaching the hull (let's say 15). In this situation the best way should be to retreat (in my opinion). But how the crew should react ? They can : 1-Try to repell the mudraptor invasion or 2-Making so the sub is already out of range of the Hammerheads. The most fun scenario (in my opinion) in when people are like "Oh my god we are totally suprised by this attack captain what should we do ?"

In this situation the best we can have is to not know what is the bast approach. We should get swarmed, feel inferior. we are on THEIR territory THEY make the rules.

But sadly, yes we only have big monster in the inner circle. a lot of small foe + some huge one should be an amazing (and deadly) situtation.

Again i apologize for my bad english.
