### ISSUE TITLE
[0.9.7.1] Pumps do not properly receive signal on set_targetlevel, when not output from a Navigation Terminal.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#2473]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pumps don't seem to receive signal on set_targetlevel properly from components that are not the Nav Terminal. They act oddly, in some cases swapping from -100 to 100 when pressing a button to output 0 to the pump.

**Steps To Reproduce**
I'm attaching a zip with a submarine in it, with two sets of manual ballast system. The Type 7 is from the Type VIIS submarine, and this system has worked for years, and only recently broke a few months ago. The HalfdeadKiller system was built today using different logic, but still fails to operate as expected.

**Version**
0.9.7.1 revision 6ec75fa2a. Windows 10 1903 build 18362.720

**Additional information**
Set_targetlevel appears to function properly when the signal is output from a Memory Component, or a signal checker using a Relay's state_out as it's signal_in.

[a.Type7Ballast.sub.zip](https://github.com/Regalis11/Barotrauma/files/4361471/a.Type7Ballast.sub.zip)

**Comment by Regalis11** [comment]
This happened because the pumps would only stay in the locked "automatic control" state for a moment after receiving the set_targetlevel signal. This isn't a problem with the nav terminals which send a continuous signal, but makes this sort of manual systems behave unexpectedly.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5bcc066d2004f2edd4963eaa4e06a91def67918d

**Comment by Rokvach** [comment]
No issues, closing.
