### ISSUE TITLE
Manual Reactor Output/Load Numbers spazzes when Battery is On

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2496]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a Battery is on alongside with a Reactor on Manual, the readings on the Reactor spazzes out. The Output number is changing up and down even though you're outputting constant amount of power.

**Version**
~0.9.8.0

**Comment by thegrb93** [comment]
The output of battery will change depending on the load in this case.

**Comment by Kaillera** [comment]
> The output of battery will change depending on the load in this case. Afaik that is normal behavior.

When you're looking at the reactor, the reactor output number should be just from the reactor is what I am getting at. You can already see the combined output from junction boxes.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this. Tested with 2 different setups: connecting the battery directly to the reactor and connecting it through a junction box. In both cases the output and load seem to be correct and stable.

**Comment by Kaillera** [comment]
Run the reactor on manual and provide less than 40% of the load. You'll start seeing the output spike random numbers.

**Comment by Regalis11** [comment]
Still couldn't get it to happen, the output is perfectly stable:
![aswegfaerg](https://user-images.githubusercontent.com/14351070/79447179-264de200-7fe8-11ea-8976-d8801372c359.png)

How exactly have you connected the battery to the reactor? I tried connecting both power_out and power_in to a junction box, and directly to the reactor, and couldn't find any issues with either setup.

**Comment by Kaillera** [comment]
let me go grab my recorder

**Comment by Kaillera** [comment]
Looks like it is fixed in unstable somewhere.

**Comment by Kaillera** [comment]
https://www.youtube.com/watch?v=7KjgjQtFOB4

Was able to get it to happen around the 2 minute mark.

**Comment by Kaillera** [comment]
Was able to get it to happen in unstable too.
https://youtu.be/9qp9zplADcQ

**Comment by Regalis11** [comment]
Thanks! I think what's happening here is that the load of the battery fluctuates a bit according to the voltage of the grid (i.e. the recharge speed changes according to how much power there's available to recharge the battery). The output fluctuates as well, because as long as you're close enough to the optimal fission/turbine rate, the output is automatically set to match the load (how close is "close enough" depends on the character's skill level).

I wouldn't consider this a bug; or at least it's such an insignificant issue that I don't think it's necessary to fix.
