### ISSUE TITLE
Mac port

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#25]

**Comment by juanjp600** [comment]
After testing a little bit with @CommanderMark we found that the Linux build almost works. EFX seems to be missing/not working, which could be a problem with OpenTK or OSX itself. Since we need to rewrite the audio classes anyway, I'll consider using https://github.com/flibitijibibo/OpenAL-CS to see if we can fix this, among other issues.

**Comment by juanjp600** [comment]
https://github.com/Regalis11/Barotrauma/tree/audio-rewrite seems to be fully functional on MacOS.

Now we just need to solve some scaling issues on retina displays and it'll be basically done.

**Comment by CommanderMark** [comment]
TODO (just writing this for myself):
[ ] - Make Fullscreen act like Borderless Windowed on Mac. Normal fullscreen breaks on Mac.
[ ] - Test if the game can run on Sierra.
