### ISSUE TITLE
[0.9.9.0] Anaparalyzant is too weak on onFailure.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2502]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Anaparalyzant onFailure is too weak, almost by 10 times as weak than success.

**Version**
0.9.9.0

**Comment by itchyOwl** [comment]
I don't think anaparalyzant is too weak in general, but it's possible that it's too harsh for failed attempts. @ezjamsen or @danielasteljoki should probably tune it so that it's on line with the other medicines. But the idea there was that it should be more likely that it would cause the psychosis. And the rationale behind psychosis was that you shouldn't be inclined to _overuse_ the anaparalyzant for achieving resistance against the paralysis.

**Comment by ezjamsen** [comment]
I've increased the resistance on failure to 250 (vs. 800 on success), increased psychosis from 10 to 20, and apply the effects over 20 seconds to make it less instantly useful.

**Comment by Kaillera** [comment]
[0.9.901] I think it felt just right,

**Comment by Rokvach** [comment]
No issues here, closing.
