### ISSUE TITLE
[0.9.9.0] Leucocytes are OP

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2519]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One sting from a cell is enough to send you to a coma once you hit that point without an antidote. Currently, the antidote takes a ridiculously long time to create.

**Version**
0.9.9.0

**Comment by itchyOwl** [comment]
It's intentional that paralysis is very powerful and you need to think a bit before encountering the Thalamus.

a) First scenario: You are properly prepared. Have an underwaterscooter and enough ammunition. You can, and probably should, have the antidote (anaparalyzant) in the inventory when you are planning to take down a Thalamus. The burn damage is 10x now, so in the next update, also test the plasma cutter or  welding tool.

b) Second scenario: You are not prepared and encounter the Thalamus either without previous knowledge or you are taken by surprise by it. Here you need to play it well to actually be able to kill the thing, but it should also be possible to just escape (or retreat for a while). Don't get the paralysis, keep the distance to the cells an kill the spawner organs. If you do get the paralysis, you might need another character to rescue you. If you have the underwater scooter and don't have the antidote, retreat to the sub and let the other characters handle the situation. They can retrieve ingredients (paralyxant) from the dead Leucocytes and use them to produce the antidote (we could probably reduce the time to fabricate it thought). The antidote can also be used as a pre-emptive protection for the paralysis.

I'm not done with the Leucocytes yet and I would be hesitant to nerf the paralysis affliction or boost the resistance. At least for now.

**Comment by Kaillera** [comment]
I've already reached Scenario 1 status on a consistent basis. There was just the issues of cells spawning ontop of players randomly which Regalis fixed.

**Comment by itchyOwl** [comment]
If it doesn't, thats a bug. But let's re-evaluate this when the Leucolytes are done.

**Comment by Kaillera** [comment]
[0.9.901]
I am pretty happy that MedCab starts with a Anaparalyzant in case you're forced into a Carrier. I was ecstatic about finding a decent amount of Anapralyzant in some wreck's medical bays. With that solved, I found a new issue.

A single Leucocyte was able to put me into critical health within 5 seconds. It was able to stun lock me.

Leucocytes are also very hard to hit with a melee weapon when they're ontop of you.

If it wasn't that, in a low frame rate situation, it was extremely hard to hit them with guns as well.

**Comment by Rokvach** [comment]
They are a lot less OP, might still need some balance but not enough to keep this ticket open. Closing.
