### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2537]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Higher memory usages than it used to be, reaching more than 1GB only on a empty sub editor file. Makes almost impossible to use other programs while playing and seems to be one of the causes of the perfomance drop that people reported on this version.

**Version**
0.9.9.0 on Windows.

![image](https://user-images.githubusercontent.com/61413244/77883943-7d0e9a00-723a-11ea-8d77-101ae076a350.png)

**Comment by thegrb93** [comment]
Running out of ram is sure to decrease performance. You should get more ram.

**Comment by SenhorPatolino** [comment]
> Running out of ram is sure to decrease performance. You should get more ram.

Correct, but im pretty sure it wasnt supposed to get that much memory, mainly when im not even playing and it was a empty file on sub editor.
I never really checked the memory usage on other versions but i assure it wasnt that high right on start

**Comment by Regalis11** [comment]
The sub editor does require quite a bit of memory, because it initializes all the item/structure prefabs. Going over 1GB is completely normal, and happened even before the wreck items/structures were added.

There is definitely still a lot of optimization to be done (in particular merging some of the new wreck atlases), but I'm afraid even after those optimizations you are going to run into problems with only 2 GB of ram.

**Comment by SenhorPatolino** [comment]
Actually my PC has 4gb of ram, Windows 10 is just evil by taking half of my memory

**Comment by MarkTrolic** [comment]
i have a 16 GB RAM gaming rig, when i installed some mods I was hit with a rare error "a new guard page for the stack cannot be created" which from what I've searched, it means the game is drawing more memory than it can hold... I have no idea how to fix this.
