### ISSUE TITLE
Ragdoll getting stuck on stairways

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2552]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to drag stunned players nearly impossible around staircases.
https://streamable.com/qqkjn

**Version**
0.9.8.0

**Comment by hubismal** [comment]
Seconding this, i'm having trouble walking through wrecked staircases for some reason.

**Comment by Regalis11** [comment]
Fixed the dragging in https://github.com/Regalis11/Barotrauma-development/commit/4e439e07d6651a25d2e6ad92d4706c4e6e49f5fd

Couldn't see spot any issues with wrecked staircases though. @hubismal I'm assuming the issue is in some custom sub, because afaik we don't have any staircases in any of the vanilla wrecks. Could it be that the staircase is placed incorrectly somehow (start/end of the staircase not aligned with the floor)?

**Comment by Rokvach** [comment]
I tested the dragging and its working, if there is no further issues this ticket can be closed.
