### ISSUE TITLE
Error spam after multiple mudraptors eat the same body of a player

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2575]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Looks like mudraptors ate someone and then error messages appear in console.
https://streamable.com/tdf2eu

**Version**
Windows 0.9.8.0

**Comment by Regalis11** [comment]
This should've been fixed in https://github.com/Regalis11/Barotrauma-development/commit/b780910f, but looks like the fix is not present in this build. Which is strange; the line numbers in the stack trace don't seem to match the current release version, nor the version before that commit.  Did this happen in the normal, non-unstable Steam version?

**Comment by thegrb93** [comment]
Yeah normal non-unstable. It's dated at 3-31-20 (I think 0.9.8.0 was out by then?). If my version is wrong then yeah maybe its already fixed.

**Comment by Regalis11** [comment]
0.9.8.0 was released on 3-31-20, so I'm suspecting this might've happened in 0.9.7.0 before you updated.

**Comment by thegrb93** [comment]
The version I played before 0.9.8.0 was 0.9.7.1. If the line numbers match up with that then I'd say you're right.

**Comment by Regalis11** [comment]
It does seem to match the line numbers in 0.9.7.1, so I'll close this and reopen if the issue still resurfaces.
