### ISSUE TITLE
Job preferences a little finicky still

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2584]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Engineer class was full. My preferences were 1. Engineer, 2. Medic. Another player was 1. Medic. I got assigned medic, but the other player got assigned assistant. You would expect other player to get medic since he prefers it more.

I'm guessing players are just picked at random and get whatever available job they prefer. Since I got medic first and made it full, he couldn't get it. I don't know for sure, but we've been having a lot of campaigns where people don't get what they signed up for.

**Version**
Windows 0.9.8.0

**Comment by itchyOwl** [comment]
Attempted to fix it in Regalis11/Barotrauma-development@9fbe95e, but I'm not sure I got it right.

I think the main issue was that the clients were looped through one by one so that all their preferences were evaluated at once before taking the preferences of other clients into account. Therefore, if the first client in line had some preference for job X, he would get it no matter if any other after him had a stronger preference. I changed this so that the preferences are now evaluated from top down horizontally so that we first check the first preference of every client, then second, and the the third.

For captains the logic was a bit different, but there were some issues with it too that I tried to solve as well. I think it would be better if giving no preference would mean "anything goes", but currently if you don't give any preferences, a random preference is created instead.

**Comment by Rokvach** [comment]
In which branch was this fixed in? It seems the reference link doesn't work anymore, shows 404.

**Comment by itchyOwl** [comment]
Dev: Regalis11/Barotrauma-development@5991e1d. Perhaps I posted a wrong link there. It's not on the release/unstable yet.

**Comment by Rokvach** [comment]
Tested, haven't noticed any issues with this. Closing.
