### ISSUE TITLE
Crash - Saving a Submarine with a Spacebar at the end

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2607]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4461134/crashreport.log)

**Version**
~0.9.903

**Comment by Regalis11** [comment]
I unfortunately wasn't able to reproduce this. The space at the end doesn't seem to make a difference, and based on the crash report this appears to be related to saving the preview image, not the submarine's file name. I added exception handling to saving the preview image in https://github.com/Regalis11/Barotrauma-development/commit/12d8d657d1c1e9493a4b9e66674980a82f23de47, so this should no longer crash the game, but the underlying issue is still not fixed.

**Comment by Kaillera** [comment]
I tried saving a "typhon" as "typhon " and had this crash.

**Comment by Regalis11** [comment]
No known steps to repro and there haven't been any additional reports about this, so I think we can close this.
