### ISSUE TITLE
[Linux] Dedicated Server Cursor is Positioned Incorrectly

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2615]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The cursor in the dedicate server console is placed on the wrong line and moves incorrectly. Typing in the server console causes the cursor to overwrite the last line outputted, moving the cursor up instead of down. This makes the console very hard to use.
![barotrauma console](https://user-images.githubusercontent.com/37539527/79045033-ec07cd80-7c00-11ea-865c-d04e75850158.gif)
*This is observed behaviour on v0.9.9.0, compiled from source.*

**Steps To Reproduce**
- Install the dedicated server.
- Start the dedicated server by running `./DedicatedServer`.
- Type into the server console.

**Version**
Versions 0.9.8.0 and 0.9.9.0. Not tested earlier versions. Both versions installed via SteamCMD and compiled from source. Linux install is Ubuntu 18.04 LTS. Connected via PuTTY.

**Additional information**
Does not occur on Win10 installation of the dedicated server for versions 0.9.8.0 or 0.9.9.0.

**Comment by Krasven** [comment]
I'm rather new to github and commenting on such issues so I apologise in advance.

I encountered the same issue. I think the problem is that it is attempting to suggest commands like on the windows version:
![image](https://user-images.githubusercontent.com/44142173/79056503-2f892880-7c4f-11ea-9914-f233b701d5a6.png)

If TERM is set to vt220 - among a few others, - this issue is fixed, however there is no colour available and the command suggestion - sans the colour - works:
![image](https://user-images.githubusercontent.com/44142173/79056563-b6d69c00-7c4f-11ea-9462-23d3cef66a59.png)
(I haven't managed to find one that works and has colour.)

So I was possibly considering if there's an issue with the escape sequence? As it seems to move the cursor up a line rather than to the start of the current line.

**Comment by Jlobblet** [comment]
Appears to be fixed on v0.9.9.0.
