### ISSUE TITLE
[Modding] [Bug] setvalue="true" invalidates range="X" for nearbyitems/characters

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2636]
```xml
<StatusEffect type="OnNotContained" target="NearbyItems" range="2000" setvalue="true">
		  <Conditional identifier="gasvent" />
		  <Remove />
</StatusEffect>
```
in the above example, setvalue="true" nullifies the range="2000" requirement for the NearbyItems target type, presumably because range is accounted for in a seperate check in StatusEffects.cs and not the initial switch statement that contains setvalue.
This makes it impossible to set the values of nearby items. If there's a way to do something like
```
<StatusEffect blahblahblah>
<SetValue IsOn="true" />
</StatusEffect>
```
where you can set values using a child element of statuseffect, I would love to know! thanks.

**Comment by Regalis11** [comment]
Could not reproduce: setvalue doesn't seem to have any effect on the range.

There's a couple of issues in the StatusEffect though: it targets all nearby items within 2000 units, and removes all of them if the condition is met. The condition will never be met though, because there's no way to check the identifier of a target with a conditional. You should instead make the effect only target gas vents by adding `targetidentifiers="gasvent"` to the StatusEffect element.
