### ISSUE TITLE
Fire's Severity/size/distance sound? occurs way too fast/often

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#265]
Version 0.8.0.0

Not quite sure how I'm to put this:

I have this issue often and noticed it again during a large submarine inferno. it was like a "tick" or "T" sound that is extremely short occuring up to 30+ times / second. perhaps the start of the fire sound beginning, ending and beginning far too many times in a second or some other warning sound repeating far too often without any delay from the previous sound.

it's heavily effected by camera angle from fire sources.

**Comment by Regalis11** [comment]
I think this could simply be the cracking sounds that are a part of the sound clip being played very frequently due to several fire sounds playing at the same time. As of dbea36b only one instance of each fire sound (firesoundlarge and firesoundsmall) is played regardless of the number of firesources, making the "ticking" much less frequent.
