### ISSUE TITLE
[Minor] Scale in meters

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2654]
Minor/Low Priority Issue:
In submarine summary on selecting sub, it gives dimensions in width x length in meters.
1) These dimensions only consider hull spaces which may not reflect the real dimensions of the sub.
2) The scale is fairly far off from the appearance.

It seems through testing that approximately 5 grid ticks of hull space is equal to 1m displayed in the sub summary.  10 ticks = 2m; in theory, 1 grid tick = 200cm
When I compare what should be 2m according to this scale to the humans rendered in-game, the humans are 'a head' taller than the 2m mark, making the humans in this game approximately 2.2m tall and doors 2.6m tall.  Average human height is anywhere from 1.6-1.8m

Really pedantic, but perhaps consider adjusting the displayed meters calculation to something more accurate.  Humans displayed in-game seem to be between 10-11 grid ticks of the hull. Perhaps make each grid of hull = 120cm?

And 1 grid in volume is 16? Curious what unit of measure this is and the interplay between the volume units and the m calculation.

**Comment by Regalis11** [comment]
1 grid node = 16 pixels
1 pixel = 1 / 80 meters = 0.0125 m
1 meter = 80 pixels

The multiplier is pretty much arbitrary: we just selected some value that seemed "close enough" in the early stages of the project. Since then the dimensions of the humanoid characters and structures have changed a bit, so the multiplier is indeed a little off: a human is about 175 pixels tall, which would translate to about 2.2 meters.

Thanks for pointing this out, I think we should adjust the multiplier a bit to get the measures to make more sense!

**Comment by Regalis11** [comment]
Set the value to 1 / 100, so now 100 pixels corresponds to 1 meter, making the characters 1.75 m tall. https://github.com/Regalis11/Barotrauma-development/commit/def2ba699b2f68d657d031b0c63a907a1f7538e6

**Comment by Rokvach** [comment]
No issues, closing.
