### ISSUE TITLE
Constantly low FPS

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#2688]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So, my friend has very low FPS during the whole game (10FPS, max. was about 17FPS) no matter what sub we use. His specs are
-Windows 10 Home
-CPU Intel Core i7 4720HQ @2,60gH 4 cores, 8 threads, 6mb cache,  8GB DDR3
-GPU Nvidia Geforce GTX 960M

His PC is way more better than mine, however I can play the game perfectly.

**Steps To Reproduce**
-/-

**Version**
Windows 10 Home
![grafik](https://user-images.githubusercontent.com/63376072/80208849-55400580-8631-11ea-940c-6f53288829f7.png)

**Additional information**
He has reinstalled the game already and checked it for errors, but this didnt help

**Comment by BurykinNikolay** [comment]
For Rx 480 same issue

**Comment by Melolatius** [comment]
So, does anyone know how to fix this?

**Comment by Melolatius** [comment]
So, any new information about the issue?

**Comment by EtiamNullam** [comment]
Are other games running fine?

I would start by checking both CPU and GPU temperature, make sure its not throttling due to overheating.

Then it might be worth checking where is the bottleneck, even a quick glance in the `Task Manager` could be helpful, for example:
- Is CPU usage at 100%?
- Is memory full?
- Is GPU usage at 100%?
- Is the correct GPU under load?
- Are there some background processes that slows down PC?
- Are you sure external GPU is rendering the game, and not the GPU integrated in CPU? It probably should still be enough for more than 15 FPS though.
- Are drivers up to date?

I'm not saying its impossible that its some problem with the game, but it works for a great majority here even on weaker PCs so its probably something on your end. Performance also seems better in the recent updates so maybe it already got better for you?

**Comment by thegrb93** [comment]
Monitor cpu temp too. Hot cpu will throttle down.

**Comment by Melolatius** [comment]
Soo

His laptop was using the CPU integrated GPU, not the external Nvidia GPU
Thanks a lot, he now has 70FPS
