### ISSUE TITLE
Components records via signal doesn`t work.

### ISSUE THREAD

**Issue by Reitarou** [Regalis11/Barotrauma#2730]
- [+ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mem component "SIGNAL_STORE" and Signal Check component "SET_OUTPUT" and "SET_TARGETSIGNAL" do nothing instead of write corresponding fields.

**Steps To Reproduce**
Simply generate any signal value, link it to Text Display and to test inputs. Text display will change, but Mem or Signal Check components remains unchanged.

**Version**
v.0.9.9.0 Release Windows, branch release, revision 0534150c8. Windows 7 via Steam.

**Additional information**

**Comment by HalfdeadKiller** [comment]
I was unable to reproduce this issue. Perhaps it's an issue with your specific circuit? The attached sub was tested using a locally hosted server, hosted through the in game menu.

[A.MemTest.sub.zip](https://github.com/Regalis11/Barotrauma/files/4548995/A.MemTest.sub.zip)

**Comment by Reitarou** [comment]
![image](https://user-images.githubusercontent.com/10302297/80569601-f3511880-8a01-11ea-8f34-963fe60fdbcc.png)
First: Thanks for test sub. It`s unclear, that "Store_Signal" is "Allow_Store_Input_Signal". May be rename label is a good idea.
Second: When you pick component manually it shows some weird data. Sometimes it replaced, sometimes not. In attached screen I already stored "one", as shown at text display, but UI says "Value: Two22".
Same for Signal Check Component when you send new output. Internal data rewrited and work correctly, but when you select item it shows old output.

**Comment by sdk2013** [comment]
I can verify the STORE_SIGNAL system is not working. 

![2020-05-12_03-52-17](https://user-images.githubusercontent.com/4116882/81669258-94c96880-940b-11ea-8349-3c12b064b98b.gif)

https://imgur.com/GAQM1zQ Another Example.

v.0.9.9.1 Release Windows, branch release, revision 1968ab79f. Windows 10 via Steam.

**Comment by HalfdeadKiller** [comment]
The issue is caused by all components outputting their true value at round start. This is easily seen by having an OR component receiving a 0, but outputting true. I've included this in MemTest2.sub.

The Memory component starts with it's store_signal pin being true. This means it will store new signal. However there is nothing wired to the store_signal pin, so it receives blank signal and doesn't update it's state. It's state is now forever 1, and will update it's signal until store_signal receives a 0. I'm not sure if this is a bug or a feature to have components output their True value at round start. It allows neat stuff like having circuits only activate at roundstart, but it's existence may cause more confusion than innovation.

The zipped sub has a few other example use cases of Memory components.

![image](https://user-images.githubusercontent.com/16188887/82011319-44841d80-963a-11ea-8cec-f7b551828f4a.png)
[A.MemTest2.sub.zip](https://github.com/Regalis11/Barotrauma/files/4632215/A.MemTest2.sub.zip)

**Comment by HalfdeadKiller** [comment]
Upon further inspection, the oddities regarding Mem components and store_signal get weirder. For example, a button wired to store_signal does nothing to stop the mem component from storing incoming signal. However an Oscillator on pulse, which works similarly like a button, operates as if the oscillator outputs a 0 when not True, which it doesn't. Oscillator's appear to output blank when false, and a pulse of 1 when true on the Pulse setting.

Here is the new testing sub.
![image](https://user-images.githubusercontent.com/16188887/82013320-ad21c900-963f-11ea-8006-a6c952973fd8.png)
[A.MemTest3.sub.zip](https://github.com/Regalis11/Barotrauma/files/4632330/A.MemTest3.sub.zip)

**Comment by Regalis11** [comment]
This report seems to have been based on a misunderstanding of what the "signal_store" input means. It has been since renamed to "lock_state" to make it's purpose more clear (makes the memory component "non-writeable", meaning the value stored in it cannot be changed).
