### ISSUE TITLE
[Feature Request] Add a crawling animation to the game

### ISSUE THREAD

**Issue by sumrex** [Regalis11/Barotrauma#2745]
I'd like to crawl through ducts and stuff, and it could be fantastic and interesting for traitor games with submarines designed for this. I was literally 99% of the way to doing it myself before I realized that current mod support just flat out won't allow this kind of editing. It would require editing a couple files including adding a new movement type and keybind. Walk, Run, Crawl movement types for land, I cobbled together a very basic crawling animation in like half an hour so I'd not expect it to be too hard.
I think this would be a valuable feature that could be added with only a few hours of effort most of which is animations.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
