### ISSUE TITLE
[Feature Request] Could Sonar hurt divers ?

### ISSUE THREAD

**Issue by Erwyn** [Regalis11/Barotrauma#2760]
Hi there!

It just came to my attention that Active Sonar is a dangerous device and could hurt badly divers. I'm no expert, but if this is true it could be really interesting to have some kind of mechanic around this implemented.

Here are some links:

* [Reddit Thread about it](https://www.reddit.com/r/todayilearned/comments/gbs0bb/today_i_learned_submarine_sonar_is_no_a_ping_like/)
* [Wikipedia article about Active Sonar and Mammals](https://en.wikipedia.org/wiki/Marine_mammals_and_sonar)

If this is irrelevant or a duplicate, sorry ! I just love this game and thought it could be interesting.

Keep up the good work !

**Comment by thegrb93** [comment]
Naaaa

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.

**Comment by Erwyn** [comment]
For future referemce: https://undertowgames.com/forum/viewtopic.php?f=19&t=11689
