### ISSUE TITLE
Unable to enter or exit sub through open airlock door

### ISSUE THREAD

**Issue by Kaetie** [Regalis11/Barotrauma#2763]
After going to an artifact and gearing up with scooba gear I am unable to leave the airlock.
The door opens, water rushes in, but I can not go out. I destroyed the door and was able to squeeze through the wreck of the door, but once fixed it is again impossible to go through when opened.

This has happened to me about 3 times in the past day or so I've played. Every time it happened I'm going for an artifact. I'm using the Dugong. (Not sure if sub type matters)
version 0.9.9.1 windows

Fom the save go to Milda while doing the artifact mission. Theres some tight rocks to squeeze through but you can make it all the way there.
Once there attempt to gear up and leave.
[Save 1.zip](https://github.com/Regalis11/Barotrauma/files/4570028/Save.1.zip)

**Comment by RusChosen** [comment]
The same problem can occur randomly at any type of a mission with any given sub. More often it happens when 2 subs are docked one to another, but I've had more then one occurrence of this bug while trying to enter the sub from the ocean, or to exit to the ocean.

**Comment by Kaetie** [comment]
I was able to figure out specifically where it happens in that save.

In the first image I'm slightly to the right and up from where I am in the second image.
In the first image I can exit, in the second I can not. Second image is very close to where the artifact was, which is why I'd want to exit the sub right there.
Something about this area in specific makes me unable to exit the sub, while anywhere else seems fine.

![can exit](https://user-images.githubusercontent.com/64730075/81426740-e8149000-9159-11ea-92dc-ff2f3dc25917.png)
![can not exit](https://user-images.githubusercontent.com/64730075/81426746-eb0f8080-9159-11ea-9991-83c54e065f05.png)

**Comment by Regalis11** [comment]
Thank you for a very informative report, I was able to reproduce and fix the issue now!

The bug occurred when the submarine was in some specific positions outside the borders of the level. In more technical terms, wall cells that generated right next to the borders of the level would not have an edge created at the border, which would cause positions outside that level cell to be considered _inside_ it. So in this case, the came though the airlock door is inside a level wall, and would not let you exit.

![5467246](https://user-images.githubusercontent.com/14351070/81480308-8e7f9480-9231-11ea-93c7-4bb4344149ea.png)

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/080c7e6894873dcf35ae8ccde3b5b8043235af1f, moving to Review/QA

**Comment by Kaetie** [comment]
Nice, good job!

**Comment by Rokvach** [comment]
Confirmed working, closing.
