### ISSUE TITLE
Relays on numerous submarines instantly burn out - MaxPower checked on Power_in instead of Power_Out?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#279]
Version 0.8.0.0+

I have been told the relay components are burning out immediately on various submarines where they should theoretically be stable, such as being connected to just a few lights.

As I understand what I've been told, relay components Power_in is being used in the checks for overload instead of Power_out.

Say the MaxPower of the relay is 1000, and the Power_Out side is 25 but the power in side has 3000 (the submarine main grid itself, which is expecting 3000 and has 3000 so that side has 1 voltage and is not overloaded).

The above seems to cause the relay to be fried immediately (Where its only transferring 25), despite the other side has a maximum requirement of 25 power draw and in previous versions this did not used to break relays. Most submarines utilizing these as a feature will often break their relays unless they are sectioned off by batteries now.

**Comment by Regalis11** [comment]
The problem is that the new PowerTransfer logic treats relay components as parts of the power grid the same way it does junction boxes, which causes the power and load of the relays to always be the same as the rest of the grid. Derp, should've tested it with subs that don't just use relays for passing signals around.

I managed to do a fix that seems to solve the issue, but the PowerTransfer code is starting to get so hairy that I need to do some more refactoring and testing before I'm ready to push it to the main branch.
