### ISSUE TITLE
[0.8.0.1] Footstep Sounds Issue

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#280]
Human footsteps in modded files cause a "file not found" console error on every audible step.

It seems to work with other creatures like crawlers. Husks work on unless you put trousers in them, then they will cause the same issue.

I tried using direct paths to them, like:
<sound file ="Mods/BTE/Characters/Human/step1.ogg"/>

But the issue persist.

**Comment by Regalis11** [comment]
As of 2cb0ee7 the recommended way to configure footstep sounds is to include them in the sound config file and use the name of the sound element instead of the path to the sound file (e.g. footstep, footstep_metal, footstep_armor). Using the direct path should also be possible in 0.8.0.0 and 0.8.0.1, and it seemed to work now that I tested it. If you can provide more instructions on how to reproduce the issue it'd be much appreciated.

HOWEVER, I just noticed that the because of the changes in 2cb0ee7 the SoundPlayer class always creates a new Sound instance when you play a sound using the file path instead of a sound tag. These sound instances are never freed which obviously had to be changed. As of 0.8.0.2 it will be possible to add new sound configuration files to content packages, and new footstep sounds should be configured by adding them to the sound configs and using the appropriate tag instead of the path in the character config file.

**Comment by ChikoEduardo** [comment]
I know what the issue is. It happens when the character is using trousers or something that uses RightFoot,LeftFoot with no sounds in them. I added sounds to all of the trousers,diving suit,jumpsuit,etc. and there's no more error.
