### ISSUE TITLE
Some problem with relay power and grid load (maybe batteries)

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#282]
On some subs, the power just doesn't flow at all. Sometimes it shows a load of -2147483648. I'm not sure exactly what causes it, but I suspect it has something to do with relays, maybe specifically ones after batteries. I observe this on both my torrent and subomination, which have power coming through relays after batteries. I've also had problems on other subs that subs and shuttles that use relays after batteries.

**Comment by ChikoEduardo** [comment]
Yeah, I think it's the relays. They don't work on the vanilla shuttles too, since they use relays instead of junction boxes. They seem to do a different thing for each of my ships. I get one that instaflood the ballasts as soon as there's power. The relays in another ship allows it to move at an impossibly fast speed, etc.

**Comment by Regalis11** [comment]
No, it means the optimized PowerTransfer logic that was added in bb98767 is only used for signals now, and transferring power uses the pre-0.8 logic. I'll probably take a new shot at fixing the optimized logic later, but I think for now it's better to revert back to the more performance-intensive old method because atm the relay issues make most of the subs unplayable.
