### ISSUE TITLE
[0.9.10.0] Depth Decoys immediately stops functioning when it lands on anything

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2834]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Depth Decoys immediately stops blarring when it land on anything. Usage in small tunnels is quite useless.

**Version**
0.9.10.0

**Additional information**
I propose giving it a timer before it stops of maybe like 10~15 seconds.

**Comment by Ek-Videogames** [comment]
I mean you're not wrong.
- I have a counter suggestion which is decoy depth charges might be useful if they fell slightly slower.
at the moment they fall and rapidly gain speed like any normal item dropped.

**Comment by Regalis11** [comment]
Actually the decoy didn't stop functioning, it just stopped playing the sound effect, but attracted enemies for a fixed duration of 20 seconds after being launched. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c232a1885a341246eb54af712b20c69c98436ca8: now the decoy stays functional for 30 seconds and also sinks more slowly.

**Comment by Rokvach** [comment]
No issues, closing.
