### ISSUE TITLE
Copy+Pasted Component Malfunction

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2842]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/4635026/Submarines.zip)
In Test2.sub, there's a logic system that is supposed to turn up the fission rate of the Reactor. The 3 components on the far right were copy+pasted from a previous setup (Which worked). For some reason these components aren't doing anything.

In Test3.sub, a new set of components wired the same way as the previous 3 components works.

**Version**
0.9.10.0

**Additional Informations**
This seriously pulled my hair out because I didn't know why that set of components weren't doing anything

**Comment by Regalis11** [comment]
I did a bit of debugging, and I think this part of the circuit may be the culprit. Specifically, having the relay component receive a set_state signal from two sources simultaneously, which can lead to unpredictable behavior as discussed in #1786.

![567824657](https://user-images.githubusercontent.com/14351070/82151978-1a637300-9867-11ea-921b-e3b1e3f6403b.png)

I don't quite understand how it's intended to work: the relay's state is controlled simultaneously by the oscillator and the state of the relay itself. If the relay happens to get updated after the oscillator during the same frame, it will always turn itself off (because it passes it's state to the signal check component, which turns it back off if it's on). And in this case I think pasting the extra components in caused the update order of the components to change, preventing the circuit from working as intended.

I'd recommend not trying to control the state of any component/device with two or more simultaneous signals, because it can lead to this sort of unpredictable results.

**Comment by Kaillera** [comment]
Here's the fully functional version after I used fresh components for everything. This was a temperature-based auto reactor logic I was working on. If the temperature was low, it would increase fission. If it was too low, it would increase it even more. Same as the opposite. If it was hot, it lowers it. If it was too hot, it lowers it even more.

[Test.zip](https://github.com/Regalis11/Barotrauma/files/4640499/Test.zip)

Try copy pasting this set of component. Configure the copy-pasted component to copy one of the other 3, and then reinserting it back into the logic the same way. The new copy pasted component will not do anything.

![Capture](https://user-images.githubusercontent.com/5086682/82152898-5d572380-9832-11ea-96d7-c6568784f7d3.PNG)

**Comment by Rokvach** [comment]
Is this still a issue? Copying and pasting has gone through a lot since then
