### ISSUE TITLE
0.9.10.0 unstable. The end of the wire is (not always) shifted to the left side when connected.

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#2851]
Connecting two logic elements, the end of the wire remains in the left edge and when the finite element is moved, the wire remains in place. It does not depend on which edge of the element the wire is connected to. 
![213434345657 — копия — копия (2)](https://user-images.githubusercontent.com/58271380/82150318-f9981f00-9860-11ea-9c64-5b0e72fc754a.png)

**Comment by Regalis11** [comment]
Seems to have been caused as a side effect of #2852, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/fdc23688bca3b8209a71349c20cf211ca4291461.

Steps to repro: 
1. Move the component so that it's not aligned with the grid (e.g. 5 pixels to the right)
2. Connect a wire to it: the last node should end up slightly outside the item (as in the pic).
3. Move the component again: the node won't follow it

**Comment by Rokvach** [comment]
Wasn't able to reproduce, working correctly. Closing.
