### ISSUE TITLE
[Modding] Mod load order reset after each restart.

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2862]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When at least two mods are enabled, you can indeed change the load order successfuly, but if you restart the game they are repositionned in their default order.

It seems that the default load is based on an alphabetical order.

**Steps To Reproduce**

**Step 1:** Subscribe to two different mods

**Step 2:** Activate them in-game

**Step 3:** Change the load order and apply

**Step 4:** Restart the game and see that mods get back on their previous position.

**Version**

Barotrauma release version 0.9.9.1 on Windows 10 updated

**Additional information**

Changing the load order without restarting the game seems to be without issue : Mod order are working perfectly in that case.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ea4fde0e60a4d21502a58690ef79ddd58849909

**Comment by Rokvach** [comment]
I don't think we should move enabled mods at the top of the list, the list hierarchy should be the exact same all the times as the player has set it to be. I know we don't have that many load order sensitive mods right now, but I do think that we will have those at some point. So if a mod gets disabled because you wouldn't need to reconfigure every time. @juanjp600

**Comment by Rokvach** [comment]
Working correctly.  Closing.
