### ISSUE TITLE
Sub Editor - Large Vertical Inside Wall using wrong icon. Looks darker like wreck.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2867]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The icon for Large Vertical Inside Wall in the sub editor is using wrong icon. It looks darker like wreck version. I normally can't find it by glancing at the icons anymore.

**Version**
<0.9.1001.0

**Comment by Regalis11** [comment]
Looks normal to me. I wonder if it could just be that the downscaled version tends to look darker because the thin, bright stripes get blended with the darker parts when downsampling the sprite?
![4567drsgth](https://user-images.githubusercontent.com/14351070/82543041-a8877400-9b5b-11ea-8f1d-7c6cf63efd5d.png)

Would you mind posting a screenshot of what it looks like at your end?

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/82549113-6c87eb00-9b2a-11ea-8c49-4fc49a07dc45.PNG)
