### ISSUE TITLE
[0.9.10.0 RC1] Played a mission round at 100% Hellish. Enemies were spawning pretty far behind

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2877]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was playing a multiplayer mission round on 100% Hellish. We met the 20% distance enemies. Upon driving forward further to around 70%, we never saw the 40% and 60% distance groups. It turned out they spawned pretty far behind us.

![Capture](https://user-images.githubusercontent.com/5086682/82683078-5b200b00-9c1e-11ea-8c7e-c96952bd2566.PNG)

Black Moloch and Thresher Swarms were fighting each other at these two zones.

**Version**
0.9.10.0 RC1

**Comment by itchyOwl** [comment]
It's possible that this issue is due to the new offset parameter that offsets the spawn of a monster towards the end of the level. It shouldn't calculate the direction back though. Let's keep the eyes open and try to repro this. I'll add @ezjamsen as an assignee so that you are aware of the possible issue.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4f9da1d4a9c8ae8f70f34894052fbc1e11bd3469 (see #3447)

**Comment by Kaillera** [comment]
I've seen aliens spawn in all sorts of directions in 0.10.502.

Top Right, Bottom Right, Behind. Usually the front side more often.

Seems to be working very well.

**Comment by Rokvach** [comment]
Closing.
