### ISSUE TITLE
 Does not start Barotrauma

### ISSUE THREAD

**Issue by RodrigoPepsi** [Regalis11/Barotrauma#292]
Hi,guys!I downloaded the game and tried to launch it, but it did not work out, it just did not start, the silence...
My system characteristics:
Windows 7
GeForce GTX 520m
Intel Core i-3 2.1 Ghz
4 gigabytes of RAM
Help please!
reply to mail: zurto.art@gmail.com
Thank you.

**Comment by NilanthAnimosus** [comment]
If "Downloaded" refers to the barotrauma launcher from 0.7.0.1 and before, you will find a new "Launcher" and barotrauma launcher is the old launcher which is broken. the game should run fine if it has been downloaded from undertowgames.com. be interesting to know the method you downloaded the game from and if it gave an error box or a crash report appeared in the games folder.

- you can also try running Barotrauma.exe directly if "Launcher" does not work.

**Comment by NilanthAnimosus** [comment]
I figure (Since no more information has been given) it is worth noting without using the launcher, simply deleting the config.xml file will cause the game to fail to launch if ran via the exe, if the config.xml file is missing certain lines (IE. is an older config file) that too will cause barotrauma to fail on launching it directly from the exe.

Perhaps getting the game able to run without requiring a config file at all (And/or adding a default masterserver url to the code).

If the content package is incomplete/damaged that too causes problems, such as crashing on null background images being drawn.

Some users have reported being unable to launch the launcher itself, but I imagine this is more down to missing certain redistributables (Such as .net versions).

**Comment by verish** [comment]
I have the same issue the game won't even launch when I tried it was version 0.8.1.0 when I use barotrauma.exe nothing happens send 119 plez

**Comment by verish** [comment]
And I mean no error code literally nothing as if it was an icon nothing attached the loading icon was on mouse for a sec then nothing no sign of life

**Comment by verish** [comment]
Tried newest version nutin happened still

**Comment by thechiken666** [comment]
verish the same thing is happening to me im so confused nobody seems to know how to fix it

**Comment by thechiken666** [comment]
someone please help

**Comment by thegrb93** [comment]
You need .net framework probably

**Comment by Regalis11** [comment]
@thechiken666 Sorry but it's hard to help without more information of the problem. Are you playing the latest windows version? Does the same thing happen when you try to use the launcher instead of Barotrauma.exe? Do you have .NET framework 4.5 or later installed? Can you see the game in the task manager after you've launched it?
