### ISSUE TITLE
[Campaign Update] NPC Interactions do not properly use mapped controls

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2929]
IE opening the menu uses LMB, closing the menu uses RMB, like the current control scheme. does not change if you are using legacy control scheme or whatever else like it should.

**Comment by Regalis11** [comment]
Which types of interactions do you mean? Interacting with the special NPCs (shop, hiring, repairs, etc) and ones related to events is done with the Use-keybind (E by default) and changing the keybind seems to work as expected.

**Comment by hubismal** [comment]
Oh okay, I was unaware that was intentional. It's kind of a strange keybind since every other interface in the game is brought up using E and can be closed by pressing E again.

**Comment by Regalis11** [comment]
That's not true unless you're using a non-default key mapping: other interfaces are opened with LMB and closed with RMB.

We chose to use a different default keybind for NPC interactions and item interactions, because with the same keybind it was too easy to accidentally choose items next to NPCs or vice versa.
