### ISSUE TITLE
[Campaign Update][Crash] spawning character, pressing tab crashes the game

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2950]
what it sounds like. very easily reproducable. seems like the spawn cheat command hasn't been updated for something new?
[crashreport (77).log](https://github.com/Regalis11/Barotrauma/files/4720369/crashreport.77.log)
[crashreport (78).log](https://github.com/Regalis11/Barotrauma/files/4720370/crashreport.78.log)

**Comment by ekqvist** [comment]
This seems to have been fixed as a side effect of fixing #2920. The issue was that since there were multiple team IDs in the crew, we assumed that we're dealing with a MP combat mission and tried to access `Game.Client.Character` without checking if `Game.Client` is null. I added an extra null check for it in Regalis11/Barotrauma-development@5f1a334, just in case.

**Comment by Rokvach** [comment]
Confirmed working, closing.
