### ISSUE TITLE
Crowbars can't open doors correctly for me.

### ISSUE THREAD

**Issue by FonkMustardBetz** [Regalis11/Barotrauma#297]
let me explain, I use the crowbar as any job (tried different ones to make sure) on any door (even tried hatches) and when I open them they immediately just close again. I got a different person to try the exact same door I tried to open and it stayed open for them, what is the deal?

**Comment by NilanthAnimosus** [comment]
This I've found is occurring only in multiplayer, I think they might not be syncing with the server and the server lets the client know the door is actually closed and not open.

**Comment by NilanthAnimosus** [comment]
The cause of this is in the shared Pickable.cs. the "WaitForPick" code once finishes calls:

if (!picker.IsRemotePlayer) OnPicked(picker);

I have zero understanding as to why, but the code that is triggered for a host character opening it is specifically excluding remote players. the set state of the doors onpicked appears to include predictedstate and I am curious as to where else in the code was this check possibly intended for (And why it excludes netplayers but not hosts or single player events).

**Comment by Regalis11** [comment]
I think the intention of disallowing remote players from triggering OnPicked was to prevent clients from calling it. Before the addition of crowbars preventing it from being called was not a problem, because the only items that had a picking timer were attachable electrical components which would get picked up once the server receives a message about the item being moved to the picker's inventory. A simple fix is to allow the server to call OnPicked, but I'll have to do some more testing to make sure it doesn't cause any unintended side-effects.
