### ISSUE TITLE
[0.1001.0] Outpost's Reactor should have 0 fuel consumption

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2974]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost's Reactor should have 0 fuel consumption. Sometimes I just like to sit inside stations for an hour while working on stuff in the sub. Kinda hate having to undock and dock back to the station to keep the power up.

**Version**
0.1001.0

**Comment by Udrakan** [comment]
Since there is an effort to wire everything properly and have a believable electrical grid even in the outpost, maybe an outpost engineer could refill the outpost reactor with rod like they do on submarines, except he would have infinite rods just like security personel has infinite revolver rounds.

**Comment by Regalis11** [comment]
I agree with Udrakan. The bots now spawn a fuel rod in their inventory if they can't find one anywhere else: https://github.com/Regalis11/Barotrauma-development/commit/a692c3d827a5e0a7fbd08518f8a73f74b54cab1b

**Comment by Rokvach** [comment]
Working correctly, closing.
