### ISSUE TITLE
Some new features with Throwable?

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#303]
There seems to be no holdpos code for throwable items so even two-handed items are carried in one hand until you aim them.

In versions prior to the 0.8.0.X of the game, I found a way to "fix" this by using this piece of xml code:
```
<Holdable slots="RightHand+LeftHand" holdpos="40,-30" aimpos="45,-20" handle1="-30,14" handle2="30,-7"/>
	
<Throwable slots="RightHand+LeftHand" throwforce="3.0"/>
```
Not only it allowed two-handed items to be carried with both hands but it also changed the aiming animation. Instead of raising the arms for the throw, aiming would instead work in a similar fashion to aiming a gun. This would affect the throw, making it look like the character is shoving the object forward and preventing big objects from hitting the ceiling.

This no longer works and causes a number of glitches. Could we maybe have the ability to use holdpos in the Throwable code and have another piece of code that uses the aiming from Holdable instead?

Edit: Another idea for Throwable could be for a piece of code that allows it to work as a weapon, and have Attack values so it causes damage/stun, etc. I'm currently attaching an explosion to simulate this but it only works when the object hits a surface.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
