### ISSUE TITLE
Random events problem, moloch and hammerheads

### ISSUE THREAD

**Issue by Nikolay0525** [Regalis11/Barotrauma#3080]
**Description**
The mistake is that a group of monsters, hammerhead, and moloch, start to fight among themselves
when they appear and do not pay attention to a passing submarine, which I think is not right

**Steps To Reproduce**
This error is reproduced during the appearance of a group of monsters, hammerhead, and moloch, they begin to beat each other, this can be seen on almost all difficulties.

**Version**
0.9.10.0 Windows 10

**Additional information**

**Comment by Nikolay0525** [comment]
similar happens with the crawlers that spawn with the tiger threshers and the bonethreshers

**Comment by Nikolay0525** [comment]
1. #

**Comment by EtiamNullam** [comment]
I actually very much like it, feels natural - You can witness the food chain working and it makes it look less like every monster exists only to kill you.

I would expect these creatures to go for easy food rather than struggling with opening a steel can that stings when you get close.

Though maybe they could be more aggressive towards what is very close.
