### ISSUE TITLE
Multiplayer - Game Over End Round reverts Sub state to the beginning of round, but deletes character data.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3096]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you get a Game Over End Round (Everyone dies), it reverts Sub state to the beginning of round, but deletes character data.

This had been bugging me for quite a long time, I don't know why I never reported it.

**Version**
<0.1002.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2cb1f4f039f940a76a064adc68782494c792ab17

**Comment by Rokvach** [comment]
I'm not fully sure if this is working correctly, when everyone died it felt as if I was assigned a way earlier character which I lost due to a disconnection issue. But I'm not sure how heavily the host was using the setclientcharacter command and how heavily that messes things up. But at least you don't get assigned a fully fresh character anymore.

**Comment by Rokvach** [comment]
I didn't notice anything wrong with this during our previous Unstable community testing session, closing.
