### ISSUE TITLE
[0.1003.0] Outpost NPC easily becomes hostile on you when defending against a Alien events

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3134]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you get like a Mudraptor vent breach event and you accidently get a NPC in a blast radius or shot, the outpost security NPC goes mayham on you.

**Version**
0.1003.0

**Comment by itchyOwl** [comment]
So the issue is that you accidentally do damage on the NPCs? If so, I'd say that's a design issue rather than a bug.

**Comment by Kaillera** [comment]
Accidental damage during alien events yes.

**Comment by Rokvach** [comment]
Yeah stray bullets can end up deadly :D I accidentally shot one of the service NPC's by trying to fight against the husk cult members who attack you regardless what you say to them.

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@c4ebcb9. Bots should now assume an attack is accidental when they can see both the attacker and an enemy/instigator character.

**Comment by ekqvist** [comment]
Made a slight adjustment in Regalis11/Barotrauma-development@5b1436e. The enemy/instigator must be active (alive and conscious) for the damage to be able to be considered accidental.

**Comment by ekqvist** [comment]
Removed duplicate code introduced earlier. I think the issue with monsters had already been fixed before, but there was still a similar issue when damaging a character while fighting an instigator. That should now be fixed in Regalis11/Barotrauma-development@4300e80. Additionally, I change the logic so outpost reputation won't decrease when damaging an NPC and there's a monster or an instigator closeby in Regalis11/Barotrauma-development@1214717.

**Comment by Lithosagym** [comment]
Tested, bots do not retaliate from player damage while both the instigator and player is visible, and outpost reputation does not get affected by the player damage. Working correctly.

**Comment by Rokvach** [comment]
Closing.
