### ISSUE TITLE
Localisation (Russian)

### ISSUE THREAD

**Issue by StPapka** [Regalis11/Barotrauma#3136]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I found some translation / logic errors:
"Жесть" = tin-plate. But Tin is "Олово".
"Обойма для револьвера" = clip for revolver. Revolver round is "Патрон для револьвера" or "Револьверный патрон".
"Обойма для ПП" = clip for SMG. SMG Magazine is "Магазин для ПП".
"Топливный стержень" = fuel rod, but other rods are name "ториевый" (thorium) and "грозовиевый"(fulgurium). Why not "Uranium fuel rod"?

**Steps To Reproduce**
Change language to Russian and compare.

**Version**
v0.9.10.0 and elder, ancient errors.

**Additional information**

**Comment by rav2n** [comment]
There are many more errors. But we are already used to solving this issue with our own handicraft translation instead of creating a request for each update here. Since I heard with other languages no better.

Regarding the length of the names, this is a problem. If the name is too long, the font is reduced and impossible to read.


[RussianVanilla.zip](https://github.com/Regalis11/Barotrauma/files/4799901/RussianVanilla.zip)
Localization for version 0.9.1. I started translating for versions above, but did not finish, so inaccuracies are possible. Also, the file doesn't affect bots dialogs.

**Comment by Regalis11** [comment]
Seems to have been fixed in v0.10.5.0, excluding the uranium fuel rod. The uranium rods are just called "fuel rods" in all languages, because they're basically the "default" type of fuel rod: similar to how normal railgun shells are just called "railgun shells" instead of "steel railgun shell".
