### ISSUE TITLE
[0.1004.0] Unable to detach components that you placed in Wrecks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3148]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For some reasons I am not able to detach this Motion Detector I placed it down inside this wreck.
![Capture](https://user-images.githubusercontent.com/5086682/85087354-51e97600-b1ab-11ea-90d5-af4a57126987.PNG)

**Version**
0.1004.0

**Comment by ekqvist** [comment]
This seems to be happening because the `PickKey` is saved/loaded incorrectly in some situations. Items which are spawned as new or as a part of the sub behave correctly, but items saved in and loaded from the player inventory get their `prevPickKey` set to `Select`, even though it should be `Use`.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@fe459af.

The issue seemed to be, as I explained above partially, that whenever an attachable item was loaded into the round a part of a previously saved player inventory, their `prevPickKey` was set incorrectly. This lead to the item not being detachable during the round it was attached to a wall. This would fix itself for the next round.

So, the issue didn't affect items spawned with the sub or items spawned as a part of the initial player inventory, only items which were loaded as a part of a player inventory.

Steps to repro:
1. Use `spawnitem atancomponent inventory` thrice and `spawnitem wrench inventory` once.
2. Attach the first component item.
3. Test to see that you can detach the first item, but leave it attached.
4. Advance to the next round.
5. Attach the second component item.
6. Test to see that you can detach the first item, but not the second one. Leave both attached.
7. Advance to the next round.
8. Attach the final componend item.
9. Test to see that you can detach the first two items, but not the last one.

**Comment by ekqvist** [comment]
Note that fix was pushed into the `bugfixes` branch because this issue is also present on the Stable version

**Comment by ekqvist** [comment]
Also, if there are any unwanted side effects of the fix, they should only affect items with the `Holdable` component's `attached` attribute set to `true`. This basically means the different electric component items, plants, minerals, and the Detonator. I also tried testing harvesting plants and cutting minerals after the change and didn't notice anything to have changed.

**Comment by Rokvach** [comment]
No issues, closing.
