### ISSUE TITLE
Unstable - Divers don't trigger monster events in mission mode

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3162]
**Description**
Went outside the sub as a diver and traveled about half the level. Then I went into submarine and traveled a bit to see if monsters spawn normally and they do. I tried this again with same result. Shuttles spawn monster events normally. Divers trigger events in singleplayer campaign.

**Steps To Reproduce**
-host a server
-select mission mode
-start round
-exit sub as diver and travel along mainpath
-no monster events get triggered (except ruins and wreck events)
**Version**
Unstable
**Additional information**
Event manager always stays empty in multiplayer. It would be great if it showed events like it does in singleplayer for debug purposes and analysis.

**Comment by Regalis11** [comment]
This is intentional: in multiplayer the submarine with the most players inside is used to determine how far you've progressed. If it was only based on the player who's furthest in the level, it'd be possible to abuse the system by for example making one player wait near the destination outpost to ensure a safe path for the sub.
