### ISSUE TITLE
Suggestion for smoke inhalation affliction (+ salbutamol)

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#3174]
[x ] I have searched the issue tracker to check if the suggestion has been made.
**Description**
- Sources
Smoke inhalation will be caused by the head coming into contact with a number smoke particles above a specific threshold amount, probably at a certain rate too. This includes fires, smouldering devices and flamer smoke. Preventable by wearing a diving mask or suit, and any other airtight masks that may come down the line.
- Effects
The affliction itself has an effect on the character's vitality, specifically in the chest. Healing window states that the patient has a burning pain in the chest, they are coughing repeatedly and have trouble breathing. By itself, the vitality won't decrease by much, yet has a slow but gradual increase in organ damage (probably unnecessary). Oxygen loss is accelerated depending on how critical the smoke inhalation is, and it is harder to regain oxygen.
- Treatment
Smoke inhalation very slowly decreases by itself as the patient coughs up the particles (much like opiate addictions), but can be accelerated by salbutamol, lasting around 15 seconds or less. Uncertain how salbutamol will be fabricated.

As of now, fires in particular aren't too much of a threat if there's enough distance between the character and the fire. This would give crewmembers more of an incentive to use masks and suits for firefighting, and to be careful around fires and broken equipment.

**Comment by rav2n** [comment]
I will support the idea of ​​adding smoke problems. This will add realism. History knows, unfortunately, not a few cases of death of submariners due to fire and smoke. From myself I’ll add:
— The smoke in the submarine is primarily a problem with visibility, not breathing. A trained submariner should be able to use an individual means of protection in seconds. Depriving a player of a review can indeed be an interesting obstacle (I always prefer a mask rather than a divingsuit inside a submarine, even if there is a threat that it will crush me with pressure).
— Recently, you added to many devices the effects of smoke during a breakdown, but they are purely decorative, it would be interesting if this direction were given development. (By the way, as far as I remember, the smoke sensor still does not work ...)
— I don’t agree on the safety of fire at a distance. I don’t know whether it is a mistake or not, but I have often come across a situation where the fire inflicted damage at a distance greater than that which must be approached with a fire extinguisher to extinguish it. (Through the doors, through the floor and ceiling).
— About treatment methods, it’s the same lack of oxygen, already existing Deusizine in the framework of the game should cope with this.
I also allow myself to offer an alternative from reality, an existing and working drug - Perftoran. Or as Blue Blood is also called. The main purpose of the drug is to saturate the blood with oxygen due to the incorporation of copper ions into the blood. This is a very interesting cure used during the hostilities in Afghanistan, used by the Ministry of Emergencies, and other military structures. Cases of rescuing a child with this drug after transfusion of the wrong blood type are known. The drug saved patients from the inevitable amputation of limbs after burns. Helps with craniocerebral injuries and cerebral edema.
Recently, doctors even suggested using it as a cure for Coronavirus.
I think, as part of the game, this drug well rubbed like something with the properties of deusizine and a package of blood.

**Comment by Solbusaur** [comment]
About fires harming you, they did actually patch that. Since the last update, I haven't been burned through any floors or doors anymore, so that's awesome.
As for treatment, any kind of bronchodilator like salbutamol should be necessary. I did have to do some research on healthline and the NHS websites before making this post. For providing oxygen to the blood, I have thought about suggesting blood bags provide a small, short boost of oxygen. Except I don't actually know if the blood is oxygenated in blood bags. Perftoran sounds like a good alternative for salbutamol

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
