### ISSUE TITLE
Unstable: request about textures 

### ISSUE THREAD

**Issue by pabimuri** [Regalis11/Barotrauma#3179]
Dear Devs, 
Since I know that Barotrauma would have a new textures, I just wanna ask You to let the old one stay in the game. I cant say that I dont like the new one, because it looks really good. But as a player, as a member of community, as a submarine maker, as a fan, I beg you - let old textures to stay in the game at least for show that the game have a big growth, step by step, for show that there were a few generations of submarines where inventive players made a creative interiors. It will whip up community to accept a new pack of textures with inspiration! I have never tried to do something that I wanted to show to other players for steam workshop. And I have never met so many different people who can become friends due to one game. Devs you are making this game great, but please dont forget that you doing this for us... with best regards, big expectations, Пеко.

**Comment by Regalis11** [comment]
Hello and thank you for the feedback!

I'm afraid we are not planning on keeping most of the old textures, for a couple of reasons: the style of the old textures doesn't quite match that of the new ones, and we generally want to discourage mix-and-matching the old and the new textures. Keeping all the old assets would also take quite a bit of memory and add a lot of extra workload for maintaining a ton of legacy items and structures .

However, since you made this report, there's been several changes and improvements to the sprites that we think should make them work a little better in older subs. There's also a chance that will be readding some of the most requested old textures as legacy options.
