### ISSUE TITLE
Empty item overlay

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#3217]
Add an overlay, a red X or something similar, on empty items so that they're easy to spot on a glance. Right now there's too much attention to detail needed to spot the ones that have an empty bar instead of no bar at all (ie full)

**Comment by Rokvach** [comment]
I think a red X would indicate that you can't use the item, but I also noted the same that it was really difficult to see if a oxygen tank was empty because the progress bar being empty is just so dark that you can't see it in comparison to the frame.

**Comment by hubismal** [comment]
Might be nice to add a more obvious outline around the bar, something to the effect of what the current player health bar is.

**Comment by KelvallRogers** [comment]
Perhaps adding a Red or Safety Orange colored "E" to the upper right of the icon as an overlay will help. Because the bar is empty but at the bottom with no outlining it is hard to see it as empty. Many pressurized tanks use a reflective orange E and gauge to show empty.

While somewhat funny, it is honestly very hard to tell if something is actually empty and its easier to slot it in and look at the tank icon gauge to see if its empty than to visually inspect an item.

**Comment by Rokvach** [comment]
This isn't a issue anymore as we have changed how empty items are displayed by using the same UI as seen on crates, toolbelts which is visually more present than the previous one was.

**Comment by Regalis11** [comment]
This still needs some work: the gray box is not that easy to see in all situations, the gradient from green to red is not colorblind-friendly and it can be hard to tell the difference between a fully empty and almost empty indicator

**Comment by Regalis11** [comment]
Ready to implement

**Comment by Rokvach** [comment]
Incorrect indicator on flashlight 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6764e27c-2b3b-4848-b503-fe3a70f4faa3)

**Comment by Rokvach** [comment]
Tested, didn't find any other issues. Working correctly. Closing.
