### ISSUE TITLE
1005 Bug: NPC AI really terrible at melee

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3222]
There seems to be a bug where attacking AI will run up to you and get too close to hit. Usually happens with a knife or a screwdriver. They will stand very close to you (almost on you) and stay there without doing anything because the weapon is "out of range" for them I think, aka you're not in their detection box for when they should strike, and they don't back up to compensate either. If you move in either direction they will be able to hit you.

Reproduction: Hold still the next time some NPC attacks you with a screwdriver.

EDIT: This also applies when you're on the ground and they can hit you, they usually strike you way slower with the knife than need be. They wait like 10 seconds between each hit when they could just keep hitting you.

**Comment by itchyOwl** [comment]
There was a reach issue where the bots didn't manage to hit targets with low range weapons like screwdrivers or knives, but that should already be fixed in the latest unstable (See Regalis11/Barotrauma-development@2166ff4).

I wasn't able to reproduce the issues you described. It's true that the bots are not as effective as they could be when the target is lying on the ground, but I don't see this a huge issue. Certainly I wasn't able to reproduce the bots gettins stuck and not being able to hit the target (as used to happen before the aforementioned commit), neither was I able to reproduce bots hitting only one in 10 secs.

However, I did find some issues that I fixed in Regalis11/Barotrauma-development@a6d03d.

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by itchyOwl** [comment]
Found some issues with the npc melee. I'll look into it later.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@025c3e8 (bugfixes).

**Comment by Rokvach** [comment]
No issues, closing.
