### ISSUE TITLE
1005 AI Bug: Outpost inconsistent treatment of evil players

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3227]
[Bug, Outpost]
Just got in a situation where I was being stabbed to death by a rightfully angry security guard who was very bad at stabbing me, while a medical doctor from the outpost was healing me at the same time.
The outpost should probably have a more consistent viewpoint of who is considered an enemy of the outpost or is punishable by death. I noticed that when controlling an outpost member, a player wrongdoer's name is in red. Either way, the medical doctors should probably not attempt to heal the player being stabbed to death by the security officer.

**Comment by hubismal** [comment]
As a sidenote, it may be beneficial to have the docs heal the criminal if he's only being arrested.

**Comment by itchyOwl** [comment]
The outpost medics shouldn't heal the player units at all.

**Comment by itchyOwl** [comment]
NPC medics shouldn't try to heal player characters and vice versa. Already fixed in Regalis11/Barotrauma-development@5d095bc.

Could not reproduce the issue anymore.

If you control outpost NPCs, player units are always shown in red, because it's not meant that player controls NPCs (they are called non-playable characters for a reason). So, for player controlled characters all NPCs and teammates are blue and others red. And for spectators everyone is white.

**Comment by Rokvach** [comment]
No issues, closing.
