### ISSUE TITLE
Possible power wiring bug

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#323]
I was examining a submarine (Using the latest github) and it simply bursts into flames, where one doesn't expect or understand why its bursting into flames.

It seems like their connected right, from batteries or a reactor but it bursts into flames without any draw and such. something is wrong with this submarine.

specifically the JSC Subomination.

[JSC Subomination.zip](https://github.com/Regalis11/Barotrauma/files/1787169/JSC.Subomination.zip)

It's creator doesn't understand why it burns, but after examining it myself it just appears like it was burning at a high load with no power output (Its definately not displaying correct information, so its hard to even tell why anything is happening with it - and these are junctions seeming incorrect).

**Comment by Regalis11** [comment]
I think the junction boxes are supposed to break when they're connected like this. See the pic: the reactor supplies power to the junction boxes marked with the orange arrow, but there's only a few pumps connected to the boxes which means that they're receiving thousands of kW of power with barely any load.

![sdfgsdfh](https://user-images.githubusercontent.com/14351070/37083505-62b6f5f6-21f8-11e8-8c10-252a471efd47.png)

**Comment by NilanthAnimosus** [comment]
Alright, just the loads don't seem right so its rather hard to determine why that was occuring.

They also did not break in previous versions of barotrauma, nor appeared to show loads that seemed correct. this used to be a virtually unburnable submarine and its creator wasn't sure as to why.

**Comment by Billsofat** [comment]
The reactor supplies power to the batteries. All of the sub get its power from the batteries. Those arrows don't look quite right, the pumps are not hooked directly to the reactor. They get their power from the batteries.

Previously, the reactor showed the load of all 20 batteries (a lot), plus the sub load. That would be at least 13-15k, sometimes higher, depending on how much they were running the engines. Either way, the reactor would want to run at full 10000 power. That worked fine- The batteries would charge from the 10k, and the sub would only take what it needed from the batteries.

Previously, it seemed like all boxes showed the full load- I don't know if that was supposed to happen, but the sub worked fine and didn't burn out. Now, the boxes show different loads. I don't think that's caused by the sub machinery- but I don't know. It just doesn't seem right, because the reactor, and the boxes to charge the batteries don't show the battery load.

The boxes, which showed odd loads, would all be taking a certain amount of power (seemed like a weird amount), and they would fry pretty quickly. First the pump boxes would go- then a lot of other boxes, including the ones in the upstairs electrical room would fry and often catch fire. The electrical room is after the batteries, and thats where most of the sub machinery is hooked up to.

Also, the relay on the reactor floor between the two boxes is turned off. That would directly connect the reactor to the grid-but I disabled it, as I only want the grid to get its power from batteries.

Overall, it just doesn't seem quite right to me. I can't figure out what's happening with the power and the load.

**Comment by Regalis11** [comment]
The sub doesn't get all it's power from the batteries. Those junction boxes in the picture receive power from both the batteries and the reactor, but the only things consuming power in that circuit are the pumps connected to the bottom-right junction box. So the boxes are getting a huge amount of power from the reactor while the pumps consume next to nothing.

The boxes that charge the batteries also seem to be showing the loads correctly (see the pic below), so I'm kind of confused about this. Have you tested it on the latest version of the code (or any version after commit e15fad6), or do these problems only appear in v0.8.0.4?

![asdfthrtht](https://user-images.githubusercontent.com/14351070/37099137-502457aa-2228-11e8-94ec-f0263b9787b2.png)

**Comment by Billsofat** [comment]
I have that commit, I was having these problems on the latest github as of yesterday. The sub works fine in 0.8.0.4.

As for the loads, that screenshot does look better, maybe I was looking at the box after the batteries yesterday.

I’ll take a look at the wiring when I get home. I thought I had everything going through the batteries, maybe I forgot a wire still going to the reactor.
