### ISSUE TITLE
Linux/Pulseaudio: audio output cannot be moved to a different device

### ISSUE THREAD

**Issue by tanriol** [Regalis11/Barotrauma#3237]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
With Linux / PulseAudio the Barotrauma sound streams cannot be moved to a different output device, unlike any other app I've seen.

**Steps To Reproduce**

Find a Linux system with a Bluetooth headset.

Install and start Barotrauma.

Try to switch the sound output between the built-in output and the Bluetooth headset (using `pavucontrol` or the applets provided by the desktop environment). Observe that it does not work (in my case it was always on the built-in output).

**Version**
v0.9.10.0 Linux (Steam)

**Comment by PJB3005** [comment]
This is because Barotrauma uses OpenAL Soft which by default disallows being moved between Pulseaudio devices.

Sticking
```ini
[pulse]
allow-moves=true
```

into `~/.alsoftrc` should fix it.

(at least, I ran into this with OpenAL before and already have this in my OpenAL config now and it just works for me so...)

(See https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample)

**Comment by mygamingaccount** [comment]
I expect to be able to move any sound source to any device, it seems weird to me that OpenAL would by default not allow moves.

**Comment by PJB3005** [comment]
One possible reason is that OpenAL does a bunch of specific configuration based on the device it targets (sample rate, HRTF, etc...) and moving it can cause that to become suboptimal.

**Comment by mygamingaccount** [comment]
Here's the upstream bug report from the OpenAL library: https://github.com/kcat/openal-soft/issues/316
