### ISSUE TITLE
Game can stay running after quitting

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3284]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game process sometimes stays active after quitting.

**Steps To Reproduce**
No known reliable steps to repro

**Version**
v0.9.10.0 and later, probably earlier versions as well

**Additional information**
Seems to happen because sprites try to request disposal in the main thread after it has stopped processing tasks:
![5678ftgh](https://user-images.githubusercontent.com/14351070/86464420-22ed0b80-bd38-11ea-9015-d0d78f2c5529.png)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d8083c01d02c375feb8168f2116edac7c2de88a

**Comment by Rokvach** [comment]
Considering how rarely this happens its impossible to measure if anyone will encounter this again, will need to just wait for the feedback from the masses later on. The change hasn't affected the current game in a negative way so I will just close this ticket. We can re-open it if this issue is sighted. Closing.
