### ISSUE TITLE
[unstable] Overwriting railguns & coilguns breaks their scale setting

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3290]
- This most likely affects other items as well.

Attempting to apply overwrites to railgun and coilgun turrets causes all submarines with modified railgun and coilgun scales to revert to their default, which can break some submarines.

**Comment by Regalis11** [comment]
This is sort-of intentional: the other option would be to always use the scale values defined in the sub file, which would also break some submarines and mods. For instance, if you replaced the railguns with another item that's set to 1.0 scale, the items in existing submarines would still be in 0.5 scale.
