### ISSUE TITLE
[Unstable 0.10.2.0] Mission giver speech bubbles aren't removed after getting all the missions

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3291]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c5065ce7-4c54-42fc-bdda-7fcd832a0d52)

**Comment by hubismal** [comment]
this is kind of an anomaly, it should be noted that you couldn't even highlight rhonda jones the way you could highlight non-mission givers. think this is something more than just not removing the bubbles, you couldn't interact with her at all on my end.

**Comment by Kaillera** [comment]
Seems to be when other ppl picks up the mission instead of you.

**Comment by Regalis11** [comment]
Yeah, this seemed to happen when another client went through the conversation. The actual interaction would get disabled despite the icon remaining visible, which was why the NPC became non-highlightable. Steps to repro:
1. Start a campaign round with clients A and B
2. Find an NPC with the talk icon
3. Go through the conversation(s) as client A
4. The icon should disappear on client A's end, but remain visible on client B's end.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/32f81709b56f83b39c71afae866d58920399dd14

**Comment by Rokvach** [comment]
No issues, closing.
