### ISSUE TITLE
0.10.2.0: After choosing "create new" char in tab menu ingame, you will be assigned new char every single round

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3292]
at the beginning of every round, a new character will always be chosen for you if you discard the old one and create a new one through the tab menu. in effect a new character is never truly creatued.
made in a rush during testing

Reproduce:
start campaign online, do whatever.
in TAB menu, discard character. change the tabs in the TAB menu, and go back to refresh the character tab so you see the char preference options.
proceed to a new round either by docking/undocking to an outpost, and you will have your brand new character. however in the TAB menu's char section you will see that it's still on the preference selection mode, meaning no new character was actually created. As new rounds start, you will always be assigned a new character.

**Comment by Regalis11** [comment]
Could be related to https://github.com/Regalis11/Barotrauma/issues/3287

**Comment by EdusFF** [comment]
Was a client-side error with the subsequent characters being treated as discarded on every round after editing, fixed in: https://github.com/Regalis11/Barotrauma-development/commit/91596e51c98068a72a337db22be10cb0ff6d2790

**Comment by Rokvach** [comment]
You can now create a new character for each round rather than when your current character dies, this can be used to duplicate items and you can keep creating new characters and re-docking to the station and in return spawning in a new set of starting items. 

This might of always worked like this but I only now noticed how easily it can be exploited with the new setup.

**Comment by Rokvach** [comment]
Made a new ticket about the above, this is working correctly. Closing.
