### ISSUE TITLE
XML-based missions

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#33]
Instead of hardcoding the criteria for each mission, we should be able to assign certain starting conditions and goals that each mission type should have.

For example, the salvage mission requires an artifact to be onboard the main sub and the main sub to be at the end waypoint. So, it would be possible to represent that criteria like so:
```xml
<MissionType name="Salvage">
    <StartingConditions>
        <Spawn itemType="Artifact" location="Ruins" name="objectiveItem" />
    </StartingConditions>
    <VictoryConditions>
        <IsOnboard target="objectiveItem" />
        <AtEndWaypoint />
    </VictoryConditions>
    <FailureConditions>
        <CrewIsDead />
    </FailureConditions>
</MissionType>
```

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
