### ISSUE TITLE
0.10.2.0 Campaign: Make ships start slightly away from outpost

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3302]
[Qol Feature Req]
Almost everyone frequently misclicks and redocks by accident. Especially confusing if you're a new player and you undock to see a big pulsing dock button that's screaming "click me".
Might be a duplicate, sorry if it is, wasn't able to find duplicate issue.

**Comment by Udrakan** [comment]
I admit its a bit misleading and Ive keep getting bamboozled all the time.

**Comment by Regalis11** [comment]
Solved this by adding a confirmation prompt instead (https://github.com/Regalis11/Barotrauma-development/commit/5dc7ff1ddebf89aec62086e09705a4bff6e23fa2). Spawning the sub further from the outpost is not as reliable, because a sub with incorrectly configured ballast could still float close to the outpost when the round starts.

**Comment by Rokvach** [comment]
No issues, closing.
