### ISSUE TITLE
Mirrored levels become unmirrored when reloading the save

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3311]
Tested on both singleplayer and multiplayer, happens on both

Repro steps:
1. Start a salvage mission (artifact or wreck)
2. Take notice of the level layout
3. Bring mission artifact onboard the sub
4. [Singleplayer] Kill your entire crew
4. [Multiplayer] Die and wait the 60 seconds for round to end
5. [Singleplayer] Press "Load game" on round summary
5. [Multiplayer] Press "Continue" on lobby
6. Notice that the whole layout of the level has changed

(Looks like zenhubs image certy has expired, click the missing image)
Before:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9d517dd5-1f4a-4ea2-b642-4f08afbd0d85)

After:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e2599962-00ec-4998-8f26-7db19ff34ccc)

**Comment by Regalis11** [comment]
Could not reproduce by following these steps.

Before:
![before](https://user-images.githubusercontent.com/14351070/86767102-28a66200-c054-11ea-8d4b-2ff11cc48aea.png)

After:
![after](https://user-images.githubusercontent.com/14351070/86767114-2cd27f80-c054-11ea-8277-f68c2da9a0f0.png)

**Comment by Rokvach** [comment]
Looks like the level gets mirrored

Before:
![image](https://user-images.githubusercontent.com/7299826/86768002-84bdb600-c055-11ea-91f5-126e8a16a322.png)


After:
![image](https://user-images.githubusercontent.com/7299826/86768026-8d15f100-c055-11ea-9a60-69ee59bec28b.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91e56d6.

Steps to repro:
1. Start a round in a mirrored level. You can see if the level is mirrored or not by putting a breakpoint in Level.Generate or in the server log when playing the MP campaign. If it's not, you can teleport to the end of the level and start a new round through it "backwards" to get it to mirror.
2. Kill you crew and load the previous save, or quit to main menu and load the save

**Comment by Rokvach** [comment]
I wasn't able to reproduce this anymore, looks to be working correctly. Closing.
