### ISSUE TITLE
[Unstable 0.10.2.0] Campaign mission is still available after you fail it

### ISSUE THREAD

**Issue by Dexo21** [Regalis11/Barotrauma#3322]
**Description**
Explosive cargo mission still appears after failing catastrophically.

**Steps To Reproduce**
Long story short, selected explosive cargo mission, explosives exploded right at the start of the round, went back to the outpost, and even though the mission failed, you can try to do the same mission again. I don't know if this is intended or not.

**Version**
Unstable 0.10.2.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91928368033fba95a789b437e00cf69c9616a692. Now cargo missions get removed from the list of available missions when they fail, and same for salvage missions if the item is retrieved from the ruin/wreck but not delivered to either outpost.
