### ISSUE TITLE
Bots - Welder bot tries to get unreachable suit while reachable suits are available

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3332]
**Description**
Title

**Steps To Reproduce**
Have a suit in a locked room.
Cause a leak
Order bot to fix it
**Version**
Unstable
**Additional information**

![image](https://user-images.githubusercontent.com/59519434/87050846-1c123d00-c1ff-11ea-96ed-8739c637eceb.png)

**Comment by itchyOwl** [comment]
It seems that this was a more general level issue with the get items objective: if the bot couldn't find a path to the best valued (usually the closest) item, it always failed to find the other items. There was a couple of reasons for this, but it should now be fixed in Regalis11/Barotrauma-development@06d884b.

Better late than never!

I also made some improvements to finding items. The bots should now in general be slightly faster in finding the items, especially while doing high priority tasks.

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate, no issues noticed 👍

**Comment by Rokvach** [comment]
Closing
