### ISSUE TITLE
Aggressive crew's AI

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3340]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing a single player campaign, I noticed that bots react aggressively to a number of situations.

1) I had to regain consciousness of one of the crew members. The first thing he did when he was able to get to his feet was to shoot me with a machine gun. As a result, my team has two half-dead fighters instead of one.

2) While repairing the hull, I accidentally hit by welding the captain who was standing nearby. After that, he grabbed the revolver and ran towards the only reliable shelter - ballast! Already from the ballast came curses and calls for protection. It would be funny if it weren’t sad that the captain was running away from the welding assistant.

3) Sometimes bots seal doors when the room is very small, and the hole is behind the door at a distance allowing it to be repaired.

**Version**
0.10.04.0

**Comment by itchyOwl** [comment]
1) needs addressing (probably an oversight), 2) shouldn't happen (needs testing, could be a bug), 3) is a known issue.

**Comment by itchyOwl** [comment]
1) Is fixed in Regalis11/Barotrauma-development@0a55629.

**Comment by itchyOwl** [comment]
I'm not sure how to repro 2). In order to react defensively (arming oneself) the bots need to receive at least 20hp cumulative damage by the same aggressor. And they also constantly "forget" the damage. The damage from the welding tool is so low that it should be impossible to trigger the defensive (or aggressive) behavior by torching the bots. Only the security officers should react aggressively, that is arresting/attacking the aggressor, if they do more than 10 hp cumulative damage. Additionally I found a bug that practically makes it impossible for the bots to react defensively when they are being torched.

**Comment by itchyOwl** [comment]
Not been able to reproduce 2. 3 is reported in #3335. That leaves 1 to be tested (should be fixed).

**Comment by Rokvach** [comment]
Confirmed working, closing.
