### ISSUE TITLE
Allow StatusEffect conditionals to target a different entity than the target of the StatusEffect

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#336]
I don't know how to even ask... For example, I want to make sure that the bandage heals the Player when his health is less than 30. When it is larger, the bandage will clean only the bleeding.
If this was already written somewhere, I didn't notice.
<Conditional Health="lt 30"/>

**Comment by CryIz** [comment]
I'm trying to make a delay in using the subject for myself, but I can't figure out how to do it. Or this game is not provided?
    
<MeleeWeapon canBeCombined="true" slots="Any,RightHand,LeftHand"
              aimpos="5,0" handle1="-5,0" holdangle="10" reload="3.0">
      <StatusEffect type="OnUse" target="This" Condition="-100.0"/>
      <StatusEffect type="OnBroken" target="This" Condition="50" delay="3" checkconditionalalways="true">
        <Conditional Condition="gt 51"/>
      </StatusEffect>
      <StatusEffect type="OnUse" target="This, Character" health="3" duration="5.0" checkconditionalalways="true">
        <Conditional Health="lt 30.0"/>
      </StatusEffect>
    </MeleeWeapon>

**Comment by CryIz** [comment]
Now that I think of and I have another question. Is there any way to track the condition of an item inside another item? For example: Rods in the reactor, the energy that is produced by the reactor, etc.
I want to make it so that when reaching a certain temperature, the core started to wear out faster.

**Comment by Regalis11** [comment]
The latest response ever:
The upper one should work with one small change: the last status effect should not target the item itself, otherwise it will check the health of the item as well as the character. 

The second one is still not possible: you can make StatusEffects target a contained item using Contained as the target, and Parent if you want to target the container that the item in question is inside. Unfortunately it's not (yet) possible to make the conditionals target another entity than the one the StatusEffect targets.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
