### ISSUE TITLE
[Unstable 0.10.4.0] Crash log 

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#3371]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Somehow in the middle of the level I crashed. No idea what it is.  And it seems that I am the only one who crashed.      Submarine I'm using is a remora with bots, I'm not the host in a multiplayer game.  

**Steps To Reproduce**

**Version**
Unstable 0.10.4.0

**Additional information**
![602960_20200716023359_1](https://user-images.githubusercontent.com/62313026/87617055-797e2080-c70e-11ea-859f-3be2db202ddf.png)
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4928843/crashreport_object.log)

**Comment by Dimsim1** [comment]
wtf is dildor the defender of porn?

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/96fdb83d1bcd699cd763a81d192a2b322156a3d1

Steps to repro:
1. Start a multiplayer round
2. Open the tab menu and select the "mission" or "character" tab
3. End the round and start a new one
4. Open the tab menu and stay in the "mission" or "character" tab
5. Join/disconnect with another client

**Comment by Rokvach** [comment]
Wasn't able to reproduce, looks to be working correctly. Closing.
