### ISSUE TITLE
Programmed turret rotating more than 180 degrees attempts to rotate through rotation limits

### ISSUE THREAD

**Issue by TheWetFish** [Regalis11/Barotrauma#3394]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Programitically feeding position data into a turret that causes more then 180 degrees of change will cause the turret to attempt to take the shorter rotation direction, even if this direction is outside the bounds of the turret rotation.

**Steps To Reproduce**
- Add turret such as Searchlight, with base rotation 0, rotation limits min -225 max 45
- Add circuit to pass data into Searchlight position_in
- Pass in position_in data 190
- Wait for turret to rotate to 190
- Pass in position_in data 360
Anticipated behaviour: Take rotational limits into account and rotate clockwise to 360
Actual behaviour: Rotate counterclockwise and stall at rotational limit -225

**Version**
Confirmed in version 0.9.10.0

**Additional information**
Attempted to create searchlight that would automatically track back & forth.  If the amount to rotate from current position to target position is 180 degrees or less then turret rotates successfully, as expected.  If the amount to rotate from current position to target position is greater than 180 degrees then turret will attempt to take least rotational distance path.

**Workaround**
More complicated automation circuit which sets the turret position to move between three points instead of two; a min, a midpoint and a maximum.  This can avoid the turret ever needing to rotate more than 180 degrees to it's target position.

**Comment by Regalis11** [comment]
Personally I don't think we should change how the turrets/searchlights interpret the signals; they angles have been wrapped to a range of 0-360 since the very first versions, and I have a feeling changing it now would cause some side-effects in older subs.

There are several other ways you could work around the issue in this case: you could for example pass the searchlight a signal that oscillates between -225 and 45 instead of going past 180 degrees or use a modulus component to make sure the value is in the correct range.
