### ISSUE TITLE
Multiply componenet fails when multiplying by fractions

### ISSUE THREAD

**Issue by Shikareth** [Regalis11/Barotrauma#3428]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It looks like multiplication by fraction is bugged. In both circuits in attached image result after round component is the same but next operation yelds different results.

**Steps To Reproduce**
round(x * 100) * 0.01 - results with original number
round(x * 100) / 100  - results with correct number.

**Version**
System: Windows(x64) 10.0.19041 Build 19041
Barotrauma: v0.10.4.0 (rev. 20132d25fb)

**Additional information**
![image](https://user-images.githubusercontent.com/16690152/88786770-381c5500-d193-11ea-85d3-34d51016134a.png)

**Comment by Regalis11** [comment]
This happens due to inaccuracies in floating-point arithmetics (see https://0.30000000000000004.com/). Sort of similar to how 1/3 cannot be easily represented as a finite decimal number, but has to be represented as 0.33...

Changing this would require huge changes to the way the game handles the signals and calculations (we'd probably have to switch to fixed-point math which would pose it's own problems), so I don't think we should do anything about this since the inaccuracies are so small they shouldn't make a difference in practice.
