### ISSUE TITLE
Completing Mudraptor egg traitor objective immediately ends round

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#3436]
**Description:** Completing the Mudraptor egg traitor objective immediately ends the round. Since the entire point of this objective is to create chaos by spawning a Mudraptor on the ship, having the round immediately end before anyone ever sees the Mudraptor seems like an oversight.

**Build:** Stable (New Frontiers)

**Comment by Regalis11** [comment]
The mission should only complete if you manage to keep the mudraptor alive for 2 minutes, so it seems the mission is bugged.

**Comment by Regalis11** [comment]
I was not able to reproduce this: the mission does not seem to complete at all, because the egg never hatches (it becomes small again when it reaches the final stage). I suspect that something else caused the round to end.

Fixed the hatching in https://github.com/Regalis11/Barotrauma-development/commit/292fb312e4ee8c5ce1823ac1f38fb60c29796188

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
