### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Richiebattags** [Regalis11/Barotrauma#3469]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

granted i am tired and maybe missed it.

**Description**
Randomly when modded or unmodded, when moving between levels on campaign we run into an error that seems to arise from changing levels.

**Steps To Reproduce**
Sadly it seems random. I can't seem to recreate it at will.

**Version**
Game version 0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5013013/crashreport.log)

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/5991963c9ca85104b564da36f5aeea3f145a4bf0. I couldn't find a way to repro this, but I strongly suspect it was a race condition that happened when the round summary was trying to add warnings to the debug console from another thread while it was being updated in the main thread.

**Comment by Rokvach** [comment]
There hasn't been any reported cases of this happening, as there is no clear steps to test this out, I will just close the ticket and re-open if the issue does come back. Closing.
