### ISSUE TITLE
Delivery Missions to Natural Formations Un-Completable

### ISSUE THREAD

**Issue by Bomtaker01** [Regalis11/Barotrauma#3470]
- 

- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Accepting a mission to deliver to a natural formation cannot be completed, Probably because there is no outpost to deliver to

**Steps To Reproduce**
Accept a Delivery mission (Chemical/explosive/medical/ clown etc) in which the destination is a natural formation

**Version**
v0.10.4.0, Windows 10

**Comment by mygamingaccount** [comment]
On the top of the screen a button will pop up that will let you enter the formation.

I still think this is a bug.

**Comment by Swato85** [comment]
Personal experience - SOLVED.
Simply when on the spot where the formations notification pops up, just click it and choose new location to go. The quest will complete and you will start new voyage. principle is the same as with docking, you just dont have anything to dock to in order to spend some time before missions so yoou jump directly into next one, therefore at lest from my point of view, htere is no problem with this.

**Comment by Regalis11** [comment]
Swato85 is correct: you don't need to dock to an outpost, you can just open the map and select a new destination to complete the round and the mission.
