### ISSUE TITLE
Barotrauma Outpost old-gen bug

### ISSUE THREAD

**Issue by V1Htor** [Regalis11/Barotrauma#3495]
**Description**
Outpost has spawned like the old one (From ol versions). No crew quarters, no reactor, not even an airlock.

**Steps To Reproduce**
i don't know how, i just playing campaign with my friend. here is save (Aphotic pleateu 41%-45% diff.)

[FFinally.zip](https://github.com/Regalis11/Barotrauma/files/5024971/FFinally.zip)

**Version**
Windows10, 0.10.4.0

**Comment by rico6822** [comment]
Maybe this can be fixed by completely removing data of how outposts originally generated from the game so only new format would be picked during random generation?

**Comment by Regalis11** [comment]
> Maybe this can be fixed by completely removing data of how outposts originally generated from the game so only new format would be picked during random generation?

This was added as an intentional fallback in case generating the outpost fails for whatever reason (e.g. all required outpost modules are not available, the required modules can't be connected to each other). Normally this should never happen unless you do some modifications to the outpost generation parameters or outpost modules, so we need to look into what's causing it here.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/de0fc30ef002c1c7c862a84df5acab5f36914dfc. There might still be some seeds where the mines fail to generate, so let's keep an eye out for this.

**Comment by Rokvach** [comment]
No issues, closing.
