### ISSUE TITLE
Game window dissappears when using alt tab in fullscreen mode

### ISSUE THREAD

**Issue by Skippeh** [Regalis11/Barotrauma#35]
Setting GraphicsDeviceManager.HardwareModeSwitch to false solves the problem, but i think that's just because it's borderless fullscreen instead.

Is this a MonoGame bug perhaps?

Edit:
It is:
https://github.com/MonoGame/MonoGame/issues/5885

Possibly fixed by updating monogame

**Comment by TotallyCoded** [comment]
I am also experiencing this bug

**Comment by z3nf1n1ty** [comment]
I have the same issue. Does anyone else have any details on performance drawbacks/limitations to using the borderless fullscreen, if that is in fact the case?

**Comment by Regalis11** [comment]
Copypasting this comment here too:

This is an issue in MonoGame 3.6. It has apparently been fixed, but the new version of MonoGame has not been released yet so we'll either have to wait or switch to the in-dev version of MG to fix this bug. But until then you should be able to work around the bug by using borderless windowed or windowed mode instead of fullscreen.

**Comment by juanjp600** [comment]
Added workaround to this in https://github.com/Regalis11/Barotrauma/commit/2f6cb84b5e238c034801513128f216568c828ceb
