### ISSUE TITLE
host and game slow down

### ISSUE THREAD

**Issue by Zthespook** [Regalis11/Barotrauma#3538]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A clear and concise description of what the bug is.   game slows down with every mission completed  roughly 2 missions in campaign and playing is slower for host by 2-4x. 
[lag issues.zip](https://github.com/Regalis11/Barotrauma/files/5049683/lag.issues.zip)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
win 7,   frontiers update 8/10/2020 stable.
**Additional information**
mods used  but prior to recent update mission count went well past 50 with mods.

**Comment by EtiamNullam** [comment]
Have you tried if its better if hosted on a different machine? Is it better without mods or on a different save?

It might be worth tracking the memory usage of the game, if it takes more and more the longer the game is running you might be subject to a memory leak. I've never played with so many mods but this "fix" should help you with memory leak caused by corrupted custom submarines: #3553
