### ISSUE TITLE
Improvement on the crew command menu and orders to improve npc task management - Feature Request

### ISSUE THREAD

**Issue by charly140** [Regalis11/Barotrauma#3571]
-A fixed list of crew that can be modified by click and drag, this way will be easier manage crew orders, its really hard to manage a list that changes every time you give an order.

-Show the face of the npc on the crew command list, you are using multi-international names that players will have problems identifying crew members by name when u have up to 12 sailors on the sup.

-Orders prioritization configuration up to 3, if order first fixed leaks, if no leaks he will repair broken systems, if no broken systems manage the reactor, instead of orders history where I can have an npc passive in front of broken devices because he has only fix leaks command.  

-Order to make an npc fill oxygen tanks and recharge batteries, or if he is on passive mode for certain time he will do it automatically. I usually have my crew with a toolbox with basic tools, oxygen mask and 3 oxygen tanks but I notice that when they use them they drop them, will be better if they keep them and when they enter passive mode they will go and fill them or exchange them for fully ones at the oxygen machine avoiding redundant micromanagement. Also give a grace period so the don’t go all at the same time to fill oxygen.

-Order report status, so the npc will tell you the health condition or what are they working on, this will make feel the crew more alive and interact able also avoiding checking one by one. 

-Maintain orders given across missions, every mission I have to give the same orders to every npc before sailing just keep the commands given across missions. 

-Better fuel rod exchange, make the npc put the full one then take the empty one at 5% avoiding the power cut, what’s the point of having a full time npc on the reactor if the power will cut and the sup will crash and go brrrrrr.

-Key binding to send crew to combat position on guns, lets say you have a small crew and you cant keep them full time on guns but you could send them all to guns positions, previously assigned with a single click and send them back to work with the same key.

-Different color and more dramatic messages on the radio chat when and npc is having health problems or cant reach fixing holes so u can see what’s going on, sometimes they are stuck or bugs happening, IA will never be perfect give us the tools to support and avoid unfair deaths. 

-Show guns on submarine sonar image with little orange dots, this will be easier to maneuver on combat and maybe even made them change color when not being operated.

**Comment by itchyOwl** [comment]
Thanks for the feedback. Some comments below.

I too would like the crew list to be fixed or an ability to make it fixed.

The faces were visible in the old UI. I'm not sure why they were removed here, but I have to agree with you that faces can make the selection easier.

Order prioritization has been under consideration. But it would make things more complex in many regards. The idea is that you wouldn't have to micro manage your crew too much: they should do things autonomously too. In the next update the bots should already be much smarter than they are now.

Filling oxygen tanks and recharging batteries is on the todo list.

Persisting orders is something we might want to consider. Yet I wouldn't implement it now. I'm not entirely sure it's a good idea, because then you would often need to clear your orders, which is something you easily can forget. The usefulness of persisting orders also depends on how much you use them. And that in turn depends on how much you have to order your crew (instead of letting it act on it's based on it's own judgement).

Fuel rod exchanging is intended to be optimized so that the bots would use the fuel entirely or almost entirely up before seeking another rod. It's also bad if the bots use only 95% of the fuel, but they actually do start looking for another rod before the current rod is out of juice. The power cut can happen when the rod is far away from the reactor, so what you can do is to ensure that there's enough rods near the reactor. I considered making the bots take a spare rod in the inventory, but that easily leads to annoying issues like bots hoarding too much fuel in their inventories. I'm sure there's room for improvement here still.

There was an option to set the bots man the guns and hold fire. Can't remember why it was removed. I think we need to bring it back. General level buttons like "arm yourselves" or "man the guns" are not so simple to design as they first sound. For example, you would probably need some means to define who should man the guns and who should keep fixing things, operating reactor etc. Perhaps the order would order all the bots without an active command to man the guns? Worth considering, but needs more design.

**Comment by ezjamsen** [comment]
Faces were actually removed due to the fact that during inhouse and community testing, we found them to not contribute anything to recognition of characters, and in fact to create a more cluttered interface.

**Comment by ekqvist** [comment]
> There was an option to set the bots man the guns and hold fire. Can't remember why it was removed. I think we need to bring it back.

It was removed in Regalis11/Barotrauma-development@ccdafba. The reasoning was that, based on feedback, it was rarely used. Removing it allowed us to remove an extra step from ordering people to operate guns and gave us an easy way to also declutter the "minimap" screen for subs with large amount of guns on them.

**Comment by un-hunt** [comment]
I guess it can be a good idea to add numbers instead of the faces for characters of the same class, so you can easily remember them. It's much faster to find 2nd engineer in the crew list than recognizing his face among others.

**Comment by ekqvist** [comment]
I can see how the crew list order getting changed can increase confusion. I disabled the automatic sorting in Regalis11/Barotrauma-development@5664c90. Let's see how it feels now. I also agree that some sort of way to manually change the list order might be a good idea, needs a bit of thinking.

**Comment by jacobgrey** [comment]
Might I suggest, as a way of approaching several of these items, creating a crew posting system/interface where you can manage/define duties which are to be assigned to each crew-member on an ongoing basis? Assign a crew member default duties, maybe a primary and secondary, and then use the current orders system to override these in the moment. This could mean simpler requirements for managing bot downtime, as it would narrow their "focus" and allow you to make more assumptions about what the player wants them to do, based on the post assigned to the bot.
