### ISSUE TITLE
Debug Console Error on Startup

### ISSUE THREAD

**Issue by FIBBIDEH** [Regalis11/Barotrauma#3597]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Attempting to overwrite a prefab item assembly results in a debug console message upon all subsequent game starts.

in my particular case:

Error registering "Diving Suit Locker", "divingsuitlocker" (BarotraumaItemAssemblyPrefab): base already exists; try overriding

Barotrauma v0.10.4.0 (releaselinux, branch release, revision 965c31410a)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/126e7b62948d47165f0260db7fc1a7ded639b381. For now you could work around the issue by saving the assembly with a different name - overriding assemblies is not really that useful anyway, all it does is hiding the original assembly from the sub editor.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
