### ISSUE TITLE
docking with a shuttle lets you inside a ghost outpost instead of ending round on mission mode

### ISSUE THREAD

**Issue by bananaofhell** [Regalis11/Barotrauma#3604]
- [x] I have searched the issue tracker to check if the issue has already been reported.

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using an escape shuttle thats attached to a submarine and docking at the end outpost does not end round

**Steps To Reproduce**
Go on a multiplayer server, Grab an escape shuttle thats attached to a submarine and fly to an outpost then dock, on a cargo mission, do not bring cargo with you

**Version**
Windows, v0.10.4.0

**Additional information**
I was not the server owner but the server owner was the one who docked

**Comment by Regalis11** [comment]
This is intentional. The vessel with the most living players inside it needs to dock with the outpost for the round to finish. Otherwise it'd be easy to grief by stealing a shuttle and forcing the round to end by docking.

**Comment by SpencerDawson** [comment]
What about survivors that escape with scooter? We had a fantastic session, where we were dropping like flies due to some sabotage while trying to salvage a falling sub going to crush depth. One of us got away as a lone survivor, made it to the station, and got inside, but the round wouldn't end. There needs to be some other conditions for a round to end outside of a ship docking.

**Comment by Regalis11** [comment]
I completely agree that in that situation the round should've ended, and I assumed it would have if everyone in the sub was dead. Although, that's only if you're playing a single mission; in the campaign mode you always have to bring some vessel to the destination. I'll reopen this and take a closer look at the end conditions.

**Comment by SpencerDawson** [comment]
In our scenario, there was a single crew member left alive, but they were paralyzed with no resources for us to fix him, so he eventually expired before the last player go the the station. This was, in fact, a campaign.

I noticed there is still a dummy terminal in the ghost station. We did technically complete our mission, which was kill a moloch, so perhaps letting there be an interface to acknowledge that the mission was completed trigger an jump to the station? Most missions give enough to buy a dugong, so perhaps just opening to a menu to purchase a submarine (or buy a new one if the credits are available).

In the event that a new sub can't be purchased, providing a trigger for a hard ending would be nice as well (just make it a big ol' "retire" button, you just survived hell!).

**Comment by hubismal** [comment]
On the subject of not being able to pay for another sub and being stuck without a sub, it might be fun to design a "debt event" that has you go into major debt with the coalition in order to get a large discount from the sub purchase npc (maybe just design an action type that gives you a free shitty sub and create a SetDataAction that tracks how many marks you owe). 
Having players struggle with crippling debt would provide a "nice" multi-mission progression goal that players have to work towards over multiple missions instead of the somewhat drab endless cycles of missions that exist now. Might also be nice to have events where collectors intimidate, harass, and harm crewmembers while the debt is not paid.

**Comment by Regalis11** [comment]
This is mostly implemented now (although not in the way we'd originally intended). You can ditch the main sub, and then later return back to the level to retrieve it. There's still some issues remaining (see https://github.com/Regalis11/Barotrauma/issues/4610), but I think there's no need to keep this ticket open anymore.
