### ISSUE TITLE
Oxygen Tank Shelf (the large one) scaled wrongly

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3615]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Large oxygen tank shelf seems to have a scale issues. Default scale when placing it down is 0.6 and it looks too big for the oxygen tanks, the golden cylinders are not inside the bottles like on the small oxygen tank shelf. When scaled down to 0.5 the size seems right, but the bottles placed inside have a small offset and look out of place.

**Steps To Reproduce**
Place down oxygen tank shelves and take a look.

**Version**
v0.10.4.0 Windows

![image](https://user-images.githubusercontent.com/48099798/90967210-33ba3200-e4dc-11ea-80ae-01acbbca4d26.png)

**Comment by Regalis11** [comment]
Looks like the scale has been 0.6 for a long time (or always), and that they're positioned using a scale of 0.6 in all the vanilla subs. I decided to leave the scale unchanged because changing it would make the items misaligned in existing subs, and instead fixed the positioning of the tanks and suits in https://github.com/Regalis11/Barotrauma-development/commit/49850b9d8dbf6408e426ea19ec9939b01cd7f89d.

**Comment by Rokvach** [comment]
No issues, closing.
