### ISSUE TITLE
Interaction with waters sensors not included in server logs

### ISSUE THREAD

**Issue by Torvald118** [Regalis11/Barotrauma#3619]
[✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We didn't find any logs about how players interact with the (water) sensors.

**Steps To Reproduce**
Please, put an echo on that to server journal.

**Version**
v0.10.4.0
Windows 7

**Comment by Regalis11** [comment]
What kind of interaction do you mean specifically? Changing the input/output settings?

**Comment by Regalis11** [comment]
In any case, changing the settings is now logged: https://github.com/Regalis11/Barotrauma-development/commit/0cfcde17d66b06b7be8f60d1ee7a8c1f27c2837c. Applies to all items with editable properties (e.g. signal components, light colors).

**Comment by Rokvach** [comment]
Could we move the item property changes under its own filter? Currently it can really spam the log when a player changes the values as it creates a new log entry for each value change. So being able to filter out the property changes could help out keeping the log a bit easier to read, because for example seeing if someone is messing around with the reactor is a bit bigger issue than someone just changing the color of a light

Other way to handle it would be to only log the changed value when the player changing the value closes the interface, but that would however leave some room to unnoticed griefing if for example player messes around with the values and returns  them to the original ones before closing out of the interface. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1961ddb3-921d-45eb-a802-e5d432958a9f)

**Comment by Regalis11** [comment]
I'm a bit reluctant to make it a separate setting because this is so closely related to the other "item interaction" logs (the difference essentially being that you're adjusting the item's settings from a different menu than the default device interface).

I changed it so that the line isn't logged until the value has stayed unchanged for 1 second, which should heavily reduce the spam at least in cases where you're "sliding" the value across some range (like the light color with the plus/minus buttons). What do you think, does it still seem excessive?

**Comment by Rokvach** [comment]
Its a lot less spammy now, looks good. Closing.
