### ISSUE TITLE
Morbusine doesn't kill monsters

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3639]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 The morbusine achievement to kill something with it doesn't flag the achievement according to players. Also it doesn't kill any aliens either.

**Version**
0.10.4

**Comment by EtiamNullam** [comment]
Was going to report it as well. It won't flag the achievement probably because it causes no direct damage and only kills indirectly by causing oxygen deprivation for players and apparently doing completely nothing for all the aliens. Pretty weak for the hardest poison to craft (and supposedly strongest) in the game, eh?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3f949ef0f03e9a6118b5b6e1d8bf3232c84181d0

**Comment by Regalis11** [comment]
Nvm, only fixed the achievement not unlocking. Will need to look into killing aliens.

**Comment by itchyOwl** [comment]
Fixed in [feature/poisons](https://github.com/Regalis11/Barotrauma-development/tree/feature/poisons).

**Comment by NilanthAnimosus** [comment]
Tested against Feature/Poisons commit https://github.com/Regalis11/Barotrauma-development/commit/693b612aeea8d01afa810b9e97c55743a339375c, no issues found, closing.
