### ISSUE TITLE
Unable to place electrical components on "Structure"-type background decoratives

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3654]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to place electrical components on "Structure"-type background decoratives. We really should be able to though.

**Version**
0.10.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97cd875a34d877a09842a3eddb90041689a4836f. I didn't make them attachable to _every_ decorative background structure though, only the ones that look like solid walls you could reasonably bolt something onto. Things like curtains, decals, random decorative clutter, etc still can't be attached to.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
