### ISSUE TITLE
[0.10.501] R-29 Problems

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3679]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
R-29 has:

1. Bad Waypoints
-The top docking port doesn't lead out of the sub properly due to mislinkage.
-Left door of engineering isn't door waypoint.
-Door of reactor room isn't door waypoint.
-Can't reach the far right end of both ballast tanks.
-Not enough waypoints on the upper platforms in cargo hold to walk inbetween them.
-Has hard time walking on the lower platforms in cargo hold. There should be a set on the lower platform and below it.

2. No power wire to top docking hatch.

3. Also for some reasons, I can't assign bots on the guns for this sub. I had to give them contextual order from the periscope to do so.

4. It also have the unbalanced default nuclear reactor.

5. The cargo hold is VERY dark even with the lights on. I suggest increasing the searchlights range from 300 to 500. People can't inspect cargo that dark.

6. A lot of the lamps and emergency lights aren't possible to be interacted with.

**Version**
0.10.501

**Comment by danielasteljoki** [comment]
Tuned waypoints and reactor, wired docking port power in d7fd193. Bot gun assignment seems to broken elsewhere too. Cargo lighting will be revisited when we get the correct cargo containers etc.

**Comment by ekqvist** [comment]
Created a new ticket (#3691) for the inability to give the Operate Weapons order

**Comment by Flotilla-zz** [comment]
Bots on R-29 are all desperate to find diving suits, right from the start of the round. No hull breaches.

![20200903054052_1](https://user-images.githubusercontent.com/3611705/92099558-a6fb5800-eda8-11ea-8476-b7ed12316241.jpg)

**Comment by rav2n** [comment]
I think it will not be quite right for me to stand aside, although on the other hand, the submarine is no longer entirely mine.

2. Remora doesn't have it either ...
5. I think the problem of lighting is related to the change in in-game units of measurement, since the version that I sent to the competition also had a value of 300, but the light reached the floor. The optimal value is 480 for the current version.
6. As planned. In part, I do this so that the players do not accidentally touch the light bulbs while trying to interact with something that is nearby. And also so that other players do not twist the colors into bright and acidic ones from which the eyes hurt. While the latter may not be fair to deprive players of that joy.

I would also like to add that due to the recent replacement of textures, many elements on the submarine will not be displayed quite correctly. And in general, given the significant expansion of the possibilities for decorating submarines, it looks a little empty (or is this still not the final version of the appearance?)
Below I attach the file of the updated version, perhaps it will be of interest to you (fixed of waypoints, fixed lighting, fixed elements that shifted due to new textures, I did a little work on the decor, changed the energy parameters of the reactor and engine).
[R-29.zip](https://github.com/Regalis11/Barotrauma/files/5167911/R-29.zip)

**Comment by ezjamsen** [comment]
I don't believe this sub has been through an art pass yet as most of the others have, but it will come.

**Comment by danielasteljoki** [comment]
@rav2n Thanks for updating the sub. We'll use the new version you shared as the basis for our art pass. 

On another note, the power connection in Remora's docking port has somehow slipped my attention. We might as well connect that one, too.

**Comment by rav2n** [comment]
Happy to help!

**Comment by Rokvach** [comment]
- [ ] Portrait on a Medium Steel Cabinet is rendered above characters
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d8c0f91f-3c89-40bc-8092-b4348dea858b)

**Comment by Rokvach** [comment]
Informed @danielasteljoki about the above issue, I don't think its big enough to keep this ticket open when everything else seems to be fixed. Closing.
