### ISSUE TITLE
[0.10.501] Bot swam into R-29 cargo hold while it was flooded, drowning himself.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3681]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was being attacked by a swarm of threshers from the mission while in R-29. Despite there being 6 suits on the sub and only 4 characters alive, engineer bot on Repair Damaged Systems swam into the cargo hold all over the place while it was flooded with no suit or mask. He drowned himself, but I was able to save him with CPR. I believe there were safer rooms to be in.

**Version**
0.10.501

**Additional Informations**
I also had a medic who suffocated in the cargo hold before the engineer earlier in the level, but I thought it was probably a fluke caused by bad waypoints. Didn't see what he was doing there while the room was flooded.

**Comment by itchyOwl** [comment]
I'd like to say that "it happens". But it's not straightforward as that. There are multiple possible causes for this that I can think of. But it's difficult to say whether this is a bug or just stupid behavior. In order to identify the cause, I'd need the steps or at least a screenshot with the debugai information.

**Comment by itchyOwl** [comment]
I think it's impossible to fix this with the current information. The issue could be due to multiple causes. It's also possible that this is already fixed. So, let's close the ticket.
