### ISSUE TITLE
(Dev build) Clothing still appears on character under diving suit. 

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#369]
Maybe worn clothing just needs to be hidden with suit on?

**Comment by Regalis11** [comment]
A lot of the stuff on the dev branch is experimental and subject to change (especially in the UI), and there's a lot of known issues that I haven't bothered fixing until we settle on one way to implement things. This is one of those, although now that I think about it, being able to wear a diving suit without taking your clothes off is such a useful addition that it should be kept in any case and this issue fixed.

**Comment by Billsofat** [comment]
Ah. So the bug was actually the ability to put it on over clothes?  Interesting.

Anyways, do you want me to not make dev branch reports?

**Comment by Regalis11** [comment]
Being able to put it over clothes was an intentional addition, but it also requires the clothes to be hidden which I haven't gotten around to doing yet.

Dev branch reports are more than welcome, even if some of them happen to be known issues it doesn't hurt to have a reminder about them in the issue tracker.
