### ISSUE TITLE
A separate set of items for the Traitor.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#371]

**Comment by Jackel64** [comment]
Do you mean like the traitor weapons in something like Garry’s mod TTT?

**Comment by Regalis11** [comment]
This could be an interesting addition, but we would need to be careful not to make it an easy way to identify traitors. If every traitor simply spawns with a specific set of items, there's the risk that every traitor round will start with the security stunning everyone and searching through their inventories.

**Comment by CryIz** [comment]
Russian community in online games has always been full of idiots.
We have our own server on which Players anymore no reason to sink the submarine or killed.

**Comment by Jackel64** [comment]
You could do it like garry’s mod TTT and have a buy menu deal that they can buy it part way through the match or they buy it at the beginning and it gets hidden somewhere like in a air vent or in a bunk or somewhere that people normally wouldn’t mess with

**Comment by CryIz** [comment]
That's funny. You can add a separate spawn to the submarine editor with your Traitor item list. It's like, because submarines are different.

Yandex translator.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
