### ISSUE TITLE
[0.10.502] StartGame has failed! Bot Deletion.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3712]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Right now is a good version to fix bot deletion caused by "Startgame has failed!" error from #3711.

**Steps To Reproduce**
1. Start a multiplayer campaign on P2P with a few bots
2. Save it
3. Load the save into lidgren dedicated server
4. Get the StartGame has failed error and end the round on the server
5. Go back to P2P and reload the save

All your bots are now gone

**Version**
0.10.502

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3e2356583f19685174c49e33d4f2d206031c557. 

This doesn't seem to be related to the "StartGame failed" error, can be reproduces as follows:
1. Start a new MP campaign
2. Return to server lobby
3. Save and Quit
4. Reload the save

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
