### ISSUE TITLE
Bots with autonomous action of powering up reactor keeps trying to turn on reactor when docked to outpost

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3747]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots with autonomous action of powering up reactor keeps trying to turn on your submarine's reactor when docked to outpost and your submarine is actively getting power from the station. This wastes fuel on the submarine when you're at the station. Especially worst in 0.10.502 where all the roles will now try to keep flipping it on.

**Version**
0.10.502

**Comment by ekqvist** [comment]
Fixed as of Regalis11/Barotrauma-development@7fe71c2 in dev. The autonomous objectives defined in Jobs.xml now support attribute `ignoreatoutpost` which defaults to false but sets the priority to 0 in outpost levels if set to true. It is now set to true for the autonomous objectives of operating reactor.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by itchyOwl** [comment]
The abovementioned commit caused also the reactor operators to ignore reactors in outposts. Keep in mind that autonomous objectives are used for both NPCs and the AI crew. Fixed in Regalis11/Barotrauma-development@287c509.

Moved back to QA. Steps to test the reactor operator issue:
1. Start the campaign
2. Type "debugai" and "freecam"
3. Observe the behavior of the npc characters. There should be several with "operate reactor" objective, until the reactor operator starts operating the reactor, after which there should only be one operator. Before the fix none of the npcs attempted to operate the reactor.

**Comment by Rokvach** [comment]
Working correctly, closing.
