### ISSUE TITLE
Bots - Doesn't refill coilgun loaders with the nearest ammo box / ammo box shelve from itself.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3751]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Watching for a while now, but I noticed that bots tends to grab ammo boxes from the highest point of the sub or something, Instead of grabbing ammo from shelves or on the floor nearest to itself. This causes a lot of downtime.

The minor exception is the top right gunnery in Kail Terra where if you store ammo boxes in the armory, that one will be taken. Very rarely I see them refilling with other shelves.

![Capture](https://user-images.githubusercontent.com/5086682/92386202-51dd8000-f0e1-11ea-953e-3cdb577a4591.PNG)

**Version**
~0.10.502

**Comment by itchyOwl** [comment]
I gave it a brief test and can't see anything wrong with it: the bots usually prefer the ammo that's closest. They give a penalty for moving in Y-axis (like with all the action), because that requires using the ladders, which is slower. So according to my tests, the bots choose these routes when they reload the turrets:
![Screenshot_1.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/80335b56-693d-45f0-ad5e-e1bb087740e7)

![Screenshot_2.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/43b7f804-fb84-489e-a9a8-29bbf830cd21)

Finding items uses the same code almost in all the bot behavior, so if there are issues here, they should be fixed. However, I didn't notice any issues on their behavior: they certainly don't prefer the "highest point" in the sub. They do prefer to keep on the same level though. It's possible that that penalty might need adjustments.

**Comment by Regalis11** [comment]
No known steps to repro? Should we close this?

**Comment by itchyOwl** [comment]
I think we should.
