### ISSUE TITLE
[0.10.505] Multiplayer(?) - Half the time the outpost runs out of fuel, NPC are stuck in "Get Item" state.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3808]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Half the time the outpost runs out of fuel, NPC are stuck in "Get Item" state and won't put a new rod in. They also seem to pick up spent fuel rods on the floor. Not sure if it's multiplayer only.

**Version**
0.10.505

**Comment by itchyOwl** [comment]
They should spawn the fuel rods, if (and when) they can't find any.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@e5e2f69.

I'm pretty sure that tickets #3808 #4106 #4044 are all about the same issue: the bots failed to make the difference between empty and non-empty items. This was the case with fuel rods and I'm pretty sure that it's the same thing with the coilgun ammo too. It's basically the same code, so fixing one should fix the other.

Steps to repro:
1) Make the fuel rods/ammo boxes empty (easy in the sub editor)
2) Insert the empty item in the reactor/turret loader
3) Order a bot to operate the item
4) See how the bot gets stuck in the "Get Item" state. In a debug build the console floods "Removing SUBobjective get item of contain item, because it is completed"

So basically a part of the code told the bot to use only items that have some juice in them, but another part of the code the bots were told that empty items are good enough (just because the default value was 0 and not 1).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
