### ISSUE TITLE
What if every medicine was unidentifiable until level 35 Medical?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3820]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was thinking since it's so easy to steal the medic's job just by having the meta knowledge of what each medicine do, what if we just make every medicine like this until level 35 Medical? :
![638401615690465340](https://user-images.githubusercontent.com/5086682/93029817-25979700-f5ec-11ea-894b-ddefb4589947.png)

You can fabricate medicine to guaruntee what they are, but until then you would have to rely on medics to identify them, or testing out medicine sound and effects.

**Comment by EtiamNullam** [comment]
I think its a really good idea but why 35 medical for everything? I say you would need for example 75% of skill required that is required to apply successfully to identify it. Talented engineer could identify morphine but not fentanyl or deusizine.

Also I think its very cool how ADOM does it with potions, but not sure how to apply that for multiplayer especially across multiple missions on campaign: every potion has random appearance on start and you have to identify or try it to find out.

**Comment by Kaillera** [comment]
When it comes down to it, all you really need to know is Bandage, Morphine, and Saline at the bare minimum. The idea was to curb using the correct medicine to give more importance to medic.

**Comment by Ek-Videogames** [comment]
Unfortunately I think this logic breaks down completely considering that the concept of 'labels' exists and also by looking at something any reasonable person would probably be able to tell the difference between a bandage and 20 bottles of cyanide.

**Comment by thegrb93** [comment]
I like this, but I think should only apply to antidotes

**Comment by EtiamNullam** [comment]
@Kaillera
> Stuff like Fentanyl and Deusizine is really just a better version of them, and are used interchangeably at the moment too.
[...]
 you would probably know it's one of them since there's not really any high level medicine in the game

Applying them incorrectly still can lead to death of patient or waste of resources. For example applying `Deusizine` instead of `Fentanyl` to a fire victim will make it worse and `Anabolic Steroids` to someone that was just outside fighting monsters and nearly died but situation got stable could be a waste.

>chances for poisons to be mixed in with the current auto fill distributions.

Auto-fill can be changed and people tend to make mess anyway so it could lead to funny situations.

@thegrb93 

> I like this, but I think should only apply to antidotes

Maybe it would be better if you could tell if its antidote, bandage-like or drug without enough skill as they all could possibly look different.

@Ek-Videogames 
> By looking at something any reasonable person would probably be able to tell the difference between a bandage and 20 bottles of cyanide.

See above. I have no idea why you bring 20 bottles of cyanide instead of one other than _reductio ad absurdum_ from your side though.

> Unfortunately I think this logic breaks down completely considering that the concept of 'labels' exists

By "labels" u mean label on a syringe? Medicine is often made crudely on a sub so it might not even be labelled correctly and drug description could be too complex for inexperienced people (low medical skill) like captain that usually has some other people to do it for him.

**Comment by hubismal** [comment]
The sprites literally have labels on them. This would make playing without a medic even worse than it already is. Right now it only takes one morphine usage for a low skill player to almost certainly overinject themselves and get an addiction. I don't think the medicines themselves need to be made any harder to use.

**Comment by EtiamNullam** [comment]
@hubismal:
Of course sprites have labels, but these could be made visible only to a skilled medic. That's exactly what this issue is about.

Is playing without medic really that bad? Overdosing with morphine and addiction from it is the least problem while healing unless you do it on purpose or lack knowledge. Actually addiction should have greater impact.

Almost all of the medic job in this game is knowledge based. High skill is only useful to waste less resources and do CPR more efficiently. Also its good to have someone dedicated to helping people, but its always better to have someone unskilled but with knowledge do the healing rather than some newbie medic.

It should be harder because its very simple now. I hope and expect there will be some medical overhaul. This idea is about making it more interesting for skilled players and make medic more important for them.

**Comment by Kaillera** [comment]
Currently it's just that it's too easy for non medic to save everyone, except for the captain who needs to dedicate quite a lot of time to get medical up.

**Comment by LuCKySoZ** [comment]
I agree it's just too easy to perform well without a medic. It should be more punishing not having a medic. Like anything that you inject would cause bleeding (injecting a blood pack wrongly should make things worse), having the necessity to use bandages. A medic could perform the injection without bleeding. Monster bites could cause an infection affliction, that is lethal at 100% (fuzzy vision, slow speed, speech impairment), that would require antibiotics (glue or broad spectrum). The fact that the only virus/bacteria is Husk makes it "simple". Taking care of crewmates should absolutely require a Medic. It doesn't even have to be implement in Casual mode, just Serious mode.

Or just create a Tryhard Mode, where every crew is essential, where the penalty of not having enough level is not just bad, it's super bad and sometimes lethal. No engineer? Electric stuff will absolutely kill you. No mechanic? Mechanical stuff will absolutely kill you. (BTW the fact that a mechanic fixes a nuclear reactor is crazy, maybe require both electrical and mechanical level?). No medic? You're absolutely killing yourself or others during treatment.

The professionals should either have a much greater advantage or the non-profs a much greater disadvantage

**Comment by ezjamsen** [comment]
Medical system will be overhauled in the future
