### ISSUE TITLE
Flamers cause the game's framerate to drop massively when hitting AI outpost crew

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3834]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you are hitting an AI outpost member (tested on them, might work on other AI or mobs) with a flamer, the game will enormously chug. This does not happen if you are just firing in the air randomly. The more AIs are in the way, the harder the game suffers. The chug ends immediately when you stop firing

**Steps To Reproduce**
- Spawn an Outpost and a ship with a Flamer on it
- Grab Flamer and find a crowd of people
- Fire at crowd of people directly with Flamer
- Powerpoint presentation mode is on

**Version**
V0.10.5.0 Unstable Build. Windows 10

**Additional information**

Outpost crews don't seem to be bothered at you casually firing your Flamer in the Outpost, even if you start fires doing it, as long as you don't directly hit crew

**Comment by Regalis11** [comment]
Seems to occur because damaging the NPCs reduces your reputation, which refreshes the prices store view. This isn't a problem in most cases, but the flamer does continuous damage to each individual limb, and causes the view to be refreshed over a dozen times per frame.

The changes in https://github.com/Regalis11/Barotrauma-development/commit/cd737f9c179ab22eced291cdec87fb4d3c5d8eff which were implemented to fix Regalis11/Barotrauma#3825 seem to have fixed this one as well, moving to QA.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
