### ISSUE TITLE
[0.10.5.0] Dedicated Server - You get a different character depending on which IP you connected to the server for local host

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3836]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you host a dedicated server on your local machine, you could connect to it in a variety of addresses. Depending whether or not you consistently use the same address, you get a new character if you don't.

**Steps To Reproduce**
1. Host Dedicated Server.
2. Join Dedicated Server through server lobby or your router address like 192.168.1.10 for example.

Your current character is tied to 192.168.1.10 endpoint.

3. Rejoin the server via direct IP connect with 127.0.0.1 or loopback

You get a new character tide to .1 endpoint instead.

**Version**
0.10.5.0

**Comment by EtiamNullam** [comment]
I'm pretty sure it happened to me a few times on 0.10.4.0 or on version before it.

**Comment by Regalis11** [comment]
In a sense this is intentional: when Steam authentication is not being used, we use IP addresses to differentiate between players. I'm not sure what'd be a good alternative: if we considered any local address to be the same player, it'd be impossible to play the campaign in a local network with more than one player.
