### ISSUE TITLE
An idea for adding teams in the combat mission

### ISSUE THREAD

**Issue by Joman2k** [Regalis11/Barotrauma#386]
I think it would be a good idea to have a way to change or choose which teams are put together when doing a combat mission in multiplayer, so people can have tournaments and such, or you can guarantee that you are going to be on the same side as a friend.

**Comment by chesse20** [comment]
the game mode needs to be removed entirely

**Comment by TheGoldenGuardian** [comment]
Why is that? I think a PvP gamemode is great, no reason to just completely remove the thing.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
