### ISSUE TITLE
The problem of "balance".

### ISSUE THREAD

**Issue by Tpo9H** [Regalis11/Barotrauma#3866]
1) Some monsters are too strong. In particular, "shark tiger" (large). It damages the hull with a catastrophic speed, and when 10 of them attack at once, the game is lost by 101%. This monster needs a global rework (reduction of movement speed, attack and damage).
2) Why do you use "scripts" to spawn monsters in the game? Why do monsters appear from scratch? This was verified and I even filmed this moment on video when a group of monsters appeared where I had already been and explored everything. And they immediately attack me. It shouldn't be that way, I consider it a scam.
3) Why doesn't the reward for tasks (missions) increase with progress? I took on the task of killing moloch, and there were 3 of them, and on the way I met 10 "shark tigers" (large). Such a task is simply not economically feasible.
4) Why do monsters attack too often? I moved much quieter (didn’t even turn on sleep during the mission) and it didn’t reduce the frequency of attacks. I even moved with maximum noise and the frequency of attacks remained the same. Most likely because of your "scripting" mechanics described in point "2".

ps This is all about "Company" (single player).

On Steam, I posted a negative review. The previous version of the game was more comfortable.

**Comment by Regalis11** [comment]
Thank you for the report!

1. If by "shark tiger" you mean the bone threshers, we're aware that they're a bit too difficult to kill at the moment. We noticed a while back that their armor had been configured incorrectly, making them much more durable than we intended.
2. I'm not sure exactly sure what you mean, would you prefer that all monsters were spawned at the start of a round instead of when you progress further into the level? We're spawning the mid-round for multiple reasons: first of all, we have more control over the difficulty when we can spawn them at moments when there's not much else going on, and it's also better for performance when every single monster doesn't need to be loaded simultaneously. However, you should not be able to see them spawning "out of nowhere".
3. The rewards are relative to the difficulty of the objective (i.e. killing that one specific moloch), not the other difficulties you may or may not face during the mission. While I agree that the mission rewards (and most other aspects of the campaign) still need balancing, I'm not sure if we should increase mission rewards just based on how far you are on the map.
4. The spawning logic isn't affected by the amount of noise you make, the monsters spawn at semi-random points during the level. I would suspect something in your submarine was making enough noise for the monsters to spot you, perhaps the reactor or the engine? There's 2 ways you can see what's making noise in your sub, one is to look at the sonar display with passive sonar enabled: sources of sound show up as blue blips inside the sub (the bigger and brighter the blip, the louder the noise). If you want an even better idea of what's making noise, you can use the console commands "toggleaitargets" and "debugdraw" to enable a debug overlay that shows the noise ranges as circles around the devices.

But any case, I'll close this ticket, since this issue tracker is mainly intended for bug reports, not this type of open-ended feedback. I'm sorry you found the balance issues severe enough to give the game a negative review, but hopefully we can improve on the balance in future updates and make the game more enjoyable to you again.
