### ISSUE TITLE
Creature AI target entities through shell

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3891]
**Description**
This mudraptor was modded to prefer doors so it will breach the submarine through airlock. This worked pretty well in previous patches, but new behaviour could use some tweaking. It's attacking the outer shell because it goes for the interior doors which it shouldn't see, while dugong's airlock is right next to it.
![image](https://user-images.githubusercontent.com/59519434/94048681-28587000-fdd4-11ea-8ae7-467bfd83214b.png)
 <ai combatstrength="210" sight="0.75" hearing="1" aggressiveboarding="True" fleehealththreshold="0" aggressiongreed="20" aggressionhurt="300" attackwhenprovoked="True" avoidgunfire="True" enforceaggressivebehaviorformissions="True" targetouterwalls="True" randomattack="True">
    <target tag="door" state="Attack" priority="180" reactdistance="0" attackdistance="0" />

**Steps To Reproduce**
Make doors maximum priority for creature
Spawn creatures around the submarine exterior
Notice how most of them go for the shell anyway, because they try to target interior doors (which they shouldnt see)

**Version**
Stable

**Additional information**
Targetouterwalls=false seems to make creature not attack airlock doors and hatches, not sure if intentional

**Comment by itchyOwl** [comment]
It's intentional that the monsters can see through walls. There's no visibility checks. It has caused issues and I'm not fully convinced that it was a good decision (initially not mine). But it's also very simple and efficient and produces purposeful behavior.

In the picture you can see that the mudraptor aims for the windowed door, but can't reach it, so it attacks the wall between it and the target. Just as it should.

Setting Targetouterwalls false is meant to be just that. Currently I think only Terminal cells use that.

**Comment by itchyOwl** [comment]
Actually, there might be a bug here, because the doors make an exception in that the creatures should only target outdoors/hatches if they are outside. Also Targetouterwalls shouldn't make the creature ignore doors totally. Only the outdoors.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@65804aa. Thanks for reporting!

**Comment by Rokvach** [comment]
I didn't notice any issues, seems to be working correctly. Closing.
