### ISSUE TITLE
Crash report: singleplayer campaign

### ISSUE THREAD

**Issue by Aktheon** [Regalis11/Barotrauma#3896]
**Description**
Crash report (first crash in recent 12 months, lol)

**Steps To Reproduce**
Was playing campaign, solo (without bots). Sub got trapped between Talamus and small Thresher swarm (Tiger and Bone)

**Version**
10.5.1

**Additional information**
Windows 10

crash log below
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/5273880/crashreport.9.log)

**Comment by Regalis11** [comment]
This seems to happen when using a repair tool on some target triggers a raycast (such as killing/destroying something with the tool causing an explosion). There may be other ways to repro this, but an easy way is to kill a terminal cell with a welding tool.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/84b751c225f0dce8edfabeda171efa474c992a79

**Comment by Aktheon** [comment]
yes, i actually killed termo cell with repair tool

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore. Working correctly, closing.
