### ISSUE TITLE
Logic and Math Wiring Operators

### ISSUE THREAD

**Issue by Umbrias** [Regalis11/Barotrauma#392]
**Idea Request**
Could be pretty low priority, but in general, subs would be highly optimized and more accessible if wiring logic was introduced. A variety of very basic signals modules, generally all single usage but very basic math and logic operators.
Ideas, because why not.

- [x] Adder
Adds values inputted together, negative or positive, outputs sum.

- [ ] Sign Flip
Flips the sign of a value inputted, outputs value.

- [x] Multiplier
Outputs product of inputs.

- [ ] Inverter
Outputs inverse of input.

- [ ] Power
Outputs say, input 1 to the power of input 2

- [x] A > B
outputs boolean
- [ ] A >= B
outputs boolean
- [x] A = B
outputs boolean
A and B both inputs

- [ ] Constant
Outputs a constant, can be modified by a set.

- [ ] Function
Takes one or more inputs and runs it through a function, i.e. f(x). Nothing could ever go wrong implementing this.

It certainly isn't a high priority feature, however, it would be incredibly helpful for sub design and for sub optimization, and nobody seems to have officially suggested it yet, so this is really to just put it on the radar.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
