### ISSUE TITLE
Game crash after c.a 5 minutes in multiplayer v0.8.1.2

### ISSUE THREAD

**Issue by ColdDead** [Regalis11/Barotrauma#396]
I have the problem only since the v0.8.1.2 and do not know why whenever I want to play with people in a lobby crashes the game. I do not know why and why in the main menu, no crash happens only when I'm in a game.

Something with mamory error it is previously spammed in the console but unfortunately too slow to screen it

**Comment by Regalis11** [comment]
Could you post the "crashreport.log" file from the game's folder (assuming there is one)?

**Comment by ColdDead** [comment]
Unfortunately not available I will try again

**Comment by Regalis11** [comment]
Damn, so I'm guessing the game crashes with the generic "Barotrauma has stopped working" windows error instead of the "if you'd like to help fix this bug, please post the report" message box?

There's a way to save the debug console output to a file by setting "savedebugconsolelogs" to "true" in the "config.xml" file, but I'm not sure if that'll help here, because if saving the crashreport fails the game probably won't be able to save the console output either.

**Comment by ColdDead** [comment]
Mhhh... no crashreport
