### ISSUE TITLE
Allow outpost exclusive songs to be moddable

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3976]
[Feature Req, Code]
Right now you can only set the outpost song for the research outpost with 
```xml
  <music file="Content/Sounds/Music/The Eerie And The Unknown.ogg" type="research"/>
```
the internal parsing only recognizes research outpost:
![image](https://user-images.githubusercontent.com/47284081/94835531-59065e00-0401-11eb-8f67-c239305ef5de.png)
...so it would be nice if you could do something like
```xml
  <music file="Content/Sounds/Music/The Eerie And The Unknown.ogg" type="location:moddedlocationidentifier"/>
```

**Comment by ekqvist** [comment]
Yes, I agree. This was a fairly quick solution to get the first outpost-specific track into the game and could definitely be improved. We just have to keep in mind that we cannot assume that every location type has associated music tracks, as I commented on the code. But yes, should be improved. I'll give it more thought next week.

**Comment by ekqvist** [comment]
This should be at least partially addressed now. I changed the code so that it will work for any location type identifier which has any music tracks defined for it.

![image](https://user-images.githubusercontent.com/16864465/98360559-b14d0300-2032-11eb-8d99-11f5fd05399d.png)

If the music tracks are defined as above, it should work now.

**Comment by hubismal** [comment]
awesome, thanks.

**Comment by Rokvach** [comment]
No issues, closing.
