### ISSUE TITLE
Server browser ping is incorrect

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#3985]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The server browser ping does not match the actual ping in the game.  Australian servers are listed as 50 ping in the server lobby despite in the game being  over 250.

**Comment by Regalis11** [comment]
This is a side-effect of how SteamP2P handles connecting to servers. They use intermediary servers to relay information between the clients and the server to bypass the need for port forwarding, which in some cases can result in a larger-than-expect ping when the data gets passed through some external server (and there's very little info on where these intermediary servers are located or how exactly the Steam backend chooses one).

Because of this, it's very tricky to reliably determine the ping in advance: we'd most likely have to make the clients actually connect to the servers to discover the real ping (and even that might not be enough, because when you actually join the server to play, some other intermediary server might get chosen). So I'm afraid fixing this might be more trouble than what it's worth, at least now when there are so many more urgent issues on the table. Marking as low prio, we may take a look into this later during the development.

**Comment by Pingerfowder** [comment]
Hey if this could be reopened, as I'm still having issues where servers listed as 10-40ms are actually getting around 300ms once connected.

Maybe if there would be a way to filter games by region that would help alleviate the overall problem.

**Comment by Regalis11** [comment]
As said in my previous comment, we unfortunately can't really do much about the issue in the case of servers hosted via SteamP2P. There is also no way to filter games by region in the Steam API.
