### ISSUE TITLE
Failed To Connect Error

### ISSUE THREAD

**Issue by QadenV** [Regalis11/Barotrauma#3995]
Hello! Me and a friend just got the game and decided to try playing together with other friends, we launched the game and decided to skip the tutorials because we like to learn through experience. We went to join a friends lobby and it wouldn't allow us to connect. We tried a public lobby to test to see if we can connect at all and we cannot. But when one of us host's a server, the host and our friends can connect except for the other one of us. We both are having the exact same issue, and have looked into other posts, and see possible firewall blocking and have looked through and allowed it through the firewall but the issue seems to persist. Also another post talked about file integrity and files are fine and we did reinstallations multiple times and modified files to try and fix the issue. We are both running the game on windows 10 and game version 0.10.5.1 I'm hoping you can get back to me on an easy fix for this issue! thanks!

**Comment by Regalis11** [comment]
Hello!

Unfortunately the current public version has a bug that prevents the players from seeing the actual reason for why they weren't able to join (so the players just see the generic "couldn't connect" error message). We've listed some common workarounds in our Trello board, could you let us know if any of these help? https://trello.com/c/t91YqiUc/324-workarounds-included-issues-with-connecting-to-servers-since-latest-update

In any case, I'm sorry for the trouble! We've got a fix for this coming up in the next patch that should hopefully resolve the issue.
