### ISSUE TITLE
The submarine can UNDOCK when the submarine moving

### ISSUE THREAD

**Issue by martin1194** [Regalis11/Barotrauma#3996]
**Description**

The submarine always only "undock button" in the navigation terminal when the sub was undocked. It can't show the descent velocity, velocity and depth while the submarine moving.

**Version**
0.10.5.1 Windows7

The submarine and shuttle file in Google drive. The link as following.
https://drive.google.com/drive/folders/1MfyMhjI8ss9G2LXm1QT30rN8bP6oleyD?usp=sharing

**Comment by Regalis11** [comment]
This happens because the navigation terminal is connected to three different docking ports: if any of them are docked, the undock button is visible. I would recommend using the customizable buttons in the navigation terminal to toggle docking with the shuttle (they're under the "CustomInterface" section when editing the nav terminal).
