### ISSUE TITLE
Farther turrets lights range

### ISSUE THREAD

**Issue by un-hunt** [Regalis11/Barotrauma#4061]
Though "Enhanced periscopes" should be one of the best upgrades, it is useless now and the reason is that coilgun and railgun lights range is too low, so it's impossible to see something farther than lights range allows.
So, my suggestion is: make turrets lights range farther, please.

**Comment by ezjamsen** [comment]
This shouldn't be a technically difficult task should it?

**Comment by Regalis11** [comment]
@ezjamsen, no, simply increasing the range of the LightComponent should do the trick. So for example
<LightComponent range="+15%"/>

**Comment by Ek-Videogames** [comment]
Whoever wrote the light component code might have to add their input here, because I know for certain that there is a hardcoded limit on light range value of 2048. The game always clamps it no matter how you try to increase the range of the light, intentional or not.

**Comment by ezjamsen** [comment]
Implemented.

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Regalis11** [comment]
@Rokvach how did you test this? The range doesn't seem to increase because as Ek-Videogames mentioned, the range gets capped to 2048. I also feel a 2% increase is way too little; a fully upgraded turret only gets an extra ~200 px to the lighting range, which is very hard to even notice and nowhere near enough to cover the whole visibility range.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c469c5698df41fcfe9def1fa4363a7db09919914

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by un-hunt** [comment]
Still isn't fixed.
