### ISSUE TITLE
Particle physics run using level coordinates, not sub coordinates

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4063]
[Issue, Code]
Couldn't find another issue pointing this out. The particles don't move and adjust relative to the frame of reference of the sub, so when the ship is moving rightwards, a flare inside will have all its particles drag to the left, as though it were on top of the ship or something. This breaks a lot of particle related effects for vanilla content and modded content alike. Most obvious with flares or smoke related items.

**Comment by Regalis11** [comment]
This is intentional: even though the particles exist in world coordinates, they inherit the velocity of the sub they spawn inside. So when inside a sub that's moving at a constant speed the particles should behave as if the sub wasn't moving, but when the sub is accelerating forwards for example, they should drag to the left. Based on a quick test they seem to be working as intended.
