### ISSUE TITLE
v0.10.6.1 (Unstable) Copying object/items in the Sub Editor doesn't copy it's contents when you paste it

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4080]
Description : 
Copying objects/items with something in its inventory will copy the object/item but not it's inventory when pasting it.

Steps To Reproduce : 
Place a railgun shell, place a item in its inventory, copy and paste it. (optional) place railgun shell(s) in railgun loader.

Version :
~v0.10.6.1 (Unstable)
![CopyBug](https://user-images.githubusercontent.com/72674994/96019402-10c65180-0e7f-11eb-8562-cad1e7125a36.jpg)

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/21fe235eb9752bb61818b1356e32c1abf1f66f87

Was caused because AddOrDeleteCommand always assumed that the content of the inventory should be cleaned up to prevent lingering items when deleting containers, restricting container cleanup behavior to only deletions fixed the issue.

Another issue that emerged was that pasting containers would fail a Debug.Asset when redoing and cause 2 sets of items appear, this was caused because pasting also includes items inside containers and AddOrDeleteCommand always assumes it's his job to handle container items (when you delete a container you are only selecting the container and not the items inside). That has been fixed too.

**Comment by Rokvach** [comment]
Tested, didn't notice any issues. Closing.
