### ISSUE TITLE
Translate the game

### ISSUE THREAD

**Issue by alextbw** [Regalis11/Barotrauma#41]
Hi. I am from Ukraine and i  _obviously_ like Barotrauma. I would like to translate it to Russian, but I keep getting errors, what should I do?

**Comment by Regalis11** [comment]
What kind of errors?

**Comment by alextbw** [comment]
When I just edit tools.xml, for example, I translate only the name and the desc of welding tool, i get this:
`Error in fabricable item Welding Tool! Item "fabricableItem" not found!`
btw, can I copy from console?

**Comment by Regalis11** [comment]
That's caused by the fabricators: the welding tool is still included in the config, but the game fails to find such item after you've renamed it. Unfortunately copying text from the console is not possible (yet?), but you could take a screenshot if there's a longer piece of text you want to show.

Also, there seems to be a bug in that specific error message. It should be showing the name of the missing item, so thanks for pointing that out. :)

**Comment by alextbw** [comment]
Ok, so how I can fix it? What should I edit?

**Comment by Regalis11** [comment]
You should open "Content/Items/Fabricators/fabricators.xml" and update the names of all the fabricable items to match the new names you've given to the items.

**Comment by alextbw** [comment]
ok. I'll try and post here about the results

**Comment by Regalis11** [comment]
It does not spawn because the sub files work based on the names of the items. The sub file says there should be welding tool there, but there's no such item anymore after you've renamed it. There's a workaround to this though: if an item with a matching name is not found, the game tries to find an item with a matching _alias_ instead. Adding `aliases="Welding Tool"` to the item config should fix your problem.

And as a heads-up: you'll definitely run into many similar issues when translating the game and some of them may not possible to fix without modifying the code and recompiling the game. There are also some hard-coded texts here and there, and changing those will require you to recompile it. So unless you are able and willing to look into how to compile the game and do changes to the C# code (or willing to settle for translating only some parts of the game), it might be a good idea to worth for official translation support.

**Comment by alextbw** [comment]
So item config should look like `<Item
    name="Паяльная Лампа"
    category="Equipment"
    Tags="smallitem"
    alias="Welding Tool"

    price="100"
    description="One of most important tools on board of a sub. Also works underwater.">`?

**Comment by Regalis11** [comment]
That looks otherwise correct but it should be `aliases` instead of `alias`. And if you need to configure more than one alias (e.g. due to some items already having an alias), you can separate them with a comma.

**Comment by alextbw** [comment]
I dunno why, but it doesn't work even if I define an alias. But if I change only the description it'll work fine. Ok, so I'll continue to work later

**Comment by Regalis11** [comment]
That won't work unfortunately, the name has to match exactly.
