### ISSUE TITLE
No Penalty for Running Machines Below Full Power

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#4107]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I can't tell whether this one is really intentional or not.  
I'll use the engine here for reference, but this appears to be present in many machines.  
When running machines, they have to receive power above minimum voltage to work: e.g. in the engine  
https://github.com/Regalis11/Barotrauma/blob/20a69375ca605688ac68f26f82f2635930141d3b/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Engine.cs#L106
If voltage is less than the min voltage, the force the engine is outputting will decrease. So far so good.  
At all voltages, a voltage multiplier is applied:  
https://github.com/Regalis11/Barotrauma/blob/20a69375ca605688ac68f26f82f2635930141d3b/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Engine.cs#L116
Here's a graph showing how this multiplier behaves
![image](https://user-images.githubusercontent.com/37539527/96578236-c274e080-12cc-11eb-90d1-889a0206bbb2.png)
On the x axis is the voltage and on the y axis is `voltageFactor`. As you can see, this has no effect on the engine's output above minimum voltage.

I spent a while thinking about this - it sort of makes sense. When the engine is being powered above its minimum power, it works. Below the minimum power, it slows down (but slower than if it was powered).  
However, I think this is unintuitive, ultimately. When players hear about a minimum voltage, they assume that minimum voltage is going to be slower than full voltage. Since this factor only affects how quickly the engine winds down to 0 force and not its output, it seems a bit strange to me. Since generally people experience giving the engine power, it behaves more like this
![image](https://user-images.githubusercontent.com/37539527/96579158-4e3b3c80-12ce-11eb-8e5c-6cedebc8097e.png)

The strangest bit, conceptually, is that between min voltage and 1.0 voltage, the engine uses more power... for no additional gain. It's effectively just eating more power for no reason. This leads to the power system providing a counter-intuitive learning curve - new players will try and maintain the sub at 100% power, since that's what the game directs you to do. Seasoned players know that running the sub at 100% power is the same as running it at 65%. Bizarre.

**Version**
0.10.5.1

**Additional information**
How could this be addressed?  
I have a few ideas, and I'm curious to see what you think about them.
1. Make it so that minimum power doesn't offer full output. Perhaps it should be relative to the voltage, or 0.5. But minimum power should not give full output.
2. Don't have a voltage factor. Currently the voltage factor is practically irrelevant. It could just be 1.0 and no one would notice.
3. Work out a new equation for voltage factor. Maybe square root, or similar? Something that starts at min voltage high enough, and scales up to 1.0 at full voltage.  

Sorry for the long issue to read. I'm genuinely curious to hear about this part of the game. Thanks for reading.

**Comment by Regalis11** [comment]
I believe this was an oversight: I can't think of any reason why it would've been implemented this way. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/574fc43972de687a9d858bad1308e35a6997de09.

However, I couldn't find this issue in any other item than the engines: all other devices seem to use the Voltage property directly.

**Comment by Udrakan** [comment]
I'll test fabricator, medfab and deconstructor to see the difference. Blue ones will run at 65% power, normal ones will run at full power.

Setup:
![image](https://user-images.githubusercontent.com/59519434/97779699-1199fb80-1b80-11eb-986b-d8ac2b741c9e.png)

-Lights on the devices are OFF.
-Deterioration on the devices is 0.
I will start stopwatch at the same time I press CRAFT on the device. I could setup a relay system to power the devices on at the exact same time, but I think it’s better to have the simplest setup possible, at the cost of small error that happens when I open the other device and click CRAFT less than a second later.

_**Fabricators**_
Item:				Ballistic helmet
Weapon skill			34

**Fabricator 1**
-crafting time [s]:		19      	
-energy consumed [kW]:	192 

**Fabricator 2**
-crafting time:			30
-energy consumed:		190

_**Medical Fabricators**_
Item:				Bandage
Medical skill			7

**Medical Fabricator 1**
-crafting time [s]:		60      	
-energy consumed [kW]:	144 

**Medical Fabricator 2**
-crafting time:			93
-energy consumed:		142

_**Deconstructors**_
Item:				Ballistic helmet

**Deconstrutor 1**
-crafting time [s]:		11      	
-energy consumed [kW]:	152

**Deconstructor 2**
-crafting time:			18
-energy consumed:		150

_**Conclusion**_
Crafting times are 65% longer with 65% power input. I don’t understand power well enough to make any conclusion, but I’ve included the data for you.

Im including the save so you can do the same test. It's comfy.
[Berilia Power Test.zip](https://github.com/Regalis11/Barotrauma/files/5469140/Berilia.Power.Test.zip)

**Comment by Rokvach** [comment]
No issues, closing.
