### ISSUE TITLE
Multiplayer lobby round-start desync into softlock.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4137]
**Known issue for multiple people but lacking information due to no relevant information appearing in logs when it happens**

When attempting to start the round, desync can cause someone to be kicked back into a broken version of the lobby with nothing loaded and unable to interact with anything on the lobby except for seeing the in-round chat updating inside the chat box correctly.

Sometimes the spectate button will appear, but it will be greyed out for some reason. More often though no buttons appear at all except for the 'ready' button.

![image](https://user-images.githubusercontent.com/55356135/97120661-1168ae80-16ef-11eb-89d2-c36f03b1426a.png)

![image](https://user-images.githubusercontent.com/55356135/97120678-35c48b00-16ef-11eb-8874-4300382e89c4.png)

**Comment by Rokvach** [comment]
I've seen this happen multiple times as well, but never had enough information to tell as to why it happens. Most prominent with the Equality Check Failed kick to lobby, when that happens the spectator button vanishes and only way to get access to it again is to rejoin the server. If you have access to round management permissions you will see a Start button instead of the Spectator button when this happens. Clicking the Start button doesn't do anything at that point.

**Comment by JoneKone** [comment]
It seems to be a Linux only issue. my window friends didn't seem to have an issue.

**Comment by JoneKone** [comment]
https://youtu.be/rVLJc_yDoy8

**Comment by Krzeszny** [comment]
https://youtu.be/1b7mZbHZCzU
Not a Linux issue. I got disconnected due to some desync and now I can't join even after restarting the game.

**Comment by Krzeszny** [comment]
There's no Spectate button but the round is in progress.

![Barotrauma_6hDkLPTsUi](https://user-images.githubusercontent.com/10529134/172059550-9eea0b2a-b13b-4319-9fa4-314a7c4da12a.png)

**Comment by Regalis11** [comment]
No known steps to repro, closing
