### ISSUE TITLE
Coil Gun's light and fire appear behind structures

### ISSUE THREAD

**Issue by Zead456** [Regalis11/Barotrauma#4155]
Yes I have searched the issue tracker to check if the issue has already been reported.

**Description**
Coil Gun's Light and fire appear behind structures. it seems that coil gun's light and fire both have the highest sprite depth which makes them appear behind structures.

**Steps To Reproduce**
The best way to solve this is by making coil gun's light and fire's sprite depth match their coil gun's sprite depth.
so for example if the coil gun's sprite depth is 500 then it's light's sprite depth should be 500 and it's fire's sprite depth should be 500 as well.

**Version**
0.10.5.1 (Windows).
![bandicam_2020-10-28_20-02-01-283](https://user-images.githubusercontent.com/73611847/97487160-29496800-1965-11eb-992a-641d5e893a89.jpg)

**Additional Information**
This issue also happens with rail guns so please consider fixing both guns.
When i saied fire above i meant decals that appear after shooting.

**Comment by Regalis11** [comment]
This is intentional: if the lights were not rendered behind the sub, they would have to calculate shadows to prevent the lights from shining through the subs walls, which would be quite performance-intensive for such a long-range light source that's almost constantly moving. 

If you absolutely need to make the light render in front of the sub, you can deselect the "draw behind subs" tickbox under "light component" when editing the coilgun in the sub editor.
