### ISSUE TITLE
Crash when using a linked Fabricator and Deconstructor

### ISSUE THREAD

**Issue by ContactOfSolitude** [Regalis11/Barotrauma#4160]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

When using a fabricator or a deconstructor that are linked to each other and "Display Side By Side When Linked" is true for both (I tested it with both)

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5461440/crashreport.12.log)

**Steps To Reproduce**

1. Link a Fabricator to a Deconstructor
2. Select "Display Side By Side When Linked" in both of the machines
3. As a Character, open any of the linked Items
4. The game Crashes

**Version**
 0.10.6.2 - Windows

**Comment by martinkors** [comment]
Proposed a fix. #4169

**Comment by Regalis11** [comment]
Thank you for the proposed fix, but it doesn't fully solve the issue: the GuiFrames will not be positioned correctly unless they're defined in the item's first ItemComponent.

Implemented a fix with a slightly different approach in https://github.com/Regalis11/Barotrauma-development/commit/37c86a770d5e46c91bc63522aa4cab482ea890a0 (finding an ItemContainer component with a GuiFrame instead of assuming it's always the first component).

**Comment by Xeavas** [comment]
[0.1100.0.1] Tested, unable to replicate.

**Comment by Rokvach** [comment]
Closing.
