### ISSUE TITLE
Minerals positioned outside of the level boundaries

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4219]
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/7aedbb948cba81208b030094443ee8579416d8eb

Screen: Level Editor
Level Type: greatseabasic
Seed: f43f3

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/00d2690a-28d4-423f-80e2-0a94640f54e5)

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@c358e51.

Would happen when a resource would overlap a sub, e.g. a wreck. The resource would be placed inside the sub and positioned outside the level. In the situation reported in the ticket, 2 of the 8 aquatic poppies in the "cluster" would overlap with the wreck which placed them outside the level.

The logic should now try to ignore edges that overlap with the sub borders.

**Comment by Xeavas** [comment]
[0.1100.0.6] - Went through ~20 maps in level editor, didn't notice any issues. 👍

**Comment by Rokvach** [comment]
Closing, Really rare one so if it exists it wouldn't really affect the game that much.
