### ISSUE TITLE
Ready check shows the result twice

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4281]
Could be because I was the one who initialized the ready check?

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f5100332-de80-41c6-8c38-488ac3e8d676)

**Comment by 3e849f2e5c** [comment]
Possibly caused because the timer on the ready check ended on the client side a little bit earlier than it ended on server side causing the client to end the ready check and then soon later receiving a "End" message from the server causing the ready check to end twice. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/87098fb4a3449299ed66237da3a948929585cfd0 by properly flagging the ready check as finished after it has ended and refusing new calls to the end method if it has already been marked as finished.

Possibly very tricky to repro as the timer would have to run out on the clients side before the server and the ready check timer is synced to the servers timer every time someone answers the ready check causing the timer to always be at least your current pings amount behind

**Comment by Rokvach** [comment]
No issues, closing.
