### ISSUE TITLE
[Suggestion] Allow stacking bot orders

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4282]
It would be great if bots had the ability to follow a sequence of orders. For example, ordering a engineer AI to repair broken electrical devices, then start up the reactor, or Telling security officers to defend the crew then operate guns. It prevents you from having to intensely micro-manage the AI, but still have a need to manage them.

**Comment by NyarlathotepZERO** [comment]
I imagine you are referring mainly to single player?

The issue I see with a 'sequence' of orders is that broken devices/fuel to reactor etc are mostly tasks that require constant attention, and a reasonable level of autonomy (removing you from much of the micro-management aspect) can be achieved just by buying another NPC and dedicating him to the task full time. A sequence of orders would need constant replenishing as each task is completed and thus, possibly more micro-management than the current system.

Buying more crew also has the added bonus of being able to (relatively instantaneously) punch into any char at any assigned task and take full manual control over the situation, without having to run from one side of the sub, to the other (or have an NPC bumble along from one side of the sub to the other).

In the beginning of the game, I appreciate its difficult to get a full crew, but I have oft heard repeated that it's one of the most valuable assets prior to upgrades, and as such, it is without doubt the first thing I blow all my cash on.

**Comment by Neko-LoverDisc** [comment]
I get what your saying, but there are still time where being able to stack tasks would be nice. Also with the fact that you currently can't add stuff to your sub like diving suit lockers, it usually results in having a surplus of staff means at the first full hull breach some people are dying. Sure you can have a bunch of suits laying around on the ground, but It's a mess and if the lights go out on some subs you'll have to drag your cursor along the ground hoping to find it. Floods also seem to happen often when i'm playing with only AI, due to them acting stupid sometimes. It would also help early game when you don't have the money to buy a bunch of crew members, allowing you to not have to constantly switch your mechanic between fixing breaches and repairing mechanical devices.

**Comment by ezjamsen** [comment]
@ekqvist what do you think?

**Comment by ekqvist** [comment]
I think allowing multiple orders to be given and manually prioritized would be a nice thing to test, and I think there would be multiple use-cases for it.

Some of this behavior the bots do already handle through their autonomous objectives, e.g. Mechanics will fix broken devices they come across when they have no leaks to fix, but it would be nice to be able to explicitly order them to do things in a specific order.

We already have priority calculation logic for different objectives, so we should already be able to tell when a bot shouldn't need to focus on their first order anymore and could focus on their second order instead.

The same thing was also suggested by someone on the Steam forums, and I believe @itchyOwl also agreed that this would be worth considering. Then there's the additional request of the orders also being saved in between rounds so they do not have to be reassigned every time a new round starts.

One thing to consider is, of course, how this will affect the UI design. If we have the ability to assign multiple orders to a single character, we need to rethink the UI a bit. We would probably scrap the previous orders on the crew list and replace them with multiple active orders. What would happen if you give a character a new order? Does that automatically take the first place, bump other active orders down a spot, and remove the last active order from them? Could it be possible to replace only the last of the active orders without having to assign multiple orders to the character? Should we support 2 or 3 active orders per character?

**Comment by itchyOwl** [comment]
One intention behind autonomous orders was to make bots act more like persons and not like.. well bots. Previously they used the initiative so that they wouldn't be so vigilant and eager to do things. But the initiative seemed to make them just too lazy/stupid, and removing it didn't make them too eager in my opinion. But I think we achieved the original goal here.

Another intention was to make the bots more useful without having to micro manage them. I think they are more useful now and I normally play/test without giving them much orders. But I understand that if you want to get the most out of them, you'll want to give them orders. When the bots have been ordered to do things, they are also more efficient in whatever they do, because they a) almost always run b) they can magically see targets that haven't actually been reported, in contrast to the autonomous behavior where they only target things that they have seen or that have been reported.

So yes: I would consider it, because it might make it easier to use the orders. Technically there shouldn't be too many obstacles. We'd have to refactor the code a bit to accept multiple simultaneous orders, but that shouldn't cause much issues.

So it's mainly about the UI, as @ekqvist described. And that's a question of design. Perhaps the previous order would remain active with a lower priority? And when we disgard an order, it would just go away? If we do that, we would probably want to allow to drag to rearrange the orders too. I'd say three would be a good maximum number of orders, like now. At least not more than that.

**Comment by Rokvach** [comment]
First pass of testing, didn't find any issues but had couple of ideas

1. I don't think its necessary to allow moving orders when there's only one order
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d7980b6f-a46e-4dda-93d9-7abaeb07b5bb)

2. Highlight the order a bot is currently doing, just to make it more clear to the player as to how the priority based orders work

**Comment by ekqvist** [comment]
Disabled order dragging when there aren't multiple current orders in Regalis11/Barotrauma-development@7753775. 

Highlighted the order the bot is acting on in Regalis11/Barotrauma-development@063f63c and Regalis11/Barotrauma-development@3c4d88a. The multiplayer implementation required some additional networking changes because the clients aren't directly aware of the AI objectives the bots are working on in multiplayer, so the server must inform them when the "active" current order changes.

**Comment by Rokvach** [comment]
Tested, I didn't find any issues with this. Can be merged and closed.

**Comment by Rokvach** [comment]
Merged, closing.
