### ISSUE TITLE
Players skills completely reset after death.

### ISSUE THREAD

**Issue by abuchelt** [Regalis11/Barotrauma#4283]
After dying all the skill points a player has earned are completely reset. In our campaign, the electrical engineer went from lvl56 back to lvl45 after death. I could not find any information if this is intended so I wanted to ask.

Ty
BR

**Comment by thegrb93** [comment]
Intended I think. Gives incentive to not die.

**Comment by LePiromano** [comment]
Intended

**Comment by abuchelt** [comment]
Alright, i just thought there might be an option like in hardcore modes that alot of games have, but it's good to know thank you.

**Comment by Xeavas** [comment]
That is indeed intended.
After you die, the one you "respawn" with is a new character, so the skills are tied to the previous character are lost.

**Comment by freed00m** [comment]
This mechanics actually makes the game so less fun.  Why not allow the players game in the way they enjoy it.

We tried to use cheats to get back the removed skill points to see that the games punished us with a cheat gimmick with the alien infection. 

It should be optional for the campaign.

**Comment by IndirectCell** [comment]
Skill loss + Reapers tax, puts you below a starting character.

Time investment in a character to get skills high enough to avoid failing critical checks on repairing junkboxes and pumps and what not.

Keep in mind game has glitches, you can litterally be teleported out of subs and die, thats just one example but there are silly deaths, so haveing characters SKILLS reset shouldnt be part of it, if DEV really wanted to make it punish then instead make reapers tax equal to this whole loss without haveing stats reset, and make the fee for cureing reapers tax higher, then at least it can be fixed by next station.

ALSO the characters that get most punished by this is obviously mechanics and engineers, captains can die left and right and you wont really feel that much, not to mention the fun qol part of their characters in general raise both weapons and helm skill by just controlling, and its never as critical as a engineer or mechanic..

SO remove this skill loss bs mechanic, and add a HARDCORE toggle for campains, if you die lose talents and skills (money and items on a character if not recovered), then those that WANTS to play with permanent loss (aka restart character completely on death) gets the option to do so, not to mention IRONMAN HARDCORE where if sub is lost for whatever reson (full team wipe) then save is deleted).

BUT most people are TRYING to have fun in this game, and in current state where accidental and glitched deaths can happen, permanent RESET of character shouldnt be a thing.

**Comment by freed00m** [comment]
I heavily agree with @IndirectCell, I've even wanted to buy this game for my brother so I could play with him.

I choose not to just because of this issue, there must be several people thinking like me and it must hurt sales. 

Simple campaign game toggle should be that hard to add.

**Comment by LaysDragon** [comment]
I totally agree with @IndirectCell ,skill loss is already a hard punishment,that made Reapers tax totally no sense. And glitch with insense punishment is really a big killer for fun. :(
