### ISSUE TITLE
Let physics objects besides bodies collide with stairs and ledges

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#43]
Had a hilarious situation where a dude dropped a box of nitro while on top of the stairs and then the whole sub exploded.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).



we're moving this kind of tickets to the forums and closing all of them here. please use [URL] for feature requests and ideas in the future.
