### ISSUE TITLE
Bots should call out Ballast Flora if they see it inside the sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4314]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots should call out Ballast Flora if they see it inside the sub

**Version**
0.1100.0.6

**Additional information**
At the moment they don't even care if ballast flora covers your entire sub.

**Comment by CurePindal** [comment]
Agree.

**Comment by NyarlathotepZERO** [comment]
Perhaps some sort of quick intelligence/experience check prior though. I'd be happy if an assistant/inexperienced crewmember walked past it blissfully unaware, whereas someone with more dives under their belt could almost sniff it out.

Ballast flora is a great game mechanic to punish the unwary, I'd hate to see this feature weakened to the point where it provided no added value to the game other than a mild annoyance whilst you rid yourself of a little excess flamer fuel.

**Comment by CurePindal** [comment]
> 
> 
>Ballast flora is a great game mechanic to punish the unwary, I'd hate to see this feature weakened to the point where it provided no added value to the game other than a mild annoyance whilst you rid yourself of a little excess flamer fuel.

Sorry, but thats exactly what ballast flora is at this point:  a mild annoyance and investment of a bit of flamer fuel.
When you know about ballast flora you dont oversee it, nor are you unwary about it any longer.

**Comment by NyarlathotepZERO** [comment]
> > Ballast flora is a great game mechanic to punish the unwary, I'd hate to see this feature weakened to the point where it provided no added value to the game other than a mild annoyance whilst you rid yourself of a little excess flamer fuel.
> 
> Sorry, but thats exactly what ballast flora is at this point: a mild annoyance and investment of a bit of flamer fuel.
> When you know about ballast flora you dont oversee it, nor are you unwary about it any longer.

No need to apologize. Nobody here is saying it has no room for improvement.

**Comment by itchyOwl** [comment]
The bots now report about it: Regalis11/Barotrauma-development@d13ea04.

Anything more than that is not simple and requires additional design. We could make them attack it or try to remove it, but it wouldn't be simple to make them very good at it. Certainly possible, but is it worth the effort?

**Comment by Regalis11** [comment]
Some issues:
- The bots report the flora multiple times in multi-hull rooms (example pic from Humpback's command room):
![image](https://user-images.githubusercontent.com/14351070/101619012-5df81700-3a1b-11eb-88ca-403cb07e6d2d.png)
- The report buttons next to the chat are now smaller and there's an unnecessary empty spot at the bottom, because the "Report Ballast Flora" order is taken into account in the layout despite being hidden.

**Comment by itchyOwl** [comment]
The first issue affects all the other report orders too, because the orders only check if the entity is equal. I think we could fix it by checking also the links when the target entity is hull.

But there's only one hull in Humpback's command room, and the bots only seem to report about ballast flora once:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b8fce3a7-9101-4f67-8a69-53305b576f40)

But I was able to repro it in Dugong, because the engine room has multiple hulls.

So the multi-hull issue should be fixed in Regalis11/Barotrauma-development@899e5b5. But I wonder if there's still something else wrong in the reporting logic, because you managed to get the bots to report the targets multiple times in Humpback too...

**Comment by Xeavas** [comment]
[0.1200.0.0] - Tested, seems to be working correctly (using dugong). Tried to replicate on humpback but unable to. 👍

**Comment by Rokvach** [comment]
Closing
