### ISSUE TITLE
[Unstable V0.1100.0.6] StartGame threw an exception: monsters.Count > 0 (6)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4320]
This error message was posted on Discord, no idea of the context of it, but hopefully the error message is enough to figure it out.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/917a8a42-c0af-404f-854d-db3a09a11ad0)

**Comment by Regalis11** [comment]
Not sure how to repro this: it appears the list of previous monsters was not cleared properly when the mission was ended during a previous round. I changed this from an exception to a warning because we can safely handle it by clearing the list manually, but we should still investigate why the list wasn't cleared (Mission.End not called for some reason at the end of the round?)

**Comment by Regalis11** [comment]
Marking as low prio since the mission classes should now be able to handle this when it happens
