### ISSUE TITLE
Light component state not synced

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#434]
When you switch the light component, it is updated only by the one who did it and the Host.
There's a complicated submarine with a bunch of components like that, which Alfred - my friend - has improved. And this is very disturbing to us, for in a voice sometimes starts a farce.
![image](https://user-images.githubusercontent.com/33912761/40855905-95601d3c-65de-11e8-983c-8a44c13d26ee.png)

**Comment by BillCombs** [comment]
I would also like to add to the client-server side problems a problem with handcuffs. When you are cuffed, you still can interact with other players' inventory(when they are cuffed or in ragdoll mode) but it only seems to actually work during interaction with the host. When 2 players, who got cuffs on(and none of them is the host), are interacting with each other's inventory(for example, taking cuffs off each other) it only happens on client side. It can be considered a desynchronization bug since after you take cuffs off from somebody, on your screen it looks like they are free, but in reality, they are running around with cuffs still on. 
A couple of times it angered some people i played with because they thought that i just did not want to take their cuffs off after they took off mine(on their clientside).
These situations don't happen often(and i don't have enough friends playing this game to help me recreate the bug) so the information here may be not completely correct.
A solution to this can be not allowing players to interact with each other's inventory when they are cuffed(since even though it's an interesting option, being able to take cuffs off each other would make it hard to deal with more than 1 traitor without killing them).

**Comment by Rokvach** [comment]
There's been allot of improvements to this issue, I don't see the point of keeping this open. Closing.
