### ISSUE TITLE
You can interact with npc/pets through (in) the inventory UI

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4347]
**Description**
You're able to interact with outposts NPC and Pets through the inventory UI if they are close enough while you're accessing a cabinet or similar containers.

**Steps To Reproduce**
- Go to an outpost and find a cabinet
- Teleport some essential NPC beside cabinet
- While NPC is near, open the cabinet and try to shuffle,take and click on items in said cabinet(inventory) UI

**Version**
[0.1100.0.7]

**Additional information** 
Using legacy controls.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/402a5f9d9778d4bcfa230b3f7ec84cc8d7e82576.

Note for testing: I pushed this to dev because it could causing some side-effects (are there some situations where we do want to allow interaction with NPC through certain UI elements?), and so I don't think we should include it in the upcoming update.

**Comment by Rokvach** [comment]
Similar to the deconstructor UI ticket about this same issue I am able to interact with a NPC if I spam click a specific area of the UI

Just rabidly click around this area whilst a NPC is standing in front of the cabinet and the click should go through eventually. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/55748170-8bc7-4634-9d6a-ca33d9c734f4)

**Comment by Rokvach** [comment]
Closing this ticket as the issue seems to be identical to this one
https://github.com/Regalis11/Barotrauma/issues/6022
