### ISSUE TITLE
Outpost handcuff could be undoned by another crew member

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4361]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I mean let's be honest, if someone get caught, all it takes is for your teammates to take off the cuff and you can go steal again. Those cuffs should probably not come off until you leave.

**Comment by Singularia** [comment]
Unbreakable handcuff just sounds silly.

Maybe AI should drag all those who was cuffed to some prison cell that you can't access without sec ID card, and you required to pay some cash (depends on crime severity or amount of damage to station) to free your crewmate(s).

Or they should stop trading\recruiting operations and quest giving immediately after multiple crimes.

**Comment by itchyOwl** [comment]
I'm not sure about it. Perhaps. Personally I don't see it an issue that it's a bit unrealistic. You can now treat arresting as a warning. Regarding offensive behavior, it now does what was intented: neutralize the offender for a while and make it less easy to misact inside the outposts. But it's true that you could abuse this for stealing stuff.

Unbreakable handcuffs don't sound silly to me, but the issue is that it's not how they normally work in the game: should we make an exception here or should we even review how they work in general?

Dragging the arrested person to a cell or some other place was in consideration previously, but that's a lot of more to do. And I'm not sure if it's worth it.

**Comment by Neko-LoverDisc** [comment]
Maybe make it where if someone uncuffs the cuffed person, it's considered a crime? Or make the guards reapply cuffs/follow up with lethal action if the arrested person is repeatedly seen without handcuffs?
