### ISSUE TITLE
[Feature request} Add Hallucinations where creatures/humans swap places when subject to heavy psychosis

### ISSUE THREAD

**Issue by Thirty-Percent** [Regalis11/Barotrauma#4378]
- [x] I have searched the issue tracker to check if the issue has already been reported. Definitely hasn't been reported.

**Description**
To further develop Psychosis, adding final stage (90-100?) symptoms where fellow crewmembers appear as crawlers/mudraptors, on top of the sounds. And... Enemy creatures appear as fellow crewmembers. Multiplayer would love it.

**Steps To Reproduce**
Injest lots of methamphetamine.

**Version**
0.666

**Comment by LePiromano** [comment]
that might end up mixing with the invisible creatures/crewmates and get even more confusing lol

**Comment by ezjamsen** [comment]
This is a pretty neat idea we may have discussed generally at one point or other. @itchyOwl @Regalis11 was there some technical limitation preventing this?

**Comment by itchyOwl** [comment]
I think the idea is fine, but there are probably multiple technical issues with it. The game hasn't been designed so that we could just swap some visuals into another. I think it's out of question to spawn some fake characters that would only show for some players and not for others. That would be a nightmare to sync for multiplayer. I'd say the only way to go here is to fake it somehow. It's probably easiest with sounds, but even with them I'm not sure how would we do it so that your fellow crewmate suddenly started speaking Crawler. But that could probably be done... And for the visuals, perhaps we could have some overlay effect where a crawlers head is shown only to the player with the psychosis. That could be a lot of work, and it won't be same as if you actually saw a crawler. So I'm not sure if it's worth it... I'd rather think of easy ways to improve the existing system.

**Comment by ezjamsen** [comment]
Let's close this idea and consider our options at a later time in that case.
