### ISSUE TITLE
Wall inside wall, outpost modules.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#4400]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A certain outpost module's top wall can spawn inside the bottom wall of another outpost module.

**Version**
V0.1100.0.9 Windows
![20201128002746_1](https://user-images.githubusercontent.com/55637865/100492978-20d58000-3111-11eb-83cc-033cb85527a9.jpg)
![20201128002811_1](https://user-images.githubusercontent.com/55637865/100492981-23d07080-3111-11eb-8530-01a494c21fef.jpg)

**Comment by Regalis11** [comment]
This is actually intentional to a degree: the walls/floors of the adjacent outpost modules are supposed to overlap as not to leave any unnecessary gaps between the modules. There seems to be something off here though, the walls shouldn't be offset from each other like this.

Do you happen to have a save file or a seed where this occurs? Those would make diagnosing the issue much easier.

**Comment by LePiromano** [comment]
[THE.zip](https://github.com/Regalis11/Barotrauma/files/5624257/THE.zip)
Here's the save, if im correct it should spawn you in the outpost with the error. @Regalis11

**Comment by Regalis11** [comment]
Since this doesn't cause any functional issues and seems to be very rare, I think we can close this instead of complicating the module placement further.
