### ISSUE TITLE
Diving suit uses afflictiontype instead of afflictionidentifier

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4405]
[Bug, Design]
eg
```xml
<damagemodifier armorsector="0.0,360.0" afflictiontypes="burn" damagemultiplier="0.0" damagesound="LimbArmor" deflectprojectiles="false" />
```
won't properly resist burns from an explosion that inflicts burns. This makes things like stun baton resistance impossible, and also makes diving suits effectively useless at resisting the radiation from explosions.
![image](https://user-images.githubusercontent.com/47284081/100533277-92d5c400-31fa-11eb-95b3-a9dd08b1fc0f.png)
this can best be seen in the aftermath of a reactor explosion while wearing a diving suit (they're supposed to resist radiation completely).

**Comment by Regalis11** [comment]
I wasn't able to reproduce the issue with the burns. I set the damage multiplier on the diving suit to 0, and the character doesn't seem to take any burn damage from explosions. The resistance against radiation sickness was bugged though: it was configured using the _affliction type_ "radiationsickness", instead of the affliction identifier (radiation sickness's type is "poison"). 

Fixed the radiation sickness modifier in https://github.com/Regalis11/Barotrauma-development/commit/94ef2233be2a5f65519db7dcd4a6d829f9aa8d6d

**Comment by hubismal** [comment]
yeah same i went over here right now to report the difference between afflictiontype and identifier which is the only real issue. my mistake.

**Comment by hubismal** [comment]
...that being said I'm beginning to wonder if damagemodifiers ignore afflictions that are defined in mods? I have essentially identical damagemodifiers for both burns and a custom affliction of mine. The burns (and other vanilla afflictions) work flawlessly but the "teargasexposure" affliction doesn't seem to get resisted at all.
To quickly test this, my [mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2003946282) can be downloaded. As of this update I'm releasing now, the "Aerosol Respirator" has a 360deg damagemodifier that resists afflictionidentifier(s) "thal_teargasaffliction" and "thal_mushroomized" . Spraying someone with a "Fumigator" loaded with a "tear gas canister" doesn't seem to resist the tear gas affliction at all. Same goes with spawning a "sporeemitter" on top of a person (which uses explosions to inflict thal_mushroomized).

**Comment by Regalis11** [comment]
I installed the mod, but couldn't find the words "teargas", "fumigator" or "respirator" in any of the XMLs.

Could it be that the fumigator targets all of the character's limbs, and that the respirator only offers protection on the head limb?

**Comment by hubismal** [comment]
You're completely right, I had always assumed armorsectors covered the full body and not individual limbs. Is there any way to protect the whole body against an affliction without having to make an empty sprite for every limb?

**Comment by Regalis11** [comment]
Damage modifiers on worn items only protect the limbs the item is worn on (the same way limb armor only protects that specific limb). Instead of making the protective headgear protect the whole body, I'd maybe make the fumigators or spore emitters only target the character's head as opposed to damaging every limb (can be done by adding `targetlimb="Head"` to the status effect that does the damage).
