### ISSUE TITLE
Shuttles spawning on the wrong side of the docking port

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4407]
#4406

[Bug]

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When loading into a CAMPAIGN mission, some shuttles spawn on the wrong side of the docking port, despite initially spawning on the proper side while in the starting outpost on a fresh save

**Steps To Reproduce**
Step 1: Have a shuttle linked to your submarine
Step 2: Host a multiplayer server (no need for other players)
Step 3: Start a new campaign (shuttle on the proper docking location)
Step 4: Start a mission or simply move to a new location
Step 5: Shuttle is on the wrong side of the docking port for unknown reasons

**Version**
v0.10.6.2 Windows 10

**Additional information**
Probably related to changing size of docking port, but no particular reason for it happening. Happened on two different submarines on both horizontal and vertical docking ports. Possibly related to docking ports that don't use a hatch. Deleting, replacing, rewiring the docking port on the main submarine did not do anything. 

Video of it happening
[https://cdn.discordapp.com/attachments/427654262453960724/782689776071213076/Desktop_2020.11.29_-_11.56.23.03.mp4](url)

You can see the docking port moving on the left on the navigation terminal:
![Dockingportbug](https://user-images.githubusercontent.com/73229309/100553643-37a1e100-328f-11eb-8d2d-eb0eefda0693.jpg)

**Comment by Regalis11** [comment]
Thank you for the report! Would it be possible to share us the submarine file so we could give this a test more easily (you can attach .sub files on github by zipping them first)? I suspect it may have something to do with the way the docking ports/hatches are set up.

**Comment by ubertpendragon** [comment]
There

[DOMA Prototype v7.sub.gz](https://github.com/Regalis11/Barotrauma/files/5615552/DOMA.Prototype.v7.sub.gz)

**Comment by Regalis11** [comment]
Thank you, I think I was able to diagnose and fix the issue. It happened because the game tries to determine the orientation of the ports based on the doors/hatches (or their gaps, to be exact) connected to the port, and if that fails, based on the world positions of the subs. During the first round the latter succeeded because the shuttle was placed to the same spot as in the editor, but on successive rounds loading the shuttle works a little differently, and the shuttle wasn't necessarily in the correct position at the time the orientation of the port was determined.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/b63672ad5f8be04f0af6eb8eb6666e81ba2f7c58. I also added the option to enforce the orientation in the sub editor, in case there are still some cases where the automatic logic doesn't work reliably.

**Comment by ubertpendragon** [comment]
Not fixed in Uncharted Depths update, still having the exact same issue; haven't seen the sub editor option

**Comment by ubertpendragon** [comment]
Unstable v0.1200.0.0 update

Good news: the shuttle previously pictured doesn't spawn in the wrong spot after loading

Bad news: it broke a bunch of other shuttles

![unstableshuttlebug](https://user-images.githubusercontent.com/73229309/101946618-76b92600-3bef-11eb-83ec-bad86662dee5.jpg)

**Comment by Rokvach** [comment]
Commented on testing dock

> Partially fixed, some shuttles that previously spawned on the wrong side are now working properly, while others now spawn on the wrong side

**Comment by Rokvach** [comment]
Moving back to todo

**Comment by ubertpendragon** [comment]
I think having the option to set which side the shuttle spawns on would fix it, but it wasn't present on this unstable build

**Comment by Regalis11** [comment]
Which submarine does the new issue happen in? I gave the DOMA prototype you provided another test, but everything seems to be working correctly there.

**Comment by ubertpendragon** [comment]
The shuttle (seabike) on the first picture is correctly docking on Unstable, but another shuttle (decoybuoy) is now docking INSIDE the submarine at the back, and can't really explain why. 

I've been able to not have the issue on Stable by moving docking ports around, but I think docking port settings will ultimately allow builders to avoid this bug.

**Comment by Regalis11** [comment]
Gave the sub a test, and I think it's a special enough case that we should rely on the new ForceDockingDirection property instead of trying to solve it automatically and complicate the logic further. The reason why the game fails to determine the direction correctly is that there are no doors, gaps or hulls to base the direction on, so the game will fall back to the "last resort" and guess that the buoy is supposed to dock to the bottom of another port since the buoy's own port is above it's center point.

We accidentally left the ForceDockingDirection property hidden in the latest unstable build, but it'll be visible in the next build (fixed in https://github.com/Regalis11/Barotrauma-development/commit/d6fe9c2).

Also, as a side note, that's a really impressive sub you've built, nice work! :)

**Comment by ubertpendragon** [comment]
I'll add this one weird behavior: Shuttle spawning on the side of the docking port and slowly sliding until it docks

https://user-images.githubusercontent.com/73229309/103145184-0bff0300-4736-11eb-96f0-ee99ee0b5278.mp4

**Comment by Rokvach** [comment]
No issues, closing.
