### ISSUE TITLE
Cannot launch a self server

### ISSUE THREAD

**Issue by WharkOddity** [Regalis11/Barotrauma#4435]
- [x] I have searched the issue tracker to check if the issue has already been reported.

- [x] I have downloaded again barotrauma and did files checking through steam. 

**Description**
When I'm trying to Host a server directly in-game from the menu, the game will show me an error message 

> "Connection lost..."
    It says that the server has crashed unexpectedly and generated an error message (servercrashlog.txt) in my game directory but nothing is generated and this bug is happening all the time. So I can't host a server...

**Steps To Reproduce**
Just starting a self server. (for me)

**Version**
Windows 10 Famille 64-bit
Computer type: Notebook
Installation Date: 20.09.2019 02:14:40 / Barotrauma v0.10.6.2

**Additional information**
Same if I use differents wifi or my ethernet cables.

**Comment by Regalis11** [comment]
Hello and thank you for the report! It's hard to say what exactly is causing this without the crash log or an error report, but there's a couple of things you could try: if you launch the server executable (DedicatedServer.exe) directly from the game folder, there might be some error message in the console that could give us some more clues. Also, do you have any mods installed? There have been some cases where mods have been causing the game to crash without a proper crash report (for example https://github.com/Regalis11/Barotrauma/issues/4421), so unsubscribing from those could be worth a try.

Anyhow, since we have a couple of existing tickets about this, I'll close this one as a duplicate.
https://github.com/Regalis11/Barotrauma/issues/4421 
https://github.com/Regalis11/Barotrauma/issues/3666
