### ISSUE TITLE
[Idea] Giving players an option to give up if they are in sub's brig for too long.

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#446]
Currently the most humane way to get rid of traitors is killing them, what is kind of counterintuitive if you are roleplaying like if it was a real life(not many people irl want to die) and makes handcuffs pointless in most situations(if not counting times when people are using handcuffs just to make killing easier). It would be fun to play as a pacifist who does not kill people but instead puts them into the brig. But it is really frustrating to stay in the brig(that usually has no windows or any other way to watch the stuff that is happening in the sub) for the whole game which can last hours if players are having trouble completing their mission or just decided to forget it and screw around instead.

It would be nice to have an option to give up(you can pretend that the arrested player is just sleeping and waiting for his arrival to a prison) once you are in the brig for 5 or more minutes so you could admit defeat and spectate the game instead of wasting your time. Also, it seems like when a traitor is dead, it still counts as his loss even if he respawned in a shuttle, so you can count that as a new non-traitor life. And it would be way nicer to just respawn and help your team(especially if you were the only engineer or mechanic) than to stay useless in the brig till the end of the game. 

You will probably need to make something like a brig area to be added in the sub editor. Once you entered it and were in it for about 5 minutes, it would give you the option to give up.

**Comment by CryIz** [comment]
It remains to add a couple of triggers with "Hammer editor".

**Comment by Auios** [comment]
I disagree and here's why. This feels like it can be exploited. Currently if a player dies they can come back in a respawn shuttle. If that player is a griefer or some player with malicious intent and you kill them, they could come back and just try to wreck things again. It's best to lock malicious players up and prevent them from respawning so that they cannot have another chance to destroy the ship. If you don't like being locked then don't give people a reason to lock you up.

**Comment by BillCombs** [comment]
The problem is that if you have no admin or ability to vote to ban the griefers, the powers are pretty much equal. You are not the only one who can put people in the brig. What will you do if a griefer does that to you? An option to give up and respawn would give you another chance to deal with them. Plus since the rule only applies to the brig, you could just put cuffs on them and move them into some other room. They can't open any doors when they have cuffs on.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
