### ISSUE TITLE
Add "Random" to items and conditions.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#447]
If The player has a skill no more than 20, he will receive some random effects. For example, when using a welding machine to get more damage, when shooting from a weapon to get a small stun. You can also make random effects when using an item.
The translator constantly translates heresy. Sorry about that. At school, I was taught only "London is the capital of Great Britain".

Если же у Игрока навык не более 20, то он будет получать некоторые рандомные эффекты. К примеру, при использовании сварочного аппарата получать больше урона, при стрельбе из оружия получать маленькое оглушение. Также можно сделать рандомные эффекты при использовании предмета.
Переводчик постоянно переводит ересь. За это извиняюсь. В школе меня научили только "London is the capital of Great Britain".

```xml
<Random>
   <StatusEffect type="OnUse" target="Character" Health="-5.0" disabledeltatime="true">
      <RequiredItem name="Medical Syringe" type="Container"/>
   </StatusEffect>
   <StatusEffect type="OnUse" target="Character" Health="-2.0" Stun="2" disabledeltatime="true">
     <RequiredItem name="Medical Syringe" type="Container"/>
   </StatusEffect>
</Random>
```

Можно конечно же использовать:
You can of course use:
```xml
random="true"
```

=================================================================
Точно также и с навыками:
Similarly, with skills:

```xml
      <StatusEffect type="OnUse" target="This" reload="1.3" checkconditionalalways="true">
        <Conditional skill"Weapons"="gt 50"/>
      </StatusEffect>
```
Знаю, что есть ошибки. Это просто наброски.
I know that there are mistakes. It's just an outline.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
