### ISSUE TITLE
[0.1200.0.0] Text displays saved in 0.11.0.9 bloats up in size in this version

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4483]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Text displays saved in 0.11.0.9 bloats up in size in this version.
![](https://cdn.discordapp.com/attachments/668819422919524352/787049038490894356/Capture.PNG)

Opening up my older subs that I never resaved for 0.11.0.9 still has proper sizes.

**Version**
0.1200.0.0

**Comment by Regalis11** [comment]
This happens because the sprite has been scaled to x2 resolution and the automatic downscaling of items in older subs isn't using the correct version number.

I think we should wait until we know the actual version number of the next release before fixing this (see https://github.com/Regalis11/Barotrauma-development/commit/7f73c829f21e8b8656e1a713ded259bebf1d4df2).

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
