### ISSUE TITLE
Alleged "exploit in character data"

### ISSUE THREAD

**Issue by Kampfkarren** [Regalis11/Barotrauma#452]
A Discord I'm in for Smoothtrauma claims to be using an "exploit in character data" where you send invalid characters and cause a "double-end loop".

![](https://cdn.discordapp.com/attachments/341535333457985539/460263944972402693/unknown.png)

I have no details other than this conversation.

**Comment by ZealanL** [comment]
Yes - this is a little trick I use on people that repetitively ban evade on my server. It helps me keep repetative abusers and griefers with VPNs away. It's not really a bug, my server just sends invalid character spawn data to the player, causing their game to crash. Sometimes the window will freeze and if they are fullscreen, they can crash.

This sounds pretty evil, but it's only a punishment used for the highest offenders. Repetitively making offensive statements and using VPNs for ban evasion is how Boyd got his ban.

Double-end loop happens when the client keeps asking for more character data but is not given any, and not disconnected. This causes them to stay frozen instead of a game crash. Again, not really a bug, but I guess you could fix it if you wanted to.

**Comment by AbandonedCroissant** [comment]
A VPN works? Well I know what I'm doing, Fuck you Yeet Fleet mods.

**Comment by ZealanL** [comment]
UPDATE: Just tested this again and it no longer works. It just causes an excessive desync kick. It seems this was fixed.

(Previously, I was not using this glitch for malicious purposes, and only on griefers who consented to it and were given a fair warning.)

It seems whatever caused barotrauma to break no longer works - sending these special character data packets doesn't do anything but desync the client.
