### ISSUE TITLE
Why is this removed from the game?

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#453]
I compare version 0.5.0.0 and 0.8.1.2.

For example, this effect used to be much better due to the fact that we do not see anything superfluous. We're less distracted by what's behind the submarine or behind that wall. We only have access to what is really visible to our character.
![11](https://user-images.githubusercontent.com/33912761/41953333-b745ce70-79dd-11e8-9e15-01b79bbaaff6.png)

Why did you decide to remove that feature installation method? Now it can be put only in the middle of Your character. Previously, you could put them where the hand of the character. Yes, it was convenient. Especially with detectors.
![12](https://user-images.githubusercontent.com/33912761/41953377-f8614592-79dd-11e8-9d78-95c27ebad9a1.png)

Player names were not visible. Yes, on the part of observers it will cause some misunderstanding of who it is. I think it's easy to fix.
Yeah, I once suggested to make when approaching the Player becomes brighter nick, but I meant that initially it will be completely hidden.
![13](https://user-images.githubusercontent.com/33912761/41953420-546fd894-79de-11e8-8742-e52018c83b71.png)

In the reactor it was much easier to set the temperature limit. Now at the slightest click you can jump over the desired limit. Not critical, but still.

Objects fell from the hands, not from the body of the character. As with components. They also fell at the angle they were thrown.

I hope at least that the components will allow us to re-establish without superfluous crap with the gap and climbing stairs, in order to put the whole thing down.

Used a translator. If something is not clear, then sorry.

**Comment by Regalis11** [comment]
In my opinion the transparent LOS effect looks much nicer than the solid black one, and it makes it easier to figure out the layout of a sub you've never played before. But in any case I added the option to make the effect opaque or disable it completely (see 93ff150).

I'm not sure if I agree about hiding the player names completely, I think it's useful to be able to see the name even when you're further away. Why do you feel they should be hidden?

Attaching/dropping the items at the position of the character was a lazy workaround to position syncing issues, however I agree that the old method was better and should be readded. 

The reactor temperature adjustment should not be an issue anymore because the new reactor interface does not even have the shutdown temperature setting.

And as a side note, it would be nice if in the future you could split unrelated bug reports and feature requests into separate issues.

**Comment by Regalis11** [comment]
Still not fixed: https://undertowgames.com/forum/viewtopic.php?f=18&t=10516
