### ISSUE TITLE
Doors locked by Ballast Flora can't be interacted with in multiplayer

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4537]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AFTER Ballast Flora has controlled a door (and given up control of it), it becomes uninteractable. Any wired buttons won't open it, and you won't be able to use plasma cutter to break it open either

**Steps To Reproduce**
Happens sometimes after triggering ballast lock by attacking flora (in multiplayer)

**Version**
 v0.11.0.9 Win10

**Comment by ubertpendragon** [comment]
Update: the  plasma cutter part is probably because flora overlaps with the door/hatch, and you can only cut one thing at a time (which might get fixed)

As for the buttons not doing anything, there was _one_ instance of this happening and hasn't happened against since. Maybe flora didn't give up control or kept taking damage from a random source, keeping the door locked?

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c60f39038a3bfe2ad122de33c12b3d77d84cbd4.

I suspect this happened if the ballast flora was killed when it was in the state where it tries to drown a character in the ballast. It requires very specific timing so it can be difficult to repro, but here are the steps:
1. Infect a ballast pump and wait for the flora to burst through the walls.
2. Get the ballast flora to the DefendWithPumpState by damaging it while you're in the ballast tank.
3. Kill the flora before it leaves DefendWithPumpState (which takes about 10 seconds). You can see when it leaves the state by putting a breakpoint in the DefendWithPumpState.Exit method.
4. At this point the door should be permanently jammed.

**Comment by Xeavas** [comment]
[0.1200.0.1] - Unable to replicate 👍 

Elaboration :
Replicated in [0.1200.0.0] by
1. `ballastflora infect`
2. `ballastflora growthwarp 200`
3. Damaging it with a plasma cutter while in ballast (and thus getting it into DefendWithPumpState)
4. Using `killmonsters` to kill ballast flora

Attempting to do mentioned steps to replicate in [0.1200.0.1] results in the doors properly unlocking and pumps back into the submarines control.

**Comment by Rokvach** [comment]
Closing.
