### ISSUE TITLE
AI pathing on laders

### ISSUE THREAD

**Issue by GorillaOne** [Regalis11/Barotrauma#4545]
- [*] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots ignore generated waypoints on stairs and use alternate paths, even if such paths have substantially longer distances. 

**Steps To Reproduce**
1) Build this. 

![image](https://user-images.githubusercontent.com/5703346/102389150-b6da2900-3fa0-11eb-94ce-24bb6d6d40f2.png)

2) Auto generate pathfinding nodes. 
3) Order a bot to turn the reactor on. 

Actual Result: 
Bot will take the ladder to the upper path, walk all the way across and down the second ladder.
Expected Result: 
Bot will walk through the door an down the stairs, which is a shorter path. 

**Version**
Windows 10. Barotrauma.exe version 0.11.0.10. 

**Additional Information**
I also tried modifying the nodes around the ladder manually (on my own sub, and not this simple reproduction) to see if I could get the desired result. Without knowing how the pathing heuristic, or what additional checks are made, I was unable to do so effectively. I did manage to make the bot take the stairs going right to left, but they would still take the long route going left to right.

**Comment by itchyOwl** [comment]
It's funny that this came up now and not earlier, because I just fixed this issue based on a user report in Discord (#baro-subs) in commit Regalis11/Barotrauma-development@6b13518. So I won't bother testing it, as I'm pretty sure that commit will fix this. I'll let the QA do the testing.

The issue was that there was a huge non-intentional penalty given to all stair waypoints.

We don't use stairs much in vanilla subs and when we use, there might not have been alternative routes, so that's probably why this issue has gone unnoticed/unreported.

**Comment by Xeavas** [comment]
[0.1200.0.1] - No issues 👍

**Comment by Rokvach** [comment]
Closing
