### ISSUE TITLE
Monsters do not play attack sounds in multiplayer

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4559]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Monsters do not play attack sounds in multiplayer. This means that any sound defined with the state "attack" will simply never play when playing on a multiplayer server.

**Steps To Reproduce**
1. Join a multiplayer server
2. Encounter a creature or spawn one
3. Let it attack you or something else
4. Pay attention to the sounds it makes while it is attacking.

**Version**
Version: 0.11.0.10 - Public Branch. OS: Windows 10.

**Additional Information**
Still an issue as of version 0.1300.0.9- Unstable Branch. 
Video showcasing the problem https://youtu.be/Zk3xdvuk7g0

The issue might be related to monsters never switching to an "attack" state. This can be observed through the debug command, as every monster in multiplayer will always be in an idle state no matter what they're doing.

**Comment by itchyOwl** [comment]
I think this is fixed since the attacks were synced.

**Comment by Rokvach** [comment]
Tested, working correctly, closing.

**Comment by Emanthealmighty** [comment]
Not working as of version v0.14.6.0.
Monsters never play sounds with the "attack" state tied to them in multiplayer.

**Comment by itchyOwl** [comment]
The AI states were not synced so the creatures always played the idle clips.

Fixed in Regalis11/Barotrauma-development@7f3084f. It's the dev branch, because the fix is bundled with some changes that require a bit of testing.

Also made some changes to how the monster audio clips are played:
- An attack clip is played when the monster attacks (not just periodically in the ai state)
- An attack clip is also played when the monster enters the attack state
- The damage clips are played more reliably than previously
- In the attack state, monsters play the idle clips periodically like they used to, but instead of always playing the attack clip in the attack state, they now randomly choose between an idle clip and an attack clip. I made this change to add more variety in the soundscape.

**Comment by Emanthealmighty** [comment]
> * An attack clip is played when the monster attacks (not just periodically in the ai state)
> * An attack clip is also played when the monster enters the attack state
> * The damage clips are played more reliably than previously
> * In the attack state, monsters play the idle clips periodically like they used to, but instead of always playing the attack clip in the attack state, they now randomly choose between an idle clip and an attack clip. I made this change to add more variety in the soundscape.

I like the sound of that!

**Comment by Emanthealmighty** [comment]
Issue fixed as of v0.1500.1.0 (Unstable). The behaviors described above trigger correctly in multiplayer and singleplayer.

**Comment by Rokvach** [comment]
Closing
