### ISSUE TITLE
AI incompetence when coming to floods and dive suits

### ISSUE THREAD

**Issue by Veritius** [Regalis11/Barotrauma#4560]
When there is any significant amount of water (such as a visible level) the bots spam "I need a dive suit!" in chat, grab a dive suit, and then seal the hole. Problem is, it might be a really insignificant leak that can be easily fixed. Also, bots leave dive suits all over the place with no respect for organisation.

Please, make it so bots go for a dive suit when the water actually reaches dangerous levels and there's a large breach/considerable flow that makes pressure a legitimate concern. Otherwise, look for an oxygen mask. If there's no oxygen mask, grab a dive suit.
And please, make it so dive suits can be dragged without putting it on for placing in storage.

**Comment by itchyOwl** [comment]
There have been issues in the decision logic regarding the bot reactions to the loss of oxygen and to leaks. The latest issues were reported here: #4390 and should be fixed in the current unstable.

I think most of the issues mentioned here should now be fixed, but verifying that requires testing.

How it should work:
- if the water level of the hull is more than 90% or there's a lethal pressure or any leaks to the outside more than 50% open, the bots should seek for a diving suit, else a mask is enough.
- if the water level of the hull is less than 60 % and there's more than 31% oxygen in the hull, the bots should not equip even a mask.

The bots should put the suits in places when they don't have anything important to do. If they have important things to do, they should drop them. Idle bots should clean the suits back in place. If idle bots won't clean up the suits, they probably can't find a proper container for the suits or a path to the container. This would be a separate issue.

Dragging suits without having to equip them is another topic. Perhaps @Regalis11 can answer to that.

**Comment by Rokvach** [comment]
Haven't noticed any issues, seems to be working correctly. Closing.
