### ISSUE TITLE
Destinations Impossible to Reach

### ISSUE THREAD

**Issue by elliotvadi** [Regalis11/Barotrauma#4569]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I started a new campaign today, and I have encountered a problem: It is literally impossible to reach some destinations. There's literally no way of getting to them. All closed off. This has naturally proven to be quite a frustrating aspect of the game, and I doubt that it is anything other than a bug. 

**Steps To Reproduce**
Start a new campaign save, and have the map seed be "Bottom Gear". In Worm Cave, you'll need to accept the mission where you destroy a Tiger Thresher nest. You will then find that the nest is located in a circular space _inside_ an undersea mountain, with absolutely no way of getting to it. In another instance, your mission is to transport nitroglycerin from Phoenix Linea Research Facility to The City of Serac. About 600 meters from your destination, you'll find that there is a wall of mountains preventing you from reaching The City of Serac. There's no way around this wall. 

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Version 0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report! Unfortunately I wasn't able to reproduce the issue. There don't seem to be locations called "Phoenix Linea Research Facility" or "The City of Serac" on a map generated with this seed. Although, I did find Worm Cave and went through all the levels adjacent to it, but the nests and caves seem to be positioned correctly in all of them:
![route1](https://user-images.githubusercontent.com/14351070/103480941-517b9a00-4de0-11eb-8092-93f1617d2177.png)
![route2](https://user-images.githubusercontent.com/14351070/103480942-52acc700-4de0-11eb-8346-1b9a719a94d7.png)
![route3](https://user-images.githubusercontent.com/14351070/103480943-53455d80-4de0-11eb-9175-02596a921821.png)
![route4](https://user-images.githubusercontent.com/14351070/103480944-53ddf400-4de0-11eb-8be2-0267cf9883eb.png)

However, the size of the submarine can affect the layout of the level (the level generator always ensures the main path is wide enough for the sub to pass through), so the problem might only occur with some specific submarines. Do you remember which one you were using? Something that could also affect this is if you originally started the campaign with an earlier version of the game, which could cause the layout of the map (and consequently, the layout of the levels) to be slightly different.

The easiest way for us to reproduce the issue would probably be to test with your save file, so if possible, could you post it here? Note that the file needs to be zipped first, because github doesn't allow attaching Barotrauma's ".save" files directly.

Thanks in advance and sorry for the trouble!

**Comment by elliotvadi** [comment]
[Save_File.zip](https://github.com/Regalis11/Barotrauma/files/5761738/Save_File.zip)

I think this is the save file in which the bug possibly lives. 
I was using the 'Azimuth' submarine. 

There exists a possibility that the bug was also patched out before this ticked was addressed, but what do I know.

**Comment by Regalis11** [comment]
Thanks, managed to find the problem spots now! 

The ice walls blocking the way from Phoenix Linea to Serac are not actually a bug, they're recently added environmental hazards called "ice spires" which you need to destroy with a turret or explosives to proceed. You're not the first person to be confused about them, and we are working on ways to make it more obvious they're destructible.
![image](https://user-images.githubusercontent.com/14351070/104221649-d81c2100-5449-11eb-9e30-af830453e146.png)

The thresher nest is also reachable, but requires destroying a couple of ice walls in the cave. Again, something we need to communicate more clearly!
![image](https://user-images.githubusercontent.com/14351070/104221700-f08c3b80-5449-11eb-96ec-8816997550f7.png)

**Comment by Maxipuh** [comment]
Hey @Regalis11 
How do you access this overview map? I literally created this account to ask. 
Me and my friends have been trying to play the game and it always ends in us not being able to find the objective or a way in or our fuel rods running out before we do.
This might just us being stupid but we really can't progress at all.
Thanks
