### ISSUE TITLE
Feature Request: Uncuff yourself if you stand still long enough

### ISSUE THREAD

**Issue by Kampfkarren** [Regalis11/Barotrauma#457]
Griefers like to put me in handcuffs when I did nothing and this seems like a good IC solution.

**Comment by BlueTheKing** [comment]
Might aswell remove them altogether then, how the hell does someone uncuff themselves from standing still.

**Comment by chesse20** [comment]
theres plenty of weird metal things in the backround your character can be rubbing their cuffs agianst to break out of them

**Comment by BillCombs** [comment]
Even though the ability to remove handcuffs could be an interesting addition to things you can do in the game(if you manage to balance it properly), i think that trolls and griefers are not really part of the game content's problems, but more of a community problem. And that can only be fixed by good admins, modders or groups of good players who are using the vote system to ban the griefers. Griefers and normal players get equal powers so giving yourself more power or abilities won't help because you are also giving it to the griefers.

**Comment by BlueTheKing** [comment]
Basically what Bill said. They would replace cuffing you with killing you or getting you stuck into a room and if they are such a problem switch servers.

**Comment by NilanthAnimosus** [comment]
I am pretty much in agreement with blue there for the most part. when I host a server i usually try to have rules which usually includes cuffing of bad players being preferable to simply killing them so they may weaponize a respawn or cause the submarine to require killing other (Innocent) respawnees.

having people able to remove their own handcuffs without anything to assist in it is most definately going to cause more problems than benefits it adds to most servers.

If you really want this to be a potential thing - instead add the ability to see the inventory while cuffed (Not interact directly - but still see it, I see no reason you cannot see who removes items from your pockets personally while handcuffed unless unconcious).

Once a player is capable of seeing their inventory while cuffed - add an item (that is fabricated, say from steel/polycarbonate or both) that can allow one to remove their own handcuffs within 1 minute.

Perhaps give it a picktime and a flag or such that it is meant to remove a cuffs (Personally I Cannot think of a good way to go about it).

An item would allow security to remove it on searching ones inventory - or even potentially miss that they have this item. it would also allow other players to give them an item to remove the cuffs on their own. Finally if such a system exists it could be made to use the pick method to remove anothers handcuffs - giving a timer to do it.

This feels more balanced, but assuming the above is unfeasable (I have not played dev so I do not know how its UI is handled) I would prefer this to not exist in the game at all if it cannot be a difficult or planned visible action requiring something.

**Comment by BlueTheKing** [comment]
I guess that would make it fair, but no sub i ever played on has the fabricator or deconstructor inside the brig (as it should be). Meaning that if you are in the brig handcuffed you are still stuck there and most likely if you are near a deconstructor or something there are people nearby who could help you. 

My idea if this was going to be added is to make it so you can "force" out of them and break the cuffs, but it should be really noticeable visually and maybe even add sounds.

But again the whole point of this seems to be that griefers are the problem in which case they will use it against you again. I would rather not have this added (yet).

**Comment by BillCombs** [comment]
I meant that you should have a chance to survive if you got handcuffed outside of the brig.  If you are in the brig, it should be a game over for you(unless you were the only engineer or mechanic and the crew suddenly needed you), because otherwise the brig would be pointless.

It's just really damn frustrating that you are doomed when the crew just cuffed you without even caring about putting you in the brig and then went to get an artifact and died, leaving you to run around till you either disconnect or die of oxygen deprivation when the power goes out (unless the players appear to be observant enough to find out about the ability to vote to end the round). It would be a different story if you could remove the cuffs.

But i guess this kind of situation is rare enough to not really care about it. I just thought that it makes sense to be able to remove handcuffs using heavy machinery rather than be able to break them with your strength or just pick it with some wire. Especially considering the fact that the game takes place on another planet what means the technology level of things (cuffs included) is most likely a lot more advanced.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
