### ISSUE TITLE
Switching submarines wipes your upgrades even if it's to an old upgraded submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4611]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Switching submarines wipes your upgrades even if it's to an old upgraded submarine

**Steps To Reproduce**
1. Start with Dugong.
2. Upgrade Dugong.
3. Purchase Orca and start level. Redock back to outpost.
4. Switch back to Dugong and start level. Redock back to outpost.
5. Upgrade NPC says Dugong has no upgrades.

**Version**
~0.1200.0.1

**Additional Informations**
Expected to either have the upgrades applied to all submarines or have all submarines remembers their upgrade. Honestly it's pretty detrimental to switch a submarine more than halfway into the campaign, especially since you need a deep diver to comfortably drive into the end. You need to halt progress to farm money to upgrade the hull even if you do that. All the upgrades in total adds up to about 1.6 million marks, so yeah it's going to hurt.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b579f13cc5cc5990c077f952d619feed62dcc16f

Happened only in multiplayer, the upgrade system has always reloaded upgrades when switching submarines but in multiplayer it reloaded it from a brand new XML every time instead of the one that is currently owned effectively wiping the upgrades.

**Comment by Kaillera** [comment]
In singleplayer this can be done with submarines that uses a shuttle.

1. Upgrade the sub.
2. Lose the main sub in the level.
3. Return to the outpost with a shuttle.
4. Switch back to the lost submarine with the outpost terminal.
5. Redock to the outpost and check upgrades.

**Comment by lzhou1998** [comment]
I find a way to solve this problem:
1. Enablecheats.
2. Give a large amount of money by "money", and upgrade 1 level at outpost officer for every modules that you have upgraded.
3. Use "upgradeitem" to upgrade -1 level for these modules in the console.
4. Reset your money by "money" to the amount that you should have.
5. Leave the outpost and dock again.
6. You can find the upgrades recovered. 
7. Restart your server to unable cheating mode.

BWT, I think it just a display error at upgrading menu, not "wipes". You can find your previous upgrades at outpost officer, by moving your mouse to modules of sub on the thumbnail rather than the upgrading menu.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

Steps I used to test this in multiplayer
1. Buy all hull upgrades to Dugong
2. Dock
3. Buy and switch to Orca
4. Dock
5. Switch back to Dugong
6. Dock
7. Check that all the hull upgrades I bought were still there
