### ISSUE TITLE
Bots try to retrieve items from non-interactable containers

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4613]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If submarine has some decorative items placed in non-interactable containers (like many custom subs do with weapon holders or fire extinguishers), bots might attempt to retrieve that item causing them to awkwardly wiggle around item's position unable to do anything.

**Steps To Reproduce**
1. Add 'extinguisher' tag to morphine
2. Place it in fire extinguisher bracket
3. Make the bracket non-interactable
4. Go to test mode and beat up bot with a stun button
5. Order bot to heal crewmates
Bot will go to the fire extinguisher and get stuck there unable to get that morphine

**Version**
v0.1200.0.1

**Additional information**
If item itself is set to non-interactable then the bot won't try to retrieve it.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@021c914.

Simpler steps to repro:
1. Se all fire extinguisher brackets as non-interactable (in the sub editor).
2. Order a bot to extinguish fires.
3. Use the console command "fire" to start a fire somewhere.

Before the fix the bot would try to get an extinguisher from a bracket (and fail). After the fix teh bot should just ignore all the brackets and yell that he/she can't find any extinguishers.

**Comment by ignis05** [comment]
Wasn't able to reproduce in v0.1200.0.2

**Comment by Rokvach** [comment]
Closing
