### ISSUE TITLE
Owned items counter in vendor menu includes non-interactable items

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4614]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When selling items at outpost vendor you can see how many of each item you own on your submarine, but that number also includes non-interactable items and items placed inside non-interactable containers.

**Steps To Reproduce**
Place some items marked as "non-interactable" in your submarine or place some items in container marked as "non-interactable" and go check outpost vendor.

**Version**
v0.1200.0.1 Windows

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@4f14141

**Comment by Rokvach** [comment]
non-interactive items inside a cabinet is counted as owned, but if those items are outside of the cabinet or the cabinet itself is non-interactive those items aren't counted.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@14e10b4

**Comment by Rokvach** [comment]
If a player takes a non-interactable item from a cabinet and has it on their inventory that item is counted as owned. Decided to just create a separate ticket for it as I don't think that should be even a possibility in the first place to happen  #2439 

Closing this ticket as I think it covers enough of the corner cases and the last issue should be addressed separately from this rather than just adding another fix to a specific corner case which might not even happen. 

Closing.
