### ISSUE TITLE
Bot having issue with repairing this particular battery.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4624]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I am not sure what it is but this battery on my sub is being ignored by Bots. When they do want to get to it to repair, they'll just continuously run in one direction (into walls or doors).

![Capture](https://user-images.githubusercontent.com/5086682/103486605-01dfa300-4dcd-11eb-887a-7226cee28bb4.PNG)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/5762101/Save.zip)

**Version**
0.1200.0.1

**Comment by Kaillera** [comment]
Currently the hotfix for this issue I found is to place a standard waypoint in between the door and ladder.

**Comment by itchyOwl** [comment]
So it's probably a waypoint issue then. I'll test it and see if the recent changes to the waypoint generator fixes it.

**Comment by itchyOwl** [comment]
I'm not sure which change has affected it, but in the current dev version the bots don't ignore it, but actually try (and manage) to reach the battery from a wrong waypoint:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/7cecc95f-f1cf-4a52-ae67-69c21d463d12)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/54caade1-a180-4c77-a1e5-fe5bc4e4fd63)

The bots try not to stop at the ladder waypoints, as they would drop from the ladders if they started the repairs while holding the ladders (which is something we have considered changing, but hasn't advanced). So currently it's actually a valid fix to add a standard waypoint above the platform, so that the bots can use it to get on the platform before doing the fixes.

The waypoint generator does not automatically add waypoints above platforms. It uses hulls to understand what is a room and from there it adds the waypoints inside it. I think we should consider adding waypoints above platforms too. In the meanwhile, another workaround would be to use compound rooms consisted of multiple hulls that are linked together. Here it's obviously an overkill, but in some cases it's better to do that instead.

So I'd consider this ticket done. I'll add a todo note about the platforms in the waypoint generator ticket.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
