### ISSUE TITLE
Unable to update Workshop item

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#4661]
So, I tried to update the good ol BTE mod but the game/workshop treats it as the item is not mine. I can only subscribe/unsubscribe to it.

My guess is the original mod is way too old. For instance, I noticed there's 'steamworkshopid' and 'installtime' in filelist.xml... those were not a thing last time I modded barotrauma so it might be an steamitem ID issue.

We finally decided to just upload the mod as a different steam item but I'm reporting this issue as suggested by Dynamoon. It could affect other old modders so it makes sense. :p

**Comment by Ek-Videogames** [comment]
Most pre 0.9 workshop pages are bricked, no real workaround just make a new workshop upload item.
Its kind of an issue on the steam API's end - but the issue happens as a result of the metadata implementation on baro's end not steam.

Otherwise the workshop uploader would be able to simply overwrite the workshop item with the new data and  'steamworkshopid' and 'installtime' would literally not matter because they would be updated.

**Comment by ChikoEduardo** [comment]
Hmm... it appears I can't even update new items either. All the changes I do are ignored in the filelist.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
