### ISSUE TITLE
Lacing items with poisonous powder

### ISSUE THREAD

**Issue by xenote** [Regalis11/Barotrauma#468]
This can be a great feature for traitors as they can sabotage a lot of crew equipment

**Comment by ZealanL** [comment]
Or griefers who want to further annoy and murder the entire crew.

I would be careful adding any dangerous/destructive features into the game, it's already very easy to grief and ruin the game for everyone. With every new addition, it seems there is a new way to grief.

Take a harpoon gun? Lace with poison? Leave out in the open? Profit. It's a cool idea but frankly a bit specific and might become a bit confusing, as well as adding the griefer factor.

**Comment by BillCombs** [comment]
Maybe also make it so the doctors (or anybody who would put the health scanner on) could see if the item was infected(perhaps you could make it have a small glow effect if that wouldn't affect game's performance too much), since they deal with chemicals a lot in this game?

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
