### ISSUE TITLE
Orca reactor fire delay so short it can be on fire at round start

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4730]
- [] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Orca's short reactor fire time of 7s is short enough that a sufficient fuel load can set the reactor on fire by the time players gain control.

there is nothing a player can do about such a pending catastrophe

**Steps To Reproduce**
1. load up reactor with 3 Thorium fuel rods or something 
2. turn on automatic control
3. leave outpost
4. by the time the round starts and players gain control, the reactor is already on fire

**Version**
0.11.0.10

**Additional information**
expectation is for things that happen during loading times to not affect players (much), as what happens during that time is completely out of the players control

**Comment by Ek-Videogames** [comment]
- Also a tangential issue is the fact that the reactor initializes at the beginning of the round in a critical state after round change under certain fairly common campaign-save / desync circumstances

**Comment by Benzin73** [comment]
Having this problem as well, on unstable 0.12.0.2
Almost every time i start a mission, the reactor is on fire. It has killed my captain twice now.

**Comment by Benzin73** [comment]
An update on this:
It got to a point, where i couldnt continue my single player campaign. Because every time i loaded the game (docked at an outpost), the reactor was allready on fire. Any attempt by me and/or the bots to enter the reactor room and extinguish the fire, resulted in an explosion that killed anyone near by.
Also tried using the "Shutdown reactor" button on the nav console. It did nothing.

The only way i found to get arroudn this problem (for now), was to search the outpost for the guy that upgrades subs, pay the fee for "Repair all items", then purchased two upgrades for "thermal tolerance" of the reactor, saved the game and loaded again.

Now the reactor is not on fire when i load the game. But the walls in the room look scorched.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4edd688e0e580c636131ed1524b03e660709bf5e.

**Comment by ubertpendragon** [comment]
> Should be fixed in [Regalis11/Barotrauma-development@4edd688](https://github.com/Regalis11/Barotrauma-development/commit/4edd688e0e580c636131ed1524b03e660709bf5e).

Unstable v0.1400.1.0
Now sets reactors on fire at the start of the round, consistently, which doesn't happen on stable

![image](https://user-images.githubusercontent.com/73229309/119390843-e4ed3300-bccd-11eb-9add-b897d89ad06e.png)

Most likely an issue with having multiple rods in the reactor

**Comment by Rokvach** [comment]
Moved to Misc

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1de27efba87f4e57dca4e0da307cb1403a7d8ddc.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
