### ISSUE TITLE
Implement status effect "OnEaten" and Item target "EatTarget"

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#478]
Version 0.8.1.4

A small idea I came up with in my head, essentially fish can consume bodies, but not chase after or be drawn to particular items beyond the effects of the nasanov artifact.

It could be possible to add lures to the game to get fish to "Eat something else" than a player character, give these items values for eat time or something (I believe characters are currently based on mass).

I understand the vanilla game might not implement this but it could be interesting in the use of modded content packages - even BTE implements food and meat or tries to.

Additionally adding to the statuseffect system "OnEaten" which could cause effects if consumed by an NPC character (Either inside the inventory of - or directly). this could allow poisoning of fish that eat, perhaps with conditionals if a modder wanted that.

I don't personally think barotrauma (In its short round-by-round design) has a good use for a food mechanic on players, though if a modder ever wanted to implement that themselves i'm sure they could trigger OnEaten with few changes to the code and reuse the above - Though I feel its more for creatures and new tactics.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
