### ISSUE TITLE
Swapped character with disconnected player in multiplayer

### ISSUE THREAD

**Issue by NikolajDL** [Regalis11/Barotrauma#4798]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was playing multiplayer with a few friends on a dedicated server. After we docked, we started some maintenance and cleaning, when one of the other players quit. The moment that person quit, I was immediately "teleported" to the outpost where we were docked, and I had become the other player. We basically swapped characters. My own character was still in the submarine, just running on the spot with a suitcase full of all our welding fuel. We tried starting a mission, hoping I would return to my own character, but instead my own character disconnected (with all our welding fuel) and I controlled the character of the person who quit. When we eventually went back to the lobby, a log message said that my character had changed name to the other character. 

**Steps To Reproduce**
Given playing multiplayer, on a dedicated server (not sure whether the bug will exist on a regular hosted game).
When docking to a station, then the moment the station has loaded, one player must disconnect from the game.
Another player should now have their character swapped with that player. 

**Version**
v0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)

**Additional information**
I was on the same local network as the player who disconnected, so we share a public IP address. That might be what caused the issue in this situation.

**Comment by timgagliardi** [comment]
Had the same problem.

My assumption is that the server decides which user he should load based on the endpoint inside the `CharacterData.xml` server file. I crosschecked a savegame from a p2p session and with a dedicated server and inside the p2p session the savegame contains unique Steam references and not the public IP.

**Comment by timgagliardi** [comment]
https://github.com/Regalis11/Barotrauma/blob/e47f0850a52709d6b3e0e92c67135124c1e61a11/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs#L392

I'm pretty sure that this could be the issue.
Using `steamid` instead of the `endpoint` could maybe solve this issue.

After further searching inside the code it looks like the steamId is used for permissions and inside `SteamP2PConnection`, but not in `LidgrenConnection`.

https://github.com/Regalis11/Barotrauma/blob/e47f0850a52709d6b3e0e92c67135124c1e61a11/Barotrauma/BarotraumaShared/SharedSource/Networking/Primitives/NetworkConnection/LidgrenConnection.cs#L44

TBH don't know if this could be easily fixed or if this has some implications that I am not aware of.
Hope this maybe helps

**Comment by JoneKone** [comment]
one of my dedicated server users complained this happened. (similar) current version v0.14.6.0

**Comment by Regalis11** [comment]
Fixed in Regalis11/Barotrauma-development@7093591
