### ISSUE TITLE
[0.12.0.0] Console Command issues

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4867]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Cannot give server owner all commands in P2P server, when you can give specific ones to other players/admins. Essentially server owner would have less command access than other players/ranks.

givecommandperm "ServerOwnerName" all
Cannot modify the command permissions of the server owner!
givecommandperm "ServerOwnerName" bindkey
Cannot modify the command permissions of the server owner!

2. Certain commands needs permissions in servers. Seems like some of them should be able to be used for just client?:

bindkey
fpscounter
savebinds
setfreecamspeed
togglevoicefilters
unbindkey
wikiimage_character
wikiimage_sub

**Version**
0.12.0.0

**Comment by Regalis11** [comment]
1. The server should bypass the permission checks when the command is executed by the server owner, so there should be no need to give the owner any command permissions. Is there some specific command that's causing you trouble?
2. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/27d11c4a26dd6bfdf930f2a2ffb671e58cf5eb62

**Comment by Kaillera** [comment]
The new commands for instance

**Comment by Regalis11** [comment]
In that case this should be fixed now

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
