### ISSUE TITLE
[0.12.0.2] Getting Perma stunned by aliens

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4983]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
With the rework on AI, enemies such as crawlers, mudraptors, tiger thresher, and all the hatchlings can perma stun the players with consecutive attacks. They don't bounce away after attacking the player, so now they can pretty much keep attacking as they hold onto you.

**Version**
0.12.0.2

**Comment by itchyOwl** [comment]
What do you mean with the "rework on AI"? Is this the same stun lock issue that was reported before or is it a new one?  I haven't been able to repro the stun lock issue, although I have seen one video (an old one) where it definitely happened.

Does the issue happen when there are multiple monsters or just one?

**Comment by Kaillera** [comment]
Iirc the circumstances for this ticket was another diver and me out in a cave that sucked oxygen out with the bushy environment that slows down character from moving. 3 crawler hatchling hatched and basically kept biting without bouncing out after each bite. They pretty much kept us in stunlocked.

**Comment by itchyOwl** [comment]
I'm not sure what you mean with bouncing out, but all crawlers should continue their movement forward after the attack executed in water and come back after a few seconds. So even a larger pack shouldn't stun lock you. And it's the same with tigerthreshers and mudraptors. In general no monster should continue frequently pushing and attacking you in water. On dry ground many do, but even there it should be relatively easy to back off and attack the creature, because those attacks should do very little stun with a lower probability. I've tested this with spawning more than 5 monsters around me at different distances to spread their attacks a bit and still I haven't found a way to get stun locked. Neither in water nor on dry ground.

With the stun lock do you mean that you couldn't move or couldn't shoot? The bushes slow you down, so it makes running away impossible, but it's pretty impossible anyway unless you happen to have scooter with you. So if you run out of bullets, that's pretty much game over there. And I don't think that's a bug. However, if you can't shoot at all, then it is a bug.

**Comment by Kaillera** [comment]
They bite us every half a second without going anywhere and held us in stun animation.

**Comment by Kaillera** [comment]
It looked very similar to this: https://youtu.be/ZxU-N-HM_Ws, but worst.

**Comment by itchyOwl** [comment]
The issue with bushes should be fixed in Regalis11/Barotrauma-development@44deac9.

**Comment by itchyOwl** [comment]
I also did some adjustments on the monster attacks. I'll move this on QA.

**Comment by Rokvach** [comment]
There hasn't been any mentions of this behavior since it was fixed, seems to be working correctly. Closing.
