### ISSUE TITLE
Font is too small

### ISSUE THREAD

**Issue by abiglari86** [Regalis11/Barotrauma#4993]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Font appears too small to read making the game difficult or even unplayable at times. Reducing resolution does not resolve the issue and just makes the game pixelated. I've seen the github fix but this needs to be integrated. That's what this ticket is about; not just fixing it in a separate github project and calling it a day.

**Steps To Reproduce**
Any device connected a 4K monitor, surface book, retina, or UHD television screen.

**Version**
Most recent to date on 2/4/2021.

**Additional information**
Please fix this... I know at least 7 other players who will all will be very grateful when this is fixed! Also, I'm aware of the github fix for this BUT this shouldn't have to be added manually. Most of my friends are not technologically savvy enough to make this installation and I would imagine most players would follow suit. Thank you!

**Comment by Regalis11** [comment]
Thank you for the report!

It sounds like you may have misunderstood the previous ticket (https://github.com/Regalis11/Barotrauma/issues/3224): we have fixed the issue, but that was just 2 weeks ago, and we haven't released a new update since then so the fix isn't yet publicly available.

We are however releasing an update next week, and the fix will be included in it. Sorry for the inconvenience, and thank you for your patience. :)
