### ISSUE TITLE
Unable to ban players.

### ISSUE THREAD

**Issue by EricPfau** [Regalis11/Barotrauma#5028]
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Banning players appears to not be working. Clicking on a player and trying to ban them, does not ban them.

**Steps To Reproduce**
Attempt to ban a player, either from GUI (Clicking their name) or from Console. Neither appear to work. Tested both on Steam version as Host, and Dedicated server (Linux gsm)

**Version**
0.12.0.2 (Latest)

**Additional information*
Will need to shut my server down again until fixed, unable to moderate griefers without this ability. Similar impact as issue #4163

**Comment by ubertpendragon** [comment]
Can confirm, tried to ban a player and nothing happened; player doesn't seem to be in the ban list either

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d745848c39e96d21ec61cdb813478f74af6e129. Seems that this only occurs when giving permanent bans to a client who's currently in the server: as a workaround until we get a patch out, you could give the clients bans with a long duration or kick them before banning them.

**Comment by Rokvach** [comment]
Tested by banning myself from a dedicated server permanently, I was successfully added to the banlist and booted off the server. So this seems to be working correctly. Closing.
