### ISSUE TITLE
Seed-specific crash

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#5060]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash occurs when the sonar interface is accessed.

Crashlog: 
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5976969/crashreport.log)

**Version**
Win10, 0.12.0.2

**Additional information**
I'm currently stuck in this mission, since I need to access the sonar interface to redock so I can avoid the bug, but I can't since it causes the crash, any suggestions on countering this would be [welcome.]

**Comment by Regalis11** [comment]
Based on the crash report, this seems to happen because there's no beacon station in the level despite you having the beacon mission. I added a null check that should prevent this from crashing the game when it occurs (https://github.com/Regalis11/Barotrauma-development/commit/36d548955142c958ad9ccfa28c039e7052a999d9), but I'm not sure how it happened in the first place. Would it be possible to send us the save file in case it'd give us some more clues?

As for a workaround, if you can enter the outpost by diving, you should be able to leave the level and hopefully get past the issue.

**Comment by OverwatchVoice** [comment]
Sorry it took me so long to get back to you. Here's the save file. (Had to save it as zip because github was being dumb)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/5995849/Save.zip)

**Comment by Regalis11** [comment]
The issue doesn't seem to occur in the latest Unstable version, closing
