### ISSUE TITLE
Game not running on Ubuntu 20.04

### ISSUE THREAD

**Issue by fonikz** [Regalis11/Barotrauma#5095]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've tried launching the game via Linux Runtime, Proton, and GloriousEggroll and the game window will not open. The task itself is running in the background, but no game window ever pops open.

**Version**
Build ID 6246229
Ubuntu 20.04.2 LTS
Intel Core i5-3470
8GB RAM
AMD Radeon HD 7900 Series

**Comment by hubismal** [comment]
that has occasionally happened to me, but when it does, it's consistent with all other games for some reason. I think it happens because a library doesn't work or something. restarting fixes it for me when it does happen. you could also try going to .steam/steam/steamapps/common/Barotrauma/ and running ./Barotrauma from there

**Comment by JoneKone** [comment]
I have it running on 20.10, Do you have multiple monitors?
