### ISSUE TITLE
[0.1300.0.0] Wreck wedged into level walls

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5097]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sub: Orca
Level seed: q6JOJtFa
![Capture](https://user-images.githubusercontent.com/5086682/108525992-a3985200-729e-11eb-9e31-4f35f8c12d9d.PNG)

**Version**
0.1300.0.0

**Comment by itchyOwl** [comment]
So, what's the issue here?

**Comment by itchyOwl** [comment]
It does look a bit weird (how would it get there?) But other than that: does it cause any issues?

**Comment by Kaillera** [comment]
No idea if we are able to traverse inside the shuttle with the level wall in it or not. Reported it just in case.

**Comment by itchyOwl** [comment]
You should be able to enter it here: ![image](https://user-images.githubusercontent.com/5370738/108975926-ad032f00-768f-11eb-876e-0c374d12d54a.png) Of course you can't enter through a level wall, but there shouldn't be any issues if the sub is partially inside a level wall when you are inside the sub. You shouldn't be able to enter inside the level wall from the sub either. There were some issues with this when we added the wrecks, but I think we managed to solved them all.

Wrecks are allowed to be partially positioned inside level walls because that helps finding a suitable position for them. And I think it looks fine if they are a bit inside the level walls (crashed and crushed?). However, adjusting the thresholds is possible if there is a reson to. But I think this is a very extreme case and still it's not too bad. Unless there are some technical issues that is.
