### ISSUE TITLE
Can't see Sprayer particles when another player is using the Sprayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5101]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f151fa6512d295543c2328480131095962a7e281

> Fixed other players not seeing the sprayer particles. Happened because we needed the targetSections (wall sections the sprayer is painting) to determine the end position of the particles, which are calculated client-side and not synced between players. Simplified the logic by just emitting the particles towards the client's cursor position. 

Note that I took a bit of a shortcut in fixing this: clients don't know the exact cursor position of other clients, just the direction which they're aiming at (but not the distance). I didn't consider it worth the trouble to address that for an issue as low-prio as this, so I just made the clients assume the remote client is aiming at 50% of the sprayer's maximum range, which in my opinion looks good enough.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/09b8873e88f8ca7b179d3f0fda9384e6ec5e727e

The sprayer will fire even if the player using it is aiming at a location they cannot clean (IE. through a solid wall). Curiously the player using the sprayer will see no effects when used through a wall/door but other players will see them.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/0b2d49ccd119c0e932389f71cf6fa7ab6d7680f0, no issues found, closing.
