### ISSUE TITLE
[0.12.0.3] Moving a full oxigen bottle into a diving suit stack makes the stack turn into a single item

### ISSUE THREAD

**Issue by Alex387-crypto** [Regalis11/Barotrauma#5111]
When having a oxygen bottle stack, of which the last bottle should be partially emptied, in a equipped diving suit, and moving a filled bottle into said stack, results in a single bottle inside the suit and the partially emptied one will be in the player's inventory (or container's one).

This was tested in the submarine editor, while i was testing the airlocks.

Here's a video with the ways i found to "lose" bottles
https://youtu.be/DaDyJGU-DHE

**Additional information**

**Comment by Ek-Videogames** [comment]
**#"NotABug"**

#4858

**Comment by Regalis11** [comment]
@Ek-Videogames It is definitely a bug, we closed the earlier ticket because couldn't find a way to reproduce the issue and assumed it had been fixed.

I suppose the key to reproducing this is to put multiple tanks into the diving suit, but I'm afraid I still haven't been able to find a way to do so, even by following the exact steps in the video. I wonder if this could have something to do with a specific diving suits not having the stack restriction (= 1 tank per suit), perhaps in some submarine or save file done in an earlier version of the game...? Can you get this to occur in the vanilla submarines as well, or would it be possible to send us the custom sub you're testing this in?

**Comment by Alex387-crypto** [comment]
Ii am sorry for wasting your time, but it was a mod conflicting with one another (i am not sure, but may be ek's utility with into the abbyss), removing one of the mods makes the diving suit not to be able to stack oxygen canisters again.
