### ISSUE TITLE
[0.1300.0.0] Modding - Abandoned Outposts can spawn non-abandoned module when increasing the amount of module limit

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5124]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When modding Abandoned Outposts, they can spawn non-abandoned module when increasing the amount of module limit.

![](https://media.discordapp.net/attachments/668819422919524352/813166831811559444/Capture.PNG)

**Steps To Reproduce**
```
  <OutpostConfig
    identifier="abandonedoutpost"
    totalmodulecount="12" minhallwaylength="20"
    allowedlocationtypes="Abandoned"
    spawncrewinsideoutpost="false"
    alwaysdestructible="false"
    alwaysrewireable="true"
    allowstealing="true">
    <modulecount flag="Airlock" count="1"/>
    <modulecount flag="EngineeringModule" count="1"/>
    <modulecount flag="AdminModule" count="3"/>
    <modulecount flag="CrewModule" count="3"/>
    <modulecount flag="ResearchModule" count="2"/>
    <modulecount flag="SecurityModule" count="2"/>
  </OutpostConfig>
```

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
This happens because there's not enough suitable abandoned modules available: the modules you're trying to place more of are only configured to appear once per outpost, so the game falls back to one of the "generic" modules. If you want to use a configuration like this, you either need to increase the "maximum count" setting of the abandoned modules or add some new modules.
