### ISSUE TITLE
Workshop mod downloader works incorrectly if there's a hash mismatch when mod is already installed

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#5154]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When attempting to join a server with Workshop mods that the client has already installed but still mismatch the server's versions of said mods, the game will attempt to download them again only to freeze after a second attempt.

**Steps To Reproduce**
- Find a server with Workshop mods installed, make sure there's a hash mismatch that the client cannot resolve.
- Attempt to join it, then accept the mod download request.
- Watch it fail and accept the second mod download request.

**Version**
v0.12.0.3

**Additional information**
We could be dealing with another issue regarding the hashing of downloaded mods that is generating a mismatch without either the host or the client needing to be out of date.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/331e79385fca6078323908fd2d3b1e2b16001ef3

**Comment by Rokvach** [comment]
@juanjp600 How should I test this? Took a look at the branch and nothing obvious came up as to how I should do it

**Comment by juanjp600** [comment]
I used the following method:
- Copy the entire game into a separate folder, deliberately modify a Workshop mod to change the hash, and then run a dedicated server with that mod enabled.
- Try joining that server with a client with the unchanged mod, and follow the steps listed above.

I would also suggest testing with more people to be able to analyze the causes of hash mismatches in the first place.

**Comment by Rokvach** [comment]
Changing the mod to force a new hash shows correctly that I am running a different version of the mod rather than tries to download the mod regardless. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5ad2b973-be35-4b5f-a5db-00883146dec5)

Using exact same steps on dev results the game to try and subscribe to the mod even though the hash is totally different and keeps looping if you try to move forward

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8970c413-90b5-4555-860e-1f640d9e2ce4)

So the issue has been fixed at least to this level, will still need to see how it acts in actual multiplayer setting with multiple players

**Comment by Rokvach** [comment]
Don't think this can be further tested without including it to a Unstable build or testing internally with a larger group

**Comment by Rokvach** [comment]
There hasn't been any type of issues when using mods, seems to be working correctly. Closing.
