### ISSUE TITLE
Players keep getting prompted for sub downloads when the host has disabled sharing sub files

### ISSUE THREAD

**Issue by tiba666** [Regalis11/Barotrauma#5191]
was ment to search if it was up first but now but i missclick..

if im host a game but unclick share submarine files with players people keep getting the download sub over and over and over agian in endless loop  and crashing im playing on 0.12.0.0.3 i belive..

when you in lobby as a host click setting -> general-> share submarine files with players uncheck that box .   

it at least do that with custom subs

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/581ddea4ab0461d78bcfdfb423839c18e8576cca

**Comment by Rokvach** [comment]
Tested, now it just tells the client that they are missing the custom submarine used by the server with just a "Ok" option, it does open up multiple times but not in a endless loop also the client doesn't crash because of this. I think this is working, I made another ticket of limiting host from starting a round with a custom sub if they have the setting disabled as that just causes issues. But closing this one.
