### ISSUE TITLE
Beacons/Wrecks spawn and are locked on the "floor" of the map

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5199]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Beacons/Wrecks spawn and are locked on the "floor" of the map, preventing movable wrecks, and the possibility of making "ceiling" beacons and wrecks (example: wrecked outpost entrance)
Shuttles attached to wrecks do not have this restriction

Request: Allow us to "unlock" beacons/wrecks, or have the option for "ceiling" spawn 

**Steps To Reproduce**
-Give a wreck/beacon a massive, empty hull for buoyancy
-The wreck/beacon doesn't float up

**Additional information**
Beacon with positive buoyancy, stuck on the "floor"
![image](https://user-images.githubusercontent.com/73229309/110326088-78409180-8018-11eb-9152-99c75a919daf.png)

**Comment by Regalis11** [comment]
While I agree this could be useful for modding, I'm afraid it's pretty low prio. Even though it'd be easy to add a setting for making them movable, many of the systems in the game assume they're immovable, so it could lead to a variety of bugs if we don't test everything carefully.

We might take a look at this at some point, but I'll close the ticket in any case since it's more of a feature request than a bug report.
