### ISSUE TITLE
"Bind" command for console

### ISSUE THREAD

**Issue by Fakyring** [Regalis11/Barotrauma#521]
What's about "bind" command for console like in games made on source engine(Half-Life, G'Mod)? That may help hosts and admins very much in server administriating

**Comment by NilanthAnimosus** [comment]
I assume this means creating a hotkey for a console command, and not literally changing the controls via the word "Bind" since that was its intention in source. it is likely possible to implement this in some form.

**Comment by ZealanL** [comment]
I was able to implement this command in 0.8.17, just made an additional client-side DebugConsole command that adds a key listener to the selected key, and executes that command. Doesn't have un-binding though, and doesn't save your keybinds. But it works fine, and those features (especially the latter) would be really easy to implement.

**Comment by NilanthAnimosus** [comment]
It's not so much the ease of making it as thinking of having the GUI changes to support and edit them more easilly for any user. At least if I would try to implement this I would actually focus on including a GUI to better handle it.

Ofc, the ability to bind/unbind and save/load the binds is sort of a necessary step too.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
