### ISSUE TITLE
Signal Check components can't send spaces

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5258]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
a value of " " (one or more space) doesn't get sent in signal check outputs

**Steps To Reproduce**
put space (one or more) as signal check's outputs (false/true)

**Version**
0.12

**Additional information**

**Comment by tiba666** [comment]
might be a part of the design i read the code line and it says: " 
 if (string.IsNullOrWhiteSpace(signalOut)) return; "  and a space is called whitespace my guess is a compromise they had to make for people who dont want to send any signal output if the field is empty. and increase the performance...

can i ask what you trying to do since  you want to send spaces around with the signal ?

**Comment by Regalis11** [comment]
This isn't actually related to performance: I think it's just an oversight (the logic was probably copied from some other logic component that treats whitespace as a "false" signal. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0085df88c429ec563fceb5977b88f363a9c18b2b

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
