### ISSUE TITLE
The error prompt is phrased in a confusing way

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5265]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Barotrauma_IZZC53QPMQ](https://user-images.githubusercontent.com/10529134/111502511-2f8a8600-8746-11eb-8465-f927cbd5a0a7.png)
It says `The error was not reported to the developers because user statistics have been disabled`
This creates the question "How can I enable user statistics?"

I propose this: "The error was not reported to the developers, as errors cannot be sent automatically, but if you'd like to help (...)
**Or**: "Errors cannot be reported automatically. If you'd like to help the developers, (...)

**Version**
v0.12.0.3

**Comment by Regalis11** [comment]
This is a remnant from back when we used a library called GameAnalytics to collect error messages and such, which we've since disabled because of complications caused by GDPR. We're planning on readding the option to enable GameAnalytics in the near future, so I think it's probably not worth the trouble to rewrite the line (and translate it to a dozen languages) at this point.
