### ISSUE TITLE
Putting items in lost limbs

### ISSUE THREAD

**Issue by sylvinite** [Regalis11/Barotrauma#529]
If you somehow manage to blow off your own arm and remain alive, then place an item in the, now missing, hand, The client has absolutely no idea what to do and just teleports the item around in the clients' viewable area.

The setup for this is extremely contrived, but I figured I would report it anyway.

**Comment by Regalis11** [comment]
Excluding console commands, is there a way to stay alive after blowing your arm off? It should not be possible for limbs to get severed unless the character is dead, but if it is, that's a bigger issue than items acting strange when controlling a dismembered torso.

**Comment by NilanthAnimosus** [comment]
This is essentially an issue with reviving players with lost limbs - personally I think the limbs should be re-attached to the player (As funny as it is watching a players ragdoll run about hopping on one leg with only one arm carrying a floating welder that is teleporting about)

I would not like to see players unable to be revived if they die to explosions and lose limbs - since that is essentially a tool of admins to revive those who weren't meant to die within a servers rules, as simple as that would be of a fix.

It is indeed impossible (Even with my mod) to stay alive and lose limbs, when a creature eats a minhealth player who cant die - they are killed before losing the limb in my modification, and its only possible to lose a limb after one is dead in it.
