### ISSUE TITLE
Humpback lost it's preview image

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5316]
- [ ye] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Humpback shows no preview image when selected, sometimes appears once you click the non-existing image.
**Version**
Unstable v0.1300.0.3

**Comment by Rokvach** [comment]
I wonder why the previews keeps constantly vanishing

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9836985ec56ae5197178e322c780f34691893402

The preview image seems to have disappeared in https://github.com/Regalis11/Barotrauma-development/commit/bc5071a9, although I have no idea how. Let's keep an eye out for this and try to figure out what causes the images to disappear.

**Comment by Rokvach** [comment]
No issues, closing.
