### ISSUE TITLE
Bots try to repair the items in abandoned outposts

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5341]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of my crewmate bots with the repair order, decided to fix the items of the abandoned outpost, and got shot to death.

**Version**
v0.1300.0.3 Windows

**Comment by Regalis11** [comment]
Todo note: seems to have been caused by the changes in https://github.com/Regalis11/Barotrauma-development/commit/406346d4

**Comment by ekqvist** [comment]
I was able to reproduce this on v0.1300.0.3, but I couldn't reproduce it anymore on v0.1300.0.7. This seems to have already been addressed in an unrelated commit (Regalis11/Barotrauma-development@765af4b) by making outpost items invalid targets for repair objectives. The fix was probably just accidentally committed with the other changes.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce it either, even asked the bot to follow me in to the abandoned outpost and then ordered them to repair devices and nothing. So working correctly, closing.
