### ISSUE TITLE
Make railgun controllers work over wifi

### ISSUE THREAD

**Issue by 8o7wer** [Regalis11/Barotrauma#535]
Listen up here regalis. I've spent the past hour trying to make a remote control sub to find out that ~~control~~ ~~monitors~~ railgun controllers don't work over wifi components. Valve plz fix.

**Comment by 8o7wer** [comment]
Update: I can manually wire to the camera and it works but its not good enough for an actual sub

**Comment by NilanthAnimosus** [comment]
dev already has separate sonar-to-monitor devices that can work over subs. control of subs works too just the monitors position is itself which dev already implemented.

railgun controllers should work as juan changed the signal to output an angle from 82dcbc3ae85b13617aba559ca387964af804d3b5

**Comment by Regalis11** [comment]
The issue seems to be that controllers make the camera focus on the item that's connected to the position_out connection, other than that railguns seem to be working correctly. I think one way to solve this would be to make the controllers focus on the last focusable item that receives the position_out signal.
