### ISSUE TITLE
I'm crashing every game... please help... me...

### ISSUE THREAD

**Issue by trashmvn** [Regalis11/Barotrauma#5361]
- 
[crashreport (36).log](https://github.com/Regalis11/Barotrauma/files/6220010/crashreport.36.log)
 ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every game ends up with a  sudden crash 
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac). 
Mac

**Additional information**
please help me.. I never finished a mission in my life

**Comment by Regalis11** [comment]
Hello!

This is a known issue that unfortunately slipped in to the last Mac version of the game. It's been fixed in the Unstable version of the game, but it will take a little longer before we can make the fix available in the public Steam version. If you'd like to give the Unstable version a try, please see https://barotraumagame.com/announcements/barotrauma-tester-version-made-public/

We already have an existing ticket about the issue (https://github.com/Regalis11/Barotrauma/issues/4504) so I'm closing this one.

Sorry for the inconvenience!
