### ISSUE TITLE
Way to play as medic or security when there are 3 or less players

### ISSUE THREAD

**Issue by tgs903** [Regalis11/Barotrauma#537]
When I go into a game with my friends. I went to the class Priority I put Medical doctor to the top as 1. I set engineer to 9. When we went into the game I automatically spawned as engineer even though there is no Medical doctor ruining what I wanted to play. I have no clue why this happened but it ruins the experience of playing the class you want.

**Comment by NilanthAnimosus** [comment]
there is a minimum in vanilla of 1 captain, 1 engineer then 1 mechanic in multiplayer, where only the host bypasses this.

my mod on the undertow forums can bypass that, but its out of date (.9) and i have no keyboard at the moment.

if your friends all modified the jobs.xml and shared it just for your private play with min= removed from each job thatd work too.

this is more a multiplayer feature/check to prevent uncompletable games as those roles are considered vital.

**Comment by Regalis11** [comment]
As NilanthAnimosus explained this is not a bug, but an intentional way to make sure there's at least one captain, engineer and mechanic. Having a way to bypass it would be a good addition, although I think in the dev version the minimum number could be removed altogether. In the master version engineers and mechanics are actually vital, as it's impossible to repair certain items without the right skills. In the version any character can repair any item, it just takes significantly longer with insufficient skill levels.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
