### ISSUE TITLE
Trigonometric Function: COS(90) != 0

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5416]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cos(90) != 0

**Steps To Reproduce**
1) DO cos(90) with circuitry. 
2) Observe!

**Version**
Windows unstable v.0.1300.0.4

**Additional information**
This seems to only happen to the cos component for some reason.
![image](https://user-images.githubusercontent.com/55001203/113377412-39190e00-9342-11eb-8e70-16f2899075e5.png)
![image](https://user-images.githubusercontent.com/55001203/113377425-40d8b280-9342-11eb-81a8-0f4b394a9e7b.png)

**Comment by Regalis11** [comment]
This happens due to the inaccuracies in floating point math (see https://0.30000000000000004.com/). The value given by the component is practically zero (-0.0000000437) so I don't think this makes much difference in practice.

We could see about prettying up the outputs of the components a bit (something like only displaying up to x decimals, and preventing scientific notation from being used on very small values), but I'd consider this a low priority.

**Comment by FamiliarBreakfast** [comment]
There's always the [Decimal Structs](https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=net-5.0) included in C#. I don't really think storage space is a concern here.

**Comment by Regalis11** [comment]
Decimals don't really solve this, they're just a more precise type of floating-point numbers. So in this case the value would still be non-zero, just with more zeroes after the decimal separator.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
