### ISSUE TITLE
NPCs take item off the fabricator to use them

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5431]
- [ yeah] I have searched the issue tracker to check if the issue has already been reported.

**Description**
NPCs take items you're using to craft something (even when the fabricator already started crafting) when they need them for something.

**Steps To Reproduce**
A good way to test this is diving suits, start crafting a combat/abyss suit with the only diving suit on board, make sure there's an npc  with the "fix leaks" order, and create a leak that floods a compartment

**Version**
v0.1300.0.6

**Comment by itchyOwl** [comment]
Related to #5400. Possibly fixed.

**Comment by LePiromano** [comment]
Still happens in 0.1300.0.7

**Comment by itchyOwl** [comment]
Ok, I'll check it.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c9ec976. Added "ignorebyai" tag for fabricator, deconstructor and medical constructor, which means the bots shouldn't ever take items from them. If we can't categorically deny them from using those items, it would become difficult to solve: when they should be allowed to take the items and when not?

Btw. a workaround for this is to use the "Ignore this" order, which should work just the same.

**Comment by LePiromano** [comment]
The fix works in 0.9, now they don't take the items from the fabricators... nor they fix the fabricators...
About "when they should be allowed to take the items and when not?", would it be possible to make it so npcs only take items from the fabricator when it's not functioning?

**Comment by itchyOwl** [comment]
Ok, so introduced another tag "donttakeitems" to overcome the earlier issue.

Fixed in Regalis11/Barotrauma-development@9fa853d (bugfixes).

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
