### ISSUE TITLE
Submarine Editor saves not just item references, but items themselves

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#5435]
Basically during my attempts to create custom modules, i found out that placing a module in a sub, saving the sub, making changes to a module then loading sub doesn't apply those changes until i delete the module and place it again, which means the .sub file probably contains not just references to that module, but it's data aswell, which makes development of modules and items (i tested it with items aswell, placing them in storage containers) harder
also this probably means, that if an update rolls in, that makes changes to a vanilla modules (like junction boxes, which i posted about earlier, (thx for the fix, much love)) the previously made submarines will have to be remade and modules replaced and rewired from scratch, b.c the .sub file will still contain old item's data instead of just referencing it by an identifier

**Comment by Showdoze** [comment]
UPD, seems like it saves not all the items, like Turrets are updating after you make changes, can confirm that pumps, batteries, handheld items, storage containers, supercapacitors aren't updating

**Comment by Regalis11** [comment]
This is actually intentional: we do need to save the item's properties, not just references to the items; otherwise it'd be impossible to edit the items in the subs.

While I can see the benefit of automatically carrying out changes done to an item assembly to the items in the sub(s), it would cause other types of complications: what to modify if some items/parameters of the assembly have been modified in some sub, does modifying an assembly mean all the subs that use the assembly become incompatible in multiplayer, do other players need to download the exact same versions of the assemblies to play with you in multiplayer...?

In any case, this issue tracker is for bug reports, and since this is intentional behavior, I'll close the ticket.

**Comment by Showdoze** [comment]
I see, maybe i'm missing out on something, but if it's a vanilla sub, the changes should automatically update on everyone who have the new game version, and if it's a mod sub, then it's on mod author's responsibility to update it, that's how it is done in every game i remember with multiplayer mods (satisfactory for ex.)
since you're the dev and i'm just a pleb, i can only kindly ask to consider maybe adding an option to a sub editor for saving/not saving item's data to a sub, so we can have benefits of both worlds
