### ISSUE TITLE
"Extravehicular Activity" achievement not registering

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#5456]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "Extravehicular Activity" achievement does not register, even when travelling over 500m from the sub

**Steps To Reproduce**
Grab a diving suit, handheld sonar and underwater scooter, and travel at least 500 meters away from the submarine.

**Version**
Current Stable Vanilla Build

**Additional information**
I'm not sure if this is an achievement meant to only trigger when the round is completed, but all videos and guides on getting this one show that you get the achievement when you pass the 500 meter mark.

**Comment by ekqvist** [comment]
We check for the achievement periodically through the round, but I think the issue here is that we check for linear distance for the achievement, i.e. the distance between the sub and the character in a straight line, whereas the distance displayed on the sonar is calculated using the waypoints between the sub and the character which can usually be more than the linear distance.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@4d8b71f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
