### ISSUE TITLE
[QoL Bot Suggestion] Bots should automatically try to revive you in a campaign mission if they notice you in critical condition regardless of their current order and job

### ISSUE THREAD

**Issue by Dexo21** [Regalis11/Barotrauma#5461]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The reasons why this would be a great Quality of Life addition is because there's way too many cases of whole missions being failed because of the bot crew not willing to revive downed players unless there's specifically an order to revive players given to them. It would help the bots to be much more reliable than they are right now. I imagine not many people trust Barotrauma's bots because they usually always act on orders but not much on themselves.

**Version**
Current versions of Barotrauma, including v0.1300.0.7 unstable.

**Comment by Showdoze** [comment]
i'd add the same functionality for every instance of AI job (for example, if an engineer sees damaged equipment, he will repair it, if anyone sees a hull breach, they will try to find welding tool, and repair it, etc) bc i can recall dying just because i forgot to reassign orders to a crew after loading screen, and they were just walking there while ship was getting damage, leaks and started to drown

**Comment by Udrakan** [comment]
Better Idle behavior system would be nice. NPCs using beds&chairs, repairing items they walk past etc.

**Comment by itchyOwl** [comment]
The bots can actually do quite a lot autonomously, but it's not our intention to make them so autonomous that the player don't have to manage the systems (play the game) at all.

Another issue with too autonomous behavior is that the bots could do things that the player don't want them to do. And that's very annoying. Like heal minor damage when they shouldn't. Or in this case: shoot everything on their own so that the player would have to tell them to do something else to keep them in bay.

But I'm sure there's room for balancing it: making them do things without having to tell them without it being too pervasive.
