### ISSUE TITLE
[Unstable] Incorrect location info in tab menu after a crash

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5512]
Can be reproduced by following the steps in the ticket about hunting grounds crash https://github.com/Regalis11/Barotrauma/issues/5510 and then loading up the save again after the crash and checking the tab menu

Alternatively you can load up the provided save and check the tab menu once you've loaded in

We were in a abandoned outpost before we teleported to that hunting grounds level where the save loads in

Save:
[https://app.zenhub.com/files/175046454/f92ea55e-0ea5-4902-b3a6-1fe62e75d9be/download](https://app.zenhub.com/files/175046454/f92ea55e-0ea5-4902-b3a6-1fe62e75d9be/download)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/89fcfcef-cb4d-43ca-b9bb-4436458f289d)

**Comment by Regalis11** [comment]
I think this actually worked as intended. What happened in #5510 was that the sub was teleported from the path from A to B into the path from C to D, but the server tried to start a round in a path from B to C (thinking the sub now reached B, and that the next path should continue from there). Since that failed, it'd load the previous valid location.

This should no longer happen though if the fix for #5510 works.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
