### ISSUE TITLE
Windowed door window misalignment ( & first vector Y axis is reversed )

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5516]
For the longest time noticed that the 'see through' area of the windowed door included the small top bit of the door beyond where the window on the sprite ends. _(Originally I thought it not much of it than possibly intentional or due to some kind of limitation with the line-of-sight code.)_ Upon further investigation it seems the original source of this could have been done in-error, this is because how window rectangles are defined seems to have an inconsistency where the **first vector Y position is on a reversed axis to the second vector Y position**. IE, vector1 is (Right,**UP**) vector2 is (Right,Down) which seems to be contrary to how rectangles are defined in the rest of the game - only other exception being trigger rectangles also are reversed on the Y axis for some reason. ?

Using a negative Y position works as needed, and so is possible to set the window so it's line-of-sight matches the sprite graphic.
`window="0,-48,48,320"`
![image](https://user-images.githubusercontent.com/55356135/114799810-80ea5d00-9d66-11eb-8448-7afd463c6df8.png)

**Comment by Regalis11** [comment]
This is actually intentional, we felt the doors look better without the shadow and LOS effect cast from the upper part.

I wouldn't say the Y axis is reversed: Y is up in the game's coordinate system (this doesn't apply to sprites, in the texture's coordinate space Y is down). And the second vector isn't a position, it's the size of the rectangle.
