### ISSUE TITLE
Exit a ship with the exit against an outside rock and player can go inside the rock and get stuck

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#552]

**Comment by rico6822** [comment]
I thin he means:
Sometimes you get teleported by kinetic force's shaking outside of your submarine inside a rock.

**Comment by BlueTheKing** [comment]
Nope. The "getting stuck in a rock" bug has been in bt for quite some time. 
It happens when you exit a shuttle while its pushed up a rock (most likely the top of the map), in which case the character is inside the rock and can't exit it, though it is sometimes possible to get back into the shuttle. 
Its easily avoidable as the only way you get stuck in it is if you exit the shuttle when its obviously pushed up near the rock, so just don't exit into the rock.

**Comment by rico6822** [comment]
At least thegrb93 could mention he means shuttle. By exit I though it is any hatch or door leading outside.

**Comment by thegrb93** [comment]
I've had this happen with any exit, including doors, or holes in the hull, not just the shuttle.

**Comment by NilanthAnimosus** [comment]
Amusingly it is also possible to exit a submarine and go through the wall of another submarine - ending up inside the submarine and passing through the wall. (I have seen 2-3 cases of this over time)
