### ISSUE TITLE
Motion detectors do not detect terrain moving towards sub

### ISSUE THREAD

**Issue by CodeHatchling** [Regalis11/Barotrauma#5622]
I have searched the issue tracker to check if the issue has already been reported.

While this may be more of a feature request than a bug, it felt somewhat unintuitive that a motion detector mounted on the exterior of the sub cannot be configured to detect non-human, non-monster objects that are moving relative to the sub.

I was trying to create an automatic collision avoidance system for my sub. When a motion detector on the front of the sub detects terrain (as I was expecting) it would send a signal to reverse the sub away from it.

**Steps To Reproduce**
- Place a motion detector that detects for motion on a region outside the sub.
- Pilot the sub near a terrain wall so that it overlaps with the region.
- Observe that the signal remains "0" when terrain is overlapping.

**Version**
v0.13.0.11 Windows

One possibility could be adding field for detecting terrain/other subs/outposts as a toggle, in addition to detecting humans and monsters.
Another possibility could be a separate item, a raycaster object, that shoots out a ray (or a thick beam) and the output signal is how far the beam travels before hitting something. Could also be neat to output the normal XY direction, and relative XY velocity.

To perhaps inspire motivation for this change, consider the possibilities for automation this could create: One could wire their sub to not only avoid collision, but automatically follow the surface of the ocean, dodge other subs or creatures attempting to ram you, and so on. Sensing systems like these are a pillar of control automation and would likely lead to all sorts of wild player-authored behaviours we can't yet imagine. At the very least, you wouldn't have to worry about the sub crashing into a wall if the helm is unattended.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/96b8f31cc3e355b0f2e828ee55415764c0c8bd17

**Comment by CodeHatchling** [comment]
Cool, good to see that we think alike! 
However, the link you provided takes me to a 404, unfortunately.

What aspect of this is implemented in this commit? I mentioned motion detectors detecting non-character objects, but also a raycast/beamcast device.

**Comment by Singularia** [comment]
Regarding [96b8f31](https://github.com/Regalis11/Barotrauma-development/commit/96b8f31cc3e355b0f2e828ee55415764c0c8bd17)
In Unstable 0.1400.1.0 motion detectors set to "Wall" detection mode can sense only indestructible level walls

Upon detection trigger laser should fire and one lamp near nav terminal should turn on
![image](https://user-images.githubusercontent.com/62324831/119816173-21bc6280-bf38-11eb-8e1a-acdc7c148f62.png)

Nothing happens if sensor overlaps destructible objects
![image](https://user-images.githubusercontent.com/62324831/119816108-094c4800-bf38-11eb-9a15-df8b43fccb28.png)

Also it sometimes detects submarine walls but VERY inconsistently
(Upon detection light near command on a top submarine should turn on and it does but it turned off second or two later despite use of a "lock" command, and it happened multiple times)
![image](https://user-images.githubusercontent.com/62324831/119816666-b4f59800-bf38-11eb-892c-49d113888589.png)

And it also detects monsters in "Wall" mode
![image](https://user-images.githubusercontent.com/62324831/119817229-714f5e00-bf39-11eb-82e9-3a7615244f2c.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/71606701ef6282be33155be7a0659dfe5285fa9e

**Comment by Lithosagym** [comment]
Tested, motion sensors set to "Wall" confirmed to no longer activate for monsters.

**Comment by Rokvach** [comment]
Closing
