### ISSUE TITLE
endworm 2shotted with emtpy common railgun shells

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5625]
- [yea ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you can just shoot 2 empty common shells at the first limb after the head of the endworm in the same spot and it decapitates it 75% of the times
(i'm assuming it's supposed to be harder to kill)

i suggest making the min damage for severance for that limb stupid high like 1200 so you can only sever that limb with a nuclear shell loaded with ic-4 or something like that, then start decreasing the min damage for severance every limb

**Version**
v0.1300.1.11

**Comment by Ek-Videogames** [comment]
Being based off of limb severance - a quality which is intrinsically part of RNG. You can also get times where you shoot up to 10 fully loaded C-4 shells into the same section of worm and only the outer armor breaks.
Instead of just making it impossible to sever limbs *(which seems in a way that would ruin the entire mechanical design of the fight to begin with)* I think it would be beneficial for larger creatures to have a kind of 'limb durability' so limbs are either guaranteed to break past a certain amount of damage sustained, or some other implementation to add this kind of damage consistency in the places that it is needed - such as endworm and moloch.

**Comment by itchyOwl** [comment]
Just shot the endworm (ai disabled, so I hit every time). It took me something like 15 shots to cut it here:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/9fb299ae-b3aa-43b7-acd3-486576a5b067)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/53766c67-f945-4c2e-b69f-0fa25aa09e31)

The probability for severing it there is 7.5% per shot, not 75%. It's defined in the xml as 0.05 (5%), but for railgun shells there's a multiplier of 1.5x. The probability for severing armor pieces with a railgun hit is much higher.

So, it's certaily possible to kill it with two hits (not one) by hitting the same spot twice. But that's just a 7.5% chance per shot. And given that the enemy moves a lot, it's not easy to do that. So it's much easier to kill it by shooting at some other part, as intended.

While I agree that the system could be revised (which is a much bigger task), I don't see any issue here. I don't agree on increasing the min damage for severing.
