### ISSUE TITLE
Issues with traitor mission

### ISSUE THREAD

**Issue by Padex98** [Regalis11/Barotrauma#5641]
- [///] I have searched the issue tracker to check if the issue has already been reported.

**Description**
as a traitor, class mechanic, I couldn't complete the (sabotage large engine to 10% or lower) mission. despite the bar reaching 0, it didn't count. not only that, but for some reason I couldn't remove the wired from any electronic circuit

**Steps To Reproduce**
pretty straight forward, try to sabotage the engine as a mechanic with that traitor mission, or try to remove wire connections.

**Version**
Windows- latest version as of now. 0.13. 0.11. if I'm not mistaken

**Additional information**

**Comment by JeffreyLo-dev** [comment]
What I have found is that it can come down to two things, either there are multiple engines in the sub (e.g. main and aux engine etc) or/and the sub comes with drone with an engine in it. So, as a result, you have to sabotage multiple engines (both main sub and drone) in order to complete the task.  You can probably recreate it with the Remora since it comes with a drone ( still not completing the task when sabotaging the main sub's engines but succeeding when you sabotage the drone's engine as well).

There was a previous ticket by #4047 relating to the numerous issues relating to various traitor missions and it was mentioned that traitor missions will be reworked later this year, so I'm guessing this issue will be eventually reworked as well (i.e. possibly not including the drone's engine to be sabotaged as well).

**Comment by Sfreck** [comment]
What I have found is that it can come down to two things, either there are multiple engines in the sub (e.g. main and aux engine etc) or/and the sub comes with drone with an engine in it. So, as a result, you have to sabotage multiple engines (both main sub and drone) in order to complete the task. You can probably recreate it with the Remora since it comes with a drone ( still not completing the task when sabotaging the main sub's engines but succeeding when you sabotage the drone's engine as well).

There was a previous ticket by #4047 relating to the numerous issues relating to various traitor missions and it was mentioned that traitor missions will be reworked later this year, so I'm guessing this issue will be eventually reworked as well (i.e. possibly not including the drone's engine to be sabotaged as well).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/471c1bf46c14f826cfc8e8dc20a0752b529f8d47

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
