### ISSUE TITLE
Cant continue finished campaign until the credits have finished server-side

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5643]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Campaign was finished and we automatically got into the lobby.
From there we couldnt continue the campaign on restarted map.
Pressing continue got stuck on "starting..something" and dropped back to the lobby screen
Also quit&save and reload the campaign did not allow us to continue on the refreshed map.
Only workaround: Stop the server, restart, reload the campaign finally allowed us to start the next run.

Expected: continue allows to continue with the save without having to restart the server.

**Version**
13.3.11, MP, client hosted, EK armory/utilities, Beacons extended, wrecks extended

**Comment by Rokvach** [comment]
This happens because you need to wait for the credits to end, even though everyone has skipped the credits. I wouldn't consider this a bug as its more of a missing feature as the players shouldn't be forced to wait for the credits to end if there isn't any players watching the credits in the first place

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/21409d99f2ce132d2eecf5449160621c859b882d

**Comment by JeroonBosch** [comment]
Tested, no more issues after the fix
