### ISSUE TITLE
Stuck at a natural formation, can't continue with campaign

### ISSUE THREAD

**Issue by FweeGamerHD** [Regalis11/Barotrauma#5662]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After trying to dock on a research facility (we also tried with numerous other routes but same result) nothing happens after we dock/select the next location on the map (depending if location was an outpost or a formation) It started on some Husked grounds from a mod, tho we already went thru some modded locations and this didn't happen. Now we're basically tied to the starting location, where we can select a different end point, but as stated before we can't rly continue after that.

**Steps To Reproduce**
I have no clue how to reproduce, I will attach the save file as stated from one of the friend people trying to come up with a solution in the discord. Maybe the file will lead you to the reason why it happened.

**Version**
0.13.3.11 Windows 

**Additional information**
We had the game modded as mentioned before. If necessary I can provide the full mod-list. 
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/6404711/Multiplayer.zip)

**Comment by Regalis11** [comment]
This seemed to happen because of the "XanMonsters Creature Pack" mod which includes some broken location type changes (namely, changing Husked Grounds into Explored a location, a location type that no longer exists).

I added an error check in https://github.com/Regalis11/Barotrauma-development/commit/5c356cf667cd38d28a72962dedf5030b5303d499 that should prevent this from crashing the game, but for now it should be possible to work around the issue by disabling XanMonsters or waiting for the creator of the mod to fix it.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
