### ISSUE TITLE
Misaligned selection boxes

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5669]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At least these 4 items have misaligned selection boxes, which makes editing harder than it should be by blocking the selection of close items:
- Junction Box

- Status Monitor

- Navigation Terminal

- Reactor (smaller)

**Steps To Reproduce**
n/a

**Version**
Any up to v0.13.3.11

**Additional information**
![Barotrauma_zldKgDsN5o](https://user-images.githubusercontent.com/10529134/116785985-c6b06080-aa9c-11eb-90f9-a73074f5c31a.png)

**Comment by Regalis11** [comment]
I couldn't reproduce the issue with the junction boxes or the reactor:
![image](https://user-images.githubusercontent.com/14351070/116864999-77d80780-ac11-11eb-9915-a818b0cdd78a.png)

The way the nav terminal's and status monitor's sprites are offset is intentional, relevant ticket: https://github.com/Regalis11/Barotrauma/issues/3195

**Comment by Krzeszny** [comment]
> I couldn't reproduce the issue with the junction boxes or the reactor:
> ![image](https://user-images.githubusercontent.com/14351070/116864999-77d80780-ac11-11eb-9915-a818b0cdd78a.png)
> 
> The way the nav terminal's and status monitor's sprites are offset is intentional, relevant ticket: #3195

It could be a problem with subs made before some particular update. For example, look at the boxes on the Humpback compared to newly-spawned ones:
![Barotrauma_HQgCfkHpH5](https://user-images.githubusercontent.com/10529134/117376921-683b1600-aed2-11eb-8b31-b3ada5078e8c.png)
