### ISSUE TITLE
Show respawn shuttle leaving timer (Not transport duration) for clients

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#567]
A simple feature suggestion, the respawn shuttle has 3 timers, yet only 2 of them show.

the first is the deploy timer, once the % dead is met it will countdown before launching the shuttle (OR spawning to the main sub, so the other two timers don't get used)

The second timer is the transport duration. this is where the shuttle is out and will count down until its out of time or has no living characters on board

The third phase, the recall/leaving phase has a third timer. often the shuttle is out of power, sinks or shot down yet will "Despawn" and teleport back to its position after the inverse of its transport duration times out or it reaches its start position.

since the shuttle is often immobilized and either gets stuck, shot down or other such - it would be nice if the third timer was displayed to clients based off the servers timer (Much like the others).

I even modify the value on my mod to allow for changing the third timers duration for the host.

**Comment by NilanthAnimosus** [comment]
I understand it is intended as a despawn timer, but when a server sets its transport duration to 6 minutes, and a timer of about 4 minutes to depart. and nobody can see where the respawn is and are wondering if/when respawn will come. the "despawn" timer would at least be more informative.

I already added timed warnings and such to my mod with the very intent to make it considerably more obvious to get out of that shuttle. along with customization on the server to make it remove itself instantly and modify the third timer so it doesn't take the transport duration to get back.

The shuttle can run out of power or sink, or have its autopilot fail horrendously (8/10 times I see BT Public's shuttle trapped under a rock, 6 minute transport duration sure is a long time to wait without a timer or idea of it).

I'm not even sure why the shuttle fails to reach its location at times, it will actually do things like rise above the main path and ram (and glue to) the ceiling when there is power left and drive max speed into a wall. which from spectator looks funny for the first minute or so.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
