### ISSUE TITLE
endworm 1shotted with nuke

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5703]
- [yea ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just splited an endworm in half with a single nuclear shell, the segments were not separated (i couldn't see the meat, i 100% hit armor), no previous shots, and died later because of the blood loss.

**Version**
v0.1300.3.11

**Additional Info**
Common vanilla nuclear shell for the common vanilla railgun, no payload, common vanilla endworm too.

**Comment by Ek-Videogames** [comment]
Optional killing condition based off of an entirely RNG dependent mechanic can do that.

To stop being able to 'crit' endworm with 1 shot decapitation the logic of how limbseverance works would need to be tweaked to be slightly less random and more a consistent threshold. To give one example; if monster limbs have to take a certain amount of total damage before they can be severed, IE a limb 'durability'.

**Comment by Krzeszny** [comment]
I don't understand why railgun shots cause bleeding – heat cauterizes wounds.

**Comment by itchyOwl** [comment]
@Krzeszny , I think you have a point there, but if an explosion tears a limb from the body, I bet the body and the limb will bleed. We could remove the bleeding damage from railgun shell hits, but the mechanics of Endworm require that it bleeds. It's actually different kind of bleeding that that caused by the railgun shells. I'm not sure, if we should change things for the sake of supposed realism here.

Haven't got to testing the nuke yet, but if a nuke _can_ severe the Endworm with one shot, that's as it's intended. Or so I believe. But the chances for that shouldn't be too high.

**Comment by itchyOwl** [comment]
Tried 10 times. Couldn't repro it. But I think it would be possible to hit between the scales, which could dissect the worm even with regular shells. ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/8eb40e37-de3a-4e08-ae95-68e2a424d5f4)

The explosion isn't strong enough to trigger the dismemberment. Or at least so it looked like in the debugger: all the hits of the explosion had lower damage than 100. Theoretically the explosion could sever the tail if it happened close enough to the center point of the limb, but I couldn't make that happen.

So, once again, I'd say there's nothing wrong here. If it would happen every time or even often, I'd consider it as an issue. I wonder how you encounter these things? Like how did you come up with that 75%? Maybe I've overlooked something. Just can't see what.

**Comment by Krzeszny** [comment]
> We could remove the bleeding damage from railgun shell hits, but the mechanics of Endworm require that it bleeds.
Currently railgun shells deal 150 lacerations and 100 bleeding. 
Since railgun shells are normally empty (solid steel), I think they should deal just blunt force trauma (but enough to make Railguns worth using – maybe 300 or more damage?). Not only bleeding doesn't make much sense, but being hit with a blunt object shouldn't cause lacerations unless it penetrates... but being penetrated with a railgun shell means instant death anyway.
If you put explosives inside, well, the explosives already have their own damage so that's fine.

The nuclear explosion makes perfect sense on the other hand: 300 burns, 100 radiation, 600 deep tissue injuries.

If a limb is severed, sure, but otherwise such an amount of bleeding from being hit with a solid steel projectile doesn't make much sense in my opinion.
