### ISSUE TITLE
Implement Job loadouts and varied inventories for the same job roles + traitor loadouts (Possibly job dependant too)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#573]
A simple concept I had in my head, essentially. Grant the ability to give jobs multiple loadouts, so on spawn the starting items can be more varied (This is more of a thing to be used my mods however)

It could be used in vanilla so hiring new crew has a chance for them to start with a few different items.

The mechanism in my head is simple, Allow for a list of items to be tied to a name, and multiple of these lists potentially can be used at once.

For instance:
-Give assistant items + one of these lists:
MechanicA - Blue jumpsuit, crowbar
MechanicB - Blue jumpsuit, welding tool with a tank

Engineer: 
-Give assistant items + one of these lists:
EngineerA - Orange jumpsuit, a fire extinguisher
EngineerB - Orange jumpsuit, one or two wires.

MedicA - Medic clothing, medical syringe with 1 corrigodone
MedicB - Medic clothing, medical syringe with 1 ethryosine
MedicC - Medic clothing, medical syringe with 2 bandages

I am terrible at naming, but then have say:
Assistant - which has screwdriver/wrench

An engineer and a mechanic will always have the items from list "Assistant", but then may have a choice between one of the lists.

A traitor could be given a traitor list (Be it job-specific or a random of 1-4 lists) of something simple they could use, but not to tip the balance too far of course (Like no starting with a direct poison, but perhaps a crowbar)

Additionally traitor items should not "Add" items a class already has (Such as again, a crowbar) or have an XML tag to prevent such.

Finally it would be nice if there could be differences applied to the items based on the team of the character, written inside the load out itself (specifically. item colour for renegade/coalition) but that is not too important.

Sadly vanilla barotrauma doesn't have too many items to think about when applying this, but the new framework could be used for content mods to grant varied different spawn clothing and to implement other features like #371

**Comment by ChikoEduardo** [comment]
Oh, I was about to make this same suggestion when I saw a piece of code used to randomize stuff in the RuinConfig.xml file.

I even tried to use it with the power of faith! T-T
https://cdn.discordapp.com/attachments/426913209602146315/544876980990902272/Image105.png

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
