### ISSUE TITLE
[V0.1400.0.0] Weird entity position error

### ISSUE THREAD

**Issue by WDebon** [Regalis11/Barotrauma#5748]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
-Video will explain itself hopefully

**Steps To Reproduce**
-Pirate mission

**Version**
V0.1400.0.0 Windows

https://user-images.githubusercontent.com/38989015/117838189-7bdad980-b250-11eb-83f0-b4c163d920e2.mp4

![image](https://user-images.githubusercontent.com/38989015/117838260-8eeda980-b250-11eb-924b-214b00cf1d94.png)

**Comment by Regalis11** [comment]
The yellow warnings are normal (as long as they're only occasional): they can happen when an item gets deleted and the item's ID gets taken up by a character immediately after (or vice versa).

The red error is a bug though, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/192c40ad0977d70e075a4728f9e755c39a9ef4b1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
