### ISSUE TITLE
Respawn shuttles delete you from existence if you linger in them.

### ISSUE THREAD

**Issue by Reed0506** [Regalis11/Barotrauma#5786]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In multilplayer, lingering inside of a respawn shuttle until it despawns will vaporize you as well, including all your items, and forcing you to wait out the round or endure reaper's tax.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
In a multiplayer campaign, die, respawn, and wait inside of the respawn shuttle until it despawns. For added effect, have the rest of the crew join you in the respawn shuttle along with all of their good gear.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows 10 patch v0.13.3.11

**Additional information**
I ded pls fix

**Comment by Regalis11** [comment]
This is not really a bug, it's intentional that the characters who haven't left the the shuttle before it despawns are killed. We've gotten feedback about this before and there's a chance we'll change the logic somehow, but I'll close this ticket since we generally only use the issue tracker for bug reports.
