### ISSUE TITLE
opening map at end of level opens to all clients

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5790]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
at end of a campaign level, the opening of the map applies to all clients
this is incredibly jarring if it's intended

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.1400 unstable window

**Additional information**

**Comment by CurePindal** [comment]
Afaik its intentional, so people clearly notice that theres no outpost and they have to select a new route.
Never saw anybody complain about it. Seems helpful to me.

**Comment by Regalis11** [comment]
Yep, this is intentional. Previous many new players were confused about how to proceed to the next level if there's no outpost to dock to, and we decided to make the map pop up automatically to make it more difficult to miss. I think if we added restrictions like only showing it to the captain or someone who's steering the sub, it would most likely make the end of the round more confusing again.
