### ISSUE TITLE
Harmonicas can still be played through diving suits

### ISSUE THREAD

**Issue by RagingFlames** [Regalis11/Barotrauma#5807]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Harmonicas can still be played even when your face is covered with a diving suit. Realistically speaking, there is no way you could put the harmonica into your mouth, and even if you could, you wouldn't be able to move it with your hands to play different notes due to the diving mask that goes around your head.

**Steps To Reproduce**
1. Put on a diving suit
2. Grab a harmonica
3. Play the harmonica

**Version**
Unstable build - windows 10

**Comment by LePiromano** [comment]
but it's funny

**Comment by mrjpjr** [comment]
This game is not based on realism. Neither does it aim to be.
Realistically speaking you should not be able to treat someone in a diving suit, nor would you be able to heal someone that quickly, or bring the sub back from total destruction with just welding fuel, a fuel rod, a wrench and a screwdriver .
Does that mean the game should change something because it is not realistic?
With that argument every game would need to change gameplay elements.
Changes in the game should be made with regard to what makes sense for that game.
I would dare say that, for this game, being able to play an instrument, in water, with your suit on, etc is a necessity as it adds so much to the mood of the game (imagine the last crew member playing their last song before running out of O2 in the flooded, ballast flora infected sub)

**Comment by Regalis11** [comment]
I have to agree with the last 2 comments: even though we try to maintain some degree of realism, this is such a tiny issue that I don't think it's worth it to fix.
