### ISSUE TITLE
Add a method for the server to sync banned/disallowed jobs to clients preferences list

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#582]
It would be nice if the server implemented a form of job banning / job white listing, but if such features were added it'd be nice if a client could be informed what jobs were unavailable on a server (and perhaps darkening the colour of the job to inform of this). just a simple list of disabled preferences from 0 - X to the client on join or lobby update.

This way a clients job order could be say:
captain
engineer
mechanic
medic
security
assistant.

But the server has disallowed captain and medic. so the client skips sending the "captain" preference and "medic" preference and doesn't let them choose it during the assign jobs (and makes their GUI colour a darker entry, without disabling the ability to order it or messing with the clients saved preferences).

If karma becomes a fleshed out saved feature, it could be implemented as part of that, or as part of a jobban/job whitelist feature. Though personally I don't think a client should see this effect from karma because its not saved (Quick rejoin resets it) Which simply helps to know when to bypass it for now.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
