### ISSUE TITLE
Selecting Shuttle as Campaign Vessel- Rebalancing

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#585]
Default shuttles does not have any manners of restoring energy. Batteries do not replenish their kW's and there are no items increasing it. We need an item doing it.

Having 3 crew members on the board is also little crowdy, exceptionally that a single engineer is already enough to fix broken navigation terminal inside. When using a shuttle tagged submarine I think engineer in single player mode should be the only starting crew member from the list.

Optional: That starting engineer will have it's head index and name chosen by the player.

**Comment by Regalis11** [comment]
That is why there's a warning when you try to select a shuttle as your campaign vessel - the vanilla shuttles are not meant to be usable by themselves, and can only be recharged by docking them to a submarine.

Also, all the submarines and shuttles will be remade for the Steam release. Instead of modifying the current shuttles for something they were not designed for I think we should include a small submarine in the set of vanilla subs.

**Comment by rico6822** [comment]
Can we at least start with solo engineer?

**Comment by Regalis11** [comment]
Being able to select the crew you start with is definitely a good idea. It could either be a submarine-specific setting set by the sub designers or something the player can choose when starting the campaign (or maybe both)? Not a very high priority feature to implement at the moment though - until it's implemented you could just "escort" the unneeded crew members out of the airlock and keep playing with the engineer.

**Comment by rico6822** [comment]
Good.
