### ISSUE TITLE
Is it intended for health scanners to only show calyx infections if it is above 50% of the way there?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#586]
Just a curiosity, but Dormant is 0% - <50%, Transition  is 50% - <100%, and active is 100%.

The health scanner code relies on Transition state to show if an infection is present. and it relies on Active state for the advanced calyx infection text.

Calyxanide only removes 20% / use, so by the time it shows it takes almost an entire bottle (or more) to remove, given response time to get around to actually carrying the medicine, crafting it or other such making that typically 100% because medical craft timers are so extremely long.

to me it seems almost unbalanced it cannot be detected sooner, given the near complete ineffectiveness of the drugs and the lack players mention they even got infected.

**Comment by Regalis11** [comment]
It is intentional, the idea was that players have a better chance of hiding the infection until they're starting to transition (if they wish to do so that is). I feel it also makes things more interesting for the doctors as they have to keep monitoring the crew after a husk attack instead of just doing a quick scan on everyone immediately after.

I do agree that calyxanide is unbalanced though, given how hard it is to make it should be way more effective.

**Comment by NilanthAnimosus** [comment]
Alright, its just the balance currently gets at me, there is never enough time nor resources to cure it once its actually available to spot given the size of crews, and one never wears a medical headset often because you cant radio through the thing which immediately gimps you in a multiplayer game.
