### ISSUE TITLE
Characters with similar combat strengths can't target eachother by default

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5865]
The way AI target priorities work right now is by defining different actions to take against enemies that are 'weaker' or 'stronger'
this works for most general cases where it is implemented this way, but where monsters with combat strengths similar to each other it does not seem to be able to satisfy either target priority, and so they will never attack each-other.

Originally I was concerned with this as a modding issue, as mods that add new monsters could increase the frequency of this issue if they have a similar combat strength stat to existing monsters. However after looking at tiger-thresher XML code seems this was a vanilla issue too already,
`    
    <target tag="mudraptor" state="Attack" priority="50" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" />`
    
This sort of hacky workaround of manually adding exception for species where combat-strength overlaps seems like unsustainable for development & modding.

**Comment by itchyOwl** [comment]
I agree that we could add the possibility to explicitly define the behavior against other creatures of equal strength. I'll add it right away.

However, it's entirely alright to explicitly define desired behaviors targeting at certain species. We use "human" and "leucocyte" targeting tags too. So the example here is not really "hacky", because we'll want to define a custom behavior for Mudraptors. Threshers on the other hand could attack just anything stronger, equal, or weaker. So replacing "mudraptor" with "equal" might be better.

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-development@243a2a1.

Testing:
- Try defining the combat strength of some monsters to the same value.
- Before the commit, all the monsters should just ignore each other. After the commit, they should do what you have defined them to do (using the "equal" targeting tag). See Tigerthresher.xml for an example.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
