### ISSUE TITLE
[Multiplayer] Multiple characters with the same name if you die whilst controlling a bot or creature and respawn

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5889]
Noticed in dev branch but should happen in any version

Repro steps:
1. Start a multiplayer mission (Not campaign but most likely will also happen in campaign)
2. Take control of a bot
3. Die as that bot
4. Notice that when you respawn there's now two characters named the same

I think you should be connected with your original character when you die whilst controlling another character rather than respawning, another way would be to kill the original character if you died whilst controlling another character and then respawning. 

The more you die whilst controlling different things the more clones there are
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/da0b03e7-e74d-48a9-9fdd-49fc34c20fc3)

**Comment by Regalis11** [comment]
I wouldn't consider that a bug. Your previous character is still around, so if you respawn as that character I'd expect there to be 2 instances of that character. Also idk if it's worth the trouble to fix these kinds of oddities that are caused by using console commands, if you're using console commands you could take control of the previous character manually or kill it if that's what you're expecting to happen.
