### ISSUE TITLE
Players are thrown from the server. / Игроков выкидывает с сервера.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#59]
На версии 0.6.1.4 я спокойно запускал сервер и все комфортно играли. После обновления игроков просто выбрасывает с сервера. Это не есть хорошо. / On version 0.6.1.4 I quietly started the server and everyone played comfortably. After updating the players simply throws it from the server. It is not good.
![image](https://user-images.githubusercontent.com/33912761/33517247-a199b242-d791-11e7-8ce2-2f3f2c7020cd.png)

**Comment by Crystalwarrior** [comment]
Это происходит только на кампании или в принципе?
Does this happen on campaign or overall?

**Comment by CryIz** [comment]
Это происходит на любом игровом режиме. / This happens on any game mode.

**Comment by NilanthAnimosus** [comment]
Last I recall a popular reason for this occuring was due to creatures that do not exist on the clients side being killed on the server side.

Respawned MonsterEvent creatures Use the same "Not net event" character create midround as it does during level gen, causing them to sync initially fine (Client also spawns the creature) - but not mid round (And if it dies or takes a form of event, it takes around 10~ seconds before all players are booted from the server due to desync).

Just find a respawning fish (Crawler) and kill the lastof it. teleport a new crawler (if 0-4 and 4 is killed, teleport the new 5) and kill that one. players should discconnect.
