### ISSUE TITLE
normal harpoon 1shots doors

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5909]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
shooting a harpoon at a normal door breaks it instantly

**Version**
Unstable v0.1400.3.0 Windows

**Comment by Tsunder** [comment]
door damage on weapons is quite wild

smg breaks door in 5 shots (1/3 a clip)

revolver also takes 5 shots (5/6 the rounds)

shotgun 1 shot with somehow 2? projectiles to spare? (less than 1/6)

grenade launcher 2 entire 40mm grenades (1 full ammo + 1 reload)

**Comment by Ek-Videogames** [comment]
How much damage the door takes is determined by the projectile's itemdamage parameter - except in the case of the 40mm grenade which has it's item damage defined under an explosion component.
- Even though a 40mm grenade does 500 damage, it is through an explosion and is therefore subject to door's 90% damage reduction from explosions. So it only does 50 damage.

A projectile damage reduction parameter ( #5380 ) would allow them to be more resistant to small-arms the same way they already are to explosions.

**Comment by Regalis11** [comment]
We decided to revert the ability for projectiles to damage doors (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/26dbd9f) for now because that'd require rebalancing item damage values and healths all across the board (and/or parameters for modifying item damage based where the damage is coming from). We'll get back to this when the next update is out.
