### ISSUE TITLE
Allow fabricators to output multiple items

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#591]
I know this is an odd one, given the style and design of the GUI has the item you are outputting as the list name, but it would be interesting if there could be secondary products to the same craft (Multiple of the same like crafting 4 bullets at a time, nested items being constructed such as loaded magazines, as well as different items 

This is a requested thing I've heard from modders, perhaps the fabrication system could just be redone somewhat someday to make this look like it fits GUI wise.

Perhaps the name and GUI image (and other such things, description and the likes) could be set via the XML, such as choosing an item prefab or image path, scale etc directly, while the description could be used to list what is outputted and a description of the craft.

An example (of my own) of what this could produce though is for instance, crafting a welding tool and part of the material output is a piece of metal not ready for further fabrication as a byproduct of the process, which could be in itself combined/reused and refined again into usable metal.

This is just different from deconstruction, as this is based in a fabricator, and not the deconstruction materials of the item.

**Comment by Momiro** [comment]
If you could 'link' a fabricator to a cabinet, like you can an oxygen generator to a vent. You could have the fabricator pull from the cabinet, and create complex items out of items that require others items that need to be crafted.. Just a semi related thought.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
