### ISSUE TITLE
Allow ranges of damage to attacks and later other XML elements such as status effects

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#593]
Not necessarilly a "random" in the sense of applying a random chance to apply a status effect etc, but allowing the ability of some variance to the games effects instead.

IE. (and I am not using game values here). Lets say a crawler deals 20 damage. instead this could be 10-30 damage. I ain't completely sure how to have this in the XML in good syntax (Not sure how well damage="10-30" would look when trying to parse etc on load, along with having to change attacks, as well as status effect and other game logic to support a range of values)

This perhaps could later be used as a method to add variation into status effects themselves, such as drugs not always reliably having the same effect, instead of just direct attacks, but implementing such a feature on attack code would be a nice start using simple min/max damage values (as well as stun. bleed etc)

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
