### ISSUE TITLE
Pirate sub spawn in abyss at the start of the round

### ISSUE THREAD

**Issue by the1eyedduck** [Regalis11/Barotrauma#5948]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Select pirate mission, start the round and enemy humpback will spawn in the abyss and start sinking

**Steps To Reproduce**
as above

**Version**
0.1400.2.0

**Additional information**
[Save.zip](https://github.com/Regalis11/Barotrauma/files/6576099/Save.zip)

**Comment by Regalis11** [comment]
On a closer look, it seems it didn't actually spawn in the abyss, but the level was deep enough that the non-upgraded pirate sub couldn't withstand the pressure even inside the level. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05ffda0e51d9fefa66d1350d848a5590867386e0 by setting the pirate sub's crush depth to be at least as deep as the player sub's.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
