### ISSUE TITLE
sub editor turret arc thing not level

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5952]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
360 != horizontal apparently
also the boxes jiggle?? who let them jiggle?

https://user-images.githubusercontent.com/5103517/120377319-fa281a00-c2ea-11eb-9899-a05235dd2c9d.mp4

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.2

**Additional information**

**Comment by Tsunder** [comment]
https://user-images.githubusercontent.com/5103517/120379328-96ebb700-c2ed-11eb-87c0-41a5d4ab256d.mp4

**Comment by 3e849f2e5c** [comment]
it's not precisely on level because of how the arc is drawn. The way the game draws a circle is it puts down points in a circle formation and connects them with lines. The amount of points is determined by the size of the arc because using too many points comes at a performance cost and smaller arcs don't require as many points but as a side effect sometimes the distance between points doesn't match up evenly with the radius of the arc causing it to be ever so slightly smaller or bigger than intended.
