### ISSUE TITLE
oddly placed coilgun on wreck dugong

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5954]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
weird spot for the top left coilgun in the wrecked version of the dugong

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
v0.1400.2.0

**Additional information**
![image](https://user-images.githubusercontent.com/55637865/120397548-e393ba00-c30e-11eb-94e6-462d08810644.png)

**Comment by Regalis11** [comment]
I'm not entirely sure I understood the issue correctly. Is the problem that the coilgun wasn't properly aligned with the sub's outer wall and was partially inside it? Fixed that one in https://github.com/Regalis11/Barotrauma-development/commit/5743ed43423159d0723c1948edd0c13c42a7aa1d

The dark part in the middle of the base isn't a bug, that's an intentional part of the sprite.

**Comment by LePiromano** [comment]
Yes the issue was it was partially inside the hull, it was low priority but it looked weird :)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
