### ISSUE TITLE
Wrecked Textures Are Out of Date

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5978]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Many wrecked textures were not updated in the art unification. This results in a jarring experience as wrecked items don't look like the modern game. This is by no means an exhaustive list, just the ones that I notice regularly:
![wikiimage](https://user-images.githubusercontent.com/37539527/120892767-c0ffea80-c607-11eb-98c1-0e008096e62d.png)
[Wrecked Textures.zip](https://github.com/Regalis11/Barotrauma/files/6602585/Wrecked.Textures.zip)

**Version**
0.13.3.11

**Comment by Regalis11** [comment]
This was actually an intentional decision, we felt having wrecked items look a little more "dated" than the current ones wasn't a big enough issue to justify the amount of work to redo all of them. We will most likely give them a quick pass at some point though, at least to increase their resolution to match the new items, but for now we'll be closing this ticket.
