### ISSUE TITLE
Selection rectangle misaligned for some items

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#5985]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some items have their selection rectangles misaligned that makes it hard to select these items sometimes.
Also periscope base doesn't have the same length as a standard periscope that make it a bit hard to plan where exactly normal periscope will be after swap.
![image](https://user-images.githubusercontent.com/62324831/120929351-7760ee00-c734-11eb-85d9-e0771943f486.png)

**Version**
Unstable 0.1400.3.0 but same things (excluding periscope base) can be observed on stable 0.13.3.11

**Additional information**
Same problem (excluding periscope base) can be observed on stable 0.13.3.11

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06ce4e99e30462cb14dbfbba5dc77d5c946c13fb. Setting the item's sprite origin back to center requires moving the devices in existing subs, which should happen automatically once we set the version number to the final one (subs saved in a version prior to v0.14.4.0 get automatically upgraded). Let's keep the ticket open until we know what the exact version number is and have verified the automatic upgrading works.

**Comment by Singularia** [comment]
Small update to this issue:
In update version 0.14.4.0 after the fix [06ce4e9](https://github.com/Regalis11/Barotrauma-development/commit/06ce4e99e30462cb14dbfbba5dc77d5c946c13fb) it appears that lights of status monitor and navigation terminal are now misaligned for items that were placed prior to fix and for newly placed ones too.
![image](https://user-images.githubusercontent.com/62324831/121773370-4286e800-cbc7-11eb-9f5d-8dda8c88c611.png)

**Comment by Regalis11** [comment]
Ready for testing

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
