### ISSUE TITLE
Option to specify if a broken door is closed or open for modding purposes

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#599]
A modder had the idea of having the EMP (Using say, a dummy powered component) effect certain doors in their mod, although EMP breaking a door would ultimately just break the door open.

The option for status effects to force doors shut (I don't know / don't think this is possible exactly), lock them up, or damage to doors to allow forcing them to stay closed (unable to open yet not letting you through) may be an interesting feature, though not sure how to go about handling it.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
