### ISSUE TITLE
Allow pressure protection to be variable by depth/pressure as a form of protection strength

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#600]
This is more for modding purposes, but for now any level of pressureprotection is a simple "protected yes/no" and all of them fail at -30000f Y coordinate depth instantly (even if the pressure internal to the submarine is minimal).

My current understanding of the current pressure protection value is it acts as a sort of timer, giving you a very small breathing room of exiting and re-entering a suit during maximum pressure without dying.

It'd be nice to specify an items maximum pressure protection (as a pressure numeric internal to the sub and/or depth with depth having a pressure going down)

IE. a diving wetsuit wouldn't handle anywhere near as much depth/pressure as a full diving suit, but would allow for faster movement and handle the interior sub pressure better before its too much.

It would be interesting if it acted as a form of multiplier on the maximum pressure so even in a lesser protective item you could get a pressure icon as a warning (Including as a submarine or player begins to head towards the abyss)

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
