### ISSUE TITLE
Levers' current state is not visible unlike switches'

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#6014]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unlike switches, it is not possible to see at a glance a lever's state. This is an issue because players with deactivated sound and deaf/hard of hearing players may not know that the lever state has changed.

**Steps To Reproduce**
1. Place a switch.
2. Place a lever.
3. Click to toggle the switch. Its light changes, indicating that its state has changed as well.
4. Click to toggle the lever. No visual change happens.

**Version**
Windows 0.13.3.11.

**Additional information**
Easily fixed by modifying the lever texture to have lever off/up and lever on/down sprites and adding the following component to the lever code:
`<DecorativeSprite texture="Path/To/lever_new.png" sourcerect="0,0,1,1" depth="0.1" origin="0.5,0.5">
  <IsActiveConditional targetitemcomponent="Controller" State="eq true" />
</DecorativeSprite>`

**Comment by Working-Joe** [comment]
In case it speeds up the process, I made some changes that would implement a fix for this

[lever.zip](https://github.com/Regalis11/Barotrauma/files/6758943/lever.zip)

The fix is only adding a decorativesprite with a conditional for the state:

![image](https://user-images.githubusercontent.com/50582661/124364969-5dd49880-dc45-11eb-8cfb-2345ad078416.png)

not perfect visually but it is a really nice feature

**Comment by Regalis11** [comment]
Thank you @Working-Joe! Implemented in https://github.com/Regalis11/Barotrauma-development/commit/a9a55e2c8c1c44438f4d6afaa5100276a31a7b86

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
