### ISSUE TITLE
Are there any likely consequences to spawning a MonsterEvent / ArtifactEvent or other event types server-side?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#604]
It is a curiosity I have as I was looking into the mission structure, and I am not the brightest at creating networked events.

But the client (as of currently) tries to create the level identically as the server does including monster events.

If there were events however created after the round had actually started, would their be any strict syncing issues with this or would this require networking as well the location and details of the monster events to clients?

I imagine at least the music could be effected.

**Comment by Regalis11** [comment]
I think creating extra events server-side shouldn't cause any side-effects as long as it's something that can be synced via NetEntityEvents. Monster and artifact events should not be a problem as the clients could get the data through EntitySpawner. The music will not work correctly client-side though, because the events are used to determine the type of track to play.

In the dev branch the events are completely server-side, so doing changes to the way the servers create events should be much easier once it's out.
