### ISSUE TITLE
[Bug(?)/Missing Feature] Pirate ship docked to yours disappear after loading to an outpost

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#6133]
Description as follows, after successfully cleaning up a pirate ship from it's personnel, and docking it to my ship to bring it with me to the next outpost, an upsetting thing happened, when after a loading screen, the docked pirate ship disappeared
Tested is multiplayer campaign
Game version 0.14.6.0

not sure if it's a bug or something that isn't implemented, but that would be very useful to dock ships and take them with you, so you can further use them for various purposes

**Comment by aeondez** [comment]
I can confirm this is happening. While I don't necessarily need the extra sub, it'd be nice to get a small salvage reward for going through the trouble of bringing it back intact.

**Comment by Neko-LoverDisc** [comment]
I also want to suggest adding a reward for bringing back the pirates alive and cuffed; it'd be nice if it was for a reason like "the criminal justice system". Combining it with this would be a good reason to not be as destructive while also using nonlethal stun weapons

**Comment by Regalis11** [comment]
This is intentional, we didn't want to allow taking pirate subs with you because it would cause a lot of balancing problems (and most likely a bunch of other issues that we haven't taken into account). Allowing this could be something to consider, but since this is more of a feature request than a bug report, I'll close the ticket.
