### ISSUE TITLE
Offer for sealed supply crates

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6135]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As far as i know and i've seen sealed supply crates don't spawn anymore, yet the outposts have a chance to have them as a requested good.
![image](https://user-images.githubusercontent.com/55637865/122691852-4f7b8b00-d208-11eb-8e7c-207027c5bb59.png)

**Version**
v0.1400.6.0

**Comment by aeondez** [comment]
Wrecks and/or pirate subs should definitely include these. It's also a missed opportunity for cargo missions to have some cargo occasionally be sealed supply crates, since they are so prone to theft by crew, especially when they are recycled and the goods resold to the outpost that was expecting those supplies.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d8fc4595b13fd80768597379992fdc6f9a0ca08

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
