### ISSUE TITLE
Camera can be focused on turrets by connecting a periscope to the "power_in" connection

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6152]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
periscope's position_out -> coilgun power_in works for some reason to offset the camera

**Steps To Reproduce**

**Version**
0.14.6

**Additional information**
example here: 2nd to right most turret, "worst coilgun, ElPiro's Bane"
https://steamcommunity.com/sharedfiles/filedetails/?id=2483236185&searchtext=turret+collection

periscope cursed position_out position camera offset power_in

**Comment by Working-Joe** [comment]
To clarify some things:

It's not the connection between `position_out`and `power_in` that makes the turret go kaput, that's done by the other components of the circuit. Essentially the `position_out` -> `power_in` connection makes the turret go into focus. This would normally not be possible with components inbetween the periscope and the turret. This is because the code that finds the turret to put into focus works by sending out a signal and putting all recipients in a list. However, this signal also stops at components. 

So essentially this isn't *really* a problem by itself. I think it's sort of nice since it's currently the only way to keep turrets in focus with components altering the signal between the periscope and the turret. Rewriting the code to work through components may affect a lot more systems and may be a lot less performant, and only allowing direct connections to the position in will make these type of circuits impossible. 

What is a problem though is that connecting systems this way negates all skill, since components (rightfully) control with the high skill parameters. \:) But that's a different issue. I think this should be fairly easy to fix by letting the periscope set the skill on the turret it puts in focus and not whatever entity sends the signal into the `position_in` of the turret.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2d7483057fb8b3978641cf061bb49469d2d4560

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
