### ISSUE TITLE
Editing Submarine in Campaign Mode, Before Embarking- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#620]
You can simply have your submarine enter editor mode, before starting a mission. In editor, you can change wiring of submarine and change location of items in it. In multiplayer only host can enter editor and edit, others can spectate.

**Comment by NilanthAnimosus** [comment]
Spectating the sub editor sounds Crazy, given camera and other such isn't synced...or if it should even be synced.

Couldn't tell if the person editing is actively easily either, Honestly not even sure how you'd go about a multiplayer-synced-submarine-editor. most submarine editor code I don't even think is in the dedicated server code so that'd probably take a lot more doing.

It is possible to open the sub editor in a multiplayer game as the host without disrupting the server or disconnecting the clients - but editing items won't sync to clients there are no methods for moving the positions of static items, the match would continue but perhaps desync completely (or at the very least moved containers would become unusable as they cant be selected because the positions wrong to clients).

I've already played with the above, it amused me greatly for all of 30 seconds. it would in theory sync once the submarine is saved though, but still a fairly bad idea.

**Comment by rico6822** [comment]
Editor does not give free items, only existing wiring structure and wires with already existing other items can be edited.
