### ISSUE TITLE
Bots don't fix airlock doors

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6221]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems like NPCs refuse to fix doors that lead to the outside

**Version**
v0.1400.6.0

**Comment by itchyOwl** [comment]
The bots are generally not allowed to target items that are outside the hulls, and some hatches and airlock doors are technically outside. So that's why they refused.

I added and exception for doors in Regalis11/Barotrauma-development@b8a0e4e, which should fix it. Works only when ordered, not autonomously.

**Comment by LePiromano** [comment]
seems to be working in 0.1400.7.0

**Comment by Rokvach** [comment]
Closing
