### ISSUE TITLE
Levers send no output if both "Can be picked" and "toggle" are set to false

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6225]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a lever is placed with  "Can be picked" and "toggle" set to false, it will not output a signal when used. The expected interaction is that when the lever is used it will still output a 1 each time.

**Steps To Reproduce**
Hook up a lever with "Can be picked" and "toggle" set to false to a terminal. There will be no sound when the lever is pressed in game, and the terminal will receive no signal.

**Version**
v0.14.6.0

**Comment by Regalis11** [comment]
This is not really a bug: "picking" in the case of Controller components means pushing the button or pulling the lever, and if it's set to false, interacting with it will do nothing. If you want to prevent deattaching the item, you should set "can be picked" to false on the Holdable component instead of the Controller.
