### ISSUE TITLE
Crash to desktop in subbuilder in specific conditions, only on my sub

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#6249]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In my sub there are second reactor, which sole purpose is to start fires on the specific condition. For that I made it invulnerable and put fuel rod with same setting in it. However, if I turn it on inside supbuilder and try to test my sub, game CTDs. I tried to connect it to the grid and remove its logic, but game still CTDs. However game works fine if that reactor isnt turned on in subbuilder, or when it was turned on during gameplay.

**Steps To Reproduce**
In my sub, turn small reactor "On" inside subbuilder and start test drive

**Version**
[0.14.6.0], vanilla, no mods active during that event, only sub assembles and subs

Crash report, cant send sub here for some reason. I can add workshop link however. https://steamcommunity.com/sharedfiles/filedetails/?id=2537878261
[crashreport (21).log](https://github.com/Regalis11/Barotrauma/files/6763978/crashreport.21.log)

**Comment by Regalis11** [comment]
Thank you for the report! This seems to happen as a result of the maximum power output of the reactor being set to 0, which messes up the reactor's optimal turbine output calculations and leads to this crash.

Fixed the issue in https://github.com/Regalis11/Barotrauma-development/commit/5980fe90b9ba78f6492c146c20cb92cb0a1981a9 (link to our private repo). Until the fix is publicly available, you should be able to work around the issue by setting the maximum power output to something like 1.

Sorry for the inconvenience!

**Comment by Stallfighter** [comment]
Yes it works now, probably it wasnt surfaced until now because people keep their "logical" (for grid load) reactors off anyway.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
