### ISSUE TITLE
Allow projectiles and repair tools the option to hit multiple

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#626]
There is a common issue where say, there is a group of fish (you kill a crawler, theres 3 more) and they can all swim to eat the body, a railgun shell can wind up hitting the body on each shot yet the projectile continues at full speed.

Since melee can hit multiple targets and keeps tracking which targets it has hit thus far, perhaps railgun ammunition could do this as well by default?

I don't think hitscan weaponry should do this, though it could as well.

Finally repair tools have a habit of hitting 1 full health wall while having broken inaccessible ones behind it due to the submarine editor, making the effect of hitting multiple an XML option for these could be nice as well.

Additionally perhaps cap the max targets something can hit (for melee, projectiles and repair tools).

The idea of hitting 6-7 players with 2 stun batons using 30s stuns from fulgurium (thus 60s) could be a bit much for a singular swing if people are bunched together. I think 2-3 max targets should suffice for getting past a ceiling.

**Comment by Momiro** [comment]
I've been trying to design subs that are both easy to repair, and keep griefers out of key areas, and a lot of the reasoning behind some of the placement has to do with this issue, and it can mean I have to rework chunks of a ship because players can't repair some sections.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
