### ISSUE TITLE
Missing Shuttles in Campaign Can Be Bought For Credits- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#629]
It's gonna be as expensive as shuttle's quality or any other in fact submarine docking to current one. Non-shuttle submarines can also be bought back. Having submarines classified as non-shuttle does not increase it's cost. If we had to remove shuttle tag from The Nibbler the cost will still be 5000 credits.

Let's just say, that The Nibbler has perfect price of 5000 credits for having a new one to purchase, after losing it on a mission and The Blind Carp has 5239 credits or something like that.

The Nibbler's content is considered to be an index of 5000 credits for replacing shuttles back. 

In case of having more missing submarines at once (same thing comes with only one missing), there can be selected one or more of them under new special store's category "Missing Submarines".

Submarines having docking ports, but no submarines docking to them by default are gonna have "Missing Submarines" store useless. Submarines like this can have this store completely invisible in store's screen upon not detecting by the game any bonus submarines.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
