### ISSUE TITLE
Allowing Regular Multiplayer Users to See if A Console Command Occured- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#631]
Simply any user can see, what console commands were used on the chat, so they can know, if admin is potentially trolling.

**Comment by NilanthAnimosus** [comment]
If a host is not trolling, but using these commands to make the server more interesting or silently help out griefed players - such as acting as a dungeon master, I did this all the time on my own server and was considered a great host and a fun place to play.

Having this optional makes it pointless, while having it none optional can easily make it annoying and remove types of hosting and gameplay.

Instead, if you really want such a thing perhaps a server could advertise that it has cheats enabled or not which restricts the command usage, I believe dev has a cheats variable or system so that could be a feature of dev for the server list (?).

If a host is bad, generally I think it is up to the player not to play there more than the code to restrict in any sense his actions or make them visible in a spammy form. as a host who doesn't go about blowing players up, spawning items for himself or spamming creatures (and other actions) in the attempt to make all games fail - I would find this an extremely annoying feature that'd be one of the first things I rip out of my mod probably for the above reasons.

**Comment by Regalis11** [comment]
Seconding Nilanth. Even if we did implement this, the admins who want to troll could just download or make a server mod that disables the feature.
