### ISSUE TITLE
Autoban Users With Low Karma- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#632]
Server admin can select from 0 to 0.5 karma level at which user is banned immediately. They can select length of ban from 0 to 1440 hours (60 days) or give permanent ban.

They can also select value of karma which user will have set to, after unban from 0.6 to 1. 

Users will be informed by server automatically about this feature being here once they enter it. They will also be informed about being banned for that reason.

**Comment by BlueTheKing** [comment]
Seeing how the current karma system is pretty flawed having an autoban feature would just make it worse, in its current state atleast.
IMO the whole point of the karma system is to punish people without denying them access to the server (banning/kicking) so they have to deal with the consequences themselves, by blocking certain important jobs you make it harder for them to keep breaking the rules. 
This just adds another hassle to deal with.

**Comment by rico6822** [comment]
I think karma should be stricter towards them and maybe a bit jerk (since they are jerks themselves). Even if it blocks certain jobs available every job has it's own way to destroy entire crew here is the list:

Engineer; Mechanic; Assistant- Unwiring all Junction boxes or overloading reactor.

Medical Doctor- Venolaceps Calyx Eggs, sufforin or other medicals.

Security Officer; Captain- Will cooperate to stun rest of the crew and murder them, eventually killing each other once they get rid of them.

Also minimum amount of time of ban is quite liberal, since it's 1 hour and in fact lowest penalty player can receive is 0 hours (they will be removed from server, but can return immediately).

**Comment by NilanthAnimosus** [comment]
Honestly this is a terrible idea, the karma is not fleshed out enough to even be turned in in my opinion, let alone be performing bans.

This should never be implemented until its even a potentially reliable system, I've read a lot of the karma code, it is by very definition bare bones. It doesn't care if its self defense either, you can be banned for attacking a player who attacks you by this logic. there are very few ways to actually regain karma and it is very easy to lose.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
