### ISSUE TITLE
All Users See Their Karma Level and of The Others- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#633]
Users can see their and others karma level.

**Comment by thegrb93** [comment]
Karma should definitely be optional. I personally enjoy the challenge imposed by 'traitors'

**Comment by rico6822** [comment]
Traitors are quite overpowered due to them being undetectable, unless they have to kill.

**Comment by NilanthAnimosus** [comment]
Right now, if a VPN user sees their karma level, they will simply rejoin to reset it, along with any other player.

Even once saving is added, this serves to (right now) just add benefits for VPN users to be reminded to rejoin. I wouldn't mind seeing this though myself as a feature though despite mentioning these points I think its a nice touch if karma is fleshed out more.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
