### ISSUE TITLE
Maximum Karma Level for A Job- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#634]
No vanilla job is gonna have it, but players with too high karma level according to this request cannot become certain job, if their karma is too high. This feature is gonna be used only in modding.

Example:
BTE prisoner job serving as punishment to players with less, than (let's say) 0.7 karma. At least there is a risk they will become one of them.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
