### ISSUE TITLE
(Animated) particle sprites render at 0.5 regardless of the specified depth. 

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6344]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Setting the depth of a Sprite for the particle. This seems unintended to me as the code for Sprites and Particles does seem to take the sprite depth into account.

**Steps To Reproduce**
The attached mod includes the particle prefab named "DepthTestParticle" which in the XML specifies the depth in the sprite using 
```xml 
<!-- particle XML left out -->
<sprite
    depth="0.75"
    texture="Content/Particles/ParticleAtlas.png"
    sourcerect="384,254,128,128" />
```
The mod also contains an item which emits the particle named "emitter" he object has the sprite depth specified as 0.85 in the XML. 

Lastly, an assembly is included named "emitterAssembly" which can be placed to easily see the depth of the particle. As can be seen, the particle renders at 0.5 depth and not at the depth of 0.75 as is specified (which would be one bar higher than the vent itself).

![image](https://user-images.githubusercontent.com/50582661/126342962-d18cc5e1-546c-42ea-9623-97d864101553.png)

**Version**
v0.14.6.0

**Additional Information**
Emitter mod and assembly:
[DepthTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6849121/DepthTestMod.zip)

**Comment by Regalis11** [comment]
This is a limitation of the particle rendering logic: they're rendered in one pass between the "background entities" and "foreground entities" (i.e. at depth 0.5), which simplifies the rendering logic and reduces the need for sorting the sprites by depth (improving performance) quite a bit.

It would be non-trivial to address this and it wouldn't make much difference in the vanilla game, so I'm not sure if it's worth the trouble to fix, but maybe at some point. I'll close the ticket though since I'd consider this more of a feature request than a bug report.
