### ISSUE TITLE
[Modding] Setting a PropertyValue of type string to a string that can be parsed as a different type causes a crash

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6376]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If an item is created that uses a StatusEffect to set the PropertyValue of an ItemComponent will cause a crash if the PropertyValue is of type string but the provided value can be parsed as a different type, such as an integer or a string.

**Steps To Reproduce**
Create an item that sets a string value to an integer, for instance a component with the following XML: 
```xml
<Item name="test component 1" identifier="testcomponent" category="Electrical" Tags="smallitem,logic" scale="0.5">
    <Sprite texture="Content/Items/Electricity/signalcomp.png" depth="0.8" sourcerect="128,36,31,25" origin="0.5,0.5" />
    <MemoryComponent canbeselected="true" >
        <StatusEffect type="Always" targettype="This" Value="20.0"/>			
    </MemoryComponent>
</Item>
``` 
Having this item on a sub will cause the game to crash. However, if a string value is entered, such as 
```xml
<Item name="test component 2" identifier="testcomponent" category="Electrical" Tags="smallitem,logic" scale="0.5">
    <Sprite texture="Content/Items/Electricity/signalcomp.png" depth="0.8" sourcerect="128,36,31,25" origin="0.5,0.5" />
    <MemoryComponent canbeselected="true" >
        <StatusEffect type="Always" targettype="This" Value="Not 20.0"/>			
    </MemoryComponent>
</Item>
``` 
There will be no crash.

**Version**
unstable v0.1400.7.0

**Comment by itchyOwl** [comment]
Fixed the crash in Regalis11/Barotrauma-development@d94690c (dev because it can break many things).

Instead of crashing, it now throw errors.

Optimally the value would always be parsed to string when the property is string, but we don't have access to the property types when we parse the data for the status effects. One way to do it might be to introduce an extra boolean in status effects to tell the game not to not try converting the value to float or an integer. But that's a bit messy, so I left it unimplemented for now.

**Comment by Rokvach** [comment]
Tested, wasn't able to cause the game to crash, instead got a error about it. Working correctly, closing.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e9c99003-f148-40aa-b98a-cabfff1a077f)
