### ISSUE TITLE
Traitors Can Have Edited Minimum and Maximum Amount of Players if They Have To Spawn- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#638]
There must be always at least 2 players for traitors to occur, regardless settings. Admin can set minimum players for traitors to be (example) 4 in order to have them on submarine and maximum can be set to (example, as it can still be higher) 9. Past 9 players traitors will never show up (when set to 9 maximum traitors).

These values are set the same way as recommended crew experience in submarine editor.

**Comment by Momiro** [comment]
Please, this would make having traitors viable on many servers again, since they would be reasonably outnumbered.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
