### ISSUE TITLE
Characters reset after nuclear meltdown & returning to lobby.

### ISSUE THREAD

**Issue by ParadoxSong** [Regalis11/Barotrauma#6387]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ballast flora infection leads to use nuke meltdowning the ship to stop it, this turns out to do jack shit to the ballast flora, so we return to lobby and reload only to find that our characters have been reset, except for one of us. This is on the Unstable patch. The player in question had an inventory that suggests a save was made by the game after the nuclear meltdown.

**Steps To Reproduce**
Have a nuclear meltdown on your ship, return to server lobby, return to game. The players with fucked up inventories died during the meltdown. 
**Version**
v0.1400.7.0, Revision Number 7644391e74.  Windows 10 for all three players.
**Additional information**
We were docked with a station at the time. On the off chance every individual operation here was intended, consider modifying save procedures; we only ever experimented with a meltdown because we knew we could reload. Plus, the plastiseal cost we'd incurred experimenting by that point was huge, we'd gone through five stacks and actually lost ground to the ballast flora.

**Comment by Regalis11** [comment]
This is actually somewhat intentional, although not that well thought out on our part: when you end the round in an outpost level, the game is automatically saved. The intention was to make it possible to for example buy supplies, unlock missions and such, end the round, and continue later without having to do everything all over again. Ofc, this causes problems if you _don't_ want to continue from the same situation, like in your case.

We added an option to choose whether to save when quitting now, ticket in our private repo: https://github.com/regalis11/barotrauma-development/issues/2766

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
