### ISSUE TITLE
Make ID cards display their access levels in description

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#64]
I realise this might need to refactor some networking stuff, but I think it'd be amazing if you could adjust item names and descriptions on the fly.
"Captain's ID card", desc: "Allows ENG, MED, COM access"
This would also allow for things like server hosts editing ID cards server-side to instead act as something completely different, example:
Using the ID card prefab, rename it to "Nuclear Codes" for the Traitor Exchange gamemode or something.

**Comment by NilanthAnimosus** [comment]
Instead of writing a new issue for the same feature request, it would be nice if the ID Card was in the format style where:
- The name of the original owner and the Name of the job is on the ID Cards name.
- Possibly include it's access tags in its Tooltip description but for some subs this could be very long and perhaps unnecessary
- Have the name of the character overridden by the ID Card if they are wearing items that cover the face (A tag perhaps in the XMLs for facial coverage?) such as Unknown (ID Name).
- Later one could add a headset-like voice changer to mask the voice in the text chat which works with this concept, I think this would better expand on improving the ID Card itself. This is sort of how SS13 handles things and would work here too for in-game impersonation purposes.

**Comment by Crystalwarrior** [comment]
Mostly solved in https://github.com/Regalis11/Barotrauma/pull/160 as exposing the item Description variable to the sub editor allows sub creators to list the card's access levels and other fancy things.
