### ISSUE TITLE
Make A Monster in The Title Screen An Enemy- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#641]
The monster we see in main menu occurs only there and nowhere else. It's kinda sad. That monster is by now only for display.

**Comment by Weebyxanide** [comment]
Personally I'm fine with its absence in-game; we already have three fish-style hostile critters — charybdis, tiger thresher, coelanth. Adding a fourth wouldn't do much for the game since they're three different types of threat. If any more creatures are added, I'd much prefer more neutrals. Europa is a completely alien environment, but that doesn't mean everything is hostile.

Or we could just leave that giant lionfish on the menu as simply ornamental to add mystery. Or even make it one of the background fish.

**Comment by rico6822** [comment]
Remember, that this thing does not have to be an enemy always. It may attack only in self defense, like Watcher.

**Comment by NilanthAnimosus** [comment]
The fish on the title screen is rather close to a crawler really, It would be interesting to have new types of fish just to increase the variation of what could be encountered though.

**Comment by Regalis11** [comment]
Nah, we've got more interesting monster coming up than the lionfish thing in the title screen. :) The main menu is most likely going to be redesigned anyway, so I think this can be closed.
