### ISSUE TITLE
Make Sprint Animations of Characters Less Goofy- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#642]
One of my family members have complained sprint in this game to be "psychotic" due to it's too athletic swinging.

In multiplayer players would possibly grief less, due to less awkward atmosphere generated by new sprint animations.

**Comment by NilanthAnimosus** [comment]
I don't think more realistic animations would cause anyone to grief less, simply because people innately grief as that's what people just do - people are typically awful when given anonymity, regardless of the context when it comes to games.

I like the goofy animations myself, it does give the game a sort of character to it, but I wouldn't mind if they were improved to have less of an arm swing.
