### ISSUE TITLE
some bugs with Chinese, please understand.

### ISSUE THREAD

**Issue by HawkingHan** [Regalis11/Barotrauma#6436]
汇报一些bug：
-机器人存档后卡没（可能与任务中退出，起点/终点为自然聚落站点有关）
-机器人自己憋死（穿着潜水服没氧气不知道脱，没有氧气瓶不知道从旁边柜子拿。以上情况几乎都发生在没进水时，例如火灾缺氧、潜艇对接后）
-开任务、进服务器报错（可能与下载缓慢导致超时有关）
-给玩家服务器权限可能损害服务器存档（频繁尝试进入服务器导致AI消失）

**Comment by Regalis11** [comment]
Hello and thank you for the report! Unfortunately no-one in the development team speaks Chinese, so I had to rely on Google Translate.

The 2nd issue (suffocating bots) should be fixed in the next patch. I'm afraid the other 3 are hard to do anything about without more info. We would need the error messages or steps to reproduce to be able to diagnose them.
