### ISSUE TITLE
Correctly placed hulls do not flow water through when damaged (heavy wall)

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#648]
Here is an example http://prntscr.com/khmxq9
And here is the ship file. https://www.dropbox.com/s/5zs8oyytrie04f1/SS%20Sentinelx.sub?dl=0
If i'm placing the hulls incorrectly, I'm very embarrased, but I've made a few ships before, and I thought the hull mechanic behaved this way.

**Comment by Regalis11** [comment]
The problem seems to be the walls, not the hulls. The game determines the orientation of gaps (= whether they're vertical or horizontal) based on their shape, and gaps placed on those narrow but tall wall sections are interpreted as horizontal gaps. This is something that obviously has to be fixed (it would make much more sense for horizontal walls to always have vertical gaps), but for now you may be able to work around it by not making the walls out of multiple tiny wall sections. Speaking of which, why are you doing the walls that way?

**Comment by Momiro** [comment]
I see, the reason I chose walls like that was to make it durable, difficult for someone to grief (multiple panels to be able to squeeze through instead of a few key blocks) and provide adequate crew separation.
For now, since the ships core design has a lot to do with the large walls, I'll wait on finishing it.

**Comment by Momiro** [comment]
I still use side walls for roof pieces and vice versa, I think the flow should be be determined by the hull pieces placed on top of it, instead of the width of the wall pieces
