### ISSUE TITLE
[unstable] status monitor hulls

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6493]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Status monitor displays incorrect order/condition of linked hulls.
The name and information (water level) of the hull in status monitor isn't for the correct hull

**Steps To Reproduce**
1. linked hulls
2. fill one hull with water
3. check status monitor

**Version**
0.15.0000

**Additional information**
In this example, there is a breach in the bottom hull, but the upper hull is the one showing a water level.
Additionally, both hulls are displaying as breached, but only the bottom hull is breached.
The names in the status monitor are of the other hull's name (i.e., monitor displays bottom hull as Top Hull's name)
![image](https://user-images.githubusercontent.com/5103517/130999297-3e6fe0c7-6966-4323-93c3-7f5050a384c2.png)

**Comment by 3e849f2e5c** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/6699604b5e7e52e3c77236123b5a01ceb423ec9c

Issue was that in linked hulls the areas on the HUD weren't being mapped to the correct hulls causing the mapping to be completely random and in the provided screenshot for example the bottom hull and top hull are swapped so the top hull is showing bottom hulls water level and name.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
