### ISSUE TITLE
Can't add mission in campaign mode with linux dedicated server

### ISSUE THREAD

**Issue by moechofe** [Regalis11/Barotrauma#6539]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When creating a campaign on linux, there is no way to indiquates:
- the maximum number of missions per round,
- enable/disable the radiation,
- set casual/serious/... game style.

**Steps To Reproduce**
1. Setup a linux dedicated server using https://linuxgsm.com/
2. Open the server console: `./btserver console`
3. Start a campaign: `gamemode 3` then `Y` and type a name, wait.
4. Launch the game (steam), join the server, start the round.
5. Select destination, mission counter is `0/0` 🔴.

**Version**
Server build: `7246116` (debian 10)
Client version: `0.14.9.0` (windows 10)

**Comment by Regalis11** [comment]
These settings should be adjustable by modifying serversettings.xml in the game folder or in the server lobby by giving a client the permission to modify the settings (e.g. with the console command `giverank` or `giveperm`).

However, the maximum mission count setting was broken, and couldn't be adjusted in the settings xml. That should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddf114e3abc1c5862d1a6bc2c6dc45ef02bbbf53

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
