### ISSUE TITLE
[Unstable] Dying with Spineling/Mudraptor genes equipped will turn your corpse into a Husk

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6554]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you die with mudraptor/spineling genes equipped you turn into a husk

**Steps To Reproduce**
Equip Gene splicer with Spineling genes
Die
Turn into husk

v0.1500.1.0

**Comment by Emanthealmighty** [comment]
I would suggest to add a new variable to husk infections to disable the transformation on death altogether, so that there's no need to do some hacky things with the husked species.

It would go along well with the newly added husk infection parameters (dormantthreshold, activethreshold, transitionthreshold).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ef34371d4edadd2a05b159c63a4154d6def1e7f

**Comment by Emanthealmighty** [comment]
Working properly as of v0.1500.2.0 (Unstable).
When using mudraptor / spineling genes on yourself and then dying, your character won't reanimate as a husk.

**Comment by Rokvach** [comment]
Closing
