### ISSUE TITLE
Taking a genetic material out of the gene splicer deletes the material

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6576]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I don't know if this is intended, and if it is, this is a suggestion to change that.
the progression system that the genetic material has (finding, praying to rng, refining, etc.) is not as enjoyable if you can't use the genes as you upgrade them :)

**Version**
windows 0.15.1.0 unstable

**Comment by Regalis11** [comment]
This is intentional: we don't want the genetic materials to be something you can swap at will, but something you'd be hesitant to use. They have powerful effects, and using one comes with a cost (= not being able to refine that material further or to "deactivate" it without destroying the material).
