### ISSUE TITLE
Allow to use wiring menu, while climbing a ladder.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#659]
Currently you automatically fall down if you try to interact with anything using a screwdriver, which makes it harder to conduct repairs on vertical hatches or shuttles and so on.

**Comment by rico6822** [comment]
Exceptionally, while rewiring docking port. I think docking port's picking range can be slightly increased to make it more rewireable.

**Comment by NilanthAnimosus** [comment]
I find myself often unable to even select docking ports while trying to rewire - even when I'm sitting above, climbed high or swam out the airlock to attempt it.

It would still be nice though if there could be a method to have multiple selected constructions for rewiring+climbing or such.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
