### ISSUE TITLE
Implement favourite, history and blacklists (Server hiding) for the server list

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#666]
I think it would be nice if a server could remember (in order of joined) a list of IP's you have played on (and if their running), with it able to state if it is down / up (and its last name or newest name if it is up)

Additionally the ability to add to a favourites system which could keep the server at the top of the list perhaps.

Finally the blacklist would be to stop servers showing on the main list, those which may be changing name but the IP remains consistent, Such as servers that use a lot of admin commands and mess with players at will in a bad way or have terrible admins.

As a note, these are all features of steam server list, but I don't know if these are implemented in dev and if they apply to the none-steam server list GUI

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
