### ISSUE TITLE
Multiple Alien Ruin Artifact Missions Selected Spawns Two Ruins Clipping Into Each Other

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#6708]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the player has multiple alien artifact missions involving ruins selected (or possibly just at the same destinaton) , the game spawns two sets of alien ruins, causing a huge mishmash of alien walls and possibly making the artifact unobtainable. 

**Steps To Reproduce**
Add a bunch of alien artifact missions, ruins type. If it works you should have two ruins overlapping.

**Version**
Stable, Windows Steam

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report!

I don't think this is actually caused by the missions, because the number of artifact missions doesn't affect the ruin generation in any way. This was probably just a bug in the level generation. However, we're overhauling the ruin generation in the next update (including changes to the placement logic), so it's probably not worth it to start debugging this any longer.
