### ISSUE TITLE
Switching editor mode clears undo history

### ISSUE THREAD

**Issue by Konfuz** [Regalis11/Barotrauma#6738]
- [x] I have searched the issue tracker to check if the issue has already been reported.
*Surprised about not finding anything, I might be blind*

**Description**
Switching between edit-mode and wiring-mode clears the undo history.

**Steps To Reproduce**
1. Open Editor
2. Do some edits and note the now existing undo-history
3. switch to wiring mode (history now gone) 
4. switch back to edit mode -> history still gone. 

**Version**
v0.14.9.1 (Linux)

**Additional information**

Bug existed for me since the beginning of time, yet no one ever reported it.  
It is a minor annoyance, yet unexpected behavior.

**Comment by 3e849f2e5c** [comment]
This is actually intentional for now, the reason it works this way is because the wiring code is a massive spaghetti monster and when I implemented undo/redo feature I noticed that the code would need massive work to be able to support undo actions so I decided that instead of delaying the undo feature by 2 years I would release it and completely exclude wiring mode and made it clear the undo buffer when switching modes because else you would have situations happen like 
1. place down a wire in edit mode
2. pick wire in wiring mode and connect it to a machine
3. drag the wire out of the connection panel and delete it
4. switch back to edit mode and try to undo

The system would attempt to remove the wire we placed down in edit mode but it was already destroyed in our time in wiring mode causing a crash.

Hopefully one day I will have more time at my hands to look into extending the undo functionality to get rid of this annoyance but the code really is that bad.

**Comment by 3e849f2e5c** [comment]
I've added a disclaimer now to make it clearer that the undo feature is not available in wiring mode in https://github.com/Regalis11/Barotrauma-development/commit/efe5100fd1a58bff8563d97375c4eb3e92d3f430

![](https://kosblue.com/e/wheabf.png)

**Comment by Konfuz** [comment]
> but the code really is that bad. 

Apreciate the honesty ^.^ Good luck with the refactor.
