### ISSUE TITLE
Question- Would changing names of items or their descriptions in xml files make content packages mismatching in multiplayer?

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#676]
If I had to rename "Junction box" in it's xml file to "Skrzynka odbiorcza" would multiplayer mode on English server inform me about mismatching content package?

**Comment by Regalis11** [comment]
Yes, changing the names of the items (or anything else in the item config files) will break compatibility. Atm there's no proper language support in the game, you need to basically create a mod if you want to translate it.

**Comment by rico6822** [comment]
Ok.

**Comment by Momiro** [comment]
With Nilanth's mod, you can change the contents of xml files, and change the hash the server tries to match to the client. If you change anything too drastic, though, you'll induce a crash. There's more information in his mod.

**Comment by NilanthAnimosus** [comment]
It won't crash you'd just induce excessive desync, infinite explosions, and weird GUI effects like being unconcious at half health.

Generally what is not to be changed has been detailed somewhat (Albeit not enough in my opinion) in the settings XML of the mod, however it is important to know the mod does NOT ALLOW modification of the XMLs client-side due to the potentially cheaty nature of such so it is not a solution Momiro.
