### ISSUE TITLE
Empty Suitcase (storage container) falls through the terrain when dropped

### ISSUE THREAD

**Issue by EvilBadger34** [Regalis11/Barotrauma#6776]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I dropped a suitcase (storage container) outside near the terrain to temporarily set it down and get out a tool, but the suitcase kept falling and I never saw it again. I made another one and had items in it, it hit the ground and stopped falling when it had items in. (Windows) 

To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by EvilBadger34** [comment]
Sorry about the issue tracker, I don't know how to check that. And github wouldnt let me type further than the description box

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I couldn't get this to happen: the storage containers seem to hit the ground regardless if there's items in them or not. Did this happen in multiplayer or single player?

**Comment by EvilBadger34** [comment]
It was solo player, If this info helps, I was above a cave system that used a separate type of terrain, it looks reddish. The cave was full of twigs that slow you down and it was full of green gas. That is where I lost my storage container that fell through all the terrain.

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by Moleculor** [comment]
Would it help if I provided a video and a save file?

https://discord.com/channels/103209684680323072/910489857028128818/930971143437967361
https://cdn.discordapp.com/attachments/910489857028128818/930971141420503040/BarotraumaWhy.mp4

That video is *two* clips of *two* separate instances of it happening to me. 

The **second** half of the video (second clip) is from the attached save file.
[First No Rad - Rename and just remove the .zip extension.save](https://github.com/Regalis11/Barotrauma/files/7861570/First.No.Rad.-.Rename.and.just.remove.the.zip.extension.save.zip)
 
It occurred in the area where I'm clearing out the nest mission in that save. To try and give slightly better directions to it, you can see my conversation on Discord of me being *above* that area [here](https://discord.com/channels/103209684680323072/910489857028128818/930962818537230386).

It would be the area BELOW this ice blocking me, I believe. 
https://cdn.discordapp.com/attachments/910489857028128818/930963236747087932/unknown.png

Since there's ores in the video, the specific location should be fairly easy to find? I think? I hope?

I've also noticed that on loading a saved game, or possibly on saving? my character will have all their items completely stripped from their body for about 200ms or so (rough ballpark estimate on the time), which means everything drops with a \*CLANK\*. I wonder if this might thus be related to #7891.

**Comment by EvilBadger34** [comment]
I don't see any further comment from regalis. I hope devs saw this
