### ISSUE TITLE
Magazines/ammo boxes don't spawn the first non-hitscan projectile while being used if used on handheld weapons.

### ISSUE THREAD

**Issue by SpazzMaticus107** [Regalis11/Barotrauma#6782]
**Description**
As I was modding I found out like the title of this post says that the magazines and ammo boxes don't spawn the first non-hitscan projectile while being used by a handheld weapon. For example if we had a weapon that uses a magazine which spawns hitscan bullets the first and each subsequent one will be fired while if we had a weapon that uses a magazine spawning non-hitscan bullets such as coilgun shots the first shot would only decrease the magazine condition and not spawn a projectile while the rest of the projectiles would be spawned. This happens with each new magazine that has not yet been fired at least once with a gun that fires projectiles with a magazine. This means that if you used 10 different magazines and fired 1 projectile out of each of them you would consume the ammo of each magazine but not fire a single bullet at all.

**Steps To Reproduce**

**1.** The easiest way to reproduce this would be by downloading this workshop mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=2511627423&searchtext=coilgun
and seeing for yourself how the first shots don't spawn.

**2.** I checked the code and didn't find anything wrong but if you'd like to go in raw then I suggest you moddyfing SMG's ItemContainer from:  Containable items="smgammo"  to  Containable items="smgammo,coilgunammo"
Then just spawn inside of a dugong, spawn in the tweaked SMG, take the ammo box off of the coilgun loader and insert it into the SMG and try hitting an NPC or anything really with the first shot.

**Version**
Live, Windows

**Additional information**
This problem with the first projectiles not being spawned only refers to handheld weapons. The coilguns of course work fine but as soon as we modders try to put together a weapon with a magazine spawning non-hitscan projectiles the first of said projectiles will not be fired, only consumed.

**Comment by Regalis11** [comment]
This happens because of the way the SMGs (and other ranged weapons) spawn ammo inside the magazine: this is done by triggering the OnUse effects of the magazine, which in turn spawns the ammo. What causes the issue is that on the first use there's no ammo inside the magazine yet, so it fails to fire. It should be possible to work around this problem by making the coilgun ammo boxes spawn with a pre-placed projectile, the same way we do with the handheld weapon magazines:

`<ItemContainer hideitems="true" capacity="1" spawnwithid="coilgunbolt"...`

**Comment by SpazzMaticus107** [comment]
Thank you so much
