### ISSUE TITLE
Make Characters on Ladders Aim Revolvers When Standing Still- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#681]
Make characters on ladders being able to aim revolvers in other directions, than up while standing still. Maybe do the same thing with other tools, like welding tool.

**Comment by ZealanL** [comment]
I would suggest this is only possible with a single hand free - that way you can still hold onto the ladder to make things more realistic. Climbing with both hands occupied seams unrealistic to me. But I think for sure if your 1 hand is free you should be able to properly aim the revolver.

**Comment by NilanthAnimosus** [comment]
Actually its not too unrealistic if you impose a restriction that they cannot move along the ladder while they are aiming instead - After all you've got no free hands to go higher up the ladder but nothing exactly stops you leaning into the ladder to use a two handed object - even if your arm was wrapped around one of the bars, but I sure would find it hard to move doing that.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
