### ISSUE TITLE
Question- How to Edit Save Files

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#682]
For me it looks like it's dll coding and notepad ++ is not enough to get through it.

**Comment by Regalis11** [comment]
The save files are created by compressing the submarine file and the gamesession file into a gzip archive. 

1. First you need to decompress the archive (with WinRAR or similar).
2. Then edit whatever you want to edit (the submarine might be difficult to do changes to, because it's embedded in the same file in a non-human-readable form).
3. Compress back to .gz and make sure the extension is .save.

I won't guarantee this works though, I haven't tried it and wouldn't be surprised if there's some additional steps required to get the edited and decompressed file back to a state where the game can still read it.

**Comment by ZealanL** [comment]
I just made a simple C# program that decompresses it, and then edit the XMLs and such inside.

Once decompressed, it's easy XML editing. You can change any value.

**Comment by Momiro** [comment]
Care to share

**Comment by thegrb93** [comment]
Just change its file extension to .gz and use something like 7zip or winrar to extract it, then edit with notepad++

**Comment by Momiro** [comment]
Interesting. Extracting a submarine file and editing the xml might be a much faster way of editing permissions on doors. Since I usually copy one type of door for all similar reasons, the 'Message' field is all the same on the ones I want to lock, so I can just find and replace all instances of that door with the one that can't be rewired.

**Comment by NilanthAnimosus** [comment]
Because its such a mess to work out what door or item is what though if your really going to use that method I highly recommend you add tags or some other form of identifier to the entities in question you want to edit - such as you wouldn't want to edit every item and door imaginable, you can just add the related changes and remove the identifying tag you placed when your done.

**Comment by Momiro** [comment]
Ah yes, all the doors I wanted to have completely locked out from player editing, I copied from one door template that has the message table for rewiring labeled "Cannot be rewired." yet it can still be rewired. When I'm done with the editing, I'll open up the submarine file and replace all instances of any doors with that message with the locked version. WIth notepad++ You can find and replace multiple lines of code at once.

**Comment by ZealanL** [comment]
I often use Notepad++ for changing builds with ease. Say for example I wanted to change all the wall colors to dark blue, I could do so in a couple seconds rather than tediously going through each wall in the editor and typing in the color values. There are many existing programs to preform and revert GZip compression. If anyone wants my program, I can give you it (but it's kinda lame).

**Comment by Neon-Nuisance** [comment]
> I often use Notepad++ for changing builds with ease. Say for example I wanted to change all the wall colors to dark blue, I could do so in a couple seconds rather than tediously going through each wall in the editor and typing in the color values. There are many existing programs to preform and revert GZip compression. If anyone wants my program, I can give you it (but it's kinda lame).
> 
> As for save files, it's fairly easy to find certain items, characters, components, etc. and change their values, since the values are displayed in a human-readable format.

I would be interested in using your program. Contact me at neonnuisance@gmail.com

**Comment by randomcarnage** [comment]
Hi ZealanL,

I would like your program. I have been trying to edit save files so I can make custom characters in a campaign, but whenever I try to load an edited save file the game tells me that the save is corrupted.

**Comment by Crushedice** [comment]
As i searched for something to edit a thing in the savefile and found this question. - but no solution
I slapped this together to solve this.  
https://github.com/Crushedice/Barotrauma-Save-Converter
