### ISSUE TITLE
Permission lock wifi components, signal check, delay components, etc - Feature Request

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#687]
There are certain electronics that cannot be permission locked, because their options don't need a screwdriver to edit their values. Currently the best way to prevent someone from messing with those is to hide them in the walls.

**Comment by NilanthAnimosus** [comment]
Essentially a method to deny InGameEdit-ables from being edited. It does make sense to give sub designers a method to restrict this - but perhaps ingameedit-able values should actually take a tool at some point to access - Or at the very least an ID cards tags and disable it that way, given there are some situations you do want these edited too.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
