### ISSUE TITLE
Allow fabricators to use condition from multiple item types (As long as the name or alias of matches)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#689]
The alias is a nice mechanic that lets you find other items with different names, and it works with the fabricator to a degree - but fabricators currently do not recognize items beyond the first even if the alias matches to use for crafting.

An example of this is wire, There is Red/Blue/Orange/Green/Black wires. their all essentially "Wire" and if a crafting recipe uses wire, all of their conditions should count towards it.

but if you load in a red wire, then blue and orange. it will only recognize the first (Red Wire) for crafting. not the others inserted until red wire is gone, which point it may begin recognizing blue, then orange.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
