### ISSUE TITLE
[0.15.9.0] Abandoned Outpost - Hostages will not follow players that has diving suits on

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6975]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was in Multiplayer. Hostages will not follow players that has diving suits on in an abandoned outpost. Likely that they believe they need a suit themselves.

**Version**
0.15.9.0

**Comment by ekqvist** [comment]
Unfortunately, I haven't been able to reproduce this so far myself either. I'll have a look at the code to see if I can spot something that could cause this. But if someone can come up with the steps to reproduce this, that would be most helpful.

**Comment by itchyOwl** [comment]
> hostages appear to be line of sight based for orders, they won't follow you if they can't see you.

They use the same method for for following the player as any other follow order. There's no line of sight check, but they can't open doors if they are handcuffed. And like Kaillera suspected, they do think they need a diving suit, just like the bots in your crew would. But they only did that when they were not handcuffed. So if you just ordered them to follow without releasing their hands, they would follow as long as the doors/ladders weren't blocking their path.

Fixed in Regalis11/Barotrauma-development@f8ba955.

Steps to repro:
- Load this save: [https://app.zenhub.com/files/93301055/55c1d4e0-9123-45ba-894d-19548fba00d3/download](https://app.zenhub.com/files/93301055/55c1d4e0-9123-45ba-894d-19548fba00d3/download)
- (Kill the bandits)
- Uncuff one of the hostages
- Order both hostages to follow
- Equip the diving suit found on the right (or just equip a suit and make sure the hostages can't access it)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
