### ISSUE TITLE
Overloading handheld sonar to use it as a creature flare

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#698]
Nasonov artifact is really useful to make a big group of creatures stop chasing you or make some big creature stay at the bottom and wander around it while you are able to shoot at it or move past it. But it's too big to fit inside a shell or depth charge and is constantly active, which makes using it inconvenient and dangerous. Also it disappears after you finish your mission, so you have to look for a new one every time.

If you could overload the handheld sonars to make them attract creatures for a short time until their batteries are depleted, it would give another interesting way of dealing with the creatures. Instead of just having a face-to-face battle, you could try to outsmart them by loading a shell or a depth charge with an overloaded handheld sonar and shooting it at wherever you wanted the creatures to be. Not only that would be helpful during killing missions, but it would also let you avoid creatures more often whenever you were trying to sneak past them in stealth mode.

Perhaps, the way this should work is having an "overload" checkmark in the sonar's gui, that, once checked, turns the sonar into an AI attractor that produces a recognizable sound and depletes its batteries really fast.

If that feels unbalanced, perhaps, you could instead make an attractor as a separate item, craftable from nasonov artifact. That way players wouldn't always have a lot of spare AI attractors on their hands.

**Comment by Weebyxanide** [comment]
Actually, handheld sonars kinda function as decoys already if you turn them on and drop them. The only problem is the fact that reactor noise is generally a lot more appealing to the critters.

**Comment by BillCombs** [comment]
Actually, for some reason they only make noise inside submarines. Once you get them in water, they become invisible to sonars, what means they are most likely silent to creatures too.

Perhaps that has been made so lone players wouldn't immediately get eaten by creatures after they get out of subs.

**Comment by BillCombs** [comment]
Sonar beacons in the dev version seem to work as flares pretty well right now. And handheld sonars got sonar noise in water now. 
So there is probably no need for the overloading sonar function anymore, since it can be substituted by using either of those.

There are few bugs that the beacons have

When you have an activated one inside a container or your inventory, taking out the batteries or depleting them doesn't turn the sonar noise off. And creatures seem to still be attracted to it.

Beacons broken by creatures seem to stop attracting them, but they still show sonar noise on the sonar. They work without batteries and in any environment.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
