### ISSUE TITLE
Make Mantis Bleed But It Quickly Recovers From It- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#701]
Mantis has enabled blood particles, so it has it's own bloodstream. Can we make mantis bleed and recover from bleeding as fast as charybdis or faster?

**Comment by Regalis11** [comment]
Why? I think it's more interesting to have monsters that require different approaches to kill, and having the mantis be completely immune to bleeding is in my opinion something that helps differentiating them from crawlers.

**Comment by NilanthAnimosus** [comment]
Although when I use my mod I make every creature except the carrier bleed (And indeed myself made mantises have an exceptionally high rate of bleed recovery), I actually am more towards vanilla not having all creatures bleed, different tactics and slight variance is always nice.

I don't recall mantises having blood particles while playing, but maybe a content pack / modder can always add bleeding to creatures outside of vanilla, Instead of static particles though perhaps it could be a config element of some kind that decides what the blood particles are to be used on a per creature basis, perhaps with a default - with the option to have none, even if it bleeds or not.

Or at the very least disabling the apparent bleed effects of a mantis.

**Comment by rico6822** [comment]
I still recognize it as weird, that mantis releases blood, even when alive and it doesn't die of blood loss at all.
