### ISSUE TITLE
Monsters Receive Reduced Damage While Eating Corpses- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#705]
I don't know if that was planned, but regardless where I hit a monster eating a corpse, that monster has highly reduced damage by at least 80%. Damage is reduced, even when monster does not hide behind corpse and is hit into unarmored body part.

**Comment by Regalis11** [comment]
I haven't found a way to reproduce this. I would guess that the attacks did hit an armored limb, because the armor reduces damage by exactly 80%. Also, when a crawler/mantis is eating something it's extremely hard to hit an unarmored body part because they're located under the monster, almost entirely shielded by the corpse that's being eaten.

**Comment by rico6822** [comment]
I have hit both armored and unarmored side for reduced damage. Try reproducing again.

**Comment by Regalis11** [comment]
If this happened in the multiplayer, it's possible that the positions of the character and the projectile didn't match exactly between you and the server, causing it to hit an armored limb server-side but an unarmored one at your end.
