### ISSUE TITLE
Charybdis may be Too Powerful- Rebalancing

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#706]
Charybdis is so fast it is nearly impossible or impossible to run away form it. It also deals very high damage to both players and submarines doing it. Players are most often being instakilled and while walls outside are hit at least 30% of the submarine outside wall structure takes damage (seriously, when my submarine got hit by it submarine really took so high damage). Charybdis also makes a short pause between hits not of 10 seconds, but about 4 seconds, but that's various.

**Comment by Weebyxanide** [comment]
It's a gigantic predatory hell-whale, you shouldn't be fighting them in person anyway. Humans are tool users. Use those railguns and evade while firing.

Also, they're inhabitants of the abyss so their rarity counterbalances how absurdly dangerous they are.

**Comment by Baywatcher11** [comment]
Charibdys is supposed to be deadly in such manner, as they are rare enough to avoid them. I mean, if you are clever enough to know what "silent running" is, you could easily avoid 80% of creature encounters. 

As Weebyxanide said it, fighting it in person will only make the situation harder, instead of going outside, you could easily eliminate Charybdis with nuclear shells.

**Comment by rico6822** [comment]
I encountered charybdis in 500 meters of spawn 3 times in a row. Not all submarines have railguns on all the side and charybdis quickly changes them. Also I never fight this thing outside submarine.

**Comment by Regalis11** [comment]
I agree with BillCombs, there aren't many enemies in the game that pose a major threat to experienced players, so I'd rather keep charybdis as challenging as it is.

However, they are supposed to be a very rare high-difficulty enemy, so obviously you shouldn't run into them 500 meters from the spawn. In the dev branch this shouldn't happen anymore, because we can configure how far the player has to progress for a given type of monster to spawn, and prevent them from spawning in low-difficulty levels altogether.
