### ISSUE TITLE
Add more sources of noise detectable by passive sonar

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#708]
Passive mode seems pretty useless in terms of vision when you are going in silent mode. None of the creatures or other things producing sound seem to be detectable by the sonars. Because of that you are completely blind when you are in passive mode and not making any noise come from your submarine.

It would be interesting to have some other sources of sonar noise. Exploding railgun shells, hydrothermal vents, creatures making noise. All that should be detectable on the sonar in passive mode.

The problem i see in that idea is that creatures may decide to follow each other or stay near any constant noise source indefinitely(like they do with the nasonov artifact) because their AI seems to be really attracted to noise. Perhaps you might find some way to work around that. 
But i don't see any problems in making anything, that only makes noise once and for a short time(like explosions), detectable by sonars. Creatures might get attracted to them, but they wouldn't get stuck in that position.

After more testing i found out that creatures don't seem to care at all if you shoot at them, they only seem to care about noise being produced by your submarine. This might be exploitable. You can just stay silent and shoot at creatures without expecting them to attack you. Railguns should make noise when they shoot.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
