### ISSUE TITLE
[AI] Bots sometimes head to the Pirate Sub when giving the "Return to Sub" Order

### ISSUE THREAD

**Issue by Cusuno** [Regalis11/Barotrauma#7109]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a pirate submarine is present in the level, giving bots the "Return to Sub" command sometimes makes them mistake the pirate sub for the player sub and they will try to head towards the pirate sub.

This originally occured while I was in a campaign level doing both a Pirate and a Cave mission. When ordering the bot to return back to the sub, I noticed they were going past my sub's airlock and went straight into the unknown. After bringing the bot back and checking the sonar, it turns out the direction they were heading to was actually one of the Pirate markers.

**Steps To Reproduce**
- Load in a Pirate Mission level
- Go outside and make a bot follow you
- Order the bot to return back to the sub
- Sometimes the bot will pathfind their way towards the pirate sub instead of your own

**Version**
v0.15.12.0

**Comment by ekqvist** [comment]
Hi! Thanks for reporting the issue! Unfortunately, I couldn't reproduce it. The Return order (and the AI objective it uses) is should only target a submarine that belongs to the same team as the order giver. There was a recent bug (#7019) that could cause problems for bots to enter the subs. It's possible that issue was also the root cause here. The most recent Unstable version should also now include a fix for that issue. So, it's possible it's been fixed. But let me know if the issue persists or if you find a way to reproduce it.

**Comment by Cusuno** [comment]
That bug was likely the issue then!
I remember being attacked and I ordered the bot to return back to sub to find safety - only to see them move past the airlock.
Perhaps the pirate sub being in the level was just a coincidence and made me think that would have been the root cause.

**Comment by ekqvist** [comment]
Yeah, that sounds likely. If it happens that you run into this issue again, please feel free to comment again on this issue or create another issue to report it. Thanks for your help either way!
