### ISSUE TITLE
Gun holding animations/positions and muzzle flash positions

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7118]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Neither shotgun is held properly.
Riot shotgun looks just weird, as it's too long to be hip-fired:
![Barotrauma_veXdDw6lbo](https://user-images.githubusercontent.com/10529134/139665593-aaf60921-38d8-439d-8100-f85778748a53.png)
![lZk8U6aQg2](https://user-images.githubusercontent.com/10529134/139665600-c3228e7c-782c-4f70-b407-c81b92563db5.png)
Yes, you could say Autoshotgun is hip-fired on purpose (doesn't mean it _should_ be) but the riot shotgun is neither really hip-fired nor shoulder-fired. 
![Cre4r77Ixg](https://user-images.githubusercontent.com/10529134/139665824-195fd31e-4b0e-45de-9a28-5af8321d6fae.png)

Muzzleflash problems:
Revolver (it definitely doesn't have a muzzle brake)
![Yao7hus5P7](https://user-images.githubusercontent.com/10529134/139665718-d275e5f7-cb4a-4ee3-9b29-d85ccc2c7346.png)
Riot shotgun
![D52ZEJVePc](https://user-images.githubusercontent.com/10529134/139667237-13dce0ff-f4ef-4272-aa70-2b5eeb954334.png)
SMG
![qdhmRmuney](https://user-images.githubusercontent.com/10529134/139667226-9332808e-6702-4445-84d0-f5e4341a760c.png)
Autoshotgun
![JoEMJKj1G5](https://user-images.githubusercontent.com/10529134/139667401-8ce69113-dfe8-4a6e-a7d4-2a497e42d3e8.png)
Assault rifle is fine.

**Version**
v0.15.12

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b425bd0517e1de26456436d17fab6f3ec093bb94

**Comment by Rokvach** [comment]
Riot shotgun crosshair hasn't been updated to match the new weapon position
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8b5b3471-db95-458c-97fc-9924a23732ec)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8eccb12e334d385a98e822dee3286f09de8a7779. Still not perfect, but that was the best I could do with the current aiming logic that doesn't take the difference between the item's barrel position and the item's origin into account. Might be something to address later, but I'd consider it a very low prio since the discrepancies are so small and since fixing this would complicate things (particularly the item holding and IK logic) quite a bit.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
