### ISSUE TITLE
Problem with hosting

### ISSUE THREAD

**Issue by KATSU3123** [Regalis11/Barotrauma#7120]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 When I start a new round (I sail from the station or dock at the station) All players are eliminated. When they try to join again, they become observers and their bodies are not controlled by them.   Unfortunately, I have no idea how to fix it.   This problem was in the update when I started playing (Embrace of the Abyss) And this is true in all subsequent versions. Windows 10 software version.   People describe this problem like this: First I load up and I see my body and the submarine. after that, things fall out and I'm out. After trying to return, I become an observer, with a living body.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Hello and thank you for the bug report!

I'm not entirely sure I understand the problem correctly: do you mean the players get disconnected and kicked back to the main menu? Is there some kind of an error message when this happens?

**Comment by HeatedWafflez** [comment]
> Hello and thank you for the bug report!
> 
> I'm not entirely sure I understand the problem correctly: do you mean the players get disconnected and kicked back to the main menu? Is there some kind of an error message when this happens?

![image](https://user-images.githubusercontent.com/51425624/141373950-55d28c29-6f5b-4b33-b523-250b12b0f570.png)
I'm not sure entirely what causes this issue, but this seems to appear when this issue happens. It's incredibly common and unfortunately it makes most campaigns unplayable because of how often people are stuck spectating and the host has to return to lobby to restart.

From what I've been told though, restarting and verifying the game seems to lessen this issue? 

Here's another error I had in that same server, although whether this is related is unknown 
![image](https://user-images.githubusercontent.com/51425624/141374261-8b4364c8-c09b-4455-8b49-92cb302e8cd2.png)

 I'd also like to state that for some reason players will sometimes get booted back to the lobby and it'll automatically try to change their name to someone else in the server, but fail because that name's already taken? Sometimes when I spawn in as well I'll take control of someone else's body but be stuck ragdolled until I leave and rejoin.

I'm also finding that as these networking problems occur more and more people seem to be kicked out more and more often from missing items. I have never encountered this issue before and I suspect it might be related to the player's internet speed, and whether they're able to load in quickly enough, since personally I have very good internet.

**Comment by Regalis11** [comment]
Most likely addressed in https://github.com/Regalis11/Barotrauma-development/commit/269ca20cfdeddb6444f0d10e60d7eea39ced8a18, closing as the changes have already been tested for https://github.com/regalis11/barotrauma/issues/7175
