### ISSUE TITLE
Changes in Water Pressure's Logistics- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#713]
1.Depending on the depth player is diving water pressure will either kill him faster or slower.

Here is how it looks like (can still decrease or increase past 10%):

800-899 10% slower.

900-999 5% slower.

1000-1099 default speed.

1100-1199 5% faster.

1200-1299 10% faster.

2.Diving suits have their limited durability and 20 minutes under ocean they break. This feature is a detail.

3.Players don't instantly cure their water pressure damage and will still have limited sight to the time they use medicals curing it. Water pressure damage also slows down player's moves.

**Comment by thegrb93** [comment]
Please no

**Comment by BillCombs** [comment]
1) I think there is no point in making pressure kill you faster or slower because, in my experience, i usually survived for about only 5 seconds max when the submarine was getting filled with water slowly. Adding or removing like 10% from 5 seconds will only make it either 5.5 or 4.5 seconds. And pressure that kills you outside of the sub does that in about a second. Adding or removing 10-50% from it will not make any noticeable changes. The only depth in which it will be really noticeable is depth of the abyss, but there is no real point in it because once a damaged sub enters abyss, it's usually never going to return alive.

2) As for diving suits, i think that if the game takes place in the future and on another planet, the technology of diving suits must be advanced enough to withstand high pressure with ease(except for the depth of the abyss).

3) I believe that having your sight limited is mostly made as a sign of being in high pressure environment, just so players would know that they are in danger and would try to get away from it. Having such a debuff as poor vision would be really annoying, and you would have a really hard time trying to find a cure for it since your poor vision wouldn't let you see much. I feel like water pressure is already pretty deadly enough.

**Comment by Regalis11** [comment]
Yeah, I don't really see the need for any of these. Protecting yourself from pressure is already difficult enough even without automatically breaking diving suits and persisting pressure damage, and since pressure kills you almost instantaneously, it doesn't make much difference if it's 50% faster or slower.

**Comment by rico6822** [comment]
It's all for details.
