### ISSUE TITLE
Creatures can't "hear" reactor sounds

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7164]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Spawn a crawler within 15 meters of a working reactor
2. Spawn a moloch within 15 meters of a working reactor

Moloch will ignore the sub if the engine and pumps are stationary, despite the reactor being on. Crawler will only attack on sight.

**Version**
v0.15.13

**Additional information**
Molochs attack the engine correctly. They won't attack an oxygen generator.
Also, only molochs attack a sonar beacon, other creatures don't.
I tried adding missing `fadeouttime` but it did not help.
https://youtu.be/MLHQfK2A07M

**Comment by Regalis11** [comment]
The molochs don't seem to be close enough to the reactor to hear it in that video. The amount of noise the reactor makes is relative to how much power it's operating, and since Humpback's reactor generally operates at way below the maximum capacity, it doesn't make that much noise and can't be heard from very far (especially now after the adjustments mentioned in https://github.com/regalis11/barotrauma/issues/6450 that were intended to make stealthy movement a more viable tactic).

To get a better idea of the sound ranges, you can use the console commands "debugdraw" and "toggleaitargets": the yellow circle around the reactor indicates the range of the sounds.
