### ISSUE TITLE
cannot mod talents file

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#7181]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
cannot mod talents

**Steps To Reproduce**
make a mod that alters talents at all, it doesnt matter, it refuses to accept changes.
the worst part is just the slap in the face when it tells you <override> isnt allowed, how do i ever override them?

**Version**
Stable windows 10

**Additional information**
sad.

**Comment by Regalis11** [comment]
It seems overriding talent trees wasn't possible, but I couldn't find any issues with overriding talents themselves. I suppose you were trying to override the whole tree?

Overriding the trees should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5229034b7115e8995ef774bf406351a48a218c4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
