### ISSUE TITLE
Electrochemist talent utterlly horribly breaks talent system upon getting bestowed a coalition medal of some kind

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#7209]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when an engineer has the Electrochemist talent, whenever a coalition medal thing is used, it breaks the character's talent tree, you can no longer gain skillpoints, xp is no longer gained, but the currently got talents are kept

**Steps To Reproduce**
give an engineer electrochemist talent, now put a medal on him, he promptly breaks forever, no death, or re-joining can fix, only way to fix is to permanently delete said character.

**Version**
Stable, windows 10

**Additional information**
(might have to do with the fact the medal is probably considered an ***attack*** as the captain DOES fall over stunned when applying the medal.

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. As bryson099 mentioned in https://github.com/Regalis11/Barotrauma/issues/7210, this might've been caused by the "All-seeing-eye" talent instead, assuming that one had also been unlocked. We have another ticket about the all-seeing-eye issue here: https://github.com/Regalis11/Barotrauma/issues/7111

**Comment by doornydew** [comment]
huh, that might be it then, i'll edit the game code quickly, give 3 talents on all seeing eye, and see if if still happens
