### ISSUE TITLE
some weapons do not respond to quality fabrication changes

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#7214]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The  Rapid Fissile Accelerator and Handcannon aren't affected by any +1 crafting perks, Mechanic can't create dementonite knife as masterwork item." 

i got this bug from discord, guy didnt want to make an account himself. 

*** he was modding to allow other jobs to get a +1 crafting quality on their respective items, seems those items said beforehand just didnt work ***

**Steps To Reproduce**
make these specific weapons with a mod or console commanded talent that adds +1 crafting quality, these will promptly not care for it and will not upgrade 1 quality higher. 

**Version**
stable, (dont know, didnt ask) .

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report! 

I'm pretty sure that the issue is with the way the mod configures the talents. The "gunsmith" talent which increases the quality of fabricated weapons requires the items to have the tag "gunsmith", which the rapid fissile accelerator or the handcannon don't have (since they cannot be crafted by security officers in the vanilla game). There is also no combination of talents that'd allow fabricating masterwork dementonite knives in the vanilla game.

I recommend modifying the talents so that they include all the identifiers/tags of the items you want it to affect.
