### ISSUE TITLE
Bots go outside to repair outer hatches/doors (they shouldn't)

### ISSUE THREAD

**Issue by OceanFish1** [Regalis11/Barotrauma#7232]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Played on Typhon 1. When something damages north dock port hatch, bots that are tasked to repair mechanical stuff, due to problems with reaching the hatch from inside, are leaving the ship (taking any suit they get in the path, resulting in death to pressure on deep missions because they can take the oldest suit), then as soon as they leave they either enter "find safety" mode (if there are no enemies) or "fight the enemy" mode. Anyways they do not fix the hatch and usually die until you recall the "fix mechanical" order.

**Steps To Reproduce**
1. Play on Typhon.
2. Order someone to fix mechanical things.
3. Damage the northern dock hatch.
4. Check how AI is going fix it.

**Version**
Windows 10 v0.15.13.0

**Additional information**
Also they may just swim as far as possible from the ship and not return.

**Comment by itchyOwl** [comment]
"Crew member bots are afraid of water." <- I don't quite understand what you mean by this, but the issue seems to be that the bots are allowed to target the doors and hatches, which are in the fridges of the submarine. It's not intentional that they actually go outside though. Fixed this in Regalis11/Barotrauma-development@9d81c25.

In that particular case the bots actually shouldn't be able to reach the upper hatch, because it can only be repaired from outside. If the bot (or a player) attempts to fix a hatch from a ladder, he/she will drop. I think these are remnantes from the past when the hatches were still repairable with welding tools instead of wrenches. We could fix this by adding a platform there, but I think there are other similar hatches on other subs that can't properly be repaired from inside. I'll pass this information for the sub designers.

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
