### ISSUE TITLE
Give Player an Option in Settings Menu to See FPS of Other Players- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#724]
Sometimes, before I reply to security, why did I did a suspicious thing they stun me, before lag goes off and so I could not finish the message. Officers seeing players with less FPS will have more patience to them.

**Comment by BlueTheKing** [comment]
Honestly that makes absolute zero sense, showing latency would be great though.

**Comment by rico6822** [comment]
An option to see FPS of other players near them, in "Info" tab or near their nicknames in lobby.

**Comment by BlueTheKing** [comment]
Why? There is honestly no use for this and most likely people will just abuse the low fps players since they can't aim/react as fast.

**Comment by CommanderMark** [comment]
> Sometimes, before I reply to security, why did I did a suspicious thing they stun me, before lag goes off and so I could not finish the message.

That...has nothing to do with FPS, that's just your internet lagging.

> Officers seeing players with less FPS will have more patience to them.

[citation needed]

**Comment by juanjp600** [comment]
A hacked client could always just report a fake framerate, so you'd end up with trolls going rampant with security guards that don't know any better, or players that are aware of this and completely ignore the reported framerate, which leads back into the same problem this is supposed to solve. Because of this, I don't think it makes much sense to implement in the first place.

**Comment by rico6822** [comment]
Alright, I think I can close this issue.
