### ISSUE TITLE
Mission Monsters In Multiplayer Sometimes Spawn Near Ending Destination- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#725]
If I get too close to them mission is getting over and (example) carrier I was tasked to kill was not only in range of ending destination, but carrier was outside the map and no leaks in rocks existed to go through.

Even if I would be able to lure that carrier out of destination it would be quite annoying to be instantly taken to a city after being close to it in the middle of combat.

**Comment by BillCombs** [comment]
> Mission Monsters In Multiplayer Sometimes Spawn Near Ending Destination- Bug

I think the monsters spawning near the end is not that much of a bug, it's a bug if they get stuck somewhere at the end where you can't reach them.

> If I get too close to them mission is getting over

If i remember correctly, there is an option to make the round end at the ending destination only after end round vote. It's pretty handy since you can get to the end and repair your ship before starting a new mission, so it wouldn't spawn full of water on the next round. Pretty sure something similar is in the singleplayer mode. Though it is a problem sometimes, when admins set the option to end the round at the destination without vote.

I would like to ask for the fix(in case one is coming) to not remove the possibility of creatures to spawn near the end, because, at least for me, it's a pretty good surprise to feel safe near the end then and suddenly get attacked by some creature.

Also, are you sure they were in an completely unreachable place? Sometimes i get monster spawns near the end destination that appear to be on the other side of the wall near the end, but they are reachable.

If you still have the save files or remember the seeds used in the maps where you encountered this bug, i am pretty sure they would help the developers get more information about it.

**Comment by BlueTheKing** [comment]
Depends what you think is "near end" if you push it to the end thats not a bug, if it spawns and doesn't move but is near the end then it is.

My idea would be to have a timer when near the end, 5-ish seconds for the dock to initiate and end the round.
As for the creature spawns, i never had them spawn so near the end that i couldn't kill it, imo they should be able to spawn on the path to the end but not on the end itself, pushing them that far is still possible though

**Comment by rico6822** [comment]
I mean it's annoying, that most often servers are set to automatically end game by being near city. Those monsters must be lured out and while this happens other monsters as well are pursuing submarine sometimes.

I also think those monsters shouldn't spawn outside the map as that's a real issue.

**Comment by BlueTheKing** [comment]
If you can't reproduce it get the map seed.

**Comment by rico6822** [comment]
I don't have it. Do I have to remember every map seed in the game I played? Also seeking similar situation like ti takes some time.

**Comment by BlueTheKing** [comment]
Alright, sure.

**Comment by rico6822** [comment]
The only way to salvage artifact like it is to leave submarine out of city's range and swim for it on foot.
