### ISSUE TITLE
Add an option to yell in chat(normal non-radio talking but with bigger range)

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#726]
Sometimes you want to tell something to people at the other side of the hallway but don't want to alert the whole crew; normal talking range is too small for that, but using radio would draw too much attention; yelling would be perfect for that.
Occasionally you end up locked in a room without a radio, and usually nobody can hear you ask for help(unless they get really close to the walls); i think you should be able to yell and be heard by somebody walking near the room(because even though the walls stop some sound, i don't think they are supposed to be completely soundproof).
Sometimes when you get your radio stolen, you may have a really hard time trying to talk to people, because they rarely want to stop their important work just to listen to you, and if you try to talk to people while they are walking, they usually walk out of your talking range before you manage to finish typing the message and press enter; yelling would give you bigger talking range and thus more time to finish typing the message(Though this particular problem could also be fixed by having an option to copy and paste your messages in the chat. Being able to prepare the message in advance, so you wouldn't have to type it all right in the middle of a problematic situation).

You could make it work like the radio works, but instead of "r;" use something like "y;".  Or you could make the message get increased range if most letters in it are capital letters(i remember seeing that mechanic in some game but not sure if it would work here, though it would be preferable since most players use caps intuitively when they are roleplaying yelling.)

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
