### ISSUE TITLE
Make All "Locked" For Rewiring Devices Being Rewireable in Single Player- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#730]
No hazardous griefers on board, so why not? Devices can be rewired with what they could be rewired by default from submarine editor. Shuttle engine would be rewired with screwdriver and signal check component with either screwdriver or a wire.

Lore:
The coalition noticed, that specified crews with normal first and last names can be trusted about wiring and they allow them to have submarines not blocking it.

**Comment by Regalis11** [comment]
Rewiring the devices is locked in the vanilla subs because you can do some serious harm by messing with the wires, even in the single player. Some of the items are positioned in a way that if you remove the wires, you may not be able to rewire them again, making the shuttle unplayable. And as the vanilla shuttles are not meant to be used as the main submarine in the single player campaign, I see very little need to allow doing changes to the wiring.
