### ISSUE TITLE
Non-Mission Monsters and Artifacts Still Give Credits- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#731]
Monsters and items having their own specified credits rewards in xml files will give half as much credits regardless of current main mission to be made at the moment, if they are not directly tasked to b salvaged or killed. If the same monster or artifact has 2 different variants of credits or more, that could be paid for hunt or retrieval mission, credits will be randomized.

Example:
Crew is tasked to salvage thermal artifact and encounters tiger tresher in the middle of job. They succeed and receive 2400 credits in total. 2000 for main mission and 400 for killing shark.

Another one:
Cargo mission for clown gears. Crew salvages nasanov artifact and succeeds in both cargo and optional loot. Crew has 50% chance to receive 850 credits, otherwise it's 1100.

**Comment by BillCombs** [comment]
> Crew salvages nasanov artifact and succeeds in both cargo and optional loot. Crew has 50% chance to receive 850 credits, otherwise it's 1100.

If you mean that you would have a chance to lose the loot and get the money, i think instead this should be an optional ability to sell optional loot, because things like nasonov artifact are pretty useful to keep due to their special properties. I wouldn't want to lose them just for some money, especially since they are more rare than the mostly useless loot like faraday artifact.

**Comment by rico6822** [comment]
Yes, but this makes the game too easy if you say so.

**Comment by BillCombs** [comment]
I don't think it makes the game easier, since the artifact is pretty dangerous and inconvenient to handle. You can't go into stealth mode when you have it on board; and you can't put it inside a railgun shell or depth charge, you need to either have an airlock on the side or the bottom, or get out of the sub in a diving suit with the artifact in your hands, hoping that creatures won't get too close to you before you drop the artifact. Also since you can't use a handheld sonar while you are holding the artifact, that makes it harder to orientate in the water when you are diving alone.

**Comment by rico6822** [comment]
I have asked for this feature, because crews have to somehow not to spend more money on the main mission, than than making them on it. Savaging artifacts is also a bonus task for players complaining cargo missions to be too short or other stuff like that.

**Comment by BillCombs** [comment]
This is why i am asking for this to be optional. You either sell it when you want to and get a chance to do it, or you don't sell it if you want to keep it.

**Comment by rico6822** [comment]
The coalition can always implement the law to take all artifacts salvaged. The leader of coalition may be an autocrat, who wants all the artifacts possible for making researches with no discussion about making artifacts trophies or personal tools.

**Comment by BillCombs** [comment]
The leader of coalition does not have to know that you got extra loot, if you catch my drift.

**Comment by rico6822** [comment]
Yea, but what if submarines are always being checked properly by most loyal people of him?

**Comment by BillCombs** [comment]
In that case, i am joining renegades.

**Comment by rico6822** [comment]
Than what if both sides of conflict are ruled by dictators?

**Comment by BillCombs** [comment]
Never contact either of them and live off the stuff you find in the waters

**Comment by rico6822** [comment]
One day submarine would run out of energy or escapist vessel would became wanted.

**Comment by BillCombs** [comment]
A sub with a reactor would work pretty well if you manage to scavenge some skyholder artifacts and deconstruct them for uranium.
Being wanted would only be good since you would be able to take down enemy submarines and get loot that you wouldn't be able to get from the waters.

**Comment by BillCombs** [comment]
That seems to be too much effort from coalition just to get a single sub. Also some places could be filled with contrabandists or mercenaries who are on neither side of the conflict, just work for money and would let you buy some supplies and maybe even let you help them with their dirty business.

**Comment by rico6822** [comment]
This could also be implemented in future development.

**Comment by BillCombs** [comment]
If talking about things like these, i think if that would get implemented, it would be a really far future, since that would take a lot of time and effort to make the whole factions with relationship systems, their events and especially whole subs controlled by AJ.

**Comment by rico6822** [comment]
It's A.I.

**Comment by BillCombs** [comment]
I know, just misspelled it.

**Comment by Regalis11** [comment]
I agree with BillCombs, the players should be able to choose whether they want to sell the artifacts and whatever other loot they find during the round. There could (and should) be a menu in the campaign view where you can see the your available items and sell them (and also #245).

Instead of directly giving money for killing monsters, the reward could be the loot you get from them (shells, teeth, fins or whatever) and again the players would be able to decide whether they want to use the loot themselves or sell it.

**Comment by rico6822** [comment]
Well this changes the thing. So the leader of coalition is not gonna be strict about it?

**Comment by BillCombs** [comment]
I think it makes sense for the leader of coalition to let you have and use the artifacts you get since they might help you in getting more artifacts for the coalition.

**Comment by Regalis11** [comment]
At this point when the lore is still quite vague and not much has been set in stone, you can choose whichever fits your headcanon:
1. According to Europan laws whoever salvages the artifacts can keep them.
2. Officially the artifacts should be delivered to the research institutes, but most submarine crews don't care because they're worth more in the black market.
3. What Bill said

**Comment by BillCombs** [comment]
> Officially the artifacts should be delivered to the research institutes, but most submarine crews don't care because they're worth more in the black market.

It would be actually pretty interesting to be able to either sell the loot on black market for a bigger price or to give it to the research stations in return for a smaller reward but perhaps also some good and powerful items or special blueprints for fabricator once you give enough artifacts for the research and it will be finished.
