### ISSUE TITLE
Override fail to override modded item

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#7328]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Currently trying to override another mod yet everytime I boot the game I get the error saying I have to override the item I already have overriden, I haven't heard anyone else having that kind of issue and no one seems to understand why I have it. EK mod author is impossible to contact by any means.

**Steps To Reproduce**
Place my mod (hazardous reactors) below EK Utilities, while I override both incendium fuel rod & fuel truck I still get the missing override error

**Version**
Windows release branch V 0.15.13.0 revision 4e66dd7b5d

**Additional information**
none

**Comment by Regalis11** [comment]
The mods higher up in the list take priority over the ones below them, so you should place "Hazardous Reactors" above "EK Utilities" to override the items correctly. I actually expect it to work the other way around too and thought it was bugged until I consulted other members of the dev team who are more familiar with the mod order logic - we definitely need to communicate it more clearly how the mod order works. I created a ticket about this in our private repo https://github.com/Regalis11/Barotrauma-development/issues/3002, but I'll close this one since it doesn't seem to be an actual bug.
