### ISSUE TITLE
Make Toughest Walls of Ruins being Only Moderately More Durable Than Alien Door- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#733]
It's kinda slightly paranormal those walls are having 100000 durability in the game files.

**Comment by BillCombs** [comment]
That adds extra difficulty by making you unable to just cut and go through the side. You have to go through their entrances to get their loot. That's what makes it more interesting.

I don't think it's too paranormal since we are talking about alien ruins with their powerful alien weapon technology and artifacts.

**Comment by Regalis11** [comment]
Yeah, they're intended to be nearly indestructible to force the players to enter the ruins instead of just cutting their way to the artifact.
