### ISSUE TITLE
Grenades and Grenade launchers are weak against Fractal Guardians

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7347]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fractal guardians takes explosions very well. Not sure if intentional. The only way to kill them is really just bullets and melee.

**Version**
0.15.13.0

**Comment by itchyOwl** [comment]
It's intentional that guardians are very resistant to fire, but not against explosions. I'll look into it.

**Comment by Ek-Videogames** [comment]
Some explosions deal 'explosiondamage' which is a damage-type affliction, but many from weapons only deal burn type 
which - with the reverted changes to how damage resistances work - means enemies take very little damage from burns.
I've found this damage-type inconsistency to be odd and may deserve its own ticket.

**Comment by itchyOwl** [comment]
Explosions should cause burns, but some explosions also cause burns. I'll check it out and and create a ticket if there's something wrong.

**Comment by itchyOwl** [comment]
It seems that there are two things affecting this: The division by 10 for the explosions cause the damage to be relatively low, because most of the limbs have protection against damage. I could remedy this by adding a special modifier for explosion damage. But another issue is that many explosions cause a lot of burns and not much explosion damage. Now that we have added burn damage modifiers to all monsters, the actual damage of explosions against monsters is probably relatively lower than it used to be, which is something we should adjust.

So this probably requires a separate ticket, like Ek-Videogames suggested. I'll discuss it with others.

**Comment by BlackMoons** [comment]
Explosions really need a better damage spread mechanism then 'apply to all limbs and divide by 10'

Like, apply to all limbs, divide by number of limbs actually damaged, with immune limbs counting for say, 0.2 of a limb. 

Or randomly apply full or near full strength to a few of the targeted limbs (Sorta a explosions are random bits of shrapnel damage effect).

**Comment by itchyOwl** [comment]
Fixed partially in Regalis11/Barotrauma-development#3489 and finally on endgame-prototyping, where guardians have been adjusted.

**Comment by Rokvach** [comment]
Tested, fractal guardians can still take 4-5 grenades until they die, which I think is fine. Not sure what type of changes has been made in the endgame-prototyping branch. But I think this is working correctly, closing.
