### ISSUE TITLE
Advanced wire system.

### ISSUE THREAD

**Issue by Baywatcher11** [Regalis11/Barotrauma#74]
Barotrauma could use more intense for engineers, wires would be a good deal.

1) Wires would break time to time because of: Too high output, being underwater for a long time.
They would look broken, and engineer would tape it with insulating tape which needs to be an item in game too, otherwise to change the wire.

If the wire is not fixed for some time, it would cause short-circuit and start fire. If it happens underwater it would deal electrical damage to surrounding people and stun them.

**Comment by Crystalwarrior** [comment]
ehhhh nooooo.
Junction boxes serve the exact same purpose tbh.

**Comment by Regalis11** [comment]
The engineers could definitely use some extra tasks but I'm not sure if this would be a good idea. Imagine a wire breaking in some complex logical circuit with dozens (or hundreds) of wires, or even worse, a wire that simply can't be reached by the players (e.g. runs inside the walls or along the ceiling in some tall room). Sure, we could force all the custom sub makers to lay out the wires in a way that all of them are reachable, but I honestly don't see the point because as Crystalwarrior said, junction boxes already serve this exact same purpose.

**Comment by Crystalwarrior** [comment]
Actually you know what, Engineers have enough "extra tasks", what concerns me more is the separation between engineers and mechanics.
Most of the time, if a mechanic is missing the sub can mostly function until the engines break or the reactor explodes. Engineer is responsible for extremely important things like junction boxes and navigation console, without which the submarine is completely unsustainable.

Perhaps give mechanics more cool and exclusive stuff to create? Let 'em make revolvers and bullets dammit!11
