### ISSUE TITLE
Make Respawn Shuttle Spawn Players With Scooters and Oxygen Tanks in Inventory- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#741]
Instead of having oxygen tank inside diving suit and scooter near suit it should be in player's inventory for a reason of people stealing oxygen tanks from suits to have more of it, causing rest of squad to suffocate.

In case of having modded non-vanilla characters with very large inventories having to spawn with those an oxygen tank and scooter will appear near them.

**Comment by thegrb93** [comment]
The same dilemma appears on any ship. It's up to the crew to cooperate to successfully return to the main ship. Making successful item distribution mandatory would take away the fun.

**Comment by NilanthAnimosus** [comment]
I did this in the past as a feature of my mod ONLY if the players spawned in an already flooded environment (Such as inside a flooded submarine, it would make the attempt to auto equip their starting diving suit) solely to aoid on-spawn pressure deaths. along with a minor spawn protection mechanic that could give timed immunity to suffocation and/or pressure / health and such configured from the host.

This wasn't the worst idea, but it has its place more towards on-submarine spawning, Otherwise players just spawn and die immediately racking up tens of corpses fairly quickly depending on spawn rates. (So I did it more as a lag prevention).

Actually spawning in your diving suit on the respawn without a disaster is a fairly quick way to waste your already limited oxygen supply, so I agree with the initial don't fix. I based it off water level of the hull the character is inside being above 70%.
