### ISSUE TITLE
Bots just walking into the wall

### ISSUE THREAD

**Issue by ThrownChair** [Regalis11/Barotrauma#7458]
![photo_2021-11-23_15-53-38](https://user-images.githubusercontent.com/94912691/143036843-675e553e-b12e-4cd8-be28-47d3b465e186.jpg)
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by itchyOwl** [comment]
Can happen for many reasons. So with the provided information, it's impossible to know what's the actual issue there.

**Comment by Ek-Videogames** [comment]
Was bot's node-following behavior changed to be more "lenient" in a recent update? 
I have noticed this happening alot more recently where bots will attempt to target an item (such as repairing a junction box) that is in a completely different room from them and - rather than finding a path along the existing node structure - they just try to take the shortest possible distance to the item which usually means trying to walk through a wall.

**Comment by itchyOwl** [comment]
Usually bots walking towards a wall has nothing to do with the pathing. It happens for example when they are stuck at something within an objective. They walk towards a door because they are not told to stop. So it's not a pathing issue, but a logic issue in the objectives. However, if the debugai view shows that the bot has a path (blue) and is targeting a node (purple), then it might be a pathing thing.

But to answer the question: it's possible. There has been some changes to the pathing too.

**Comment by itchyOwl** [comment]
Closing this one as there's not enough information to solve it.
