### ISSUE TITLE
Bots trying to go through ice blocks (in caves)

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#7469]
The bots should (and I think they did) ignore these ice blocks (when using the pathfinding), but apparently it's now broken.
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/76664782-60b3-41a0-b320-e261a65421d6)

Version:
Regalis11/Barotrauma-development@ce5e863 (dev)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@25cd6b4.

**Comment by Regalis11** [comment]
I did some further changes to this: the changes I did to the VoronoiCell.IsPointInside method in https://github.com/Regalis11/Barotrauma-development/commit/f0c6475033b042c6b8ed794141f4b00405d3a794 caused problems with cells that have been translated, and the fix above doesn't address those problems but works around them. The method should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/32b1751

**Comment by itchyOwl** [comment]
There was actually two issues. The first was that if any destructible wall was destroyed, the method could return true for a node, because it checked the position of the node only after that. This issue was probably present since the ruin update. The other issue was a recent one and like Regalis11 said, my fix was just a workaround.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
