### ISSUE TITLE
PVP Team-colored armband accessories for all crew members

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#75]
If you're part of the Coalition or Renegade, your character will have arm bands with the team color that are purely aesthetic. Think of them as an overlay to make team identification easier.

**Comment by Regalis11** [comment]
How about actually changing the looks of the opposing team's gear? If we did that and got rid of the red color on the opposing team's names, it wouldn't be a purely aesthetic change but also provide some gameplay value. Players would be able to disguise themselves as members of the opposing crew, and sneak in to kill unsuspecting enemies who haven't been attentive enough to check the names of the players in their team.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
