### ISSUE TITLE
Make it Possible to Use Unconscious Players or Their Corpses as Railgun Ammo- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#753]
WARNING: Unconcious players will receive physical damage upon launching. 

This feature can be used to either deal physical damage to monsters or help the crew reach further distances using railgun. Dead husks can also be put inside railgun loaders for it.

Having character restore consciousness results in them leave railgun loader, if they press "E".

**Comment by thegrb93** [comment]
Pretty funny idea, but I don't think a player would fit. Maybe if a bigger cannon gets added.

Also might be too easy to stun someone and rid the evidence with this.

**Comment by BillCombs** [comment]
Not sure if railguns work that way. If i remember correctly, the way railgun works is basically throwing a piece of metal using powered magnets. Human bodies are not that susceptible to magnets. You could try to stuff the corpse into a shell or a depth charge but i think it wouldn't fit(except if you dismember them and put each individual part in its own shell or depth charge). The only thing i can think of is putting a corpse inside a diving suit(because it's probably made of some metal) before stuffing it into a railgun loader. However, even if you manage to put live humans in there, they most likely wouldn't be able to survive that amount of force.

**Comment by rico6822** [comment]
That's what I name content Bill.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
