### ISSUE TITLE
NGrok support.

### ISSUE THREAD

**Issue by Id405** [Regalis11/Barotrauma#756]
Now I love me some NGrok alright. I throw that shit on pizza like pineapples. You know what I'm saying? But there is one big issue with barotrauma and NGrok, the public server browser will make clients join my ip and not the ngrok IP, AKA It dont work. My proposal for a solution is to be able to put what ip is reported to the master servers when hosting in game.

EDIT: Also maybe replace the UPNP option with use ngrok or something similar?
EDIT 2: Also maybe add pizza and pineapples to put on the pizza?

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
