### ISSUE TITLE
`impulsespread` doesn't seem to be working right

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7565]
The projectile property of `impulsespread` does not seem to create much velocity variance. 
Even turning the velocity spread to very high levels ( `impulsespread="0.99"` ) on a weapon like the canister shell only manages to create a few projectiles that are slightly slower in the group. Either there's a bug in the math itself or it feels like the RNG is **_very-heavily_** weighted to be always picking the median value, as opposed to a completely linear or 'bell-curve' relationship. Also I notice that no projectiles ever seem to go faster than the median-value even when I reduce the initial impulse amount so as to not clip the upper speed limit.

### Expected Behavior:
- launchimpulse=80
Impulsespread=0.25
Result: projectile velocity ranging from 60 to 100

- launchimpulse=50
Impulsespread=0.5
Result: projectile velocity ranging from 25 to 75

### Additional Info:
Setting impulse spread to 1 or greater produces interesting results, projectiles will occasionally fly backwards at the same speed as normal - but again, with very little variance of speed between shots, only now 'negative' velocity. No clue if this can narrow down the issue.

**Comment by Ek-Videogames** [comment]
Default railgun canister shell with a impulse variance of '30%' - appearing very uniform with only a few pellets being behind the main line of pellets which are all traveling at default velocity.
![image](https://user-images.githubusercontent.com/55356135/144193341-0f6f9a67-8630-41e5-bcd3-0673ca1d3492.png)

**Comment by Regalis11** [comment]
I did a bit of debugging on this, and at least in the case of the canister shell the problem seems to be that the pellets are already very close to the maximum physics body velocity (64 m/s), and the spread causes most of them to be clamped to the max value.

When I reduced the launch impulse, the problem seemed to go away.

There's a couple of things you haven't taken into account in the "expected results": the impulse value doesn't mean the projectile will travel at that velocity, it means that an [impulse](https://en.wikipedia.org/wiki/Impulse_(physics)) of that magnitude is applied to the physics body - the resulting velocity will depend on it's mass. You've also not taken the maximum velocity into account in the calculations. The actual results in this case for a canister shell pellet (which weighs 0.8 units) would be:

launchimpulse=80
Impulsespread=0.25
Result: projectile velocity ranging from 64 to 64

launchimpulse=50
Impulsespread=0.5
Result: projectile velocity ranging from 31 to 64 (with approximately half of the pellets going 64 m/s)

**Comment by Ek-Videogames** [comment]
However this does not seem to explain why some projectiles are impulsed backwards when impulsespread is >1.
If it is additive and increasing the impulse spread to higher numbers (thus more variance) worked then there is no issue.

### Am I misinterpreting something here?
`LaunchImpulse * (1 + Rand.Range(-ImpulseSpread, ImpulseSpread)`
the `*(1+` seems to imply that it is a multiplicative modifier not straight addition, the random spread is added/subtracted from 1 and then the impulse is multiplied by it, IE my previous examples:
Initial Impulse(50) * (1 + Random Impulse Range(-0.5 to 0.5) )
Evaluating the parenthesis: 50 * (0.5 to 1.5)
-then multiplied: 25 to 75

**Comment by Regalis11** [comment]
> However this does not seem to explain why some projectiles are impulsed backwards when impulsespread is >1.

1 essentially means the impulse can vary by more than 100% in either direction, which means it can go negative.
E.g. 
`Initial Impulse(50) * (1 + Random Impulse Range(-1.5 to 1.5) )`

Can result in an impulse of `50 * (1 - 1.5) = -25`

> Am I misinterpreting something here?

That part is correct. However, you need to take into account that the values you got aren't the final velocity: they're the _impulse_ applied to the body, and the final velocity depends on it's mass (and can further be affected by things like hydrodynamic drag).

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
