### ISSUE TITLE
Using the shuttle to escape the submarine and reach the target outpost.

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#76]
Should that end the round, or should it simply destroy the shuttle and "kill" everyone inside it while counting it as survival?
For example, let's say a traitor takes the nibbler and escapes to the outpost. That traitor will have a traitor victory as soon as he reaches the target outpost.
Another part to this is reaching the target outpost with the objective.

However, there's an issue to this, as the crew is essentially ditching the sub, which, in Campaign mode, would still be considered a game over I'd imagine.

Perhaps in the event of a sub-ditching in Campaign mode, the crew would be able to pay a large sum of credits (5k?) to buy a new sub? Perhaps even allowing them to change their sub to another one?

But even reaching the outpost in a diving suit should count as survival imo, ESPECIALLY for the traitors.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
