### ISSUE TITLE
Server crashing on level generation

### ISSUE THREAD

**Issue by ZealanL** [Regalis11/Barotrauma#760]
This is a recurring problem I have where occasionally when my server starts a new round, it will hit an exception and crash. 

Looking from the stacktrace, this seems to be due to Barotrauma.CaveGenerator.GeneratePolygons() creating invalid polygons, which causes FarseerPhysics to throw the exception.

Suspecting this could be due to me modifying the server, I set up a test vanilla server and played on it for a while, and encountered the same issue. I have to assume I am not the only one.

**Screenshot of error message box popup upon starting a new round:**
![code](https://user-images.githubusercontent.com/36944229/44883642-aafdb800-ac6c-11e8-803b-06919aa4f880.png)

**Comment by Regalis11** [comment]
Isn't this just a debug assertion failing, not an actual crash? I'm not sure if this causes any actual issues in-game. It happens when the level generation algorithm happens to create a triangle with a very low surface area, but these triangles are simply ignored (meaning that they don't have a physics body and aren't rendered).
