### ISSUE TITLE
You can grab a bot and operate a weapon at the same time

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7622]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was trying to force a bot off a periscope so I can use it without having to dismiss the bots order to use it. While grabbing and dragging the bot away from the periscope and then in a hurry selecting it, the bots inventory was rendered on the periscope view.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8fbfe783-a15c-4cbe-af96-55a4677afc85) 

**Steps To Reproduce**
Grab a bot and then use a periscope

**Version**
Unstable 0.15.18.0

**Comment by Regalis11** [comment]
There are some valid use cases for being able to select a character and an item at the same time (dragging someone while on ladders probably the most important one). I could also imagine it sometimes being useful to be able to check a periscope without letting go of someone you're dragging.

I think if we were to disable this, we'd need to think carefully which items can be selected while dragging someone and which can't, and even then I bet we'd get complains when someone notices they can't drag people back from wrecks with some mini-submersible steered via a periscope or something along those lines.

Since this is a minor annoyance at best, I'd rather not change it considering how many unintended side-effects it might have.
