### ISSUE TITLE
Portable pump - unrealistic max flow

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7638]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Sorry! That's the game plan or mistake?
The dimensions of the device do not match its performance!

**Description**
`Portable pump` has an unrealistic max flow. It exceeds the power of even the `biggest pump`!

**Steps To Reproduce**
![Image 001_23-44](https://user-images.githubusercontent.com/93348499/144763344-85680c75-f0f9-4c03-bdfa-03c5537a291c.png)

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No

**Comment by gerakis** [comment]
It only lasts 8 seconds though. Its already too weak.

**Comment by MaaiG** [comment]
In addition, the speed is set only after switching on. The energy is consumed immediately after turning on and before setting the speed! The actual time of useful work is reduced!

**Comment by Regalis11** [comment]
The intention of the very high pumping rate was to differentiate the portable pumps from the normal ones: they're a sort of emergency device that can be used to pump water out extremely fast, with the drawback that they drain batteries at an extremely high rate. I don't see how that's necessarily unrealistic (considering that it's not current-day technology): one could say it operates in a different way than the "normal" pumps, for example some kind of an ultra-high speed centrifugal pump.

> The energy is consumed immediately after turning on and before setting the speed!

This is a bug though, fixed in https://github.com/Regalis11/Barotrauma-development/commit/6458a4084a9e60d0947dc728b3cc4f8195b19e98

**Comment by MaaiG** [comment]
>  I don't see how that's necessarily unrealistic (considering that it's not current-day technology):

IMHO because it just begs the question: If advanced technology allows create such a portable small-sized device, then why is the same technology not used in "normal" pumps with a permanent power source?

* Could it be that this **efficiency is due** to the fact that the device is self damaged and full self-destructed during operation and is a **disposable device**?

You can install a pump that allows you not to worry about the integrity of the hull. Any water will be immediately removed from a given area. Even without walls.
I can install two large ballast pumps in the airlock and an open lock hatch will not result in flooding.
https://user-images.githubusercontent.com/93348499/144862555-2feab74d-4af7-426f-a439-25ba0a7523a4.mp4

> they're a sort of emergency device

Also, where does the water go? It can be attached to any wall. Are there valves everywhere? I don’t think so.
Where does water come from when a portable pump it in?

* If the portable pump is an **emergency device** and annihilates the water, then perhaps by destroying the water it **can produce oxygen**?

**Comment by gerakis** [comment]
Does it matter if its realistic? Its a video game.

**Comment by MaaiG** [comment]
There must be logic. Otherwise, the brain resists.

**Comment by Rokvach** [comment]
Tested, the issue of pump using up battery when its not pumping in/out is working correctly, closing.

**Comment by Dopamin3** [comment]
If its rate is 10x a normal pump, wouldn't it not be in use because it's inefficient? 

Any chance of getting a power terminal on them so we have some more potential for engineers? Like as an emergency thing that maybe would slow its portable battery drain?

 or recharge the batteries or something? 

Maybe it could just run them at a slower rate? :D
