### ISSUE TITLE
Destructible railguns.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#765]
Would be cool to be able to destroy the railguns of an enemy ship.

**Comment by KingChairis1** [comment]
Yes that would be a nice addition however that means creatures could destroy it too and then you wouldn't be able to kill them
And do you have a suggestion on how you could fix them?

**Comment by thegrb93** [comment]
Welder tool could fix them of course

**Comment by rico6822** [comment]
It would make sense if destructable railguns were highly resistant to be destroyed too, since they are meant for combat purposes.

**Comment by BillCombs** [comment]
Since railguns have got a collision box recently, perhaps they should also take damage whenever they get crashed between their submarine and the world? Though it would probably be really annoying if they broke every time the sub crashed, so the damage should probably be small enough to let the guns handle few average crashes.

**Comment by NilanthAnimosus** [comment]
Perhaps the creatures don't directly target the railguns (But could damage them) - Or allow items/walls to have damage modifiers (Or other methods of damage resistance/armour mechanics) and give railguns resistance to typical creature attacks, and they would have higher than wall health (At least 1500 health I'd say), which should take around 3-4 explosive railgun shells and survive a nuclear shell (Unless a direct strike to the turret).

Despite however nice it sounds to have breakable railguns, it would be a high irritation in gameplay if you needed to swim outside to fix them regularly. Either have part of the break internal to the submarine (Like a railgun control box) which connects to the gun, and breaks that part instead of the gun, or have them break infrequently. I really do not see multiplayer games pausing their submarine travel often to fix railguns constantly being a liked feature.

Its probably too late to add such a thing given it would require submarines to change their designs unless its optional, then most likely wouldn't use it. Either way, I think I'd go nuts personally in single or multiplayer if one had to swim outside regularly just to fix these things - especially while fish attack the submarine and theres no good weapon to fight them with (Harpoons really do not stop threshers at all and such, no strategy is in place like bait or such to prevent them targeting you either) outside a submarine while swimming.
