### ISSUE TITLE
Make Time of Ejecting Railgun's Ammo From Railgun Depending on Range of Railgun From The Loader- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#770]
However ammunition will immediately be removed from loader and a sound effect of it will be made.

**Comment by BillCombs** [comment]
Internet lag already makes timing shots hard enough. Plus, with that randomness of amount of delay being added(since the distance is different on most subs)), it might force players to have to learn how big is the delay on every new submarine they join, before they will be able to aim properly.
If you want your own submarine to be more realistic, i am pretty sure adding a delay component to the wire system would work.
