### ISSUE TITLE
Add Option to Submarine Editor to Set Object as Physical or Impassable- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#771]
Physical- Object cannot pass through walls, rocks and other stuff like that.

Impassable- No living creature can pass through it plus all things from above.

All of this can be used for objects outside submarines to prevent them from going through rocks.

**Comment by Regalis11** [comment]
Honestly I don't see the need for this. While there could be some rare situations where this is needed, I think it would cause more problems than it solves:
1. It's too easy to abuse. You could for example surround the sub with enormous background walls and add a collider to them.
2. It would be confusing. Now you can easily see/learn which structures are impassable, but if sub designers were able to change it freely, I'm willing to bet it would lead to situations like someone crashing a sub because they didn't know a normally decorative sprite had been changed to have a collider.
3. The gaps and leaks are designed to work with objects of a specific shape (= narrow rectangles). If anything could have a collider that can bump into the level walls, we'd most likely need to rethink the whole gap/hull logic and how wall damage works.
