### ISSUE TITLE
Ragdolls can be grabbed from behind walls or below floors

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#772]

**Comment by rico6822** [comment]
This thread is a potential duplicate.

**Comment by rico6822** [comment]
> Regalis11 reacted with confused emoji

I mean somebody could report this before.

**Comment by BillCombs** [comment]
>I mean somebody could report this before.

The same thing can be said for any other report thread. But it leaves you with as much uncertainty as you had before(It either has been reported before or has not. People still will have to look for the first reports similar to it to find that out). There is no real point of saying it if you don't know for sure, since you are pretty much just stating the obvious.
