### ISSUE TITLE
Beacon's reactor counts as a wrecked reactor

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#7762]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
To the "hazardous materials" talent, every beacon's reactor counts as a wrecked reactor, meaning you will get alien materials from every beacon an engineer with that talent visits.

**Version**
v0.15.20

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dea0a175b1bc9009573e018f6060f07576c0a9b3.

Note for testing: I refactored the submarine checks in talents to use one generic AbilityConditionItemInSubmarine condition instead of having separate conditions for different types of subs. This affects Hazardous Materials, Scavenger, Scrounger and Scrap Savant, so it'd be good to check that those are still functioning the same as before.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
