### ISSUE TITLE
Levers wont trigger set state on relay if located too far from relay

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7770]
Simply put, visible again here on stream.

I put a lever next to the circuit, flipped it, it works. 

I put the level 3 stories up, flipped it, no good. 

I added an OR gate closer to the upper Lever, that connects the outputs from the levers into a single wire to the relay for the pump and sig circuit and it just broke it into an ON state.

**Comment by Dopamin3** [comment]
13 hours ish on the ballast

**Comment by Dopamin3** [comment]
13:12:00 i put the lever closer again, pump works.

**Comment by Regalis11** [comment]
I think the reason for this is that the OR component you're using in the upper floor has no false output set, so it'll never turn off the pump.

**Comment by Dopamin3** [comment]
bro i fucking troubleshooted this circuit for 16 hours and fucked with that
level literally 30 fucking times and you think because there was 1 miswire
in the span of hours that the bug is closed?

**Comment by Dopamin3** [comment]
the wiring is in the game is a jenky fucking mess it is not closed, it is a
BUGGY MESS

**Comment by Dopamin3** [comment]
THE OR GATE WAS A SOLUTION TO THE BROKEN WIRING, NOT THE BUG.

I SAT THERE AND LITERALLY SHOWED THE BUG FOR LIKE AN HOUR, A LITERAL
KINDERGARTENER COULD SEE THAT IT IS BROKEN AS FUCK.


YOU ADD THE FUCKING LEVER, YOU CLICK IT, IT WORKS. YOU GO UPSTAIRS, ADD THE
LEVER, CLICK IT, IT DOESN'T RESET THE SIGNAL CIRCUIT.

THE WIRING IS BUGGY AS FUCK

**Comment by Regalis11** [comment]
I may have been a little hasty with closing this, but at least looking at the part you mentioned on the video (around 13 hour mark), the issues I saw seemed to have been caused by the other issue you reported https://github.com/Regalis11/Barotrauma/issues/7765. There could be something else wrong there too, but it's hard to say just by looking at the video. The fix was just released to the public version a moment ago, so I recommend updating the game and seeing if the problem's gone now.

I understand it's not your (or any of the players') job to help us diagnose issues or give us accurate step-by-step instructions on how to reproduce them, but unfortunately we don't always have the time and resources to spend a lot of time debugging issues that we don't have much information on (especially in cases like this where it's likely that the problems were caused by some other, already-fixed bug), so we may sometimes be a little too hasty to close issue reports like this. In this case for example, it's hard to say what's causing the problems without knowing how exactly the circuit controlling the relay is built. If you could send us a save or sub file where we can test this broken circuit though, I can take another shot at debugging this.

But in any case, I'm sorry for the all trouble you've had with the wiring, I understand that spending this much time troubleshooting the circuit must have been been enormously frustrating. :/

**Comment by Dopamin3** [comment]
Sorry pissed and cant get to this will look into responses later

**Comment by Dopamin3** [comment]
And tbh idk wtf that sketchy contract is that pops up now but i put
barotrauma in the recycling bin and im considering chargebacking the 8
dollars and supporter pack.
