### ISSUE TITLE
Sub editor - "Mirror Y" the same as "Mirror X"

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7789]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When object rotating 90 and 270 degrees the option "Mirror Y" (problem here) the same as option "Mirror X" (works well).

**Steps To Reproduce**
- Run "Sub editor"
- Take the `Oxygen Generator`
- Turn the oxygen generator 90 or 270 degrees
- Use the options to "Mirror X" and "Mirror Y"
- Same result!

**Version**
v0.15.21.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by MaaiG** [comment]
**v0.18.11.0 - Issue not fixed!**
Why is it closed?
This problem is not only with Oxygen Generator.

https://user-images.githubusercontent.com/93348499/174350987-c4a833c4-cdc5-4444-a9ef-bd4c248881b5.mp4

**Comment by NilanthAnimosus** [comment]
Can confirm this is still an issue in 0.18.13.0 as I experienced it when testing issue #9387

got this to occur with the heater decoration. the mirroring changes the rotation value instead of actually attempting to mirror the sprite. If the rotation value is 0.00 no change is made to the rotation value with either button.

It is also not obvious this behavior occurs as the rotation value does not update until you deselect and select the entity again.

**Comment by MaaiG** [comment]
0.19.14.0 - The axis-X still works wrong! The axis-Y seems to work properly...

https://user-images.githubusercontent.com/93348499/199253037-8c907653-7fbb-43ff-865a-e83cb8d077e5.mp4

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e3d1fae718c8ecb59381733a2239919e3ba521fd.

**Comment by Regalis11** [comment]
Tested, no issues found. Closing.
