### ISSUE TITLE
Moloch Shell Fragment and Mudraptor Shell got swapped

### ISSUE THREAD

**Issue by idogadol** [Regalis11/Barotrauma#7813]
- [✔️] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After the holiday update, the Mudraptor Shell (shield) and Moloch Shell Fragment (armour) were swapped, with the armours being unequipped and turning into shields, and Mudraptor Shell getting the appearance of the Moloch Shell Fragment and becoming equippable.

**Steps To Reproduce**
Spawn either a Mudraptor Shell or a Moloch Shell Fragment.

**Version**
v0.15.22.1, Windows 10

**Additional information**
My friends and I lost our Moloch Shell Fragment armour in the middle of our campaign because it turned into a shield we can not equip, we only have a single Mudraptor Shell, meaning we now possess several shields and one set of alien armour.

**Comment by Regalis11** [comment]
This is intentional: the moloch shell fragment was actually supposed to be the shield, and the mudraptor shell the armor (if you look carefully, you can see that the mudraptor shell reuses parts of the actual mudraptor's shell, and the moloch shell is clearly the same color as molochs). We'd gotten them mixed up at some point, and fix the issue in v0.15.21.0.
