### ISSUE TITLE
suggestion: making stairs modifiable height by using a customization setting for the number of steps 

### ISSUE THREAD

**Issue by Cosmo213** [Regalis11/Barotrauma#782]
usually, you have to align the sub you make to the height of stairs, setting floors far apart enough to do that. however, if you were to allow stairs to be customized by the amount of steps they have, it would allow for more customization of submarine design. obviously, this isn't really a needed thing, but it would allow for more diverse submarines. thanks for reading, have a good day.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
