### ISSUE TITLE
Wrong decimal separator in delay's set_delay wiring 

### ISSUE THREAD

**Issue by Smieszkokoleszko** [Regalis11/Barotrauma#7837]
- [Tried] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you define delay in delay block in editor everything works fine - `4.5` means `4.5`. But when sending to delay's `set_delay` input number has to be `4,5`, when sending `4.5` it doesn't work. Because of that it is unusable with with any calculations. 

**Steps To Reproduce**
Place delay block, connect signal `4.5` and `4,5` compare result.

**Version**
v0.15.22.1 - WIN10

**Comment by MaaiG** [comment]
I'll add. In my country, the decimal separator is a comma! As in most countries! Please, take that into account. Otherwise, it’s a mistake. 
**3,141 - What is that? Pi or Three thousand one hundred forty-one? I’m sure it’s Pi!**

![DecimalSeparator svg (1)](https://user-images.githubusercontent.com/93348499/146645572-c490fbb8-f987-4a7f-863d-44a9eb21dda3.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
