### ISSUE TITLE
Allow throwables to vary their throw distance based off the time the throw key is held.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#789]
It would be nice if throwables could be nearly dropped, thrown great distances or rolled a small distance.

It doesn't seem too far fetched of a feature, multiplying the throw distance to time held and making it take a second or so to lerp towards that max throw distance/force (Not sure on network syncing but it should be fine I think with how inputs are handled).

Also allows you to begin throwing and in theory, cancel the throw by letting go of the aim key before letting go of the attack key, letting you start charging your throw distance then cancel the action.

If a target starts getting too close, you can let go earlier and such, if their running away, chase and keep charging the throw. Just feels more dynamic/fluid to have such a function (Assuming it does not already exist in dev).

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
