### ISSUE TITLE
Talent: Scrounger - works on 'impossible' items like suit lockers & batteries

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7892]
In a similar vein to issue #7762 , the "scrounger" perk does discriminate between different types of containers, leading to the somewhat comical behavior of pieces of scrap popping out when you interact with any kind of interactable container even if the container itself is not capable of holding normal items. 
- Diving suit lockers, reactors, batteries / charging-docks, weapon holders, even fire extinguisher brackets!

**Comment by gerakis** [comment]
I thought they patched this out. This was a real nerf to that tree, as you get barely a quarter of the scrap you used to. Also being able to harvest scrap from batteries and racks and things always felt very "mechanical" to me; it fit the character pretty well.

**Comment by Regalis11** [comment]
This should have been fixed in the latest patch (commit https://github.com/Regalis11/Barotrauma-development/commit/41f82c189f7a9a5fef16122fcec06bdb00031eb3). The talent now checks that the container has the tag "container" and only spawns the items if they can be put inside it.

I gave this a quick test in both single player and multiplayer and couldn't repro the issue. Are you using some kind of mods? Which version did the bug happen in?
