### ISSUE TITLE
All guns linked to all loaders leads to bugged upgrade merchant

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7916]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you make a custom sub where more than one gun is linked to more than one loader, the upgrade merchant has some kind of meltdown. See pic related.

**Steps To Reproduce**
Open the Berilia in sub editor. Link all the guns and the hardpoint to all the loaders. (4 loaders per gun, so 16 total links) Try to visit the upgrade merchant during a campaign with it.

**Version**
0.15.22 Windows, no mods, singleplayer campaign

**Additional information**
![more than one linked gun](https://user-images.githubusercontent.com/16128947/147301936-91f7cdb7-e128-4b75-80b9-20853991da1d.png)

**Comment by Regalis11** [comment]
This isn't actually a bug. As of the latest update, [turrets linked to the same loader can't be swapped individually](https://github.com/regalis11/barotrauma/issues/6328), because it'd cause some of them to be linked to an incorrect type of loader. If you link all of them to all the loaders, you need to swap all of them in one go.
