### ISSUE TITLE
Items can be placed in non-interactable areas

### ISSUE THREAD

**Issue by thebuttsatisfier** [Regalis11/Barotrauma#7919]
- [*] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A portable pump can be placed in areas of the submarine where they cannot be interacted with after placement.

**Steps To Reproduce**
- Put a portable pump in your inventory
- Place it near an area where it appears that the pump can clip through solid walls or floors
- Attempt to interact with the pump with your mouse

**Version**
v0.15.22.1
Windows 10 64-bit

**Additional information**
I found this bug by accidentally placing a portable pump in the very bottom floor of the Humpback's "lower mid" section. After I placed it partially clipped through the sub I couldn't interact with it to pick it back up.

![Screenshot 2021-12-23 212717](https://user-images.githubusercontent.com/96389585/147320229-f6cd1b87-7db0-406d-955f-ab45b59e3e97.png)

**Comment by Regalis11** [comment]
Changed the title, since this applies to all items that can be attached to walls, not just portable pumps

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/3f874d71a8cdc82d1d16314abdd6ae91f7e42098

Appears to work well in most areas such as flat walls, doors, areas you cannot reach and anything outside of wrench range. however on a Humpback submarine I noticed I could place it into a spot I could not retrieve with a wrench indicating some further work could be done (Likely due to sloped/curved structure pieces)?

Note I placed a relay in the rough area marked in the image below and could no longer select it.

![image](https://user-images.githubusercontent.com/29177976/194864019-f7d7fb37-3ba2-4a73-9f6a-46a82ecc88ba.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/71b39c123d73612a052cf9a1585a3d28890cb9c0

> Fixed items still being attachable inside walls in some cases (sloped walls in particular). Happened because we first did the raycast to find a position outside the wall and then rounded the position to the grid, which in some cases placed it inside a wall.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/56ddb502c58d91fea177e4f4c9b9c57bb12e7c8c, no issues found, closing.

Notes: Anywhere an attachable item could be placed that intersects a wall partially, can easily be removed by wrench. I could not find in any situation/shape where the item was no longer reachable via a wrench.
