### ISSUE TITLE
Humans Can Attack With Their Fists- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#795]
They do low damage doing so. Characters with weapons skill 30 or higher have shorter cooldown on it and they do more damage. Characters hitting an active husk with their fists in front of husk's head are taking damage exact to being attacked by a husk and they are infected with it's eggs. Received damage depends on if the player have hit an ordinary husk or a crew member taken over by it.

**Comment by BillCombs** [comment]
I feel like it would take too long to kill somebody with just fists for this to be fun or useful. Any other weapon would win over you unless your enemy had lowered hp. The only point i see in it is if hitting somebody in the head would cause a short stun so you could use it as a last resort kind of self defense(not trying to kill the guy, but rather hit him and run for cover or to get some actual weapon).

Though it would probably be kind of fun to watch a drunk fist fight between crew members.

I wonder if the game could have some kind of consciousness mechanic. For example, if you get beaten in the head with a melee, you don't drop instantly, but you lose some of your consciousness, which would cause you to get knocked unconscious if you were hit enough times before your consciousness recovered. Some chemicals could be lowering it, or lowering max consciousness, so you would be easier to knock out. You could also make it so you lose some consciousness if you get hit by explosion or get headshot by a revolver, though not sure if it would be fun to have that whole mechanic in total. But it would make fists and other melee more useful and give a bigger chance to arrest the attacker instead of killing him(though it would also help in killing the guy, if that was your intention).

**Comment by thegrb93** [comment]
Yeah, you do get stunned from crowbar hits sometimes for a moment. I think fists would be fun. Not a fan of the husk mechanic he mentioned tho.

**Comment by BillCombs** [comment]
Husk mechanic would probably be unnecessary since husks can just manually attack the incoming fist.

**Comment by rico6822** [comment]
At least people won't be defenseless in case of having no weapons.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
