### ISSUE TITLE
AI security officer attacking crewmember persistently after friendly fire and it really needs to change

### ISSUE THREAD

**Issue by Luckspeare** [Regalis11/Barotrauma#7956]
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Security officers are supposed to defend crewmembers and arrest wrongdoers, I get it.  But in SP games, friendly fire happens and the security officer won't stop attacking the crewmember 10 minutes later.  It's very disconcerting to have your security officer refusing to lay off attacking a crewmember (I was controlling him to make him walk away, but it would only work so long as I was controlling him).

**Steps To Reproduce**
Accidentally hit a friendly in a firefight, I suppose, enough to trigger the security guard's hostility.  I was definitely not doing it on purpose -- was outside the sub in a crossfire with a coilgun, my medic following me with an SMG, and a couple of crawlers.

**Version**
Current version as of 2021-12-29.

**Additional information**
I understand the "ragdoll yourself and let him cuff you" solution, but this is frustrating and annoying and really needs to be handled better.  AI crew in a SP game should under no circumstances attack each other, just for gameplay's sake, but if they do, there should definitely be a pretty short time limit on it.

As it stands, to me this sort of nonsensical behavior rises to the level of definite bug, and I just saw a 20-day old thread where someone was complaining about this, and the answerers told him the best solution to this problem, aside from ragdolling so they cuff you and accomplish their arrest order, is to never use AI security officers, because they're constantly liable to do this.

**Comment by Luckspeare** [comment]
https://www.reddit.com/r/Barotrauma/comments/rczm6d/is_there_a_way_to_stop_your_bot_security_officers/

**Comment by itchyOwl** [comment]
Initially all the bots did retaliate when they were attacked. At some point it was changed so that security officers first attempt to arrest, and then kill if the aggression continues. The bots with other jobs just try to run away, defending themselves if they can. And I think this line of behavior is ok in multiplayer and for NPCs. But it feels weird in single player mode where you wouldn't expect the bots (that you can control) to act against you. I agree that we have to do something on it.

**Comment by itchyOwl** [comment]
Changed the friendly crew behavior in single player so that they shouldn't ever retaliate/attack/arrest the player: Regalis11/Barotrauma-development@abe31ee. In multiplayer and for the other NPCs the behaviors should remain as they were.

**Comment by Oukido** [comment]
Here's a suggestion for npc behavior in multiplayer:
Since it is not always clear if the actions of a player are malicious or in the best interest of the team (cut open a wall to rewire something, heal with abx...) there should be multiple stages of response from the bots. For example:

Escalation 1: Bots warn the player over chat that whatever he is doing is considered malicious
Escalation 2: Bots equip weapons and handcuffs and ready for retaliation
Escalation 3: Bots engage.

Each escalation stage has a threshold that has to be reached and that also cools down at a certain rate, which is even faster if the player has been released from handcuffs (since this should be an intentional decision of another player)

I also suggest a "free of retaliation" mode in which the player can do whatever but also sends a chat message and spawns an icon that shows everyone on the sub that the player has entered this mode and where he/she is.
(This mode is not meant for normal traitor gameplay so it is not meant to be stealthy)

**Comment by Regalis11** [comment]
Moving this back from QA. The changes seem to be causing problems in multiplayer: bots now react to any amount of damage, e.g. accidentally damaging them with a welding tool

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@fed6bdd.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
