### ISSUE TITLE
Rubberbanding and desyncing issues

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7962]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Constant rubberbanding / re/desyncing  issues in multiplayer, as both host and client

Fabricator drops item from player inventory / doesn't appear to remove item from player inventory until fabrication is done.

Fabricator "create" button doesn't start creation ( possible related #7801 

Rubberbanding evident through closing of doors

Ice rocks desyncing positions

**Steps To Reproduce**
Move around and do things in multiplayer, as host or as client

**Version**

0.15.22.3 stable

**Additional information**
Videos + youtube video attached:

Fabricating a harpoon where the steel bar drops from inventory to ground, getting rubberbanded at doors. Player is the host.

https://user-images.githubusercontent.com/5103517/147803542-f1911e7b-8837-4aa1-aead-1f47ba5ff5e3.mp4

Looking at an ice rock that the submarine auto-piloted into (go to destination). The rock appears to move client-side but I think server-side the rock isn't moving? probably? Client is also host.

https://user-images.githubusercontent.com/5103517/147803545-19964f0e-ffa4-4cc6-9f5f-574ef8b6756b.mp4

Difficulty using fabrictor, moving ingredients seems to remedy this (happens frequently tbh). Client is not host, host is ~200ms ping in europe. Massive desync while using scooter/swimming.

https://user-images.githubusercontent.com/5103517/147804007-e0fea00d-8858-44cf-ad91-971b508a5a09.mp4

**Comment by Regalis11** [comment]
The fabricator issues are most likely related to https://github.com/Regalis11/Barotrauma/issues/7914

**Comment by Regalis11** [comment]
This could possibly be explained by the server running slower than the clients, since the rock and the player using the scooter seem to rubberband back to where they were a moment ago.

I added some additional performance indicators in https://github.com/Regalis11/Barotrauma-development/commit/0af2bbf0b54ced286e30d86567e77eca052c6e4a that should make situations like this easier to diagnose. The physics update rate (which should be a fixed 60 steps per second) is shown below the FPS counter in single player, and the server now displays warnings if it drops below 60. The warnings are also visible in the clients' debug consoles.

**Comment by Rokvach** [comment]
Added diagnostics are working correctly, there hasn't been notable rubberbanding and zero cases of desyncs in Unstable, but that might just be because of the clients connection to the host has been reliable. But closing as there's been some improvements towards this and no further info to test. Closing.
