### ISSUE TITLE
Bug when trying to select campaign on my server.

### ISSUE THREAD

**Issue by Gurkk80** [Regalis11/Barotrauma#7982]
**Description**
Whenever I attempt to select campaign on my server the game loads for some seconds then crashes. Before my most recent attempt it would give me an error:

**Steps To Reproduce**
1. Start Server
2. Click on Campaign
3. Game Loads For A Couple Seconds Then Crashes Or Gives An Error.

**Version**
Game Version: 0.15.22.1 OS: Windows

**Additional information**
Before the crash I was getting the attached error message. Also I attached the crash report.
![Screenshot 2022-01-01 234156](https://user-images.githubusercontent.com/74194879/148004245-5738d0ee-fc5f-42d4-b5f9-8a76b0f98b6b.png)
[crashreport (33).log](https://github.com/Regalis11/Barotrauma/files/7805139/crashreport.33.log)

**Comment by Regalis11** [comment]
The error seems to happen because the client is trying to display a save file with no file path. I'm not sure how that can happen, but I added a null check that should hopefully fix this in https://github.com/Regalis11/Barotrauma-development/commit/f459170dfcb6b144e7414f231c97790f7d1d53e3 (commit in our private repo)

**Comment by Rokvach** [comment]
There hasn't been any sightings of this happening in the Unstable since the fix released there, seems to be working correctly. Closing.
