### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#80]
Hard-coded texts should be gotten rid of where possible/reasonable in order to make modding and translating the game easier.

It's also too difficult to change texts in item names now - a bunch of things (in crew AI for example) depend on the names. We should switch to using item identifiers instead of the display names wherever possible. It should also be possible to translate things without causing content package mismatches, now changing things like item or monster names prevents from playing on servers without the translation.

There are still a bunch of hard-coded texts here and there, please report them here. Other types of issues encountered while translating the game are also welcome here.

TODO (things that can't yet be translated at all or without modifying the content package):
- [x] Job names & descriptions
- [x] Mission names & descriptions
- [x] NPC conversations
- [x] Loading screen tips
- [x] Entity categories
- [x] Affliction names and descriptions
- [x] InputType names
- [x] Skill names
- [x] Crew order names
- [x] Client permission names
- [x] Mission type names 
- [x] Game mode names 
- [x] Item pick/select messages ("Rewire [screwdriver]", "Unauthorized access" etc)

**Comment by Crystalwarrior** [comment]
Even more the reason to do this with this being a thing:
http://undertowgames.com/forum/viewtopic.php?f=20&t=7733

Heck I might take a crack at it.

**Comment by Regalis11** [comment]
@NilanthAnimosus The solution I've been thinking is along the same lines: including both the display name and the identifier in the item configs, and then allow defining identifier-based translations in an external file (not just the name but description, UI messages and such). The display name and other strings defined in the original config file would be used if no translation is found.

I believe we could deal with mods by making it possible to define multiple translation files. Then it wouldn't be just up to the translator to support mods, but modders could also include a translation file in the mod itself.

**Comment by Regalis11** [comment]
@rico6822 Was the server also using the translation? The message at the end of a round comes directly from the server, so it won't be translated at the client's side.

This is actually something I've also been wondering about - to what extent should the messages from the servers be translated. I'm leaning towards keeping them as-is whenever possible, because it makes server-side customization easier.

**Comment by NilanthAnimosus** [comment]
I have not even attempted translating my own mod, server-side translation in of itself being a nightmare concept for me - I've no way to know the language of a joining player. Perhaps these multiple language files could have a defined language string (IE. EN. FR. RU etc - codes for the language to use) selectable as an option and thus sync able with the server? then assumably if the server has similar translation files it may simply pull from the relevant file?

It's bad enough all my text is hard coded, but this would be a considerable start for the base game. content packs could then just include the relevant translation files then as you suggested - multiple would be nice.

**Comment by NilanthAnimosus** [comment]
It may be possible to mix the two methods if you retain the ability to send a written message instead of relying entirely on the tags, but it would be nightmarish still (if not well, impossible) for me to server-side translate, and I've no methods to give the clients required files when they do not have the mod installed (Which is about 99.8% of all barotrauma's playerbase, only the hosts really use it).

If my mod becomes incompatible I will likely just remove/redesign aspects to the newer barotrauma, parts of it (but not all of it as a lot doesn't really suit the vanilla game) could probably use being part of the vanilla game anyways in a better designed manner.

A lot of the texts used by my mod are typically things spamming the chat with MOTD server join lines, messages for round starts into the chat based on the mission/traitor reminder and such. Theres even ones for commands like being frozen (Denied any sense of input/control via server command beyond talking).

the respawn shuttles have timed messages too and kill messages. There is quite a bit of text but most of it is written by the host of the server via XML documents at the moment.

Thing is these could be replaced by vanilla implementations mostly of similar features. such as a less skippable MOTD popup listing a servers rules and welcome message.

Less skippable traitor and mission popups so its more of a required read as so many players honestly mash the ok then ask what the mission is or don't know their targets (Along with including target information into the info panel - its seriously silly you cannot check this mid-round)

Generally my text from my mod is essentially quality of life or information based. if it winds up not being an option for server-side modding to send messages I would likely just start making fake chat messages over server messages and such - to less translated methods as a workaround (I do a lot of work arounds actually - for instance I use the "Error" chatmessage type for admin messages).
