### ISSUE TITLE
Game crash many time pls help.

### ISSUE THREAD

**Issue by boyworayot** [Regalis11/Barotrauma#8000]
**Description**
Game crash many time pls help.

**Additional information**

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7833618/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7833614/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/7833615/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/7833616/crashreport.4.log)
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/7833617/crashreport.5.log)

**Comment by boyworayot** [comment]
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/7835578/crashreport.6.log)
crash again playing is crash .

**Comment by boyworayot** [comment]
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/7840666/crashreport.7.log)
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/7840668/crashreport.8.log)

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I can't think of what could be causing this off the top of my head. The crash reports seem to indicate that the crashes are happening due to a bunch of different, unrelated reasons, and they're occurring in pretty bizarre places: the game is for example somehow failing to find certain things (sprites, objects related to rendering) that shouldn't be missing in any situation.

Have you been able to play the game without crashing before? I wonder if this could have something to do with your PC, perhaps running out of memory or something - could you post your system specs here?

I'm sorry for the trouble and not being able to offer more help on this for the time being, I hope we can figure out what's causing this asap!

**Comment by boyworayot** [comment]
My spec
![01](https://user-images.githubusercontent.com/11890121/149158767-65b297d7-4d80-4bf1-a093-2168566976f2.PNG)
![02](https://user-images.githubusercontent.com/11890121/149158770-7f7491c4-dc3d-4b9e-bf49-aa4b0a10b3ee.PNG)
![03](https://user-images.githubusercontent.com/11890121/149158772-e51b5edf-b6f1-435a-b341-07a0ca80758e.PNG)
![04](https://user-images.githubusercontent.com/11890121/149158773-e22ede89-0033-4407-b983-e636bca9bdf7.PNG)

Other games I don't have a problem. Normally I play APEX GTFO and I have never had a problem with the game crashing.
Or maybe it's because I have windows 11 pro.
Now I'm reinstalling Windows 10. I'll try to play again to see if it's okay.

**Comment by Regalis11** [comment]
No known steps to repro, closing
