### ISSUE TITLE
Workshop update text gets smaller in 2nd prompt and after

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8013]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the font size in the 2nd and after prompt is smaller than the first

https://user-images.githubusercontent.com/5103517/149014958-a1f1329b-59c6-4b6b-839d-c1e96351d0c5.mp4

**Steps To Reproduce**
1. 2+ pages of workshop item updates

**Version**
0.15.22.1

**Additional information**

**Comment by Regalis11** [comment]
In your clip the font size is exactly the same in all prompts? 
![image](https://user-images.githubusercontent.com/14351070/149110788-8458a609-7a84-415f-bc79-bee1148fa422.png)

**Comment by Tsunder** [comment]
The first prompt vs the second prompt

the second and after are the same size

![image](https://user-images.githubusercontent.com/5103517/149191400-53f9b0e7-f40b-407b-9d3f-daf593fd1836.png)

**Comment by Regalis11** [comment]
Ah, thanks! 

What's happening here is that the second prompt switches to a different font due to the Chinese symbols (which aren't available in the default font), and the characters in that font are of slightly different size despite the same font size being used. I would consider this such a low prio issue that I think we can close ignore it.
