### ISSUE TITLE
Add a windowed hatch

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#802]
Windowed doors are pretty useful, so why not have a windowed hatch as well? Many times i have seen players open hatches that led inside flooded rooms, because they did not know that the rooms were flooded, which then often caused flooding in the rest of the submarine. Or players letting creatures such as crawlers or husks inside because they did not know that something was behind the hatch. A windowed hatch would help with that problem. (At the moment you can kind of get information about flooding and nearby life using detectors and light components but that is a bit bulky and does not always fit the style of some submarines)

Of course that makes the game easier, but that's why we have submarines with different kinds of difficulties.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
