### ISSUE TITLE
Add old submarine wrecks as randomly-generated parts of a level

### ISSUE THREAD

**Issue by BarryTrauma** [Regalis11/Barotrauma#807]
(this may have been already suggested, please merge or close as needed)

I think it would be really neat to find submarine wrecks on some flat surfaces of a level. These could contain monsters, artifacts, or various materials that could come in handy to a crew in need. Some could be booby-trapped with explosives, some could be husk or mantis-infested, some could have automated railgun defenses, hell, one could be a crashed shuttle filled to the brim with clown apparel and bike horns. There's a lot of room for creativity here.

Quick disclaimer: I'm not a programmer, I don't understand how this game works on the inside, and I don't know how doable this is. I just think it'd be an interesting feature to have in the final game.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
