### ISSUE TITLE
Failed to spawn item ruintoxins 

### ISSUE THREAD

**Issue by pie-** [Regalis11/Barotrauma#8083]
- [x] I have searched the issue tracker to check if the issue has already been reported.

It sounds similar to #6234, but not sure if it's the same.

**Description**
When arriving at New Iapetus and selecting the next destination the game gives the error "Failed to spawn item ruintoxins {ID 9334 is taken by Shipwreck ID card}"
See the screenshots. 
It happened while playing multiplayer.

**Steps To Reproduce**
Load the attached save, go to the end of the level. Click on the next location and click start.

**Version**
v0.15.23.0
Using windows 10

![1](https://user-images.githubusercontent.com/6615782/150659499-41adcf2f-daf3-404e-9100-ec291f69917a.jpg)
![2](https://user-images.githubusercontent.com/6615782/150659498-b06a35ec-8cb7-427b-a39e-85a516b47fcb.jpg)

[barosave.zip](https://github.com/Regalis11/Barotrauma/files/7919510/barosave.zip)

**Comment by Regalis11** [comment]
Hmm, I unfortunately wasn't able to reproduce this, although I did run into another issue, a crash when trying to save the ballast flora in the drone. That one should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0bfe305.

I wonder if this could have something to do with the items in the players' inventories. If you could send us the CharacterData file in addition to the campaign save, I could give that a test.

Thanks and sorry for the trouble!

**Comment by pie-** [comment]
Here is the CharacterData file
[t_CharacterData.zip](https://github.com/Regalis11/Barotrauma/files/7933439/t_CharacterData.zip)

Let me know if I can do anything to help.

**Comment by Regalis11** [comment]
No known steps to repro, closing
