### ISSUE TITLE
Add an artifact mimic kind of creature

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#812]
Currently collecting random artifacts from the bottom of the ocean feels a bit like a routine and is not risky at all, if you have killed all nearby creatures before getting out of the submarine, it's just a boring trip to the artifact and back to the submarine. I think there should be some kind of adventure on that trip.

Artifact mimics might be good for this. Imagine some kind of alien parasite surrounding the artifact and nourishing on its energy. Once a player gets too close or attacks it, it disconnects from the artifact and begins to defend its territory(it shouldn't be too hard to kill, it's main power is element of surprise). I feel like that creature would add a thrill to the trip; instead of just brainlessly swimming from submarine to the artifact and back, you will have to stay on guard, and be ready to fight a creature, if it appears to be one(or just hope it's not, if you have no weapons, that would be even more thrilling). It would also probably give more use to depth charges, as players might use them to check the artifact on the ocean's bottom for parasites.

Some players might not enjoy having that kind of threat, but i feel like since you are adding different difficulties, they could be just turned off at lower ones for a safer trip.

I feel like the type of enemy that is waiting for its victim to come close instead of immediately attacking is the one this game is missing. Right now you don't have to be on guard that much as all enemies pretty much show themselves to you as soon as they noticed you. There should be some that can sneak up on the player.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
