### ISSUE TITLE
Inconsistent damage from explosions

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8122]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
To start with, damage seems to multiply on each limb that the explosion reaches instead of dividing, so for example:
used "explosion 200 100 50 0 0 0" on leucocyte (1 limb, 25 health)
![image](https://user-images.githubusercontent.com/55637865/151683829-3856d42c-6f4b-48bd-9d58-5ccfb707edd0.png)

used "explosion 200 100 50 0 0 0" on mudraptor (27~ limbs, 120 health)
![image](https://user-images.githubusercontent.com/55637865/151683871-a4bbf65a-7657-4074-bde4-cf5048709822.png)

Then there's the damage fall off, which is so incredibly high that most explosions deal even less than half than they're supposed to even when the target is right next to the explosion, making even nuclear explosives useless against swarms. For some reason it works correctly for structures, tho.

(nuclear shell)
![image](https://user-images.githubusercontent.com/55637865/151684108-d0a5ce17-e77c-4a0e-b7b1-a0b4d2e18104.png)

explosions straight up not deal the damage they're supposed to, i hit directly on this moloch's armor-less brain with a nuke, which is 250 impact + 900 explosion damage if the moloch has 1250 health, and takes 50% more damage on the brain, this moloch should've taken 375 impact damage and 1350 explosion damage, dying instantly, but instead it only dealt half of its health
![image](https://user-images.githubusercontent.com/55637865/151684333-072dd448-98e9-475a-b3dc-0d0e1894ff34.png)

and i almost forgot to mention that a lot of creatures use "explosions" as their attack

**Version**
any

**Comment by Udrakan** [comment]
This is a fundamental mechanic and I hope it gets adressed.

**Comment by Regalis11** [comment]
> To start with, damage seems to multiply on each limb that the explosion reaches instead of dividing

This is actually intentional: we used to divide the damage per the number of limbs, but that lead to even weirder results: for example, a moloch which has a ton of limbs would take a minuscule amount of damage if the explosion only hits one or two limbs.

>explosions straight up not deal the damage they're supposed to,

That's not really the case. For example the nuclear shell you mentioned is not "supposed to" do 900 explosion damage: that's just a theoretical value it _could_ do if the target's limbs were all close to the center of the explosion.

I agree that the explosion logic could use some improvements, but in my opinion there's no reason to change it so that the affliction value defined in xml is the absolute amount of damage it does. If the results of the explosion seem strange in-game (like the difference between the leucocyte and the mudraptor), that's something that should be addressed, but the average player is not aware of the values defined in xml and imo we shouldn't change the damage formula just to make those values more intuitive to someone who is not aware of how the formula works.

**Comment by itchyOwl** [comment]
I agree that it's confusing, but I'm not sure if we should change the way it works right now. Something to consider while doing a balance pass for the explosions though...

**Comment by Regalis11** [comment]
Something we could consider though is dividing the amount of damage by the number of limbs that are within the explosion's range?

**Comment by LePiromano** [comment]
I started a discussion on what me and a few other people in the discord thought would be appropiate for an explosion rework, if you ever have time for it :D

https://github.com/Regalis11/Barotrauma/discussions/8144

**Comment by Ek-Videogames** [comment]
Past multiplicative damage was changed in order to 'fix' the problem where larger multi-limb creatures would be essentially entirely immune to explosions. ( Because only a few limbs would be within' AOE but damage would be divided by a large amount )

Also tangentially related to this issue is that some monsters use 'breakable armor' which is vulnerable to explosions (mudraptors for example are basically allergic to explosive coilgun ammo) - while other monsters use the older flat damage resistance behavior ( bonethreshers, hammerheads, etc ) and will take 'normal' or much less damage from explosions.

**Comment by BlackMoons** [comment]
Maybe explosion damage should be reduced to only a few of the most vulnerable limbs it hits, even if it hits a large number of them? This would let the damage be divided and still strong enough to kill limbs and get through armor?

Or you could also randomize the division of damage, biased towards vulnerable parts. random is never even, so some limbs will 'die' early from damage.

**Comment by Rokvach** [comment]
Tested, went through all the examples shown above and didn't notice any issues, can be merged.
