### ISSUE TITLE
[Unstable] Typo + Visual Glitch

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8167]
- [Yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1.) Veteran's Cap removes/ignores character's hair when worn. 
Every hairstyle looks like a shaved head when wearing the veterans cap, which doesnt make sense. Other head accessories do not have this issue. (apologies for the poor screenshot quality)
Before: 
![image](https://user-images.githubusercontent.com/91236493/152071856-0614908b-9456-410f-9271-7db24f17699b.png)
After: 
![image](https://user-images.githubusercontent.com/91236493/152071926-2ef24dcd-ce49-416e-bf41-1d5c97e5b3dc.png)

Before: 
![image](https://user-images.githubusercontent.com/91236493/152072825-57738811-3e87-42c0-b68e-d862ed19a4c0.png)
After: 
![image](https://user-images.githubusercontent.com/91236493/152072896-41aa2897-7f12-47c5-8af4-6367abbaf1d6.png)

2.) The Mudraptor Shell stats does not capitalize Damage
![image](https://user-images.githubusercontent.com/91236493/152070674-55dd4308-7555-4355-8a38-ea3aad1fdd56.png)

**Steps To Reproduce**
Put on a Veteran's cap. 

**Version**
Unstable v0.16.2.0.

**Comment by Regalis11** [comment]
The hair thing is actually intentional: we switch the long hairstyles to a short version when wearing certain hats to prevent the hair from clipping through the hat. There was a bug there though: _all_ of the hairs were switched to the same short version, even ones that were short enough already. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/290da462a49db53aafa19cbd1a439a7893cb9d7f

The tooltip issue should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0fc23d0262a0ff7f9b3153914973ef8ef9cb296f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
