### ISSUE TITLE
Cargo Exchange Mission

### ISSUE THREAD

**Issue by Baywatcher11** [Regalis11/Barotrauma#817]
There was a discussion about this recently on forum.

[](http://undertowgames.com/forum/viewtopic.php?f=19&p=123413#p123413)

This mission is the exact opposite of Sub vs Sub. The idea consists of both submarines being at different points, example: one submarine at point A and other submarine is at point B. They need to meet at some point, now here's the exact thing: both of them have cargo which needs to exchanged. Cargo B goes to submarine A while Cargo A goes to submarine B. After the cargo has been delivered the submarines travel back to their starting destinations.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
