### ISSUE TITLE
Design - Damage inconsistencies when using 'maxtargetstohit' and internal expectations

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8181]
### Not a specific issue moreso a general design consideration that may need addressing in either coding or balance.

**"Issue"**:
I've noticed in the `alienitems.xml` line `#1211` for spineling spikes there is a comment that reads:
> Hits up to 3 limbs, so the actual damage can be 3x

-and damage has been reduced to account for this assumption. However that made me realize in certain situations is it not possible for such 'piecing' attacks to instead do 1/3 of the damage ( or whatever fraction of it's maximum limb hits ) if the projectile only hits one limb, such as:
- If a creature only has one limb ( Terminal cells & Leukocytes ).
- If a creature only has very few limbs of 'depth' ( Where few limb overlaps are possible from most angles )
- If impacting a creature with a worm-like chain of limbs at a perpendicular angle, rather than along its length.

EX:
![image](https://user-images.githubusercontent.com/55356135/152408882-b4ca4428-3f91-4624-8aea-073f939d5a2a.png)

From a consistency point of view, shouldn't ideal damage still be the same even if a projectile were to hit a creature with only one limb of very few limbs? I don't have any ideas off the top of my head mostly just presenting the question as given the huge variety of creature structural designs it is important that game mechanics work smoothly when going between them all.

Intended damage increase by a 'weak point' or reduction by 'armor' VS "unintentional" damage increase by density of limbs 
( Much like the problem with explosions with mudraptors ) or reduction by sparsity of limbs.

**Comment by Regalis11** [comment]
This is a good point. However, I think it's more realistic and intuitive that the projectiles do more damage when they pass through multiple limbs: for example, I'd say the projectiles _should_ do more damage if they pass through a worm-like creature along it's length rather than one limb at a perpendicular angle.

The behavior is a bit strange with 1-limb creatures, but to me that seems more like a theoretical problem than something that you'd even notice during gameplay: in single limb creatures we don't really have "armored spots", (and if we do, it's intentional that they're armored all over) and their health is adjusted accordingly, which in a sense balances this out.
