### ISSUE TITLE
[Suggestion] Improvements to bug reporting template

### ISSUE THREAD

**Issue by p2635** [Regalis11/Barotrauma#8197]
- [x] I have searched the issue tracker to check if the issue has already been reported.

It's my first time reporting a bug #8196, I thought it might be useful to add a few more sections to the template.

**Description**

**Steps To Reproduce**
Please describe the exact steps to tell how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Example:
1. Go to Mechanic Training
2. Select the wrench using the mouse
3. ...and so on.

**Actual Results**
What did you observe on the screen?

**Expected Results**
What did you expect to happen?

**Version**
The version of the game and operating system you're using (Windows/Linux/Mac). This can be found on the bottom left when you're in the main menu.

**Additional information**
Add any other relevant context about the problem here (graphic resolution, singleplayer/multiplayer session, settings, internet speed, pc spec etc.).

**Comment by Regalis11** [comment]
While I do agree these extra sections could make the bug reports more clear, I would be reluctant to make it even longer than it currently is, since a lot of the people making reports don't even bother to fill up most of the current sections. + I think the "description" section pretty much covers these two new sections.
