### ISSUE TITLE
Give Characters a Chance to Receive Unique Traits- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#824]
Depending on their job characters have a chance to receive special traits having either fully positive, mixed or negative manner.

Examples:

Security officer has 97,9% chance to be "strong". This means he deals more melee damage and stun duration done by non-electrical melee hits. He also loses less speed when carrying diving suit.

Engineer has 12,6% chance to be "strong".

All characters have 0,6% chance to receive "Gene H". This means they are immune to become infected by venolaceps calyx in any manner, but in exchange they do recover from bleeding by their own more slowly (at passive rate of 0.1 normal people do recover, which in case of "Gene H" is 0.025).

I personally think "Gene H" is balanced, since it makes player immune to become a husk, but for such a strong buff like it he needs medicals like bandages or fibrizione to cancel bleeding efficiently. Griefers won't use a player like him to create a hazardous zombie. Also in single player players do not encounter husky situations regularly, so having them to lose ability to recover from bleeding by their own completely would be overrated.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
