### ISSUE TITLE
Add the name of the submarine being used during the round to the information tab

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#826]
Unless it has already been made or there is another way to find out the name of the sub while not being in lobby.

You don't always pay attention to the names of submarines, and, even if you do, you may not always remember each name you see. That sometimes makes it hard to know which submarine was being used, and therefore makes you have to spend extra time to find it in the sub editor. That is pretty inconvenient for those who want to learn new things about sub making or report bugs that only appear on certain subs.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
