### ISSUE TITLE
(unstable) Winterhalter - non-adjacent Amidships are linked

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#8266]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I believe, having two separated hull volumes linked is not intended since it might lead to multitude of issues at at least submarine condition checkup levels...

**Steps To Reproduce**
Open Winterhalter preview.
Hover over any of two Amidships.
See another one highlighted.
![20220213160837_1](https://user-images.githubusercontent.com/81986452/153754783-4f17b097-3168-4fc7-996f-b7315664443a.jpg)

**Version**
Today's Unstable.

**Additional information**
none

**Comment by Regalis11** [comment]
It seems that the hulls were not actually linked, but are shown as such because they had the same name. I think we should change how they're highlighted in the sub preview.

I changed the name of the small hull at the center now though, which should fix this Fixed in https://github.com/Regalis11/Barotrauma-development/commit/69ab65bcf361af0948e525004e5a8e926bbac863

**Comment by Regalis11** [comment]
Created a ticket about the highlighting https://github.com/Regalis11/Barotrauma/issues/8278

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
