### ISSUE TITLE
Gap passable in editor (or in open sea) - not passable in real game (or while docked)

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#8267]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Top docking hatch of my perfectly normal submarine is not passable in actual game. Watch poor cap' being stuck in semi-appropriate position here:
![20220213164029_1](https://user-images.githubusercontent.com/81986452/153755949-14106834-f667-48dc-bc05-c41881f24f6f.jpg)
Somehow, the hatch's assotiated gap is fully passable when I'm either trying it in Sub Editor's playtest mode or simply forcing it open (assuming that I managed to reach open waters somehow).

**Steps To Reproduce**
I believe, the culprit here is a special wiring I did to docking port's hatch:
(water detector : state_out) > (not) > (hatch : set_state)
I also believe that simply sticking there a timer might fix it.
But (but!) who knows what actual cause it have (and who knows which funky things it might fix for broader audience...)

**Version**
Today's Unstable. Do note that sub file itself was assembled at (I believe) today's Release version - and it had the issue too.

**Additional information**
Sub file: 
[Кирпич.zip](https://github.com/Regalis11/Barotrauma/files/8055641/default.zip)

**Comment by Regalis11** [comment]
Looks like this happened because the detectors would recheck which hull they're inside after those hulls between the docking ports are created. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/cb951353f89dfae981d045ea428bf2392b6bd2c9.

Until the fix is out, you could maybe work around the issue by making the door open using the docking port's "state_out" output (= open the door when the ports are docked).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
