### ISSUE TITLE
Bug report - Container's picked required tags

### ISSUE THREAD

**Issue by CanXue233** [Regalis11/Barotrauma#8276]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hello devs.
In the submarine editor
Itemcontainer/picked required. Uppercase letters entered are forced to lowercase.See the exact location below.I think it will be used
in better access settings if it could be fixed up.My English is poor, please make do with it.
**Steps To Reproduce**
I think it's the bug here:
![X LIUN8P24UGLEG_L 0F07Y](https://user-images.githubusercontent.com/93201375/153818072-77ed88b8-2570-44dd-887b-96e80f9b3c0f.png)
**Version**
v0.15.23.0  Windows10.
**Additional information**
Exact location:
![EPXCK~C(Y)KSNQST%E22ONY](https://user-images.githubusercontent.com/93201375/153817237-c5903237-baf1-4f1c-9fad-1cc5585ed4b7.png)
Thanks!

**Comment by CanXue233** [comment]
Maybe it's a bug.

**Comment by Regalis11** [comment]
This is actually intentional. All kinds of tag comparisons in the game are generally case-insensitive, and converting all the tags added in the sub editor into lower case serve to purposes: making those case-insensitive checks easier to do, and making it clearer to the sub creators that you can't differentiate tags with capitalization.

**Comment by CanXue233** [comment]
Okay, thanks for your reply. So is there any other way to set container access according to player's name?I really can't think of any other way except this.
