### ISSUE TITLE
Outline mode for map editor

### ISSUE THREAD

**Issue by Bagelboi** [Regalis11/Barotrauma#828]
It's really stressful to have to draw a sub by copy and pasting a square every time, so to make that a simpler task, add a seperate mode that all we have to do is draw lines by clicking onto a point and clicking on another until a shape is made. (Basically the lasso tool from photoshop).
It'd be great if we could tweak the lines to set what object should fill in the outline and what scale.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
