### ISSUE TITLE
Husked creatures

### ISSUE THREAD

**Issue by yaelatletl** [Regalis11/Barotrauma#83]
Other than the human husk,  having mantises, crawlers and _maybe_ the owners of the alien ruins as husked creatures, and place them into the same team. 
Also about that, humans that turned into Husk are attacked by regular husks, and sometimes they attack each other, maybe having them cooperate with anything else that is a husk is a better idea

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
