### ISSUE TITLE
Make railgun shells/shell trajectory and explosions visible on sonar

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#830]
Firstly, this would give more useful combat information to captains and other sonar users: due to gibs being visible on the monitor, it is already possible to sometimes see whether the enemy has been killed or not, however, the captain usually has no idea how many shots had to have been fired up to that moment and, therefore, knows little about his gunner's skill and the remaining ammo supply. Making shells and explosions visible would help captains better evaluate their ship's performance and take quicker notice of the damage inflicted upon the enemy.

Secondly, in the rare cases when the sub crew is more or less organized, a savvy sonar user may use this sonar feature to fire accurately at targets that are positioned beyond the immediate railgun visibility range (though making such long range engagements more reliable would probably require some tweaks to railgun aiming as to make it more precise but that's not the point).

And finally, it would just look cool, don't you think?

**Comment by KingChairis1** [comment]
I think that would be great but a little OP

**Comment by BillCombs** [comment]
Judging by how small are humans and husks on the sonar, i feel like the railgun shells would be barely noticeable, since they are even smaller. Also, I don't think that the frequency of sonar pings is big enough to accurately track the trajectory of railgun shells. Though the game is not going for full realism, so i am not completely against it. Perhaps there could be some special railgun shells that send their own more frequent signal to the submarine?

You can find out if the targets are dead even if they are too far away from your cameras; you can see that they are dead, if the sonar does not show that they are moving anywhere except slowly downwards.  
In other cases that is usually done by proper communication. Your crew just should report things. If the captain needs to know how many shots were taken, they should just ask the shooter about it. If your crew is not talkative enough to share even vital information, the amount of your railgun ammunition is the least of your worries.

Also, i don't think you can reliably shoot moving targets at long range. Not only you have to know the trajectory but you have to know how to time the shot for the shell to hit the target before it moves further. Add random internet lag to that and the hit chance would become small enough for this action to be considered a mere waste of ammunition. It would probably help only if you were fighting a big and slow submarine.

I am also having doubts about the reliability of using sonars and railguns at same time. Since the sonars are not connected directly to railguns, you would have to run back and forth from the guns to sonars to track your shots. I am not sure if this is actually going to make you that much more accurate. Perhaps there could be railgun controllers with small sonar monitors inside? Handheld sonars are a thing, so why not have such a thing on the railguns. Though, not sure if you can make it so that it would be actually giving you enough information while not covering your whole screen.

Overall, i am not really sure if this feature is that necessary. I am not against it, but i don't feel like i would really need it. Though i do agree, it would probably look cool and thrilling to see the shells come out of the enemy submarine's silhouette and move towards yours. The "oh crap" feeling right before the thing hits you. That also kinda reminds me of pirate ship battles.
I also agree about the explosions. Loud sounds should be visible on the sonars, at least in passive mode.

**Comment by Waagher** [comment]
I agree that the individual shells may be too small to be cohesively implemented, but the way around it is to display not the shell itself but the wave fluctuation that it leaves behind. As far as I know, the dev build sonar already displays the water currents, so the visible shell trajectories could be explained this way. This also can solve the sonar frequency proble you pointed out, since the waves created by the railgun shell may take a few moments to dissipate.

Finding out whether a creature is dead indeed can in most cases be found out through sonar already, and good communication is the best way to handle isssues with ammo. But I still think this feature can provide some useful combat information. It can be frustrating as a captain to not know how good are your gunners faring against a big enemy while you're doing your best to keep your distance away from it, which is the experience I had in mind while coming up with this whole idea. As for long-range firing and use of sonar in combat - these are indeed specific things that are very uncommon in most matches, but they do happen: the sonar-aimed firing is sometimes utilized against hostile subs in PVP or for ruin-bombing, and I have tested it myself against large monsters with some success.

I agree with you that's definitely not a necessary feature, but it could have it's practical uses, as well as look really dope.

**Comment by BillCombs** [comment]
I like the way you explained the visibility of trajectories, that actually might make sense.
As i said, i am not against having it.  It would indeed be pretty cool.
Now, that i thought about it more, it would probably be nice to have more things appear on the sonar, especially in passive mode. It looks a bit empty right now.
It also could probably help in cases of somebody killing your crew members that are swimming outside of the sub. I have got killed by traitors and griefers when i was outside of the subs quite a few times, and since death from the shells is pretty much instant, you cannot send a message about the fact of getting shot at by railguns. Perhaps, if the captain sees the shells suddenly going out of the sub towards crew members, he would send the security team to investigate it, so that wouldn't be that easy of a kill to get away with.

**Comment by ZealanL** [comment]
I also think it would be nice to see a wake come from shells fired. It wouldn't be that hard to do, either.

I could try coding this later today and make a pull request to the dev branch.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
