### ISSUE TITLE
Unstable - Reload Ammo Railgun bug

### ISSUE THREAD

**Issue by brjc** [Regalis11/Barotrauma#8305]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots commanded to reload ammo do not reload the railgun. Any loose rounds lying about are instead put into the railgun shell racks if space is available, and ignored if not.

**Steps To Reproduce**
1. Singleplayer
2. Humpback
3. Railgun loader less than full
4. Leave railgun ammo lying on floor
5. Command assistant to Reload Ammo
6. wait

**Version**
Unstable 0.16.4.0, rev a92cd175a9
Windows 10 Home

**Additional information**
This command seems to only direct bots to reload the railgun shell racks, the actual loader is ignored. Coilgun reloading seems to function properly.

**Comment by ekqvist** [comment]
Thanks for the report! It seems that the "Reload Ammo" order wasn't working correctly because the characters couldn't find the needed ammo. The issue was trying to find them using the ammo tag while we required item identifiers to be used instead. It should be fixed in Regalis11/Barotrauma-development@f6cc56f.

**Comment by AngryMerkas** [comment]
It seems like the bots now are loading shells into the railgun loader, but only a single one. When that one is fired, at some point another single shell is loaded, never the full railgun loader to max capacity.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
