### ISSUE TITLE
Mod development issue

### ISSUE THREAD

**Issue by DarthSidiousPalpatine** [Regalis11/Barotrauma#831]
Hello, umm... I'm creating a mod for dev version of barotrauma. A very big mod from Russian community, that I have creating and updating for 1.5 years. And.... We have some problems, because we can't play multiplayer to test my mod...

It's says that our contentpackages in't matching. But they are completly same!

This mod is created for multiplayer campaign. Ores, Loot, More professions and some tweaks. Reusable fuel tanks and fire extinguishers, food and more. And we are very sad, because we can't test it in multiplayer.

(Sorry, English is not my first language.)

**Comment by DarthSidiousPalpatine** [comment]
This is a screeenshot of a issue

**Comment by Regalis11** [comment]
Could you share me a download link so I can test it? Based on your screenshot I'm assuming the mod is for the dev version of the game?

**Comment by DarthSidiousPalpatine** [comment]
Yes, screenshot is for dev version.
https://drive.google.com/file/d/17nGrG0swJmlJV8jv4-_BcfBgsQjUXeV2/view this is the old version of sovietrauma, same with version on screenshot. You need only:
1)Put Sovietrauma.xml into contentpacks
2)Folder Sovietrauma into mods
3)Characters into Content with replacement

This was a first test of adding loot.

**Comment by Regalis11** [comment]
I couldn't reproduce the problem, I was able to join with no problems. 

The error seems to imply that the content package has not been selected, not that it doesn't match. Did you select it in the launcher or in the game settings before attempting to join?

Also, as a sidenote, I would not recommend making the mod replace vanilla game files, because that means player will not be able to switch back to the vanilla content package without reinstalling the original files. You should instead include the modded creature files in the mod folder, the same way you've done with the new item files.

**Comment by DarthSidiousPalpatine** [comment]
Oh, yes, we selected content package. I think it was an error in older dev version.

Yes, I know that I can create files in mod folder, but it was a fast test of adding loot, and I created it in 20 minutes)
