### ISSUE TITLE
after docking map screen gets stuck and can't be closed 

### ISSUE THREAD

**Issue by laggerrusher** [Regalis11/Barotrauma#8312]

**Comment by Regalis11** [comment]
Hello and thank you for the report!

I think we need more info to diagnose this: did it happen in single player or multiplayer? Which game mode? How exactly did it get stuck: were you unable to select locations, was the "start" button not clickable, did nothing happen when you clicked it...? Which game version did this happen in?

**Comment by Punchington** [comment]
I'm sure it's probably not what laggerrusher was referring to, but I remember there being an issue where if you undock your sub in a Campaign remotely (i.e. not from the nav terminal but instead a button), you will get stuck in the map screen and are forced to begin a mission.

I imagine this is to prevent players from sailing around in these outpost levels, but it's problematic when it's done accidentally and there's no way to re-dock to exit the map screen. Not sure if this was ever changed though since that was a few updates ago since I had last used that docking port arrangement.

Could be nice if the game would just re-dock you immediately or force the main docking port to stay docked no matter what signals it receives, just to prevent this from happening - or maybe if it receives any signal to undock, it instead brings up the map like when you try to undock from the nav terminal, but again remains docked.

**Comment by Regalis11** [comment]
No known steps to repro, closing
