### ISSUE TITLE
Make a message appear on your screen if you get killed by a traitor who had you as his target

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#832]
Since griefers exist, sometimes it may be quite hard to understand if the person, who killed you, did it because he had to, or just because he wanted to. Sometimes players were getting really angry at me for killing them, even though i was just doing my job as a traitor. And most of the time they try to votekick me, which leads to other players seeing the votekick message, getting suspicious, finding the body and immediately realizing that i was the one who killed the person. That kinda ruins the fun of being a stealthy killer. I think there should be a message telling players that they were killed by a traitor who had them as his targets, so they would know that it was not just a griefer killing them for no reason.

Perhaps the way it could work is checking if the traitor did any damage or stun their targets recently, and, if the target died soon enough after that, count it as getting killed by the traitor. That won't help those smart traitors, who manage to convince their crew that their target is the traitor and should be killed, but at least it would help those who do killing the usual way; i think most traitors kill their targets themselves, so that would help the majority of them.

**Comment by ZealanL** [comment]
This is a good idea, but when a player re-spawns they would know that person was a traitor.

That's the only visible flaw - besides that, this works.

**Comment by BillCombs** [comment]
The problem is that if you kill a guy for to noticeable reason, you are usually either a traitor or a griefer. So if the player, who got killed by you, did not know if you were a traitor, he would most likely want to revenge kill you anyway. It's not like anybody, who got killed for no noticeable reason, would just immediately forget about it.

The message should probably contain some words about new life rule(like it's made in some roleplay kind of games), since once you are dead, it still counts as traitor's victory even if you respawned. Since there is nothing else for the traitor to do once he completed the task, besides helping the crew, the message should probably tell the player that they should just try to work with the traitor like if nothing ever happened. Unless the crew witnessed the murder and is trying to kill or arrest the traitor. In that case, even if you have a new life, you could still be informed about a traitor on the sub and get an order to kill or arrest him.

The whole thing is mostly needed to help players to distinguish griefers from traitors, so traitors won't get as much hate just for doing their job. If players are dishonest, they will try to revenge kill their killer in any case.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
