### ISSUE TITLE
Portable Pumps 

### ISSUE THREAD

**Issue by KingChairis1** [Regalis11/Barotrauma#835]
Someone on a discord server had the theory that ruins are made of hulls and could be drained, but pumps on a sub might not work.
This would work

**Comment by BillCombs** [comment]
Why would you want to get rid of the water in the ruins though?
  The height of the rooms and lack of platforms and ladders would make it hard to move around if you did not have any water. You would just be stuck at the bottom of one of the rooms until you pumped the water back inside.
  There is no oxygen generator so there still wouldn't be any breathable air.
  If you wanted to do that to get rid of the guardians by making them get stuck on the bottom, you would have to somehow make all of the doors in the room with a guardian get closed while the guardian was still in the room, and to manage to get whatever you wanted without triggering the motion sensors. I think that, even if it's possible, it would just take too much time and effort.

  It could be useful for abandoned subs or stations(if these get added), though i am pretty sure they would have their own pumps anyway,

  It could also help if you are on a sub which does not have a pump in some vital spot. Though, if the sub maker did not think about adding a pump in such spot, they probably did not think about adding a portable pump either. So you still wouldn't be able to use it unless it could be fabricated.

**Comment by ZealanL** [comment]
Ruins are not made of hulls. Draining them would restrict you to the floor too.

Portable possible gas-powered pumps would be cool, like sentry pumps you could plant around or relocate. Or maybe a pump with a tube that you could grab the end of and stretch it from room to room.

**Comment by rico6822** [comment]
I have to agree with Bill. Why would coalition do this? It only makes a lot of trouble.

**Comment by KingChairis1** [comment]
Idk just a rumor I heard on a discord server I thought would be cool

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
