### ISSUE TITLE
Player can not see the explosion

### ISSUE THREAD

**Issue by Sakraello** [Regalis11/Barotrauma#839]
In multiplayer only host can see some explosions. We tried to switch roles, but it didn't help - who isn't a host can not see the explosion of for example nitroglicerine. It doesn't matter who throw granade. Stun grenade works correctly.

**Comment by NilanthAnimosus** [comment]
Just as a side note - but console explosions and such do not show if I recall, explosions themselves are not networked in any way - but instead the client handles most things locally by triggering its own status effects.

This caused issues such as removing explosion from an item server-side on potassium for instance to have the effect on clients of infinite explosions.

 It's quite possible the clients are simply skipping the related trigger method to cause the status effect on these specific explosions (at least where the status effects are server-side only or just too fast for the client to even register they ever occurred in a network update or something?).

**Comment by ZealanL** [comment]
This is _still_ a problem. This goes for explosive shells, nitroglycerin (as well as flash powder and liquid oxygenite), oxygenite crystals, detonators, etc. 

The only reliable sources of explosions are grenades and nukes. This could probably be fixed pretty easily, I'm surprised this is still an issue, and players are really confused when all the sudden half of the submarine is cracked and broken with no idea of the source. No sound and no visuals sort of ruins the experience.

Devs, please fix.

**Comment by Regalis11** [comment]
This seems to happen because of the items being removed when they explode, and the way the entity event system handles removed entities (= simply skipping over the event if the entity does not exist at the time of writing). It's not as trivial to fix as it may sound - I have a few potential solutions in mind, but all of those require changes to the core eventmanager logic and I want to make sure it doesn't cause any unintended side-effects before implementing a fix.
