### ISSUE TITLE
[Feature Request] Add support for modding via Patch Operations

### ISSUE THREAD

**Issue by leonard84** [Regalis11/Barotrauma#8422]
Rimworld has powerful XML Modding support via [PatchOperations](https://rimworldwiki.com/wiki/Modding_Tutorials/PatchOperations), allowing mod authors to write modifications for the game files, instead of having to copy and modifying it. This makes it possible for multiple mods to modify the same item without conflict, as long as they don't modify the same value. Furthermore, it makes mods more stable as the item will retain all non-modified properties from its base version, thus being properly updated. Another advantage is, that mods can also add something to other mods without having to know them explicitly, just by specifying a general xpath.

Having something similar for Batorauma would make modding easier and more powerful. 

There is a [third-party-tool](https://github.com/Jlobblet/Barotrauma-Mod-Generator) doing something in this direction, but it is more limited and only works for a single mod.

**Comment by Regalis11** [comment]
That's a good idea! The item variant system actually works similar to this, allowing selectively replacing parts of the base item's xml file. It could be worth considering to expand that to other types of content as well.

I'll close this ticket though, since we only use the issue tracker for issue reports, feature requests should go in the [Discussions](https://github.com/Regalis11/Barotrauma/discussions).

**Comment by leonard84** [comment]
@Regalis11 you can simply convert issues to discussions without closing them.
