### ISSUE TITLE
too many materials in abyss islands

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8424]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i really like the addition of alien minerals in the abyss islands but there's way too many of them, you usually only use 2 to 5 physicorium bars in ammo to kill an abyss creature, but you get 3 stacks of physicorium bars and other materials in reward, i'd cut the amount of materials in each island to a quarter or a third of what it is now.
(move this to discussions if you disagree)

**Version**
v0.17.0

**Comment by itchyOwl** [comment]
Yeah we already discussed this internally. Currently you can find over 30 alien materials in one island, and there's multiple islands in one level. Moreover, we need to add some level of scaling too, so that you can't just go into the abyss in the first level and loot all the rare materials freely when there's no abyss monster to guard them.

**Comment by itchyOwl** [comment]
Quickly tested, and I think the resources are now much too scarce, at least in the beginning of the campaign.
Here's the first level:
![first](https://user-images.githubusercontent.com/5370738/158776544-5d5d66d5-1531-4f9e-9737-f15d4007786b.png)
Here a second in the beginning of ridge (20% difficulty):
![ridge](https://user-images.githubusercontent.com/5370738/158776557-d738850e-2439-4c68-9fcc-45f80a04fe98.png)

I actually had to use a while to spot the resources in the islands in freecam mode. So currently they are too empty. I think we should fill the islands with common stuff and place some rare resources there too. But not only the rare resources. Also it seems that the items are still spread very close to each other. And then also tell the player in some way that there's rare stuff there (e.g. via a mission, as suggested before).

**Comment by itchyOwl** [comment]
Also could make it so that the rare resources start to appear only in the ridge, for example. But that doesn't mean the islands should be empty either.

**Comment by Regalis11** [comment]
Thanks for the feedback, I'll do some more adjustments to this.

> Also it seems that the items are still spread very close to each other

This is intentional: level resources always spawn in clusters.

**Comment by LePiromano** [comment]
> This is intentional: level resources always spawn in clusters.

I think itchy means they spawn inside eachother when they spawn in a wall that's too small

**Comment by itchyOwl** [comment]
Yeah that's what I meant: there's no spacing between the resources. Clusters are good, but in this case it might be better if there was just 1-3 resources per spawn position. It's partially a visual thing, but affects the balance too. If you can't spot any resources, it's hard to find them. And if you accidentally find like 10 at one spot, that's a bit overwhelming.

In my opinion the goal would be that by a glance you can see that there's something interesting in the islands. And when you take a closer look, you should be able to find the rare materials. So there needs to be things there, but not too much to break the economy. Spreading the resources would help to achieve this. But I'd also add normal minerals there too, so that they catch the player's attention.

**Comment by cshingle** [comment]
I know it is pretty late in the process for this one, but I have an alternative idea/solution. Currently when you kill the abyss monster you have free reign of it for an unlimited period of time. Adding a chance that another monster could spawn after a random cool down period (maybe influenced by difficulty) would encourage players not to linger in the abyss and do more smash and grab type mining.
https://github.com/Regalis11/Barotrauma/discussions/8553

**Comment by itchyOwl** [comment]
I think it's a good request. Created a ticket about it: #8589.

**Comment by LePiromano** [comment]
it's back to being ridiculous
![image](https://user-images.githubusercontent.com/55637865/161158864-16022617-e476-441d-a475-4e82a6700eb7.png)
![image](https://user-images.githubusercontent.com/55637865/161159042-328c62d6-7065-44e7-bf52-9c864a70a8ef.png)

I think what you could do is keep the current cuantity of clusters per island but drastically reduce the amount of minerals a cluster can have to a max of like 3 or 4

**Comment by JeroonBosch** [comment]
Still blocked atm. Once that issue is fixed it will still need some finetuning
