### ISSUE TITLE
Character Editor crash game when creating new or copying existing

### ISSUE THREAD

**Issue by PlayerWithConflicts** [Regalis11/Barotrauma#8452]
When trying to create a new character the game will just crash when clicking on CREATE, maybe textures are bad? Maybe joint and limbs must be predefined even though no one teach you how?

And copying an existing character, like a human, and then choosing your custom textures and creating the folder for this copy (something the game wants you to do to proceed), the game just crashes, but the game make a noise, like when you select something and it proceed with no problems, that doesn't happen when creating a character so is like the game worked but crashed at the same time.

After this last process, even though the game crashed, you can see that copied character in the characterlist of the character editor, but when selecting it the game crashes again.

This is my first time in here, just telling about this problem because I can't find a solution and the game tells me to tell about this here.

[crashreport - when creating new character.log](https://github.com/Regalis11/Barotrauma/files/8189312/crashreport.-.when.creating.new.character.log)
[crashreport - when copying human.log](https://github.com/Regalis11/Barotrauma/files/8189313/crashreport.-.when.copying.human.log)

**Comment by PlayerWithConflicts** [comment]
Well, it still crashes, I don't know that is it now. Looks like it wanted to spawn monsters for some reason and that it searched for textures that I didn't tell to use when copying, and when creating a new one after clicking on CREATE it told me if I wanted to override a folder with the same name and I said yes, then it crashed.

[crashreport - copying.log](https://github.com/Regalis11/Barotrauma/files/8208627/crashreport.-.copying.log)
[crashreport - creating.log](https://github.com/Regalis11/Barotrauma/files/8208628/crashreport.-.creating.log)

Is it something I have to do before creating a character? Maybe I have to do something with the limbs an joints? I don't know what tho.

**Comment by cshingle** [comment]
I am not sure about this error. I would try reinstalling just in case something got corrupted/overwritten. If that doesn't work the game devs will likely need to help you.

**Comment by PlayerWithConflicts** [comment]
> I am not sure about this error. I would try reinstalling just in case something got corrupted/overwritten. If that doesn't work the game devs will likely need to help you.

Alright, I reinstalled this and now I can load it but it looks really weird because the limbs and things have to be positioned, but when copying the human to customize that, is crashes after clicking create, and when creating a new one it crashes again after clicking create.

So it's the same ...

[crashreport - creating.log](https://github.com/Regalis11/Barotrauma/files/8209961/crashreport.-.creating.log)
[crashreport - copying human.log](https://github.com/Regalis11/Barotrauma/files/8209962/crashreport.-.copying.human.log)

**Comment by itchyOwl** [comment]
Fixed the reported crash in Regalis11/Barotrauma-development@f4af6d3. Copying humans should now work, but it will complain about the lack of AI block, beacause there's none defined for humans. You can fix that by adding the AI block in the character config file (e.g. Humantest.xml). ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/1745db6b-3b8a-4be9-9bff-d77877b9ee38)

However, that wouldn't make your character fully function like the vanilla humans, because currently the game doesn't support humans that are not of "Human" species. In other words, you can create humanoids that use the enemy AI but not the bot AI, unless they are of the "Human" species. I'll create a ticket about changing that, but doing that will require some changes and it's not going to be a high priority, so no promises on if or when that's going to change.

Note that you can use the override system for overriding the vanilla human  character with a custom human. To do that, copy the entire "Human" folder from Content/Characters/ to "Mods" and add the character definition file in the filelist: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/09e0442e-deb4-4f74-b23f-dfa2621db9a0)

Then add `<override>` tag in the beginning of the custom Human.xml and `</override>` tag in the end of the file.

(Note that in the next update, we'll separate local mods and those that have been downloaded from the workshop into different folders, probably requires an action from the modders)

**Comment by itchyOwl** [comment]
To be clear about it: did it crash only when trying to create/copy humans? If it crashes also when creating/copying non-humans (i.e. monsters), could you post the crash logs here, thanks!

**Comment by PlayerWithConflicts** [comment]
> To be clear about it: did it crash only when trying to create/copy humans? If it crashes also when creating/copying non-humans (i.e. monsters), could you post the crash logs here, thanks!

What the frick ... IT DOESN'T CRASH, it only crashes when copying or creating a humanoid character ... WHY?

**Comment by PlayerWithConflicts** [comment]
> Fixed the reported crash in [Regalis11/Barotrauma-development@f4af6d3](https://github.com/Regalis11/Barotrauma-development/commit/f4af6d3). 

Cool, thanks, I hope one day it will be possible to create humans character and use them, like making them part of the crew or your main character in multiplayer, like a completely custom character, with custom textures, etc.

**Comment by PlayerWithConflicts** [comment]
> Fixed the reported...

BTW, that link is not working.

**Comment by itchyOwl** [comment]
The link works, but it's to a private repo that you don't have an access to. It's meant for the QA.

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
