### ISSUE TITLE
broodmother regens health too fast

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8462]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
nailed like 50 physicorium coilgun rounds on a broodmother's head but it did nothing because it was eating the dead body of a crawler while approaching, regenerating health faster than i could drain it with the highest dps coilgun ammo.

**Version**
v0.17.0

**Comment by itchyOwl** [comment]
Forgot that the regeneration was defined in percentages. Fixed in Regalis11/Barotrauma-development@1e1230d (lowered the regen rate from 15% to 1%)

Note: couldn't repro it naturally, because the broodmother prefers targeting the sub when it can. So I wonder how it actually happened? If you are able to shoot at it, it should target the sub instead of the corpse.

**Comment by LePiromano** [comment]
> Note: couldn't repro it naturally, because the broodmother prefers targeting the sub when it can. So I wonder how it actually happened? If you are able to shoot at it, it should target the sub instead of the corpse.

It was carrying the body on it's mouth and eating It while cgarging at the sub

**Comment by itchyOwl** [comment]
Oh, didn't know that can happen. Sounds like a bug to me. I think the monster should drop the dragged target when it no longer is targeting it.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
