### ISSUE TITLE
Gender restrictions broken for custom humans [unstable]

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8498]
Gender restrictions don't seem to work on custom humans (created either by copying human in the character editor or by overriding) after the modding-refactor.

Seems to work properly in the release version though.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/c757a936-bfee-4911-883d-4afe75069637)

**Comment by Jallu** [comment]
Copy a character in character editor or create an override in XML.

**Comment by juanjp600** [comment]
[Test_humanTags.zip](https://github.com/Regalis11/Barotrauma/files/8317447/Test_humanTags.zip)
Failed to replicate. Cloning a human in the character editor doesn't work in either dev or master because of the gender-specific texture path, and the overridden human that I've linked here seems to be working properly.

**Comment by itchyOwl** [comment]
Cloning humans can be done by adding a valid texture path in the wizard:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/4e3b1dc6-6b55-4c2e-8e2f-8856f47f0351)

Can't repro it either anymore. So it's possible that I forgot to change the texture path in the ragdoll xml back to "Content/Characters/Human/Human_[GENDER].png" and used the female texture there.

Removed the texture path validity check when copying humans in Regalis11/Barotrauma-development@76612a6.

**Comment by Rokvach** [comment]
Tested, no issues, closing.
