### ISSUE TITLE
Stuffing bodies into closets

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#85]
Being able to stuff a body into the closet and block the inventory view with a ragdoll would be really awesome!

Imagine opening the locker to get some oxygen, only to see a dead body covering most of the objects inside.

**Comment by Crystalwarrior** [comment]
If the gui body stuff is too hard or annoying to implement, perhaps it should just dump out the body when you interact with it instead of showing the inventory?

**Comment by AlyMar1994** [comment]
I +1 this for the Traitor mode possibilities.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
