### ISSUE TITLE
Water flows much more slowly when the gap is submerged between hulls

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8511]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Huge difference in flow rate when the gap is "pushing" water into air, and pushing water into water
![image](https://user-images.githubusercontent.com/73229309/158029591-74bddce6-3ed1-4e49-a3df-9ae8c51b298e.png)

In this configuration, the horizontal hull is faster than the vertical one, because half is underwater and half is dry.
![image](https://user-images.githubusercontent.com/73229309/158030336-af4c77a6-4b57-4216-8db6-fd265765f1fe.png)

The flow rate however seems identical from open water into a hull

**Steps To Reproduce**
Download and test [Gapsbug.zip](https://github.com/Regalis11/Barotrauma/files/8238129/Gapsbug.zip)

You can see the vertical gap flow is much faster, then kinda slows down after it gets submerged
The horizontal gap is always submerged and the flow is really slow

Shifts the position of the buffer hull around and you'll notice

**Version**
v0.16.7.0

**Comment by cshingle** [comment]
@ubertpendragon I created a fairly comprehensive discussion on gaps and water flow.
https://github.com/Regalis11/Barotrauma/discussions/8328
The short version is that 
- Horizontal gabs flow is **much** faster than vertical. 
- Down is faster than up (I didn't document this, but the upflow magic number is like 8000)
- Flow from ocean in is completely different values/code then hull to hull flow
- This was all intentional design. I am guessing that vertical flow was limited to make the sub fill more slowly. If vertical flow matched horizontal flow a sub would completely flood in a few seconds. If horizontal flow was as slow as vertical the water would feel like syrup, so it is a much more realistic value for larger hulls. Small hulls it is still looks odd because the flow rate is calculated by the hull volume not currently filled with water.

In my opinion the magic vertical flow numbers that limit vertical flow should be moved to xml to allow modders to make the sub flood in a few seconds if they want.

**Comment by ubertpendragon** [comment]
Interesting
I brought that up because some subs builders were confused that their airlock filled very slowly.
