### ISSUE TITLE
votekick bug

### ISSUE THREAD

**Issue by Andrej134234** [Regalis11/Barotrauma#855]
sometimes when i votekick a person the game will votekick a different one

**Comment by ZealanL** [comment]
I believe this should only be possible if:

1. You miss-clicked.
2. As you clicked on someone's name, they left they left the game, and a new person received the same client ID before you hit the "Vote to kick" button. (This is a pretty rare scenario, but possible).

I don't really see any way that this would happen otherwise.

**Comment by Regalis11** [comment]
I haven't been able to reproduce this, and without further information I don't think we can fix this.
