### ISSUE TITLE
Add a hint/reminder about neutral ballast level setting in sub editor

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#858]
I played in a lot of custom subs and noticed that quite a few of them have default neutral ballast settings even though their ballasts vary in sizes a lot. Also some of them actually have it changed, but the change is either not accurate enough or just wrong.
It seems that a lot of sub makers forget/don't know about that setting, or how to set it properly.
That makes it a lot harder to control most of those submarines in Y axis without using autopilot, because to set their neutral Y position you have to aim somewhere above or below the actual middle of the sonar.

There should be some hint/reminder that tells players about this setting. Perhaps when placing the navigation terminal. I think it wouldn't be too annoying, since you usually only place one or a couple of them when making a sub.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
