### ISSUE TITLE
Add a submarine speedometer/speed detector component

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#862]
With vertical and horizontal speed measuring settings.
Or you could make it so the Navigation terminal and sonars had vertical and horizontal speed info outputs, since they are already measuring them.
Would help with making automatic sub controlling systems or giving the crew information about the speed of the sub without a need to check the sonars(i know that you can just look outside of the submarine to guess the speed, but it's not always accurate, especially when the sub is inside of a water current, since movement of water creates an illusion of submarine going fast); also, systems that would tell if the sub is moving too fast or moving when it's not supposed to and vice versa.

Right now it's hard to make sub control systems automatic by only changing engines' and pumps' force, since the submarine does not immediately lose most of its speed once they have been set to 0 force(in case of engines) or neutral ballast level(in case of pumps), and the speed is too dynamic with all those creatures and water currents pushing the sub around. There should be some way to make the wire systems able to get submarine's speed information.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
