### ISSUE TITLE
Add vertical hatches.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#863]
Add vertical hatches to allow making believable crawlspaces or maintenance shafts and such. I believe it would give more options for creative submarine design.

**Comment by ScarletScythe** [comment]
As someone who's trying to make a sub with maintenance shafts, this would be very nice to have, since the closest we got to this are small doors from BTE.

**Comment by BillCombs** [comment]
You can try using duct blocks as a sort of door or hatch with a custom size. Though they have flaws such as being more complicated, having gaps that let light and bullets through, having a bugged texture in vanilla and affecting fps more, since you have to use more than one.
![wilson-pc-2018-oct-27-004](https://user-images.githubusercontent.com/38168249/47609540-f238d700-da6a-11e8-8f0c-e0f0edcfa92f.jpg)

**Comment by BlueTheKing** [comment]
+1, plus should be easy to add anyway

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
