### ISSUE TITLE
Add an ability to edit stats of multiple selected items of same kind at once

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#864]
Most likely really hard to implement, but would make sub making so much easier. It's such a pain to edit stats of stuff like lamps 1 by 1 when you have about 30 of them. Being able to just select them all and then edit the stat once would give sub makers a lot more free time to do more important things for their sub.

Would also be really nice to have an ability to select multiple items of same kind by dragging the mouse cursor across the sub instead of having to ctrl click each one individually. Something like selecting an item, holding a special key, and then dragging the mouse to make it select the other items of the selected item's kind.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
