### ISSUE TITLE
Stuff that would help with moderating servers

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#868]
### Unban command

Self explanatory i would say.

`unban <ip/steamid>`

### Faster kick/ban commands

The current system for banning in the console is pretty annoying so a faster way to do it would be great.

This should apply to all variants (kick/kickid/ban/banid/banip).

Something similar to this:
`ban <player>;<reason>;<duration>;`

### Traitor logging

Since it's somewhat difficult to find out if someone is a traitor in the moment it would be useful if all traitors are announced in the console along with their targets.

Adding a new permission that changes the color of their name or otherwise displays who a traitor is while spectating could help too.

### Disguise logging

Currently if someone is disguised its difficult to figure out who it by spectating, a new permission to bypass the disguise feature and display who is disguised as what when spectating ingame would be nice.

Something like:
`<Player>(<Disguise>)` above a players name

### Ban message

When a player is banned they just get the reason and not for how long they were banned for, which in some cases turns people off from even attempting to join again.

The message should display the time they were banned for and on every other join it should display the remaining time until the ban expires.

**(Stuff below here would probably fit into the steam version more)**

### Playtime count

Logs the time a player has spent playing on the server, could be logged in its own file which would fit the time played next to the steamid and player name. 

### Job bans
(Could work with the suggestion above)
Locking jobs for players who have less than a certain amount of time played on the server, in case nobody fits the criteria or the player that does has the job in a lower priority then it would pick the next player with the highest playtime.

This could extend to or just use the total steam playtime of BT as a secondary option. 
(eg. "You need to have played 20 hours of BT to be allowed to play captain on this server")

Thanks

**Comment by rico6822** [comment]
About those unbans owners can simply remove players from their banlist in the game files, but not everyone knows about it.

**Comment by BlueTheKing** [comment]
Maybe i should have said that this is mainly from experience on dedicated servers. 

When the banlist is changed the server doesn't recognize it until a restart occurs, i was removing it manually from the banlist but having a proper command to do it would be good.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
