### ISSUE TITLE
Outpost guards doesn't act on you attacking NPC's

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8685]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've noticed that unless I'm at the same hull as the guard the guard rarely aggroes on me causing havoc in the outpost.

**Steps To Reproduce**
Load up a campaign and shoot at some store NPC's while the guard is on the opposite side of the outpost. 

**Version**
0.17.5.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/812b51225e9ac432716718d6b26195265ea6a06d

**Comment by itchyOwl** [comment]
Can't repro

**Comment by itchyOwl** [comment]
Are you sure you didn't accidentally attack your own crew?

**Comment by Zetabite** [comment]
tested myself, they are totally indifferent about it

**Comment by itchyOwl** [comment]
Actually there was a default max report range, but it didn't work. Instead of fixing it, I decided to removed it, because it might be seen as a bug, like this. The report range has an effect on the bandits in the abandoned outposts, because it's defined for them.

But the actual bug here was caused by the combat objective. There's a hard coded 2000 pixel limit for chasing the target before it's considered as escaped. Changed this so that outpost npcs can't lose the target anymore. (Regalis11/Barotrauma-development@b2d1316. The intention behind the max distance was that you could hide from the enemies in an outpost. This wasn't changed.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
