### ISSUE TITLE
RepairTool behaves differently in multiplayer

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#869]
It seems RepairTool behaves differently in multiplayer than it does in singleplayer. I've noticed it does more damage in multiplayer sometimes.

It's even easier to spot the difference when you use condition as a way of "rate of fire" in them. Here, an example of what I mean:

```
<StatusEffect type="OnUse" target="This" Condition="-99" disabledeltatime="true">
   <RequiredItems name="Gauss Pistol Magazine" type="Contained"/>
</StatusEffect>
<StatusEffect type="OnBroken" target="This" Condition="100" delay="2">
  <sound file="Mods/BTE/Items/Weapons/EnergyOn.ogg"/>
</StatusEffect>
```

In singleplayer, this piece of code will only allow it to be discharged once each 2 secs but in multiplayer, it will allow it to fire it for longer. Since RepairTool ignores armor, it makes them good weapons to kill heavily armored creatures and crew with the damage increase it gets in multiplayer.

**Comment by Regalis11** [comment]
I haven't been able to find a way to reproduce this. In the multiplayer it is sometimes possible to fire it for longer than intended, because the clients are not allowed to directly modify the condition of the item, but instead rely on updates from the server. Especially in poor network conditions there can be a noticeable delay before the clients receive a message that tells them the item's condition has reached zero. 

However, because the server also has authority on the healths of the characters, the longer firing duration at client's side should not affect the amount of damage taken. I did a bunch of testing on the gauss weapons and different simulated network conditions, and the amount of damage does seem to be consistent. Do you by any chance know any way to reliably reproduce the bug?
