### ISSUE TITLE
Easy subamrine swap

### ISSUE THREAD

**Issue by Nest0r13** [Regalis11/Barotrauma#8750]
Nowadays swap submarine is laborious, change all your items between the subs not is easy.
You have a list of all of your stored items, in the shops.

Is possible take this list and spawm this items in the cargo in the new sub? Like when you buy new items.
A checkbox to confirm the "item swap" could be nice.

Sorry if i dont do correctly this post.First time

**Comment by leonard84** [comment]
Suggestions should go to the discussions, there is already one for this topic https://github.com/Regalis11/Barotrauma/discussions/6761

**Comment by Regalis11** [comment]
Thank you for the report! We are planning on addressing this in a future update (one option we've been considering is a list where you can choose which items to transfer, like you described). But yeah, this is technically a feature requests / suggestion instead of an issue report, so I'll close the ticket.
