### ISSUE TITLE
[Dev version] Make the directional ping checkbox accessible on the sonar in passive mode

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#877]
Directional ping checkbox should be accessible on the sonar in both passive and active mode. Having to turn on active sonar before enabling directional ping makes your first sonar ping go in all directions, which makes using directional ping after it less effective.
Same thing with the zoom setting. Why not allow to use it in passive mode if you still can see the map when there is sonar noise nearby?

**Comment by Regalis11** [comment]
This was intended to make the interface a little more intuitive to use, the directional settings do nothing in passive mode so I thought it'd make sense to disable them. But you're absolutely right, it makes sense to be able to change them before switching to the active mode. I think I'll just gray them out a bit or something like that instead of disabling them completely.
