### ISSUE TITLE
start mission button appears interactable despite having no permissions

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8784]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "start" mission button in campaign map is interactable even if the client has no permissions. Clicking it makes it pressed, hovering over the button highlights it. It is misleading!

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
tooltip saying requires X permission would be great but i'm not holding my breath (i have a diving mask)

https://user-images.githubusercontent.com/5103517/162801176-c6fceabc-d752-4f5b-9020-0dfb5cc36779.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c437b8f279e376d5bb351d34e5d6ce470e570cee

Fixed clients not getting notified of the permissions of the rest of the clients when they join, making them think they're allowed to manage the campaign since there's seemingly no-one with permissions on the server.

Steps to repro:
1. Host a dedicated server (important, because if there's a server host present, the client will know they don't have the permission to start the round)
2. Join as client A, give this client permissions
3. Join as client B and open the map screen

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
