### ISSUE TITLE
[Tutorials] Reactor part of engineer tutorial can be skipped by just turning on automatic control

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8803]
Previously you had to widdle with the sliders for a bit before it allowed you to turn on auto. This is the reactor at the start of the tutorial, not the one at the end.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f1f26a76e5624cbf324ee7797ce68e1db2a1789c

Happened because the tutorial checks if the output matches the load for 2 seconds before moving on to the next stage, but the problem was the check was done while the popup was on the screen and the game paused (at which point the load is still 0, so just keeping that popup open for 2 seconds would complete that stage of the tutorial)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
