### ISSUE TITLE
Bots struggle to weld ballast in Typhon 2

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8838]
**Description**
title, video:
https://user-images.githubusercontent.com/59519434/163740841-c98d9a4b-2ab8-4fa4-bdf6-c5f494b18c48.mp4

**Steps To Reproduce**
Damage Typhon 2 ballast, observe. #8837 also happens in Typhon 2 ballasts often.

**Version**
Unstable

**Additional information**
According to Kaileris, deleting waypoint no. 85 fixes the problem
![image](https://user-images.githubusercontent.com/59519434/163740647-c6201b40-9492-4969-9056-face96704ea4.png)

**Comment by ekqvist** [comment]
Bots seem to be able to fix that wall from the Ballast C correctly now. I suspect this might have been fixed in commit Regalis11/Barotrauma-development@c8a7eb1 which introduced fixes to the hull fixing behavior.

**Comment by NilanthAnimosus** [comment]
Noticed on the Dev branch commit https://github.com/Regalis11/Barotrauma-development/commit/56b7828aed00a8e0297aa20ebff1bada2a35dd83

A breach here appears to be in a spot where the AI cannot pathfind too as well as the potential issues in the ballast.
![image](https://user-images.githubusercontent.com/29177976/201717409-71618749-b041-48e1-8519-e2cbe54a8b9c.png)

**Comment by itchyOwl** [comment]
After Regalis11/Barotrauma-development@facc37d, pathing to a gap between the ballast tanks failed again. Fixed that in Regalis11/Barotrauma-decelopment@2807e26, after which I couldn't repro any of the issues described above. So I think the previous fix managed to fix some edge cases, where a waypoint wasn't accepted, because it wasn't inside any hull connected to the gap.

**Comment by ekqvist** [comment]
Just adding a reminder here as well to also run a quick test on https://github.com/Regalis11/Barotrauma/issues/10686 while testing this as the changes can affect that issue as well!
