### ISSUE TITLE
Game does not launch without DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

### ISSUE THREAD

**Issue by famfo** [Regalis11/Barotrauma#8858]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game does not launch without `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` due to a missing ICU package.

![image](https://user-images.githubusercontent.com/44938471/164231037-483d0ff5-2e17-4914-a760-17921bb0d61b.png)

![image](https://user-images.githubusercontent.com/44938471/164231135-d5607b77-8475-48ee-a3bb-6388fe6ee70c.png)

**Steps To Reproduce**
Launch the game (from the command line) on (Arch) Linux.

**Version**
Game Version: Barotrauma v0.16.7.0 (ReleaseLinux, branch release, revision aa4c852c2c)
OS: Arch Linux 

**Additional information**
I have searched the repositories for a dotnet ICU package, but I did not find one which could resolve the problem.

**Comment by fulgensfulgens** [comment]
I got the same problem. I posted on the steam discussions and am glad it is not just me who has this problem so it gets more attention.

**Comment by fulgensfulgens** [comment]
Good day again. 
A friend helped me ask around and the Discord supp suggested installing the Package "icu63".
after doing so with paru and restarting steam the game now starts up again. 
Please try it and report back as well. hope it works for you too!

**Comment by famfo** [comment]
With the package icu63 installed the game does nothing. Not launching nor crashing. There is an icu package in the core repository, which is installed and the game apparently does not detect. 
Though I think it should be the responsibility of the developers to a certain extend to make sure that the game has all the needed libraries too run, and not the of the users on more minimalist Linux distributions like Arch.

**Comment by chrBrd** [comment]
Just run into this problem on openSUSE Tumbleweed which uses ICU 71.

The Steam Runtime doesn't include `libicu` and, as illustrated by this issue, relying on the system's version can result in things breaking (and new versions of ICU are released quite frequently, generally every 6 months).

I'm not a C# dev, but after a quick and lazy look into this it seems like using an [app-local ICU](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu) should ensure this won't happen again:

> Moving between versions of ICU can subtly impact app behavior when it comes to globalization-related operations. To help application developers ensure consistency across all deployments, .NET 5 and later versions enable apps on both Windows and Unix to carry and use their own copy of ICU.

**Comment by Captain-Rage** [comment]
Got the same problem on Arch Linux (64-bit, although that goes without saying these days).

'Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.'

This message is thrown when trying to start the game. Something must have happened in a recent system update.
The following packages pertaining to ICU are installed on my system:

local/harfbuzz-icu 4.2.1-1
    OpenType text shaping engine - ICU integration
local/icu 71.1-1
    International Components for Unicode library
local/lib32-icu 71.1-1
    International Components for Unicode library (32 bit)

Trying to start the game using Steam's own runtime libraries and the system native libraries makes no difference.

**Comment by EgorIII** [comment]
still an issue on latest unstable

**Comment by Jlobblet** [comment]
FYI you can also edit `Barotrauma.runtimeconfig.json` to have `"System.Globalization.Invariant": true` in the `configProperties` section.

A typical file may look like this:
```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "3.1.22"
      }
    ],
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
      "System.Globalization.Invariant": true
    }
  }
}
```

**Comment by EgorIII** [comment]
thank you, why isn't that shipped with the game if its so easy of a fix?
also you probably forgot a comma 
```
...
"System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
"System.Globalization.Invariant": true
...
```

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7cd128f26eaf7759cdc0cb63ab0ff3b98f294c8f

**Comment by Rokvach** [comment]
Haven't noticed any issues since the change, working correctly. Closing.

**Comment by Regalis11** [comment]
I unfortunately had to [revert](https://github.com/Regalis11/Barotrauma-development/commit/fd3388a7941569395db32821307e2221fbb8912e) the change, because it seems to break case-insensitive comparisons and converting to upper or lower case in non-latin alphabets.

So it looks like we're going to figure out some other solution to the issue (although, it's worth noting we don't officially support Arch).

**Comment by chrBrd** [comment]
@Regalis11 I've done some more looking into this:
- The breaking ICU version is ICU 71; ICU 70 and below (I tried down to 63.1) work without issue.
- I can get a release build to run if I download the [Ubuntu build](https://github.com/unicode-org/icu/releases/download/release-70-1/icu4c-70_1-Ubuntu-20.04-x64.tgz) of ICU 70 from [here](https://github.com/unicode-org/icu/releases/tag/release-70-1) and start the game with, eg. ` LD_LIBRARY_PATH=~/Downloads/icu70/usr/local/lib/ ./Barotrauma` (note, although I'm using the Ubuntu build of ICU to run the game my actual distro is openSUSE Tumbleweed).

As the [ICU license](https://www.unicode.org/copyright.html) permits redistribution (subject to copyright attribution) a possible solution is to bundle a compatible version of the ICU binaries with the game and load those instead of the system binaries.

Unfortunately, as mentioned above, I'm not a C#/.NET dev so I don't know how to do this properly (I've tried making a few modifications to `LinuxClient.csproj` without success), so I can't make PoC PR.

**Comment by Captain-Rage** [comment]
Following the instructions makes the game start on Arch Linux again. The binaries, as mentioned above, must end with *.70 (for example *.70.1 won't work, which is the suffix of the files in the linked archive).

**Comment by famfo** [comment]
If you launch the game inside the Steam Linux Runtime, the game seems to run just fine (you can enable it under Properties->Compatibility->Force the use of a specific Steam Play compatibility tool and then select Steam Linux Runtime from the list).

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/4093830f5cd11eb03b61c6f8ac594787a5442e6c (again). We're bumping the game up to .NET 6, which allows us to use project-wide invariant culture without breaking comparisons between non-ascii characters.

https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
