### ISSUE TITLE
Biological tests on living organisms and medi-pod

### ISSUE THREAD

**Issue by PreacherOfAtom** [Regalis11/Barotrauma#89]
Hello.
Having played at Space Station 13 for a while, I could see that we could experiment with chemicals to make other chemicals.
The Mod-pack "Chiko" has added a "Prisoner" job, where you only have an orange jumpsuit and nothing else.
The work does not matter if the game does not have a system of "tests".
My suggestion is:

- Doctors can use a console to mix several chemicals (example: Husk Eggs + Neurotoxin = Husk Virus that kills in the next few seconds, and if you add nytroglycerin, when the virus will activate the body will explode and you will die) and test the mixtures on the prisoners. You will probably say that this suggestion is of no interest if the work is not available in vanilla; you are right, that's why I ask the addition of the work "prisoner" on the vanilla version.

-Test mixtures on humans can make benefits or viruses, for example if you get to do a drug with Erythrozine and Husk eggs, you have a 75% chance to make a poison and 25% chance to make a drug that allows you to breathe in water without a mask. To see if the drug works, try on the prisoners ....

My second suggestion is : 
-As in the movie, Prometheus, a medipod can repair your serious injuries
For example, if you are infected with Husk eggs, you can go on the medipod, lie down and ask to remove the virus (70% chance to miss) or remove the alien in your throat to slow down the last symptoms (65% chance to miss) if the operation fails, you will start bleeding. To use the medipod, you must:

* Put bandages in the machine
* Put the drug to treat the wounds
* Put a battery
Each operation uses a battery.

Well, that's it!
I hope it will be added in the future!

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
