### ISSUE TITLE
[Dev version] Reactor does not make sonar noise

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#890]
Seems like in the dev version the reactor does not make any sonar noise even if it's overheating. Is that intentional?

**Comment by BillCombs** [comment]
Perhaps you could make it actually depend on the temperature, so it would have something like a low power idle mode(not making any sound when the temperature is low enough). You would be able to turn off most of the machines on the sub and only leave things such as oxygen generator powered. That would greatly help in singleplayer, when playing on subs that have low capacity batteries or don't have any batteries at all. Right now it's pretty hard to go for the artifact and keep watch on the creatures attacking the sub at same time. Just turning off the reactor would turn off the oxygen generator and kill the bots, unless the sub has a lot of spare oxygen tanks.

**Comment by Regalis11** [comment]
Actually due to the way the reactor works now, I don't think it should depend on the temperature. There's an optimal temperature range at which the reactor works properly (indicated by the red markers in the temperature bar), and the amount of generated power is determined by the turbine output. So when you want to go low power, you don't decrease the temperature, you decrease the turbine output (and fission rate to prevent it from overheating). I think instead the sound range should be tied to the amount of generated power.
