### ISSUE TITLE
Attempted to move the anchor of a limb's pull joint extremely far from the limb

### ISSUE THREAD

**Issue by LordCactuar** [Regalis11/Barotrauma#895]
![2018-11-07](https://user-images.githubusercontent.com/42049273/48176765-9b8b9280-e2df-11e8-8c8f-633f9cd535ce.png)

Getting error messages fighting naturally spawned Charybdis attacking from below my sub. Does not happen with console spawned Charybdis, or naturally spawned Moloch or endworm

**Comment by Regalis11** [comment]
7968207 didn't seem to have an effect, I'm still getting this in v0.8.9.2. I believe the problem has something to do with the characters only using the collider to move around (with the actual ragdoll being disabled) when far away from the players.

**Comment by NilanthAnimosus** [comment]
Looking further into this as it spammed the error approximately 2000 times from a find in files check. I found a fish far above the sunken sub in debugdraw with its collider heading into a rock (Well out of disable distance, near the starter outpost), its limbs floating down-right away from the rock, then teleporting back up to it. I think it may have gotten caught on something or gotten stuck. once the fish seemed to stop drifting its bodyparts away from its collider - the error stopped repeating.

The creature was perfectly visible for this, as I think it may have stopped only because the respawn shuttle was killed by a moloch which the creature was trying to run from.

since its disabled, it no longer is visible - But the error stopped while it has been disabled too, I think the error may repeat again once players respawn if the round lasts long enough (Its doubtful it will though).

![image](https://user-images.githubusercontent.com/29177976/52209887-33683080-287d-11e9-8537-c4493ab516d8.png)

**Comment by Regalis11** [comment]
I think this is fixed now, there haven't been any reports of this through GameAnalytics since ce33a52.
