### ISSUE TITLE
IsMale and IsFemale are always false for player characters

### ISSUE THREAD

**Issue by Mannatwo** [Regalis11/Barotrauma#8950]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Saving a game seems to serialize the gender tags improperly (are they case sensitive?), causing IsMale and IsFemale to both be false after saving and loading once. This hampers gender detection in xml status effects and breaks mods that rely on it.

**Steps To Reproduce**
- Start a new multiplayer campaign as any male or female character
- Save and quit
- Continue the savefile
- IsMale and IsFemale are now both false

**Version**
v0.17.12.0, Windows

**Additional information**
If I had to theorize as to what causes this, it is that IsMale and IsFemale check for case sensitive "Male" and "Female" tags, which are no longer present after loading, because they get converted to lowercase for saving.

**Comment by Krzeszny** [comment]
There is nothing like case-sensitive XML...

**Comment by Regalis11** [comment]
Turns out this wasn't cause by case insensitive, but happened because the IsMale and IsFemale properties only got updated when creating the characterinfo from scratch (not when loading it from xml). Should not affect the vanilla game, because we no longer use these properties (they're only included for backwards compatibility).

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c69b33b480b204c97f5752872d7afe0b15b9a5a0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
