### ISSUE TITLE
[0.17.12.0] Cave has no opening to reach artifact for mission

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8972]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/8558134/Multiplayer.zip)

**Version**
0.17.12.0

**Comment by Regalis11** [comment]
![image](https://user-images.githubusercontent.com/14351070/165299179-67ac8ca3-6ff4-4b45-809d-9a809aa23014.png)

**Comment by Kaillera** [comment]
Last night the mission spawned a Thermal Artifact for the mission in the cave to the right here
![Capture](https://user-images.githubusercontent.com/5086682/165327139-44f1cacb-5cf6-4c9f-8115-a1492fe80192.PNG)

**Comment by JamesTheAwesomeDude** [comment]
Sometimes, I get bugs like this.

How do I find the level seed to allow reproducing it later?

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/68d02ff7ba62555e380a24ff29b99b8a05450339, no issues found, closing.

Notes:
Successfully replicated the issue where the caves were too tight to traverse on 0.17.12.0 on the provided save (Though not the location the artifact spawned for me, it could potentially spawn there?). On later versions (around 0.19.5.0) this issue has likely been fixed by the fixes for #9414
