### ISSUE TITLE
Round ends prematurely in multiplayer

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Regalis11/Barotrauma#8985]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The multiplayer auto-restart code triggers if all living crewmembers are Downed, even if one/more of them has Hammerhead Matriarch genes and would have been able to recover and finish the mission.

**Steps To Reproduce**

1. Host a server _(1 player is sufficient to reproduce this; do not use bots)_
2. Start a mission _(or a Campaign)_
3. Obtain and apply Hammerhead Matriarch genes
4. Take enough damage to Down you
   * `giveaffliction "Internal Damage" 115 <playername>`
5. Observe that the round ends immediately
6. (Optional): Repeat the process in singleplayer; observe that the player is allowed to recover
   * Do not forget to get rid of your other crewmembers first in this case

This becomes extra relevant for Husked or high-Thresher-DNA players for whom suffocation while Downed is little-to-no threat.

**Version**

v0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)

**Comment by Regalis11** [comment]
I wouldn't consider this a bug: it was intentional that the server ends the round when everyone is either dead or unconscious. Even though in this specific case it'd make sense to wait and allow the character to recover, it probably wouldn't be a good idea to make the game wait for everyone to actually die: it could lead to unnecessarily long wait times if there's some stubborn player on the server who wants to wait their health bar to go all the way down before ending the round.

**Comment by JamesTheAwesomeDude** [comment]
So one concern with this is that HHM genes are too slow compared to, say, the Still Alive talent?

**Comment by Regalis11** [comment]
We've decided not to address this: it's a very rare situation, and there's a high chance it'd cause some unintended side-effects or loopholes if we allowed the round to continue when there's unconscious players around who might have a chance of reviving later.
