### ISSUE TITLE
Crash after equipping id card from wreck with any mod what replaced human.xml

### ISSUE THREAD

**Issue by Sharaj00** [Regalis11/Barotrauma#8997]
**Description**
Crash after equipping id card from wreck with any mod what replaced human.xml

**Steps To Reproduce**
Install any anime mod, find wrecks, equip id card from corpse

**Version**
0.17.12.0

**Comment by Sharaj00** [comment]
https://pastebin.com/fgxyj7f4

**Comment by Sharaj00** [comment]
another one https://pastebin.com/BpMPjJuC

**Comment by Regalis11** [comment]
Thank you, I think I managed to fix this now: https://github.com/Regalis11/Barotrauma-development/commit/eeac8fdee590c17b9592e4d22bdaa0e6af26b741 (link to our private repo).

Note for testing: this seems to require that you cover your face before equipping the ID card, because it happens when trying to fetch the sprites of the ID card's owner to display on the character portrait.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
