### ISSUE TITLE
Indestructable, Unburnable Ballast Flora?

### ISSUE THREAD

**Issue by Araxiel** [Regalis11/Barotrauma#9024]
**Description**
Ballast Flora seems completely impervious to damage. No matter how much I throw at it. Even with a completely destroyed Pump, still continues. Video (4min44) recording of a test run after multiple failed attempts:
https://youtu.be/XeYcooxa0ok

**Steps To Reproduce**
Get a Pump infected by Ballast Flora

**Version**
v0.17.15.0

**Additional information**
I tried everything. Followed all the steps people are saying online. No water. Pump offline. Pump got even destroyed by the end. Based on the 200 HP, 4 incendiary grenades each doing 50dmg should take care of it, together with a raging inferno.
I would have also tried a flamer, but all the Military Outposts turned into Colonies, and Colonies don't sell flamers, only Military Outposts; and Flamers are also non-craftable.

**Comment by Regalis11** [comment]
Something to note is that ballast flora now regenerates health, and the bigger it gets, the faster it regenerates. It _could_ be that it had gotten so large here that the only way to kill it is to prune it first. I'm not completely sure about this though, the fire was so large that it should've killed the branches easily.

Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/eebc967fd9e1f451a88d52e4c11da0a58b67b39d

**Comment by CurePindal** [comment]
We just got an immortal ballast flora on x.18.4 yesterday on our dedicated server.

Was noticed when we docked to a station. BF was pretty small but when the health bar was down it didnt die.
We undocked, tried again, no change, re-docked, tried again, no dice.

Here's the save: (rear ballast tank)
[SaveImmortalBallastFlora.zip](https://github.com/Regalis11/Barotrauma/files/8825756/SaveImmortalBallastFlora.zip)

**Comment by Regalis11** [comment]
I unfortunately couldn't repro the issue in the save: the root seems to be gone in the save, and the flora automatically withers down and disappears after a while. I did notice an issue in that save though that could be related to it being unkillable, which I fixed in https://github.com/Regalis11/Barotrauma-development/commit/2299813f4967a82f8b2c33c1207fc83e3c5dac76:

> Fixed ballast flora branches that have been disconnected from the root not being considered disconnected after a level transition (allowing them to keep growing).

**Comment by Rokvach** [comment]
Tested, haven't had any issues killing a ballast flora after the fix. Working correctly, closing.
