### ISSUE TITLE
Client can't syncs with changes about SavedStatValue

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#9056]
Actually there is now something wrong with SavedStatValues, as the title said.
No arguments were provided when creating UpdatePermanentStatsEventData:
```csharp
partial void OnPermanentStatChanged(StatTypes statType)
{
    if (Character == null || Character.Removed) { return; }
    GameMain.NetworkMember.CreateEntityEvent(Character, new Character.UpdatePermanentStatsEventData());
}
```

**Version**
0.17.15.0

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/3dddbce4ca334063e471cddd3675a70ba81d34a3.

I couldn't find any talents this would've caused any noticeable issues with though; unlocking the talent seems to set the stat values correctly even though they're not synced separately. Did you notice a problem with some specific talent?

**Comment by zhu-rengong** [comment]
No, it seems to be ok for Vanilla.
I hosted a modified executable server that has the mod directly changes the SavedStatValues.
I noticed something strange happening, and finally figured out the reason what caused that issue.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
