### ISSUE TITLE
machines can't send signals to themselves via junction box

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9175]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

in editor mode, I wired up a reactor as follows:
White wire first, then blues, then green

![image](https://user-images.githubusercontent.com/5103517/169436113-1bab35aa-790a-47ff-93d0-713762d492fb.png)

the reactor wasn't being controlled!

I hooked up a terminal, to the signal pin, it was recieving values as expected, 

### Reproduction steps

wired up a reactor + JB as above picture:
White wire first, then blues, then green

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Varangianoi** [comment]
It is probably because of this. So if I'm not wrong: if the receipent item is the Junction Box itself or the source of the signal, don't pass it.

[                if (recipient.Item == item || recipient.Item == signal.source) { continue; }](https://github.com/Regalis11/Barotrauma/blob/c81410b83eabdb455e7bef08e9b87feac16ee390/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Power/PowerTransfer.cs#L424)

You can test it by connecting a Terminal to a Junction box' signal pin, then connecting that to the Terminal itself again, and it won't return the signal to the Terminal. However, if you connect that signal to another Terminal, that one will receive it.

I don't know if it's intentional or not, but it'd be good if it worked.

**Comment by cshingle** [comment]
> It is probably because of this. So if I'm not wrong: if the receipent item is the Junction Box itself or the source of the signal, don't pass it.
> 
> [ if (recipient.Item == item || recipient.Item == signal.source) { continue; }](https://github.com/Regalis11/Barotrauma/blob/c81410b83eabdb455e7bef08e9b87feac16ee390/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Power/PowerTransfer.cs#L424)
> 
> You can test it by connecting a Terminal to a Junction box' signal pin, then connecting that to the Terminal itself again, and it won't return the signal to the Terminal. However, if you connect that signal to another Terminal, that one will receive it.
> 
> I don't know if it's intentional or not, but it'd be good if it worked.

I am pretty sure this was intentional. Before the power rework Junction Boxes were pass though and not treated as a "source" or "sink". This avoided needing to touch each intermediate junction box for each connection each update. I am betting that signal connections are using the same/similar logic. I bet if you use a relay or any other item that gets updated each tick it will work as expected.
