### ISSUE TITLE
[DEV] When you hold something in hands and complete mission, item in first cell disappears

### ISSUE THREAD

**Issue by Diffle** [Regalis11/Barotrauma#918]
I'm holding gun in hands, which, let's say, in 5 inventory 'cell'. After completing mission, item in first cell disappears, and item which you held in your hand moves to first cell, eg screwdriver disappears and gun moves to first cell

**Comment by BillCombs** [comment]
Doesn't seem to be an issue for me. The items change their positions, but they don't disappear.
![-2018-nov-17-005](https://user-images.githubusercontent.com/38168249/48661901-3b011000-eaac-11e8-8e26-0c044858004c.jpg)
![-2018-nov-17-007](https://user-images.githubusercontent.com/38168249/48661904-3d636a00-eaac-11e8-87ab-a62049f074e9.jpg)
Do you need to hold something special for the bug to happen?

There is a small problem when the character holding the items in the extra slots:
![-2018-nov-17-009](https://user-images.githubusercontent.com/38168249/48661908-3f2d2d80-eaac-11e8-9bd2-922c191514cb.jpg)
![-2018-nov-17-011](https://user-images.githubusercontent.com/38168249/48661909-405e5a80-eaac-11e8-9de8-653950dcae79.jpg)
But the items don't disappear in that case either, they just get dropped at the position of the character(Though i think this still shouldn't happen. This problem could lead to getting your items lost in random places, or getting them stolen by other players in multiplayer).

**Comment by BillCombs** [comment]
Okay, so this problem seems to be a bit complex, there are a couple of different things than can happen and different interactions needed for that. I got some info about it, but could easily mess something up or just understand the problem incorrectly, so i suggest doing your own testing as well, if necessary.

**A couple of videos with the examples:**
1: https://streamable.com/zzc3p
2: https://streamable.com/g6374

**Text description of the videos**, in case some part of the videos is hard to understand(Most likely not necessary, but i (poorly) made it anyway. Just **skip it**, if you understand the things going on in the videos):

**What you can see in the first one:**
The player's inventory is full of 2-handed items. They pick up a 2-handed item, it gets added to the extra slots. They switch the item in the extra slots with an item in one of the [1-0] slots. The item that has been in the [1-0] slot drops on the ground and becomes impossible to pick up(until the next mission).
Then comes a similar test with picking up another 2-handed item, giving similar results.
But then the player picks up 2 1-handed items, they get added to the extra slots, and the player switches them with a two-handed item in one of the [1-0] slots, and the two-handed item from that slot just disappears. A couple of seconds later the player repeats the test with the second 1-handed item and gets the same result.

**What you can see in the second one:**
The player's inventory is full of 1-handed items. They pick up a 2-handed item. It gets added to the extra slots, They switch the 2-handed item with one of the 1-handed items in one of the [1-0] slots. The latter drops and becomes impossible to pick up(until the next mission).
Then the player repeats the first test from the first video, gets results similar to the first video. After that the player repeats the last test from the first video, gets a bit different results. The 2-handed item disappears, but you also drop a ghost of the 1-handed item from the extra slots. If you keep watching it, you will notice that it disappears after the player unequips the actual items. At the end the player switches 1-handed item from the extra slots with a 1-handed item from the [1-0] slots, getting results similar to same actions done with 2-handed items.


What we can get from the videos + what i got from more tests:
-
- Switching a 2-handed item from extra slots with a 2-handed item from slots [1-0] makes the item from the [1-0] slot drop and become impossible to pick up until the next mission.
- You get same results when doing the action above with 1-handed items.
- Switching a 1-handed item from extra slots with a 2-handed item from slots [1-0] makes the latter disappear. Also, it does not matter if the 1-handed items are only occupying 1 extra slot or 
occupying both of the extra slots.
- Sometimes the action above makes you drop a ghost of the 1-handed item that disappears once you unequip the real one.
- Also, the action above does not create the bug in case of items getting switched by the game at the end of the round. They just get dropped.
- The disappeared items come back at the next mission.
