### ISSUE TITLE
[Unstable] Autofill no longer fills items after switching to new sub (welding tools, plasma cutters...)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9184]
**Description**
Items on autofill will not fill when you change subs in campaign
![image](https://user-images.githubusercontent.com/73229309/169607493-649fca9e-4dc1-4baf-832e-73318327c6e9.png)

**Steps To Reproduce**
Buy a new sub in campaign
Check the supply cabinets

**Version**
 Unstable v0.18.3.0

**Comment by Regalis11** [comment]
Now autofilling only happens when you first start the campaign - when you switch the sub, items from your old sub get automatically transferred to the new one, but you aren't given any new items.

I couldn't repro this in the vanilla game (which was expected because there's no empty masks or cutters in the subs) - did this happen in some custom sub, or had you emptied these items in the initial sub?

**Comment by ubertpendragon** [comment]
This happened on a custom sub

The supply cabinets themselves don't have Autofill, they're pre-filled with what's on the screenshot.
Those items have autofill though, and don't get filled

If you start the campaign with the sub they're properly filled

Guess that's not a "bug", just a side effect of the new system that will take getting used to

**Comment by itchyOwl** [comment]
Yeah, it's intentional that the items spawn only at the start of the game, because otherwise we'd need different definitions for the items that should spawn only at the start and not when you switch subs. When you switch the subs, the items from your old sub now automatically transfer with you to the new sub, and the change in how it works is related to this: it would be messy to get e.g. diving masks for each supply cabinet when you switch the subs + the items from your old sub. You'd quickly have too many diving masks to be of any use, other than selling. And we'd have to take that into account when balancing the economy. So it's just simpler this way.

Moreover, we now use mostly StartItems.xml to define the start items, and spawns defined in PreferredContainer elements of the items mosly for the loot (wrecks etc). Both systems can be used, however.

And the items you manually place in the subs, are ofc always there when the sub spawns the first time. So to fix your manually placed items: just manually place the oxygen tank and welding fuel inside them.
