### ISSUE TITLE
Unable to publish submarine.

### ISSUE THREAD

**Issue by TerraPlanet** [Regalis11/Barotrauma#9185]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So I've made two subs and decided that I'd try to publish them to the workshop because I spent a lot of time on them. And well. When I try to do that it says, "Publishing 'shipname' in the Steam Workshop failed. "

### Reproduction steps

1. Make a sub.
2. Attempt to upload it.
3. Fail.
4. Cry.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Publishing 'shipname' in the Steam Workshop failed.
```

**Comment by Regalis11** [comment]
This could possibly be caused by a too large preview image (they need to be less than 1 MB) or by running out of storage space in the Steam cloud. There's an issue in the current public version that causes the game to display this generic error message instead of the more specific error message if publishing fails due to those reasons.

**Comment by TerraPlanet** [comment]
Okay yeah. The image was above 1 MB. I'll try to get it below that and I'll tell you what happens.

**Comment by TerraPlanet** [comment]
I compressed the image using an image compressor and it worked! It seems that the only issue is it being above 1 MB. Thanks for the tip.
