### ISSUE TITLE
Throwable Drugs prevents status effects by self using from applying unless Aimed.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#92]
Tested on Commit 26216a "Fixed Fish being Selectable" on branch master.

Unless you are holding right click (Due to code in Item.Components.Throwable) the status effects of various drugs (Both negative and positive) for corrigodone, auxiliorizine, liquid oxygenite and other such throwable drugs does not take effect.

Despite not granting the status effect it still uses up the condition of the item from the medical syringe itself.

If right click (Aim) is held when clicking the "Use" button above the held item - the effects will be triggered correctly but you will also swing your arm with a syringe to attack possibly injecting other characters.

**Comment by Crystalwarrior** [comment]
Confirmed, needs to be fixed before official update

**Comment by Crystalwarrior** [comment]
Plus if they're in syringes even aiming them seems to do nothing

**Comment by Crystalwarrior** [comment]
#f0225e43129dd2c7959aac7165d4c682ed256046 Seems like the underlying issue here is that for "Holdable" type, "onUse" returns True no matter what.
Perhaps "onUse" should be moved to "onThrow" so the Throwable class doesn't override "onUse" and have different, special things happen? For example: trigger "onUse" to activate the Incendium Grenade timer, flare, etc. while "onThrow" would be used for, say, throwing knives or something, where "onThrow" would propell the knife in a special way.
Just brainstorming here.
