### ISSUE TITLE
Replace "Set Default Bindings" and "Set Legacy Bindings" buttons in keybinds with a single button "Reset Keybinds"

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9243]
Both of those buttons doesn't seem to do anything anymore and I think we should just deprecate the legacy bindings entirely

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/146f630455d36a3c57cc31661f0a2c1b79029f3d

**Comment by Rokvach** [comment]
The reset button doesn't seem to be working, tested by changing the Health key from H to J and hitting reset and nothing happens.

**Comment by Regalis11** [comment]
Resetting the binds seemed to work, the problem was that the inputs displayed in the menu didn't get refreshed. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/96b2b1269179cec935a97b0c4ef364b86fd2b947

**Comment by Rokvach** [comment]
Tested already and didn't spot any issues, this ticket can be closed if there is no further adjustments after review

**Comment by Ek-Videogames** [comment]
**In a tangentially related issue:**
Component placement probably needs to be included in the tutorial somewhere 
_(or a new selection tooltip appears when "aiming")_
because not a single person has been able to guess that the "improved" keybind for it is E without being told it.

- Alternatively: **how about no?** Being able to aim & shoot guns while on ladders without letting go, selecting items/containers without having the input eaten by a random corpse on the ground, and interacting with doors & buttons being separated from interacting with inventory all seem like pretty useful reasons legacy keybinds are still used by people.
