### ISSUE TITLE
One time use alien artifact/tool that would scare all of the creatures away from it for a short period of time

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#926]
As usual, this is just an idea/suggestion. I have no clue how easy or hard it is to implement this. Feel free to decline it or change it however you want.

---

 It would be nice to have something like a last resort kind of item that would help you in a dire situation.

 Imagine falling to the bottom in areas heavily populated by creatures. You could easily spend all your railgun ammo in an attempt to get rid of them all but still have a lot of them surrounding your submarine, making it impossible for you to fix it and get out of that place. 
 You could try turning off everything, including the reactor, but you still have to turn it on again to pump the water(unless your sub has powerful batteries), and in such crowded areas you still have a big chance to attract something again, making it really hard for you to finish the mission or even just get to either of the checkpoints alive.
 That's when that artifact could save you. You have no more ammo, and are surrounded by a ton of creatures breaking your sub. You turn off everything, wait for them to go away, fix the hulls, then start the reactor to pump the water; notice that a lot of the creatures are coming back, activate the artifact and get out of there while your sub's hulls are not leaking and the creatures are running away.

 Or you could use it before that situation happens. Trying to get to the next checkpoint, notice that a lot of them are coming for you, use the artifact and keep going while they are away.

 Would also help if you needed to hold them off while your sub is maintaining position during the artifact missions.

 The amount of time the artifact should be working is about 30 seconds. Not too much to be OP, but enough to do something during that time.
 Activation probably should require you to hold m1 for a bit, so you wouldn't accidentally activate it when you don't need it.

If you make it look like its effect is soundwave based, you could also make creatures, that have no hearing(like Watcher), immune to it.

It should probably give something like fulgrium and steel upon deconstruction, but, if you used its powers, it should look scorched and only give you some steel.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
