### ISSUE TITLE
Pump causes rubberbanding when rewiring it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9269]
**Steps To Reproduce**
1. Load up Dugong in multiplayer
2. Go into one of the ballasts
3. Take all wires off from the pump
4. Set the pump to pump out while it doesn't have any wires attached
5. Plug power back to the pump
6. Notice that there's rubberbanding when your character moves around in the ballast and the oxygen low affliction flashes

**Version**
0.18.6.0
Branch: bugfixes

**Comment by Regalis11** [comment]
The issue turned out to be pretty severe: the server didn't refresh the power grid when a wire was reconnected, causing it to think the pump is still unpowered (which meant the ballast was flooded server-side, but got pumped empty client-side). Didn't affect just pumps, but all powered items. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/74cdce003404f64220c113293acdcfa83356ba33

**Comment by Regalis11** [comment]
Looks like there was another issue here too: the water level in the hull should've been corrected by the server, but it wasn't. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f203a2e81cdff4f9054605e4e3c59af00e01025

Fixed hull updates not being sent if the water/oxygen/fire in the hull doesn't change server-side, preventing the hull's status from getting corrected if a client somehow ends up out of sync (see https://github.com/Regalis11/Barotrauma/issues/9269). Caused by the changes in https://github.com/Regalis11/Barotrauma-development/commit/a443dfe23501983d2cbb18787e4e1445da1a08f3

**Comment by Rokvach** [comment]
Tested this, I noticed if I failed to unwire/wire it would set the pump out of sync

1. Play with a very low electrical skill
2. Unwire the set_targetlevel from a ballast pump
3. Wire it back into the pump but fail
4. The ballast keeps constantly refilling

**Comment by Rokvach** [comment]
Tested, wasn't able to repro the issue anymore, the temporary fix seems to be working correctly. Closing.
