### ISSUE TITLE
Scientist, capturable/tameable creatures

### ISSUE THREAD

**Issue by yaelatletl** [Regalis11/Barotrauma#93]
Creating a mission where a crew member spawns as a "scientist" who's capable of handling europa's small beasts that wants to capture an alive specimen for research or making it an actual job, allowing crews to get a "tamed" mantis or crawler (husk wouldn't be tamed as they are more zombie-like) [if tamed, they should be persistent through the campaign]
The process could be dangerous, as it involves stunning the creature and then using chemicals or an item (just like the handcuffs) to make it docile, friendly or at least make it unable to move or attack.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
