### ISSUE TITLE
[Suggestion] Headless bodies without an ID should be unidentifiable.

### ISSUE THREAD

**Issue by Pugie** [Regalis11/Barotrauma#932]
From my viewpoint it only makes sense, a body with a mask and no ID is very much unidentifiable, so why shouldn't the same apply to someone who has lost their head?

**Comment by BillCombs** [comment]
It would also be interesting if you were able to destroy or mutilate body parts beyond recognition when playing as a human. Smashing somebody's head with a crowbar till it cracks into pieces, making the victim unrecognizable. You would be able to play like a real maniac, leaving crime scenes full of blood and gore, and also making it harder for the crew to know which one of the crew members is just not talking and which one is actually dead. Making them play like detectives, trying to find out the reason of the murder and the murderer. Kinda like a murder mystery game.

**Comment by rico6822** [comment]
Why won't we just allow players to recognize each other after other body parts? All slots would have to be filled with clothing to hide identity.

**Comment by BillCombs** [comment]
If assuming that members of the crew usually aren't close friends or relatives(you can hire new ones at almost any checkpoint in the campaign, so they must barely know each other), they most likely wouldn't know the exact look of their colleagues' bodies.
Players could easily figure out the identities themselves by process of elimination, if they only had about 4 members in their crew, or if only a couple of crew members were dead.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
