### ISSUE TITLE
Poor performance from AIObjectiveRescue

### ISSUE THREAD

**Issue by Mannatwo** [Regalis11/Barotrauma#9329]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Having many bots trying to rescue someone when theres many suitable treatments available and afflictions on the target causes a considerable increase in computation time.
My guess as to why this happens is that the objective tries to look for the suitable treatment items on the submarine more often than it should. I understand that theres not much one can do to get the suitable treatments other than looping through all items, but considering how expensive that can be with the amount of items people like to hoard I think it would be best to put that logic on a cooldown.

Heres a link to the code which I believe to be the main offender in this situation:
https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveRescue.cs#:~:text=.Clear()%3B-,foreach%20(KeyValuePair%3CIdentifier%2C%20float%3E%20treatmentSuitability%20in%20currentTreatmentSuitabilities,%7D,-if%20(itemNameList

Image: excessive computation time from rescue objectives
![image](https://user-images.githubusercontent.com/103883287/173350734-1eb87184-4c3f-4dd2-bdc1-33b0b9519e32.png)

### Reproduction steps

1. Start a game
2. Spawn a bunch of crew bots
3. Remove items the bots could use to treat someone
4. Give the bots the rescue order
5. Injure one of the bots in numerous ways, aiming to produce the largest collection of different suitable treatments
6. If theres no medical items around, the bots should continuously search for some, hurting performance considerably

### Bug prevalence

Happens regularly

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I doubt the code in question is actually the cause, since it only runs when the bot has reached the patient and is trying to decide which meds to use. There's also a cooldown of at least 0.5 seconds, so if this was the cause, it should cause occasional freezes or hitches instead of a constant performance hit.

We did identify one clear performance problem with AIObjectiveRescue and have a fix coming up in the next update (and already up in the unstable branch): that was related to the FindBestHull method, which the bots use to find a safe hull to bring the patient to a safer room. However, I don't know if that can be the cause here, since it doesn't seem like there's any bots in dangerous (e.g. flooded) hulls here.

But in any case, I'll take a closer look at this and see if I can pinpoint the cause.

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.0 commit https://github.com/Regalis11/Barotrauma-development/commit/c81ad82458d0f6e3570943db493ed7bacba2c5e7

Notes:

Using a combination of rapid fissile accelerator, acid grenades and some SMG shots, with over 10 AI's on the heal and rescue order I saw no perceptible increase in performance cost on showperf.

there was a perceptible increase in update costs for characters (going from around a 1-2 to 4-6 and sometimes just barely seeing a 10 for fractions of a second) when every single AI was simultaneously ended up trying to find diving suits as a result of various submarine flooding in the hulls between the rescue target and the AI, but not on the levels anywhere close to the poor performance seen above.
