### ISSUE TITLE
[Unstable] Deep Sea Slayer and Gene Harvester talents make items drop outside of their inventory

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9330]
**Description**

Deep Sea Slayer and Gene Harvester make enemies drop alien materials and genees
I assume any enemy with an inventory can drop these. 

Enemies have limited inventory slots, and when these talents trigger, more items are generated that there are inventory slots. 
Excess items drop outside and fall to the abyss.

For example, Crawlers only have 2 inventory slots but can drop 4 different item types (Blood, Mask, Genes and Alien materials).
Some enemies (hatchlings) don't have inventory at all

It also affects enemies that are intended to be "swarm" types like hatchlings and Leucocytes, which typically drop tons of alien materials via Deep Sea Slayer

So the problem is two fold:

1. Items dropping (lack of space)

2. Excessive rewards on small enemy types

**Comment by JeroonBosch** [comment]
This is likely still relevant with the new talents

**Comment by JeroonBosch** [comment]
We should fix the 'swarm' enemies dropping genes still, which will require code to flag these enemies as not being able to drop gene materials

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/3cf59ccb6dbeb077a2a9200dddac7eec49ccd240

There was no need for any code changes, AbilityConditionCharacter can be used to check arbitrary properties of the character

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b

It appears Mudraptor_unarmoured has a one slot inventory defined in its three inventory definitions which may cause issues.

The same occurs with watcher which has a second 2 slot inventory defined (that already contains an item) which may have insufficient space. (Note - this one is below the AI tag, with another inventory definition above the AI tag?)

It appears (and I am not sure why actually) that fractal guardians do not spawn blood, but the curious thing is I imagine their a monster and probably have a decent mass, but I wouldn't expect them to spawn blood either (Just don't understand what is excluding them there and if it is worthy of note mechanically speaking).

Bloody Business uses target "Large" to filter this, while genetics uses minimum health of 25 (To include crawlers and mud raptors I assume). doesn't appear (from what I've seen) to spawn alien blood on any small characters though.

Otherwise this does work correctly, smaller creatures do not spawn alien blood or genetic materials.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddc77fccea321c7232eff32f10373cbfc20d2b3f

**Comment by itchyOwl** [comment]
Some comments on this:

> make items drop outside of their inventory

and 

> Items dropping (lack of space)

I couldn't repro this nor should this happen. There's "SpawnIfCantBeContained" property in ItemSpawnInfo that can be used as an attribute for the `<spawnitem>` elements, but it defaults to false and doesn't seem to be set "true" anywhere. Without doing that, the items shouldn't spawn if there is no inventory or enough space in it. And if this does happen, it could be a bug in the item spawn logic in StatusEffect.cs or maybe in the item spawn definitions.

> It appears (and I am not sure why actually) that fractal guardians do not spawn blood, but the curious thing is I imagine their a monster and probably have a decent mass, but I wouldn't expect them to spawn blood either (Just don't understand what is excluding them there and if it is worthy of note mechanically speaking).

What blood do you mean? Alien blood is spawned by explicitly adding it in the inventory definitions in the character xml file? Fractal guardians obviously shouldn't spawn any blood (nor bleed).

**Comment by itchyOwl** [comment]
> It appears (and I am not sure why actually) that fractal guardians do not spawn blood, but the curious thing is I imagine their a monster and probably have a decent mass, but I wouldn't expect them to spawn blood either (Just don't understand what is excluding them there and if it is worthy of note mechanically speaking).

It seems that "Large" means greater than 50, which will exclude Fractalguardians with the mass of ~35:

![image](https://user-images.githubusercontent.com/5370738/205256314-d7f29e77-74a5-4648-93d6-46c0e5a01be8.png)

> It appears (and I am not sure why actually) that fractal guardians do not spawn blood, but the curious thing is I imagine their a monster and probably have a decent mass, but I wouldn't expect them to spawn blood either (Just don't understand what is excluding them there and if it is worthy of note mechanically speaking).
> 
> Bloody Business uses target "Large" to filter this, while genetics uses minimum health of 25 (To include crawlers and mud raptors I assume). doesn't appear (from what I've seen) to spawn alien blood on any small characters though.

I don't think we should keep relying on mass as much, because they may not stay the same. If for instance, I could need/want to change the mass of some limb of Mudraptor. And if we rely on masses, every such case might break if I did so. Moreover the mass can only be seen by debugging the code, so it's impossible for a designer or a modder to work with them. So, I think it would be better to use the actual parameters of the characters. Maybe we need something like a Size, an arbitrary value (maybe defaulting to the mass)? However, if we do use masses, it's better to be explicit with it, like on "gene harvester":
![image](https://user-images.githubusercontent.com/5370738/205258461-2f150ca0-fab4-4969-92bf-8281dca16916.png)

**Comment by itchyOwl** [comment]
Changed to using a explicit mass conditional instead of the "Large" target type in Regalis11/Barotrauma-development@3efaec2 (dev).

**Comment by itchyOwl** [comment]
Actually checking against the max health might be sufficient for the most cases. After a brief discussion with Jeroen, decided to change the condition to check the health and "is machine" instead. Also the description is now updated in Regalis11/Barotrauma-development@8009c3d (dev).

**Comment by JeroonBosch** [comment]
Since the definition of 'large' is quite vague, we could go with an approach instead of
"When a monster drops at least one Alien Blood, it drops one more"?

Otherwise, we should also take care to exclude Husks.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
