### ISSUE TITLE
Plenty of small bugs I do not like..(and small features I'd like). [dev version]

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#935]
This is a list of bugs I dislike that cause the dev version to be clunky imo

1. There should be more blood for the gun and less recoil caused by it (to the victim and shooter)
2. The husk tongue has been glitchy since forever, it needs to stay in the mouth
3. Some enemies really need to slow down (husks the new crawlers and mantises) when inside the sub.
4. Mantis limbs are glitchy
5. When running at a door and someone closes it looks like you're on the other side but you're actually back on your side
6. getting crushed by doors is annoying
7. making the gun in the dev version shoot lasers will go against trying to have good aim and kills the tension when hoping to strike a moloch with a torpedo right in the sweet spot
8. I'd like for the deaths to be a bit more gruesome, specifically the human ones ;)
9. remove the "10 xp" or whatever that shit is, there is no need to make someone feel good over repairing a wall
10. propeller should obliterate any humans, injure huge monsters, kill small monsters, and fuck up the shuttle beyond repair upon contact
11. propeller should break if coming into contact with a rock, thus needing a crew member to exit the submarine and try and fix the propeller from the outside
12. on that note more things need to be fixed specifically from the outside to add tension
13. don't use the new diving suits from your twitter unless you're going to completely revamp the husk's visuals
14. i love the new coral and leaves and the visuals you added outside the sub don't remove them ;)
15. I'd like it so that the clown gets a banana peel which he can throw to make crew members slip ;)
16. the sonar flora look like cum bubbles, idk maybe have some solar flora look different from the other solar flora
17. players should be more encouraged to explore the non lethal part of the abyss, to add tension ;)
18. I think you should implement some of the instruments bte introduced, they gave atmosphere
19. text box should be located in the lower right corner
20. the endworm is pretty lazy imo, as of now. it'd be cool if enemies like it would grab onto the sub and drag it into the abyss or something

------------------------

Anyways that was a list of things I don't like about the dev version and things I like, and what I want changed. Other than that I'm looking forward to the new game, as the new visuals are not as much of a culture shock to me as they were a few months back. 

Good luck!

**Comment by Regalis11** [comment]
Thanks for the feedback again! :)

1. The recoil has been reduced recently, I think you might be playing an older dev version?
2. Yeah, we're aware of the problem with the husks's appendage, but haven't done anything about it yet because the husks are going to be remade soon (new art, new ragdoll, new animations).
3. I think we should have monsters that can move very fast inside the sub, although not all of them should be like that. The new mantis and husks are still a work in progress, and at least the mantis is most likely going to be a lot slower than it is now. The husks could also work better as a more zombie-like slow enemy.
4. The new mantis hasn't been implemented yet, and we haven't bothered fixing the old version or the very unfinished test versions because they're going to be replaced soon.
5. This is caused by inaccuracies in the network syncing. Something we need to work on, there's quite a lot of rubberbanding and issues like this especially when the latency between the client and server is high.
6. Agreed
7. The idea was to have the coilgun as a more lightweight machine gun type of weapon that'd be effective against large numbers of smaller enemies, and keep the railgun as a way to deal with the larger monsters. I think with a little bit of balancing we can make their roles more distinct (now the coilgun is way too overpowered).
8. I believe will add a bit more to deaths later, including death sounds and some more particle effects. :)
9. I'm not that fond of the XP texts either, but I think there should be some way to communicate it to the player when they gain XP. Not only to make it easier to follow how your character progression is going, but also as a small "reward" when the player completes a task successfully.  
10. The propeller already damages characters. The new engines however have the propellers placed inside a sort of protective cylinder which would prevent shuttles from colliding with it.
11. Perhaps
12. I agree, we're planning on making the railguns and coilguns destructible. #765
13. We are going to completely revamp the husk, as well as all other monsters. The diving suit sprite you saw on Twitter was not final though, so don't expect the husks to look like that in the new version. :)
14. Thanks, again the kudos go to our artist Iiro.
15. I'd love to have some more comedic relief items too, we'll see about banana peels once we get rid of some more high-priority stuff on the todo list.
16. I really like how the sonar flora looks. They're supposed to look nasty, so I don't think we're too far off if they look like "cum bubbles". :)
17. Agreed. We're planning on adding some more collectable resources to the levels (plants, minerals, creature parts) to encourage exploration outside the sub. The alien ruins are also currently being revamped, they'll also going to be much more interesting to explore.
18. Yep, I agree that we should add more variety to the devices and items. So far we've been mostly focusing on improving the core gameplay and existing items, but once that's out of the way, we'll start looking into adding more content (including new items).
19. See #936 
20. The endworm will be reworked just like the rest of the monsters.

This kind of feedback is really useful, but in the future I think it'd be preferable if you posted it on the forums. GitHub is more suitable for concrete "add feature X" or "fix bug Y" -type of requests and issue reports - when the requests are more open-ended like this, it's harder to figure out if the issue has been resolved and if it can be closed. Each issue report should also be one feature request or bug report, because including multiple ones in the same report again makes it more difficult to keep track of what has been resolved and what has not.
