### ISSUE TITLE
Purely visual issues

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#937]
I personally think that the moloch from your twitter is the most majestic moloch I've ever seen, it looks amazing.

But I don't think its art style would fit with the rest of the visuals from the game (like the humans or rokcs), so on that note, I think if we were to go full on with that moloch idea of yours, it'd be better to keep the art style consistent.

Thanks in advance, moi.
![image](https://user-images.githubusercontent.com/41457828/48974190-e535e600-f01e-11e8-9042-72bc5a407891.png)

**Comment by Regalis11** [comment]
Thanks for the compliments (kudos go to our artist Iiro)! We will definitely keep in mind that the artstyle has to stay consistent when implementing this. It will not look exactly like this in any case because of the way the ragdolls are built from multiple rigid parts, but I'm hoping we can get pretty close and make it blend in nicely with the rest of the art.
