### ISSUE TITLE
[Balance] Increased prices of all items, especially Steel Bars, broke the balance of the whole game

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9370]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Update 0.18 was supposed to reduce crafting spam by decreasing **deconstruction** yield, not by increasing fabrication costs. Increasing fabrication costs wasn't even mentioned in the patchnotes!

This change is easily the biggest balance change this game has seen since making items stack.

Steel is the most basic material, used to craft everything, starting from Storage Containers (which are now luxury items, costing 2 Steel Bars), to a Harpoons and Railgun Shells (which also cost 2 Steel Bars). 

Some of the problems this causes:
1. Making 50% of the iron useless (because 2 Carbon is required to craft a Steel bar) _increases_ crafting spam by incentivizing players to craft crowbars (to skill up Mechanical) or knives (to skill up Weapons) with unused Iron because of the lack of Carbon.
2. Railgun shells were already expensive when they costed 1 Steel bar, now they're twice as expensive.
3. Storage containers became luxury items.
4. Harpoons still require the same volume of steel as Railgun shells to craft, which still seems silly, and they're very expensive for how easy they are to lose.

### Quadruple nerf

It could be argued that there were 4 nerfs at the same time:

1. Making items sell for 25% of their value
2. Making all items cost more, especiall Steel Bars and Railgun Shells
3. Making deconstructing lossy
4. Making carbon 2 times more needed than iron

I personally think that selling items for 50% of their value would've been enough. That's how it usually works in real life with used things. Nothing magically loses 75% of its value as soon as you try to resell it. But the idea of decreasign selling prices is good, I agree.
Making deconstruction lossy is also a good idea. However, I don't think having partial items would've been a bad idea. But then again, there are better solutions (check option 4 below).
But 2. and 4. really break the balance of everything. What are we supposed to do with the extra iron and lack of carbon? How are we going to deal with railgun shells being 3 times as expensive (6 materials) for the same damage if they had already been expensive? Why is _everything_ so much more expensive?

### Solutions

**Option 1.** Making items deconstruct into less, not construct from more:
Steel should really have the same costs, but deconstruct to 50% iron and carbon.

Another sub-option would be to make Steel deconstruct into Iron without Carbon.

Other basic items (and only basic items) could deconstruct into the much-hated partial items, rounded to 50%. Not a huge problem given the goal of this change.

**Option 2.** Making basic items work like pre-0.18 but not level up skills while crafting:
Crafting knives, steel bars, crowbars, plastic, battery cells, railgun shells etc. could just not level up skills. The required materials could be pre-0.18.

**Option 3**:
If the recipes absolutely must remain as they are, carbon should be 2 times as common as it is, railgun shells should deal twice the damage, same for harpoons, storage containers should be twice as big... only that would return the balance that has existed for years.

**Option 4**:
Reverting all recipes, but limiting the amount of EXP you can get from repeating a given action. (Credit for the idea: Ed)

### Version

0.18.11.0

**Comment by mygamingaccount** [comment]
I think it is much better than how it was before. Maybe a little tweaking can be done, but it already good.

You are always free to create your own take on what you feel is a fair asking price for resources by making a mod that changes the prices ([modding guide](https://regalis11.github.io/BaroModDoc/))

**Comment by Regalis11** [comment]
Thank you for the feedback! Balancing the economy is an ongoing process to us, and we will definitely be doing further adjustments to it, so any feedback on it is really valuable to us.

However, I think you may have somewhat misunderstood our intention behind these changes. They were not just intended to fix "crafting spam", but to make resources overall more scarce, to introduce some more progression to the economy (giving you gradually more resources as you progress), and to balance the economy in general. Addressing the "crafting spam" was just one small part of it.

That being said, it could be that we've made steel (and some other materials) a little too difficult to obtain, so we do need to evaluate things.

> Democratic voting isn't mandatory, but it seems logical to base design choices on the expectations of the users. 

I somewhat disagree on this: even though we do listen to feedback and want to make sure players are happy with the changes we do, in my opinion doing design choices by vote isn't a good idea. If we had done that, the game would still look like this:
![image](https://user-images.githubusercontent.com/14351070/174257053-8c159316-f5d1-4a87-aafd-d73bb77e5c38.png)

We have done many controversial decisions during the years, and often it has seemed that the initial backlash has been mainly resistance to change, and that many people noticed the changes were actually for the better after getting used to them. There are of course many changes that many people dislike too, but it's impossible to please everyone - if we went with a safe and democratic middle-ground on every design decision, I think we would end up pleasing no-one.

And in this case, a sizable portion of player base has been of the opinion that certain resources are too easy to come by: for instance, it's been common for the crew to accumulate an enormous stock of ammo and fuel by the late stages of the campaign, which should now be a little less difficult to do.

**Comment by GenericGoose** [comment]
economy nerf is good, but too sledgehammery, especially lossy deconstruction
btw revert the duffelbag nerf asap and ban whoever came up with it

**Comment by Ek-Videogames** [comment]
- The fabrication recipe changes make sense on paper but need to be actually well though out not just making everything 2x as expensive across the board. _(For instance, why does smashing aluminum together magically make a scooter?)_
Plus certain items that already have ingredients designed to be prohibitively expensive _(IC-4)_ have been hit exceedingly hard.
_(I think partials are an invaluable recipe tool in certain situations. Everybody hates partial-items for some reason, but having more recipes using partials is better than wasting an entire bar of alloy on every revolver round.)_

- Same with shop prices, I think there needs to be a middle ground somewhere between fuel & ammo & meds being affordable enough to not instantly softlock campaign, but still maintaining some level of scarcity & incentivizing the crew to use crafting to fill needs.

- Mining is too much of a crapshoot in terms of getting the ores you actually need to spawn - not to mention almost the entire playerbase doesn't even do mining because of how much of a timesink / boring it is. _Plus rounds going for a long time isn't good from a stability perspective either_. While immersive, **it doesn't really jive with the rest of the gameplay loop very well.**

**Comment by Krzeszny** [comment]
- Steel uses 2 carbon and plastic uses 2 carbon. But iron itself has at least 4 uses, while silicon doesn't, IIRC. If plastic used 2 silicon and 1 carbon, it would balance steel.

**Comment by JeroonBosch** [comment]
> Other basic items (and only basic items) could deconstruct into the much-hated partial items, rounded to 50%

We briefly experimented with this, but it still makes it needlessly annoying to stack these items. One of the things the balance update sought to address was consistency: no partials anywhere, every recipe deconstructs to less than the construction recipe. 
Before the update, already some deconstruction yielded less resources, while others did not. Now it's consistent across the board. 

The infinite XP gaining loop was not the main reason for these changes, but we also did not want some people constantly fabricating / deconstructing just to gain XP. As long as the infinite crafting exists and there's some XP reward, this would remain the optimal way to play (unless the rewards are negligible... but maybe even then).

> Making items sell for 25% of their value

With max. reputation reducing buying costs by 10% and selling value by 10%, the buying and selling was way too efficient previously. Of course the overabundance of loot in wrecks made it way too easy to get rich too, so it could be the cumulative sum of all these changes has impacted the economy too much. However, in my testing experience the increased scarcity simply makes the game better overall by giving much more meaning to items and money.

The low sell price also means we can easily add something like a campaign setting that gives +20% selling value, or a talent that increases selling value significantly, without instantly breaking the game entirely.

---
That's not to say the balance is perfect as it is now. It will be much easier going forward to balance the game now that there's some scarcity rather than overabundance of pretty much everything. So this is just step 1 in a iterative process. Aside from that, Steel seems to be a real issue now, and we can take many approaches to solve it:
- Some recipes using Steel can use Iron instead (as that's not actually used much)
- More loot on wrecks would automatically mean more Steel from deconstruction
- Handheld weapon ammo (revolver bullets, harpoons) could be constructed in larger quantities

Thank you for your feedback, we'll be looking into it more closely.

**Comment by JeroonBosch** [comment]
Most of these balance issues have been addressed. Will need to see where the balance lands now, but feel free to close this ticket. We can create separate tickets (if they don't already exist) if things still pop-up

**Comment by Ek-Videogames** [comment]
Possible unintentional playstyle implications:
- Crews are more incentivized to hoard resources in "raw" item form, because store purchase is unaffordable & recyling/"cannibalizing" of other gear to meet demands in the short-term is no longer possible.
- This combined with double crafting costs seems like it will drive up the number of items stored on the ship & performance issues therein.

Btw I think the idea of making less-used materials more practical is good in theory - but as getting some of the more niche materials for crafting can be very RNG, that can be a problem when vital items are tied to them.
_(Sort of like the issue with early fuel-rod rework, where the lead was consumed every time before recycling was added)_

**Comment by NilanthAnimosus** [comment]
I am definitely not knowledgeable in balancing games, I only know my personal opinions on this, I dislike lossy recycling of things I don't want or need, I'm a total hoarder in any crafting survival game, and I don't want too much of resources that don't have very good usage (Like a metric ton of iron without enough copper to get the steel I would need), and when I play barotrauma I don't tend to get enough of what I feel I need (I'm looking at you anaparalazant and calyxanide) unless I go wreck diving usually...and I play with friends whom never craft and hate crafting, and do not mine, with a crew size of 2 or 3 at best typically without any bots to help (Not that they craft or anything).

I do wonder if we could at least add some kind of balancing as part of the campaign presets like the other difficulty/starting money tweaking. Things like a recycle percentage, sell/buy pricing, mission reward scaling, availability of goods in stores and vending machines as well as wreck loot quantity and minable materials spawning being more modifiers to the settings and in the hands of the players/hosts of their own games as an alternative form of scaling it.

Obviously - some items could be exempt from such scaling if its an issue to unilaterally apply such things with a simple flag on the deconstruct recipes specific item returns and the basics still need balancing overall, but it would be nice to have some control over it as part of your difficulty for those who like, or dislike certain things.

If one wants a hardcore run with 50% more minable resources, 50% less buyable goods in stock, 50% increased purchase cost, 50% loss on recycling (Yes, I know we want no partials, those things are really annoying to be honest, why can't we stack a partial is beyond me?) and 75% less wreck loot as one example with the base game around a default where you get a 1:1 return - I don't think that'd be a huge issue, we are essentially dealing with X amount of mineable spawning, X amount of wreck items spawning, X shop inventory in stock...all values that perhaps could be tweaked to have percentage scaling applied as game session settings to the campaign.

I also think items "given" by the game for free (such as crates) should have a special flag to yield zero return on recycling or be something that actually costs money equal to the steel. the free steel has always been a silly thing as were not charged for the crates - we require crates to receive goods so an option to buy the crates you need to receive a shipment in the purchase screen itself as its been brought up so many times on that delicious free steel (Kind of like checking a crate capacity available, and if you need more crates). - I know this also poses a problem if you were to add to the crates after you make the purchase though given we cannot "Cancel" purchases I don't know why we don't just make them real time in the outpost as well.

I know a lot of stuff though can just be done through modding so is a none issue if the games balanced well, though getting to modify the balance as settings would be a nicer way about some things in my eyes.
