### ISSUE TITLE
The lastest vision (0.18) made auto docking imposible

### ISSUE THREAD

**Issue by Raven-233486** [Regalis11/Barotrauma#9376]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I want to complain that the lasted vision made auto docking imposible, which destroyed most of my sub.
I think you should give an option that enables us to decide whether we can use auto dock or not, rather than just delete the function.

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Could you elaborate a bit, how did it destroy your sub? I do understand the usefulness of making the docking port dock automatically when it's in range, and to a degree that's still possible, you just need to click one extra button to verify it.

**Comment by mygamingaccount** [comment]
@Regalis11 IIRC you have locked all docking ports due to the possibility of sabotage trashing campaigns. Please let me suggest an alternative!

When the docking port receives the dock order signal, check if the sender is a human character. If it is from a signal component, dock the ship but do not end the round, and send a popup to those who have campaign management permissions if it is OK to end. If the command is to not end the round, you can ignore further docking commands from that component and dock using the standard method instead.

**Comment by mygamingaccount** [comment]
Sorry @Regalis11, I missed the new feature. Now I don't know why this issue exists :(

**Comment by RaptorIM** [comment]
Good evening! The current solution seems to prevent fast-approach docking. (Whether that is good or bad I'll leave up to you, but until now it had been an option.) 
Would it perhaps be possible to have the docks connect automatically and the popup only to confirm completion of mission, or set up toggle in settings to override this pop-up?
As it is now, if the docks get misaligned before you confirm the pop-up (which may in some cases happen very fast), nothing seems to happen when you confirm the docking and I had to dock manually anyway, removing the purpose of having the automatic docking system in the first place.
