### ISSUE TITLE
Reintroduce separate voice chat keybinds

### ISSUE THREAD

**Issue by OffLayne** [Regalis11/Barotrauma#9379]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Currently lost the ability to speak with voice activation by default and use the push to talk button for radio. I realize the new format is to switch between local and radio, however the push to talk to activate radio voice chat is much more immersive.

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Hi! Thanks for your feedback. I understand where you're coming from and understand the want to retain the old voice chat behavior with separate binds. I have renamed this ticket to "Reintroduce separate voice chat keybinds". We will hopefully look into this issue when we can, but it might take some time for the change to reach the public release. Sorry for the inconvenience!

**Comment by Rokvach** [comment]
Moving this back to Review as there were some code changes done

**Comment by OffLayne** [comment]
Thank you for the quick responses and work. I just wanted to confirm that this will include the old option to have voice activation speak only in local and use push to speak in radio. The line from the old config that allowed this was uselocalvoicebydefault="true"

**Comment by ekqvist** [comment]
Unfortunately, that config option won't be supported anymore. However, you can set the chat mode to Local to use local voice chat by default for the voice-activated voice chat and use the separate push-to-talk key for the radio voice chat.

**Comment by polambert** [comment]
Setting the voice mode to voice-activated and the radio channel to local, then using the push-to-talk key to talk over radio doesn't work. It still just transmits over local chat. I have to toggle between them with R still.

Also, I'm pretty sure he knew the config option wasn't supported, and that he was asking to confirm that the radio would be able to behave the way he wants.

**Comment by ekqvist** [comment]
> Setting the voice mode to voice-activated and the radio channel to local, then using the push-to-talk key to talk over radio doesn't work. It still just transmits over local chat. I have to toggle between them with R still.

Unfortunately, the abovementioned changes haven't been included to the public builds yet so the things I described won't work until then.

> Also, I'm pretty sure he knew the config option wasn't supported, and that he was asking to confirm that the radio would be able to behave the way he wants.

As I said, once the changes are in, you should be able to set the chat mode to Local to use local voice chat by default for the voice-activated voice chat and use the separate radio push-to-talk key for the radio voice chat.

If there's something I misunderstood, please let me know and I can try to give a better answer.

**Comment by polambert** [comment]
Okay, thank you for clarifying.

**Comment by Regalis11** [comment]
Tested and merged, will be coming up in the next unstable build

**Comment by Regalis11** [comment]
Or on a second thought, lets keep this ticket open a little longer so it can be tested in unstable

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

**Comment by polambert** [comment]
I'm on 0.19.0.0 and I can't seem to get voice-activated local and PTT radio to work. It is on voice-activated radio and PTT local, no matter what settings I try to tweak. I've also tried going back into the config and adding uselocalvoicebydefault="true" but that didn't seem to work either (this line is removed whenever the game is run). 

Is it possible to get it to work this way? I assume I'm missing something because that is what this issue was for.

**Comment by NilanthAnimosus** [comment]
I just switched back to the 0.19.0.0 build.

Hm, in my testing personally voice-activated chat defaults to radio on, and then holding V (the voice chat bind) forces local chat.

![image](https://user-images.githubusercontent.com/29177976/182301061-dfe0d2fa-f6a4-45d3-8907-8f23736f3f44.png)

when I set the binds for radio voice chat (legacy) and local voice chat (legacy) and then use voice activated chat it does change the voice mode.

However it starts in radio chat then hitting the legacy voice chat key will switch it to local voice until you fall below the activation threshold and are no longer hitting the key, reverting to radio. if you hit the radio legacy key before you stop talking it will change back to radio voice.

It does seem that I cannot get it to default to local chat based voice activation. and although I can effect which mode is used in voice activation with only one key I cannot invert the behavior so this is worth re-opening and looking into.

**Comment by Taramelg** [comment]
Agreeing with Nilanth, we play the game again with friends after a 2-3 months pause and we were pretty disappointed to not be able to play anymore with the local voice activation.
It was really our favorite/most immersive way to play in coop so would be pretty happy to see this option back in the game, thx boyz

**Comment by NilanthAnimosus** [comment]
Tested against voice-acitivity-fix commit https://github.com/Regalis11/Barotrauma-development/commit/7a34485eade56cce5778f835e57096c9f6dbaa01

when you switch the text chat from radio to local I found it worked correctly, my voice activity based chat defaulted to local, with the legacy keypress for radio changing it to radio. However changing the chat mode back to radio did not default it to radio, it is now permanently defaulted to local voice chat for voice activity based chat.

Additionally, while it was in local-defaulted voice activity, the original voice activation key simply does local chat. meaning one must use the radio keybind for the opposite effect.

I also feel (in my personal opinion) the this default probably should be set in the settings menu instead of through the constantly changing in game text chat setting, at least for voice activated chat.

Even harder to explain though is you can change it back to radio defaulted voice chat, by hitting certain keys, Like if you set the chat mode in the bottom left to radio, then use the radio legacy keybind, it will now just default to radio voice activated voice. I find it confusing personally, but its like their are permanently sticky keys with unexpected results going on as I mix both legacy and none legacy keys and the mode switch alongside the text chat keys.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/75512c2c4ea5bde2792008903c0c5eda8ad81515

**Comment by NilanthAnimosus** [comment]
Tested against voice-acitivity-fix commit https://github.com/Regalis11/Barotrauma-development/commit/75512c2c4ea5bde2792008903c0c5eda8ad81515

everything works as expected now to my understanding of this.

PTT binds radio and local function correctly.
Changing chat mode now sets the default mode of voice activity
chat mode controls PTT voice mode (if not using a specific legacy key for it).
Mixing voice activated (with chat mode) then using a legacy bind allows for a default mode of chat with a modifier key (Such as local default, and a key held down for radio) if setup right.

Note, since its currently based off the chat mode near the text chat box (changed with default bind R) it has been noted it may be possible that mixing text and radio chat could result in accidentally using the wrong voice mode than intended for microphone chat. but its not sure if there is a better way about this that doesn't lead to some different kinds of confusion or awkward key binding.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/7f3f6c800271e4dbdc682bb79cdd4e7e6c074a11, no issues found, closing.

Notes:
Text chat local/radio mode effects default voice mode. PTT binds work fine and legacy voice chat binds can be used to invert the current voice mode by using 1 key with voice activity such as setting voice to local then using radio legacy key to talk into radio by holding it down.

**Comment by Tamei** [comment]
Weirdly, this is not working for me.
Voice activity is enabled, radio legacy key is set, chat mode is set to local by default.
Pressing the radio legacy key now DOES switch to radio, but the chat text box also gets activated and I am therefore just spamming my radio legacy key letter into it.
Also, the mode does not switch back if let go of the button. Did I miss something in the configuration?

**Comment by Regalis11** [comment]
By radio legacy key, do you mean the "Radio chat (Legacy)" bind or "Radio voice chat (legacy)"? You need to set the latter, as the former is specifically for switching to radio and selecting the chat box. And of course, make sure they're not bind to the same key.

**Comment by Tamei** [comment]
I am an idiot and set the "Radio chat (Legacy)". Thanks for clearing it up!
