### ISSUE TITLE
Interesting chaos!

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#938]
Sorry if you all feel like I'm spamming my threads too much and filling the board with my ideas (I'm a bit enthusiastic for this game judging by the alpha version you have on your website).

Straying away from that, I really like one thing from the previous version.

Sometimes when a huge dent was made in the ship players would often get sucked into the water and explode!

I honestly really liked that feature, and was thinking, if it'd be possible to somehow create a percentage for the holes, for example there'd be a 37% chance that the hole would be large enough to create basically a vaccum or suction from the water outside, that would basically start sucking the player outside of the sub. I really found it to be exhilarating when such things happened a couple of games ago (when playing with friends).

My note being that I'd like you to consider this feature.

(ps this is pretty realistic which is why space stations depressurize the airlock first https://www.quora.com/Why-will-people-get-sucked-out-to-space-when-a-door-is-open-in-a-spaceship)

Thanks in advance, moi

**Comment by Regalis11** [comment]
I feel this was more a bug than a feature, it used to happen because the impulses applied to characters when the sub hits something we're so large relative to the amount of force the water that rushes in applies to the characters, causing the characters to get "thrown out" quite often.

I feel like readding it wouldn't be a very good idea honestly. First of all, most of the time it's not very fun when it happens to you: instant death that you can do nothing about. Second, it's not realistic at all. The comparison to space stations doesn't really apply here: in a space station there's a vacuum outside the walls, but in a submarine there's pressurized water that wants to rush inside the sub. So realistically the effect should be exact the opposite, a hole should blast you with water and throw you further away from the wall.
