### ISSUE TITLE
Monsters spawned so close that they killed each other (0.18.12)

### ISSUE THREAD

**Issue by Raven-233486** [Regalis11/Barotrauma#9385]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

MissionID: killmudraptors1 killcrawlerswarm1
If you cloose both these two mission, you will complete them before you reach the monsters' loaction.
I have tryed three times in different levels, everytime it happens.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@3de089d.

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0,

I tried four combat missions at once (easily doable with mods and luck) and threw this error:
![image](https://user-images.githubusercontent.com/29177976/181407346-627e8c25-8af2-476d-ae5f-96d66b7921f7.png)

Of course, this is an exaggerated situation.
![image](https://user-images.githubusercontent.com/29177976/181407571-be061e2c-a4b2-4c16-85c8-91d8aaf6bee6.png)
and all the creatures were relatively close to each other, but  this was also a tiny level at the start of a campaign I was just testing against using unlockmission.

With three missions:
![image](https://user-images.githubusercontent.com/29177976/181409104-1cd03d8a-677b-4682-b855-538cd213b6d8.png)

They still managed to find and kill each other within the first 30 seconds to a minute, though this is theoretically doable in vanilla due to captain talents (And maybe racking some missions up along a route).

Given the map generation, not sure if all map sizes can be accounted for and the creatures do travel quite a distance at times on top, not sure if anything here is to change though as they definitely do not spawn inside each other / in immediate attack range unless there is no good spawn positions left meeting the required distance.

guess it could be considered a feature than a bug if your targets just happen to meet and eat each other though, Perhaps we could make combat mission enemies more resistant / immune to other combat mission enemies or something (At least so they are alive once the player reaches them)?

Single player campaign save I was quickly using
[Save 9.zip](https://github.com/Regalis11/Barotrauma/files/9204976/Save.9.zip)

Perhaps this is a non-issue in later levels (But I find it common for players to stick to the first biome for a long while, perhaps long enough to get the 3 mission captain talent, or a server setting allowing for more than 2 missions instead).

**Comment by itchyOwl** [comment]
The change here is that we now first try to get a position that's not too close to the previous monster swarm spawn, which in this case seems to fail and throw that warning in debug builds. Increasing the distance between the spawns would make this happen more often, so it's not the best solution. In general, monsters fighting each other is intentional, but with the mission monsters it's not, so we could also consider changing their targeting behavior. But that might lead to weirdness when monsters suddenly fight happily against the player alongside with their rivals. So idk if it's really worth using any more reasouces. And in any case, I don't think we should even try to support more than 2 swarm missions per level.

**Comment by Regalis11** [comment]
To me this doesn't seem like something we should put more resources into, considering how unlikely it is to happen now during normal gameplay.
