### ISSUE TITLE
Multiple item and category localization issues in the Russian version 

### ISSUE THREAD

**Issue by AbyssBeast09** [Regalis11/Barotrauma#9393]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. Medical category called medbay (медотсек)  
   Translation variants: 
   Медицина, медицинские принадлежности 
 

![Screenshot_54](https://user-images.githubusercontent.com/85645359/174343913-4ebce80a-5ce1-48d9-9f51-58d34c83e6f9.png)

2. Diving category called "водолазное" (wrong word gender in russian)
   Translation variants: 
   Дайвинг (More logical variant) 
   
    
![Screenshot_55](https://user-images.githubusercontent.com/85645359/174345348-8e8d5911-1a08-411b-8f5b-1932f7812b23.png)

3. Same issue with Alien category. Called "инопланетное"(wrong word gender in russian) 

  
  ![image](https://user-images.githubusercontent.com/85645359/174347726-14f396de-bb52-416b-b0fb-d34c823c6c6f.png)

4. Rapid fissile accelerator wrong translation
   ingame variant says "Быстрый ускоритель распада" 
   i think the right variant should be called "Ускоритель быстрых частиц" 
   
   
![Screenshot_56](https://user-images.githubusercontent.com/85645359/174348378-105e58af-398f-4259-ac89-e6be846a047c.png)

5. Physcorium bar called Physcorium rod(Физкориевый стержень)
    Translation variants: Физкориевый осколок 
 
     
![image](https://user-images.githubusercontent.com/85645359/174349066-edc5a4d8-656e-41d0-bdff-c8c023baedab.png)

6. Disposable diving suit called Consumable diving suit(Расходный водолазный скафандр) 
   Translation variants: Одноразовый  водолазный скафандр (lol even Google translator says what) 

   
![image](https://user-images.githubusercontent.com/85645359/174349520-1e17ee85-0148-4b7c-afab-594964a5111f.png)
![image](https://user-images.githubusercontent.com/85645359/174349587-f8952804-a4f8-4c7c-bcaa-c4d1bb76bd08.png)

  
    
    

### Reproduction steps

1. Switch language to russian
2. Look at the items/categories names 

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I don't speak Russian, but based on a quick google translate, the current name for Rapid Fissile Accelerator translates to something like "Rapid Decay Accelerator", and you're suggesting something like "Rapid Particle Accelerator". In my opinion the current name seems completely fitting: fission is a type of radioactive decay, and the weapon accelerates it. Could you elaborate on why you think it's wrong?

**Comment by AbyssBeast09** [comment]
okey,thx for answers

**Comment by MaaiG** [comment]
1.
> I'm also curious of "Расходный водолазный скафандр": I'm not sure how "расходный" is normally used, but if it translates to "consumable" (something that's intended to be used up and replaced), it seems like a fine translation.

I don’t think my English will do it, but I’ll try to explain.

`Расходуемый` - consumed, expendable...
Yes, there is such a word in Russian, but in this case it is not suitable. It is difficult me to explain...
`Расходуемый кислород` (Oxygen consumption) - Yes!
`Расходуемый костюм` (Expendable Suit) - No!
This is never said. You may be understood )) but not at once and not every person )). We have to look at a specific object of discussion.
That kind of translation for this suit doesn’t tell us (unequivocally) what it is. I also had to try it out first to understand and know what its name means!
I tried it and I can say with certainty - It’s a disposable suit!

`Расходуемый костюм` (Expendable Suit) - Maybe in Russian it sounds like...
It’s kind of like say "Сonsumable syringe" instead of a "Disposable syringe" in English. But I’m not sure ))

In this case, the word `Одноразовый` means "for single use", "used once"
In Russian it is correct to say this:
`Одноразовый шприц` - like Disposable syringe
`Одноразовые перчатки` - like Disposable gloves 
`Одноразовый пароль` - like One-time password
`Одноразовый костюм` - like Disposable suit

2.
> Rapid Fissile Accelerator

I don’t like the translation - it sounds "crooked", but now I can’t think of anything...
May be "Ускоритель быстрого распада" - better, but it’s still tautology.

3. For me I fix and left as follows:
`<mapentitycategory.medical>Медицина</mapentitycategory.medical>` - **fixed like this**
`<mapentitycategory.diving>Водолазное</mapentitycategory.diving>` - **left as. Like as "Водолазное дело"**

`<mapentitycategory.all>Все</mapentitycategory.all>`
`<mapentitycategory.structure>Конструкции</mapentitycategory.structure>`  - **fixed like this**
`<mapentitycategory.machine>Устройства</mapentitycategory.machine>`  - **fixed like this**
`<mapentitycategory.equipment>Снаряжение</mapentitycategory.equipment>`
`<mapentitycategory.electrical>Электрика</mapentitycategory.electrical>`
`<mapentitycategory.material>Материалы</mapentitycategory.material>`
`<mapentitycategory.misc>Разное</mapentitycategory.misc>`
`<mapentitycategory.alien>Инопланетное</mapentitycategory.alien>` - **left as**
`<mapentitycategory.itemassembly>Сборки объектов</mapentitycategory.itemassembly>`
`<mapentitycategory.legacy>Устаревшее</mapentitycategory.legacy>`
`<mapentitycategory.decorative>Украшения</mapentitycategory.decorative>`
`<mapentitycategory.wall>Стены</mapentitycategory.wall>`
`<mapentitycategory.wrecked>Обломки</mapentitycategory.wrecked>`
`<mapentitycategory.thalamus>Таламус</mapentitycategory.thalamus>`
`<mapentitycategory.weapon>Вооружение</mapentitycategory.weapon>`
`<mapentitycategory.fuel>Топливо</mapentitycategory.fuel>`
`<ItemAssemblies>Сборки объектов</ItemAssemblies>`  - **fixed like this**
