### ISSUE TITLE
error and console spamming whenever trying to change the turrets 

### ISSUE THREAD

**Issue by ZabuSama** [Regalis11/Barotrauma#9408]
### Disclaimers

- [X] My issue happened while using mods.
- [X] I have searched the issue tracker to check if the issue has already been reported.

### What happened?

its basically what it says in the title
whenever i go to the Submarine upgrades merchant and get to the turret upgrades, it greets me with a console error about a green GUI
luckily, i can easily closes that by just pressing F3

but what brings me here is an error that, just didnt happen before
and it is that if i "dare" to select a turret and try to look for another one, itll just spam errors and keep on opening the console till i either go back to the main menu or choose something different of the submarine to upgrade

![imagen_2022-06-18_154628380](https://user-images.githubusercontent.com/107769935/174452289-7455436b-973b-498f-b845-77497337298f.png)

### Reproduction steps

1. start a new campaign
2. get to the submarine upgrades merchant
3. look for turret options and upgrades
4. select a turret and try to change it from the submarine

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
failed to phrase the string "COLOR GUI.GREEN" to color
```

**Comment by Ek-Videogames** [comment]
#8914 got re-added somehow 🤷

**Comment by Regalis11** [comment]
Thank you for the report!

We had fixed this error manually for the previous update, but looks like the error in the localization file hadn't been corrected in the master localization kit the translators used, so we accidentally reintroduced it in this update.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5c1ed84a2bb60bf601c01bbb7a66f81806e6edf9

Until we get the fix out, it's possible to work around this problem by finding the file `Content/Texts/CastilianSpanish/CastilianSpanishVanilla.xml` or `Content/Texts/LatinamericanSpanish/LatinamericanSpanishVanilla.xml`, and changing `color gui.green` on line 4784 to `color:gui.green`.

**Comment by Regalis11** [comment]
Internal note: let's keep this open until we've imported the next batch of texts and verified this has been fixed.

**Comment by Regalis11** [comment]
Should be fixed now https://github.com/Regalis11/Barotrauma-development/commit/fce88d95d454f11167d99f1010d2acadacf60dcc

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/19bb2dffd537d3a9dde093d6d5c2bb41b4a68b25, Works correctly. closing.

Note: Tested both Castilian Spanish and Latin American Spanish and found no issues. looks like the previous issue is no longer re-introducing itself in new translation batches.
