### ISSUE TITLE
Cant continue to the bug in map generator

### ISSUE THREAD

**Issue by MatejPetrik007** [Regalis11/Barotrauma#9456]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello, me and my friends were playing and due the bug that happened we can’t continue in the game without cheats how could we solve it everything important is in zip file

### Reproduction steps

here are .save .sub screenshots gamesession etc
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/8967639/Barotrauma.zip)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I fixed this now in https://github.com/Regalis11/Barotrauma-development/commit/fbbde3581e52cc016bdea70ea036589f7a32e978 (a link to our private repo), but until the fix is publicly released, I'm afraid there might not be another way around this than to use console commands (unless there's a way forward on the map through some other location, which I didn't check.)

**Comment by Regalis11** [comment]
That's a link to our private repository, I only linked it for our internal use.

**Comment by NilanthAnimosus** [comment]
Tested, seems fine now, closing.

NOTE: Tested along 6 different locations in the provided save and shuttle on campaign. no issues found with level geometry using a shuttle along the main path that would prevent reaching the next location.
