### ISSUE TITLE
Transparent UI

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [Regalis11/Barotrauma#9460]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When i launched the game and joined my friend on multiplayer i got transpernt UI, i can't see the durability of hull or how damaged  for example electrical box is. Most of the times relaunching the game helps, but currently i've launched the game 3 times a row and still have this bug. I've not tested if this occurs during singleplayer.

### Reproduction steps

1. Launch Barotrauma
2. Join multiplayer campaign
3. See what happens

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Linux

**Comment by TheEpicNoobZilla** [comment]
Example of this
![Zrzut ekranu z 2022-06-24 20-04-34](https://user-images.githubusercontent.com/55759769/175617760-31f5e5f0-7658-437b-9cd3-5026dab84e30.png)

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not entirely sure I understand the issue here: which UI elements are transparent (I don't see any transparent elements in the screenshot you posted)? How does the UI being transparent affect your ability to see the condition of walls or junction boxes? 

Also, are you using some kind of 3rd party "game optimization" software like Razer Cortex? This is just a wild guess, but we've previously had some issues with these kinds of software interfering with the rendering, and I'm wondering if something similar could be going on here.

**Comment by Krzeszny** [comment]
I've spotted missing reputation bars on the screenshot.

**Comment by TheEpicNoobZilla** [comment]
The only software that i while using Barotrauma is gamemode which worked flawlessly with this game before 0.18 update

**Comment by Regalis11** [comment]
No known steps to repro, closing
