### ISSUE TITLE
Harpoons tend to disappear all the time

### ISSUE THREAD

**Issue by V1Htor** [Regalis11/Barotrauma#9468]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When doing few shots in a row with harpoons there is (HIGH) chance of they disappear. That makes harpoon pretty expensive and useless because it ammo "recoverability" goes to zero.

### Reproduction steps

1. Start a game
2. Give yourself a harpoon
3. Shoot in one direction 
4. check the amount of harpoons at the en

https://user-images.githubusercontent.com/39983153/175833646-2a5c8f82-85d8-49c1-8cd6-5eadea88f6da.mov

d

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Krzeszny** [comment]
Very likely to be related to #9406

**Comment by V1Htor** [comment]
> Very likely to be related to #9406

it happens not only in sub but in caves/outside/ruins also, feels like the thing with died monsters coming alive back bc of ping.

**Comment by Regalis11** [comment]
> Very likely to be related to #9406

That bug only affects collisions outside the sub, so I doubt it's what's happening here.

**Comment by NilanthAnimosus** [comment]
Been testing this issue in 0.18.13.0,

I would just like to point out this is visibly on a server and thus is possibly a case of item position syncing teleporting the item visibly elsewhere, and on single player the harpoons bounce off a door but in that same location should land on the floor. In the provided video of the issue they pass right through the walkway in the middle of the room to instead land on the submarine floor and sometimes disappear there.

At the very least, this is pointing out that where the same shot lands in single player, the position is extremely different in multiplayer - this cannot possibly be intended if the final position of the item is incorrect.

the collisions have definitely changed between 0.18.12.0 and 0.18.13.0 inside the submarine so that it no longer passes through the walkway inside the hull.

Now onto some findings from testing involving two clients:

both localhost on the same machine:

Client 1:
![image](https://user-images.githubusercontent.com/29177976/177207765-e721a3d0-45dc-4d99-a108-d4acd096b6ff.png)

Client 2 (Note lack of harpoon spears at feet):
![image](https://user-images.githubusercontent.com/29177976/177207821-ad505b71-be02-4031-a6aa-34a6f6bae0e4.png)

its as if these spears just disappeared from existence for one client, but not for the other. and laughably one of my spears went right through the wall on both (Guess its a little thin at the angle I aimed at for that one). out of 12 shots 1 passed through and two went missing as seen in the images for one client.

Not being able to see the harpoons anymore on the other client, I decided to see what would happen if I simply used explosion command to remove the hull where they had disappeared, and then I saw this interesting tidbit I can't really explain:

https://i.gyazo.com/732393efa64fba7a070c139bd1c1ddc4.mp4

It was not doing this behavior on the first client before the explosion (Which could see them) but now it was visible to the second client (Yet now on both it phases in and out of existence and has not dropped through the submarine as one would expect?).

I'm at least considering this to be an issue of item position syncing for projectiles (And possibly spent throwables if they don't delete?)

**Comment by Xsayen** [comment]
Hello! 
I would like to add that harpoon projectiles completely disappear for me when you are holding it outside the hull while your body still touches the inside of the hull. This makes shooting out an airlock while the sub is moving impossible. It also eats shotgun pellets making it only one projectile. Revolver seems to work fine.

Here's another person that experienced this, here's a reddit post referencing that: https://www.reddit.com/r/Barotrauma/comments/11kr1y9/insanely_annoying_feature_of_the_harpoon_gun/

Here's my gif
https://user-images.githubusercontent.com/56316987/233511219-3a20a4f5-5851-4c1c-afb3-996cfe8236d0.mp4

**Comment by Regalis11** [comment]
Might be addressed in https://github.com/Regalis11/Barotrauma-development/pull/4110, moving to QA

**Comment by Jasontti** [comment]
Tested.
Disappearing issue seems to be resolved, shot 20 harpoons and got 20 back (although they are sometimes hard to see and pick up due to structures).
Shooting out of sub still has problem of shot completely disappearing.
When shooting in to sub and when both parties are in same side of the threshold, there are no issues.

https://github.com/Regalis11/Barotrauma/assets/8488224/436c4a5c-845b-4bd5-8b7d-671d678b6a2f

**Comment by Jasontti** [comment]
Tested again in SP and MP.
Shooting out of and in to subs or ruins work.
Closing ticket.
