### ISSUE TITLE
[Editor] Keybind for the bottom drawer menu is non-bindable again

### ISSUE THREAD

**Issue by FalconPilot** [Regalis11/Barotrauma#9496]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the submarine editor, since the 3rd anniversary update, it isn't possible anymore to bind the "items menu" toggle which is, by default, on Q. However, on azerty keyboards, this causes some issues :/

I checked on the keybind XML file, and the bind has completely disappeared, which makes it so everytime I pan the camera to the left, it toggles the bottom menu (which is a little bit inconvenient)

I'm suspecting that the last update changed some keybinds and, somehow, the keybind for this one has been removed for some reason

### Reproduction steps

1. Open the submarine editor with an AZERTY keyboard
2. Pan the camera to the left, using the "Q" key

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1d334ecb5900507b4d856aff1c395b471fab2f17

> Partially reintroduced the "toggle inventory" keybind. It was also used for toggling the entiry menu in the sub editor, but I removed that in https://github.com/Regalis11/Barotrauma-development/commit/9c5f202f47 and hard-coded it to Q (assuming it was something very few people know about, much less use or rebind to something else). But being able to change it to something else than Q is important on AZERTY keyboards, so let's readd it.

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0.

The keybind appears to work fine, however the tooltip for the collapse/expand button in the submarine editor always states "Q" instead of the correct key (and it is not related to changing the key in the editor or the menu beforehand, the tooltip simply does not represent the correct key).

![image](https://user-images.githubusercontent.com/29177976/180118061-09337f98-a3cf-4347-b26f-42035ab4fc63.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e70c41c043a760da60e2f916c246eef181bd5019

**Comment by NilanthAnimosus** [comment]
Curious as I started the game and immediately changed the bind, opened sub editor (first time) and saw Q instead of the key I chose. then tried changing it to another key in the editor and it didn't change, then main menu'd and went back to editor, seems to only change on a game restart. hopefully that minor difference doesn't effect the above fix.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/3391dc7033d5d12b9167b38a6269ffd1096e546d, working correctly, closing.
