### ISSUE TITLE
Quick griefing on a server with default settings. 

### ISSUE THREAD

**Issue by Xandaron539** [Regalis11/Barotrauma#9505]
https://user-images.githubusercontent.com/63539923/176899397-817524d0-154e-438c-8108-5796240cf2b1.mp4

All the servers have vote kick enabled by default, where it requires just 60% votes. The problem is that there's no cooldown on it, so that single or a group of players are able to do quick raids on servers, where once they join, they vote kick everyone, in a result all innocent players are getting a 2-hour ban. Unlike any other griefs, this one is instant and incredibly simple, where host and admins, if he has any, get to do job for all those banned players to get to nearby outpost, which is impossible for many reasons.
As a solution, i recommend you to add cooldown, so that newcomers had to spend at least minute on a server, before they gain access to vote kick.

**Comment by Tsunder** [comment]
https://github.com/Regalis11/Barotrauma/blob/960835082a7c635b174af2edcf08203ed9dece55/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs#L3270

the minimum vote count is floor of the ratio, which for 3 people * 60% of the vote = 1.8 = 1.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/69700bc2387fe81629b47c30c0ada34786171d3a

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f8405b0b4a117fdfe90873c71665ceae649ad52b, does not work correctly for preventing votes within 2 minutes and also feel maybe this should be tweaked further?

Notes: It indeed takes a minimum of two votes to kick a player now, since you cannot vote to kick yourself this means three players. the default is still 60%.

If you have 4 players, and two initiate a votekick - its successful. as 60% of 4 = 2.4, it floors down to 2 again. 2 is 50% of players, should we perhaps just treat both as floats and round to the closest or a much safer of always rounding up of the end result instead of always rounding to the floor?

additionally, the timing part of this doesn't work as this appears it should be inverted as a less than:
![image](https://user-images.githubusercontent.com/29177976/186604436-5321a377-64cf-4387-a593-8c0d17fdb7db.png)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/5535bf70d19b49d72968cdbc838f877efac060b4 and https://github.com/Regalis11/Barotrauma-development/commit/88e27b5ae9f28ddaa448055766fdead3c438b105

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4711fb13cd04281194d486c16c925ee952b1cd14 and https://github.com/Regalis11/Barotrauma-development/commit/e59f7f155f1dc347c060e7f5409d12cafb7eb9c9

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2b6f358552c3195aef78f97c763b26fe447bc0e, no issues found, closing.
