### ISSUE TITLE
After melee attack on ground (not in water) you unable to turn back some time

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#9533]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems to be a issue of bugfix of unable to turn inside water while melee "recharging".
Also, i would like if you could turn inside water and turn your head while holding right mouse button, without equipped item, it will help with this issue a bit, and also help with communication (nodding, shaking head)

### Reproduction steps

1.Equip melee weapon
2.Attack
3.Flick cursor behind your character
4.Character not turning before melee weapon aimed

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Just to be clear with this issue/request - the character only turns when you use the movement keys in water (Assumedly turning is rotation of the sprites here).

turning via aiming (While on melee recharge or not, or a ranged weapon and such) does not effect your ability to rotate (via spinning) your character, but it does prevent rotation via movement keys even if you aim directly behind yourself and the fastest most logical way to reach that aim would be to rotate the characters sprite instead of a 180 degree rotation (melee cooldown not effecting this, but aiming effects it) and I think that's what they want there.

Now if you melee and let go of aim, you indeed cannot rotate your character through movement keys until the melee weapons cooldown is over. which for some weapons (Like a crowbar) can be lengthy. just tap A and D to keep flipping your sprite and click right and left together while still alternating A and D and you'll see what is meant by being unable to turn post-melee.

**Comment by itchyOwl** [comment]
Seems to be intentional, but I set it independent from the reload time in Regalis11/Barotrauma-development@29adc99, making it much shorter on most weapons. The flip lock also considers swimming animations, but the result is a bit different.

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, working correctly. Closing.
