### ISSUE TITLE
Respawn without penalty 

### ISSUE THREAD

**Issue by Frostie-Intelligence** [Regalis11/Barotrauma#9561]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you press respawn without penalty, stats still drop and gives you penalty.

### Reproduction steps

1. Start a multiplayer campain
2. Pick orca 2,
3. Play and die
4. Penatly

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is actually kind of intentional: as of the Among Ancients update, you always get a penalty your skills when you die. The 'penalty' this message is referring to is the Reaper's Tax. I reworded the message a bit in https://github.com/Regalis11/Barotrauma-development/commit/1faa17b730468cc11145390951ae339217b319e4 to make this a little clearer.

**Comment by Regalis11** [comment]
The difference is the Reaper's Tax affliction. The point of the affliction is that we feel there needs to be a cost to respawning mid-round (you shouldn't be able to get infinite free reinforcements and supplies mid-round), and Reaper's Tax is intended to be that 'cost'. That being said, the respawning rules are pretty confusing and unintuitive at the moment, and there's a chance we'll still do some changes to them.

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0,

I do think we still need some changes here.

It should be communicated with the player a skill loss will occur from not creating a new character, not just about the reapers tax. it could still be thought by a player that not respawning mid round (and thus not getting the reapers tax) means no skill loss at all.

Currently it is:
Do you want to respawn now with Reaper's Tax, an affliction that applies a penalty to your skills and health, or wait for the next round to spawn

But I feel it is much clearer to state (With perhaps some better re-wording):
Do you want to respawn now with Reaper's Tax, an affliction that applies an additional penalty to your skills and health you can recover later, or wait for the next round to spawn

and when you pick next round to spawn (Indicating one wants to save skills primarily) - get a final popup detailing that you can re-roll for a new character and job pick for a reset to the baseline skills (Dying and losing skills with a character that hasn't even played a singular round is not a great way to start and its not communicated at all, and I don't think we are setting a bare minimum to those skills either for the class?)

Obviously, the second one needs better more concise rewording too but that is just my ideas on this issue.

~I know that is extra translation, but if this is to resolve it being unclear...I don't think that text conveys you are still losing skills either way.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2439352f992712e9ca560e23fb8d5a33c1a751cb

Based on our earlier discussion, I also made [a small change](https://github.com/Regalis11/Barotrauma-development/commit/647f117b6c5cc8c064bd074009bbf4159fd68f39) to the skill penalty you always get when dying: now instead of dropping towards the minimum initial skill, the skills drop towards the _maximum_ initial skill. So dying should never make your existing character worse than a completely new character.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861

If your skill is lower than the max, death will actually raise it instead of lowering it (we should probably prevent this behaviour).

Multiple deaths I've noticed do not increase the severity of reapers tax which I feel it should be doing, It looked like a progressive affliction yet it always applied the same -12 vitality on a captain, and only reducing skills very minorly (I.e.. a helm of 50 -7 from reapers tax) despite having killed myself 5 times and capping my skill to 50 for helm. this could be linked to the corpse immediately turning into a duffelbag on respawn (?) if its intended to stack the affliction.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/ba57500e2551cb899486dc3d617c73ebfeb71815, https://github.com/Regalis11/Barotrauma-development/commit/8ad477c4d65a5b882e1db1327b7990d926a3b8b4 and https://github.com/Regalis11/Barotrauma-development/commit/a52a47187103afff5eeba31e73145d72e387125e

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/43eb0a8fb27f532a3b23dfaba500cce2c41c4eec, no issues found, closing.
