### ISSUE TITLE
[Dev version] Legacy railgun controllers are not loading on some subs

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#957]
**Description**
This is the beginning of the error message it gives me
(The message is pretty long, so i did not screenshot the whole thing)
![-2018-dec-4-002](https://user-images.githubusercontent.com/38168249/49420691-45ffb400-f7bf-11e8-840f-e119a1cd315a.jpg)

**Steps To Reproduce**
Try loading Vanilla subs such as Vellamo or Nehalennia.
For some reason it's fine on Aegir mark III.
My sub file(In case you don't manage to reproduce it on vanilla ones on your side):
[Sub.zip](https://github.com/Regalis11/Barotrauma/files/2642564/Sub.zip)

**Version**
Windows. The most recent(04.12.2018) dev version.

---
Is there a console command or any other way(except for intentionally crashing the game) to dump the console output into a text file? If not, that should be a thing. Would make error reports a lot more convenient than having to make screenshots or retype the error. 

---
(Unrelated to the issue)
In one of the subs i got an error saying:
"Error loading item - item prefab "Calyxanide" (identifier "calyzanide") not found."
Judging by the identifier being "calyzanide", i assume it has been caused by a typo.
Though not sure if it's like that in the whole game or just a single sub. Don't know how the identifiers work.

**Comment by Regalis11** [comment]
This happens due to 7c3382fa. We removed the railgun controller and rear railgun controller, replaced them with a new Periscope item and created legacy railgun controllers which are compatible with the ones in old subs (i.e. any subs made with the master version). If you have subs that were made with a dev version that used identifiers for controllers, you need to replace them manually.

The calyxanide problem was fixed in 3a478a98, you're probably using a submarine that was saved using some old dev version.

The only way to dump console output to a file atm is to set "savedebugconsolelogs" to true in the config file. But that causes all of the console output to be saved - it'd definitely be useful to be able to copy/save the current contents of the console, so I'll add that to my todo list!
