### ISSUE TITLE
Low FPS in the game in the middle part of the game

### ISSUE THREAD

**Issue by xFox113** [Regalis11/Barotrauma#9578]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the game at medium levels of the company frame rate drops to 5 FPS, even on modern configurations PC. This is due to volcanic eruptions, underwater currents, and radiation in the player's environment.

### Reproduction steps

1. Launch the game
2.  Create the server and invite friends ( Turn on the radiation in the company)
3. Play as usual and reach the pass to the next part of the game (After getting a pass from the captain of the outpost)
4. Keep on playing
5. Note that during the game at medium levels of the company frame rate drops to 5 FPS, even on modern configurations PC. This is due to volcanic eruptions, underwater currents, and radiation in the player's environment.

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Nope
```

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately haven't been able to measure any noticeable performance drops caused by volcanic eruptions, underwater currents or radiation. I believe they might be linked to the performance drops, but it might be that there needs to be something else going on as well for them to start causing these issues: perhaps something in the submarines or in the characters (AI, talents, status effects...?).

If it's possible to provide us a bit more info on the issue, it might help us pinpoint what exactly is causing these issues:
1. Would it be possible to send us the save file your using here? Giving it a test ourselves and measuring what exactly is causing the drops would help us a great deal in diagnosing this.
2. How do you know the issues are caused by volcanic eruptions, underwater currents, and radiation? Do you notice the performance dropping in some specific situation, e.g. when you're watching or getting damaged by a volcanic eruption, or when you're inside a current or looking at a current on the sonar?
3. By middle part, which biome do you mean specifically? I would assume the second biome Europan Ridge (although it's not quite at the middle of the map), which has currents and volcanic eruptions?
4. Something that might also help is if you entered the command "showperf" in the debug console (which can be opened by pressing F3) and sent us a screenshot of what you see when the performance drops. Although, sending us the save file would be even better, so we could do these kinds of measurements ourselves.

But in any case, I'm sorry for the trouble and understand that bad performance in the game must be very frustrating - as it is for us as well, since we still haven't been able to pinpoint exactly what is causing such severe performance drops. I hope we can iron out these issues as soon as possible, and we're grateful for any information that might help us get to the bottom of this.
