### ISSUE TITLE
winterhalter gaping issue

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9591]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

has
![image](https://user-images.githubusercontent.com/5103517/179465824-9e5fa8f4-1026-474c-8811-e25ee3810883.png)

should be:
![image](https://user-images.githubusercontent.com/5103517/179465968-a8fb24ac-ac08-405e-8e75-76899c66d598.png)

water doesn't flow from upper hull down into the left/middle hulls on the bottom

the airlock's gap is slightly misplaced : 
![image](https://user-images.githubusercontent.com/5103517/179467022-e66bf368-7c8e-47f4-ad0e-e984e79d2111.png)

there's a couple other gaps that are a bit wider/shorter than absolute perfect but they appear pretty much correct.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/da81d4184876a5e8bd7719e0b023a3ae5a11255b

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0621ae95bcbd7cfa75e4c9f05e53d7074c51f1dc

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0

I feel this gap could be tweaked slightly (I have hidden items, it is just below a door and actually goes into the other hull, when I believe it should end at the small metal piece within the hull on the left it starts from on the platform):

![image](https://user-images.githubusercontent.com/29177976/180105491-6fe6c720-dd44-48ff-9557-73a914e9ba2b.png)

I feel this should be modified to be like this:

![image](https://user-images.githubusercontent.com/29177976/180105790-48001c95-b19f-4451-beab-51214761034a.png)

Otherwise everything seems fine and all previously mentioned issues are gone.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e2c8c8eb5e1645ca607339ef99c4db192d05074c

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/3391dc7033d5d12b9167b38a6269ffd1096e546d. works correctly, closing.
