### ISSUE TITLE
Sub editor doesn't save subs in their original folder

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9610]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

#9259 has been closed but not resolved

If you open a sub from Localmods/Submarine/Subfolder/Sub.sub and save it
The game will save it in Localmods/Submarine/Sub.sub

**Comment by ubertpendragon** [comment]
Try with this:

[New Wrecks For Barotrauma (With sellable wrecks).zip](https://github.com/Regalis11/Barotrauma/files/9150186/New.Wrecks.For.Barotrauma.With.sellable.wrecks.zip)

**Comment by Regalis11** [comment]
https://github.com/Regalis11/Barotrauma-development/commit/ed4a41bf76882a5463aee160916d5b01168ea092 did not fix this, moving back to Bugfixes

**Comment by NilanthAnimosus** [comment]
Tested against sub-saving-fix-2 commit https://github.com/Regalis11/Barotrauma-development/commit/58941145896fc7271f062831f20cf68712c3251a

Everything this sets out to fix appears to function perfectly fine, updating existing submarines that are in different locations than the root folder (such as mod/wrecks/yourwreck.sub)

However I noticed if you edit a local mod's submarine that has such a path and then proceed to use "Create a local package" it will instead update and overwrite the local mod its originally from (And not create a new/separate package of the submarine name) - though it will if you rename the submarine and then try that.

I am not sure if the above behavior is intended given it does not state "Update" but instead "Create" implying it won't save over the original.

otherwise I couldn't see any other issues with this be it new or old submarines I was saving, selecting the another package then the original and such in the list.

**Comment by Regalis11** [comment]
I had so much trouble wrapping my head around this logic and getting it to work correctly in every situation that I ended up doing a bit more extensive changes to it, see https://github.com/Regalis11/Barotrauma-development/commit/39c12933cecbfc8d24c1caac1e12c55d4b4ea0e0. 

The issue should now be fixed, but please give a thorough test on the different ways of saving the sub (creating a completely new one, adding a new one to an existing package, modifying a sub in an existing package, trying to save with a name that's already in use...)

**Comment by NilanthAnimosus** [comment]
Tested against sub-saving-fix-2 commit https://github.com/Regalis11/Barotrauma-development/commit/39c12933cecbfc8d24c1caac1e12c55d4b4ea0e0

Created a new submarine save as a new local package - went to save again and saw "Modify vanilla" (Topmost option, mind you probably only visible in debug builds) selected and "Create new local package" instead of update - the entry to "Update local package" was at the very bottom of the list and not selected by default and could very easily be missed.

may be an issue if thinking "Create local package" should be used where update used to be, which would only work if the submarine name is the same as the content package name.

I feel this option should be at the top next to "Create new local package". I also feel the content package the submarine is loaded from (if from a local package) should automatically select that content package to save to in the list, and perhaps be at the top of the list with the rest of the options.

Notes on various things I've tested with no issues to note on the path it saves to:

- Saved, saved again, loaded and saved a new submarine with no issues to a new local mod or unnecessary warnings.
- Updated a local mod's submarine fine.
- Updated a local mod's submarine with a none-root path fine (IE mods/submod/wrecks/subname.sub)
- Added a new/differently named submarine to a local mod with multiple submarines. - Even if the path was a non-root this adds it to the root of the local mod and works fine.
- loading and saving a workshop submarine under a local package or as a new local package saves correctly.
- Saving into a content package with a new submarine (not loaded from the package) of the same name gives a warning that it will overwrite an existing submarine.
- Warning for overwriting occurs even if loading the same named submarine from a different content package and attempting to save in a different package containing the same submarine.

**Comment by Regalis11** [comment]
> the entry to "Update local package" was at the very bottom of the list and not selected by default and could very easily be missed

I actually intended it to be the 1st option and selected by default, but that was bugged, should be fixed in  https://github.com/Regalis11/Barotrauma-development/commit/1bb6bcbd2a94ec3ccab0a12db8734532df320841
