### ISSUE TITLE
Humanhusk isn't showed as expected

### ISSUE THREAD

**Issue by Raven-233486** [Regalis11/Barotrauma#9611]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the editor, it go as expected.
![屏幕截图 2022-07-20 232933](https://user-images.githubusercontent.com/72175577/180022501-296f6853-673e-47d6-91c1-f8eea17f226d.png)
However, in game.
![QQ图片20220720233055](https://user-images.githubusercontent.com/72175577/180022793-4302a7ad-e774-4f0c-9eae-4abd3ae3c54d.png)
The new limb doesn't show in game, as well as the huskbeard.
Besides, the "hideotherwearablesofttype" doesn't work.
![QQ图片20220720233540](https://user-images.githubusercontent.com/72175577/180023799-8fbc1ec1-4cee-4922-bacc-0f478dd242d9.png)
In the picture you can find that its beard hasn't been hidden.

It's about how I find the bug:
 I'd want to add some facialattachment, however, it doesn't work as expected.
expected:
![QQ图片20220720233734](https://user-images.githubusercontent.com/72175577/180024264-4616272b-b7e0-4b30-bee6-3b0aee0489b6.png)
actually:
![QQ图片20220720233744](https://user-images.githubusercontent.com/72175577/180024301-2124f80b-d9c7-4c32-a09a-c88bf3f2fb47.png)
how I write:
![QQ图片20220720233842](https://user-images.githubusercontent.com/72175577/180024467-5e715da9-3bdf-4842-b157-10ed3ad6e10c.png)
Another question is, can you tell me how can I achieve the expected. Thinks a million.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not reproduce this issue. The husk sprite does seem to show up correctly on the humanhusk, and the character's beard is hidden, both in-game and in the editor:

![image](https://user-images.githubusercontent.com/14351070/180031997-0a61b66d-1aee-4071-be20-c1a11da90a8d.png)

I can't see anything wrong in the provided XML either, so I suspect the problem is somewhere else. Although, I'm not quite sure what you intend to do here - that configuration should disable the hair when those attachments are active (`hidewearablesoftype="Hair"`), and looking at the provided picture, you seem to be wanting to draw them in front of the hair? Are you sure that the sprite depths of the attachments are correct (if you want to draw them in front of the hair, they should be smaller than the hair's depth)?

**Comment by Raven-233486** [comment]
I reinstalled the game, then it fixed.
However, facialattachment still can't be showed above hairs. After 1 day's trying, I gave up.
