### ISSUE TITLE
Add In-Game Option to Change Current Output of Batteries- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#962]
As we know we have already a visible in-game percentage bar responsible for charging speed of a battery, but what about making another one responsible for how much energy it releases?

Example:
We set in a shuttle a battery with maximum output of 1000 kW to 50% output. This makes battery share a maximum of 500 kW power at the time.

Setting it to 0% disables battery from sending energy.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
