### ISSUE TITLE
Herja Fabricator UI overlapping

### ISSUE THREAD

**Issue by Dipcor** [Regalis11/Barotrauma#9626]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After using Fabricator on Herja, Fabricator interface start overlapping interface of container next to it.
As long as you don't touch Fabricator, interface of container seems to be fine.
Tested this only in multiplayer campaign.

![Barotrauma_2022 07 23-00 18](https://user-images.githubusercontent.com/109827901/180570240-4814ba87-faae-4a2e-9028-9c489137246d.png)

### Reproduction steps

1. Start multiplayer campaign on Herja
2. Use container on upper aft side next to Fabricator
3. Use Fabricator
4. Use container on upper aft side next to Fabricator again, now interface should be overlapping 

Video example
[https://youtu.be/QqjNqJ-lpSo](url)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by MaaiG** [comment]
It would seem, after all, there are not so many such windows in the game!
You can simply list their combinations and set the rules of sticking to each other depending on their number... Or rigidly set the order of windows on the screen depending on their sequential number...

But, IMHO, in any case this problem has no solution if the number of linked objects is unlimited!

https://user-images.githubusercontent.com/93348499/180603702-88f39d24-cc9e-4154-8c03-e07ce872dcae.mp4

**Comment by Krzeszny** [comment]
Good points MaaiG. 
By the way, I've always wanted to say I keep seeing a garden gnome in your profile pic :)

The main problem is that this issue happens even if one cabinet is linked, and it often makes crafting broken until the round ends. I'd give it high prio tbh.

**Comment by MaaiG** [comment]
> ...garden gnome...

Is that better? :)

**Comment by MaaiG** [comment]
> I keep seeing a garden gnome

That be better? ))
![Kitty2](https://user-images.githubusercontent.com/93348499/180967734-423cd54a-02c9-46c1-9b23-6824fd493c19.png)

**Comment by NilanthAnimosus** [comment]
As a note, this issue has already been fixed in the current unstable in issue #9032

The new draggable UI's that are coming in the next version (currently available in the unstable build) do fix this problem, but it is true that no limits on the links/containers themselves is an issue in of itself that I noted when testing the draggable UI as well. I would say you can handle around 3 or 4 containers and one deconstructor and fabricator with the upcoming changes with the option to lock/unlock UI interfaces upcoming too.

![image](https://user-images.githubusercontent.com/29177976/181486105-cc97a6b4-12a4-47bd-8ba0-db61432aef25.png)
Will be closing this issue as a duplicate, in the meantime when the UI overlaps in the current stable it is possible to "reset" the UI by using a screwdriver and opening the connection panel of the linked machine. (No rewiring needed just opening it is enough)
