### ISSUE TITLE
Question About GitHub Non-Contributor Users

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#963]
Does GitHub feature request designers and bug reporters receive the steam full version of Barotrauma at reduced price or for free if they make enough successfully accepted feature requests and report enough personal bug reports no one previously stated?

**Comment by Regalis11** [comment]
When the closed beta period starts we'll be giving Steam keys to a bunch of people who've been contributing to the project in some way. That includes people who've been active here on the issue tracker, and yes we can send a key your way too.

As a disclaimer to everyone: we'll use our own discretion to choose who gets free steam keys, and submitting a bug report or a feature request doesn't guarantee you one. So please don't start submitting stuff here just because you want a free key. :)

**Comment by rico6822** [comment]
Ok, my nickname on steam is Redeloper.
