### ISSUE TITLE
Projectile with damagedbyprojectiles="true" can't be hit by other projectile

### ISSUE THREAD

**Issue by ghostsheet** [Regalis11/Barotrauma#9637]
Projectile with `damagedbyprojectiles="true"` can't be hit by other projectile, while they're active by default.

It seems that both projectile needs to have `damagedbyprojectiles="true"`.

This means stuff like shooting down Crawler Eggs from brood mother is impossible (until they are deactivated after afew seconds).

To shoot down an active crawler egg you'd need to have your gun's projectile eg. `coilgunbolt` to have `damagedbyprojectiles="true"`,
to be able to fend off those acid crawler eggs from the broodmothers.

(PS)
I've only found this bug while making a mod for depth charges that can be shot down.

**Comment by itchyOwl** [comment]
I don't think Regalis11/Barotrauma-development#3495 addresses this, but it should be addressed in Regalis11/Barotrauma-development@1383a13 instead. Disconnecting the issue.

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/ef3d676b9c7ab5c712f358dfc21327f5cdf21bd9

Originally tried to test on release but launching a depth charge caused a crash that is fixed in bugfixes.

However I cannot hit projectiles such as depth charges with both railguns and chainguns (hitscan and projectile). the shots simply pass through it until it is say, picked up and dropped which then a health bar appears and the shell is deflected around.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@f3f08c9.
