### ISSUE TITLE
Tinkering/Bandolier doesn't increase pulse laser fire rate

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9663]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Tinkering/Bandolier doesn't seem to increase pulse laser fire rate
It's very noticeable on other  guns.

_So apparently what dictates the pulse laser fire rate is actually "charge rate" which can be increased by [Optimized Power Flow
](https://barotraumagame.com/wiki/Optimized_Power-Flow). This still strikes me as a bug, marginally increasing the chaingun spinup and only affecting the laser fire rate seems too niche and you'd expect "fire rate" to affect the laser regardless_

### Reproduction steps

1. Load Barsuk
2. Equip a bandolier on captain
3. Give tinkering talent to mechanic
4. Tinker the laser loader
5. Shoot with the captain

### Version

0.18.15.0

**Comment by Regalis11** [comment]
I think the issue here is that the pulse laser isn't limited by the "reload" time, but the "charge up" time which tinkering/bandolier don't affect. We're planning on replacing tinkering with other types of effects in the upcoming talent rework, so I don't think we'll be addressing this.

**Comment by bookslayer10** [comment]
This problem still affects bandoliers on the public unstable branch as of September 10th 2023, making them have no effect when firing a pulse laser. It makes the bandolier item significantly less valuable to certain submarines without any indication beforehand that this is the case. Is this still not regarded as an issue? If this isn't going to be fixed, then what about simply changing the description of the bandolier to mention it not affecting pulse laser charge rate. (At the same time clarify the bandolier actually buffs firing rate in the first place, because the description of the item doesn't make that fact obvious.)
