### ISSUE TITLE
Captain talent Traveling Tradesman bug

### ISSUE THREAD

**Issue by Instant2116** [Regalis11/Barotrauma#9674]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Single player. After finishing mission Mopping Jack have got one more captain, old one has Traveling Tradesman that add 4 more special sales in merchants, but with new crew member merchants don't offer additional sales even after second captain have got Traveling Tradesman.

### Reproduction steps

1. Start single player.
2. Give captain Traveling Tradesman talent.
3. Get and complete mopping jack mission.
4. Check special sales.
5. Give second captain Traveling Tradesman talent.
6. 4. Check special sales.

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I wouldn't actually consider this a bug. The talent doesn't state that the special sales appear in the stores immediately: the specials are created after each round, so you should see them when you reach the next outpost.

Even though this could be considered a little misleading, I don't think we will be addressing it at least for now, since we're reworking the talents and most likely getting rid of this one.
