### ISSUE TITLE
No optimization

### ISSUE THREAD

**Issue by WOLFPACKH** [Regalis11/Barotrauma#9682]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You killed optimization. FPS is Normal but i have a realy bad ping in SINGLEPLAYER CAMPAIGN! Ping - its a big delay from action to character response and i'm stuck in the level because I'm always dying. And I'm not the only one with these problems! My friends with top PC too. Earlier with older versions, there were no such problems. We can't continue the normal game and playing the campaign. Please fix the optimization or do something... please.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

We are aware of and working on addressing the performance problems, and there are several existing tickets about them. Please see this trello ticket for some more info and guidelines on what kind of information might help us address the problems: https://trello.com/c/hmCsrwdz/431-performance-issues-since-spring-2022
