### ISSUE TITLE
Reactor Temprature bar doesn't give appropriate information

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#9709]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Even when reactor says "Low Temp" actually is not

### Reproduction steps

1Start Reactor
2Enable auto
3Make big load for reactor
4See, that reactor low on temp, but works as always

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not reproduce the issue: the temperature warning only seems to light up when the temperature is below the optimal range (indicated by the red arrows on the temperature bar). Do you mean that the problem is the reactor works even though the temperature is below the optimal range? That's not exactly a bug, even though maybe somewhat confusing: it is possible to run the reactor at a too low or too high temperature, although only up to a certain point (a much too low temperature will make the output drop, a too high temperature may cause it to catch fire or explode).

**Comment by Abkim27** [comment]
Yes, i say about reactor works, even when below optimal range of temprature, i think it's too confusing, there is a needed optimal range, so there is no need for making that optimal bar bigger inperceptibly. If needed, just make visible optimal bar bigger

**Comment by Krzeszny** [comment]
Abkim is talking about underclocking. 
The reactor functions fine at 75% of optimal temperature and most things on the sub still work below the required voltage, down to 50% voltage (but things like engine or pumps are slower at lower voltage). 

This 75% temperature value is used in most reactor controllers on the Steam Workshop, so I'd advise against changing the values because it adds engaging ways to optimize reactors. However, the UI bar itself could be tweaked, along with the LOW TEMPERATURE indicator.

**Comment by Krzeszny** [comment]
Related reactor suggestion: https://github.com/Regalis11/Barotrauma/discussions/8702
