### ISSUE TITLE
Unable to use Pre-Purchased Submarine in Solo-Campaign and Multiplayer-Campaign

### ISSUE THREAD

**Issue by SirNightKnight** [Regalis11/Barotrauma#9746]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Purchasing a submarine without switching in either a solo or multiplayer campaign game will cause the purchased submarine to disappear from the shipyard UI and all following instances of the UI afterwards. Not sure if this would contribute, but I did use cheats to give the player 999,999mk to be able to purchase the submarines when testing.

### Reproduction steps

1. Load up a multiplayer or solo campaign game
3. Purchase a submarine from an outpost without "Purchase and Switch"
4. Submarine will disappear from the UI and you will be unable to switch to the submarine

### Bug prevalence

Happens every time I play

### Version

0.19.1.0 (unstable)

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
This is actually intentional. The shipyard UI lists submarines available for purchase - submarines you've already purchased are no longer available. You can switch between the submarines you've purchased on the submarine switch terminal next to the outpost's airlock.

I added a mention of the terminal to the message box in https://github.com/Regalis11/Barotrauma-development/commit/f82a333e436d97a8051448f960194e41892e9be5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
