### ISSUE TITLE
endless spawning of boxes with purchases

### ISSUE THREAD

**Issue by Ayeeooo** [Regalis11/Barotrauma#9755]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

every time you buy an item at the stations, a new crate with those items will spawn in the submarine. After 10 stations, the entire submarine is crammed with boxes, they do not disappear anywhere. Maybe that's how it's meant to be, but it annoys me.

### Reproduction steps

1. land at the station
2. Buy any item. A crate with these items will appear
3. Sail to another station
4. repeat several times 1-3
![image](https://user-images.githubusercontent.com/111947716/186328606-5c916d4f-7c30-475a-a243-d263e079dc53.png)

### Bug prevalence

Happens regularly

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by LePiromano** [comment]
this is intended but i also agree that it can get a bit annoying, but there's no other easy way for getting crates since you can't craft or buy crates, just do a bit of maintenance

**Comment by gerakis** [comment]
You can throw them into the deconstructor to get rid of them. You dont seem to get anything from them any more though. :(

**Comment by NilanthAnimosus** [comment]
Not sure what the best approach is for this, I can understand this on a submarine that has no deconstructor at least these boxes just piling up until you ditch them in the ocean or on the next outpost you visit as garbage. you can throw three empty crates into a deconstructor as a way to remove them as you travel/play normally though at least (that is what I tend to do in this case).

There is other questions to be had with this, such as placing items where players may not want to have them placed (IE. if you place into an existing metal crate, that might be a players box of items they wish to sell at an outpost or deconstruct later as example). Placing them into various containers over the submarine may also be more irritating than at a central location at a cargo point in your submarine in crates.

currently, it just places the items into disposable crates that give no advantage nor cause further headache than sorting the crates out oneself. If there is a better way you think to handle this it may be worth mentioning but I think this has actually been the intended way given the above alternatives are potentially annoying in their own rights.

**Comment by Krzeszny** [comment]
Right now I can think of 3 potential solutions:
1. Make crates work like Duffle bags (which was a horrible idea in the first place, as making Duffle bags self-deconstruct limits item transport to crates in Vanilla, making wreck salvage tedious)
2. Make crates disappear but only when they're empty
**3**. Place items into existing crates of the required type that aren't contained, or ones that are contained but _not_ in a Deconstructor. I can't imagine any downsides.

**Comment by NilanthAnimosus** [comment]
Crates in deconstructor's would deconstruct the crate - not its contents. so its not a normal place for them to go anyways and is essentially "Contained".

players may just put recently bought items crates into a crate shelf instead of the floor then have the "Too many crates" again. or simply take a very old purchased crate out, leave it on the floor when its their goto crate and find its filled when they didn't want it to be (maybe its their salvage crate for wrecks). Don't think its the best idea to try to keep track of certain crates or unanimously make an identifier/tag of crates take the cargo specifically.

Downsides of items in contained crates is they may be sorted manually by players, and having store bought goods placed into them (IE. a submarine with few containers that has some mod to purchase crate shelves and they use that to store things, having your store bought items thrown into those automatically could be considered a major irritation than benefit).

just personal thoughts on this really, but player intention and what will and won't cause irritation to players is difficult to work out from just a single view alone on it. I would be more for less pointless crates that take up energy deconstructing or manual trips to remove from the submarine on each shopping trip at least, given currently it just adds extra work. though changing it may just annoy another crowd of players on how they play the game, sort their submarine etc.

**Comment by mygamingaccount** [comment]
On the sub with no deconstructor you already have to learn deal with trash like empty ammoboxes, usually by throwing it overboard or leaving it at stations.

Never thought these crates are an issue, and I've never heard anyone complain for having to deconstruct them.

**Comment by itchyOwl** [comment]
Implemented in #3871. Old containers are now reused, but only when they are in the cargo bay.

**Comment by Regalis11** [comment]
Tested, couldn't find any issues. Closing.
