### ISSUE TITLE
Mysterious Decorativesprite disappearance inside containers

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9781]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When put inside a container, the Decorativesprite will disappear entirely

Decorativesprite is the casing, there's one Brokensprite for each individual status

![image](https://user-images.githubusercontent.com/73229309/187071378-af1303bc-386f-4e3b-aee3-fb9971a7aa94.png)

![image](https://user-images.githubusercontent.com/73229309/187063383-2fbbaa1f-19aa-49ad-b7e1-91d92e1d6cb9.png)

I've tried removing the brokensprite, I've tried changing a lot of parameters, inserted it into many different containers to no avail. 
The decorativesprite just disappears 🤔 

You can see this doesn't happen with a pseudo weapon holder also using decorative and broken sprites
![image](https://user-images.githubusercontent.com/73229309/187064468-5b787f13-2084-40aa-8a02-7c87d11d2db8.png)

_I'll post the zip of the mod when Github allows me to_ 
https://drive.google.com/file/d/1IT-xbRb6hMJvVHB-iEN8XZGVJIBbqMNk/view?usp=sharing

### Version

0.19.2.0 (unstable)

**Comment by Regalis11** [comment]
It seems this is just something that hasn't been implemented: when the item is in a container, its sprite is just drawn by the container, instead of gong through the "full" rendering logic involving the decorative sprites, broken sprites and such. The reason why the weapon holder works is that it's a "static" item with no physics body, which behave a little differently when contained (something that should normally never happen - it doesn't make sense to put a static item in an inventory or a container).

**Comment by ubertpendragon** [comment]
>  instead of gong through the "full" rendering logic involving the decorative sprites, broken sprites and such

Oddly enough, Brokensprite works, you can see the "ammo" count go down, in the second picture. Only Decorativesprite doesn't. Probably because Brokensprite replaces the sprite entirely instead of adding a layer onto it

**Comment by ubertpendragon** [comment]
I'm updating this due to new findings:

**Decorativesprite would allow "dynamic" looking ammo boxes with a relatively small sprite print.**

By using a "casing" sprite as Decorativesprite and a single "ammo" sprite that changes with brokensprite, you can simply slide the sourcerect in a direction to make it seem like the ammunition is decreasing, one bullet at a time.
![image](https://user-images.githubusercontent.com/73229309/188504032-524ddf18-61d0-403b-9c7a-3291300ed05d.png)

![image](https://user-images.githubusercontent.com/73229309/188503913-4867525f-40a5-456b-bac6-971524b9c43e.png)

**Comment by Regalis11** [comment]
Bumping this up in priority because it affects some new vanilla items coming up in a future update.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4590/commits/8e4f8afdb5bc15038c95e65e4773909cc0d77483

Old test mod gives error now when placing flakcanisterloader:
`Item "flakcanisterloader" has a ConnectionPanel component, but cannot be wired because it has an active physics body that cannot be attached to a wall. Remove the physics body or add a Holdable component with the Attachable attribute set to true.`

FlakShell seems to mostly work on important parts.

Not going to close this yet if @ubertpendragon want's recreate original mod.

**Comment by ubertpendragon** [comment]
This was just proof of concept for ammunition containers to display their contents inside inventories, the actual mod doesnt really matter 👍

**Comment by Jasontti** [comment]
It did seem to work on flakshell.

I'll close the ticket then.
