### ISSUE TITLE
[Suggestion] Monster

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#984]
I have a suggestion for a new type of monster, for Barotrauma.

My monster will function pretty simply, when lone divers are swimming around the ocean (these creatures are mildly afraid of big ships or shuttles) the player will hear a sort of chirping sound. Soon after that the monster (I want it to look as nasty and disgusting as possible) will come out from the dark and rush at you.

This is where the fun starts, as this monster is pretty weak and takes two hits with a crowbar to kill. But the fact is that these little monsters attack in big, big, big swarms. I'm talking in numbers of 8-16 (these monsters would be the size of two of the player character's legs in length, preferably looking like a snake or leech). Anyways in these hordes, the monster will cooperate in dragging you down, down and down, all the way to the abyss. First they'll go for the legs, but sometimes (20% chance per 16 of these monsters) they'll cling on to your head so you won't be able to see at all, or 40% chance per 16 of these that they'll attach to your arms so your inventory will be disabled. The player will have to either try and swim away (only if the shuttle is close, otherwise it is no use) or escape using a water scooter, but then again, these creatures will cooperate and probably surround you from each side. Otherwise you're fucked, unless you manage to kill all of them (grenade) or get them one by one (using other weapons). Other than that, they will drag you to the abyss at the speed of a water scooter, but will not actually make you bleed or harm you in any other way.

**Comment by etet2** [comment]
really cool idea

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
