### ISSUE TITLE
[Suggestion] Monster 2

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#985]
Regalis/Juan, I have yet another idea.

This next monster is the underwater "spider-like" creature known as "Collud".

I think if this monster comes to life this game will be the scariest coop game known to man.

So this creature is approximately 1.5 times bigger than the moloch.

It usually lives near tight fits where submarines have to be careful not to ram into walls.

It uses its super strong silk (obtained from the food it eats, most specifically young charybdises). This spider like creature will form gigantic webs used for ensnaring prey (like humans, shuttles (this beast will be a huge problem for shuttles, therefore I suggest shuttles come with plasma cutters for tearing down the web), and gigantic ships like the aegir). Depending on who gets ensnared in it, this is how it plays out.

Human - No way out of this one, you're firmly ensnared in this web as you wait for the blind spider to come and slowly suck out your intestines.

Shuttle - This is a big impact, the spider will definitely notice it, and it will most likely arrive within the timespan of 2 minutes (tension and pressure, yee haw) after which when it arrives, it'll start scewering holes into the shuttle and basically stabbing people through with it's legs. The humans will have to have a volunteer quickly exit the shuttle in a diving suit, cut the web away with their plasma cutter (the web is durable so it might take about 25 seconds to fully cut away all the web and free the submarine). After the person has to get back in and get the fuck outta there! If a person is caught cutting webs by the spider, the spider will pull the person into the web to trap them, after which it will start piercing the sub as previously mentioned, after which it will slowly devour the person.

Submarine - Depending at what speed you're going at, you might be able to ram through the web (the sub must be at top speed, and even then there will be rng to determine a mere 40% chance the sub will break through at top speed). Otherwise the spider will definitely come fast, but this time the crew is not that helpless. It can shoot through the web with the railgun and all that nice stuff. But this time the spider will be most cunning, as it will encircle the sub with its web, blocking up windows  and breaking railguns. After this the sub will go back to piercing holes into the sub.

Yim-Yum!

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
