### ISSUE TITLE
Barotrauma keeps duplicates of workshop mods in AppData

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9857]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

There are 2 locations where Barotrauma keeps workshop mods on my system:

The folder C:\Users\krzes\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed
takes 4.42 GB
The folder E:\SteamLibrary\steamapps\workshop\content\602960
takes 4.34 GB

I understand that the extra 80 MB in AppData is my local mods, but why are mods even kept there?
Firstly, there's the folder LocalMods. Why use AppData for the same thing?
Secondly, if AppData isn't used anymore, it should've been cleaned up by the game.

![explorer_5Q4sYWkEvI](https://user-images.githubusercontent.com/10529134/189486671-88ed9d77-82db-4dee-a183-639467bae6d4.png)

### Bug prevalence

Happens since April 20th

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional. The mods in the Steam installation folder are managed by Steam, and when you enable one, the game creates a copy of it in AppData. If we didn't do this, and just used the mods directly from the Steam folder, you would have no control over when the mods update.

>Firstly, there's the folder LocalMods. Why use AppData for the same thing?

They are not used for the same thing: LocalMods is a place for your own mods (that you might be expected to edit), AppData is for ones installed from the Workshop ("hidden" in AppData, outside the game folder to make it less likely for anyone to try editing them, which would easily lead to the local changes getting overwritten by Steam).

**Comment by Krzeszny** [comment]
> This is intentional. The mods in the Steam installation folder are managed by Steam, and when you enable one, the game creates a copy of it in AppData. If we didn't do this, and just used the mods directly from the Steam folder, you would have no control over when the mods update.
I see. Then this is what creates a problem for some players. If a player hasn't played for a few weeks, there are so many mods that need updating that the player must wait for several minutes.
There could be an option to always keep the mods updated (load them from the workshop folder) to remove the need for manual updates in the Settings menu.
