### ISSUE TITLE
Randomize subs in combat missions

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#987]
In the sub vs sub missions, the submarine that each team gets is randomized

**Comment by BillCombs** [comment]
It would be great if sub vs sub could let you choose what sub and team you want to be on, so one group of friends could fight against other one instead of having random players as teammates. Groups of people could make their own subs and then compete to find out who's sub and team is better. Competitive barotrauma matches, that might be a fun sight to see.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
