### ISSUE TITLE
[Dev Version] Medication Overhaul

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#988]
I suggest that the names of the chemicals themselves change, so that low skilled workers wouldn't be able to memorize the description of the drug itself, so when someone has low medical skill the drugs they use would have random names.

**Comment by BillCombs** [comment]
Probably related to #982.

 I am pretty sure if a crew of trained professionals was about to go on a deadly mission without a doctor, knowing that they would very likely get hurt during it, they would check the meds they have in stock and at least try to understand the basics of using them.


 In my opinion, games should have something that rewards players who have a lot of experience in it. Having trouble with meds when not playing as a doctor despite all of the time and effort you put in the game might make it less motivating to spend any effort to get better at the game.
 It's fun to learn new things, to train your memory. Taking it away makes gameplay more repetitive.  When you know everything you could learn, your playstyle rarely changes. But when you are learning new things, your playstyle changes according to the things you have learned. Every time you find something new, you are able to do more things, to push boundaries of the game a bit further, and explore deeper parts of the game.

As i said in #982, i think that doctors should be better in some other way. Perhaps having better effects from meds, since they likely have more experience in actually using them, instead of just reading their description.

**Comment by Regalis11** [comment]
The comment I made in #982 applies to this too. We're been trying to design the skill system in a way that any character can do anything regardless of their class, just less effectively if their skill level is low. This change would make it nearly impossible for anyone except the doctors to apply medical treatments and I don't think we should go that far.
