### ISSUE TITLE
Med overhaul [dev version] part 2 electric boogaloo

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#989]
Syringes don't actually have colourful liquid in them, in fact, they all look the same.

To confuse non-doctors even more, remove all colour from syringes.

This is good as it prevents the crew from hogging all the medicine, and is overall more realistic unlike the current game in which I basically horde, along with others, medical supplies.

**Comment by etet2** [comment]
syringes are getting removed in dev. all medicine will be in pill or any other form that just needs straight aplication and not a syringe.

**Comment by Regalis11** [comment]
Yeah, syringes are not going to be used in the dev version. We decided to get rid of them because we felt loading drugs into syringes was just an unnecessary, annoying extra step when applying treatments.

The comments I made to #982 and #988 also apply to this, we don't want to make non-doctors completely unable to use medical items.
