### ISSUE TITLE
Power flowback on supercapacitors is misleading and affects vanilla ships

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9899]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So, we've seen https://github.com/Regalis11/Barotrauma/issues/9195 that power can flow back and "bounce" between turrets

This picture shows that despite different wiring, in both cases the railgun uses the power of two supercaps instead of one. Any other gun that would otherwise be separately wired to a single of these supercaps will also benefit from both
![image](https://user-images.githubusercontent.com/73229309/191252641-4f43343c-7079-4ede-bfbc-72d0d747d088.png)

**1. The flowback is poorly communicated**

Despite this flowback being "intended", Supercaps have a POWER_OUT pin, turrets/EDC have a POWER_IN pin, despite both of those pins working like a Junction Box "POWER" pin. There is no way for a sub builder to know about the flowback works, and the game even misleads players (see 2.). This also throws off balance attempts as sub builders may not even know that they're inadvertedly merging several supercaps

**2. Turrets will only still display one supercap bar and won't fire if it's empty**

Like in the picture, if you have 2 supercaps wired by bounceback, the railgun will only display supercap 1's power, and fire if supercap 1 has enough power despite actually dividing the cost between 1 and 2. This is misleading sub builders into believing that only direct wiring is in effect.
Only uses half the power show on the bar, but not actually enough %
![image](https://user-images.githubusercontent.com/73229309/191261353-756ec6db-e3a5-4821-a550-1389f7f4fdd9.png)
Both supercaps wired shows the proper minimum %
![image](https://user-images.githubusercontent.com/73229309/191261825-4c177682-6ccc-4a80-a79a-80417e7c5fab.png)

**3. Vanilla subs have not been updated with this flowback in mind**

Considering the following: 
_If you want to avoid flowback, it's fine to have a supercap wired to several turrets, but not a turret wired to several supercaps_

Of all the vanilla subs, these have unintended power flowback issues:

**Berilia** (big guns through coilguns/EDC)
**Dugong** (turret hardpoint through guns)
**Kastrull** (bottom coilgun/hardpoint through everything else)
**Orca** (coilguns through EDC)
**Remora** (all guns through EDC)
**Typhon** (all guns through EDC)
**Typhon2** (all guns through EDC)
**Winterhalter** (all guns through EDC)

Only the Orca2 and Herja have, by design, ALL of their turrets/EDC wired to ALL supercaps

Combined with an already low power consumption on guns, you can plow through enemy waves unconcerned by power, never using the freshly coded 100% supercap mechanic even if you didn't intend to https://github.com/Regalis11/Barotrauma/issues/9620

**Comment by Regalis11** [comment]
Thank you for the in-depth description of the problems this caused. Based on the previous reports about this I'd just dismissed it as an insignificant drawback of the new power logic (which we were aware of and [discussed in the PR](https://github.com/Regalis11/Barotrauma/pull/8184)), but these examples really hit home how unintuitive this behavior is.

Luckily it turned out addressing this didn't require that extensive changes to the power logic, because the turrets (and EDCs) don't even use the "normal" power propagation logic, but instead pull the charge directly and instantaneously from the batteries. 

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b12454da5e79414e3968f2de2c573634a6f16172

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/373b429eaed92741b3dd4dd58397917e06ad8647, no issues found, closing.

Notes:
mainly tested on berillia which had 2 wires to coilguns (intentional sharing of super capacitors) and two to the top EDC while the flak cannon had only one super capacitor connected to it.

The flak cannon could only draw power from one of the super capacitors, once depleted it could not draw more. the coilguns and top EDC did draw from two super capacitors as expected.

I had charged them up fully (then disabled their recharging) and completely discharged them for these tests to make sure they were only drawing from one or both as they should do.
