### ISSUE TITLE
Add speech bubbles above players who are typing messages in chat

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#991]
This would eliminate the awkward standoffs between players where you're not sure whether the other person is just tying a long response or is  busy putting some husk eggs in his syringe.

**Comment by thegrb93** [comment]
The awkward standoffs are great though. Good tension

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
