### ISSUE TITLE
Main menu improvements

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9912]
Polish pass of some sort for the main menu for full release.

This was also requested by the publisher, they feel this would be a good way to make players or people watching streams/videos go "ok this is new" as soon as the game starts.

Could also consider improving the loading screen visuals while we're at it?

**Comment by LePiromano** [comment]
maybe the game could alternate between different main menu screens every time you open it

**Comment by AlanGuardsman** [comment]
i think it would be nice to make some kind of presets for interface style - put in some vanilla ones like standart current one and then give people an ability to make and pick their own styles (kinda like skins in osu or background style in hollow knight)

**Comment by Tsunder** [comment]
Initial game loading screen should go to main menu once game is loaded, rather than require an additional mouse click (I didn't understand the UI code when I tried in #8443 )

"steam workshop" label should just be "mods", since local/non-steam mods are there too.

can keyboard even be used to traverse main menu?

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #3578](https://github.com/Regalis11/Barotrauma-development/issues/3578) via [**Zenhub**](https://www.zenhub.com/)
