### ISSUE TITLE
Add an option to randomize item spawns in the sub editor

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#994]
Speaking from a view of a person, who has no idea how complicated this can be, and how many problems this could create. Just saying what part of the gameplay could have some improvement and what could be done for it. Since you are the one doing all the work, it's up to you to decide if it's worth the effort.

 Players tend to often chose subs they like and know instead of trying something new, which leads to people voting for the same sub, learning the spots where the best items are and then just playing the game of who-gets-to-the-good-items-first, making the beginning of each round the same boring routine.
 It is also hard to play as a traitor on a well known sub, since if you go to a well known spot to get a dangerous item, players would immediately realize that you took it once they saw you going away from the spot and the item not being there.

 Imagine if you could add a random factor to the items you put in your submarine, giving them different chances to spawn(would also be nice to make them depend on each other, so you could make some spots spawn different items but never all of them at same time).
 With this, players wouldn't be able to immediately learn all the item spots(unless they just look it up in the sub editor) and would be more encouraged to walk around the submarine trying to find something good. Players, who tend to race to the best item spot, would have to spread around the sub more, since different spots of the sub would have chances of spawning the items they need. 
 And, knowing about the random, players would have a harder time trying to accuse somebody of being a traitor based on the dangerous item not being on the spot, since it just could have a chance to not spawn that time.
 Bonus points if you add an option to randomize assemblies, making it possible to have entire sections of subs be different each round.

Overall this would make gameplay a lot more diverse, making players have to think of new plans and work depending on the equipment they get, instead of them having the same preset of actions every time.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
