### ISSUE TITLE
[Dev build] Can't edit humans with the new content packs

### ISSUE THREAD

**Issue by ScarletScythe** [Regalis11/Barotrauma#998]
I tried to change human sprites and their stats in their xml in my content pack, and the game assumes they're another creature so they don't work at all in the game, yet they show up fine in the character editor.

I'm assuming this is a bug, rather than just modded humans aren't supposed to work yet.

**Comment by itchyOwl** [comment]
Could you attach the modified xml here? It's a bit difficult to say anything with so little information. But editing characters (also human) should be possible.

If you change the filenames, the files should be added into the content package. If you merely change the texture paths, it should work, but the source rects and the origins would most likely be off.

It won't work (currently) if the species name does not match the config file name and the ragdoll + animation files. That's why we are building the wizard, but it's barely functional (yet it barely is).

Notice also that for the release builds, editing the vanilla content in the character editor is disabled, so that people don't accidentally create miss-matching versions of their content, which would not allow them to play together in multiplayer.

**Comment by itchyOwl** [comment]
Great, I updated my initial comment with some more specific info. Hope that it helps!
