### ISSUE TITLE
kinetic ammo does not work

### ISSUE THREAD

**Issue by NomCarver01** [Regalis11/Barotrauma#9984]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

when using any turret, the ammo just falls down and doesn't work properly.
![image](https://user-images.githubusercontent.com/115100377/194111416-6976986e-7c9c-4567-b5ed-72cc99f7ccb8.png)

### Reproduction steps

1. open a single player save file
2. use a periscope and fire your gun
3.  observe how the ammo falls down

### Bug prevalence

Happens every time I play

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I think this is caused by the recent change to the launch impulses:
`Added DamageMultiplier and LaunchImpulse to Turret. LaunchImpulse is now defined on turrets instead of ammunition (total impulse is the sum of turret + ammunition).`

It should be possible to fix this by increasing the launch impulse of the turret. Sorry for the inconvenience!

**Comment by Nikolasg05** [comment]
Happens for me as well. tried using the chaingun on a different save and its the same way, except the projectiles stay suspended rather than just falling into nothing.
